### ISSUE TITLE
ENH: Index StringMethods should return MultiIndex when result dimension is more than one

### ISSUE THREAD

**Issue by mortada** [pydata/pandas#10008]
Currently the `Index.str` methods only support returning `Index` results. However, analogous to the expansion from `Series.str.*` -> `DataFrame`, we should be able to do `Index.str.*` -> `MultiIndex` in certain cases, as discussed in https://github.com/pydata/pandas/pull/9870#issuecomment-92416184 

Some of the string methods that can support this are: `str.get_dummies`, `str.extract`, `str.split`

- [x] ``split`` (#10085)
- [x] ``rsplit`` (#10303)
- [x] ``partition`` / ``rpartition`` (#9773)
- [x] ``extract`` (#11386, only supports one group )
- [ ] ``extractall`` (not implemented in Index)
- [x] ``get_dummies`` (#12842)

Here are the related PRs: https://github.com/pydata/pandas/pull/9667, https://github.com/pydata/pandas/pull/9843, https://github.com/pydata/pandas/pull/9870, https://github.com/pydata/pandas/pull/9985

**Comment by sinhrks** [comment]
I should have comment here... #9773 is going to have a general logic for ``expand``. I've commented #9870 to organize affected methods.

**Comment by sinhrks** [comment]
I understand current status is:

- [ ] ``split`` (#10085)
- [x] ``partition`` / ``rpartition`` (#9773)
- [ ] extract
- [ ] get_dummies

**Comment by sinhrks** [comment]
``Index.str.extractall`` raises ``AttributeError``. Just fix and close.

```
idx = pd.Index(["a1a2", "b1", "c1"], ["A", "B", "C"])
idx.str.extractall("[ab](?P<digit>\d)")
# AttributeError: 'Index' object has no attribute 'iteritems'
```

CC: @tdhock

**Comment by jreback** [comment]
thanks @sinhrks
