### ISSUE TITLE
BUG: Inconsistency in converting Series to Dataframe when columns specified

### ISSUE THREAD

**Issue by artemyk** [pydata/pandas#10006]
The dtypes don't match:
```
In [16]: pd.DataFrame(pd.Series([], dtype="int64"), columns=["D"]).dtypes
Out[16]: 
D    object
dtype: object

In [17]: pd.DataFrame(pd.Series([], dtype="int64")).dtypes
Out[17]: 
0    int64
dtype: object
```

This came up in #9983 .

When this is fixed, the `check_dtype` flag should also be removed in `TestDataFrame.test_mode` in `pandas/tests/test_frame.py` .

**Comment by TomAugspurger** [comment]
Maybe related: https://github.com/pydata/pandas/issues/10006

Haven't looked closely but they sound similar. I can't remember where I was at on that PR

**Comment by artemyk** [comment]
@TomAugspurger I think you meant a different PR ;-)

**Comment by TomAugspurger** [comment]
:laughing: https://github.com/pydata/pandas/pull/9237 is the one

**Comment by artemyk** [comment]
#9237 looks relevant indeed.  Perhaps this case could also be tested/fixed in there?

**Comment by TomAugspurger** [comment]
Probably. Does your PR in https://github.com/pydata/pandas/pull/9983 depend on this being fixed?

**Comment by artemyk** [comment]
I would say not. In #9983 we are adding an extra `check_dtype=False` in `pandas/tests/test_frame.py` to get around this issue, but that can be removed in the commit for #9237 .  @jreback -- thoughts?

**Comment by jreback** [comment]
no this is independent

**Comment by jreback** [comment]
actually this is not a bug; #9983 maybe will address the 'issue'. But this is correct. Passing ``columns`` reindexes the frame; since the Series is is not named (well it actually is de-facto named 0), it is effectively removed, and thus the dtype is ``object`` which is correct.

Pls remove the comment in the original issue w.r.t. to this.

**Comment by jreback** [comment]
sorry meant #9237
