### ISSUE TITLE
assert_almost_equal fails with KeyError on non-integer column names

### ISSUE THREAD

**Issue by dhj-io** [pydata/pandas#10013]
import pandas as pd

    df = pd.DataFrame(0:'b', index = ['c'])
    pd.util.testing.assert_almost_equal(df, df)  # SUCCESS

    df = pd.DataFrame({'a':'b'}, index = ['c'])
    pd.util.testing.assert_almost_equal(df, df)  # FAIL KeyError

Top of the trace stack is:
* pandas\hashtable.pyd in pandas.hashtable.PyObjectHashTable.get_item (pandas\hashtable.c:12310)()
* pandas\hashtable.pyd in pandas.hashtable.PyObjectHashTable.get_item (pandas\hashtable.c:12261)()
* KeyError: 0

I am sure this used to work without any problem, because I have unit tests that depend on it.

I tried uninstalling and re-installing pandas and the bug is still present.

I couldn't find a similar bug searching for get_item, assert_almost_equal or hashtable.

**Comment by jreback** [comment]
This is not in the spec to work at all, and may accidently work. ``assert_almost_equal`` essentially is a recursive list-like/scalar comparator. Doesn't know about anything else.

use ``assert_frame_equal`` for testing or ``.equals(..)`` is the full-fledged method on pandas objects.

**Comment by dhj-io** [comment]
Thank you for the quick feedback!  Just a few things:

1. Can you direct me to the spec?  I wasn't able to find any documentation on pandas.util.testing.assert_almost_equal and the python "help(assert_almost_equal)" is as follows: `assert_almost_equal(...)`

2. Is the function supposed to be only for **Series** objects with floating point values?  If **DataFrames** containing only floating point numbers are supposed to be evaluated then the **same error** occurs with a floating point number substituted for 'b'.

3.  Previous behavior (this may have been as early as 0.6), was to compare equality by python standard except for floating point columns.  These columns assumed the behavior of `numpy.testing.assert_almost_equal`.  The `numpy.testing.assert_almost_equal` function allows precision to be specified in decimal places.  Is there a testing function with this behavior to compare everything normally except specify precision when comparing floating point numbers?  `assert_frame_equal` with `check_less_precise` looks promising, but that is a boolean specification and not a "number of decimal points" specification.

4. If a test function with the assert_almost_equal behavior applying only to float comparisons doesn't exist then I will need to write one for myself (in python).  I can send a pull request if it might be of use to others.

**Comment by jreback** [comment]
@dhj-io these are internal functions that we use for testing, no spec per se. you should use ``.equals`` if you are comparing things.

**Comment by jorisvandenbossche** [comment]
@dhj-io See also the issue at #9895 on providing some of the testing functions in a public `testing` module. 
Feedback on which functions you would use/find useful is certainly welcome over there!

And if you want to know the exact behaviour of `assert_almost_equal`, I think there is only the code :-) https://github.com/pydata/pandas/blob/master/pandas/src/testing.pyx#L58 (no docstring alas) But as you will see, `assert_almost_equal` is not meant to work with dataframes (it may have worked before y accident), so will probably not be part of a public testing module. 
But if `assert_frame_equal` is lacking in some ways for the precision issues, you can certainly provide some feedback/ideas on the issue.
