### ISSUE TITLE
support for 3d scatter plot if both axes are numerical values

### ISSUE THREAD

**Issue by denfromufa** [pydata/pandas#10019]

**Comment by jreback** [comment]
we are not adding additional plot support endemic to pandas. you can use ``matplotlib``, ``seaborn``, and ``bokeh`` to extend

**Comment by denfromufa** [comment]
FYI, only matplotlib has built-in support for 3d plots out of listed, but not aware of pandas in its API.

**Comment by jreback** [comment]
you can simply pass in the data like any other matplotlib function.

http://pandas.pydata.org/pandas-docs/stable/visualization.html#plotting-directly-with-matplotlib

**Comment by orena1** [comment]
Why not add built-in support?
