### ISSUE TITLE
Issue writing Dataframe to SQL Server Full+

### ISSUE THREAD

**Issue by vadoverde** [pydata/pandas#10011]
I've seen many developers post about incredible slowness when writing pandas dataframe to a SQL Server table. Some people labeled the issue "chunk size doesn't work" or "data incompatibility slowness" and what not. After a lengthy research I found the following explanation from SQLAlchemy:

http://docs.sqlalchemy.org/en/rel_0_8/faq.html#i-m-inserting-400-000-rows-with-the-orm-and-it-s-really-slow

Briefly, I believe Dataframe.to_sql() method is using SQLAlchemy ORM which uses the Unit of Work method and ends up performing row maintenance work upon insertion of every row of the dataframe. This issue can be resolved if to_sql uses SQLAlchemy CORE instead (link above). Is there a workaround for using Dataframe.to_sql() with SQL Server (not lite) with acceptable performance? I'm really trying all I can to avoid exporting the dataframe to a file and import it to SQL with an SSIS package.

Thanks,
Sam

**Comment by jorisvandenbossche** [comment]
@vadoverde Thanks for looking into this! I also seen some recent complaining about it, but it is a difficult issue as (as far as I thought) could not really do anything about this on the pandas side.

I was in the belief we *do* use sqlalchemy Core and not ORM (but have to look later in some more detail to verify). You can see the insert code here: https://github.com/pydata/pandas/blob/master/pandas/io/sql.py#L703 
Do you want to take a look as well?

**Comment by vadoverde** [comment]
Joris, thanks for the quick reply and the reference. You are using sqlalchemy Core and it looks like the Core has performance issues too. I just developed the Core solution suggested by sqlalchemy and the DB write is still slow! It's definitely a sqlalchemy issue.
I'm new to python (3 weeks) I've always worked with Microsoft technology, so I'll try all I can to help get this issue resolved as I needed for the solution I'm working on. I'll give you a status, but if you find any solution please let me know too.
Thanks,
Sam

**Comment by jorisvandenbossche** [comment]
What would be interesting is that you also compare it with a non-sqlalchemy implementation (so using a connection object of `pyodbc` (or another driver you are using) and using the `execute` method of that one instead of using an sqlalchemy engine). So to check if it is a sqlalchemy performance issue, or more an issue with the driver/connection with SQL Server itself.

**Comment by vadoverde** [comment]
I developed the following code to prove the issue is not caused by the driver. Not a pymssql issue at the least. The script below that inserts 37,830 records of two integers in 53 seconds when the proposed sqlalchemy Core solution takes 2 minutes and 40 seconds. Dataframe.to_sql() takes over 4 minutes. Here is my script:

**********************************************************************************************
import pymssql
from datetime import datetime
import pandas as pd
import numpy as np

#insert Account Relations into SQL table
tStart = datetime.now()
sqlSt = """WITH cte(AccountID, RelatedAccountID) AS
(
    SELECT AccountID, RelatedAccountID FROM 
    (
        VALUES
        """

for i in cba_simAccts.index:
    if i == cba_simAccts.shape[0] - 1:
        sqlSt += "(" + str(cba_simAccts.loc[i,"AccountID"]) + "," + str(int(cba_simAccts.loc[i,"RelatedAccountID"])) + ")"
    else:
        sqlSt += "(" + str(cba_simAccts.loc[i,"AccountID"]) + "," + str(int(cba_simAccts.loc[i,"RelatedAccountID"])) + ")"
        sqlSt += ","

sqlSt += """
    ) as V(AccountID, RelatedAccountID)
)
INSERT INTO ML.RelAcct_Credit (AccountID, RelatedAccountID)
SELECT AccountID, RelatedAccountID
FROM cte"""

tEnd = datetime.now()
print (str(tEnd-tStart))

tStart = datetime.now()
conn = pymssql.connect(inp.dbServer, inp.dbUser, inp.dbPwd, inp.dbName)
cursor = conn.cursor()

cursor.execute(sqlSt)

conn.commit()
conn.close()

tEnd = datetime.now()
print (str(tEnd-tStart))
**********************************************************************************************
The resulting time deltas of this query are:
0:00:13.975398 ==> time needed by my machine to formulate the SQL statement
0:00:52.802280 ==> time needed to compile and execute the statement on the SQL server

**cba_simAccts**
In [304]: cba_simAccts.shape
Out[304]: (37830, 2)
In [305]: type(cba_simAccts)
Out[305]: pandas.core.frame.DataFrame
In [306]: cba_simAccts.dtypes
Out[306]: 
AccountID             int64
RelatedAccountID    int64
dtype: object

**Comment by TomAugspurger** [comment]
Thanks for digging into this. Are you familiar with any of the profiling tools for python? At the very least we should be able to narrow the gap between us an SQLA.

**Comment by jorisvandenbossche** [comment]
Yes, indeed, thanks a lot for looking into this. 
A question about the code you posted above. If I understand it correctly, here you insert data into a table from another table that is already in SQL? (the `INSERT INTO ... SELECT ... FROM ...` part) 
Do you do the same with sqlalchemy? Because at least with pandas `to_sql` you transfer the data from outside the database into a table.

**Comment by vadoverde** [comment]
Sure thing. I haven't done profiling in Python yet. I did some profiling in SQL Server when issues the to_sql() statement and it appeared to me as if every row was being written individually. 
Here is the code I used for SQLA.

**********************************************************************************
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Table, Column, Integer, String,  create_engine, insert, schema, MetaData, insert
from sqlalchemy.orm import scoped_session, sessionmaker

Base = declarative_base()
DBSession = scoped_session(sessionmaker())
engine = None

def init_sqlalchemy(dbname="mssql+pymssql://username:password@SQLSERVERNAME:1433/DATABASENAME"):
    global engine
    engine = create_engine(dbname, echo=False)
    DBSession.remove()
    DBSession.configure(bind=engine, autoflush=False, expire_on_commit=False)

class RelAcct_Credit(Base):
    __tablename__ = 'RelAcct_Credit'
    __table_args__ = ({'extend_existing': True, 'schema':'ML'})
    RelAcct_SKID = Column(Integer, primary_key = True, autoincrement = True)
    AccountID = Column(Integer)
    RelatedAccountID = Column(Integer)

tStart = datetime.now()
engine.execute(
        RelAcct_Credit.__table__.insert(),
        [{"AccountID": int(cba_simAccts.loc[i, 'AccountID']),
          "RelatedAccountID": int(cba_simAccts.loc[i, 'RelatedAccountID'])} for i in cba_simAccts.index])

tEnd = datetime.now()
print (str(tEnd-tStart))
**********************************************************************************
Time Delta: 
0:02:35.721570

**Comment by jorisvandenbossche** [comment]
Can you time something in line of the following (will probably not be fully correct, but you get the idea):

```
conn = pymssql.connect(inp.dbServer, inp.dbUser, inp.dbPwd, inp.dbName)
cursor = conn.cursor()

cursor.executemany(
    "INSERT INTO ML.RelAcct_Credit (AccountID, RelatedAccountID) VALUES (%d %d)",
    [(int(cba_simAccts.loc[i, 'AccountID']), int(cba_simAccts.loc[i, 'RelatedAccountID'])) for i in cba_simAccts.index])

conn.commit()
conn.close()
```

This is in my view a fairer comparison, as this also transfers the data from python to the database.

**Comment by vadoverde** [comment]
Unfortunately, no dice. This query took me 0:14:27.387294 (14 minutes) on a wireless connection. The time for my solution above (with sqlSt) on wireless is 10 seconds slower:
0:00:14.630463
0:01:02.058205 

I'm more convinced now that the sqlalchemy execute and executemany are writing data row by row and doing heavy communication back and forth between my machine and the server which is reflected by the drastic decrease in performance over wifi...

**Comment by jorisvandenbossche** [comment]
@vadoverde I am not fully understanding. Do you mean that the code snippet I showed above took 14 mins? (this is without pandas or sqlalchemy) Because that would be even slower as with sqlalchemy, you said above that this took 2min 35s. 
And what are the other timings?

**Comment by vadoverde** [comment]
@jorisvandenbossche sorry about the confusion. Here are the details:
The code snippet you showed above took 14 minutes because I was connected to the network through wireless. I just ran your code snippet while hardwired to the network and it took 0:02:36.178616.

**Comment by jorisvandenbossche** [comment]
And the timing above of 0:02:35.721570 for sqlalchemy, that is with the same network? Because, then , my conclusion would be: it is not an issue with sqlalchemy, but with the speed of the driver (pyodbc, pymssql, ..), the network or sql server itself.

**Comment by vadoverde** [comment]
You're right, sqlalchemy is not the problem. pymssql's executemany() is inserting the data row by row. I developed a solution that sends the data to SQL server in XML format and inserts into a SQL table using OPENXML() SQL command and it took 
0:00:02.101211.
SQL server though inserts this data in a few milliseconds, so the performance is still not ideal compared to SQL Server but I'm happy with 2 seconds compared 2 minutes 35 seconds that executemany() and to_sql() takes.

Joris, I appreciate all your help getting this issue resolved. I'd be happy to share the XML solution if you'd like.

**Comment by jorisvandenbossche** [comment]
@vadoverde No problem, and glad you found a solution 

For other people it is indeed interesting to post your solution somewhere, maybe also post it at the recent thread on the sqlalchemy's mailing list. 
For pandas itself this will be out of scope (I think we want to restrict ourselves to a solution based on sqlalchemy)

Further, maybe also worth raising this at the pymssql mailing list/issue tracker.

**Comment by maximilianr** [comment]
@vadoverde We are having similar issues. Is there a way you can share your XML solution? 

Thanks,
Max

**Comment by vadoverde** [comment]
Max - here is a function I developed to translate the pandas array to XML format and writes it with a SQL statement. The reason it's fast because pymssql sends one XML file to SQL instead of writing tens of thousands of rows each in a separate batch.
https://gist.github.com/vadoverde/84f4d4a4c31416d2dfee

**Comment by MaximilianR** [comment]
@vadoverde Many thanks indeed! 

I haven't used any XML libraries, and it looks likes there are some imports (`ET`) outside the function. Can you clarify what those are?

**Comment by vadoverde** [comment]
@maximilianr - sorry I forgot to add those. Here are all my imports, ET being xml.etree.ElementTree

import pandas as pd
import xml.etree.ElementTree as ET
import xml
from datetime import datetime
import pymssql

**Comment by MaximilianR** [comment]
@vadoverde Thanks again!

**Comment by vadoverde** [comment]
Anytime, hope it helps
