### ISSUE TITLE
pandas.to_datetime silently fails for invalid input string

### ISSUE THREAD

**Issue by ptrcarta** [pydata/pandas#10029]
when entering an invalid string in pandas.to_datetime, the output is the given string. it should either raise an exception or output a NaT value
```
>>> a = pd.to_datetime('1991-02-30')
>>> a
'1991-02-30'
>>> a = pd.to_datetime('1991-02302')
>>> a
'1991-02302'
>>> a = pd.to_datetime('199102302')
>>> a
'199102302'
>>> a = pd.to_datetime('19sd')
>>> a
'19sd'
```

**Comment by jreback** [comment]
you can pass ``coerce=True`` to have it make these into ``NaT``. This is long established and done for user convenience as strings can take on many many forms.
