### ISSUE TITLE
2 spaces in csv file between date and time

### ISSUE THREAD

**Issue by denfromufa** [pydata/pandas#10037]
```
df.to_csv(path_or_buf=f, sep=' ', header=False, 
                index=True, mode='a', quoting=QUOTE_NONE, escapechar=' ',
                date_format='%m/%d/%Y %H:%M:%S')
```

generates 2 spaces in csv file between date and time. It should only be one space since sep=' '.

**Comment by jorisvandenbossche** [comment]
@denfromufa can you provide a small reproducible example? (some data that show this) 
Isn't your date and time in one column?

**Comment by denfromufa** [comment]
import pandas as pd
    from csv import QUOTE_NONE
    import numpy as np


    rng = pd.date_range('1/1/2011', periods=72, freq='H')
    rng.values[:3]


    df1=pd.DataFrame(np.random.rand(rng.shape[0],5),index=rng)
    df1.head(3)


    df1.to_csv('test.csv', sep=' ', header=False, 
                    index=True, mode='a', quoting=QUOTE_NONE, escapechar=' ',
                    date_format='%m/%d/%Y %H:%M:%S')


    # %load test.csv
    01/01/2011  00:00:00 0.8135433263165096 0.32811684099353866 0.4145982626151403 0.20669348747780092 0.40366368662756147
    01/01/2011  01:00:00 0.18014728764443488 0.5146938838675809 0.4536598423132532 0.34155733427820656 0.440876368183323
    01/01/2011  02:00:00 0.4768181257700802 0.9281149054744247 0.1394599500466026 0.44100722743440857 0.4725515115245551
    01/01/2011  03:00:00 0.8827699134085255 0.23117935993894556 0.7247609890740998 0.46107279818544544 0.3034632588430233
    01/01/2011  04:00:00 0.7587177485651242 0.774790622810391 0.06699642692286567 0.1384981319339471 0.8932072731692663
    01/01/2011  05:00:00 0.10015283348607174 0.38220578967027674 0.4148014776634852 0.11548217031729191 0.04768268242910356
    01/01/2011  06:00:00 0.009332655125750211 0.3219250343041896 0.7456368943160526 0.8880456857306563 0.9427586244971458
    01/01/2011  07:00:00 0.8259394479424389 0.7739443963570316 0.46502361908665046 0.06414331242986782 0.9812830751461493
    01/01/2011  08:00:00 0.16525838975094442 0.34134816018816205 0.49708268918687315 0.4492019264155531 0.4644320135637432
    01/01/2011  09:00:00 0.15304431836675558 0.1532133949438823 0.0007128393678985656 0.10839873617410367 0.31219734606529836
    01/01/2011  10:00:00 0.8410740756313426 0.9345144325731438 0.15806885400955495 0.7634559588774982 0.8013531655650757
    01/01/2011  11:00:00 0.9130963646552894 0.06306812403058681 0.6636252785779093 0.5673272780410901 0.6741426149989511
    01/01/2011  12:00:00 0.6358598844782327 0.8030366985874456 0.4542545666669118 0.9223030501438932 0.9940468706012558
    01/01/2011  13:00:00 0.9404854236653073 0.47982064783581524 0.5321329997417077 0.27722562315902 0.2637073270166461
    01/01/2011  14:00:00 0.6260069889023235 0.5350906951425742 0.1555584230087339 0.141202718108013 0.24335014139098843
    01/01/2011  15:00:00 0.4810173670486547 0.36361789656696886 0.6062147756052291 0.7419697690348793 0.11429710377536506
    01/01/2011  16:00:00 0.9545679446115913 0.4029839335485481 0.401694386643468 0.7986907211996336 0.5152860124780485
    01/01/2011  17:00:00 0.8607004856222028 0.8809506629260269 0.9318004311145482 0.06538953727070618 0.3197291872362322
    01/01/2011  18:00:00 0.49142246814705604 0.134112428080996 0.6555806547403249 0.24240228991010693 0.5714883942984069
    01/01/2011  19:00:00 0.5852598278447046 0.528710335910723 0.747720253720378 0.29232031815899373 0.4942095312943948
    01/01/2011  20:00:00 0.051033555833764344 0.8544964962754257 0.39994243258096496 0.19761729002111406 0.27574239496114805
    01/01/2011  21:00:00 0.25085092189001157 0.6784762020894095 0.3739354345521878 0.46557954317469086 0.07221134067834689
    01/01/2011  22:00:00 0.9044249728769235 0.6944515604538478 0.7455888678520047 0.9209851063127739 0.3447546615916308
    01/01/2011  23:00:00 0.9830294946409804 0.32489282549715137 0.7645199066636087 0.6644999786291534 0.3786063720970688
    01/02/2011  00:00:00 0.944287341540107 0.8502233854263226 0.22806956681858115 0.3344661605380722 0.7781207260355414
    01/02/2011  01:00:00 0.29099589737466713 0.0563200265028545 0.004295857543390125 0.1836757328047378 0.13085209092720407
    01/02/2011  02:00:00 0.8448781765463917 0.689756843411802 0.8134411718470742 0.6041278994801442 0.9595113407410018
    01/02/2011  03:00:00 0.7055186826291187 0.21025088133373737 0.41247767842109406 0.32548627899071103 0.011176632461411318
    01/02/2011  04:00:00 0.6280347588337498 0.7169845599479692 0.7960404191007645 0.28318032007998306 0.4877179018947523
    01/02/2011  05:00:00 0.11943651249042697 0.45561029124267005 0.6162020270434331 0.7107501680441025 0.6423798714966604
    01/02/2011  06:00:00 0.4529763948230072 0.45409605870763303 0.4849514525073776 0.9628899009676548 0.23739108884904392
    01/02/2011  07:00:00 0.09466583467963485 0.3066733697675642 0.2665133437406664 0.9558617509752713 0.096382455719914
    01/02/2011  08:00:00 0.8869659358177973 0.14494642528150903 0.36290711021999267 0.897453161148009 0.9164005419452141
    01/02/2011  09:00:00 0.6662565905939655 0.7190569709524318 0.5639681691312882 0.22856416209009267 0.05343561658163676
    01/02/2011  10:00:00 0.3107025330869121 0.10232175385779141 0.2437549396888401 0.03180741327984882 0.6290510752990796
    01/02/2011  11:00:00 0.29687826200217393 0.4207621537027304 0.04962788966601672 0.6387728001213947 0.45847956842664495
    01/02/2011  12:00:00 0.6248483443819739 0.5956210927259238 0.027931135461846335 0.1231580242813839 0.018847826685410296
    01/02/2011  13:00:00 0.23684126515901516 0.28299417221057965 0.6235196265570828 0.6630939790497901 0.6106743038941336
    01/02/2011  14:00:00 0.04906681222971032 0.09149631739215747 0.3186482927851183 0.11944035459475888 0.8147775232699773
    01/02/2011  15:00:00 0.062412440348232456 0.42551097539246174 0.6254899125546779 0.2672302583221978 0.08626318449506953
    01/02/2011  16:00:00 0.6174024154462946 0.2097178893034699 0.6596354911463238 0.32506071466194264 0.2000314794406972
    01/02/2011  17:00:00 0.6407500021691708 0.8688120791368592 0.43310410423820567 0.08181630015859487 0.027922534571337976
    01/02/2011  18:00:00 0.4838369738101791 0.4889907890952736 0.10050367605818489 0.3065795131178881 0.25434254208499374
    01/02/2011  19:00:00 0.8128241342996093 0.8015158641133285 0.41488376655295944 0.7917104505354494 0.880203906779188
    01/02/2011  20:00:00 0.09653519528131604 0.4850310142136016 0.22720587252274416 0.39422594326072646 0.5985147841492376
    01/02/2011  21:00:00 0.28796877363112006 0.7846774957896145 0.2641592260872051 0.017437935273674987 0.2164218056674705
    01/02/2011  22:00:00 0.052441093081390555 0.24568557014402015 0.5205907807205123 0.5924266116786371 0.25137987737500644
    01/02/2011  23:00:00 0.26984449341268746 0.6599178380524725 0.26988659724710373 0.07097938985300434 0.9407293837285815
    01/03/2011  00:00:00 0.967466576367879 0.16127708026873677 0.600194478494303 0.9406232828195052 0.6899947036927737
    01/03/2011  01:00:00 0.7430820257793065 0.056410565014622716 0.2688424684353854 0.09468067773769073 0.9402868017729881
    01/03/2011  02:00:00 0.4862152969828537 0.1572823467390716 0.6234847582379207 0.2706959094584439 0.09917220777695701
    01/03/2011  03:00:00 0.597863670050043 0.8302290048585018 0.8665841001111021 0.15006608992871917 0.31625644818962606
    01/03/2011  04:00:00 0.16138606182314996 0.31149630720280963 0.0970816184737554 0.319945496516725 0.6200656646723811
    01/03/2011  05:00:00 0.16920602811291485 0.01627259849291851 0.003631168588151934 0.38827409629281484 0.8846632142920735
    01/03/2011  06:00:00 0.3209599093732357 0.5057052588612116 0.9981541509436036 0.25666529804045146 0.9931922772984885
    01/03/2011  07:00:00 0.45213741455495393 0.3686167688977925 0.3079513045923289 0.5792321186504825 0.7316096090666614
    01/03/2011  08:00:00 0.44147264754327264 0.08801316389116642 0.10186812319358662 0.45305996587913233 0.9612147446799971
    01/03/2011  09:00:00 0.33496910614046405 0.9412604396112639 0.7951139464963424 0.9777130661938228 0.27855252926317686
    01/03/2011  10:00:00 0.760478335555992 0.21965881572237433 0.8224524022181791 0.543104710413362 0.23086409176055822
    01/03/2011  11:00:00 0.18866313010167202 0.7507881804468483 0.037472754190086666 0.4500505164116413 0.7156454449636624
    01/03/2011  12:00:00 0.264494035691749 0.43355514772323234 0.6937800259879133 0.8058238844806092 0.6256928200584311
    01/03/2011  13:00:00 0.2736528134346097 0.16903704517672058 0.9055205449623714 0.648935181951483 0.654418991698296
    01/03/2011  14:00:00 0.7558521260386539 0.19675818151163882 0.7258048434462796 0.9131058728620046 0.929728136453011
    01/03/2011  15:00:00 0.1264630766629834 0.7026146985776004 0.27910624347008217 0.8471962243524381 0.8484816171950694
    01/03/2011  16:00:00 0.7681374450085684 0.28796966361080245 0.6842852852369017 0.1638334912201781 0.3130917048715611
    01/03/2011  17:00:00 0.888640786468385 0.7405276516258239 0.272774446816341 0.786069889445504 0.4332838053248147
    01/03/2011  18:00:00 0.18108955879716626 0.7391954126179028 0.05825119906141141 0.5191561940652476 0.8669347426710133
    01/03/2011  19:00:00 0.17066274567985806 0.060359277439300696 0.7229232575053816 0.7545147496919973 0.41352709416100975
    01/03/2011  20:00:00 0.03331691446523821 0.42722596579237093 0.14468812819440824 0.9364117803030266 0.580604138714224
    01/03/2011  21:00:00 0.6092368121026717 0.8298927077685252 0.8823758095890506 0.6381067623701301 0.49232033807319286
    01/03/2011  22:00:00 0.09924831794317468 0.5168911396983634 0.15941269841562378 0.7153566835675894 0.1463030258757284
    01/03/2011  23:00:00 0.22531555414611026 0.5978116397423624 0.7509126588754997 0.13173373304796787 0.20256672380191176

**Comment by jorisvandenbossche** [comment]
@denfromufa Thanks for the example. I made it a bit smaller:

```
In [48]: from csv import QUOTE_NONE

In [49]: rng = pd.date_range('1/1/2011', periods=3, freq='H')

In [50]: df = pd.DataFrame([[1,2],[3,4],[5,6]],index=rng)

In [51]: df
Out[51]:
                     0  1
2011-01-01 00:00:00  1  2
2011-01-01 01:00:00  3  4
2011-01-01 02:00:00  5  6

In [60]: print df.to_csv(sep=' ', quoting=QUOTE_NONE, escapechar=' ', date_format='%m/%d/%Y %H:%M:%S')
 0 1
01/01/2011  00:00:00 1 2
01/01/2011  01:00:00 3 4
01/01/2011  02:00:00 5 6
```

and it has to do wiht your combination of `quoting` and `escapechar`. If I remove both:

```
In [61]: print df.to_csv(sep=' ', date_format='%m/%d/%Y %H:%M:%S')
 0 1
"01/01/2011 00:00:00" 1 2
"01/01/2011 01:00:00" 3 4
"01/01/2011 02:00:00" 5 6
```

But I think this is expected behaviour, as `escapechar` is meant to escape occurences of the delimiter that are not the delimiter (a space is occuring in the date-time column, while you set the delimiter as a space). Eg I can set it to a backslash:

```
In [64]: print df.to_csv(sep=' ', quoting=QUOTE_NONE, escapechar='\\', date_format='%m/%d/%Y %H:%M:%S')
 0 1
01/01/2011\ 00:00:00 1 2
01/01/2011\ 01:00:00 3 4
01/01/2011\ 02:00:00 5 6
```

What do you try to achieve exactly? If you want to have it with only one space and without quotes, you will have to split it to two columns I think, as you it is not allowed to give no escapechar with QUOTE_NONE

**Comment by denfromufa** [comment]
I want to have it with only one space and without quotes without breaking to 2 columns

**Comment by jorisvandenbossche** [comment]
If you want that, then it means that it are *in practice* 2 columns in the csv files, as there is no way to distinguish the space between date and time, and the space as delimiter between the other columns.

As I said above, the only way to do this is splitting it up in to 2 columns (as you cannot generate an invalid csv file).

**Comment by jorisvandenbossche** [comment]
With my example of above, you can easily do this with:

```
In [28]: df
Out[28]:
                     0  1
2011-01-01 00:00:00  1  2
2011-01-01 01:00:00  3  4
2011-01-01 02:00:00  5  6

In [29]: df.index.to_series().apply(str).str.split(' ', return_type='frame')
Out[29]:
                              0         1
2011-01-01 00:00:00  2011-01-01  00:00:00
2011-01-01 01:00:00  2011-01-01  01:00:00
2011-01-01 02:00:00  2011-01-01  02:00:00
```

If you put that in the original dataframe, you can now write it as you want.

**Comment by jorisvandenbossche** [comment]
Closing, as it is more a question as a pandas bug/enhancement (which does not mean you can ask further!)

**Comment by denfromufa** [comment]
This approach loses the date formatting `date_format='%m/%d/%Y %H:%M:%S'`

**Comment by denfromufa** [comment]
reproc_time.to_series().apply(lambda x: x.strftime('%m/%d/%Y %H:%M:%S')).str.split(' ', return_type='frame')
