### ISSUE TITLE
Strange behavior of to_dict() inside apply

### ISSUE THREAD

**Issue by scls19fr** [pydata/pandas#10049]
Hello,

I don't know if that's a misunderstanding from my side but

    import pandas as pd
    df_task = pd.DataFrame({
        "Name": ["Saint Auban", "Go", "Coupe S", "3 Eveches", "DORMILLOUSE FORT", "Saint Auban"],
        "Lat": [44.054901123046875, 44.015087127685547, 44.053600311279297, 44.288883209228516, 44.414447784423828, 44.054901123046875],
        "Lon": [5.9840002059936523, 6.0107221603393555, 6.3285999298095703, 6.5361166000366211, 6.3811173439025879, 5.9840002059936523],
        "Altitude": [1500, 1500, 1600, 2700, 2200, 1500]
    })

    In [129]: map(lambda callable: callable(), df_task.apply(lambda tp: tp.to_dict(), axis=1))
    Out[129]:
    [[44.054901123046875, 1500, 5.984000205993652, 'Saint Auban'],
     [44.01508712768555, 1500, 6.0107221603393555, 'Go'],
     [44.0536003112793, 1600, 6.32859992980957, 'Coupe S'],
     [44.288883209228516, 2700, 6.536116600036621, '3 Eveches'],
     [44.41444778442383, 2200, 6.381117343902588, 'DORMILLOUSE FORT'],
     [44.054901123046875, 1500, 5.984000205993652, 'Saint Auban']]

I was expecting a list of dict like:

    [{'Altitude': 1500, 'Lat': 44.054901123046875, 'Lon': 5.984000205993652, 'Name': 'Saint Auban'},
     {'Altitude': 1500, 'Lat': 44.01508712768555, 'Lon': 6.0107221603393555, 'Name': 'Go'},
     {'Altitude': 1600, 'Lat': 44.0536003112793, 'Lon': 6.32859992980957, 'Name': 'Coupe S'},
     {'Altitude': 2700, 'Lat': 44.288883209228516, 'Lon': 6.536116600036621, 'Name': '3 Eveches'},
     {'Altitude': 2200, 'Lat': 44.41444778442383, 'Lon': 6.381117343902588, 'Name': 'DORMILLOUSE FORT'},
     {'Altitude': 1500, 'Lat': 44.054901123046875, 'Lon': 5.984000205993652, 'Name': 'Saint Auban'}]

Why ? because

    tp = df_task.irow(0)

    In [137]: tp.to_dict()
    Out[137]:
    {'Altitude': 1500,
     'Lat': 44.054901123046875,
     'Lon': 5.9840002059936523,
     'Name': 'Saint Auban'}

Maybe I missed something ?

Any idea ?

**Comment by TomAugspurger** [comment]
Have a look at the `orient` parameter to `to_dict`.
In your second example, `tp` is a `Series`. The default (and only) orientation for `Series.to_dict` is `{label -> value}`. You want the `records` orient.

```python
In [19]: df_task.to_dict(orient='records')
Out[19]: 
[{'Altitude': 1500,
  'Lat': 44.054901123046875,
  'Lon': 5.984000205993652,
  'Name': 'Saint Auban'},
...
```

**Comment by scls19fr** [comment]
Thanks. Sorry
