### ISSUE TITLE
Pandas and h5py load the same data (ndarray) differently: hvl_t support.

### ISSUE THREAD

**Issue by kierun** [pydata/pandas#10059]
Based off this [question](http://stackoverflow.com/q/29986826/232794). In fact more or less copied and pasted :)

I have a file in HDF5 format.  It was created using the HDF5's C++ API using these:

```c++
    struct SignalDefH5
    {
        char  id   [128];
        char  name [ 64];
        char  units[ 16];
        float min;
        float max;
        hvl_t tags; /* This right there does not work in Pandas... */
    };

    struct TagDefH5
    {
        char  tag [ 64];
        char  desc[256];
    };
```

Note that tags is supposed to be a list of strings. If I load the file using h5py, I get this:

```python
    >>> import h5py
    >>> hfile = h5py.File('test.h5', 'r')
    >>> signals = hfile['/signals']
    >>> signals[0]
    ('id1', 'a pressure', 'bar', 0.0, 300.0, ['Pressure'])
    >>> type(signals[0][5])
    numpy.ndarray
```

However, if I use Pandas to load the same file, I get this:

```python
    >>> store = pd.HDFStore('test.h5')
    >>> store.root.signals
    /signals (Table(179,)) ''
      description := {
      "id": StringCol(itemsize=128, shape=(), dflt='', pos=0),
      "name": StringCol(itemsize=64, shape=(), dflt='', pos=1),
      "units": StringCol(itemsize=16, shape=(), dflt='', pos=2),
      "min": Float32Col(shape=(), dflt=0.0, pos=3),
      "max": Float32Col(shape=(), dflt=0.0, pos=4),
      "tags": StringCol(itemsize=64, shape=(), dflt='', pos=5)}
      byteorder := 'little'
      chunkshape := (234,)
    >>> store.root.signals[0]
    ('id1', 'a pressure', 'bar', 0.0, 300.0, '\x02\x00\x00\x00\x00\x00\x00\x00\xf0f\x1e\x04\x00\x00\x00\x00\xba\nVT\xd1!\xa7\xdd\xb0\xe3\x9a\x02\x00\x00\x00\x00@\xecR\x1f\xa2\x7f\x00\x00}B\x178\x96\xa4u\xe6\xb0\xdd\x7f\x02\x00\x00\x00\x00 \x01')
    >>> type(store.root.signals[0][5])
    numpy.string_
```

So, [Pandas cannot cope with this type](http://stackoverflow.com/a/29988505/232794) yet it would be nice if it could... I am quit happy to test any patch and help in as much as I can.

Here's all the versions:

```python
pd.show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.5.final.0
python-bits: 64
OS: Linux
OS-release: 3.10.0-229.1.2.el7.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8

pandas: 0.16.0
nose: 1.3.6
Cython: 0.22
numpy: 1.9.2
scipy: 0.15.1
statsmodels: None
IPython: 3.0.0
sphinx: 1.2.3
patsy: None
dateutil: 2.4.2
pytz: 2015.2
bottleneck: None
tables: 3.1.1
numexpr: 2.2.2
matplotlib: 1.4.3
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 0.9.7
pymysql: None
psycopg2: None
```

**Comment by shoyer** [comment]
Can you read this data using pytables directly? (That's the library pandas uses to handle HDF5.)

I think your question reflects some confusion about the purpose of HDF5 support in pandas. HDF5 is an extremely flexible file format, so mapping every HDF5 file onto native pandas data structures is hopeless. Instead, pandas uses HDF5 for a custom binary serialization format (one still readable by other tools). If you want to read/write arbitrary HDF5, you should probably stick to h5py, and write your own helper functions for reading and writing dataframes.

**Comment by kierun** [comment]
I can map it using hd5py, as shown above. I have just tried with pytables and it does not work. Should I report it as a bug there instead of here?

**Comment by jreback** [comment]
@kierun as I explained in the SO answer, this is not implemented in ``PyTables`` AFAIK. You can use ``h5py``, read it, and then try to map to a pandas structure (though it doesn't look like it would nicely map).

``PyTables`` implements a sub-set of ``HDF5`` with a pythonic interface; ``h5py`` is a much more strict c-API translation. 

This is not a bug; rather you are expecting arbitrary structure support which does not exist.

**Comment by kierun** [comment]
I am really struggling to understand why a list of string is an "arbitrary structure".  We have string in Python and in PyTables as entities. We have arrays/lists. So, how come we cannot have an array/list of strings?

Maybe it's the C++ side fault for using something weird, but in that case there should be a way to change that, should there not?

I am really not trying to be a pain, but I just don't get it how a collection of base types is not support.

**Comment by jreback** [comment]
@kierun its not a 'list-of-strings', rather a sub-node (I think) of 2 other items. If you put them in the main table this might work. I don't know.

**Comment by kierun** [comment]
@jberka And now I get it... Looking back at the C++ code, it writes a  H5::VarLenType which indeed is an arbitrary structure.  Thank you very much for your patience. ^_~
