### ISSUE TITLE
rpy2 / R interface (v0.16.0)

### ISSUE THREAD

**Issue by borisRa** [pydata/pandas#10062]
Hi,

Using the last pandas version, the command : "import pandas.rpy.common as com"

produces the following warning : 
 "The pandas.rpy module is deprecated and will be removed in a future version. We refer to external packages like rpy2, found here: http://rpy.sourceforge.net  "like rpy2, found here: ttp://rpy.sourceforge.net", FutureWarning) "

I use the following functionality heavily : 
com.convert_to_r_dataframe(pandas_DF) 
com.convert_robj(results_from_R)

How with rpy2 I can do the same ?

Regards,
Boris

**Comment by jorisvandenbossche** [comment]
See #9602. 
We were actually a little bit too fast with the deprecation, before we could put good docs in place on how to port to rpy2 (and the docs in rpy2 itself on this are also not very clear)

I think you can start with this: http://stackoverflow.com/questions/20630121/pandas-how-to-convert-r-dataframe-back-to-pandas 
And we would really appreciate some feedback/problems you encounter (eg things that work in pandas but not with rpy2), you can report that at #9602

**Comment by jreback** [comment]
closing in favor of #9602

**Comment by jorisvandenbossche** [comment]
@borisRa Here is a notebook exploring some things: http://nbviewer.ipython.org/gist/jorisvandenbossche/d0deaa53ace697e1514e

Basically:

* imports: 

  ```
import rpy2.robjects.conversion as conversion
from rpy2.robjects import pandas2ri
pandas2ri.activate()
```

*  after that, you can change:
  * `com.convert_to_r_dataframe(df)` -> `conversion.py2ri(df)`
  * `com.convert_robj(rdf)` -> `conversion.ri2py(rdf)`

Does this work for you?

**Comment by borisRa** [comment]
Thanks ! that is exactly what looked for !

**Comment by borisRa** [comment]
And what are the alternatives for : 

import pandas.rpy.common as com
pydf = com.load_data('iris')
r_matrix = com.convert_to_r_matrix(df)

Thanks,
Boris

**Comment by jorisvandenbossche** [comment]
For the data, does this work?

```
from rpy2.robjects import r
r.data(name)
robj = r[name]
conversion.ri2py(robj)
```

**Comment by jorisvandenbossche** [comment]
And for the matrix, this is actually just using `convert_to_r_dataframe`, and then using the R `as.matrix` function.

**Comment by borisRa** [comment]
Everything works as a charm !
Thanks !
