### ISSUE TITLE
Problem constructing Series from dict with datetime.date in level of MultiIndex

### ISSUE THREAD

**Issue by eoincondron** [pydata/pandas#10060]
When calling the Series constructor on a dict with tuple keys containing a datetime.date object 
the values are converted to NaNs as this example demonstrates:
    
    In [52]:

    pd.Series({(1, datetime.date(2012, 1, 1)): 1, 
               (2, datetime.date(2012, 1, 2)): 2})
    Out[52]:
    1  2012-01-01   NaN
    2  2012-01-02   NaN

It only happens with MultiIndex but otherwise arises regardless of the number and order of the levels. 
I know having datetime.date objects in an index is not optimal and that calling the constructor in this way actually forces the dates to Timestamp objects but in my use case I'm receiving data which is structured this way and converting it to Pandas objects.

**Comment by eoincondron** [comment]
P.S.
version is 0.16.0

**Comment by jreback** [comment]
it seems the same question is #8802
 
You can do this if you really want. 
```
In [4]: pd.MultiIndex.from_arrays([[1,2],Index([datetime.date(2013,1,1),datetime.date(2014,1,1)])])
Out[4]: 
MultiIndex(levels=[[1, 2], [2013-01-01, 2014-01-01]],
           labels=[[0, 1], [0, 1]])

In [5]: pd.MultiIndex.from_arrays([[1,2],Index([datetime.date(2013,1,1),datetime.date(2014,1,1)])]).levels[1]
Out[5]: Index([2013-01-01, 2014-01-01], dtype='object')

In [6]: pd.MultiIndex.from_arrays([[1,2],Index([datetime.date(2013,1,1),datetime.date(2014,1,1)])]).levels[1][0]
Out[6]: datetime.date(2013, 1, 1)
```

This is in general not very useful, much slower, and harder to deal with. Is their a reason you insist on using ``datetime.date``?

**Comment by eoincondron** [comment]
It's not really the same question. In the previous question I had a problem with the new version forcing dates to Timestamps which caused existing code not to work. I've adopted this and the code I write now doesn't use datetime.date objects in the index. However, I'm working with data which is produced by existing programmes written by others which isn't aimed at Pandas and has a dictionary with tuple keys containing datetime.date objects which I would like to convert to Pandas. 
I have no problem with the index of the resultant Series (or DataFrame in the case of a dict of dicts) being forced to contain to Timestamps. The problem is that values of the result are all NaN which seems like an a genuine bug.

**Comment by jreback** [comment]
prob related to this: https://github.com/pydata/pandas/issues/9456

pull-requests welcome for fixing that (and you can use this as a test case as well)
