### ISSUE TITLE
ENH: Add Index.fillna

### ISSUE THREAD

**Issue by sinhrks** [pydata/pandas#10089]
Related to #6194. There seems no direct way to replace ``NaN``s in ``Index``?

I think a point is what types are acceptable via ``value``.

- scalar: OK
- dict: NG (or accept {iloc : value} dict?)
- Series : NG
- DataFrame : NG

- http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.fillna.html

**Comment by jreback** [comment]
this should be a simple version, maybe with just ``value``. the ``methods`` are already implemented via ``.reindex`` (e.g. ``pad/bfill/nearest``). Don't need much functionanilty here (and in ``.dropna``) but to fill (drop) the correct nan (NaT) type for that index and return a new one. This is actually a pretty simple method.

**Comment by jreback** [comment]
@sinhrks I think this is a preqreq for some other PR's.
