### ISSUE TITLE
ENH: support .strftime for datetimelikes

### ISSUE THREAD

**Issue by jreback** [pydata/pandas#10086]
I think ``Series.dt.strftime()`` might be useful
This is essentially just calling ``.format()`` on a datetimelike lindex (which handles ``NaT`` and such)

```
In [1]: dates = pd.to_datetime(pd.Series(['20010101', '20010331']), format = '%Y%m%d')

In [2]: dates
Out[2]: 
0   2001-01-01
1   2001-03-31
dtype: datetime64[ns]

In [4]: pd.DatetimeIndex(dates.values).format()
Out[4]: ['2001-01-01', '2001-03-31']

In [5]: pd.DatetimeIndex(dates.values).format(date_format='%Y%m%d')
Out[5]: ['20010101', '20010331']
```

**Comment by jorisvandenbossche** [comment]
Why not just exposing the already existing `format` function through the `dt` accessor instead of adding a new method?

**Comment by jreback** [comment]
``strftime`` is the 'expected' name here (expected meaning what you use to format ``datetime.datetime`` (as well as ``Timestamp``)

**Comment by mortada** [comment]
One problem I have with `format()` is that it is not clear the format string should be passed via `date_format=`. I'd always try to do 

```
In [9]: pd.DatetimeIndex(dates.values).format('%Y/%m/%d')
Out[9]: ['', '2001-01-01', '2001-03-31']
```
and realize that it doesn't work. (also not sure why there's an empty string in front in this case, seems like a bug)

Maybe this should be opened as a separate issue/PR?

**Comment by jreback** [comment]
``.format()`` is an internal method (only really used by the to_csv, and takes a bunch or arguments). That's why I am suggesting ``strftime``
