### ISSUE TITLE
Series.plot() ignores label keyword

### ISSUE THREAD

**Issue by goyodiaz** [pydata/pandas#10119]
Using pandas 0.16.1, tested in several environments:
```python
>>> import pandas as pd
>>> s = pd.Series([0, 1])
>>> ax = s.plot(label='stuff')
>>> assert ax.lines[0].get_label() == 'stuff'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AssertionError
```
This is a regression since 0.16.0. I think the problem is in this line in pandas.tools.plotting.MPLPlot._compute_plot_data():
```label = self.kwds.pop('label', None)```
It should read:
```label = self.label```
because the label has been popped before and stored in an attribute.

I want to make a pull request but it will take some time to install git, set up a development environment and get my fingers to relearn their way through it all so it will be a lot of opportunities to beat me.

**Comment by TomAugspurger** [comment]
Yep I noticed that last night.

For people looking for a workaround, the index name is still used if it's set.

```python
s.name = 'stuff'
s.plot()
```

**Comment by TomAugspurger** [comment]
Yes extremely annoying :/ I'll rebase my PR fixing it today.

**Comment by ispmarin** [comment]
:+1: same problem with 0.16.1.

**Comment by goyodiaz** [comment]
Sorry for spamming a closed bug but I thought a couple of suggestions could be useful.

@jorisvandenbossche, not very straightforward but you can do this:
`pd.Series(df1['var'], name='df1').plot(ax=ax)`

Or monkey patch Series.plot: copy this code into a module and import it at the beginning of yours:

```
# Monkey patch to work around pandas 0.16.1 issue #10119.
# https://github.com/pydata/pandas/issues/10119
import pandas as pd

if pd.__version__ == '0.16.1':
    _old_plot = pd.Series.plot
    def _plot(self, *args, label=None, **kwargs):
        return _old_plot(pd.Series(self, name=label), *args, **kwargs)
    pd.Series.plot = _plot
```

Or just patch your local pandas (but this won't help other people using your code).

**Comment by ispmarin** [comment]
Small fix (note the label declaration)

    if pd.__version__ == '0.16.1':
        _old_plot = pd.Series.plot
        def _plot(self, label=None, *args,  **kwargs):
            return _old_plot(pd.Series(self, name=label), *args, **kwargs)
        pd.Series.plot = _plot

**Comment by schmohlio** [comment]
@TomAugspurger @jorisvandenbossche 

In #9574  I had removed:
`label = self.kwds.pop('label', None)`
and hadn't reintroduced it in _compute_plot_data. Was it added somewhere else? This was tied back to the initial issue and wan't to see if I introduced regression. Thanks,
Matt

**Comment by sinhrks** [comment]
``_compute_plot_data`` is changed in #9852 (by me...) , and it moved the previous logic before you've fixed. We should have test cases to cover possible cases.

**Comment by TomAugspurger** [comment]
I added tests in my PR so it should be tested now.
