### ISSUE TITLE
Sort broken after unique -> Series

### ISSUE THREAD

**Issue by anushshetty** [pydata/pandas#10123]
I see #1807 issue reoccurring in my setup:

```
>>> Series(Series([1,3,4]).unique())
0    1
1    3
2    4
dtype: int64

```
And this doesn't return anything:

```
>>> Series(Series([1,3,4]).unique()).sort() 

```
INSTALLED VERSIONS
------------------
commit: None
python: 2.7.5.final.0
python-bits: 64
OS: Linux
OS-release: 3.14.4-200.fc20.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

pandas: 0.16.1-13-gf6c7d89
nose: 1.3.0
Cython: 0.21.1
numpy: 1.8.2
scipy: 0.12.1
statsmodels: None
IPython: 0.13.2
sphinx: None
patsy: None
dateutil: 1.5
pytz: 2012d
bottleneck: None
tables: 3.0.0
numexpr: 2.2.2
matplotlib: 1.3.1
openpyxl: None
xlrd: 0.9.3
xlwt: None
xlsxwriter: 0.7.2
lxml: None
bs4: 4.3.2
html5lib: 0.999
httplib2: None
apiclient: None
sqlalchemy: None
pymysql: None
psycopg2: 2.5.1 (dt dec pq3 ext

**Comment by arcolife** [comment]
+1 same here..

**Comment by jorisvandenbossche** [comment]
`sort` is by default inplace, so no return value is to be expected

**Comment by jorisvandenbossche** [comment]
```
In [7]: Series(Series([1,3,4]).unique()).sort(inplace=False)
Out[7]:
0    1
1    3
2    4
dtype: int64
```

**Comment by anushshetty** [comment]
@jorisvandenbossche Then, should the test case be updated here: https://github.com/pydata/pandas/commit/dbfdb073030a8ef868bcd5583433136c555c153f#diff-933180870dd152b775952fc54a99dba7R3100 ?

**Comment by jorisvandenbossche** [comment]
I don't have such an old pandas to test, but maybe it raised an error? (so the test just checks it does not generate an error, it indeed does not check if the result is correct)

**Comment by jreback** [comment]
this is just testing an older guarantee that function doesn't raise. This is a simplistic regression test.
