### ISSUE TITLE
Typo in pandas/pandas/io/parsers.py

### ISSUE THREAD

**Issue by endisway** [pydata/pandas#10137]
In pandas/pandas/io/parsers.py line 1000, np.uin8 is referred. It is an inexistent member in numpy. I suppose it's a typo for np.uint8.

**Comment by jorisvandenbossche** [comment]
Duplicate of #9266 
And there are already two PRs for this (#9350 and #10074)

**Comment by jorisvandenbossche** [comment]
But thanks for reporting! We should try to merge one of those ... :-)
