### ISSUE TITLE
Support categorical variables with CSVs

### ISSUE THREAD

**Issue by esafak** [pydata/pandas#10153]
It would be nice to be able to read CSVs with categorical variables using read_csv's dtype parameter instead of casting the columns after the fact.

**Comment by TomAugspurger** [comment]
I'm not opposed to this in principle, but I think the API will necessarily be clunky. Would we require (or allow) the user to specify all categories in the call to `read_csv`.

@esafak we do support categoricals in `read/write_hdf` if that's an option for you (it may not be).

**Comment by esafak** [comment]
Can't we already declare the dtypes of selected columns? I thought the problem was limited to categoricals, but if not, please expand my request to all dtypes.

**Comment by TomAugspurger** [comment]
You can specify the types. I was just thinking

```python
pd.read_csv('file.csv', dtypes={'A': np.int64, 'B': pd.CategoricalDtype(['cat1', 'cat2', 'cat3'])})
```

which means you'd need to know all the categories up front. Or we infer them and you'll need to check that they're aren't any surprising categories.

**Comment by sinhrks** [comment]
Nice workaround, but I think it is still nice to support ``category`` arg. 

As a first step, how about converting the specified columns to ``Categorical`` after parsing? Though it is very nice to have optimized IO logic...
