### ISSUE TITLE
No output of xticklabels when plotting to gridspec subplots

### ISSUE THREAD

**Issue by JWarmenhoven** [pydata/pandas#10162]
What seems to be the problem here?
The xticklabels for the first axes defined in a gridspec are not visible when plotting with pandas. The corresponding plot using pyplot.plot does have the labels. 

pandas 0.16
matplotlib 1.4.3

```python 
import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt

%matplotlib inline
df = pd.DataFrame(np.random.randn(8, 4), index=np.arange(8), columns=['A', 'B', 'C', 'D'])
```
Matplotlib
```python
gs = mpl.gridspec.GridSpec(2, 4)
ax1 = plt.subplot(gs[0,:-1])
ax2 = plt.subplot(gs[0,-1])
ax3 = plt.subplot(gs[1,:-2])
ax4 = plt.subplot(gs[1,-2:])

ax1.plot(df.index.values, df.A)
ax2.plot(df.index.values, df.B)
ax3.plot(df.index.values, df.C)
ax4.plot(df.index.values, df.D)

gs.tight_layout(plt.gcf())
```
![mpl](https://cloud.githubusercontent.com/assets/7450204/7680755/08db0c76-fd6a-11e4-9632-d7a0bfca594f.png)

pandas
```python
gs = mpl.gridspec.GridSpec(2, 4)
ax1 = plt.subplot(gs[0,:-1])
ax2 = plt.subplot(gs[0,-1])
ax3 = plt.subplot(gs[1,:-2])
ax4 = plt.subplot(gs[1,-2:])

df.A.plot(ax=ax1)
df.B.plot(ax=ax2)
df.C.plot(ax=ax3)
df.D.plot(ax=ax4)

gs.tight_layout(plt.gcf())
```
![pandas](https://cloud.githubusercontent.com/assets/7450204/7680770/205d661e-fd6a-11e4-8d2d-2629e2528426.png)

It seems that xticklabels are absent when plotting with pandas to the first axis generated in a gridspec. Switching ax1 and ax2 definition:

pandas
```python
gs = mpl.gridspec.GridSpec(2, 4)
ax2 = plt.subplot(gs[0,-1])
ax1 = plt.subplot(gs[0,:-1])
ax3 = plt.subplot(gs[1,:-2])
ax4 = plt.subplot(gs[1,-2:])

df.A.plot(ax=ax1)
df.B.plot(ax=ax2)
df.C.plot(ax=ax3)
df.D.plot(ax=ax4)

gs.tight_layout(plt.gcf())
```
![pandas2](https://cloud.githubusercontent.com/assets/7450204/7680788/39b53678-fd6a-11e4-85b0-4c9b091b2354.png)

http://stackoverflow.com/questions/29552382/legend-overriding-x-label-and-x-ticks

**Comment by TomAugspurger** [comment]
Could you give it a shot on a newer version of pandas? All 3 are the same for me (master pandas, matplotlib 1.4.3)

**Comment by JWarmenhoven** [comment]
Thanks! That seems to have solved the problem... 

pandas 0.16.1
matplotlib 1.4.3

```python
gs = mpl.gridspec.GridSpec(2, 4)
ax1 = plt.subplot(gs[0,:-1])
ax2 = plt.subplot(gs[0,-1])
ax3 = plt.subplot(gs[1,:-2])
ax4 = plt.subplot(gs[1,-2:])

df.A.plot(ax=ax1)
df.B.plot(ax=ax2)
df.C.plot(ax=ax3)
df.D.plot(ax=ax4)

gs.tight_layout(plt.gcf())
```
![pandas3](https://cloud.githubusercontent.com/assets/7450204/7682586/61a6a806-fd79-11e4-82db-be4cd4f80651.png)

**Comment by jorisvandenbossche** [comment]
Maybe we should add a test for this, to ensure this keeps working correctly in the future. 
@JWarmenhoven Are you interested to do this?

**Comment by JWarmenhoven** [comment]
Interested, yes. But since this is not my daily bread...it might take a while :-)
For starters, I wonder what bugfix in 0.16.1 solved this problem.
#9158 perhaps?

**Comment by jorisvandenbossche** [comment]
That's possible. 
If you have any questions how to get started with this, just ask! (here or on https://gitter.im/pydata/pandas)
