### ISSUE TITLE
'logging' name causing issues

### ISSUE THREAD

**Issue by rpagliarix** [pydata/pandas#10167]
create a file named logging.py anywhere as follows
#!/usr/bin/env python
print "hello"

Then
>>python
>>import pandas

you will get the following error
AttributeError: 'module' object has no attribute 'getLogger'

**Comment by shoyer** [comment]
Something strange is going on here with your Python configuration. Have you added the directory containing `logging.py` to your Python path? This is not a pandas bug -- pandas is simply using `import logging`, which it expects to be the standard library `logging` module.

**Comment by rpagliarix** [comment]
hi shoyer,
well yes, if logging.py is in the very same folder of the script from where I import pandas, there will always be issues. I was wondering what is the best way to avoid namespace conflicts. 

thank you,

**Comment by shoyer** [comment]
Pandas will not import your `logging.py` module unless you put the directory that contains it directly in the Python path, in conflict with the standard library's logging module. You do not want to be munging your Python path directly like this -- it's going to cause all sorts of problems, not just with pandas. Instead, run your code with relative imports or put your code in a package, and install that package.

**Comment by rpagliarix** [comment]
Hi shoyer,
it definitely does import logging.py 
I created it like above, and just by importing pandas (in a different script, but same directory) loading.py is loaded, and not the python logging module. 

Is there something I am missing?

**Comment by shoyer** [comment]
Run Python in a different directory (not related to your project) and type `import logging`. Is it the standard library module or your script `logging.py`?

**Comment by rpagliarix** [comment]
in that case, the standard library will be loaded.

**Comment by shoyer** [comment]
How did you install pandas?

**Comment by TomAugspurger** [comment]
I don't think this is a pandas thing. Replace pandas with `numpy` or `requests` and the same thing happens.

**Comment by shoyer** [comment]
Hmm. I mislead you because this issue doesn't appear when you `import pandas` from IPython. But indeed, it happens when you `import pandas` from the python command line:
```
$ touch logging.py
$ python -c 'import pandas'
Traceback (most recent call last):
....
AttributeError: 'module' object has no attribute 'getLogger'
```

The simple solution is not to name your own file after a standard library module. Nothing we can do to help you here, though.
