### ISSUE TITLE
Support 'interpolation' keyword in pandas.DataFrame.quantile and pandas.Series.quantile

### ISSUE THREAD

**Issue by rhkarls** [pydata/pandas#10174]
interpolation : {‘linear’, ‘lower’, ‘higher’, ‘midpoint’, ‘nearest’}

This would make it consistent with numpy.percentile options (new in 1.9). See http://docs.scipy.org/doc/numpy-dev/reference/generated/numpy.percentile.html

**Comment by jreback** [comment]
seems straightforward to pass this kw to ``np.percentile``. Want to do a PR?

**Comment by jreback** [comment]
xref #10207 . Let's do this in a separate PR though.

**Comment by jreback** [comment]
closed by #10174
