### ISSUE TITLE
How to use loc WITHOUT enlargement in pandas >0.14

### ISSUE THREAD

**Issue by mangecoeur** [pydata/pandas#10176]
It appears that `loc` now enlarges the result if an index is not found  - a behavior I find confusing, because 
```python
df.loc[['missing_label']]
```
gives a `KeyError` while 
```python
df.loc[['existing_label', 'missing_label']]
```
works just fine. Apparently this was changed in 0.15. I have older code that relied on catching errors for the case where some labels might be missing, which now doesn't work. How can I do a `loc` select, guaranteeing that I will get an error if a non-existing label is given - i.e. do the same as `loc` but without ever enlarging the result?

**Comment by jreback** [comment]
``df.loc['missing_label']``

**Comment by mangecoeur** [comment]
That isn't the behaviour I see:

```python
df = pd.DataFrame({'a':[1,2,3],
                   'b':[1,2,3],
                   'c':[1,2,3]
                  }, index=['x','y','y'])
```

```python
df.loc[['q']]
```
-> KeyError: "None of [['q']] are in the [index]"

```python
df.loc['q']
```
KeyError: 'the label [q] is not in the [index]'

```python
df.loc[['x', 'q']]
```

| idx | a | b | c |
| --- | --- | --- | --- |
| x  |	1  | 1 | 1 |
| q  | NaN | NaN | NaN |


The problem is that I might have a list-like with some valid and some invalid labels, and I want to throw an error if any of the labels are invalid.  `loc` no longer throws an error in that case, so does that mean I have to do the check manually now or is there another method to use?

**Comment by mangecoeur** [comment]
p.s. on pandas 0.16.1

**Comment by jorisvandenbossche** [comment]
@mangecoeur This behaviour of `df.loc[['x', 'q']]` returning an enlarged frame with a NaN row and not a KeyError is something I already see in 0.14.1.

The change in 0.15 was that `df.loc[['x', 'z'],:]` previously raised a KeyError and now is the same as `df.loc[['x', 'z']]` (enlarged frame).

**Comment by mangecoeur** [comment]
@jorisvandenbossche I'm not disputing the change. But you said "using a list-like, so it will always succeed", but using list likes with missing labels does the following:

`df.loc[['q']]` -> KeyError (none of labels are in index)
`df.loc[['w', 'q']]` -> KeyError (none of labels are in index)
`df.loc[['x', 'w', 'q']]` -> No error

It seems odd to get a failure if none of the labels are in the index but no failure if at least one item is in the index.

Moreover, if I want the KeyError behaviour (I was using `df.loc[['x', 'z'],:]` which is why it worked prior to 0.15) is there something like a non-enlarging `loc`, or do i have to implement a separate check?

**Comment by jreback** [comment]
You can use ``.ix`` for this. By definition ``.loc`` is quite strict. This is the reasoning behind raising ``KeyError`` if nothing is in the index (whether single element of list-like). 

```
In [14]: df.ix[['q','y']]
Out[14]: 
    a   b   c
q NaN NaN NaN
y   2   2   2
y   3   3   3

In [15]: df.ix[['q']]
Out[15]: 
    a   b   c
q NaN NaN NaN
```

**Comment by jorisvandenbossche** [comment]
Ah, you *were* using ``df.loc[['x', 'z'],:]``, that explains :-) (I was just confused because you used `df.loc[['x', 'z']]` above, which did not change recently)

But I see what you mean, but the discrepancy between `df.loc[['w', 'q']]` and `df.loc[['x', 'w', 'q']]` is the result of the 'at least one' rule we use. 
But in any case, if you want the KeyError behaviour in all cases, you will need to implement a separate check. For the future, a possibility would be to have a `strict` keyword or something `df.loc(strict=True)[['x', 'z']]`

**Comment by jorisvandenbossche** [comment]
@jreback yes, but I think @mangecoeur wants the opposite, not more flexible, but more strict, so also raising if only some of the labels are not in the index

**Comment by jreback** [comment]
@mangecoeur prob want to simply check yourself.

```
In [2]: df.index.isin(['q','y'])
Out[2]: array([False,  True,  True], dtype=bool)

In [3]: df.loc[df.index.isin(['q','y'])]
Out[3]: 
   a  b  c
y  2  2  2
y  3  3  3

In [4]: df.index.isin(['q','y']).any()
Out[4]: True

In [5]: df.index.isin(['q','y']).all()
Out[5]: False
```

**Comment by mangecoeur** [comment]
OK, I will add a check. @jreback @jorisvandenbossche thanks for the help!

**Comment by shoyer** [comment]
We've discussed this before. I agree that it would be better (if we were starting from scratch) to raise KeyError if any labels are found when doing list based indexing.... but it's probably too late to change that now.
