### ISSUE TITLE
Setting option 'display.max_seq_items' to None results in TypeError when pprinting index

### ISSUE THREAD

**Issue by JWarmenhoven** [pydata/pandas#10182]
According to the docstring, the following is allowed:
```Python
pd.set_option('display.max_seq_items', None)
```
With 0.16.1 this results in a TypeError when pretty printing an index. This is because the None value is compared against lenght of the index to see if we need to limit output.
```Python
TypeError: unorderable types: int() > NoneType()
```

**Comment by jorisvandenbossche** [comment]
Thanks for the report!

**Comment by jorisvandenbossche** [comment]
@JWarmenhoven https://github.com/pydata/pandas/pull/10183/files should fix it. Can you try this out? (you can just change that one line in the source code)

**Comment by JWarmenhoven** [comment]
You'll also need to change line 538 & 2559 into something like this for it to work.
```python
max_seq_items = get_option('display.max_seq_items') or len(self) 
```

**Comment by jorisvandenbossche** [comment]
Ah, yes, python 3. Thanks. Doing that means that the 'length' will never be shown, but maybe that is most consistent (only show that when truncated)?

**Comment by JWarmenhoven** [comment]
I see.
Why not always output the 'length' attribute, regardless whether the output has been truncated or not?
