### ISSUE TITLE
Performance drop when using timezone-aware DateTimeIndex

### ISSUE THREAD

**Issue by adrien-pain-01** [pydata/pandas#10192]
It seems that pandas.DataFrame operations on Index with timezone-aware dates is order of magnitude slower than on regular datetimes.

for a 500k datetimes created with pandas.date_range, and using DataFrame.shift() to compute deltas between dates, timings goes from **17ms** for standard datetimes to **16seconds** for timezone-aware datetimes.  

I don't understand why it is so slow with timezones objects.

I already posted a complete message related to this behavior on stackoverflow yesterday :
http://stackoverflow.com/questions/30385481/performance-of-timezone-aware-pandas-datetimeindex

I'm using latest pandas 0.16.1 from Anaconda, and latest numpy 1.9.2

**Comment by jreback** [comment]
see #8260 as this is a known issue.

datetimes with tz's are represented as ``object`` dtype, rather than ``datetime64[ns`` for datetimes. The fix is to implement #8260 which not difficult is a bit in depth as it requires learning a bit about the internals.

**Comment by adrien-pain-01** [comment]
@jreback:
thanks for your explanation and quick reply.
will wait then for the next major release to see the fix :-)

and really good work on pandas, awesome library !

**Comment by jreback** [comment]
closed by #10477
