### ISSUE TITLE
pandas diff().hist() produces inaccurate plot

### ISSUE THREAD

**Issue by Llewelyn62** [pydata/pandas#10201]
Using a df.diff().hist method creates a different (and inaccurate) multiple plot than using the matplotlib api.
My data are Super Rugby differential scores. The matrix of data is below.
```python
#Create base matrix of score differentials across Teams (row) x Round (col)
S15_Base = np.matrix([[-10,6,-24,0,28,43,-12,42,-5,-17,14,-6,41,0],#Crus
                       [10,-10,-5,0,4,-4,-24,8,0,5,-2,1,20,-17],#Reb
                       [44,-2,5,12,29,-15,0,17,-2,-5,13,-3,-1,10],#Brum
                       [-44,12,-7,-18,-29,0,-1,-8,-21,1,-16,0,-41,17],#Red              
                       [-14,-17,-3,3,-28,4,1,4,2,0,5,-2,5,-10],#Lion              
                       [14,4,29,0,7,7,24,5,0,-5,16,6,8,4],#Hurr
                       [-5,-11,-1,-3,-7,0,-12,-7,2,-6,-14,17,-20,5],#Blues
                       [5,2,24,-3,9,-1,10,7,0,17,8,-1,0,-4],#Chiefs
                       [-6,17,-8,-16,17,1,6,-42,-2,-7,0,-33,-8,-15],#Sharks
                       [6,0,1,-19,-17,-43,-10,-17,9,-1,-5,8,0,-21],#Cheetahs
                       [-12,-4,8,19,0,1,12,-4,21,7,-2,2,0,-5],#Bulls
                       [12,11,3,16,-9,0,-18,-5,14,7,2,-8,1,0],#Stormers
                       [-12,10,0,18,-7,15,12,0,-14,5,2,3,-7,15],#Waratahs
                       [12,-12,-29,-12,-4,-1,-6,0,-9,-7,-8,-17,7,0],#Force
                       [0,-6,7,3,7,-7,18,0,5,6,-13,33,-5,21],#Highlanders
                       ])
```
I create a dataframe with:
```
import pandas as pd
s15df = pd.DataFrame(S15_Base.T, columns=['Crusaders', 'Rebels', 'Brumbies', 'Reds', 'Lions', 'Hurricanes', 'Blues', 'Chiefs', 
                                      'Sharks', 'Cheetahs', 'Bulls', 'Stormers', 'Waratahs', 'Force', 'Highlanders'])
```
The following call produces the multiple plots by team:
```python
s15df.diff().hist(color='purple', alpha=0.5, figsize=(12,8),sharey=True,sharex=True,bins=20)
````
The result is different in at least one instance (for the Sharks, who never win by 60pts or more), yet have a bin reflecting this frequency. I checked using:
`s15df.Sharks.plot(kind='hist',bins=20)` and 
`fig = plt.figure()`
`ax = fig.add_subplot(111)`
`x = [s15df.Sharks ,s15df.Crusaders,s15df.Reds]`
`numBins = 20`
`ax.hist(x,numBins,color=['green','blue','red'],alpha=0.8)`
`plt.show()`

Both the latter two plots were identical and numerically correct, but different than the multiple plot. 

PS: Please forgive me if I err in any way posting this as an issue -- am a huge fan of pandas but novice in the issue-tracking thing! :)

**Comment by TomAugspurger** [comment]
This may be unrelated, but you your plot with all the teams you have `s15df.diff().hist(...)`, but in your other one you don't do the `.diff`.

Could you post images of what you see as well? Github let's you [embed them](https://guides.github.com/features/mastering-markdown/).

**Comment by Llewelyn62** [comment]
Ahh .. my apologies -- got this example from http://pandas.pydata.org/pandas-docs/stable/visualization.htmlat. Removing `diff()` corrects the problem I was having. 

What I had been attempting to do was plot several histograms against each other in the same plot-space so as to examine overlap, with a view to establishing the worth of creating distributions using max likelihood. The pandas.plot(kind='hist') doesn't seem to be able to do this so went to the option of multiple plots, an adequate work around. So the example I pasted to do this was: 
`In [27]: df.diff().hist(color='k', alpha=0.5, bins=50)`

Couldn't paste images from Ipynb to here sorry. Thank you for pointing the error out -- just a suggestion for less skilled, like myself, maybe change the example by removing the diff(). 
Also, this function is what I will now use to allow  multiple comparisons. (My humble attempt to fix as well as raise issues).
 ```python 
def Hist_plot(column_list, bins=10, color=['green','blue'],alpha=.3):
    '''This plots a list of series, obtained from columns
    column_list is, for example, [df.colA ,df.colB,df.colC]
    Default colors = ['green','blue']'''
    fig = plt.figure()
    ax = fig.add_subplot(111)
    x = column_list
    bins=bins 
    ax.hist(x,numBins,color=color,alpha=0.8)
    plt.show()`
Hist_plot([df.colA,df.colB])
```

**Comment by TomAugspurger** [comment]
For that I find it easiest to iterate over a groupby. 

For `group, series in ...: series.hist`
