### ISSUE TITLE
Panel.apply (2d) doesn't return a result of Series in 0.16.1

### ISSUE THREAD

**Issue by iriyaasagao** [pydata/pandas#10203]
Panel.apply (2d) doesn't return a result of Series in 0.16.1

y = panel.apply(lambda df: df + 1, axis=[1, 2])
--> Returns Panel. OK.

y = panel.apply(lambda df: df['Column'] + 1, axis=[1, 2])
--> Returns DataFrame. OK.

y = panel.apply(lambda df: df['Column'].mean(), axis=[1, 2])
--> Returns Series is expected. but got error as follows.

>   File "test.py", line 28, in <module>
>    y = panel.apply(lambda df: df['Column'].mean(), axis=[1, 2])
>   File "C:\Anaconda3\lib\site-packages\pandas\core\panel.py", line 969, in apply
>     return self._apply_2d(f, axis=axis)
>   File "C:\Anaconda3\lib\site-packages\pandas\core\panel.py", line 1068, in _apply_2d
>     return self._construct_return_type(dict(results))
>   File "C:\Anaconda3\lib\site-packages\pandas\core\panel.py", line 1124, in _construct_return_type
>     '[result->%s]' % (self, result))
> pandas.core.common.PandasError: invalid _construct_return_type [self-><class 'pandas.core.panel.Panel'>

**Comment by jreback** [comment]
you would have to show what the panel looks like and its elements. 

Here's an example of using ``.apply``

```
In [9]: p = tm.makePanel()

In [10]: p
Out[10]: 
<class 'pandas.core.panel.Panel'>
Dimensions: 3 (items) x 30 (major_axis) x 4 (minor_axis)
Items axis: ItemA to ItemC
Major_axis axis: 2000-01-03 00:00:00 to 2000-02-11 00:00:00
Minor_axis axis: A to D

In [11]: p.iloc[0]
Out[11]: 
                   A         B         C         D
2000-01-03  1.559708 -0.750264  0.373918 -1.087982
2000-01-04  0.635857 -1.381124 -0.978167 -0.312289
...              ...       ...       ...       ...
2000-02-10  0.521931 -0.039384 -2.514734  0.523842
2000-02-11 -0.969084  1.253346 -1.115830  1.034186

[30 rows x 4 columns]

In [12]: p.apply(lambda df: df + 1, axis=[1, 2]).iloc[0]
Out[12]: 
                   A         B         C         D
2000-01-03  2.559708  0.249736  1.373918 -0.087982
2000-01-04  1.635857 -0.381124  0.021833  0.687711
...              ...       ...       ...       ...
2000-02-10  1.521931  0.960616 -1.514734  1.523842
2000-02-11  0.030916  2.253346 -0.115830  2.034186

[30 rows x 4 columns]
```

**Comment by iriyaasagao** [comment]
I have found that this error is caused by data type of lambda function.

I opened new issue, #10332

Thanks.
