### ISSUE TITLE
series round ?

### ISSUE THREAD

**Issue by apiszcz** [pydata/pandas#10237]
Does .round support arbitrary precision rounding in Python 3.4.3/Pandas 0.16.1?

(Pdb) data['h'].round()
0      0
1     54
2     20
3    793
4     72
5     43
6     51
Name: h, dtype: float64
(Pdb) data['h'].round(1)
0      0.00000000000000000000000
1     54.10000000000000142108547
2     19.69999999999999928945726
3    793.00000000000000000000000
4     72.40000000000000568434189
5     42.79999999999999715782906
6     51.10000000000000142108547
Name: h, dtype: float64
(Pdb) data['h'].round(2)
0      0.00000000000000000000000
1     54.07999999999999829469743
2     19.67000000000000170530257
3    793.03999999999996362021193
4     72.39000000000000056843419
5     42.84000000000000341060513
6     51.06000000000000227373675

**Comment by shoyer** [comment]
Nope, this is not supported. Pandas uses floating point numbers or integers. It does not have a decimal type.

**Comment by jreback** [comment]
This ultimately just calls the numpy ufunc [around](http://docs.scipy.org/doc/numpy/reference/generated/numpy.around.html)
