### ISSUE TITLE
Disable networking in tests?

### ISSUE THREAD

**Issue by adnelson** [pydata/pandas#10238]
I'd like to run pandas tests but not have it do any tests that require networking. I can get the tests to pass if I disconnect from the internet on my machine, but otherwise I'm getting SSL errors. This might be because am building pandas with nix, but presumably there are other reasons why one might want to disable any tests that require networking -- regardless of whether networking is actually available.

Poking around through the tests code, it looks like there's a check [here](https://github.com/pydata/pandas/blob/d5fdbc6beb81ed2aa76bac9bb1c7dd2b7330617c/pandas/util/testing.py#L1451) which attempts to connect to google and skips the test if it's unable to do so. This, therefore, is *nearly* there. All that would be needed is to add an additional condition which would read a configuration option. For example an environment variable `PANDAS_NO_NET_TESTS` or something:

```python
        if check_before_test and not raise_on_error:
            if 'PANDAS_NO_NET_TESTS' in os.environ or not can_connect(url, error_classes):
                raise SkipTest
```

The particulars are relatively unimportant but the point is, is such a thing undesirable for some reason? Or should I perhaps make a pull request?

**Comment by jreback** [comment]
just run

``nosetests -A 'not network' pandas``

you can also skip the slow and/or disabled tests.
