### ISSUE TITLE
to_sql : MySQL identifier cannot be entirely numeric

### ISSUE THREAD

**Issue by jorisvandenbossche** [pydata/pandas#10255]
Reported at StackOverflow: http://stackoverflow.com/questions/30586292/valueerror-mysql-identifier-cannot-be-entirely-numeric-with-pandas-to-sql

MySQL supports numeric identifiers (if quoted) (http://dev.mysql.com/doc/refman/5.0/en/identifiers.html) 
@artemyk Was there a reason we explicitely disallowed this? (https://github.com/pydata/pandas/blob/v0.16.1/pandas/io/sql.py#L1287)

**Comment by artemyk** [comment]
@jorisvandenbossche Whoops!  I saw the following : "Identifiers may begin with a digit but unless quoted may not consist solely of digits" but did not pay attention to the "unless quoted".  Submitting a PR now.
