### ISSUE TITLE
Convert 1 dimensional iterables returned to .apply() columns to pd.Series

### ISSUE THREAD

**Issue by naught101** [pydata/pandas#10260]
As per http://stackoverflow.com/questions/30621887/return-a-column-vector-in-pandas-apply-with-different-length/30622209#30622209

It would be nice if an apply function automatically converted lists to pd.Series when they are returned to .apply(), in other words,

```{python}
import numpy as np
import pandas as pd

df = pd.DataFrame({'a':[0,10], 'b':[0,30]})

df.apply(lambda x: pd.Series(np.percentile(x, q=[10,20,30,40,50,75,100])), axis=0)
```
could become
```{python}
df.apply(np.percentile, axis=0, q=[10,20,30,40,50,75,100])
```

(np.percentile currently returns a list, unless `axis=` is supplied, and then it returns a list of arrays o_O )

**Comment by jreback** [comment]
You should just do this.

```
In [9]: df.quantile([.10,.20,.30,.40,.50,.75,1])
Out[9]: 
         a     b
0.10   1.0   3.0
0.20   2.0   6.0
0.30   3.0   9.0
0.40   4.0  12.0
0.50   5.0  15.0
0.75   7.5  22.5
1.00  10.0  30.0
```


You suggestion for apply is not inline with how pandas works.

**Comment by naught101** [comment]
Thanks, but that's just one example - what about for an arbitrary function that returns a 1D vector/list/iterable?

I don't really understand the last comment - is that because apply returns an index/column that is either the original values, or the groups (for aggregation)?

**Comment by jreback** [comment]
@naught101 

you are suggesting that pandas should somehow magically infer the result of this? how would it go about doing that?

**Comment by naught101** [comment]
Since you clearly know more about pandas than me, it's probably not worth your while asking me questions about it :P 

Apply receives the results from the func= function before it re-combines them, doesn't it? I guess the problem is that list items aren't all of one type? Couldn't you still do something like

```
try:
    result = pd.Series(result)
```

And just pass the error if that fails? (Sorry, on my phone)

**Comment by jreback** [comment]
@naught101 this might be ok in the sense that having pandas auto-wrapping a list-like with a Series. But it goes against the philosphy at bit here. You lose ALL meta data (e.g. the name of the Series and the index). So i think better to simply wrap the function call with a ``Series`` explicity by the user.

**Comment by naught101** [comment]
Fair enough. Thanks for the response :)
