### ISSUE TITLE
REL: 0.16.2

### ISSUE THREAD

**Issue by jreback** [pydata/pandas#10307]
going to release 0.16.2 this friday (11th). so don't add anything else to the milestone unless we discuss.

**Comment by jorisvandenbossche** [comment]
@jreback on pr #10232, it is still marked as 0.16.2, but this is maybe coming a bit close? (I would rather see this live in master a bit longer)

**Comment by jorisvandenbossche** [comment]
Regarding other issues, it would be nice to also deal with #10219 and #10161, as these are labeled as regressions (but don't have much time myself this week to look at it)

**Comment by jreback** [comment]
he seems to be updating for #10232 so I think this is ok

**Comment by jreback** [comment]
both those are very minor edge cases. They won't make it for this release.

**Comment by jreback** [comment]
@jorisvandenbossche I published the release, see [here](https://github.com/pydata/pandas/releases/tag/v0.16.2). Building artifacts now. Pls let me know when docs are up!

**Comment by jorisvandenbossche** [comment]
Building the docs now. Will give a notice in an hour or so when it's ready

**Comment by jorisvandenbossche** [comment]
Docs are up! http://pandas.pydata.org/pandas-docs/stable/index.html

**Comment by jreback** [comment]
ok, everything updates, just waiting for windows builds and then will send out the announcement.

**Comment by jorisvandenbossche** [comment]
Super!

**Comment by jreback** [comment]
@jorisvandenbossche I wanted to mention, pls have a look at the build-docs on the wiki and update anything if needed (e.g. you have adjusted the build process and/or used different deps). Further maybe it makes sense to have a ``ci/requirements-docs.txt`` ? (which can be the exact file you use)

**Comment by jreback** [comment]
release announcement [here](https://groups.google.com/forum/#!topic/pydata/slgCenzHrZU)

thanks everyone!
