### ISSUE TITLE
DOC: API docs broken with sphinx 1.3.x

### ISSUE THREAD

**Issue by jorisvandenbossche** [pydata/pandas#10316]
Just to track this on our side: as raised by @shoyer, there is a bug in the latest sphinx version that causes part of the API docs not to built.

Sphinx bug report: https://github.com/sphinx-doc/sphinx/issues/1822, pr: https://github.com/sphinx-doc/sphinx/pull/1828

**Comment by jorisvandenbossche** [comment]
Once this is solved, probably good to update the version used in our travis doc build (now it is 1.1.3) to just the latest sphinx.

**Comment by embray** [comment]
As a workaround you can subclass the Automodsumm extension and override the `get_items` method as demonstrated here: https://github.com/astropy/astropy-helpers/pull/148/files#diff-c95430c65faa667beb1feea7abfb3fd6R188

**Comment by jorisvandenbossche** [comment]
Just tested this, and it seems to work with the new sphinx release (>= 1.3.2). Only, now the accessor docs do not link correctly anymore in API overview.

**Comment by jorisvandenbossche** [comment]
As mentioned above, this is fixed in more recent versions of Sphinx, and the broken accessor docs are tracked here: #12161
