### ISSUE TITLE
to_excel : Excel Writer output limit 65,536

### ISSUE THREAD

**Issue by apiszcz** [pydata/pandas#10311]
Excel supports 1e6 rows with .xlsx files. I'm using to_excel  for a dataframe with >65,535 rows and am getting the error, User Warning ... since it exceeds Excel's limit of 65,530 'items' per worksheet. Are there any options that allow > 65K rows with .xlsx output files? BTW: to_csv works correctly.

**Comment by rockg** [comment]
Do you have the error trace and your versions?  I personally only use the csv methods as I'm on Linux but given that Excel support for more rows has existed for many years now I'm surprised to hear this is still a constraint.  I'll need more information to look further.

**Comment by apiszcz** [comment]
I reviewed the issued and .xlsx output format appears to be fine, .xls is
limited and throws the error. You can close this. Thank you.​

**Comment by rockg** [comment]
Great!
