### ISSUE TITLE
mapping with category data does not work

### ISSUE THREAD

**Issue by tnilanon** [pydata/pandas#10324]
```
import pandas as pd
a = pd.Series([1, 2, 3, 4])
b = pd.Series(["even", "odd", "even", "odd"], dtype="category")
c = pd.Series(["even", "odd", "even", "odd"])
​
print("-- map by category")
try:
    print(a.map(b))
except AttributeError as e:
    print(e)
​
print("-- map by string")
print(a.map(c))
```

has the following output:

> -- map by category
> 'Categorical' object has no attribute 'flags'
> -- map by string
> 0     odd
> 1    even
> 2     odd
> 3     NaN
> dtype: object

**Comment by jreback** [comment]
This is a trivial change [here](https://github.com/pydata/pandas/blob/master/pandas/core/series.py#L2012)

``.values`` -> ``.get_values()``

along with some tests of course

**Comment by tnilanon** [comment]
Thank you for such a quick response
