### ISSUE TITLE
Groupby - Apply method doesn't handle arguments correctly

### ISSUE THREAD

**Issue by neiseman** [pydata/pandas#10325]
The `apply` method on a groupby object appears to send all arguments to the applied function. As in, if you try to do `df.groupby(level='dt').apply(func, axis=1)`, the `axis=1` argument is passed to `func` rather than being parsed by `apply` as intended. The behavior is correct, however, in the `DataFrame.apply` method.

**Comment by jreback** [comment]
See [docs](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.core.groupby.GroupBy.apply.html?highlight=apply#pandas.core.groupby.GroupBy.apply)

you are probably looking to do:

``df.groupby(level='dt',axis=1).apply(func)``
