### ISSUE TITLE
df.fillna inplace bug 

### ISSUE THREAD

**Issue by VladMironov** [pydata/pandas#10342]
This code:

    a = df()
    a['f'] = [None, None]
    a['s'] = [None, None]
    a['t'] = [None, None]
    a.loc[:,['f','s']] = a.loc[:,['f','s']].fillna(-1) #works
    a.loc[:,'f'].fillna(-1, inplace=True) #also works
    a.loc[:,['f','s']].fillna(-1, inplace=True) #doesn't

It's not the biggest error, but still.

**Comment by shoyer** [comment]
please showed actual and expected output

**Comment by VladMironov** [comment]
Should be like this:
```python
 	f 	s 	t
0 	-1 	-1 	None
1 	-1 	-1 	None
```
But instead after a.loc[:,['f','s']].fillna(-1, inplace=True) you got this:
 	f 	s 	t
0 	None 	None 	None
1 	None 	None 	None

**Comment by jreback** [comment]
You are chained indexing, and operating on a copy (numpy is creating a copy here, for object type is often does this). See docs [here](http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy)

You should not use a chained ``inplace`` op, ever. It is pretty hard for pandas to detect this though.

Further, in general you should NOT be using ``object`` dtypes to represent numbers (which is what you get with ``None``). ``NaN`` is the missing value marker.

```
In [20]: id(a.values.base)
Out[20]: 4430108432

# so this is a view
In [19]: id(a.loc[:,'f'].values.base)
Out[19]: 4430108432

# this is a copy
In [18]: id(a.loc[:,['f','s']].values.base)
Out[18]: 4431376592
```
