### ISSUE TITLE
TST: run doc-tests

### ISSUE THREAD

**Issue by jreback** [pydata/pandas#10357]
need to add the option ``--with-doctest`` in ``ci/script.py`` to run doc tests. Lots of these fail at them moment though. 

We could run add these incrementally as the doc tests are fixed though, eg add lines line

``nosetests --with-doctest pandas/core`` after the main tester

**Comment by jorisvandenbossche** [comment]
Actually there was already an issue for this: #3439

**Comment by jreback** [comment]
closing this one as a dupe then. And I updated the other issue.
