### ISSUE TITLE
Code sample in pandas/core/categorical.py 

### ISSUE THREAD

**Issue by anushshetty** [pydata/pandas#10356]
The code sample in pandas/core/categorical.py needs a minor correction. In https://github.com/pydata/pandas/blob/master/pandas/core/categorical.py#L186:

```
>>> a = Categorical(['a','b','c','a','b','c'], ['c', 'b', 'a'])
>>> a.min()

```
Shouldn't a.is_ordered() come before a.min() ?

**Comment by jreback** [comment]
yep, looks like an error (as the default was ``ordered=True`` in < 0.15.1). care to do a pull-request to fix?

**Comment by anushshetty** [comment]
Will do.

**Comment by jreback** [comment]
closed by https://github.com/pydata/pandas/commit/3e35c842f37265ac7339908869d4cc7bdef784d9
