### ISSUE TITLE
pandas.read_msgpack(None) returns [78, 111, 110, 101]

### ISSUE THREAD

**Issue by sergeny** [pydata/pandas#10369]
It should return an error, as that's what it most likely is. 

If someone is really sending empty msgpacks out there to transmit [78, 111, 110, 101], they could add a special case.

**Comment by jreback** [comment]
yep, that should raise. The idea is you can simply pass a string or a file-like object (e.g. ``StringIO``). So needs to be a test for a ``.read`` method on the file-like, and otherwise raise. Want to do a pull-request?

**Comment by sergeny** [comment]
Yes, but it should work for strings, which have no `read()`. For example, the following should succeed: 

 `pandas.read_msgpack('\x87\xa5index\x85\xa5dtype\x07\xa3typ\xa5index\xa5klass\xaaInt64Index\xa4data\xa8\x00\x00\x00\x00\x00\x00\x00\x00\xa4name\xc0\xa4name\xc0\xa3typ\xa6series\xa8compress\xc0\xa5klass\xa6Series\xa5dtype\x07\xa4data\xa8\x01\x00\x00\x00\x00\x00\x00\x00')`

**Comment by jreback** [comment]
strings are allowed now
you just need to exclude not (strings or file-like)
