### ISSUE TITLE
Add note in docs for interpolate that Only `method=linear` interpolation is supported on MultiIndexes.

### ISSUE THREAD

**Issue by cancan101** [pydata/pandas#10371]
Trying to interpolate a DataFrame with MultiIndex:
```
lib/python2.7/site-packages/pandas/core/generic.pyc in interpolate(self, method, axis, limit, inplace, downcast, **kwargs)
   2868 
   2869         if isinstance(self.index, MultiIndex) and method != 'linear':
-> 2870             raise ValueError("Only `method=linear` interpolation is supported "
   2871                              "on MultiIndexes.")
   2872 

ValueError: Only `method=linear` interpolation is supported on MultiIndexes.
```
add a note [in the docs](http://pandas.pydata.org/pandas-docs/dev/generated/pandas.Series.interpolate.html).

**Comment by jorisvandenbossche** [comment]
@cancan101 thanks for the reports! (and feel free to open PRs for it :-))

**Comment by Winterflower** [comment]
@cancan101 link redirects to the Pandas docs front page. 
Here is a link to the doc paged referenced in the issue http://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.interpolate.html for anyone working on a PR and wondering which doc page should be amended.
