### ISSUE TITLE
str conversion to and comparison with datetime no longer working

### ISSUE THREAD

**Issue by pbbarnard** [pydata/pandas#10377]
It appears that appending a dataframe with a column containing string representations of dates, to a dataframe containing datetime objects now results in a column of mixed types, previously the strings were converted to datetime.  In addition filter operations using strings now no longer match the equivalent datetime objects.

This was working in 0.13.1, but no longer works in 0.16.1.

Example
=======

```
import pandas as pd
import datetime
import pprint
data1 = [{'a': 1, 'b': datetime.datetime(2015,06,10)},
        {'a': 2, 'b': datetime.datetime(2015,06,11)}]
df1 = pd.DataFrame(data1)

data2 = [{'a': 3, 'b': "2015-06-10"},
         {'a': 4, 'b': "2015-06-11"}]
df2 = pd.DataFrame(data2)

df = df1.append(df2)

pprint.pprint(df)
pprint.pprint(df['b'])

print("filtered table")

df = df[df['b'] == '2015-06-11']

pprint.pprint(df)
pprint.pprint(df['b'])

Output using 0.13.1
===============

   a          b
0  1 2015-06-10
1  2 2015-06-11
0  3 2015-06-10
1  4 2015-06-11

[4 rows x 2 columns]
0   2015-06-10
1   2015-06-11
0   2015-06-10
1   2015-06-11
Name: b, dtype: datetime64[ns]

filtered table
   a          b
1  2 2015-06-11
1  4 2015-06-11

[2 rows x 2 columns]
1   2015-06-11
1   2015-06-11
Name: b, dtype: datetime64[ns]

Output using 0.16.1
===============
   a                    b
0  1  2015-06-10 00:00:00
1  2  2015-06-11 00:00:00
0  3           2015-06-10
1  4           2015-06-11

0    2015-06-10 00:00:00
1    2015-06-11 00:00:00
0             2015-06-10
1             2015-06-11
Name: b, dtype: object

filtered table
   a           b
1  4  2015-06-11

1    2015-06-11
Name: b, dtype: object
```

**Comment by jreback** [comment]
you are appending an ``object`` dtype to a correctly typed ``datetime64[ns]``. This was a bug in 0.13.1 which 'worked', but failed in a lot of edge cases.

When appending if you don't have the same dtypes they will be coerced to a compatible type.

**Comment by pbbarnard** [comment]
OK, and just for clarity, I assume that you also apply the same logic to the comparison operation used in the filter...

**Comment by jreback** [comment]
The filtering is more flexible in that you can use strings that will be automagically converted to selectors, see [here](http://pandas.pydata.org/pandas-docs/stable/timeseries.html#datetimeindex-partial-string-indexing)
