### ISSUE TITLE
density plot on zero series throws exception

### ISSUE THREAD

**Issue by vumaasha** [pydata/pandas#10402]
```python 
    pd.Series(np.zeros(4)).to_frame().plot(kind='kde')
  ```

Executing the above line throws the below exception. 

```
LinAlgError                               Traceback (most recent call last)
<ipython-input-118-eac1a90078a2> in <module>()
----> 1 pd.Series(np.zeros(4)).to_frame().plot(kind='kde')
```

pandas version 0.16.2

**Comment by TomAugspurger** [comment]
We use scipy's gaussian kde.

```python
from scipy import stats
stats.kde.gaussian_kde([0, 0, 0])
```

I suppose the density is defined to be one in this case, but perhaps the failure is the bandwidth being zero since it's probably using Silverman's rule? You might raise this in the scipy repo, but I suspect that their kde isn't meant to be used on constant series.

**Comment by vumaasha** [comment]
I agree this is a scipy issue. However, when you try to plot a Dataframe without inspection, this throws up the nasty exception when such an attribute is encountered. Why dont we just log the exception and go ahead with plotting other columns in dataframe?

**Comment by TomAugspurger** [comment]
Hmm, good point I see how that's annoying. But I'm not a huge fan of warnings.  We could catch the exception and reraise with a more informative error message saying which column failed, making it easier to `df.crop([static_column], axis=1).plot(kind='kde')`. Would you be interested in submitting a pull request for that?

**Comment by vumaasha** [comment]
Yeah, sure. Let me give it a try.
