### ISSUE TITLE
Assign SparseDataFrame row-by-row error

### ISSUE THREAD

**Issue by jakezhaojb** [pydata/pandas#10403]
Hi,

I am trying to initialize a sparseDataFrame into block of memory and assign the value row-by-row, which ends up with:

    a = np.random.rand(4,5)
    b = pd.DataFrame(a)
    c = sparse.csr_matrix(a)
    d = pd.SparseDataFrame(index=b.index, columns=b.columns)
    elem = pd.SparseSeries(c[2].toarray().ravel())
    d.loc[[2]] = [ elem ]  # Got a NotImplementedError.
    elem = pd.Series(c[2].toarray().ravel())
    b.loc[[2]] = [ elem ]  # Yes.

Seems SparseDataFrame can't be assigned row-by-row, in the manner of assigning DataFrame by DataSeries. Any other method to implement it?

**Comment by jreback** [comment]
this would be completely inefficient to do this way. Create ``SparseSeries`` and concat / construct to form a ``SparseDataFrame`` is the best way. Pls have a read in the docs [here](http://pandas.pydata.org/pandas-docs/stable/sparse.html#interaction-with-scipy-sparse).
