### ISSUE TITLE
Unstack MultiIndex vs consecutive unstack

### ISSUE THREAD

**Issue by Lijantropique** [pydata/pandas#10416]
Hello,

If I try to unstack using multiIndex I got some groups divided. However, if I tried to do it by successive unstacking they are correctly grouped.  Please see image below

![image](https://cloud.githubusercontent.com/assets/5657134/8312620/b044c562-19ab-11e5-8f88-f338efdb4ae8.png)

I believe this is due to the fact that the first rows don't have n=3 for "actor" and the corresponding column is added only when it appears in a posterior row. Please note this issue is more related with presentation than performance as both operations yield the same results in subsequent processing (e.g. plotting).

Best!

**Comment by jreback** [comment]
See this issue [here](https://github.com/pydata/pandas/pull/9023) where this is discussed.

you want a simultaneous ``unstack``

**Comment by Lijantropique** [comment]
Hello jreback,

Thanks for the reply. After reading the discussion my impression is that pandas is already doing a simultaneous unstack, and considering the optional argument 'sequentially' was not added for unstack, I shouldn't do anything additional to get that behavior. Still I am not able to get the second table properly grouped. Maybe I am missing something.

best!
