### ISSUE TITLE
Writing as Excel with a MultiIndex is not yet implemented.

### ISSUE THREAD

**Issue by Owojori** [pydata/pandas#10410]
I get this error  "NotImplementedError: Writing as Excel with a MultiIndex is not yet implemented. 
when running the example  below(as described in your site):
"Generating Excel Reports from a Pandas Pivot Table.  "

**Comment by swayson** [comment]
I also notice this error cropping up in one of my projects. But on Pandas 0.15.2 I don't get this error...

**Comment by jreback** [comment]
see #9794 ; a broken excel file was almost always written. If it worked before it was accidental. The original issue is #4679 which is still open.

Easiest way to deal with this is to ``df.index = [....]`` before you write to make a single level index.
