### ISSUE TITLE
Pandas Interpolate Does not Handle Empty Values at Front of Series

### ISSUE THREAD

**Issue by cancan101** [pydata/pandas#10420]
[This code](https://github.com/pydata/pandas/blob/7d6fb510c1dfdbe7342f32f05ca5fd69b7854081/pandas/core/common.py#L1646) means the interpolator won't handle extrapolating to the front of the Series even though the underlying implementations may have no problem with the extrapolation. 

See for example [`UnivariateSpline`](http://docs.scipy.org/doc/scipy-0.15.1/reference/generated/scipy.interpolate.UnivariateSpline.html) whose default behavior is extrapolation.

Interpolation works fine at the end of the Series.

For example:
```python
s = pd.Series([1, 2, 3, 4, np.nan, 6, np.nan])
s.interpolate(method='spline', order=1)
0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: float64
```

but:
```python
s = pd.Series([np.nan, 2, 3, 4, np.nan, 6, 7])
s.interpolate(method='spline', order=1)
0   NaN
1     2
2     3
3     4
4     5
5     6
6     7
dtype: float64
```

**Comment by jreback** [comment]
hmm, I suppose that if the underlying can handle it then would be ok to change this. Try it and see if anything blows up. You might need to expand the tests a bit to make sure that this is all tested.

**Comment by lmjohns3** [comment]
This seems related to #9218 -- the only reason the values aren't filled at the beginning of the DataFrame/Series is that the fill for interpolate only happens forward.

**Comment by cancan101** [comment]
Sure. This lines in the referenced ticket seems to sum it up:
>The limit refers to forward filling only, even though interpolation is not inherently directional.

**Comment by lmjohns3** [comment]
Agreed.

Also see #10691 for an ongoing pull request/discussion.

**Comment by github-repo-health-uic** [comment]
> [This code](https://github.com/pydata/pandas/blob/7d6fb510c1dfdbe7342f32f05ca5fd69b7854081/pandas/core/common.py#L1646) means the interpolator won't handle extrapolating to the front of the Series even though the underlying implementations may have no problem with the extrapolation.
> 
> See for example [`UnivariateSpline`](http://docs.scipy.org/doc/scipy-0.15.1/reference/generated/scipy.interpolate.UnivariateSpline.html) whose default behavior is extrapolation.
> 
> Interpolation works fine at the end of the Series.
> 
> For example:
> 
> ```python
> s = pd.Series([1, 2, 3, 4, np.nan, 6, np.nan])
> s.interpolate(method='spline', order=1)
> 0    1
> 1    2
> 2    3
> 3    4
> 4    5
> 5    6
> 6    7
> dtype: float64
> ```
> 
> but:
> 
> ```python
> s = pd.Series([np.nan, 2, 3, 4, np.nan, 6, 7])
> s.interpolate(method='spline', order=1)
> 0   NaN
> 1     2
> 2     3
> 3     4
> 4     5
> 5     6
> 6     7
> dtype: float64
> ```

You can set limit_direction='both' . This is a parameter in the interpolation()
