### ISSUE TITLE
TST: Allow assert_numpy_array_equal to compare nan

### ISSUE THREAD

**Issue by sinhrks** [pydata/pandas#10427]
Related to #10373.  ``pandas`` ``assert_array_equal`` needs to be updated to perform ``nan`` comparison properly.

```
import numpy as np
import pandas as pd
import pandas.util.testing as pdt
import numpy.testing.utils as npt

npt.assert_array_equal(np.array([1, np.nan, 3]), np.array([1, np.nan, 3]))
# no AssertionError

pdt.assert_numpy_array_equal(np.array([1, np.nan, 3]), np.array([1, np.nan, 3]))
# AssertionError: [  1.  nan   3.] is not equal to [  1.  nan   3.].
```

**Comment by jreback** [comment]
no, this is the point of ``array_equivalent``. This is on purpose essentially ``np.array_equal``.

**Comment by sinhrks** [comment]
Thanks. Based on impl, there is no benefit to use ``assert_numpy_array_equal`` except for speed?

How about merging with ``numpy_array_equivalent`` to avoid confusion, assuming testing time is not so much affected  because  ``Series`` and ``DataFrame`` comparison is mostly done by ``assert_almost_equal``.

**Comment by jreback** [comment]
yes these should be the same

I think assert_numpy_array_equal is used much more

**Comment by sinhrks** [comment]
OK, let's deprecate ``assert_numpy_array_equivalent``. ``assert_numpy_array_equal`` is good for typing:)
