### ISSUE TITLE
unexpected behaviour when reindexing a Panel with MultiIndex

### ISSUE THREAD

**Issue by toniatop** [pydata/pandas#10437]
I was trying to reindex a Panel with a MultiIndex. The ultimate goal is to be able to do slicing like this:

    wp.loc[(1,slice(None)),:,:] #Access the panel fixing the first index of the multiIndex

But whenever I try to reindex, like in this example I got this strange behaviour.

    wp = pd.Panel(pd.randn(4, 5, 4), items=['Item_1_1', 'Item_1_2','Item_2_1','Item_2_2'],major_axis=['a','b','c','d','e'],minor_axis=['A', 'B', 'C', 'D'])
    a=[tuple([int(i) for i in item.split('_')[1:]]) for item in wp.items]
    swp=wp.reindex(items=x)

But when I try to access an item of the panel I got;

    In [101]: swp[1,1]
    Out[101]: 
        A   B   C   D
    a NaN NaN NaN NaN
    b NaN NaN NaN NaN
    c NaN NaN NaN NaN
    d NaN NaN NaN NaN
    e NaN NaN NaN NaN

The current workaround I have found is the following:

    def sp(string):
        s=string.split('_')
        return int(s[-3]),int(s[-1])

     wwp=wp.rename(items=sp)
     w=wwp.items.sortlevel(level=0)
     swwp=wwp.reindex(items=w[0])

I don't think that the first is something that is excepted, and the second way is quite complex for nothing, but I might be wrong. 
And now it is working at it should.

**Comment by jreback** [comment]
You don't have a multi-index in the first place. You need to create one explicity.

```
In [46]: wp = pd.Panel(pd.randn(4, 5, 4), items=pd.MultiIndex.from_product([range(2),range(2)]),major_axis=['a','b','c','d','e'],minor_axis=['A', 'B', 'C', 'D'])

In [47]: wp
Out[47]: 
<class 'pandas.core.panel.Panel'>
Dimensions: 4 (items) x 5 (major_axis) x 4 (minor_axis)
Items axis: (0, 0) to (1, 1)
Major_axis axis: a to e
Minor_axis axis: A to D

In [48]: wp.loc[(0,0)]
Out[48]: 
          A         B         C         D
a -0.084994 -0.653210 -0.404298 -2.500130
b  0.907593  0.078896 -0.998117 -1.167685
c -0.776501 -0.298755 -0.601618 -0.140084
d  0.370016  1.158117 -0.162282 -1.613040
e  0.852059  0.973698  0.757224 -0.621917

In [49]: wp.loc[(0,1)]          
Out[49]: 
          A         B         C         D
a -0.020449  1.094973 -1.252915  0.460252
b -1.749595 -0.312298 -0.116360  1.205130
c  1.421608  0.982935 -1.430015 -0.854789
d  1.044343  0.786917  1.527114 -1.098493
e  0.037582  0.744138  0.080397 -0.594863

In [50]: wp2 = wp.reindex(items=[(0,1),(0,0),(1,0),(1,1)])

In [51]: wp2.loc[(0,0)]
Out[51]: 
          A         B         C         D
a -0.084994 -0.653210 -0.404298 -2.500130
b  0.907593  0.078896 -0.998117 -1.167685
c -0.776501 -0.298755 -0.601618 -0.140084
d  0.370016  1.158117 -0.162282 -1.613040
e  0.852059  0.973698  0.757224 -0.621917
```

Further, I would for sure name these levels. And what you are doing is going to require explicty
tuple accessors always, e.g. ``wp.loc[(0,0)]``
