### ISSUE TITLE
Unclear UnicodeDecodeError exception.

### ISSUE THREAD

**Issue by startakovsky** [pydata/pandas#10434]
`<type 'exceptions.UnicodeDecodeError'> at /token
'ascii' codec can't decode byte 0xd7 in position 0: ordinal not in range(128)`

This is hard to understand.  I finally figured out the issue, and it was that strings and floats are being compared. I suppose now the error message makes sense. This is an issue related to an unclear error message.

Here is the line of code it points to, where `cc` is a string.  `df = df[df['my_col'] > cc)]`.

I am assuming this is the right place for this error, but please close this issue if that is not the case.

**Comment by jorisvandenbossche** [comment]
Can you give a small code sample that reproduces the problem?

**Comment by jorisvandenbossche** [comment]
Closing as this needs more information.
