### ISSUE TITLE
ENH: Convert datetimelike index to strings with astype(str) 

### ISSUE THREAD

**Issue by jorisvandenbossche** [pydata/pandas#10442]
xref #10110 

- [x] Fix ``.astype(str)`` on ``DatetimeIndex`` to use call ``.format()`` (Index method)

~~- [ ] Add ``Series.dt.format()`` accessor to call ``.format()``~~ (#10110 does this with ``.strftime``)

- [x] Change ``Series.astype(str)`` to call equiv of ``Series.dt.format()`` for ``datetime64[ns]`` dtype

Recently the ability to convert a datetimelike series to strings with `astype(str)` was introduced (#9758 by @evanpw):

```
In [27]: pd.Series(pd.date_range('2012-01-01', periods=3))
Out[27]:
0   2012-01-01
1   2012-01-02
2   2012-01-03
dtype: datetime64[ns]

In [28]: pd.Series(pd.date_range('2012-01-01', periods=3)).astype(str)
Out[28]:
0    2012-01-01T01:00:00.000000000+0100
1    2012-01-02T01:00:00.000000000+0100
2    2012-01-03T01:00:00.000000000+0100
dtype: object
```
it would be nice if this also possible on a index (now you still get the same error as previously for a series):
```
In [29]: pd.date_range('2012-01-01', periods=3).astype(str)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-29-68a28f79c8e9> in <module>()
----> 1 pd.date_range('2012-01-01', periods=3).astype(str)

C:\Users\vdbosscj\Scipy\pandas-joris\pandas\tseries\index.py in astype(self, dty
pe)
    692             return self.asi8.copy()
    693         else:  # pragma: no cover
--> 694             raise ValueError('Cannot cast DatetimeIndex to dtype %s' % d
type)
    695
    696     def _get_time_micros(self):

ValueError: Cannot cast DatetimeIndex to dtype |S0
```

**Comment by jreback** [comment]
sure, this is pretty easy.

this is competes a bit with ``.format()`` (which takes a formatting argument and is 'internal'; and the ``.strptime``, which I think is still outstanding). But ok by me

**Comment by jorisvandenbossche** [comment]
yes, for more control over the conversion the ``.format`` is certainly the preferred way to do, but for consistency with series this would be good.

Something else I was thinking: we are now using the numpy machinery I suppose to do the conversion, with the result that this also uses the odd numpy representation in local time:

```
`In [46]: s.astype(str)[0]
Out[46]: '2012-01-01T01:00:00.000000000+0100'

In [47]: str(s[0])
Out[47]: '2012-01-01 00:00:00'
```

Would it be possible to also have the second output for `astype`?

**Comment by jreback** [comment]
hmm, that's a problem, these should all go thru format (with no format specified) for consistency. Further I really though that we added ``.strptime``, but if we didn't ok. should also expose this as ``Series.dt.format`` then. I'll add a list to the top. All these pretty straightforward.
