### ISSUE TITLE
API/BUG: SparseSeries.shape ignores fill_value 

### ISSUE THREAD

**Issue by sinhrks** [pydata/pandas#10452]
``SparseSeries.shape`` seems to return incorrect result ignoring shapes filled by ``fill_value``.

```
s = pd.SparseSeries([0, 0, 1, 0], fill_value=0)
s
# 0    0
# 1    0
# 2    1
# 3    0
# dtype: int64
# BlockIndex
# Block locations: array([2], dtype=int32)
# Block lengths: array([1], dtype=int32)

len(s)
# 4

# must be (4, )?
s.shape
# (1,)

# OK
s._data.shape
# (4,)
```

**Comment by jreback** [comment]
This refers to the shape of the sparse values, not the shape of the series itself. 
```
In [19]: s._data.blocks[0].sp_values
Out[19]: array([1])

In [20]: s._data.blocks[0].sp_values.shape
Out[20]: (1,)
```

**Comment by sinhrks** [comment]
I see. This is a spec and not be fixed?

May be a option to fix docstring to say ``underlying`` means sparse values.

```
help(pd.SparseSeries.shape)
# return a tuple of the shape of the underlying data
```

**Comment by jreback** [comment]
I don't remember where exactly this is used and whether its just user-facing. If its user facing only, then it *should* be consistent and return the shape of a densified frame, and we should have a ``sparse_shape`` or something. I am not sure what this really should do. If you want to experiment and report back would be gr8.
