### ISSUE TITLE
Feature proposal: pandas vectorize decorator

### ISSUE THREAD

**Issue by twiecki** [pydata/pandas#10463]
`numpy` has a very useful `vectorize` decorator: http://docs.scipy.org/doc/numpy/reference/generated/numpy.vectorize.html that allows writing a function for scalars and then pass in arrays transparently. Under the hood, the function is called multiple times on subsets of the data.

I'm currently writing code that operates on a `Series` object. Some of those functions can also be passed in DataFrames and still work the same while some would require special logic. I think a pandas vectorize decorator could be very useful for these cases. In my specific case, I can just write that myself easily but I thought I'd bring it up. Perhaps this already exists and I just don't know about it.

**Comment by twiecki** [comment]
Here is a quick and dirty fast-pass:
```python
from collections import OrderedDict
import pandas as pd

def vectorize(func):
    def wrapper(df, *args, **kwargs):
        if df.ndim == 1:
            return func(df, *args, **kwargs)
        elif df.ndim == 2:
            # Call function on each column
            out = OrderedDict()
            multidim_output = False
            for col in df:
                out[col] = func(df[col], *args, **kwargs)
                if isinstance(out[col], pd.Series):
                    multidim_output = True
            if multidim_output:
                return pd.DataFrame(out)
            else:
                return pd.Series(out)

    return wrapper
```

**Comment by jreback** [comment]
this is essentially apply

**Comment by twiecki** [comment]
@jreback can that be used as a decorator?

**Comment by jreback** [comment]
pls show why you would want to actually do this

**Comment by twiecki** [comment]
This is an example function that works on a Series but not a DataFrame:
```python
def calc_alpha_beta(df_rets, benchmark_rets):
    ret_index = df_rets.index
    beta, alpha = sp.stats.linregress(benchmark_rets.loc[ret_index].values,
                                      df_rets.values)[:2]

    return alpha * 252, beta
```

With my decorator I just pass in a DataFrame too and it would magically work.

**Comment by twiecki** [comment]
You're saying I could do:
```python
# if series
calc_alpha_beta(rets_as_series, bmark)
# if dataframe
df_rets.apply(calc_alpha_beta, args=(bmark,))
# with decorator method
calc_alpha_beta(df_rets, bmark)
```

**Comment by jreback** [comment]
pass axis=1 and u have to pass the args in the function itself

**Comment by twiecki** [comment]
@jreback pass `axis=1` to `linregress` you mean? Note that the columns in the dataframe could have different lengths and I'd call `.dropna()` on them. Then there really is no way around a loop, so I think it's a legitimate case.

**Comment by twiecki** [comment]
So the `calc_alpha_beta` function is one of many in my library. Another one would be rolling sharpe ratio:
```python
def rolling_sharpe(df_rets, rolling_sharpe_window):
    return pd.rolling_mean(df_rets, rolling_sharpe_window) \
        / pd.rolling_std(df_rets, rolling_sharpe_window) * np.sqrt(252)
```

That one works on `DataFrame`s natively. So from an API standpoint it would be odd to have some functions that work on Series and DataFrames, and others that require you to use `.apply()`.

**Comment by jreback** [comment]
adding syntax that papers over non performant functions is just not a good idea

magically making things work on series which are often vectorized and data frames which may or may not is another trap

you can use .pipe to do this in any event

**Comment by twiecki** [comment]
Fair enough, just thought I'd bring it up as an idea, as I said I can just do that manually with my own decorator. `numpy.vectorize` certainly came in handy in many cases. It's slow but sometimes speed does not matter.

I don't see how pipe could be used here?

**Comment by twiecki** [comment]
Updated code:
```python
def vectorize(func):
    def wrapper(df, *args, **kwargs):
        if df.ndim == 1:
            return func(df, *args, **kwargs)
        elif df.ndim == 2:
            return df.apply(func, *args, **kwargs)

    return wrapper
```

**Comment by jreback** [comment]
``df.pipe(rolling_sharpe)``
