### ISSUE TITLE
BUG: query with invalid dtypes should fallback to python engine

### ISSUE THREAD

**Issue by DSLituiev** [pydata/pandas#10486]
The following call of `df.query()` produces an error:

    ...
    File "/Applications/anaconda/lib/python3.4/site-packages/numexpr/necompiler.py", line 629, in getType
    raise ValueError("unkown type %s" % a.dtype.name)

    ValueError: unkown type str128
in pandas 0.15.2

    # -*- coding: utf-8 -*-
    import re
    import pandas as pd
    
    def get_gene_site(tp):
        site = re.sub('T.$', '',tp)
        gene = site.split('%%')[0]
        t = int(re.search(r'T(\d+)$',tp).group(1))
        return gene, site, t
        
    sub_sample_list = ['Actb%%qeqwT0',
     'Actb%%qeqwT1',
     'Actb%%qeqwT2',
     'Actb%%qeqwT3',
     'Actb%%tralalaT0',
     'Actb%%tralalaT1',
     'Actb%%tralalaT2',
     'Actb%%tralalaT3',
     'Dummy%%rrrrT0',
     'Dummy%%rrrrT1',
     'Dummy%%rrrrT2',
     'Dummy%%rrrrT3',
     ]
     
    dict_samples = {'sample':[], 'gene':[], 'site':[], 'timepoint':[]}
    for tp in sub_sample_list:
        gene, site, t = get_gene_site(tp)
        dict_samples['sample'].append(tp)
        dict_samples['gene'].append(str(gene))
        dict_samples[ 'site'].append(site)
        dict_samples['timepoint'].append(t) 
        
    df = pd.DataFrame(dict_samples , 
                    columns = ['sample', 'gene', 'site', 'timepoint'])
    
    df.query('gene = "Actb"')

**Comment by jreback** [comment]
well, ``numexpr`` does not support this, nor are string ops actually passed. You should simply use regular indexing

``df[df.gene == "Actb"]``

I suppose this is a bug in that this should fall back to the python engine.
