### ISSUE TITLE
BUG: Index doesn't take over the Categorical name

### ISSUE THREAD

**Issue by sinhrks** [pydata/pandas#10482]
``Series`` can take over the ``Categorical.name``.

```
import pandas as pd
c = pd.Categorical([1, 2, 3], name='xxx')
pd.Series(c)
# 0    1
# 1    2
# 2    3
# Name: xxx, dtype: category
# Categories (3, int64): [1, 2, 3]
```

But ``Index`` doesn't.

```
pd.Index(c)
# CategoricalIndex([1, 2, 3], categories=[1, 2, 3], ordered=False, dtype='category')
pd.CategoricalIndex(c)
# CategoricalIndex([1, 2, 3], categories=[1, 2, 3], ordered=False, dtype='category')
```

**Comment by shoyer** [comment]
Why does `Categorical` have a `name` attribute at all? This seems strange to me, given that it's not a feature of other dtypes (which are just numpy arrays). @JanSchulz ?

**Comment by JanSchulz** [comment]
As far as I can see, that's a quite old property of `Categorical` from the time before a cat could be used as a `Block`.

This commit seems to have introduced the property: https://github.com/pydata/pandas/commit/ea1186da6a892ad9b66939c605554f4511816bbd 

From reading this commit and https://github.com/pydata/pandas/issues/292, it seems that the name is needed when a Categorical is (or was?) used in groupbys.

**Comment by jorisvandenbossche** [comment]
My first reaction is the same: categoricals shouldn't have a name at all. @JanSchulz any idea if this now still needed?

**Comment by JanSchulz** [comment]
@jorisvandenbossche See #10632 At least the changes all seem ok...

**Comment by sinhrks** [comment]
``name`` is being deprecated in #10632.
