### ISSUE TITLE
Feature Question: does pandas have a "groupsort" function?

### ISSUE THREAD

**Issue by lishaoyi** [pydata/pandas#10504]
Is there a hashtable based sort function in pandas to sort integer interchangeable dtype (dense) in O(n) time?

Not sure if the feature is the one mentioned in the link below. It's called groupsort.

http://wesmckinney.com/blog/tag/pandas/

**Comment by jreback** [comment]
you'll have to supply more detail

order n sort is a only in a very restricted way
not a general function

**Comment by lishaoyi** [comment]
Sure. I am sorting timeseries/dataframe based on a column of datatime64. Frequency is daily. Range of the date is known.

**Comment by jreback** [comment]
and? what is the problem/issue

**Comment by lishaoyi** [comment]
The problem/issue is: do I have a "groupsort" function in pandas to do the sorting in O(n) time, in this situation?

**Comment by jreback** [comment]
no, wes's post is applicable to group calculations where k << n. Here you are simply doing a sort.

though not clear on what you are actually trying to do.

see this: https://en.wikipedia.org/wiki/Radix_sort

fyi, the sorting is only sometimes necessary and usually not the limiting factor in most situation.
often times you can use partial sorts, eg. see [here](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.nlargest.html?highlight=nlargest#pandas.Series.nlargest)

**Comment by jreback** [comment]
```
In [1]: N = 10000000         

In [3]: s = Series(np.random.randint(0,N,size=N))

# quicksort
In [4]: %timeit s.order()
1 loops, best of 3: 2.64 s per loop

In [6]: %timeit s.order(kind='mergesort')
1 loops, best of 3: 2.44 s per loop

In [7]: s = Series(np.random.randint(0,4*N,size=4*N))

In [8]: %timeit s.order()
1 loops, best of 3: 14.9 s per loop
```

so 1.5x growth rate. I don't think this is a big deal. Of course if you think that you could implement a faster sort, then pull-requests are welcome. (counting sort/radix) actually would work, but you have to factorize first

```
# for the 40M
In [11]: %timeit pd.factorize(s)
1 loops, best of 3: 4.2 s per loop
```

So in theory you might have a small gain by doing this, but a lot of complexity.

**Comment by lishaoyi** [comment]
This is helpful. Thanks
