### ISSUE TITLE
Inconsistent handling of variables with missing values in groupby

### ISSUE THREAD

**Issue by mwaskom** [pydata/pandas#10524]
I found this behavior confusing.

```python
df = pd.DataFrame(dict(a=["a", "a", "a", "b", "b", "b"],
                       x=[True, True, False, True, np.nan, False]))
```

This works fine:

```python
df.x.mean()
0.59999999999999998
```

But this fails:

```python
df.groupby("a").x.mean()
---------------------------------------------------------------------------
DataError                                 Traceback (most recent call last)
<ipython-input-34-867769d888c3> in <module>()
----> 1 df.groupby("a").x.mean()

/Users/mwaskom/anaconda/lib/python2.7/site-packages/pandas/core/groupby.pyc in mean(self)
    698         """
    699         try:
--> 700             return self._cython_agg_general('mean')
    701         except GroupByError:
    702             raise

/Users/mwaskom/anaconda/lib/python2.7/site-packages/pandas/core/groupby.pyc in _cython_agg_general(self, how, numeric_only)
   1101 
   1102         if len(output) == 0:
-> 1103             raise DataError('No numeric types to aggregate')
   1104 
   1105         return self._wrap_aggregated_output(output, names)

DataError: No numeric types to aggregate
```

Happy to be kicked over to StackOverflow, but I cannot make heads or tails of this behavior.

**Comment by shoyer** [comment]
You'll notice `df.mean()` is also does not aggregate the column `x`:
```
In [8]: df.mean()
Out[8]: Series([], dtype: float64)
```

pandas looks at dtypes when deciding if it can aggregate a column or not. In this case, `x` ends up with `object` dtype. The aggregations do work if you use `astype(float)` on `x`.

Ultimately, I would probably blame this one on the lack of an boolean type with missing value support in numpy. It would probably be more robust to convert values like `[False, True, np.nan]` to float (like we do for integers), but at this point the ship may have sailed on making these sorts of conversions automatically.

**Comment by mwaskom** [comment]
Hm, I suppose that makes sense. In seaborn the approach is to duck-type numeric operations by trying to cast object arrays to float, but I'm not sure if that would be too much of a performance hit for you guys.

Is there a good way to do inline dtype conversion with groupby? One thing that would make this inconsistency easier to live with would be if 

```python
df.groupby("a").x.astype(float).mean()
```
worked, but currently it raises an `AttributeError`.

**Comment by mwaskom** [comment]
I actually should say in my actual application I've already dropped the nans by the time I get to the groupby, so it's just failing on an object array that is pure boolean -- could also provide another avenue for testing if numeric operations will work on an object array.

**Comment by jreback** [comment]
```
In [2]: df.assign(x1=df.x.astype(float)).groupby('a').x1.mean()
Out[2]: 
a
a    0.666667
b    0.500000
Name: x1, dtype: float64
```

**Comment by mwaskom** [comment]
Yeah I understand how to change the dtype of a variable before the groupby, it just feels cleaner to do it once you've reduced the operation chain to the particular column you're working on.

**Comment by shoyer** [comment]
Groupby methods map over each subgroup, and then concatenate together the results. So arguably `df.groupby("a").x.astype(float)` should just be a plain dataframe, not a groupby object.

**Comment by mwaskom** [comment]
Alright, fair.
