### ISSUE TITLE
BUG: 'base' argument when resampling TimedelataIndex has no effect

### ISSUE THREAD

**Issue by JonasAbernot** [pydata/pandas#10530]
```python
import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.normal(size=(100,4)))
df.index = pd.timedelta_range(start='0s', periods=100, freq='s')
print df.resample('10s',base=5)
```
The resampled index is still aligned to 0. 
The base argument seems to never be used, it doesn't raise any error when passing `base=1223456879`, or `base='gjhmljpouj'`, or even `base=df`

**Comment by jreback** [comment]
this is not implemented. I don't think very difficult to do this as its just a freq shift.

**Comment by arisliang** [comment]
This is marked as closed. But I still encounter the same thing that base doesn't do anything with version 0.23.4

**Comment by arisliang** [comment]
`
import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.normal(size=(3,4)))
df.index = [pd.Timestamp('2018-02-07'), pd.Timestamp('2018-06-22'), pd.Timestamp('2018-09-17')]
df.resample('6M',base=6)
`
