### ISSUE TITLE
Merging Index on Column Output Behavior

### ISSUE THREAD

**Issue by pmart123** [pydata/pandas#10538]
Merging two data frames, the first using the index, and the second using a column,with a left join has an unusual behavior.  Logically, the merged Dataframe should keep the index column, and discard the right Dataframe's join column(a right join logically has the reverse argument).  Here is an illustrative example:

```python

import pandas as pd
df1 = pd.DataFrame({'a':['bb','zz','dd'],'g':[10,20,30]})
df1.set_index(inplace=True)
df2 = pd.DataFrame({'a1':['aa','bb','zz','qq','tt','dd'],'b':[4,2,7,8,6,3]})

dfj = pd.merge(df1,df2,how='left',left_index=True,right_on='a1')

print(dfj)

    g  a1  b
1  10  bb  2
2  20  zz  7
5  30  dd  3

```

This deletes the index column, and outputs the right data frame's column.  I am not sure why this would be desirable over 'a' remaining the index, and only column b being added to the outputted data frame.

**Comment by TomAugspurger** [comment]
You might have a slight typo in your example. Should the second line be `df1.set_index('a', inplace=True)`?

I think your expectation is correct. I see the `left_index` / `right_index` options as being equivalent to a `.reset_index().set_index()`

```python
In [18]: pd.merge(df1.reset_index(), df2, how='left', left_on='a', right_on='a1').set_index('a')
Out[18]:
     g  a1  b
a
bb  10  bb  2
zz  20  zz  7
dd  30  dd  3
```

I'm not really sure why `a1` is even around now.

**Comment by pmart123** [comment]
Yes, sorry, typo.  Yes, I can look through, and see if I can spot something.

**Comment by pmart123** [comment]
From stepping through the merge calls, in _MergeOperation.get_result, the call:

```python
        result_data = concatenate_block_managers(
            [(ldata, lindexers), (rdata, rindexers)],
            axes=[llabels.append(rlabels), join_index],
            concat_axis=0, copy=self.copy)
```

returns a BlockManager with 'a1' as an index column.  Potentially, this could/should be remedied in the call:

```python
self._maybe_add_join_keys(result, left_indexer, right_indexer)
```

It looks like from the codebase, self._maybe_add_join_keys is the logical place we should swap the indexer?  Let me know if this is the case, and I can work on refactoring the conditional statements in the method.

**Comment by jreback** [comment]
@pmart123 I disagree on this. If you want to set the index when you have certain values of ``how``, e.g. ``left|right``, then what is returned becomes very odd.

you should just do this.

```
In [121]: df1.join(df2.set_index('a1'))
Out[121]: 
     g  b
a        
bb  10  2
zz  20  7
dd  30  3
```

**Comment by pmart123** [comment]
I disagree.  The current behavior is very inconsistent.  In the initial case I mentioned, the 'a' index is completely blown away, whereas:

```python
pd.merge(df1,df2.set_index('a1'),how='left',left_index=True,right_index=True)
Out[92]: 
     g  b
a        
bb  10  2
zz  20  7
dd  30  3
```

Keeps the index as the left DataFrame's name.  In one case, the left frame is taking precedence, and in the other case, the right frame is taking precedence.

**Comment by jreback** [comment]
@pmart123 if you step thru the join, then you will see this is exactly the merge that is generated.
