### ISSUE TITLE
Bug: type not maintained when using operators on subclass of Series

### ISSUE THREAD

**Issue by FRidh** [pydata/pandas#10545]
When working with a subclass of `Series` or a `DataFrame` the type is not maintained.

```py
In [1]: import pandas as pd

In [2]: class Subclassed(pd.Series):
   ...:     pass
   ...: 

In [3]: type(Subclassed(range(10)))
Out[3]: __main__.Subclassed

In [4]: type(Subclassed(range(10)) + Subclassed(range(10)))
Out[4]: pandas.core.series.Series

In [5]: pd.__version__
Out[5]: '0.16.2'
```

**Comment by jreback** [comment]
not generally recommended to subclass, but you need to define a few properties to make it work, see [here](http://pandas.pydata.org/pandas-docs/stable/internals.html#subclassing-pandas-data-structures)
