### ISSUE TITLE
COMPAT: allow multi-indexes to be written to Excel (even they cannot be read back in)

### ISSUE THREAD

**Issue by jreback** [pydata/pandas#10564]
xref https://github.com/pydata/pandas/issues/9794

**Comment by jreback** [comment]
cc  @onesandzeroes 

can you do a pull-request?

**Comment by flamingbear** [comment]
I can see if I can. if @onesandzeroes doesn't beat me too it.

**Comment by flamingbear** [comment]
jreback: "issue at #10564 though I think we need a argument to allow (so it can be turned on/off)"

@jreback Is the `index` argument not enough?  What would you want it called?  
We could warn, and add an argument not to warn. (particularly that the resulting xls file can't be read back by pandas)?

I'm also not seeing any tests around dataframes and to_excel.

**Comment by jreback** [comment]
https://github.com/pydata/pandas/blob/master/pandas/io/tests/test_excel.py#L1164

I think that a warning is appropriate here. I normally hate that but the reason for this is that this is a one-way serialization.
