### ISSUE TITLE
New GLIBC requirement?

### ISSUE THREAD

**Issue by michaelaye** [pydata/pandas#10573]
With master I currently get no error at compilation but then at import:

ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found

With 0.16.2 this does not happen. Is GLIBC_2.14 absolutely required for some new functionality? Why does the bubble not burst during `python setup.py install` then?

**Comment by jreback** [comment]
no idea 

make sure you clean before you build
try checking out 0.16.2 and building that

**Comment by michaelaye** [comment]
Yep, clean before install solved it, thanks. usually i never need to do that, so i should have tried that before.
