### ISSUE TITLE
DataFrame constructor fails when passed a list with an empty array.

### ISSUE THREAD

**Issue by santegoeds** [pydata/pandas#10585]
```Python
import pandas as pd
import numpy as np

data = {'a': np.empty(0)}

df = pd.DataFrame(data)
print df

rows, cols = data.values(), data.keys()
print rows, cols

df = pd.DataFrame(rows, columns=cols)
```

```
Empty DataFrame
Columns: [a]
Index: []
[array([], dtype=float64)] ['a']
Traceback (most recent call last):
  File "issue_2.py", line 12, in <module>
    df = pd.DataFrame(rows, columns=cols)
  File "/home/tjerk/dev/pandas/pandas/core/frame.py", line 251, in __init__
    arrays, columns = _to_arrays(data, columns, dtype=dtype)
  File "/home/tjerk/dev/pandas/pandas/core/frame.py", line 4951, in _to_arrays
    dtype=dtype)
  File "/home/tjerk/dev/pandas/pandas/core/frame.py", line 5010, in _list_to_arrays
    coerce_float=coerce_float)
  File "/home/tjerk/dev/pandas/pandas/core/frame.py", line 5068, in _convert_object_array
    'columns' % (len(columns), len(content)))
AssertionError: 1 columns passed, passed data had 0 columns
```

INSTALLED VERSIONS
------------------
commit: e51d5cf1b09554ceb182ca71cc02b716277a5a08
python: 2.7.10.final.0
python-bits: 64
OS: Linux
OS-release: 3.13.0-57-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8

pandas: 0.16.2-138-g2b801b6
nose: 1.3.7
Cython: 0.22.1
numpy: 1.9.2
scipy: None
statsmodels: None
IPython: 3.2.1
sphinx: None
patsy: None
dateutil: 2.4.2
pytz: 2015.4
bottleneck: 1.0.0
tables: 3.2.0
numexpr: 2.4.3
matplotlib: None
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: 4.4.0
html5lib: 0.999
httplib2: None
apiclient: None
sqlalchemy: None
pymysql: None
psycopg2: None

**Comment by jreback** [comment]
that's as expected. its very similar to

``DataFrame([[]],columns=['a'])``

its inferring this as an list-of-list-likes so the shape of the inside array has to match the columns

e.g.
``DataFrame([np.ones(1)], columns=['a'])`` is good
while anything else (e.g. np.ones(0) or np.ones(2)) will fail

if you don't want that, don't pass the columns in
