### ISSUE TITLE
DataFrame.resample Can Be Very Innaccurate With Timedelta Rule

### ISSUE THREAD

**Issue by mgabel-stratoscale** [pydata/pandas#10580]
DataFrame.resample() is not accurate, at least when using time delta as rule. 
This is because it does not interpolate between values when up-sampling, nor does aggregation take into account the exact sampling point when down-sampling. When a new sampling point falls between two original samples:
* when up-sampling, the only option is to select one of them or leave NaN (fill_method)
* when down-sampling, simple aggregators such as mean do not consider the distance between the new sampling point to the others. When trying to pass an aggregator function, pandas does not tell it exactly where the new sample point falls either.

Consider a simple example which generates three linear series in a DataFrame of length 10 seconds with exactly 10 points.

### Down-sampling
Let's try down-sampling to 6 points (over the same length of 10 seconds) using DataFrame.resample() and using scipy.interpolate.interp1d().

![resampled_6](https://cloud.githubusercontent.com/assets/13135979/8696874/0c4ee49c-2af9-11e5-979d-eae6c744ccd8.png)

Black dots are the original samples, colored lines and X's are the resampled data.
First, DataFrame.resample (left figure) actually **misses** the original points entirely.
Second, note the distortion near 09:00:06 and 09:00:07 where the slope of the interpolated data is simply wrong. This is exactly the sort of problem that happens when the exact position of the new sample is not taken into account.

Compare to the scipy.interpolation.interpolate (right figure) which interpolates the original (and correct) lines exactly.

### Up-sampling
Let's try up-sampling to 16 points (over the same length of 10 seconds).

![resampled_16](https://cloud.githubusercontent.com/assets/13135979/8697005/0f8c2f7e-2afa-11e5-8cde-a1f6223a7c4c.png)

Again, we see inaccuracies and "stairs", and again, simple linear interpolation with scipy produces the correct result.

### Code
The following code reproduces the above figures. This code uses how='mean' for resample(). Using fill_method='bfill' or 'ffill' gives even worse results.

```python
import pandas as pd
from scipy.interpolate import interp1d  
import numpy as np
import matplotlib.pylab as pl

n = 10
x = pd.date_range(start='2015-07-13 9:00:00', freq='S', periods=n)
y = np.vstack([range(n), range(n+1,1+2*n), range(1,2*n+1,2)]).T
df = pd.DataFrame(y, index=x)

def PandasResample(df, length):
    td = (df.index[-1] - df.index[0]) / (length-1)
    return df.resample(td, how='mean').interpolate() # Handle NaNs when upsampling

def CorrectResample(df, length):
    time_delta = (df.index[-1] - df.index[0]) / (length-1)
    new_index = pd.date_range(start=df.index[0], end=df.index[-1], freq=time_delta)
    f = interp1d(df.index.astype('i8'), df.values.T)
    return pd.DataFrame(data=f(new_index.astype('i8')).T, index=new_index)
    
def PlotComparison(a, b, ax, title):
    a.plot(ax=ax, style='ko', legend=False)
    b.plot(ax=ax, style='x-', title=title)

def TryLength(new_length):
    dfa = PandasResample(df, new_length)
    dfb = CorrectResample(df, new_length)
    fig, ax = pl.subplots(1,2, figsize=(12,6))
    PlotComparison(df, dfa, ax[0], 'DataFrame.resample')
    PlotComparison(df, dfb, ax[1], 'scipi.interpolate')
    pl.suptitle('Resample to %d' % new_length)
    pl.savefig('resampled_%d.png' % new_length)
    
    
TryLength(6)    
TryLength(16)    
pl.show()
```

I'm using pandas 0.16.2 from WinPython 2.7.10.1 x64.
I can provide show_versions() if needed, but this issue is long enough already :)

**Comment by jreback** [comment]
You are trying to compare resample and interpolation which are completely different. Resample creates the bins according to the rule. If something falls in a bin then the how gets applied. This is really just a group-by.

Interpolation on the other hand generates the bins and looks at ALL of them them to decide how to put the values.

If you want a generated point where you don't have a bin then interpolation is reasonable. If you want to reduce a bunch of points that are possibly irregular then resample is used.

```
In [77]: df
Out[77]: 
                     0   1   2
2015-07-13 09:00:00  0  11   1
2015-07-13 09:00:01  1  12   3
2015-07-13 09:00:02  2  13   5
2015-07-13 09:00:03  3  14   7
2015-07-13 09:00:04  4  15   9
2015-07-13 09:00:05  5  16  11
2015-07-13 09:00:06  6  17  13
2015-07-13 09:00:07  7  18  15
2015-07-13 09:00:08  8  19  17
2015-07-13 09:00:09  9  20  19

In [78]: df.resample(Timedelta('1.8s'),how='mean')
Out[78]: 
                            0      1      2
2015-07-13 09:00:00.000 0.500 11.500  2.000
2015-07-13 09:00:01.800 2.500 13.500  6.000
2015-07-13 09:00:03.600 4.500 15.500 10.000
2015-07-13 09:00:05.400 6.500 17.500 14.000
2015-07-13 09:00:07.200 8.000 19.000 17.000
2015-07-13 09:00:09.000 9.000 20.000 19.000
```

**Comment by TomAugspurger** [comment]
And FYI we do have the `.interpolate` method (which can call the spicy routines).


```python
In [34]: df.reindex((df.index + td / 2) | df.index).head()
Out[34]:
                          0   1   2
2015-07-13 09:00:00.000   0  11   1
2015-07-13 09:00:00.500 NaN NaN NaN
2015-07-13 09:00:01.000   1  12   3
2015-07-13 09:00:01.500 NaN NaN NaN
2015-07-13 09:00:02.000   2  13   5

In [37]: df.reindex((df.index + td / 2) | df.index).interpolate().plot()
Out[37]: <matplotlib.axes._subplots.AxesSubplot at 0x11d0df1d0>
```
![gh](https://cloud.githubusercontent.com/assets/1312546/8698172/0c52ab28-2ac1-11e5-901c-43994ea5ad6c.png)

**Comment by mgabel-stratoscale** [comment]
I am trying to resample in the signal processing sense of the word: I have a sampled signal of length N covering interval T, and I want to resample it to length K with the same interval, meaning the sampling rate changes from N/T to K/T. This is resampling as I know it. Obviously there is a jargon issue here.

From what I can see,  pandas.resample is the only way to do that. pandas.interpolate cannot change the length of the DF. The problem is that pandas.resample loses too much information on the way.

**Comment by mgabel-stratoscale** [comment]
TomAugspurger: note the final point in your figure, where the line slow is incorrect. I Don't know if it's an artifact of the drawing code.

Also note that your new samples are evenly spaces between the original ones (0.5, 1.5, 2.5) which is exactly the situation where pandas resampling is sufficient.

I'd very much like to know how to achieve correct resampling *when the new length does not evenly divide the old length or vice versa*.

**Comment by TomAugspurger** [comment]
The "slowdown" at the end comes from from us / scipy not *extrapolating* outside the original bounds

```python
In [40]: df.reindex((df.index + td / 2) | df.index).interpolate().tail()
Out[40]:
                           0     1   2
2015-07-13 09:00:07.500  7.5  18.5  16
2015-07-13 09:00:08.000  8.0  19.0  17
2015-07-13 09:00:08.500  8.5  19.5  18
2015-07-13 09:00:09.000  9.0  20.0  19
2015-07-13 09:00:09.500  9.0  20.0  19
```

I believe there's an option for this. For the non-even division.

```python
In [59]: length = 16

In [60]:     time_delta = (df.index[-1] - df.index[0]) / (length-1)

In [61]:     new_index = pd.date_range(start=df.index[0], end=df.index[-1], freq=time_delta)

In [62]: df.reindex(new_index).interpolate().plot()
```
![gh](https://cloud.githubusercontent.com/assets/1312546/8698399/7837b296-2ac3-11e5-9cbf-6be93f4b5ced.png)

**Comment by mgabel-stratoscale** [comment]
Thank you, that indeed works for both up and down sampling. I actually tried exactly the same code, except I used 'resample()'. Turns out I simply needed `reindex()` . That's a bit surprising, to be honest, as nothing in `reindex()` doc suggests it will do interpolation.

Anyway, thanks again!

**Comment by TomAugspurger** [comment]
There's a section in the docs [here](http://pandas-docs.github.io/pandas-docs-travis/missing_data.html#interpolation)  (search for `interpolation at new values`), not that I blame you for not seeing that. I'm not really happy with that API since as you say `reindex`isn't interpolation. It's just a step *before* the interpolation.

**Comment by mgabel-stratoscale** [comment]
I actually read it but I couldn't figure out how to get the correct values to interpolate *from* (which is what `reindex()` does). I guess I just assumed `resample()` is what I need to get these values from, but I couldn't find a way to make it return the correct values.
Live and learn. Thank you.

**Comment by jreback** [comment]
@TomAugspurger so suppose its worthwhile to maybe have a short section in resample to elaborate on the differences between interpolation and resample (with a cross-link to interpolation). E.g. when/why to reindex to the points of interest first.

@mgabel-stratoscale interested?

**Comment by mgabel-stratoscale** [comment]
Sorry, I am now fairly sure I don't actually know the differences either.
I'm just starting with pandas though.
