### ISSUE TITLE
CI: migrate to travis container infrastructure

### ISSUE THREAD

**Issue by jreback** [pydata/pandas#10598]
http://docs.travis-ci.com/user/migrating-from-legacy/

trivial I think to remove the ``sudo``. but prob have to change some stuff (as we
use *some* apt stuff)

currently we externally cache, so that would have to be figure out (at a later date is ok)

**Comment by bashtage** [comment]
I haven't seen any major improvements in testing speed when using this.  I switched pandas-datareader to this and the build time dropped form 3 to 1.5, which is something for a small project.

In terms of buidl time, I don't think it woudl do much for pandas.  However, if you get faster access to build servers then it could be worth it - the backlog of PRs can get pretty big at times.

**Comment by jreback** [comment]
@bashtage thanks for the fb.

I have actually been noticiing that travis *seems* to be building faster lately (on the old infrastructure).

I think main benefit is we *could* use the travis caching (as opposed to the only pyx build cache that we use from iron-cache).

**Comment by jreback** [comment]
Might be a good reference: https://github.com/libdynd/libdynd/pull/481
also scipy recently changed.

**Comment by nparley** [comment]
It seems that the travis job `27_slow_nnet_LOCALE` is having problems with the container-based infrastructure. Also travis is not detecting the use of sudo and is running in containers on my fork at least. Compare https://travis-ci.org/nparley/pandas/jobs/124695152 and https://travis-ci.org/nparley/pandas/jobs/124778492. I have created a PR to add sudo: required for the time being.
