### ISSUE TITLE
DOC: Add more examples for Series resampling in tutorials

### ISSUE THREAD

**Issue by Winterflower** [pydata/pandas#10594]
It would be nice to see more resampling examples in the Tutorials section [here] (http://pandas.pydata.org/pandas-docs/stable/timeseries.html). 
Some examples I am working on for this:

* example using custom `how` function
* example showing how to use `base`

**Comment by jorisvandenbossche** [comment]
And more here: https://github.com/pydata/pandas/issues/5023

**Comment by jorisvandenbossche** [comment]
Let's add the different items there.

**Comment by jorisvandenbossche** [comment]
@Winterflower if you see more items to improve, just add it as a comment to the other issue. And certainly feel free to tackle some of those!
