### ISSUE TITLE
ENH: Add "select all" option for duplicates

### ISSUE THREAD

**Issue by nickeubank** [pydata/pandas#10592]
How would people feel about me adding a "select_all" option to duplicates / duplicated that returns all duplicated rows, not just all but first or all but last?

I often check to see if I have duplicates by some primary key, and if I do, I then want to look at ALL rows with the same primary key. Right now, duplicates / duplicated won't do so and I need to use the following hack:
   
    df[df.duplicated('key',take_last=True) | df.duplicated('key')]

It seems I"m not the only person with this issue: 
http://stackoverflow.com/questions/26244309/how-to-analyze-all-duplicate-entries-in-this-pandas-dataframe
http://stackoverflow.com/questions/14657241/how-do-i-get-a-list-of-all-the-duplicate-items-using-pandas-in-python
http://stackoverflow.com/questions/23667369/drop-all-duplicate-rows-in-python-pandas

Happy to write PR if people support.

**Comment by jreback** [comment]
generally it makes more sense to groupby if you are going to work with duplicates other than the simpler cases that ``duplicated`` does

**Comment by nickeubank** [comment]
you mean something like ```df[df.groupby('key').count()>1]``` ? 

Seems like this particular situation isn't an uncommon use-case, and seems like a ```select_all``` option would really help make code readable. That's why programs like Stata offer this functionality (like the ```duplicates tag``` command).

**Comment by sinhrks** [comment]
I think this is covered in #10236.

**Comment by nickeubank** [comment]
Yup, thanks @sinhrks ! Excited to see it merged!
