### ISSUE TITLE
TST: test_read_famafrench fails with HTTP 404

### ISSUE THREAD

**Issue by sinhrks** [pydata/pandas#10591]
Not look into detail because I'm out, filenames seem to be changed.

http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/data_library.html

**Comment by jreback** [comment]
pls report on ``pandas-datareader`` repo.

**Comment by sinhrks** [comment]
@jreback It fails on current master, and it uses ``pandas.io.data`` yet. us it OK to remove the test cases from pandas, and fix in datareader?


https://travis-ci.org/pydata/pandas/jobs/71088889

**Comment by jreback** [comment]
I guess might as well fix in both

**Comment by jreback** [comment]
ok, this is annoying. Skipping the test for now: https://github.com/pydata/pandas/commit/e023f2f7d7739ab0c509d53f97066b6e60b04917
