### ISSUE TITLE
API: change default in to_datetime for errors to 'raise'

### ISSUE THREAD

**Issue by jreback** [pydata/pandas#10636]
xref #8894 
xref #10615 
xref #10154

The idea is that if you have completely unparseable dates with or w/o a format specified, then the default will be to raise. Further, since ``coerce`` is by default ``False``. You will get an immediate exception rather than have strings returned.

I think some tests will need to be adjusted and a simple example for the user in the whatsnew.

**Comment by shoyer** [comment]
Agreed, this is a good idea.

**Comment by chris-b1** [comment]
To summarize latest current behavior (in #10615)  - here is what happens to invalid string data - same whether format specified or not.  Default is `(coerce=False, errors='ignore', format=None)`

| coerce | errors   | Invalid    |
|--------|----------|------------|
| FALSE  | 'ignore' | Return obj |
|     FALSE   | 'raise'  | Raise      |
| TRUE   | either     | Return NaTs       |

**Comment by vincentdavis** [comment]
@chris-b1 I was think about the grid you made above. Why not have 1 keyword arg that can be 3 different values, (raise, ignore, NaTs) Would it not simplify the code to not have to search for coerce or error handling but only whatever this new keyword would be. It would be possible to convert coerce and coerce to the new keyword for backward compatibility. The new keyword default would be 'raise'.

Should coerce=True error=raise be rejected?

**Comment by jorisvandenbossche** [comment]
I agree with @vincentdavis that the two keywords `errors` and `coerce` don't need to be two different ones, as they are actually mutually exclusive (which makes it even confusing what you should expect when combining those two, eg the example of  coerce=True error=raise). 
I wanted to propose to just integrate `coerce` into the `errors` keyword, giving that one then an extra option: `'ignore'|'raise'|'coerce'` (this should also be possible in a backwards compatible change).

And then the change of the actual default value is of course another discussion. But I am personally +1 to change it to `'raise'`.

Also note that the actual stable behaviour (in the latest release) depended on whether you supplied the `format` keyword or not. The table above provided by @chris-b1 was valid for the default case, but when providing a date that could not be parsed following a provided format, this would raise regardless of `errors='ignore'`. 
So this is another reason to change the default to raise to unify this behaviour.

**Comment by jorisvandenbossche** [comment]
As the discussion about `coerce` is not really linked to the change of the default value to'raise', I opened a separate issue for that: #10653

**Comment by jorisvandenbossche** [comment]
I also mentioned this discussion on the mailing list, as it backwards incompatible change: https://groups.google.com/forum/?fromgroups#!topic/pydata/Ef_xP7zQOTc

**Comment by bwillers** [comment]
Having been bitten by the silent failure in to_datetime on a few occassions, would love to see this change.
