### ISSUE TITLE
pd.Series.interpolate(method='spline') Error

### ISSUE THREAD

**Issue by JianxunLi** [pydata/pandas#10633]
Although in docs it says `method='spline'` is a choice, but it raises a `ValueError`.

    import numpy as np
    import pandas as pd

    np.random.seed(1)
    s = pd.Series(np.arange(10)**2)
    s[np.random.randint(0,9,3)] = np.nan
    s.interpolate(method='spline')

    # raise ValueError
    ValueError: invalid method 'spline' to interpolate.

**Comment by jreback** [comment]
I believe this was just fixed in master
can u try?

**Comment by TomAugspurger** [comment]
That's using the `scipy` `[`interp1d`](http://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.interp1d.html#scipy.interpolate.interp1d) function which requires an order parameter when you call it. order=1 is linear, 2 is quadratic, and 3 is cubic.

If you want we could provide a more informative error message.

**Comment by souravsingh** [comment]
I would like to work  on this bug.How do I start?

**Comment by TomAugspurger** [comment]
There are some instructions here: https://github.com/pydata/pandas/wiki/Contributing.

For this one you'll need to check if the interpolation method is `spline` and check if they don't have an `order` keyword argument.

**Comment by jorisvandenbossche** [comment]
Nowadays, there is also a guide in the docs: http://pandas.pydata.org/pandas-docs/stable/contributing.html

**Comment by jreback** [comment]
closed by #10880

**Comment by eliezerpekar** [comment]
Still fails in version 0.20.3, using the same test code as JianxunLi's.

**Comment by jorisvandenbossche** [comment]
Please read the responses. You need to pass an `order`

**Comment by jefffriesen** [comment]
This still fails in 0.22.0 after merging https://github.com/pandas-dev/pandas/pull/10880/files using @JianxunLi 's code. I know you have to pass an `order` and that does work. But the error when not passing an `order` still says this without referencing `order`:

```
ValueError: invalid method 'spline' to interpolate.
```
