### ISSUE TITLE
to_dense does not preserve dtype in SparseArray

### ISSUE THREAD

**Issue by ebolyen** [pydata/pandas#10648]
This isn't a huge deal, but it seems a little odd:

```python
In [1]: import pandas as pd

In [2]: a = pd.SparseArray([True, False, False, False, True], fill_value=False, dtype=bool)

In [3]: a
Out[3]: 
[True, False, False, False, True]
Fill: False
IntIndex
Indices: array([0, 4], dtype=int32)

In [4]: a.dtype
Out[4]: dtype('bool')

In [5]: d = a.to_dense()

In [6]: d
Out[6]: array([ 1.,  0.,  0.,  0.,  1.])

In [7]: d.dtype
Out[7]: dtype('float64')
```

I would have expected `d` to retain the dtype of `bool`. I can cast down, but I am still wasting 7 bytes per element in the process.

**Comment by ebolyen** [comment]
INSTALLED VERSIONS
------------------
commit: None
python: 2.7.6.final.0
python-bits: 64
OS: Linux
OS-release: 3.13.0-57-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

pandas: 0.16.2
nose: 1.3.7
Cython: 0.22.1
numpy: 1.9.2
scipy: 0.15.1
statsmodels: None
IPython: 3.2.0
sphinx: 1.2.2
patsy: None
dateutil: 2.4.2
pytz: 2015.4
bottleneck: None
tables: None
numexpr: None
matplotlib: 1.4.3
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: None
pymysql: None
psycopg2: None

**Comment by jreback** [comment]
prob a bug, not really well tested and not really a lot of dev support in sparse 
pull requests are welcome

**Comment by ebolyen** [comment]
I may be speaking too soon, but after skimming the code for this, it looks pretty simple to fix. I'll work on a PR!
