### ISSUE TITLE
Pandas rendering minor ticks in matplotlib sublots with shared axes

### ISSUE THREAD

**Issue by williamsmj** [pydata/pandas#10657]
When the plot method of a dataframe is passed an `ax` keyword to render to a matplotlib subplot, the minor ticks and their labels are rendered regardless of whether `sharex|y=True`. The major ticks/labels are correctly removed.

Here's a [short notebook](https://gist.github.com/williamsmj/12a0abb2fb98aec67c17) that reproduces the issue. Note that the minor ticks are included in the upper axes of the final figure.

I am 90% certain this is a regression, but I wasn't able to pin down which version of pandas or matplotlib prompted this bug. Nor was I able to figure out whether this was due to pandas or matplotlib.

**Comment by williamsmj** [comment]
To add to this, the bug shown in the notebook linked above happens in

```
CPython 2.7.10
IPython 3.2.1
pandas 0.16.2
matplotlib 1.4.3
```

The bug does not happen with:

```
CPython 2.7.9
IPython 3.2.0

pandas 0.16.0
matplotlib 1.4.3
```

A pandas regression?

**Comment by TomAugspurger** [comment]
Thanks. It probably is a maybe a regression on our end. We kind of take over the axes and use our own logic for determining what to draw.

Your plot appears to work when you pass in  `sharex=True` to the `.plot` calls. Could you try that out.

**Comment by williamsmj** [comment]
Yes, you're right. `sharex=True` in the individual `.plot` calls fixes this.

To be consistent with the `matplotlib` API this should not probably be necessary.

Happy to attempt a first PR if someone can point me in the direction of the file(s) that might have introduced this regression!

**Comment by TomAugspurger** [comment]
@sinhrks am I correct in thinking that this is buggy?

```python
In [25]: x = pd.DataFrame(list(zip(range(10), range(0, -10, -1))), columns=['a', 'b'])

In [26]: x.index = pd.date_range('2000-01-01', freq='Q', periods=10)

In [27]: fig, ax = plt.subplots(2, 1, sharex=True)

In [28]: x.plot(subplots=True, ax=ax)
Out[28]:
array([<matplotlib.axes._subplots.AxesSubplot object at 0x116b96630>,
       <matplotlib.axes._subplots.AxesSubplot object at 0x117580198>], dtype=object)

In [29]: plt.savefig('nosavefig.png')
```
![nosavefig](https://cloud.githubusercontent.com/assets/1312546/8935969/374ef076-3515-11e5-9a8d-7e4c3072d4b3.png)
Note that the axis is *not* shared.

```python
In [30]: fig, ax = plt.subplots(2, 1, sharex=True)

In [31]: x.plot(subplots=True, ax=ax, sharex=True)
/Users/tom.augspurger/Envs/py3/lib/python3.4/site-packages/pandas/tools/plotting.py:3218: UserWarning: When passing multiple axes, sharex and sharey are ignored.These settings must be specified when creating axes
  "These settings must be specified when creating axes", UserWarning)
Out[31]:
array([<matplotlib.axes._subplots.AxesSubplot object at 0x117deb940>,
       <matplotlib.axes._subplots.AxesSubplot object at 0x10c64f828>], dtype=object)

In [32]: plt.savefig('with_share.png')
```
![with_share](https://cloud.githubusercontent.com/assets/1312546/8935978/415f3ac6-3515-11e5-88ec-efce4413b454.png)
Now it is shared, but we get the warning to tell us what we just did.

I haven't looked at this section in a while.

**Comment by TomAugspurger** [comment]
@williamsmj probably somewhere near here: https://github.com/pydata/pandas/blob/818f0a7e88762e9ac77609024ecb96ea185f4667/pandas/tools/plotting.py#L977

**Comment by williamsmj** [comment]
I think it's https://github.com/pydata/pandas/commit/015fc62dad34e1293728f4ae0cf438f798f5f1de that's the problem.

Given the stated intentions of that commit, it's above my pay grade to determine whether this new behaviour is a feature or a bug!

**Comment by sinhrks** [comment]
@Tomauguspurger Yes, major ticklabel should be displayed when ``sharex=False`` (#7801). Unfortunately test cases must have been incomplete.

**Comment by TomAugspurger** [comment]
cc @JanSchulz 

Do you remember in https://github.com/pydata/pandas/pull/9740 how the interaction of `sharex` in `plt.subplots` and `sharex` in `df.plot` is supposed to work?

**Comment by JanSchulz** [comment]
@TomAugspurger sorry, no idea whats going wrong here. I only tested (optimized for...) a gridspec without sharex, seems that I overlooked this case :-(
