### ISSUE TITLE
google-api-python-client Version Check is broken

### ISSUE THREAD

**Issue by fdellavedova** [pydata/pandas#10652]
Hi All, I cannot use io.gbq due to an issue with the version check of the installed google library.

    >>> pkg_resources.get_distribution('google-api-python-client').version
    '1.2'

The [offending line](https://github.com/pydata/pandas/blob/master/pandas/io/gbq.py#L29) executes the version check as follows:

    >>> pkg_resources.get_distribution('google-api-python-client').version < '1.2.0'
    True

but

    >>> pkg_resources.get_distribution('google-api-python-client').version < '1.2'
    False

**Comment by sinhrks** [comment]
@jacobschaer @sean-schaefer Pls take a look.
