### ISSUE TITLE
Memory error when plotting simple time series

### ISSUE THREAD

**Issue by andreabedini** [pydata/pandas#10650]
This crashes:

```
import pandas as pd
index = pd.timedelta_range(start="06:00:01", end="12:00:00", freq='S')
pd.Series(range(index.size), index=index).plot()
```

Traceback at https://gist.github.com/andreabedini/074d529ff63356312ce6

So far I have figured out that `_get_default_locs` gets called with completely bogus `vmin` an `vmax`.

**Comment by jreback** [comment]
dupe of #8711

**Comment by andreabedini** [comment]
Thanks @jreback
