### ISSUE TITLE
BUG: Series.align(join='left') and join='right' are inverted

### ISSUE THREAD

**Issue by gdementen** [pydata/pandas#10665]
join='left' does a right join and 'right' does a left join

See the notebook for details
https://nbviewer.jupyter.org/gist/gdementen/fa4d388993ee981b5698

**Comment by gdementen** [comment]
btw, this is with pandas 0.16.2

**Comment by gdementen** [comment]
probably related to (possibly a dupe of, I am not sure) #10147.
The strange thing, is that for DataFrames, align seems to work correctly.

**Comment by sinhrks** [comment]
Thanks. Looks to be caused by following line. 

- https://github.com/pydata/pandas/blob/master/pandas/core/index.py#L2152

When ``Series`` with ``MultiIndex`` is on left side, ``how=left`` and ``right`` are must be fripped also. PR is appreciated!
