### ISSUE TITLE
Can't save pandas dataframe to HDF file

### ISSUE THREAD

**Issue by malapradej** [pydata/pandas#10669]
I have been trying for a while to save a pandas dataframe to an HDF5 file. I tried various different phrasings eg. `df.to_hdf` etc. but to no avail. I am running this in a python virtual environment see [here][1]. Even without the use of the VE it has the same error. The following script comes up with the error below:

    ''' This script reads in a pickles dictionary converts it to panda 
    dataframe and then saves it to an hdf file. The arguments are the 
    file names of the pickle files.
    '''

    import numpy as np
    import pandas as pd
    import pickle
    import sys

    # read in filename arguments
    for fn in sys.argv[1:]:
        print 'converting file %s to hdf format...' % fn
        fl = open(fn, 'r')
        data = pickle.load(fl)
        fl.close()
        frame = pd.DataFrame(data)
        fnn = fn.split('.')[0]+'.h5'
        store = pd.HDFStore(fnn)
        store.put([fn.split('.')[0]], frame)
        store.close()
        frame = 0
        data = 0

Error is:

    $ ./p_to_hdf.py LUT_*.p
    converting file LUT_0.p to hdf format...
    Traceback (most recent call last):
      File "./p_to_hdf.py", line 22, in <module>
        store = pd.HDFStore(fnn)
      File "/usr/lib/python2.7/site-packages/pandas/io/pytables.py", line 270, in __init__
        raise Exception('HDFStore requires PyTables')
    Exception: HDFStore requires PyTables

`pip list` shows both pandas and tables are installed and the latest versions.

    pandas (0.16.2)
    tables (3.2.0)

I can `import tables` without errors in Ipython.

  [1]: http://docs.python-guide.org/en/latest/dev/virtualenvs/

**Comment by maximilianr** [comment]
Have you tried using anaconda? That will cut through a lot of the PyTables installation issues

**Comment by malapradej** [comment]
Unfortunately I can't use anaconda as I do not have sudoers rights on the system. The most I can do is to use a Virtual Environment which allows some modification of python packages compared to the standard install.

**Comment by jreback** [comment]
anaconda can be installed in user space and does not need root

**Comment by malapradej** [comment]
Sorry if this sounds obvious, but have not had much experience with anaconda. Will this not be a problem if a version of python is already installed by the admin? How can get the anaconda version installed in my ~./local area to overrule this.

**Comment by TomAugspurger** [comment]
When you install Anaconda it modifies your PATH (with your permission) so that its python shows up first.

**Comment by malapradej** [comment]
Sounds good. I'll wait for response from the servicedesk on Monday. If they can't get this resolved I'll definitely turn to an anaconda local install. Thanks Tom.

**Comment by jreback** [comment]
http://pandas.pydata.org/pandas-docs/stable/install.html

**Comment by jreback** [comment]
closing, but if you still have issues, pls comment.

**Comment by bashtage** [comment]
You don't need sudo to use Anaconda.  It is happy to install in $HOME and run just for the local user.
