### ISSUE TITLE
Older versions of Stata dta files are not readable

### ISSUE THREAD

**Issue by bashtage** [pydata/pandas#10682]
Checking some older verions, and found that the versions that are not tested cannot be imported using `from_stata` or `StataReader`.  For example, 

http://fmwww.bc.edu/ec-p/data/wooldridge2k/401ksubs.dta

produces an error when trying to parse the header. This file is version 105.  As far as I know, there are on online docs for older versions of dta, so it probably isn't worth trying to support them.

The simplest fix is to just modify the versions that are supported to only include 113+, which still covers a long history.

**Comment by jreback** [comment]
this is indicated in the docs
http://pandas-docs.github.io/pandas-docs-travis/io.html#reading-from-stata-format

need anything more?

**Comment by bashtage** [comment]
Didn't see that change... so no, but can start to clean up the very old < 113 code paths at some point in StataReader.

**Comment by jreback** [comment]
sure - unless it is possible to support those older versions?

**Comment by bashtage** [comment]
I think the docs are very difficult to find for older versions - I probably would require someone with a printed copy.

**Comment by jreback** [comment]
@bashtage I am totally ok with punting on this as I don't think important, unless you are really interested yourself :)

**Comment by bashtage** [comment]
I might put it on the low prio to clean when I have time, but it isn't important.
