### ISSUE TITLE
Assignment using .ix and None incorrectly assigns NaN

### ISSUE THREAD

**Issue by dewoller** [pydata/pandas#10685]
When I try to initialize a new column with None, NaN is filled in instead.  For example:

```
import pandas as pd
df=pd.DataFrame(1, index=['A'], columns=['x'])
df.ix[:,"Grouping"]=None
df
```

results in 

```
   x  Grouping
A  1       NaN
```

Alternatively, if I assign a random number instead of the constant 1, I get None in the Grouping column

```
import pandas as pd
df=pd.DataFrame(np.random.randn(1,1), index=['A'], columns=['x'])
df.ix[:,"Grouping"]=None
df
```

```
          x Grouping
A  0.254445     None
```
It should result in None in both cases

**Comment by jreback** [comment]
well, you didn't specify the version of pandas you are using. These both yield ``NaN`` for the column which is dtyped to be float. This is the marker for missing values. The ONLY case where ``None`` is directly preserved is if its specifically set in an ``object`` dtype column.

See docs for more details [here](http://pandas.pydata.org/pandas-docs/stable/missing_data.html)

**Comment by jreback** [comment]
See a little way down here for some examples: http://pandas.pydata.org/pandas-docs/stable/whatsnew.html#whatsnew-0150-api

**Comment by dewoller** [comment]
Thanks for giving it  your attention, and also, this great library.  I
really appreciate it, python is a lot more fun than R,  you make that
replacement possible.

On Mon, Jul 27, 2015 at 10:25 PM, jreback <notifications@github.com> wrote:

> well, you didn't specify the version of pandas you are using. These both
> yield NaN for the column which is dtyped to be float. This is the marker
> for missing values. The ONLY case where None is directly preserved is if
> its specifically set in an object dtype column.
>
> See docs for more details here
> <http://pandas.pydata.org/pandas-docs/stable/missing_data.html>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pydata/pandas/issues/10685#issuecomment-125186547>.
>



-- 
-- 
-------------------------------------------
Dennis Wollersheim
-------------------------------------------

**Comment by jreback** [comment]
@dewoller kind words. get more R users to convert! they will be happier!
