### ISSUE TITLE
MAINT: use numpy.nanvar (requires numpy >= 1.8)

### ISSUE THREAD

**Issue by jvkersch** [pydata/pandas#10689]
This came up in #10679.

Numpy 1.8 implements `numpy.nanvar`, which can replace `pandas.core.nanops._nanvar` when the minimum requirement for Numpy is bumped to 1.8 . The implementation of `_nanvar` in #10679 is in fact based on the corresponding implementation in Numpy.

I haven't checked whether other nanops can be replaced by a suitable Numpy equivalent.

**Comment by jreback** [comment]
@jvkersch I commented on the other issue. I think should simply do this now with a conditional on the version of numpy. just use ``not _np_version_under1p8``.

alternatively

``f = getattr(np,'nanvar',None)``

and replace it with the current function

**Comment by jvkersch** [comment]
Will do, thanks!
