### ISSUE TITLE
Loss of series name attributes in pd.concat 

### ISSUE THREAD

**Issue by compandu** [pydata/pandas#10698]
`pd.concat` nicely preserves name attributes when given a list of series. However, this only works if all series have the name attribute set, otherwise all names are lost:
    
    In [1]: import pandas as pd
    In [2]: pd.__version__
    Out[2]: '0.16.2'

    In [3]: foo = pd.Series([1,2], name='foo')
    In [4]: bar = pd.Series([1,2])
    
    In [6]: pd.concat([foo, bar], 1)
    Out[6]: 
       0  1
    0  1  1
    1  2  2

Not sure this qualifies as a bug.

**Comment by jreback** [comment]
hmm, so you want

```
In [14]: DataFrame({'foo' : [1,2], 1 : [1,2]},columns=['foo',1])
Out[14]: 
   foo  1
0    1  1
1    2  2
```

seems reasonable. I'll mark it as a bug. pull-requests welcome!

**Comment by compandu** [comment]
yep, that's it.

**Comment by jreback** [comment]
gr8. pull-requests welcome!

**Comment by IamGianluca** [comment]
I've fixed this bug. I'll send a pull request later today ;-)

**Comment by IamGianluca** [comment]
@jreback Do you have any comment on the last pull request? I fixed all unit tests which were previously failing.
