### ISSUE TITLE
API: value_counts on a Categorical Series should have a CategoricalIndex

### ISSUE THREAD

**Issue by TomAugspurger** [pydata/pandas#10704]
Thoughts on this?

```python
In [8]: import pandas.util.testing as tm

In [9]: s = pd.Series(tm.makeCategoricalIndex(k=100))

In [10]: s.value_counts()
Out[10]:
vcKH    40
vXR9    31
Zn8J    29
dtype: int64

In [11]: s.value_counts().index
Out[11]: Index(['vcKH', 'vXR9', 'Zn8J'], dtype='object')
```

Now that we have `CategoricalIndex` (thanks Jeff), should that type be preserved so that `Out[11]` is a `CategoricalIndex`? My use-case (not shown in this example) is when the original categories are ordered, you get your `value_counts` and then want to sort the index.

**Comment by jorisvandenbossche** [comment]
I think that is the logical consequence of having a categorical type in series and having a CategorialIndex, so OK for me! 
It is similar as how `df.groupby('cat').count()` now also preserves this categorical type. So in that regard, it would only be consistent that `value_counts` returns that as well.

**Comment by jorisvandenbossche** [comment]
There can of course be some incompatibilities, such as with plotting afterwards, but that is similar as eg the groupby case (we had some reports on that, eg #10140)

**Comment by jreback** [comment]
yes I would agree with that logic. go for it @TomAugspurger

**Comment by TomAugspurger** [comment]
Cool. I'll shot for next week.
