### ISSUE TITLE
API: deprecate combineAdd and combineMult methods?

### ISSUE THREAD

**Issue by jorisvandenbossche** [pydata/pandas#10735]
On a DataFrame, we have the [``combineAdd``](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.combineAdd.html) and [``combineMult``](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.combineMult.html) methods:

* they are a redundant, as they are defined as `self.add(other, fill_value=0.)` and ` self.mul(other, fill_value=1.)` (that is the actual implementation), which is also just cleaner to use IMHO.
* they have awkward (and non-pep8) names
* I assume they are not used a lot (I found 3 relevant references on StackOverflow for combineAdd ([SO1](http://stackoverflow.com/questions/28421137/subtract-two-dataframes-with-non-overlapping-indexes/28421255#28421255), [SO2](http://stackoverflow.com/questions/27744908/computing-sum-of-pandas-dataframes/27746836#27746836) and [SO2](http://stackoverflow.com/questions/20927701/pandas-numpy-how-to-turn-column-data-into-sparse-matrix/20929504#20929504), which is more than I expected), and none for combineMult

Therefore, I was thinking we could maybe deprecate these (as kind of clean-up)?

**Comment by jreback** [comment]
yeh they have a 'deprecated stuff' comment, but were not actually deprecated, sigh :( so let's deprecate and remove in next version.

**Comment by jorisvandenbossche** [comment]
> yeh they have a 'deprecated stuff' comment,

Ah, yes, you mean in the codebase (as in the docstring nothing is said about that ..)

Will do a PR in a few days if no one complains

**Comment by TomAugspurger** [comment]
+1

**Comment by jreback** [comment]
yes I think these are pretty old methods. Let's just actually deprecate them.
