### ISSUE TITLE
DataFrame msgpack objects written from linux cannot be read on windows

### ISSUE THREAD

**Issue by ruidc** [pydata/pandas#10732]
eg. on linux:
```
df2 = pandas.DataFrame([['100']], index=[1], columns=['v'])
df2.to_msgpack(r"/mnt/C/temp/p2.msgpack")
```
then on windows:
```
df = pandas.read_msgpack(r"C:\temp\p2.msgpack")
ValueError: Shape of passed values is (1, 1), indices imply (1, 2)
```

**Comment by jreback** [comment]
pls show versions. This IS tested in master for cross-platform compat. Its possible that you are hitting an old bug.

**Comment by ruidc** [comment]
0.16.2 tested

**Comment by ruidc** [comment]
and 0.14.2

**Comment by jreback** [comment]
pls try on master.

**Comment by ruidc** [comment]
where is pandas nightly these days?

**Comment by ruidc** [comment]
ah, found it, but stale for a year

**Comment by ruidc** [comment]
that's going to make it difficult for me to test windows reading.

**Comment by jreback** [comment]
hmm, this is only partially working, will mark as a bug.

**Comment by jreback** [comment]
cc @kawochen want to have a look

The reads cross platform work but are just returning a byte stream, so the tests don't fail. odd.

**Comment by ruidc** [comment]
it seems to be an issue between the index being picked up as dtype np.int32 vs np.int64 but i'm well out of my depth trying to dig into this

**Comment by kawochen** [comment]
OK I will take a look, but the cross platform issue itself should have been fixed on master already in `pandas.io.packers.dtype_for`.

**Comment by ruidc** [comment]
do you mean https://github.com/pydata/pandas/commit/b0c14c18aa52992c4c2b9cdc7b0da34e88a0ade2 ? can you reproduce my problem above?
If you can no longer reproduce since your fixes i'll have to find/merge all the related fixes as we need to still run 0.14.2 for compatibility reasons

**Comment by jreback** [comment]
@kawochen yes I think they are fixed on same-platform reading, but the cross-platform is returning odd results (and the tests dont catch this).

@ruidc If you have compat with 0.14.2 you are on your own. (it *should* work, and their are not too many fixes, but that will be tricky)

**Comment by ruidc** [comment]
... and actually seems to not just be the index, for some larger test cases, happens on the data too. Again forcing int64 dtype on the windows side seems to fix it for me.
