### ISSUE TITLE
Client Secrets file in the gbq.py

### ISSUE THREAD

**Issue by snamburi3** [pydata/pandas#10754]
https://github.com/pydata/pandas/blob/master/pandas/io/gbq.py#L102
Why is this in the gbq.py? can we set this as an environmental Variable?

**Comment by TomAugspurger** [comment]
cc @jacobschaer

**Comment by snamburi3** [comment]
Thanks. I think the best way would be to set GOOGLE_APPLICATION_CREDENTIALS in the script overriding the gbq.py defaults...
https://developers.google.com/identity/protocols/application-default-credentials

**Comment by snamburi3** [comment]
Or, can we switch to [gcloud-python bigquery](https://googlecloudplatform.github.io/gcloud-python/stable/bigquery-usage.html). We need to just set GOOGLE_APPLICATION_CREDENTIALS and then we are done. Thanks you all.

**Comment by jacobschaer** [comment]
I believe those credentials were to simplify the authentication flow. We created a Pandas GBQ google account so when the authentication flow pops a browser for credentials it can give a customized description of what the credentials are needed for (in case the user is unsure). It also lets us get a sense of how popular the module is in the sense of people actually authenticating with it.

Also, I think that non-application tokens had a rather restrictive expiration time.

@sean-schaefer - Sound right?

**Comment by parthea** [comment]
I've committed a change to the authentication flow in #11141. The authentication worked without modifying `client_secret`.

**Comment by parthea** [comment]
@jreback @snamburi3  Can this be closed? Pandas supports application default credentials with PR #13608
