### ISSUE TITLE
Performance: Implicit boxing to TimeStamp of datetime64[ns] inside DateTimeIndex

### ISSUE THREAD

**Issue by drglitch** [pydata/pandas#10769]
Hello,

I've stumbled onto a behavior that causes performance problems on large datasets: When creating a multiindex with second level being a DateTime64 col, and then doing a `.loc[('val1', TimeStamp('val2'),)]` to get at particular value, pandas coerces (via _box_func, called from __iter__) all values in that particular column to TimeStamp dtype. This is done only on first access, but affect performance quite heavily since the op is O(n).

However, when chaining the same op (or calling it via multi-level `.xs`, this behavior is not exhibited. It is not a viable workaround however because doing so introduces an extra call to getitem per each level of multiindex.

Is there a workaround for this or what am i doing wrong?
In essence, given a df with unique multiindex, i want to get to a particular row given values for each level of the index.

Repro:
```
df = <dataframe with: [colA:string, colB:datetime64, colC:numeric with 1,000,000 rows>
gr = df.groupby(('colA', 'colB',))
ag = gr.aggregate({'colC':'sum'})

path = ('one', pd.TimeStamp('2015-01-01 01:02:03'),)
ag.loc[path] # << first call iterates over entire dataset doing the conversion, and is slow
ag.loc[path] # << second call is very quick
ag.xs(path, levels=('colA','colB',)) # << this takes a different code path but does an extra call to getitem, making it slower.
```

Other things:
- padding numpy.datetime64 into the path tuple instead of timestamp doesnt help
- specifiying axis for loc doesn't help

**Comment by jreback** [comment]
pls show construction of the frame with code 
and pd.show_versions()

**Comment by drglitch** [comment]
@jreback here you go - please let me know what else may be helpful.

```
>>> import pandas as pd
>>> import numpy as np

>>> pd.show_versions() # snipped
python: 3.4.0.final.0
python-bits: 64
OS: Linux
OS-release: 3.13.0-36-generic
machine: x86_64
processor: x86_64
byteorder: little

pandas: 0.15.2
nose: 1.3.0
Cython: 0.21.2
numpy: 1.9.1
scipy: 0.14.1
dateutil: 2.2
pytz: 2013.9
tables: 3.1.1

>>> dates = [np.datetime64(x) for x in pd.date_range('1/1/2001', periods=500000, freq='S')]
>>> cats = list('ABCDEFGHIJ'*50000)
>>> nums = list(range(1,500000))

>>> df = pd.DataFrame([cats, dates, nums]).T
>>> df.columns = ['colA','colB','colC']
>>> df = df.convert_objects(convert_numeric=True)
>>> df.dtypes
colA            object
colB    datetime64[ns]
colC           float64
dtype: object

>>> gr = df.groupby(('colA', 'colB',))
>>> ag = gr.aggregate({'colC':'sum'})

>>> ag.index
MultiIndex(levels=[['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'], [2001-01-01 00:00:00, 2001-01-01 00:00:01, ...]],
           labels=[[ ...]], 
           names=['colA', 'colB']) # snipped for clarity
>>> ag.index.levels[1]
<class 'pandas.tseries.index.DatetimeIndex'>
[2001-01-01 00:00:00, ..., 2001-01-06 18:53:19]
Length: 500000, Freq: None, Timezone: None

>>> path = ('A', pd.Timestamp('2001-01-01 00:00:10'),)
>>> ag.iloc[1]
colC    11
Name: (A, 2001-01-01 00:00:10), dtype: float64

>>> ag.loc[path] # iterates over each row, calls on cProfile > 500k
colC    11
Name: (A, 2001-01-01 00:00:10), dtype: float64

>>> ag.loc[path] # will be fast - just 180 calls
colC    11
Name: (A, 2001-01-01 00:00:10), dtype: float64
```

**Comment by jreback** [comment]
You are doing some really non-performant construction. The way you showed things are all ``object`` dtype. You want to avoid object whenever possible. Certainly for datetimes. 

```
In [69]: np.random.seed(1234)

In [70]: pd.set_option('max_rows',12)

In [71]: dates = pd.date_range('1/1/2001', periods=500000, freq='S')

In [72]: cats = list('ABCDEFGHIJ'*50000)

In [73]: df = pd.DataFrame({ 'A' : cats, 'B' : dates, 'C' : np.arange(500000) })

In [74]: df['C'] = df['C'].shift(-1)

In [75]: df.info()
<class 'pandas.core.frame.DataFrame'>
Int64Index: 500000 entries, 0 to 499999
Data columns (total 3 columns):
A    500000 non-null object
B    500000 non-null datetime64[ns]
C    499999 non-null float64
dtypes: datetime64[ns](1), float64(1), object(1)
memory usage: 15.3+ MB

# if you have lots of duplicates then this will make some types of selections much faster (and reduces used memory)
In [77]: df['A'] = df['A'].astype('category')

In [78]: df.info()
<class 'pandas.core.frame.DataFrame'>
Int64Index: 500000 entries, 0 to 499999
Data columns (total 3 columns):
A    500000 non-null category
B    500000 non-null datetime64[ns]
C    499999 non-null float64
dtypes: category(1), datetime64[ns](1), float64(1)
memory usage: 11.9 MB

In [84]: agged = df.groupby(['A','B']).aggregate({'C' : 'sum' })

In [85]: agged.info()
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 500000 entries, (A, 2001-01-01 00:00:00) to (J, 2001-01-06 18:53:19)
Data columns (total 1 columns):
C    499999 non-null float64
dtypes: float64(1)
memory usage: 10.0+ MB
```

To do this type of indexing it constructs a hash table. So it needs to do some work on the first indexing. 
A multi-index by-definition is an ``object`` dtype itself, so this type of individual indexing is not efficient.
If you need to do this repeatedly and the initial indexing is a problem, then you are going about things the wrong way.
```
In [86]: path = ('A', pd.Timestamp('2001-01-01 00:00:10'),)

In [87]: %timeit -n 1 -r 1 agged.loc[path]
1 loops, best of 1: 1.85 s per loop

In [88]: %timeit -n 1 -r 1 agged.loc[path]
1 loops, best of 1: 423 us per loop
```

This is almost always better to slice out things first.
```
In [92]: idx = pd.IndexSlice
n [94]: agged.loc[idx[['A']],:]
Out[94]: 
                            C
A B                          
A 2001-01-01 00:00:00       1
  2001-01-01 00:00:10      11
  2001-01-01 00:00:20      21
  2001-01-01 00:00:30      31
  2001-01-01 00:00:40      41
  2001-01-01 00:00:50      51
...                       ...
  2001-01-06 18:52:20  499941
  2001-01-06 18:52:30  499951
  2001-01-06 18:52:40  499961
  2001-01-06 18:52:50  499971
  2001-01-06 18:53:00  499981
  2001-01-06 18:53:10  499991

[50000 rows x 1 columns]
```

```
In [95]: agged = df.groupby(['A','B']).aggregate({'C' : 'sum' })

In [96]: %timeit -n 1 -r 1 agged.loc[idx[['A']],:]
1 loops, best of 1: 40.9 ms per loop
```

Then subslice on this, which has a quite efficient index scheme.

**Comment by jreback** [comment]
In theory this could be changed NOT to do this. However, this would require special cython support for MultiIndexing (IOW maintaining separate hashtables) in a ``IndexEngine`` structure. So possible, but quite a bit of work.

**Comment by drglitch** [comment]
@jreback thanks for the detailed explanation - in my example the df construction was just for the sake of the example - i obviously don't do it that way in prod :) 

Having read quite a bit of docs, i figured that using multiindex for this would be the recommended/best way to go about it (and also because thats what pivot_table seems to do).

Slicing didn't seem like the right fit because my access pattern is accessing individual row (all paths end up unique after the groupby) multiple times over, meaning a new indexslice would have to be created with size of 1 each and every time.

Am i correct in understanding that the DateTimeIndex is constructed on top of the datetime64 objects, but the actual (multiindex) lookup is what causes it to coerce entire index into Timestamps?

I'll see what kind of performance i get with subslicing (as opposed to chaining, which i already tried and found a bit slowish). Thanks!

**Comment by drglitch** [comment]
To clarify one more thing: this doesn't happen when multiindex is not involved. Is that due to the fact that it doesn't have to build a full hash of all tuples in the groupby/multiindex?

e.g.:
```
gra = df.groupby('colB')
aga = gra.aggregate({'colC':'sum'})
aga.loc[(path[1],)] # << no boxing happening and fast even on first pass
```

**Comment by jreback** [comment]
yep, ``Int64/Float/Object`` have dedicate hashing types. MultiIndex is a list of tuples.
