### ISSUE TITLE
pandas Truck Factor

### ISSUE THREAD

**Issue by gavelino** [pydata/pandas#10768]
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **pandas** and obtained a value of **2**.

The developers responsible for this TF are:

Wes McKinney - author of 59% of the files
Jeff Reback - author of 19% of the files

To validate our results, we would like to ask **pandas** developers the following three brief questions:

(a) Do you agree that the listed developers are the main developers of **pandas**?

(b) Do you agree that **pandas** will be in trouble if the listed developers leave the project (e.g., if they win in the lottery, to be less morbid)?

(c) Does **pandas** have some characteristics that would attenuate the loss of the listed developers (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by maximilianr** [comment]
You probably want to weight that contribution by time - Wes is more of a sage than a maintainer now and so those numbers are going to look very different if you look at the more recent history

Also surely winning the lottery would mean they spend more time on unpaid open source work? :)
