### ISSUE TITLE
reindex() from string index to DatetimeIndex index returns nan values on Pandas 0.16.2

### ISSUE THREAD

**Issue by stigdescamps** [pydata/pandas#10764]
When upgrading to pandas 0.16.2, reindex() from string index to DatetimeIndex index returns nan values.

This test code:

indexInit = ["19990101","19990102","19990103"]
values = [1.0,2.5,2.1]
outSeries = Series(values,index=indexInit)
outSeries.reindex(index=DatetimeIndex(outSeries.index))

returns:

1999-01-01    nan
1999-01-02    nan
1999-01-03    nan

Same output on the latest Mac OS X version and also the latest linux version.
We had to downgrade the Pandas version for this to work.

**Comment by jreback** [comment]
what version were u on?

this is correct a string index is different from s datetimeindex and they don't overlap

**Comment by stigdescamps** [comment]
Pandas version: 0.16.2

**Comment by jreback** [comment]
0.10. is very old
pls read the realease notes
the behavior you described is incorrect and fixed s while back

**Comment by jreback** [comment]
you need to convert strings to an index with pd.to_datetime()

string conversion has many options and is sometimes ambiguous so cannot be automatic

**Comment by stigdescamps** [comment]
Thank you for your help. We will check.

**Comment by stigdescamps** [comment]
With the new approach proposed:

This test code:

indexInit = ["19990101","19990102","19990103"]
values = [1.0,2.5,2.1]
outSeries = Series(values,index=indexInit)
##outSeries.reindex(index=DatetimeIndex(outSeries.index))
outSeries.reindex(index=outSeries.index.to_datetime())

returns the same issue:

1999-01-01 nan
1999-01-02 nan
1999-01-03 nan

**Comment by stigdescamps** [comment]
For the Pandas 0.13.1, reindex() is working properly.

**Comment by jreback** [comment]
What you are doing is not consistent.

```
In [5]: outSeries = Series(values,index=pd.to_datetime(indexInit))

In [6]: outSeries
Out[6]: 
1999-01-01    1.0
1999-01-02    2.5
1999-01-03    2.1
dtype: float64

In [7]: outSeries.index
Out[7]: DatetimeIndex(['1999-01-01', '1999-01-02', '1999-01-03'], dtype='datetime64[ns]', freq=None, tz=None)

In [8]: outSeries.reindex(index=DatetimeIndex(outSeries.index))
Out[8]: 
1999-01-01    1.0
1999-01-02    2.5
1999-01-03    2.1
dtype: float64
```

**Comment by jreback** [comment]
@stigdescamps IIRC. this was only accidently allowed, and was completely inconsistent. I don't think there were any tests cases for this, and that's prob why it changed. ``.reindex`` works on non-same type indexes, but doesn't make sense and will return ``nans`` if things cannot be mapped. Having this automagically convert to a ``DatetimeIndex`` just because you reindex is not intuitive and very magical to me.
