### ISSUE TITLE
rolling_window(mean=True), why?

### ISSUE THREAD

**Issue by lababidi** [pydata/pandas#10767]
I attempted to use ```rolling_window()``` and couldn't figure out why my simple test cases weren't working. I realized there's a default value of ```mean=True``` to average the result out. Is this really the most common use case people have? I would have assumed most use cases would be ```mean=False```

**Comment by jreback** [comment]
these types of questions are basically impossible to answer w/o some user data which is hard to get. Can you show an example of what you are doing?

**Comment by lababidi** [comment]
I wanted to keep track of the cumulative sum over last 30 days, exactly what a rolling window is for. The results came back scaled now and i didn't understand why. Then I looked into the actual code and saw the ```mean=True```. If my first thought was to get a ```mean``` wouldn't I use a ```rolling_mean()```. I would think explicitly modifying the results by forcing a ```True``` would make more sense.

Here's a line from my project:
```window_30 = pd.rolling_window(data_frame, window=30, win_type='boxcar', mean=False)```

**Comment by jreback** [comment]
your are not using the right function, use ``rolling_mean`` if you want a functional mean, or ``rolling_sum`` if you don't. These are windowed functions that use specific types of windwos. see the doc-string.

**Comment by jreback** [comment]
docs are here: http://pandas.pydata.org/pandas-docs/stable/computation.html#moving-rolling-statistics-moments

**Comment by lababidi** [comment]
@jreback I appreciate the feedback. I didn't realize that rolling_window is used as a convolution. Thanks for presenting me with ```rolling_sum```. Thanks for the work you're putting in.
