### ISSUE TITLE
Timedelta has unpexected properties when negative

### ISSUE THREAD

**Issue by adamgreenhall** [pydata/pandas#10775]
Here's what's going on:

    In [1]: import pandas as pd
    In [2]: pd.__version__
    Out[2]: '0.16.2+308.g529288e'
    In [3]: dt = pd.Timedelta(seconds=-2)
    In [4]: dt
    Out[4]: Timedelta('-1 days +23:59:58')
    In [5]: dt.seconds
    Out[5]: 86398

I would expect ``dt.seconds == -2``.

It seems like the fix may be something like:

    In [6]: dt.days * 3600 * 24 + dt.seconds
    Out[6]: -2

Is it that easy? ``Timedelta`` is based on UTC time, so days always have 24hrs, right?

**Comment by jreback** [comment]
read the docs here: http://pandas.pydata.org/pandas-docs/stable/timedeltas.html#attributes

this is as expected as these are the seconds not total_seconds
