### ISSUE TITLE
Timestamp handles a different date range than datetime.datetime and numpy.datetime64

### ISSUE THREAD

**Issue by kawochen** [pydata/pandas#10773]
This may very well be known/intentional, and if so I think it's worth putting in doc somewhere. 
```
>>> datetime(2300,1,1)
datetime.datetime(2300, 1, 1, 0, 0)
>>> numpy.datetime64('2300-01-01')
numpy.datetime64('2300-01-01')
>>> Timestamp('2300-01-01') # pandas.tslib.OutOfBoundsDatetime

```

**Comment by jreback** [comment]
http://pandas.pydata.org/pandas-docs/stable/gotchas.html#timestamp-limitations

if u think can be better documented pls lmk

**Comment by kawochen** [comment]
Oops. Should've gone through the gotchas.
