### ISSUE TITLE
ENH: Allow exponential weighing functions to specify alpha, in addition to span / com / halflife

### ISSUE THREAD

**Issue by MaximilianR** [pydata/pandas#10789]
Currently the exponential functions take one of three arguments to specify the length of backhistory. Each of these numerically converts to alpha. Outlined here: http://pandas.pydata.org/pandas-docs/stable/computation.html#exponentially-weighted-moment-functions

Is there a reason we don't allow users to just pass in `alpha`? This is how I think about weighing some of the time.

I'm happy to do a PR in time; this issue is to solicit feedback.

**Comment by bashtage** [comment]
This would be useful - I also find it strange that alpha is always indirectly parameterized.

**Comment by jreback** [comment]
this would be a pretty easy add. I don't know the original reason why this is, nor do I see the harm. As long as the docs are updated, ok by me.
