### ISSUE TITLE
Improve Installation documentation

### ISSUE THREAD

**Issue by ganego** [pydata/pandas#10782]
On this website http://pandas.pydata.org/pandas-docs/stable/install.html there are the console commands to install pandas on for example debian.
They are listed as *sudo apt-get install python-pandas*.
It would be a good idea to mention, that this will install pandas for python2 and you need to specificly write *python3-pandas* to get the version for python3.
This might probably be completely obvious to everyone installing stuff like this every day, but for a beginner like me it was not clear at all and I struggled for quite some time to get pandas for py3.
Thank you.

**Comment by jreback** [comment]
is there a reason you are not using the recommended instructions? e.g. anaconda/miniconda

**Comment by ganego** [comment]
Because as the help site states:
> Anaconda, a cross-platform (Linux, Mac OS X, Windows) Python distribution for data analytics and scientific computing.
> However this approach means you will install well over one hundred packages and involves downloading the installer which is a few hundred megabytes in size.
> Miniconda allows you to create a minimal self contained Python installation, and then use the Conda command to install additional packages.

Neither do I want a new python installation nor do I want hundreds of MB and new packages. I simply want pandas my existing py3.4.

Anyway, as stated in the issue, it might be a good idea to write, that you can use *python3-pandas* and get the py3 version from your distribution.

greetings

**Comment by jreback** [comment]
ok, pls do a pull-request if you would

**Comment by jorisvandenbossche** [comment]
Note that you almost never want to install the version in the system packages I think, as this will probably be outdated?

If you're on linux, maybe just `pip install pandas` is the better thing to recommend?

**Comment by ganego** [comment]
This is what I tried first, but it takes quite some amount of memory to compile. Memory I did not have on my server. This is when the gcc crashed. (Also creating swapfiles was disabled, so the swapfile method did not work (somewhere explained in the issues)).

**Comment by jreback** [comment]
@ganego this is why we recommed using ``conda``. It is very fast, does not compile and solves all of these types of issues. If you insist on using the (older) versions distribution with the default package managers, then things are not as friendly.

**Comment by ganego** [comment]
Ok I think I have done it correctly (?) (never done it before).
https://github.com/pydata/pandas/pull/10784

**Comment by jreback** [comment]
closed by #10784
