### ISSUE TITLE
Pandas runs so slow when get option data

### ISSUE THREAD

**Issue by zhimakaimenxa** [pydata/pandas#10787]
I'm using windows server 2003, and python2.7 with pandas 0.16.2. It takes my computer 4-5 minutes to execute the following program:

----------------------------------------------------
from pandas.io.data import Options
aapl = Options('uso', 'yahoo')
data = aapl.get_all_data()
print data.iloc[0:5, 0:5]

----------------------------------------------------

Is it ok or not? 

If anyone wants to know more details, please let me know.

Thanks

L

**Comment by jorisvandenbossche** [comment]
That has probably more to do with the internet connection/download speed (on my computer it takes some 40s at the moment).

Are you able to try it on another machine?

**Comment by zhimakaimenxa** [comment]
Hi jorisvandenbossche,

It seems you are right, the issue is related to the internet speed. Now it takes 50s-88s after I connect internet on vpn.
