### ISSUE TITLE
API: nlargest/nsmallest, take_last -> keep

### ISSUE THREAD

**Issue by jreback** [pydata/pandas#10792]
``nlargest/nsmallest`` on frame should have ``take_last`` -> ``keep``, in-line with #10236 

[here](https://github.com/pydata/pandas/blob/master/pandas/core/frame.py#3187)

no deprecation is necessary as this is new in 0.17.0

cc @sinhrks 
cc @cpcloud

**Comment by sinhrks** [comment]
Do we need an option to keep all elements in this case, ``keep='all'` or `keep=True`?

And ``Series.nlargest/nsmallest`` need deprecation.

**Comment by jreback** [comment]
you don't need to keep all option (that would be just sort :)

so just a direct keyword replacement for Series
