### ISSUE TITLE
Clarification: Index.to_native_types() always converts to strings

### ISSUE THREAD

**Issue by jiffyclub** [pydata/pandas#10790]
This may have been intended, but this change (https://github.com/pydata/pandas/commit/3d54482bbd8086c27a01d489a0ae751e0b9c3731) released in 0.16.2 broke some of my code because `Index.to_native_types()` started converting all index types to strings, even integers. By reading the source I found I can prevent that by passing `quoting=True` to `to_native_types`, but since there's no documentation for `to_native_types` I wanted to get a little clarification: What is the expected behavior of `to_native_types` and what does the `quoting` keyword mean? Thanks!

**Comment by jreback** [comment]
this is not in the public API. why are you doing with it?

**Comment by jiffyclub** [comment]
You can see where I'm using it here: https://github.com/UDST/urbansim/blob/master/urbansim/utils/yamlio.py#L12

I'm trying to serialize a Series (hah) to YAML and preserve the Index dtype. YAML allows integer object keys (unlike JSON), but the YAML serializer chokes if the dict keys aren't Python native ints. I could no doubt work around this another way, but the `to_native_types` method was nice.

**Comment by jreback** [comment]
why not ``s.index.tolist()`` as well? that should preserve the type

**Comment by jiffyclub** [comment]
It preserves it a little too much because the values aren't converted to native Python ints but left as numpy ints:

```
In [27]: s.index.tolist()
Out[27]: [0, 1, 2]

In [28]: type(_[0])
Out[28]: numpy.int64
```

**Comment by jreback** [comment]
yeah this is a bit tricky

I don't recall even if we r using the quoting keyword
this routine was very tricky to profile
turns out that the astype is a good bit faster than doing the conversions of ints/floats in cython so this is why it was changed

**Comment by jiffyclub** [comment]
Thanks! I'm happy to use this off-spec as long as my tests are passing, and I can whip something up on my own if it stops working for me.
