### ISSUE TITLE
BUG: read_csv on windows loads "zero width no-break-space" unicode character

### ISSUE THREAD

**Issue by hlin117** [pydata/pandas#10793]
I'm working on a windows computer, with python pandas 0.16.2 installed. This is what happens when I tried loading in my csv file.

![bug](https://cloud.githubusercontent.com/assets/1865885/9190049/a3ec7cb8-3fa5-11e5-9922-70ccb55c30a9.png)

According to <a href="http://www.utf8-chartable.de/unicode-utf8-table.pl?start=65024&utf8=string-literal">this page</a>, the unicode character that pandas is loading in (`\xef\xbb\xbf`) is the "zero width no-break-space" character. The first entry of the csv doesn't need to be "mouse" for this bug to occur.

Can someone try to replicate this bug on another windows computer?

**Comment by kawochen** [comment]
that's just utf-8 byte order mark https://en.m.wikipedia.org/wiki/Byte_order_mark

**Comment by hlin117** [comment]
Indeed, it is the UTF-8 byte order mark. (U+FEFF.) I'm not sure if other windows computers have the problem where they read U+FEFF at the start of the file, or my computer is just a special case.

**Comment by kawochen** [comment]
Maybe try passing in `encoding="utf-8"`?

**Comment by hlin117** [comment]
No, that didn't work either. And passing in `encoding="utf-16"` and `encoding="utf-32"` only gave me errors.
![bug2](https://cloud.githubusercontent.com/assets/1865885/9190576/c2421ba4-3fab-11e5-810e-cec6c57bebd6.png)

**Comment by kawochen** [comment]
`utf-8-sig`?

**Comment by hlin117** [comment]
> `utf-8-sig`?

Looks like that did the trick.

If you would like to see if you could replicate the bug, I uploaded the file up to dropbox.
https://www.dropbox.com/s/009gova445lpboz/bug.csv?dl=0
