### ISSUE TITLE
tseries.holiday.USMemorialDay definition incorrect

### ISSUE THREAD

**Issue by compandu** [pydata/pandas#10805]
I believe this is a bug in the definition of memorial day in ``pandas.tseries.holiday``:

    USMemorialDay = Holiday('MemorialDay', month=5, day=24, offset=DateOffset(weekday=MO(1)))

should be
    
    USMemorialDay = Holiday('MemorialDay', month=5, day=31, offset=DateOffset(weekday=MO(-1)))

as memorial day is always the last monday in may. Tested against list from here http://www.timeanddate.com/holidays/us/memorial-day .

**Comment by jreback** [comment]
dupe of #9760, being handled in #10282

**Comment by compandu** [comment]
sorry about that, should've checked
