### ISSUE TITLE
unwanted cast of string to datetime

### ISSUE THREAD

**Issue by levicivita** [pydata/pandas#10809]
Note how the string 'M15' becomes somehow 8/15/2015!

>>> pandas.Series([datetime.datetime(2015,1,1), 'M15'])
0   2015-01-01
1   2015-08-15
dtype: datetime64[ns]

Compare other arbitrary strings that are left alone:

>>> pandas.Series([datetime.datetime(2015,1,1), 'MM15'])
0    2015-01-01 00:00:00
1                   MM15
dtype: object

**Comment by sinhrks** [comment]
Thanks for the report. It is because "M5" is parsed by dateutil as below.

```
dateutil.parser.parse('M5')
# datetime.datetime(2015, 8, 5, 0, 0)
```

Specify ``object`` dtype to handle it as object.

```
pd.Series([datetime.datetime(2015,1,1), 'M15'], dtype=object)
0    2015-01-01 00:00:00
1                    M15
dtype: object
```

**Comment by kawochen** [comment]
The likes of "T2", "20A", "2M", "T99", "M98", "m-1--2---3----4", "at", "on", "of", and "..-.-----.-.." provide endless surprises.

**Comment by jreback** [comment]
yes nothing much to do about this
when u put a datetime like inside a Series it will try to infer 

as indicated above being explicit about the dtype will work
