### ISSUE TITLE
Add .dt.total_seconds() method for timedelta64 Series

### ISSUE THREAD

**Issue by brandon-rhodes** [pydata/pandas#10817]
Background: I am trying to build a horizonal bar graph that shows me when various builds on a server started and ended, so that I can see visually which builds overlapped in time. But the idea that a horizontal bar graph's bar-width would be a timedelta seems completely foreign to all of the plotting libraries that I have tried today (matplotlib, bokeh, ggplot), so I want to punt and instead reduce my timedelta64's to a floating-point number of days. I can then fudge the axes to display dates anyway.

Problem: there is no easy way to move from a timedelta64 to the standard Python idea of an ordinal date. I would have to extract all of the components manually (days, seconds, fractions of a second) and then multiply them each by an appropriate factor and then add them back together.

The Python `timedelta` class has an alternative that I like very much: a `total_seconds()` method that expresses then entire value of the `timedelta` as a single scalar number of seconds.

This is not a perfect solution, since the factors it uses internally neglect the fact that a day might have included a leap second, but it works pretty well for non-astronomical use.

Could a `Series.dt.total_seconds()` method be added that returns the floating point value `days * 86400 + seconds + microseconds / 1e6`? It would be a great convenience for moving from date-land to scalar-land before plotting. Thanks!

**Comment by jreback** [comment]
see here: http://pandas.pydata.org/pandas-docs/stable/timedeltas.html#frequency-conversion

**Comment by jreback** [comment]
canoncially this is just an astype or division operation

```
In [3]: s = Series(pd.timedelta_range('1day',periods=5,freq='1s'))

In [4]: s
Out[4]: 
0   1 days 00:00:00
1   1 days 00:00:01
2   1 days 00:00:02
3   1 days 00:00:03
4   1 days 00:00:04
dtype: timedelta64[ns]

In [5]: s.astype('timedelta64[s]')
Out[5]: 
0    86400
1    86401
2    86402
3    86403
4    86404
dtype: float64

In [12]: s/np.timedelta64(1,'s')
Out[12]: 
0    86400
1    86401
2    86402
3    86403
4    86404
dtype: float64

In [6]: s.iloc[0].total_seconds()
Out[6]: 86400.0
```

I suppose could add a ``Series.dt.total_seconds`` to make ``TimedeltaIndex`` consistent with the method on ``Timedelta``

**Comment by jorisvandenbossche** [comment]
+1 on a `Series.dt.total_seconds()`

**Comment by brandon-rhodes** [comment]
Wonderful! Thank you — Pandas is an unusually responsive project to feature suggestions, and gets better with each version.

**Comment by brandon-rhodes** [comment]
And thank you, @jreback, for the idea of a `s.astype('timedelta64[s]')` — I had never seen an `astype` before with something in brackets!

**Comment by jreback** [comment]
@brandon-rhodes np. issues building up like crazy, so trying to work them down :)
