### ISSUE TITLE
support for simple interpolation with new values

### ISSUE THREAD

**Issue by denfromufa** [pydata/pandas#10811]
something along the lines: 

```
df.reindex(df.index.tolist()+new_values).sort().interpolate().ix[new_values]
```

**Comment by TomAugspurger** [comment]
Could you write up a sketch of what the API would look like?

**Comment by denfromufa** [comment]
The API is simple: pass new_values as keyword argument to interpolate()
with a default = None.

**Comment by TomAugspurger** [comment]
What if there are missing values, are they interpolated at too?
Do you return the interpolated values only, or their union with the original Series?
What does new_values look like for a DataFrame?

**Comment by denfromufa** [comment]
1. Return interpolation for new_values only.
2. new_values is plain 1d list for dataframe index of 1d.
3. This feature can be extended to Multiindex later.

**Comment by denfromufa** [comment]
I actually forgot .sort() before interpolate.

**Comment by denfromufa** [comment]
And new_values should really handle 1d numpy arrays and python iterable
objects.

**Comment by denfromufa** [comment]
and here is the function to enable this feature:

```
def interpeasy(df, new_idxs):
    return df.reindex(
        np.concatenate(
        (df.index, np.unique(new_idxs)))
        ).sort().interpolate().ix[new_idxs]
```

**Comment by shoyer** [comment]
I agree that something like this would be useful -- in many cases this is exactly what I'm looking for with interpolation. Note that from an implementation perspective, this is also much closer to what scipy's interpolation functions already do.

@denfromufa what would the full new function signature look like? e.g., we currently have this: http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.interpolate.html

**Comment by TomAugspurger** [comment]
FWIW, I think this might warrant a new method, e.g. `df.interpolate_at(values, method='linear')`. I wanted to include something like this when I did interpolate on DataFrames originally, but the API got too clunky.

**Comment by shoyer** [comment]
I do recall some discussion about interpolate_at, possibly related to fillna (which is very similar to interpolate in functionality). Let me see if I can dredge up that discussion.

**Comment by denfromufa** [comment]
https://github.com/pydata/pandas/issues/9340

**Comment by TomAugspurger** [comment]
Thanks @denfromufa, let's close this one and move over the #9340.
