### ISSUE TITLE
Inconsistency with MovingOLS min_periods

### ISSUE THREAD

**Issue by MatthewGilbert** [pydata/pandas#10823]
I'm not sure if this is a bug or a typo in the documentation but for the `min_periods` parameter in MovingOLS the documentation claims

    min_periods : int
           Threshold of non-null data points to require.
           If None, defaults to size of window.

However this does not seem to be the case? From line 640-648 we have

        if self._is_rolling:
            if window is None:
                raise AssertionError("Must specify window.")
            if min_periods is None:
                min_periods = window
        else:
            window = len(self._x)
            if min_periods is None:
                min_periods = 1

So this is not true for expanding window MovingOLS? Would it be appropriate to update the documentation to reflect this?

**Comment by jorisvandenbossche** [comment]
Yes, certainly welcome to update the docstring.

(and even more welcome to look into migrating this to statsmodels!)

**Comment by MatthewGilbert** [comment]
Okay I will look at updating the docs. Probably don't have the bandwidth to take on migrating this to statsmodels, is this something that is actively being discussed though so I can follow along?

**Comment by jorisvandenbossche** [comment]
Issue that tracks this on the pandas side: https://github.com/pydata/pandas/issues/6077 
and for statsmodels: https://github.com/statsmodels/statsmodels/issues/2302

**Comment by MatthewGilbert** [comment]
From the conversation in #6077 it seems like the plan is to move the stats part of pandas into statsmodels and deprecate the functionality in pandas? Is this still the plan? I do not see any deprecation warnings using 0.16.1 however from that thread it seems like that was going to be the idea?

**Comment by jorisvandenbossche** [comment]
That is indeed the idea. But since the functionality is not yet in statsmodels (at least eg the MovingOLS), we cannot already deprecate it in pandas saying you have to use the statsmodels one.
