### ISSUE TITLE
Can't access 'Strike' column in option dataframe

### ISSUE THREAD

**Issue by zhimakaimenxa** [pydata/pandas#10830]

**Comment by zhimakaimenxa** [comment]
I'm doing calculating work from yahoo option web page with the following code:

aapl = Options('aapl', 'yahoo')
data = aapl.get_all_data()

middle = data.query('Expiry == "2015-08-28" & Type == "call"')
strike = middle.ix[:, 0]

I find I can't access 'Strike' column with above code, when I retrieve data of column 0, I get 'Ask' column. It seems pandas only looks 'Strike' as index, instead of data column.

if I use following code:

strike = middle.index.levels[0]

the returned result is all the element of 'Strike' index, but not the real column data of 'Strike' from the query above ( middle = data.query('Expiry == "2015-08-28" & Type == "call"') ). Is this a problem in pandas?

Thanks

Li

**Comment by jreback** [comment]
``Strike`` is an index of the dataframe. You can simply ``.reset_index()`` if you want to move the index to the columns

```
In [19]: middle.head()
Out[19]: 
                                             Last  Bid  Ask  Chg PctChg  Vol  Open_Int     IV  Root IsNonstandard Underlying  Underlying_Price          Quote_Time
Strike Expiry     Type Symbol                                                                                                                                     
85     2015-08-28 call AAPL150828C00085000  28.56    0    0    0  0.00%    2       458  0.00%  AAPL         False       AAPL            115.96 2015-08-17 16:00:00
90     2015-08-28 call AAPL150828C00090000  26.11    0    0    0  0.00%  100       194  0.00%  AAPL         False       AAPL            115.96 2015-08-17 16:00:00
95     2015-08-28 call AAPL150828C00095000  18.45    0    0    0  0.00%  185       156  0.00%  AAPL         False       AAPL            115.96 2015-08-17 16:00:00
98     2015-08-28 call AAPL150828C00098000  17.06    0    0    0  0.00%    1        11  0.00%  AAPL         False       AAPL            115.96 2015-08-17 16:00:00
99     2015-08-28 call AAPL150828C00099000  16.70    0    0    0  0.00%    3         3  0.00%  AAPL         False       AAPL            115.96 2015-08-17 16:00:00

In [20]: middle.reset_index().head()['Strike']
Out[20]: 
0    85
1    90
2    95
3    98
4    99
Name: Strike, dtype: float64
```

**Comment by jreback** [comment]
docs are [here](http://pandas.pydata.org/pandas-docs/stable/indexing.html#set-reset-index)

**Comment by zhimakaimenxa** [comment]
Thanks jreback, it works!
