### ISSUE TITLE
Slow DataFrame column data access

### ISSUE THREAD

**Issue by Suor** [pydata/pandas#10843]
The simplest way to access underlying data (ndarray) for dataframe column is `df['column_name'].values`. But it is so slow, that special cache is used for it:

```python
>>> import pandas as pd
>>> import numpy as np
>>> df = pd.DataFrame(np.zeroes((1000, 5)), columns=list('abcde'))
>>> %timeit df['a'].values; df._item_cache = {}
10000 loops, best of 3: 73.1 µs per loop
```

For regular non-sparse array this should approach:

```python
>>> %cpaste
def get_col_values(df, name):
    i = df.columns.get_loc(name)
    bm = df._data
    return bm.blocks[bm._blknos[i]].iget(bm._blklocs[i])
>>> %timeit get_col_values(df, 'a')
100000 loops, best of 3: 4.67 µs per loop
```

**Comment by jreback** [comment]
well 90% of this comes from the calculation for whether this index it unique. So this is actually just a matter of a couple of function calls.

Not sure how this actually matters in reality though. If you are relying on extreme performance for selecting columns which inherently is an iterative process then use a dict of ndarrays.

**Comment by Suor** [comment]
I can't see where index is checked for uniquiness. Most of the time is spent in `NDFrame._get_item_cache()`:

```
In [4]: timeit df._get_item_cache('a'); df._item_cache = {}
10000 loops, best of 3: 73.3 µs per loop

In [5]: timeit df['a']; df._item_cache = {}
10000 loops, best of 3: 77.2 µs per loop
```

And here are line profiling of it:

```
Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
  1079                                               @profile
  1080                                               def _get_item_cache(self, item):
  1081                                                   """ return the cached item, item represents a label indexer """
  1082     82222        49337      0.6      0.9          cache = self._item_cache
  1083     82222        51398      0.6      1.0          res = cache.get(item)
  1084     82222        30061      0.4      0.6          if res is None:
  1085     82222      2304416     28.0     42.8              values = self._data.get(item)
  1086     82222      2079673     25.3     38.6              res = self._box_item_values(item, values)
  1087     82222        60641      0.7      1.1              cache[item] = res
  1088     82222       576752      7.0     10.7              res._set_as_cached(item, self)
  1089                                           
  1090                                                       # for a chain
  1091     82222       195010      2.4      3.6              res.is_copy = self.is_copy
  1092     82222        33936      0.4      0.6          return res
```

Significant time is spent in boxing values here and in `BlockManager.iget()`:

```
Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
  2872                                               @profile
  2873                                               def iget(self, i, fastpath=True):
  2874                                                   """
  2875                                                   Return the data as a SingleBlockManager if fastpath=True and possible
  2876                                           
  2877                                                   Otherwise return as a ndarray
  2878                                           
  2879                                                   """
  2880                                           
  2881     41111        61730      1.5      6.9          block = self.blocks[self._blknos[i]]
  2882     41111        79573      1.9      8.8          values = block.iget(self._blklocs[i])
  2883     41111        37949      0.9      4.2          if not fastpath or block.is_sparse or values.ndim != 1:
  2884                                                       return values
  2885                                           
  2886                                                   # fastpath shortcut for select a single-dim from a 2-dim BM
  2887     41111        22861      0.6      2.5          return SingleBlockManager([ block.make_block_same_class(values,
  2888     41111        34554      0.8      3.8                                                                  placement=slice(0, len(values)),
  2889     41111        17342      0.4      1.9                                                                  ndim=1,
  2890     41111       382364      9.3     42.5                                                                  fastpath=True) ],
  2891     41111       263750      6.4     29.3                                    self.axes[1])
```

**Comment by Suor** [comment]
Extracting underlying values is significant for optimization. You/researcher write nice code with pandas, but you should be able to fall back to numpy for faster operations. E.g. look how `get_TE_se()` is implemented [here](https://github.com/idrdex/star-django/blob/0614efc754753d8ddd6f0431e832d3751fa4feab/analysis/analysis.py#L461).

Here is it's line profiling:
```
Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
   506                                               @staticmethod
   507                                               @profile
   508                                               def get_TE_se(gene_stats):
   509                                                   # Convert to numpy arrays for speed
   510        50         5496    109.9     21.0          caseSigma = gene_stats['caseDataSigma'].values
   511        50         5295    105.9     20.2          caseCount = gene_stats['caseDataCount'].values
   512        50         5096    101.9     19.4          controlSigma = gene_stats['controlDataSigma'].values
   513        50         4900     98.0     18.7          controlCount = gene_stats['controlDataCount'].values
   514                                           
   515                                                   # MD method
   516        50          854     17.1      3.3          na = np.sqrt(caseSigma ** 2 / caseCount + controlSigma ** 2 / controlCount)
   517                                           
   518                                                   # Studies with non-positive variance get zero weight in meta-analysis
   519       983          573      0.6      2.2          for i in range(len(na)):
   520       933         1019      1.1      3.9              if caseSigma[i] <= 0 or controlSigma[i] <= 0:
   521                                                           na[i] = float('nan')
   522                                           
   523        50         2970     59.4     11.3          return pd.Series(na, index=gene_stats.index)
```

Column access is too slow.

**Comment by Suor** [comment]
Maybe I need to make this into feature request? Something like `df.get_column_values('a')`.

**Comment by jreback** [comment]
@Suor always glad to profile things. But you have to make sure it works with the current tests suite. The optimizations you are talking about are so tiny I can't imagine that any real use case would benefit.

**Comment by Suor** [comment]
I presented my use case. I can add that I am processing large amount dataframes resulted from `.groupby()` call. By switching to numpy arrays I already made it 2.5x faster. And this optimization could make function above 4x faster again.

Maybe if you process small amount of large dataframes then this is insignificant, but here it's decisive.

**Comment by 0phoff** [comment]
Sorry to bump this old thread, but I was wondering whether there is a chance this would ever come to pandas? I am doing lots of computations on data with ``groupby().apply()`` and I have sped up the function quite a bit by accessing the raw numpy arrays where possible.  
After profiling, I noticed that a considerable amount of time was spent getting those arrays, which is how I stumbled on this thread. Using @Suor's function, I was able to get a 2x speedup (30sec -> 14sec), so this again proves that it can be useful to have this function.

If I understand anything from this issue, it is that the biggest bottleneck comes from trying to cache the data for future hits? If that is the case, maybe we could implement a ``.values_`` property that returns the numpy array witouth caching or checking the cache for the data?  
I am not well aware how pandas works behind the scenes, but to me it sounds useful to have a function returning numpy arrays without caching. Whenever I would want a numpy array, I probably want to perform some heavy computations that return a different value, so caching makes no sense in those situations? (eg. in a ``groupby().apply()`` situation) Then again, this might be something different as I have no clue how pandas works.

I am just another user, that would benefit from such a function being implemented.

**Comment by vanschelven** [comment]
> Not sure how this actually matters in reality though.

Well, it matters in my reality too.

The particular scenario where this is bothering me is when using pandas in dataframes with very few rows (e.g. a signle row). In that context, per-column slowness is not nicely amortised over the large number of rows, and the per-row cost balloons.

I understand that data with few rows is not exactly Pandas' sweet spot; on the other hand: the fact that Pandas is non-performant for the small data scenario implies that it cannot be employed as a single solution across the big data / small data domains. Which in turn may take Pandas off the table as a potential tool for the big-data scenario too.
