### ISSUE TITLE
REL: 0.17.0

### ISSUE THREAD

**Issue by jorisvandenbossche** [pydata/pandas#10848]
To keep track of the 0.17.0 release

- [x] Potentially change ``FutureWarning`` to ``DeprecationWarning`` for the changed in sorting, xref https://github.com/pydata/pandas/pull/10726
- [x] go thru enhancements make sure that we are using versionadded tags

**Comment by jreback** [comment]
@jorisvandenbossche @TomAugspurger @sinhrks @shoyer @cpcloud 

going to do the RC this friday.

**Comment by shoyer** [comment]
Sounds good, I'll cleanup my plot methods accessor PR ASAP.

**Comment by jorisvandenbossche** [comment]
fine!

@jreback question: would it be possible to get the conda builds working in the pandas channel http://anaconda.org/pandas/pandas? Would be nice if we could provide conda packages of the RC through the channel, this could make it easier to test it out.

**Comment by jreback** [comment]
yes I will have conda builds up (for all platforms)

**Comment by jreback** [comment]
so as a test I built all of the packages. (all master, windows a few commits behind).

```
[jreback-~/pandas] conda search "pandas >0.16.2*" -c pandas --spec --plat linux-64 --override-channels
Fetching package metadata: ..
pandas                       v0.16.2              nppy34_623  pandas          
                             v0.16.2              nppy27_623  pandas          
[jreback-~/pandas] conda search "pandas >0.16.2*" -c pandas --spec --plat win-64 --override-channels
Fetching package metadata: ..
pandas                       v0.16.2              nppy34_590  pandas          
                             v0.16.2              nppy27_590  pandas          
[jreback-~/pandas] conda search "pandas >0.16.2*" -c pandas --spec --plat osx-64 --override-channels
Fetching package metadata: ..
pandas                       v0.16.2              nppy34_623  pandas          
                             v0.16.2              nppy27_623  pandas          
```

can people try the win/linux packages and install just to make sure they are not horribly broken.

e.g. ``conda install pandas -c pandas``

thxs.

**Comment by jorisvandenbossche** [comment]
I installed and quickly tests it on py2.7 / windows, and that seems to work fine!

**Comment by jreback** [comment]
gr8. I am not 100% I am building a kosher recipe on 3.4/windows.....but when I do the rc will know.

**Comment by TomAugspurger** [comment]
Used the 3.4 Windows build (lightly) today. I’ll swap it in the environment I’m using tomorrow and let you know how things look.

-Tom

**Comment by jreback** [comment]
@TomAugspurger gr8 thanks!

**Comment by jreback** [comment]
RC1 is posted: https://github.com/pydata/pandas/releases/tag/v0.17.0rc1

going to send out the e-mail / update pandas-website shortly.

**Comment by jreback** [comment]
posted to some downstream projects, if any others, pls post and issue and record here:

https://github.com/matplotlib/matplotlib/issues/5050
https://github.com/mwaskom/seaborn/issues/702

**Comment by rosnfeld** [comment]
A minor note: are the RC docs expected to render images properly? I don't see images at http://pandas-docs.github.io/pandas-docs-travis/whatsnew.html#changes-to-excel-with-multiindex

**Comment by kawochen** [comment]
I referenced the wrong issue in my PR: 
Bug in read_msgpack where encoding is not respected (GH10580)
It should be 10581.

**Comment by jreback** [comment]
@rosnfeld not sure about the images... @jorisvandenbossche any idea?

**Comment by shoyer** [comment]
Looks like we just forgot to commit these images in our PRs. This is easy to miss because because our `.gitignore` includes the `_static` directory.

**Comment by jreback** [comment]
@kawochen fixed that issue, thanks!

**Comment by jreback** [comment]
So obviously waiting on merging this: https://github.com/pydata/pandas/pull/11173 (just needs a couple of more tests).

Thoughts on pushing out a 0.17.0rc2. for say a week? (e.g. till next sunday/monday). Then release next sunday/monday? or just release next sunday/monday. (I am busy with strata this week, so doing a release takes a bit of time).

**Comment by jorisvandenbossche** [comment]
A second release candidate sounds good to me! At least, if you have the time of course

**Comment by jreback** [comment]
ok rc2 is up and announced: https://groups.google.com/forum/#!topic/pydata/k03SQiBG3jc

**Comment by jreback** [comment]
and we are released: https://groups.google.com/forum/#!topic/pydata/2nUh2UenY_o

thanks to everyone who contributed!
