### ISSUE TITLE
inconsistent dtype conversion during join

### ISSUE THREAD

**Issue by michaelaye** [pydata/pandas#10869]
Just stumbled about a very nasty subtle dtype inconsistency after join operation that crippled by out-of-core-join-many-result-files pipeline for unfitting index sizes for the HDF append operation.
See the example code here:
https://nbviewer.jupyter.org/gist/michaelaye/1c34cda54872046b5989
or here as screenshot:
<img width="849" alt="screenshot 2015-08-20 15 23 01" src="https://cloud.githubusercontent.com/assets/69774/9396054/5df0dbc6-474f-11e5-9282-eff823d51b18.png">

What happens that the dtypes of the to-be-joined dataframe depend on if the joining dataframe has either 1 or 2 columns.

Any hint how to avoid that would be appreciated.

Version: '0.16.2+148.gc740bb0'

**Comment by jreback** [comment]
No this depends on whether things are converted to float (e.g. a ``NaN`` is needed or not)

```
In [10]: df1.join(df2)       
Out[10]: 
         0         1         2         3         4         5         6        7         8         9   10  11  12
0  0.516009  0.060819  0.651483  0.272277  0.666867  0.559865  0.790434  0.11257  0.990345  0.329986   1   2   3
1  0.355554  0.344380  0.835125  0.101141  0.691940  0.894923  0.922320  0.88279  0.497368  0.253967 NaN NaN NaN

In [11]: df1.drop(1).join(df2)
Out[11]: 
         0         1         2         3         4         5         6        7         8         9   10  11  12
0  0.516009  0.060819  0.651483  0.272277  0.666867  0.559865  0.790434  0.11257  0.990345  0.329986   1   2   3
```

**Comment by jreback** [comment]
brave man for using master though :)

**Comment by michaelaye** [comment]
So i guess the only way to force dtype consistency is to copy the one row data frame n times the height of the first one to avoid the need for NaNs?
Lacks elegance**2. ;)

**Comment by jreback** [comment]
how can you avoid the need for ``NaN`` in a type that doesn't support it (ATM)?

not really sure how/why this is an issue.

**Comment by michaelaye** [comment]
I need to join data frame 1 with data frame 2 and sometimes data frame 1 has 1 row and sometime more than 1.  When it has more than 1 the join operation leads to NaNs and therefore a type conversion of the Int columns of data frame 2 when joining them. 
After they have been joined I need to store them in HDF files during an parallel processing for later joining them into a big HDF store. But for that the types need to be consistent. So I need to avoid the automatic conversion to float for the case data frame 1 has more than 1 row (which I prefer to the solution of concert the whole data frame 2 to floats even so it's storing  integers conceptually).

**Comment by jreback** [comment]
is their a reason you would just not use all floats in the first place ?

**Comment by michaelaye** [comment]
I didn't calculate if it mattered in terms of space for me, but usually I stay with integers if I can in case I need to do selection on their values. df[df.a==x] is easier to type than df[(df.a - x) < eps]

**Comment by michaelaye** [comment]
I shouldn't have used `join` in the first place, I think as I do a simple concat actually.
Here's my solution for keep using ints where appropriate:
```python
if len(df1) > 1:
    df2 = df2.append([df2] * (len(df1) -1), ignore_axis=True)
joined = pd.concat([df1, df2], axis=1)
```
