### ISSUE TITLE
Add Base.to_graphviz

### ISSUE THREAD

**Issue by sinhrks** [pydata/pandas#10865]
Add function to return ``graphviz`` instance created from dask graph for below reasons:

- When using IPython, ``.visualize`` outputs unnecessary image file
- Sometimes we want to modify graphviz instance directly

**Comment by shoyer** [comment]
Pretty sure you meant to make this issue in dask, not pandas :)

**Comment by jreback** [comment]
@sinhrks I hear you are a big contributor :)

**Comment by sinhrks** [comment]
Ah, sorry.
