### ISSUE TITLE
BUG: Index name is not preserved during some conversions

### ISSUE THREAD

**Issue by soupault** [pydata/pandas#10875]
The issue is existing name of `Index` is dropped during conversion to either `TimedeltaIndex` or `DatetimeIndex`.

    In [42]: vec = ['01:02:03', '01:02:04']
    In [43]: i = pd.Index(vec, name='label')
    In [44]: i
    Out[44]: Index(['01:02:03', '01:02:04'], dtype='object', name='label')

    In [45]: pd.to_datetime(i)
    Out[45]: DatetimeIndex(['2015-08-21 01:02:03', '2015-08-21 01:02:04'], dtype='datetime64[ns]', freq=None, tz=None)

    In [46]: pd.to_timedelta(i)
    Out[46]: TimedeltaIndex(['01:02:03', '01:02:04'], dtype='timedelta64[ns]', freq=None)

**Comment by soupault** [comment]
Bug is blocking for https://github.com/pydata/pandas/pull/10845 to be merged (comparison in unittest).

**Comment by soupault** [comment]
For `to_timedelta`:
Could add `to_timedelta` method to `pandas/core/index.py`.

Simplest solution is to add something like this to `pandas/tseries/timedeltas.py`:

    elif isinstance(arg, ABCSeries):
        from pandas import Series
        values = _convert_listlike(arg.values, box=False, unit=unit)
        return Series(values, index=arg.index, name=arg.name, dtype='m8[ns]')
    +elif isinstance(arg, ABCIndexClass):
    +    from pandas import TimedeltaIndex
    +    values = _convert_listlike(arg.values, box=box, unit=unit)
    +    return TimedeltaIndex(values, name=arg.name)
    elif is_list_like(arg):
        return _convert_listlike(arg, box=box, unit=unit)

**Comment by jreback** [comment]
closed by #10945
