### ISSUE TITLE
EuroScipy 2015 pandas sprint

### ISSUE THREAD

**Issue by jorisvandenbossche** [pydata/pandas#10877]
There will be a pandas sprint at EuroScipy (https://www.euroscipy.org/2015/sprints/) on Sunday the 30th of August. 
The sprints will take place at the Seminar Centre of the Hauser Forum (very near to the conference venue) from 10am to 5pm.

This issue will be the landing page for contributors.

[pandas](http://pandas.pydata.org) is an open source, BSD-licensed library providing high-performance, easy-to-use data structures and data analysis tools for the Python programming language. 

See our shiny new [Contributing Guidelines & Instructions](http://pandas-docs.github.io/pandas-docs-travis/contributing.html)

Here are various issues that are open and would like your attention:

- [Difficulty Novice](https://github.com/pydata/pandas/issues?q=is%3Aopen+is%3Aissue+label%3A%22Difficulty+Novice%22)
- [Difficulty Intermediate](https://github.com/pydata/pandas/issues?q=is%3Aopen+is%3Aissue+label%3A%22Difficulty+Intermediate%22)
- [Difficulty Advanced](https://github.com/pydata/pandas/issues?q=is%3Aopen+is%3Aissue+label%3A%22Difficulty+Advanced%22)

Please comment on an issue if you are working on it.

Here is a [link](https://gitter.im/pydata/pandas) to the gitter dev chatroom.

#### How to prepare?

If you want to prepare the sprint, the most important is to *set up a development environment*: forking the pandas repo, cloning your fork locally, installing all development dependencies in an environment and testing that you can build pandas locally, ...
You can find some information about this in our contributing docs: http://pandas-docs.github.io/pandas-docs-travis/contributing.html

#### What to work on?

There is no plan to work on something specific, but the idea is that everybody can choose on something they would like to work, and that there is some guidance to do that (but of course, if some of the attendants want to work together on a specific topic, this is certainly possible!).

You can work on whatever you like, but to facilitate finding an appropriate issue, we have the 'Difficulty Novice / Intermediate / Advanced' labels. 
I will also put some ideas of issues I would like to see tackled during the sprints here in the coming days.

Please comment on an issue if you are working on it.

**Comment by jreback** [comment]
@jorisvandenbossche awesome!

**Comment by jorisvandenbossche** [comment]
Some possible idead that could get tackled on the sprint (just some ideas, not restrictive, you are free to choose whatever you like!):

**Ensuring correct examples in the docstrings with doctest**

* First try to run the doctest, and start fixing those
* Enable the tests on travis

**Comment by qwhelan** [comment]
Anyone interested in digging into regressions identified by ```asv``` can reference my run data here (equivalent to ```asv preview```): http://qwhelan.github.io/pandas_asv/

An explicit regression list is here: http://qwhelan.github.io/pandas_asv/#regressions

**Comment by jorisvandenbossche** [comment]
There are some other issues listed here as well: https://github.com/pydata/pandas/issues/8323 (from a previous sprint, so some of them can all be solved)
