### ISSUE TITLE
Unexpected keyword argument for some arguments documented in to_latex

### ISSUE THREAD

**Issue by gsmafra** [pydata/pandas#10888]
To reproduce the errors:

    import pandas as pd

    names = ['Bob','Jessica','Mary','John','Mel']
    births = [968, 155, 77, 578, 973]
    BabyDataSet = zip(names, births)
    df = pd.DataFrame(data=BabyDataSet, columns=['Names', 'Births'])

Any of these will yield a ``TypeError``:

    print df.to_latex(frame=None)
    print df.to_latex(force_unicode=False)
    print df.to_latex(justify='left')

I assume this is a problem with documentation and that these arguments are deprecated

**Comment by jreback** [comment]
this is using the same doc-string formatter as ``to_html`` and ``to_string``. So needs to be refactored to add args to the other methods separately.

pull-requests welcome.

**Comment by jreback** [comment]
closed by #11011
