### ISSUE TITLE
DOC: date_range docstring should list allowed frequencies

### ISSUE THREAD

**Issue by michaelaye** [pydata/pandas#10893]
So far it just says this:
```
freq : string or DateOffset, default ‘D’ (calendar daily)
Frequency strings can have multiples, e.g. ‘5H’
```
but it should also either refer to a doc where possible frequencies are being discussed or list them here.

**Comment by jorisvandenbossche** [comment]
Yes, fully correct that this could be better. Closing this in favour of #3324
