### ISSUE TITLE
Handle between_time on empty series

### ISSUE THREAD

**Issue by MichaelAdolph** [pydata/pandas#10897]
Right now using between_time on an empty series will raise an TypeError: Index must be DatetimeIndex. I would think that it would make more sense to return an empty list (or at least return a more helpful Error).
```python
import datetime as dt
import pandas as pd
s = pd.Series([])
s.between_time(dt.time(0, 0), dt.time(23, 0))
```
I would assume that expanding the Error Handler of the method should do the trick:
```python
[...]
except AttributeError:
    if self.empty:
        return self
    else:
         raise TypeError('Index must be DatetimeIndex')
```

The Error persists on this configuration:
INSTALLED VERSIONS
commit: None
python: 2.7.6.final.0
python-bits: 32
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None

pandas: 0.16.2
nose: 1.3.3
Cython: 0.20.1
numpy: 1.8.1
scipy: 0.14.0
statsmodels: 0.5.0
IPython: 2.1.0
sphinx: 1.2.2
patsy: 0.2.1
dateutil: 2.2
pytz: 2014.3
bottleneck: 0.8.0
tables: 3.1.1
numexpr: 2.4
matplotlib: 1.4.0
openpyxl: 2.0.3
xlrd: 0.9.3
xlwt: 0.7.5
xlsxwriter: None
lxml: 3.3.5
bs4: 4.3.2
html5lib: 0.999
httplib2: None
apiclient: None
sqlalchemy: 0.9.4
pymysql: None
psycopg2: None

**Comment by jreback** [comment]
I suppose that would be ok. It violates the guarantees (that it must be have a ``DatetimeIndex``). A pull-requests would be ok.

**Comment by MichaelAdolph** [comment]
Well, I tried to fix this and create a pull request. It's my first time, so I hope I didn't make any major mistakes

**Comment by jreback** [comment]
actually on 2nd thought. This is a correct error message. You don't have a ``DatetimeIndex``, e.g.

```
In [10]: s = pd.Series(index=pd.date_range('20130101',periods=1)[:0])

In [11]: s
Out[11]: Series([], Freq: D, dtype: float64)

In [12]: s.index
Out[12]: DatetimeIndex([], dtype='datetime64[ns]', freq='D', tz=None)

In [13]: s.between_time(dt.time(0, 0), dt.time(23, 0))
Out[13]: Series([], Freq: D, dtype: float64)
```

**Comment by MichaelAdolph** [comment]
This is True, but I believe it first doesn't any harm and secondly gives the expected result: If I have a dynamically calculated Series, which may be empty or filled with data and I querry if there are any values between time a and b I expect an empty list if there are no values between these timesteps. And that is also the case for an empty Series.
Obviously I could modify my calculated series the way that it contains a DatetimeIndex even if empty, but I think this is rather tedious.

**Comment by jreback** [comment]
well if it doesn't have a DatetimeIndex it is an error
I don't think we do this for any other Datetime ops

this is a very specific operation and should fail if it's the wrong type

**Comment by MichaelAdolph** [comment]
closed associated pull request as result of discussion
