### ISSUE TITLE
df.apply has problems storing tuples into new column

### ISSUE THREAD

**Issue by michaelaye** [pydata/pandas#10900]
I am quite perplexed about this: 
A function applied to rows of dataframes that returns a tuple throws an error if the result is stored into a new column, but does not if the column already exists? This does not happen if I return just a number.
Get the example notebook here:
https://gist.github.com/a83ed19c43fe2eaac6a4
or see it here:
https://nbviewer.jupyter.org/gist/michaelaye/a83ed19c43fe2eaac6a4

Using master pandas. ('0.16.2+442.g24c147a', 24c147a369d4)

**Comment by jreback** [comment]
you asked the same question here: https://github.com/pydata/pandas/issues/10399

my answer stands. I find this odd that you are trying to shoe-horn a tuple into a column anyhow. Just use a loop and concat if you really want to do that. ``.apply`` is already way over complicated.

**Comment by michaelaye** [comment]
I'm sorry, forgot about the older issue.
I don't understand your shoe-horn comment. I need to store tuples because they, together, define the status of an observation. This is not a weird way to create Series, I need to store the tuples themselves.

**Comment by michaelaye** [comment]
So, from the older issue it is clear that the re-interpretation as a Series is what throws off the apply process. How can I prevent that interpretation and let pandas know to just store the tuple? Interestingly, it works when the column exists without a problem, which is why I reported it as an oddity.

**Comment by jreback** [comment]
Just do this. I mean ``.apply`` will see that you are returning an iterable, which violates what ``.apply`` does.

```
In [42]: df['new_col'] = [ tuple(row[col] for col in ['SPE_OFS', 'SPE_SIZE', 'SPA_OFS', 'SPA_SIZE']) for _, row in df.iterrows() ]

In [43]: df
Out[43]: 
   SPE_OFS  SPE_SIZE  SPA_OFS  SPA_SIZE       new_col
0        3         1        4         1  (3, 1, 4, 1)
1        3         4        1         1  (3, 4, 1, 1)
2        2         3        1         1  (2, 3, 1, 1)
3        4         3        2         2  (4, 3, 2, 2)
4        3         2        3         4  (3, 2, 3, 4)
5        4         2        3         1  (4, 2, 3, 1)
6        4         2        4         3  (4, 2, 4, 3)
7        3         2        2         3  (3, 2, 2, 3)
8        1         1        3         4  (1, 1, 3, 4)
9        2         2        2         3  (2, 2, 2, 3)
```

**Comment by michaelaye** [comment]
ah darn, thanks. Sometimes it's easier than one thinks.
