### ISSUE TITLE
TST: fix pythonxy changed links in test_html.py

### ISSUE THREAD

**Issue by jreback** [pydata/pandas#10906]
skipping these tests as the link seems t have changed: https://github.com/pydata/pandas/commit/a3c4b59f1190035df98e70635291fce0dc04b91d

but would like to replace these with something new testing the same functionaility.

**Comment by terrytangyuan** [comment]
How about we save the static html files in the resources folder and read_html from local file for testing?

**Comment by jreback** [comment]
that's ok too

**Comment by terrytangyuan** [comment]
I realized you wanted to test read_html() from an actual html link, instead of reading html from local file, right? So should I go ahead find another html link that can be tested in the same way OR save html locally to test?  @jreback

**Comment by jreback** [comment]
ideally another link would be best

**Comment by jreback** [comment]
closed by #10958
