### ISSUE TITLE
execute str.upper() on multi-type data type column will change number data to NA

### ISSUE THREAD

**Issue by cloga** [pydata/pandas#10915]
Version : 0.16.2
OS : Mac

What I think is when use .str need first change compulsory change dtype to str, but in my situation, pandas change my number data to NA.

And when I use .astype('str')  first,  I got the output I need, but I think this may may somebody confused and make some mistake without .astype('str') .

**Comment by jreback** [comment]
pls show a reproducible example as it is not clear what you are doing.

**Comment by cloga** [comment]
Hi Jreback,

Here is reproducible example:
sample = pd.read_excel('http://www.cloga.info/files/sample.xlsx') # read sample data
sample['Website'].value_counts() # print website name, there are some websites name are numbers, such as 17173, 5068
```
17173    169
52PK      42
265G      19
7K7K      15
5068      10
7k7k       7
52pk       7
265g       2
dtype: int64

```
sample['Website'] = sample['Website'].str.upper() # change str to upper
sample['Website'].value_counts() # now you may see 17173, 5068 were lost

```
52PK    49
7K7K    22
265G    21
dtype: int64

```

**Comment by jreback** [comment]
@cloga pls use an example that one can copy-paste.

**Comment by sinhrks** [comment]
I may understand what it it means. You're asking why ``str.upper`` results in ``NaN`` for non-str types (thus filtered in ``value_counts``)?

```
import pandas as pd
s = pd.Series([1, 2, 'xx', 'xx'])

s.str.upper()
# 0    NaN
# 1    NaN
# 2     XX
# 3     XX
# dtype: object

s.str.upper().value_counts()
# XX    2
# dtype: int64
```

It is natural because you cant call ``upper`` method for numbers.

```
x = 1
x.upper()
# AttributeError: 'int' object has no attribute 'upper'
```

If you want to convert them in non-standard way, use ``apply``.

```
s.apply(lambda x: x.upper() if isinstance(x, str) else x).value_counts()
# XX    2
# 2     1
# 1     1
# dtype: int64
```

**Comment by cloga** [comment]
@sinhrks You are correct. what I wonder is call .str.upper() on numbers will results `NA`。For my situation I have some websites names mix with numbers, upper and lower string, and what I want is to convert string to upper, but upper will results `NA` on numbers, so I will lost some website name.

Is it possible change to upper or lower on numbers will compulsory change number to string but not `NA`. And this is common in Excel , also follow intrinsic.

Thanks.

**Comment by jreback** [comment]
@cloga you cannot mix numbers and strings, best to 

``s.apply(str).upper()`` if you want to upper things (but they will all be strings)
