### ISSUE TITLE
Series.dot returns undocumented ndarray type

### ISSUE THREAD

**Issue by skycaptain** [pydata/pandas#10924]
According to the documentation `pandas.Series.dot` returns a `pandas.Series` or a scalar value. Certainly, the output type is depending on the type and dimension of the first positional argument of the `pandas.Series.dot` function. The following example outputs a value of type `numpy.ndarray` using pandas (0.16.2):
```python
In [0]: pd.Series(np.ones(3)).dot(np.eye(3))
out[0]: array([ 1.,  1.,  1.])
```
Even though, the result is plausible (array of scalars), the documentation is inconsistent on this. This only applies to `pandas.Series.dot`.

**Comment by jreback** [comment]
you are inputting an array so the results are plausible and can only be an array
not a Series, so the documentation is correct

btw this is not a very useful thing to do - pandas cannot align the input you give it and so it just returns a straight np.dot

**Comment by skycaptain** [comment]
As I already said and as you pointed out, the result is plausible, since the resulting index bases on the input columns. All I'm saying is, that to my understanding the documentation is incomplete, if the function can return a undocumented type. But I'm agreeing on closing this issue, if you think this is more a side effect than a real bug. Apparently, there are some use cases, but these can easily avoided by using indexed pd.DataFrames instead of np.ndarrays.

**Comment by kawochen** [comment]
I think input and output type specification can only be done on a best-effort basis -- if input is unexpected then due to duck-typing the code might still work but spit out an unexpected output.

**Comment by skycaptain** [comment]
After all, I'm totally agreeing. I just stumbled over this while debugging my application. Due to duck typing the input type might be unexcepted. Since the first positional argument will get deligated to numpy, if it's not an instance of ndframe, the output type is a ndarray. That's ok, if one is aware of this issue and does not run into unexpected exceptions.
