### ISSUE TITLE
ENH: density of a categorical

### ISSUE THREAD

**Issue by jreback** [pydata/pandas#10949]
I think ``s.cat.density`` is appropriate here

```
In [1]: s = Series(list('aabbcccc')).astype('category')

In [2]: 100*len(s.cat.categories)/len(s)
Out[2]: 37
```

**Comment by bashtage** [comment]
`density` seems like the wrong word since it isn't continuous.

**Comment by jreback** [comment]
this is to mimic ``sparse``, could be ``cardinaility`` as well (but that's kind of long).

**Comment by TomAugspurger** [comment]
`mass` is the discrete version density. I would expect that to be a normalized `value_counts` though. Not sure about `cardinality`.

**Comment by jorisvandenbossche** [comment]
Is this needed? Seems like easy to calculate it yourself if you need it

(is there a specific use case where this came up?)

**Comment by kawochen** [comment]
Of the suggestions so far I think `density` sounds the most reasonable.  There needn't be a probablistic interpretation at all.  It is more akin to a compaction ratio in string interning.

**Comment by shoyer** [comment]
I'm also not convinced this is necessary -- what's the use case here?

**Comment by jreback** [comment]
IIRC was having a discussion about the use cases of categoricals with high (k < n), and low (k << n), where k is number of cats and n is length. So density came up.

**Comment by jreback** [comment]
ok, I guess let's wait if/when an actual use case comes up
