### ISSUE TITLE
REGR: if someone wants to find where this was fixed would be gr8

### ISSUE THREAD

**Issue by jreback** [pydata/pandas#10980]
Regression from 0.16.2 to 0.16.1, but fixed in master, doced here: https://github.com/pydata/pandas/commit/2748e82ae99511f23f0f5134332706bde0798ef5

xref #10979 #9345 

Ideally want identify where this happened, and if we have enough test coverage.

**Comment by kawochen** [comment]
#10625 looks relevant

**Comment by jreback** [comment]
@kawochen yeh that didn't affect this. just trying to see if we are not testing this adequately as the regression slipped thru.

**Comment by jreback** [comment]
the note is close enough
