### ISSUE TITLE
Errors when running nosetest test_excel.py

### ISSUE THREAD

**Issue by terrytangyuan** [pydata/pandas#11005]
When I run tests nosetests pandas/io/tests/test_excel.py, I got a lot of errors but the code is just pulled from master without any changes. Could anyone try it on your end? Anything I missed?

**Comment by jreback** [comment]
you need to rebuild the c-extensions, lots of things have just been pushed

**Comment by terrytangyuan** [comment]
Yes, what I did was a pull from master branch from pydata/pandas and run `python setup.py build_ext --inplace` and then run the nosetests. But didn't work.

**Comment by jorisvandenbossche** [comment]
You will need to post some of the errors you see, otherwise difficult to say. BTW, for such questions, you can also use gitter: https://gitter.im/pydata/pandas

**Comment by jreback** [comment]
master seems borked on travis for some reason atm, but I can't repro locally.....but investigating...

**Comment by terrytangyuan** [comment]
Ok. Thanks guys. Yeah it seems to be a broke on master.
