### ISSUE TITLE
read_csv index callback functionality

### ISSUE THREAD

**Issue by willembressers** [pydata/pandas#11012]
I have 3 csv files, which could be linked together via different columns. I want to merge all the 3 csv files in 1 dataframe. 

```
import pandas as pd
a_df = pd.read_csv(a_file, sep=';', index_col=['booking_id'])
b_df = pd.read_csv(b_file, sep=';', index_col=['ga:adwordsCreativeID', 'ga:date', 'ga:transactionId'])
c_df = pd.read_csv(c_file, sep=';', index_col=['Advertentie-ID', 'Dag'])

df = b.merge(a,b, left_index=True, right_index=True)
```

But some of the columns need some altering before the linking can occur. 

Alterations:
* I need to get the first 7 characters of the `ga:transactionId` column so it's equal to `booking_id`.
* I need to parse the `ga:date` string to a timestamp (format = yyyymmdd) so i can use it with `ga:adwordsCreativeID` to form an unique key. 
* I need to parse the `Dag` string to a timestamp (format = dd-mm-yyyy) so i can use it with `Advertentie-ID` to form the same unique key.

I assume that somewhere in the read_csv code is iterated through the csv data and added to the dataframe. Why not invoke a function callback so that during import the alterations can be applied?

**Comment by jreback** [comment]
well, this would make an already very complicated parser even more complicated. and its in c so doing this would be difficult. 

is their a problem doing a sequence of actions to do this?

seems much more natural.

**Comment by willembressers** [comment]
thanks for your quick response, i was diving into documentation, but i guess `converters` would do the job. doesn't it ? see: http://pandas.pydata.org/pandas-docs/stable/io.html#io-read-csv-table

**Comment by jreback** [comment]
well, you are much better off doing something like:

```
df = read_csv(.....)
df['booking_id'] = df['....].str[0:7]
.....
whatever
```

you will find debugging viewing much more natural. aside from MUCH more efficient.
