### ISSUE TITLE
accept pathlib paths wherever a path/file is expected

### ISSUE THREAD

**Issue by flying-sheep** [pydata/pandas#11033]
i’d like `pd.read_table(some_path / 'filename.tsv')` to work without going through `str()`

**Comment by jreback** [comment]
sure, these just need stringifing. want to do a pull-request?

**Comment by flying-sheep** [comment]
gladly, but we need to define how first:

* stringify everything that isn’t file-like and try treating it as a path?

    (there might be a problem if some custom `__str__` function of an accidentally passed object happens to be a valid path)

* test for being a `Path` subclass?

    this might need backwards-sensible code like
    
    ```
    try:
        from pathlib import Path
    except:
        class Path: pass  # dummy for instance checks

    ...
    
    if isinstance(file_or_path, Path):
        file_or_path = str(file_or_path)

**Comment by jreback** [comment]
[here](https://github.com/pydata/pandas/blob/master/pandas/io/common.py#L127) is where all of this path inference is done (well not 100% sure of all but vast majority)

you can use several/both of those strategies (though keep in mind that other ``pathlib`` like libs exists, e.g. ``py.local.path`` is the big one).

so I think its probably safe to ``str(filepath_or_buffer)`` (if this is not a file-like) might just work, but some tests would be gr8.

**Comment by flying-sheep** [comment]
io has no tests. should i start a module?

**Comment by jreback** [comment]
all of the io tests are in their respective directory. however for this you can add in ``pandas/io/tests/test_common.py`` (ideally you can add for all of the major ones, e.g. ``excel,sql,hdf5,csv,json,stata``)

**Comment by flying-sheep** [comment]
the tests are a bit uninspired but yeah :smile:

**Comment by jreback** [comment]
closed by #11051

**Comment by jreback** [comment]
@flying-sheep this is failing on windows (3.5, though prob same on 2.7)

your test case should have a platform based separator, i think
``os.join(['foo','bar'])``

can you do a pull-request for this (and test on windows if you can, if not I can do it)

thanks

```
======================================================================
FAIL: test_stringify_path_pathlib (pandas.io.tests.test_common.TestCommonIOCapabilities)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\Jeff Reback\pandas3.5\pandas\io\tests\test_common.py", line 46, in test_stringify_path_pathlib
    self.assertEqual(redundant_path, 'foo/bar')
AssertionError: 'foo\\bar' != 'foo/bar'
- foo\bar
?    ^
+ foo/bar
?    ^


----------------------------------------------------------------------
Ran 8244 tests in 340.876s```

**Comment by flying-sheep** [comment]
PR is #11362
