### ISSUE TITLE
BUG: Invisible rounding error in the results of Dataframe.interpolate()

### ISSUE THREAD

**Issue by coillarach** [pydata/pandas#11035]
This issue arose when using the interpolate method to extend an existing dataframe using the procedure in the snippet. Most interpolated values seem to behave correctly, but occasionally there is some kind of rounding error which is not visible to ordinary inspection. Trying to access a row in the dataframe using one of the interpolated values as the key sometimes fails even though the value appears to be correct when the data is viewed. The snippet provides an example:

```python
import pandas as pd
import numpy as np

# Setup
df = pd.DataFrame({'values': [0,1,2,3,4,5]})
df2 = pd.DataFrame(index = np.linspace(0, 5, 501))
df3 = pd.concat([df, df2], axis=1)
df4 = df3.interpolate()

# The results of this statement appear correct
print df4.iloc[113:116]

# This statement works as intended: demonstrates correct syntax
print df4[df4.values == 1.13]

# This statement returns an empty dataframe despite everything else looking right
print df4[df4.values == 1.14]
```

The problem can be solved by replacing the interpolated column with one which has been rounded to the same level of precision. Viewing the data shows no change, but the previous errors disappear.

INSTALLED VERSIONS
commit: None
python: 2.7.6.final.0
python-bits: 64
OS: Windows
OS-release: 8
machine: AMD64
processor: Intel64 Family 6 Model 69 Stepping 1, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None

pandas: 0.15.2
nose: 1.3.4
Cython: None
numpy: 1.8.1
scipy: 0.14.1rc1
statsmodels: None
IPython: 2.3.1
sphinx: None
patsy: None
dateutil: 2.2
pytz: 2014.9
bottleneck: None
tables: None
numexpr: None
matplotlib: 1.4.2
openpyxl: None
xlrd: None
xlwt: 1.0.0
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
httplib2: None
apiclient: None
rpy2: None
sqlalchemy: None
pymysql: None
psycopg2: None

**Comment by jreback** [comment]
directly indexing on floats is a very odd, unreliable thing to do.

in 0.17.0 (releasing shortly), you may have better experience doing this:

```
In [31]: df4.reindex([1.13,1.14,1.15],tolerance=0.005,method='nearest')
Out[31]: 
      values
1.13    1.13
1.14    1.14
1.15    1.15
```

more typically you would do this
```
In [36]: df4[(df4.index>=1.13)&(df4.index<=1.15)]
Out[36]: 
      values
1.13    1.13
1.14    1.14
```

**Comment by jreback** [comment]
see [here](http://pandas-docs.github.io/pandas-docs-travis/whatsnew.html#other-enhancements) down a bit

**Comment by coillarach** [comment]
Thanks Jeff

That’s the fastest support response I think I’ve ever seen…

I understand about indexing on floats – that is just to make the concat step work. In my actual code I later replace the index with ints anyway.

The problem is that I want to be able to look up a value in one column using the value in an interpolated column (not the index).

Brian

**Comment by jreback** [comment]
if you need *exact* numbers, then you should make these integers (e.g. multiply by factor, then round, and cast to an int). otherwise you will have issues.

maybe a small example if what you are ultiemately doing would help.

**Comment by coillarach** [comment]
Hi Jeff

I’ll use that approach – no need for an example.

Thanks for the advice
Brian
