### ISSUE TITLE
gc.collect(2) call shouldn't be forced by pandas

### ISSUE THREAD

**Issue by sylvinus** [pydata/pandas#11045]
We have lots of objects allocated in memory and the explicit call to `gc.collect(2)` in `generic.py` is killing our app's performance (taking ~0.5s *each time*!)
https://github.com/pydata/pandas/blob/master/pandas/core/generic.py#L1278

Ideally pandas shouldn't call the garbage collector manually, or at the very list there should be a way to disable this call.

Thanks!

**Comment by shoyer** [comment]
Ouch!

I believe you can avoid these checks by setting the `mode.chained_assignment` option:
```python
pd.set_option('mode.chained_assignment', None)
```

**Comment by sylvinus** [comment]
Thanks @shoyer! I can confirm this option avoids the calls.

**Comment by jreback** [comment]
note that setting single items repeatedly is probably not the performs my way to go

further if you simply copy the original object that is sliced this won't even be checked
