### ISSUE TITLE
DOC: consider updating visualization.rst to use plot submethods rather than kind

### ISSUE THREAD

**Issue by shoyer** [pydata/pandas#11043]
Another followup to #9321:

Most of the documentation examples in visualization.rst (the [main plotting docs](http://pandas.pydata.org/pandas-docs/stable/visualization.html)) currently use the `kind` argument. We should probably switch these to use the plotting submethods instead, to push users in that direction.

**Comment by MattRijk** [comment]
Question. I'm using analytics.quant-platform. Plotting submethod does not give me a graph just object. Kind argument works. I'm I leaving something out?

In [38]:
import pandas as pd
import numpy as np
%matplotlib inline

df = pd.DataFrame(np.random.rand(10, 2), columns=['a', 'b']).plot(kind='barh')


data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAW0AAAD7CAYAAAChScXIAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAEWFJREFUeJzt3XvQXHV9x/H3FwJIsOFiKBQIjYV6IaUYKkgUbWgtxQuYoZ0pitZKQaeVSx1skYKTZSiKdizqiMwUqjWO4kxxpGpBlMsqVC5FEyBcrNByDVRMNMhthsu3f+xCnjy3Pftkz579Pc/7NfPM7OU853yyu883Z3/nd843MhNJUhm2ajqAJKk6i7YkFcSiLUkFsWhLUkEs2pJUEIu2JBVk3pauICKcMyhJM5CZ0e/vDGRPOzNH7mflypWNZzCTmeZiLjNV+5kph0ckqSAWbUkqyKwt2suXL286wgRmqsZM1Y1iLjPVK7ZkbAX6OxC5pduSpNkiIsgZHIjsOXskIk4BjgcCuDAzPzNhoVaFLVVZRpLGiOi7po2kQe6wTlu0I+J36BTsg4BngO9ExLcz856BJZCkaZT+DX3Q//H0GtN+FXBjZj6dmc8B3weOHmgCSVJlvYr2WuCNEbFLRMwH3gbsVX8sSdJkph0eycy7IuITwHeBJ4DVwPPDCCZJmqjngcjM/ALwBYCI+Bhw/4SFWtU2NlsOKki9lD4Oq8Frt9u02+0tXk/PKX8R8euZ+bOI2Bu4AnhdZj425vkEP6DSJmHRHpDutLgJj9VtkO/fZP+GMY8PfsofcElEvIzO7JG/HluwJakZdf6nONojAj3PiMzMN2Xmksx8TWZeM4xQklSCc889l3333ZcFCxawZMkSLr300tq3OWtPY5ekuu27775cd911PPbYY6xcuZJ3v/vdPPLII7Vuc6insUtzhWPagzH1mHa9wyMzff+WLl3KWWedxVFHHbVpbQ2MaffkB1TSXLRq1SrOO+887r33XgAef/xx1q9fX+s2B1K0JWmuue+++3j/+9/P1VdfzbJly4gIli5dWvtOrEVbkmbgiSeeICJYuHAhzz//PKtWrWLt2rW1b9cDkZIKFDX+VLPffvtx6qmnsmzZMnbffXfWrl3LoYceOpB/3XQGciDSMW1JdZjqIF5JBn0g0j1tSSqIRVuSCmLRlqSCWLQlqSAWbUkqyEDmaXudbElVlT4bpGmDObmmNZC1SJrtWk0HKF/P4ZGIOD0ibo+I2yLiqxGx3TCCSZImmrZoR8Ri4ATgwMzcH9gaOKb+WJI02hYvXsxVV1019O32Gh55jE7HmvkR8RwwH3io9lSSNIVRaTcWEY0cz+vVjX1DRHyKTjPfp4ArMvPKoSSTpKm0Cl33AExbtCNiH+BvgMXARuDfIuLYzPzKZgu2akonSSPspptu4qSTTuLhhx9mxYoVXHDBBWy33eSH/YbSjT0i/gz4o8w8vnv/PcAhmfnBMcvYjV0VlX/xHw3XlJ1rWjVutFVteGTx4sUsWLCAyy+/nPnz53PkkUdy2GGHcfbZZ2+23LAvGHUXcEhEbB+dwZs3A3f0uxFJmm0ighNPPJE999yTnXfemTPOOIOLL7649u1OW7Qz8xZgFXAzcGv34X+uO5QklWDRokUv3t57771Zt25d7dvseXJNZn4S+GTtSSSpMPfff/9mt/fYY4/at+m1RyRpBjKT888/n4ceeogNGzZwzjnncMwx9Z/GMqAekV57RNIQtZoO0BnTPvbYYzn88MNZt24dK1as4Mwzz6x/u7YbkzSqbDc2kcMjklQQi7YkFcSiLUkFsWhLUkEs2pJUEIu2JBVkQPO0Jake9qDdnEVb0sgqfY52HRwekaSCDGRP268v0ibuHapOPYt2RLwS+NqYh34L+GhmfvbFR1oDzyWVqdV0AM12VS7N+hNgKUBEbEWnse83as4lSZpEv2PabwbuycwH6ggjSZpev0X7GOCrdQSRJPVW+UBkRGwLHAmcNuHJ1uACSdJsNJRu7JstGPEO4K8y84hxj9uNXSOg/Osua24ZxvW03wnU32pYkjSlSnvaEbEDcB/w8sz81bjn3NPWCHBPW2WZ6Z72QNqNWbTVPIu2ymK7MUmaA+zGLkkFGUjR9mupJA2HwyOSVBCLtiQVxKItSQWxaEtSQSzaklQQi7YkFcSiLUkFsWhLUkEs2pJUkEa7sXsmpST1p0o39p2Ai4AldC7nd1xm3rDZQq0ZbHkmvyNJc1yVPe3PAJdl5p9GxDxgh5ozSZKmMG3RjogdgTdm5nsBMvNZYOMwgkmSJup1IPLlwKMR8cWI+HFEXBgR84cRTJI0Ua+iPQ84EPh8Zh4IPAF8pPZUkqRJ9RrTfhB4MDP/q3v/EiYr2q2ZbbzqrBNnmUgqXbvdpt1ub/F6evaIjIgfAMdn5n9HRAvYPjNPG/N8zT0i7f0nafaprbFvRBxAZ8rftsA9wPsyc+OY5y3aktSnWdyN3aItafaxG7skzQF2Y5ekgtiNXZIK4vCIJBXEoi1JBbFoS1JBLNqSVBCLtiQVxKItSQWxaEtSQSzaklQQi7YkFaTRbuxS0zybV6UZzLVHWgNZizRcraYDSP2rVLQj4l7gMeA54JnMPLjOUJKkyVXd005geWZuqDOMJGl6/RyIdOBakhpWtWgncGVE3BwRJ9QZSJI0tarDI2/IzIcjYlfgexFxV2Ze++KzrTqiSfUb9swnZ6vMXUPrxj7hFyJWAo9n5qe692vuESnNFvY71Sa19YiMiPkR8Wvd2zsAhwO39R9RkrSlqgyP7AZ8o/s1ch7wlcz8bq2pJEmT6nt4ZMIKHB6RKnJ4RJvUNjwiSRodgzmN3SnckjQUAynafuWTpOFweESSCmLRlqSCWLQlqSAWbUkqiEVbkgpi0Zakgli0JakgFm1JKohFW5IKMpAzIod9IXltGc9glcpVtRv71sDNwIOZeeSEBVqDDaUatZoOIGlLVB0eOQW4A6/BKkmNqtK5Zi/grcBFeDk/SWpUlT3t84C/BZ6vOYskqYdpx7Qj4u3AzzJzdUQsn3LB1mBDqV4eOC6LB45nh6F0Y4+IjwHvAZ4FXgIsAL6emX8+ZhnbjUm1sUXZbDXTdmOVe0RGxO8DHx4/e8SiLdXJoj1bDatHpJ8eSWqQ3dilkeae9mxlN3ZJmgPsxi5JBbEbuyQVxOERSSqIRVuSCmLRlqSCWLQlqSAWbUkqiEVbkgpi0Zakgli0JakgFm1JKojd2CX1zbOgm9OzaEfES4DvA9sB2wL/npmnb7ZQq45okkZSq+kAc1vPop2ZT0fEYZn5ZETMA66LiEMz87oh5JMkjVFpTDszn+ze3BbYGthQWyJJ0pQqFe2I2Coi1gD/B1yTmXfUG0uSNJmqe9rPZ+ZrgL2AN03bmV2SVJu+Zo9k5saI+A/gtUD7xSdaA80kacQ5Y2yTqjNp2u027XZ7i7fXs0dkRCwEns3MX0bE9sAVwFmZeVX3eXtESpqjZt7Dc6Y9Iqvsaf8G8KWI2IrOcMqXXyjYkqThshu7JM3Y8Pe0PY1dkgpiN3ZJKojd2CWpIA6PSFJBLNqSVBCLtiQVxKItSQWxaEtSQSzaklQQi7YkFcSiLUkFsWhLUkHsxq7ieAau5rLBXHukNZC1SL21mg4gNavn8EhELIqIayLi9ohYGxEnDyOYJGmiKnvazwAfysw1EfFS4EcR8b3MvLPmbJKkcXruaWfmI5m5pnv7ceBOYI+6g0mSJupr9khELAaWAjfWEUaSNL3KByK7QyOXAKd097g3aQ02lCTNNkPrxg4QEdsA3wYuz8xPj3tumh6RM++fJkmz2Ux7RPYs2tGZhP0lYH1mfmiS5y3aktSnOov2ocAPgFvZVJ1Pz8zvdJ+3aEtSn2or2hU2bNGWpD7NtGh77RFJKshgTmPHa49I0jAMpGg7BCJJw+HwiCQVxKItSQWxaEtSQSzaklQQi7YkFcSiLUkFsWhLUkEs2pJUEIu2JBVkIGdEdq7eKkmjZTaerd2zaEfEF4C3AT/LzP0nXag12FCStMVaTQeoR5XhkS8CR9QdRJLUW5Vu7NcCvxhCFklSDx6IlKSCDOZ62q2BrEWSZq1hd2NfDHxrsgOR07cbU3lsEScNg+3GJGkO6Fm0I+Ji4IfAKyLigYh4X/2xJEmTqbkbu8rj8Ig0DA6PSNIcYDd2SSqI3dglqSAOj0hSQSzaklQQi7YkFcSiLUkFsWhLUkEs2pJUEIu2JBXEoi1JBbFoS1JB7MYuzYBnAaspVbqxHwF8GtgauCgzPzFhodbAc0mjq9V0AM1l0w6PRMTWwOfodGPfD3hnRLx6GMEkSRP1GtM+GLg7M+/NzGeArwHvqD+WJGkyvYr2nsADY+4/2H1MktSAXkXboy2SNEJ6HYh8CFg05v4iOnvbm2sNLpBUAmdMNaPkWTvtdpt2u73F65m2R2REzAN+AvwhsA64CXhnZt45Zhl7REoagtnVv3SmPSKn3dPOzGcj4kTgCjpT/v5lbMGWJA2X3dglFcI9bfA0dkkqit3YJakgdmOXpILM2uGRQUytGTQzVWOm6kYxl5nqZdEeIjNVY6bqRjGXmeo1a4u2JM1GFm1JKsiA5mlLkvo1k3naW1y0JUnD4/CIJBXEoi1JBalctCPiiIi4KyJ+GhGnTbHMZ7vP3xIRSwcXc2aZIuJVEXF9RDwdEafWnaePXMd2X6NbI+I/I+J3RyDTO7qZVkfEjyLiD5rONGa5gyLi2Yg4uulMEbE8IjZ2X6fVEXFm05nG5FodEWsjol13piq5IuLDY16n27rv4U4NZ1oYEd+JiDXd1+ov6sxTMdPOEfGN7t/fjRGxZNoVZmbPHzpX+LsbWAxsA6wBXj1umbcCl3Vvvw64ocq6Z/pTMdOuwGuBfwBOrTNPn7mWATt2bx8xIq/VDmNu70+nzVyjmcYsdzXwbeBPms4ELAe+OYzPUh+ZdgJuB/bq3l84CrnGLf924MqmM9G5+v/HX3idgPXAvIYz/SPw0e7tV/Z6naruaVfpFXkU8CWAzLwR2Ckidqu4/pnomSkzH83Mm4Fnaswxk1zXZ+bG7t0bgb1GINMTY+6+FPh505m6TgIuAR6tOU8/mYZ5sZ0qmd4FfD0zHwTIzLrfu6q5xme8eAQyPQws6N5eAKzPzGcbzvRq4BqAzPwJsDgidp1qhVWLdpVekZMtU2cxGtX+lf3m+kvgsloTVcwUESsi4k7gcuDkpjNFxJ50PuAXdB+qe6pTldcpgdd3v8peFhH7jUCm3wZ2iYhrIuLmiHhPzZmq5gIgIuYDfwx8fQQyXQgsiYh1wC3AKSOQ6RbgaICIOBj4TaapnVUvGFX1j2X8Hkidf2SjOlexcq6IOAw4DnhDfXGAipky81Lg0oh4I/BlOl/Vmsz0aeAjmZnR6e9V9x5ulUw/BhZl5pMR8RbgUuAVDWfaBjiQToep+cD1EXFDZv604VwvOBK4LjN/WVeYriqZ/h5Yk5nLI2If4HsRcUBm/qrBTOcCn4mI1cBtwGrguakWrlq0q/SKHL/MXt3H6lKtf+XwVcrVPfh4IXBEZv5iFDK9IDOvjYh5EfGyzFzfYKbfA77W7ce4EHhLRDyTmd9sKtPYP+7MvDwiPh8Ru2TmhqYy0dmT+3lmPgU8FRE/AA4A6iza/XymjqH+oRGolun1wDkAmXlPRPwvnZ2Tm5vK1P1MHffC/W6m/5lyjRUH0+cB99AZTN+W3gciD6H+g2s9M407+DCsA5FVXqu96RycOGSEMu3DppOtDgTuaTrTuOW/CBzddCZgtzGv08HAvSOQ6VXAlXQOes2ns7e2X9O5usvtSOdg3/Z15unjtfonYOWY9/JBYJeGM+0IbNu9fQLwr9Ous4+Nv4VOk9+7gdO7j30A+MCYZT7Xff4W4MAhvEnTZgJ2p7MXshH4BXA/8NIRyHVR94O8uvtz0whk+jtgbTfPtcBBTWcat2ztRbvi6/TB7uu0BvghQ/iPt+Lf3ofpzCC5DTi57kx95Hov8NVh5Kn4/i0EvtWtUbcB7xqBTMu6z99F56D7jtOtz9PYJakgnhEpSQWxaEtSQSzaklQQi7YkFcSiLUkFsWhLUkEs2pJUEIu2JBXk/wEkykuCuvBFQgAAAABJRU5ErkJggg==

In [41]:
import pandas as pd
import numpy as np
%matplotlib inline

df = pd.DataFrame(np.random.rand(10, 2), columns=['a', 'b'])

df.plot.bar


Out[38]:
<bound method FramePlotMethods.bar of <pandas.tools.plotting.FramePlotMethods object at 0x7f04b10fa908>>

**Comment by shoyer** [comment]
@MattRijk you need to call the method `df.plot.bar()`, not `df.plot.bar`

**Comment by MattRijk** [comment]
Alright. Works. That's weird i used .bar() a few times and nothing. Thanks
