### ISSUE TITLE
Broken nunique on Series group by

### ISSUE THREAD

**Issue by cpcloud** [pydata/pandas#11077]
The following code works in 0.16.2 and not in latest master:

```python
data = pd.DataFrame(
    [[100, 1, 'Alice'],
     [200, 2, 'Bob'],
     [300, 3, 'Charlie'],
     [-400, 4, 'Dan'],
     [500, 5, 'Edith']],
    columns=['amount', 'id', 'name']
)

expected = data.groupby(['id', 'amount'])['name'].nunique()
```

Going to bisect this today unless someone beats me to it.

**Comment by jreback** [comment]
https://github.com/pydata/pandas/pull/10894

**Comment by cpcloud** [comment]
Can we just revert that change and keep the test?

**Comment by cpcloud** [comment]
The only other solution I see is to coerce `val` to `str` if it's an object dtype

**Comment by jreback** [comment]
if its not ``int64`` factorize it
```
ipdb> p np.lexsort((pd.factorize(val)[0],ids))
array([0, 1, 2, 3, 4])
```

**Comment by cpcloud** [comment]
ok

**Comment by jreback** [comment]
or rather it has a ``TypeError``, though this shouldn't have gotten this far if that was the case....

**Comment by cpcloud** [comment]
Using `factorize` won't give the same results and is therefore incorrect:

```python
In [8]: np.lexsort(([1, 2, 3], list('cba')))
Out[8]: array([2, 1, 0])

In [9]: np.lexsort(([1, 2, 3], pd.factorize(list('cba'))[0]))
Out[9]: array([0, 1, 2])
```

**Comment by jreback** [comment]
might be faster to just ``.astype(str)`` an object array

use ``is_object_dtype``

**Comment by cpcloud** [comment]
yep

**Comment by behzadnouri** [comment]
> Using factorize won't give the same results and is therefore incorrect:

factorize _does_ work there. if you do not understand the algo, it would be better to ping whoever wrote the code rather than suggesting to revert it

**Comment by cpcloud** [comment]
@behzadnouri This is unrelated to my understanding of the algorithm. My suggestion to revert it was based on the fact that it broke existing code.

**Comment by behzadnouri** [comment]
> My suggestion to revert it was based on the fact that it broke existing code.

existing code is not forced to update to master

**Comment by jreback** [comment]
@behzadnouri no this DID break things. We just weren't fully testing it.

**Comment by cpcloud** [comment]
> existing code is not forced to update to master

That's certainly true. However this broke existing *pandas* code.
