### ISSUE TITLE
Union of index with itself not invariant, sets frequency attribute

### ISSUE THREAD

**Issue by compandu** [pydata/pandas#11086]
When creating the union of an index with itself, the frequency may end up being reset. I would have expected the call to union in the following example to be invariant and return the original index:
```
In [56]: index = pd.bdate_range('20150101', periods=10)
In [57]: index.freq = None
In [58]: index
Out[58]:
<class 'pandas.tseries.index.DatetimeIndex'>
[2015-01-01, ..., 2015-01-14]
Length: 10, Freq: None, Timezone: None

In [59]: index.union(index)
Out[59]:
<class 'pandas.tseries.index.DatetimeIndex'>
[2015-01-01, ..., 2015-01-14]
Length: 10, Freq: B, Timezone: None
```
This then propagates through to e.g. `combine_first`, which is also not invariant. This might be desirable behavior in some cases but definitely surprising imo.

**Comment by jreback** [comment]
so the case is an index that has ``idx.freq is None`` with another will NOT take the fast path, but then both compare equal. ok so far.

Then an infererence happens [here](https://github.com/pydata/pandas/blob/master/pandas/tseries/index.py#L899)

I suppose if both have incoming ``freq is None`` then don't need to infer.

Not sure what this would break though.

want to do a PR and see?
