### ISSUE TITLE
Unit tests in test_ga are being skipped

### ISSUE THREAD

**Issue by parthea** [pydata/pandas#11090]
While working on another issue, I noticed the following error in the build test log on travis.
```
-------------------------------------------------------------
#15 nose.failure.Failure.runTest: need httplib2 and auth libs
-------------------------------------------------------------
```
I'm not familar with the ga module, but 'll try to fix it

**Comment by jreback** [comment]
yeh, GA have not gotten much TLC (mainly for lack of testing). Though to be honest, this is something I think that we should remove from pandas. It can be an associated module, e.g .``pandas-ga`` or something. Interested?

**Comment by parthea** [comment]
I was only planning on fixing the ga unit test in the short term because I think it is similar to the other import issue I worked on. My current focus is to contribute to the pandas BigQuery module. 

I don't have much experience with GoogleAnalytics. It may be better to create a new issue for migrating GA to an associated module.

**Comment by jreback** [comment]
@parthea ok thanks then. tests would be good.
