### ISSUE TITLE
COMPAT: return instead of raising StopIteration in generator

### ISSUE THREAD

**Issue by kawochen** [pydata/pandas#11108]
And a couple other changes for [PEP479](https://www.python.org/dev/peps/pep-0479/) to avoid warnings. Will submit a PR if others agree.

**Comment by jreback** [comment]
sure

**Comment by jreback** [comment]
@kawochen pr for this?

**Comment by kawochen** [comment]
Ah yes will do tomorrow.

**Comment by kawochen** [comment]
Working on it.  I can trigger the warnings in 'SparseArray'.  Will see how to trigger those in 'io'.
