### ISSUE TITLE
Pandas options data not working (Data Reader)

### ISSUE THREAD

**Issue by MathTinker** [pydata/pandas#11109]
I am trying to use get_all_data() method to download options data. I am getting following error:
RemoteDataError: Parsed URL 'http://finance.yahoo.com/q/op?s=SPY' has no rootelement
Actual code:
from pandas.io.data import Options
SPYD = Options('spy', 'yahoo')
data = SPYD.get_all_data()

My pandas version is 0.16.2

NOTE: I am raising this issue again, as it was closed without showing the fix/solution

**Comment by jreback** [comment]
pls open an issue here: https://github.com/pydata/pandas-datareader/issues
