### ISSUE TITLE
read_clipboard() Windows to Linux

### ISSUE THREAD

**Issue by joshualeond** [pydata/pandas#11117]
I have an IPython (Jupyter) Notebook running on a webserver (Ubuntu) and am trying to read_clipboard() from a Windows computer. I have xclip installed on the ubuntu machine.  Here is the code: 

    import pandas as pd 
    from pandas import Series,DataFrame 
    test = pd.read_clipboard()
    print test

It appears that the clipboard is empty and Pandas is trying to parse the empty clipboard. The error I receive is the following:

    ValueError 
    Traceback (most recent call last)
    <ipython-input-3-4f7527f57c80> in <module>()
          2 import pandas as pd
          3 from pandas import Series,DataFrame
    ----> 4 test = pd.read_clipboard()
          5 print test

    /usr/local/lib/python2.7/dist-packages/pandas/io/clipboard.pyc in read_clipboard(**kwargs)
         49         kwargs['sep'] = '\s+'
         50 
    ---> 51     return read_table(StringIO(text), **kwargs)
         52 
         53 

    /usr/local/lib/python2.7/dist-packages/pandas/io/parsers.pyc in parser_f(filepath_or_buffer, sep, dialect, compression, doublequote, escapechar, quotechar, quoting, skipinitialspace, lineterminator, header, index_col, names, prefix, skiprows, skipfooter, skip_footer, na_values, na_fvalues, true_values, false_values, delimiter, converters, dtype, usecols, engine, delim_whitespace, as_recarray, na_filter, compact_ints, use_unsigned, low_memory, buffer_lines, warn_bad_lines, error_bad_lines, keep_default_na, thousands, comment, decimal, parse_dates, keep_date_col, dayfirst, date_parser, memory_map, float_precision, nrows, iterator, chunksize, verbose, encoding, squeeze, mangle_dupe_cols, tupleize_cols, infer_datetime_format, skip_blank_lines)
        472                     skip_blank_lines=skip_blank_lines)
        473 
    --> 474         return _read(filepath_or_buffer, kwds)
        475 
        476     parser_f.__name__ = name

    /usr/local/lib/python2.7/dist-packages/pandas/io/parsers.pyc in _read(filepath_or_buffer, kwds)
        248 
        249     # Create the parser.
    --> 250     parser = TextFileReader(filepath_or_buffer, **kwds)
        251 
        252     if (nrows is not None) and (chunksize is not None):

    /usr/local/lib/python2.7/dist-packages/pandas/io/parsers.pyc in __init__(self, f, engine, **kwds)
        564             self.options['has_index_names'] = kwds['has_index_names']
        565 
    --> 566         self._make_engine(self.engine)
        567 
        568     def _get_options_with_defaults(self, engine):

    /usr/local/lib/python2.7/dist-packages/pandas/io/parsers.pyc in _make_engine(self, engine)
        703     def _make_engine(self, engine='c'):
        704         if engine == 'c':
    --> 705             self._engine = CParserWrapper(self.f, **self.options)
        706         else:
        707             if engine == 'python':

    /usr/local/lib/python2.7/dist-packages/pandas/io/parsers.pyc in __init__(self, src, **kwds)
       1070         kwds['allow_leading_cols'] = self.index_col is not False
       1071 
    -> 1072         self._reader = _parser.TextReader(src, **kwds)
       1073 
       1074         # XXX

    pandas/parser.pyx in pandas.parser.TextReader.__cinit__ (pandas/parser.c:4814)()

    **ValueError: No columns to parse from file**

I've tried using xsel with no luck so I don't think that's the issue.  I tried to use read_clipboard on the try.jupyter.com site as well and it shutdown the kernel.  Any clarity on this subject would be nice.  Below is the full version string of Pandas and dependencies:
    
    INSTALLED VERSIONS
    ------------------
    commit: None
    python: 2.7.6.final.0
    python-bits: 64
    OS: Linux
    OS-release: 3.13.0-48-generic 
    machine: x86_64
    processor: x86_64
    byteorder: little
    LC_ALL: None
    LANG: None

    pandas: 0.16.2
    nose: 1.3.1
    Cython: None
    numpy: 1.9.2
    scipy: 0.13.3
    statsmodels: 0.5.0
    IPython: 4.0.0
    sphinx: None
    patsy: 0.2.1
    dateutil: 2.4.2
    pytz: 2015.4
    bottleneck: None
    tables: 3.1.1
    numexpr: 2.2.2
    matplotlib: 1.3.1
    openpyxl: 1.7.0
    xlrd: 0.9.2
    xlwt: 0.7.5
    xlsxwriter: None
    lxml: None
    bs4: 4.2.1
    html5lib: 0.999
    httplib2: None
    apiclient: None
    sqlalchemy: None
    pymysql: None
    psycopg2: None

**Comment by jreback** [comment]
try pasting to say excel, if you then show data then ``pd.read_clipboard()`` should work

**Comment by joshualeond** [comment]
There probably isn't a problem with pd.read_clipboard().  I think it has to deal with me attempting to read_clipboard over https.  I can do a read_clipboard() and it functions correctly when I'm using an SSH with X11 Forwarding enabled.  So I think the real problem is X11 Forwarding over https, which I don't know if it's possible. Thanks.

**Comment by jreback** [comment]
hmm on putty (which u r prob using on windows)
this should be the default iirc

though I have found this unreliable

I usually need to copy to something on the windows side, reselect and then do the read_clipboard

but ymmv

**Comment by joshualeond** [comment]
I did use putty with X11 forwarding enabled to test, for me it wasn't default.  My webserver is an amazon EC2 instance and I'm just not sure you can read_clipboard() from my local windows computer to an offsite server.  I'm still looking for a way though because it would be great to use.

**Comment by jreback** [comment]
closing as not a pandas issue
