### ISSUE TITLE
Possible bug!! Replacing str in dataframe delete entire number

### ISSUE THREAD

**Issue by SlyOne** [pydata/pandas#11118]
```
df.head()
	OSymbol
0	.GGP:150918:C:18.0
1	.GGP:150918:C:19.0
2	.GGP:150918:C:20.0
3	.GGP:150918:C:21.0
4	.GGP:150918:C:22.0

df['OSymbol'].str.replace(".0", "")

0           .GGP:1918:C:18
1           .GGP:1918:C:19
2             .GGP:1918:C:
3           .GGP:1918:C:21
4           .GGP:1918:C:22
```
Look at 20 strike... should be 20.0 > 20 , instead all of 20.0 is removed...

Pandas version 0.16.2

**Comment by maximilianr** [comment]
You need to provide the code to replicate the issue

**Comment by SlyOne** [comment]
The code is there.. here the html table...

u'<table border="1" class="dataframe">\n  <thead>\n    <tr style="text-align: right;">\n      <th></th>\n      <th>OSymbol</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>.GGP:150918:C:18.0</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>.GGP:150918:C:19.0</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>.GGP:150918:C:20.0</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>.GGP:150918:C:21.0</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>.GGP:150918:C:22.0</td>\n    </tr>\n  </tbody>\n</table>'

**Comment by jorisvandenbossche** [comment]
@SlyOne That is because the string you provide `.0` is interpreted as a regex pattern (so everything character followed by a 0 is replaced).

Try escaping the `.`:

```
In [10]: df[0].str.replace('\.0', '')
Out[10]:
0    .GGP:150918:C:18
1    .GGP:150918:C:19
2    .GGP:150918:C:20
3    .GGP:150918:C:21
4    .GGP:150918:C:22
Name: 0, dtype: object
```

**Comment by SlyOne** [comment]
who knew? !
