### ISSUE TITLE
PERF: infer_datetime_format fails without zero-padding

### ISSUE THREAD

**Issue by chris-b1** [pydata/pandas#11142]
I think this can be fixed by just padding tokens in the inference step.  The dates *do* parse, just always fall back to the slow path, even with `infer_datetime_format=True`

    In [22]: from pandas.tseries.tools import _guess_datetime_format

    In [23]: _guess_datetime_format('02/02/2014')
    Out[23]: '%m/%d/%Y'

    In [24]: _guess_datetime_format('2/2/2014')

**Comment by jreback** [comment]
I think you can add additional formats here.
