### ISSUE TITLE
.ix/.loc methods are *significantly* slower when upgrading pandas from 0.13 to 0.16.2

### ISSUE THREAD

**Issue by vgoklani** [pydata/pandas#11151]
We ran a profiler comparing both the .ix and .loc methods for pandas, in both versions, and got substantially slower results when using 0.16.2. Why is that?

**Comment by TomAugspurger** [comment]
Do you have a small reproducible example that shows the slowdown?

**Comment by jreback** [comment]
see a discussion https://github.com/pydata/pandas/issues/7493

**Comment by jreback** [comment]
well, if you have an example post it.
