### ISSUE TITLE
Add Python 3.5 OSX wheel to pypi?

### ISSUE THREAD

**Issue by matthew-brett** [pydata/pandas#11160]
I just built a Python 3.5 wheel for Pandas 0.16.2 using the good ol'  MacPython travis setup:

https://travis-ci.org/MacPython/pandas-wheels/builds/81332167

The Python 3.5 wheel is at the usual http://wheels.scipy.org location:

http://wheels.scipy.org/pandas-0.16.2-cp35-cp35m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl

Would someone mind uploading this to pypi?    I'm happy to do that if someone gives me permission (`matthew.brett` on pypi).

**Comment by jreback** [comment]
3.5 is somewhat broken in 0.16.2
it almost all works but some smaller things
this is already fixed in 0.17.0 so not going to update for the older version
