### ISSUE TITLE
DataFrame.unstack() issues DeprecationWarning with MultiIndex

### ISSUE THREAD

**Issue by xflr6** [pydata/pandas#11162]
```python
>>> import warnings
>>> warnings.simplefilter('error')

>>> import pandas as pd
>>> pd.__version__
u'0.17.0rc1'

>>> df = pd.DataFrame({'A': list('aabb'), 'B': [0, 1, 0, 1], 'C': range(4)})
>>> gf = df.groupby(['A', 'B']).sum()
>>> gf
     C
A B   
a 0  0
  1  1
b 0  2
  1  3

>>> gf.unstack()
Traceback (most recent call last):
..., line 4274, in _reference_duplicate_name
    return np.sum(name == np.asarray(self.names)) > 1
DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
```

**Comment by jreback** [comment]
what version numpy?

there are 'lots' of these. We do have to fix this at some point. But its not a big deal.

**Comment by jreback** [comment]
this is covered in #8537 

pull-requests always welcome!

**Comment by xflr6** [comment]
Yes, sorry, I just realized this seems to be due to [this](https://github.com/numpy/numpy/blob/master/doc/release/1.10.0-notes.rst#array-comparisons-involving-strings-or-structured-dtypes) in the `numpy 1.10.0b1` I am using here.

The line in the traceback seems to involve a comparison like: `-1 == np.asarray(['A', 'B'])`

**Comment by jreback** [comment]
We actually test with this: https://travis-ci.org/pydata/pandas/jobs/81396483
numpy master with DeprecationWarnings turned on. I try to get rid of them; I think I got most but their are some (also the 3.4 build has some as well).

so eventually have to fix!

**Comment by rosnfeld** [comment]
Yup, I just hit this one today too when I did a fresh pull of the latest pandas and numpy.
Another repro case:
```python
pd.DataFrame([[1, 2], [3, 4]], columns=['a', 'b']).groupby('a').b.value_counts().unstack()
```

**Comment by jreback** [comment]
yeh this is a numpy warning - never got around to tracking this one down

you are welcome to it!

**Comment by xflr6** [comment]
Maybe this should be re-opened (does #8537 mention mixed-type comparisons?).

I hope, we already tracked it: Wouldn't it be enough to replace [this](http://github.com/pydata/pandas/blob/a89b96d441b3c025021fe3d080494619c0e1c594/pandas/core/index.py#L4279)
```python
return np.sum(name == np.asarray(self.names)) > 1
```
with this?
```python
return sum(name == n for n in self.names) > 1
```
