### ISSUE TITLE
Test failure due to Timestamp not being imported on master

### ISSUE THREAD

**Issue by bashtage** [pydata/pandas#11170]
I am seeing test failures (both local and Travis) due to 

https://github.com/pydata/pandas/blob/master/pandas/tests/test_internals.py#L667

which uses `Timestamp`, not `pd.Timestamp`.  Is this expected?

**Comment by kawochen** [comment]
It's imported here, so it probably shouldn't error, but I think making it more explicit is better. 
https://github.com/pydata/pandas/blob/master/pandas/tests/test_internals.py#L13

**Comment by bashtage** [comment]
Thanks - I had somehow dropped that line, and it was pretty difficult to find since it is only indirectly imported (since `internals` imports `Timestamp`)

**Comment by jreback** [comment]
yeh, let's fixed that ``*`` import.
