### ISSUE TITLE
CI: update builds to include matplotlib v1.5.0 when available

### ISSUE THREAD

**Issue by jreback** [pydata/pandas#11186]
xref #11145 

- [ ] change ci/requirements
- [ ] remove checks for '0+unknown' in version checks (bug already fixed in matplotlib)

**Comment by TomAugspurger** [comment]
I added a task for cleaning up the version checks that I had to workaround for the RC. I'll be adding a few more todo items.

**Comment by jreback** [comment]
just annnonced by @tcaswell ! 
http://matplotlib.org/devdocs/users/whats_new.html#new-in-matplotlib-1-5

**Comment by jreback** [comment]
this is ok now

**Comment by jreback** [comment]
@TomAugspurger unless you think anything is still open on this (FYI mpl 1.5 has been running on the 3.5 build since wednesday)
