### ISSUE TITLE
[Request] pd.rolling_apply - apply a given function to a rolling window of data

### ISSUE THREAD

**Issue by logannc** [pydata/pandas#11190]
I might make a pull request sometime next week with an implementation - it shouldn't be too difficult.

**Comment by logannc** [comment]
For reference, my personal reason to want this is that I wanted a rolling_geometric_mean and there doesn't seem to be an easy way to do this currently.

**Comment by jreback** [comment]
and how is this different from ``pd.rolling_apply``?

**Comment by jreback** [comment]
http://pandas.pydata.org/pandas-docs/stable/generated/pandas.rolling_apply.html?highlight=rolling_apply#pandas.rolling_apply

**Comment by logannc** [comment]
Apparently my ability to find it in the docs... somehow. Never mind....
