### ISSUE TITLE
BUG: pd.frequency.get_offset cache may be overwritten

### ISSUE THREAD

**Issue by sinhrks** [pydata/pandas#11192]
Because ``frequencies.get_offset`` may be broken by user operation because of its cache.

https://github.com/pydata/pandas/blob/master/pandas/tseries/frequencies.py#L515

```
import pandas as pd
x = pd.tseries.frequencies.get_offset('D')
x.__dict__
# {'normalize': False, 'kwds': {}, 'n': 1, '_offset': datetime.timedelta(1), '_named': 'D', '_use_relativedelta': False}

# modify its property
x.n = 5

# NG, modified instance is returned
y = pd.tseries.frequencies.get_offset('D')
y.__dict__
# {'normalize': False, 'kwds': {}, 'n': 5, '_offset': datetime.timedelta(1), '_named': 'D', '_use_relativedelta': False}
```

It should return a copy of the cache.

**Comment by jreback** [comment]
yeh these are class properties, but ``get_offset`` should prob return a copy. Though need to check for perf impacts on this.

**Comment by sinhrks** [comment]
[``n`` is an instance property](https://github.com/pydata/pandas/blob/master/pandas/tseries/offsets.py#L182) specify its length/span. I don't think user touch it actually though... 

From what I've seen, there is no function uses freq taken from ``get_offset`` as it is. Applying numeric ops (like multiplying freq mult) will results in copy. Thus, user ops should not affect to internal cache.

```
pd.tseries.frequencies.get_offset('A')
# A-DEC
pd.tseries.frequencies.get_offset('A') * 1
# <YearEnd: month=12>
```

Above repr difference is caused by ``_named`` property, which looks to be attached by [``_make_offset``](https://github.com/pydata/pandas/blob/master/pandas/tseries/offsets.py#L2669). It is introduced in #5189 for repr backcompat. I don't think it is needed anymore (because user can't get freq from ``get_offset``).

Maybe we can cleanup freq-retrieving functions in ``freqnencies.py`` and guarantee user can't touch the internal cache.
