### ISSUE TITLE
Unexpected behavior with apply function on axis 0

### ISSUE THREAD

**Issue by flolas** [pydata/pandas#11200]
Hi,
is this a expected behavior when using apply on axis 0?( apply iterates twice the first column a)
Thanks!

```python
import pandas as pd
import numpy as np
pd.show_versions()
df3 = pd.DataFrame(np.random.randn(10, 5),columns=['a', 'b', 'c', 'd', 'e'])
```

    
    INSTALLED VERSIONS
    ------------------
    commit: None
    python: 2.7.10.final.0
    python-bits: 64
    OS: Darwin
    OS-release: 14.5.0
    machine: x86_64
    processor: i386
    byteorder: little
    LC_ALL: None
    LANG: None
    
    pandas: 0.16.2
    nose: 1.3.7
    Cython: 0.22.1
    numpy: 1.9.2
    scipy: 0.16.0
    statsmodels: 0.6.1
    IPython: 4.0.0
    sphinx: 1.3.1
    patsy: 0.3.0
    dateutil: 2.4.2
    pytz: 2015.4
    bottleneck: 1.0.0
    tables: 3.2.0
    numexpr: 2.4.3
    matplotlib: 1.4.3
    openpyxl: 1.8.5
    xlrd: 0.9.3
    xlwt: 1.0.0
    xlsxwriter: 0.7.3
    lxml: 3.4.4
    bs4: 4.3.2
    html5lib: None
    httplib2: None
    apiclient: None
    sqlalchemy: 1.0.5
    pymysql: None
    psycopg2: None

```python
def f(x):
    print(x.name)
    return x
df3.apply(f,0)
```

    a
    a
    b
    c
    d
    e

<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>a</th>
      <th>b</th>
      <th>c</th>
      <th>d</th>
      <th>e</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1.726737</td>
      <td>-0.759505</td>
      <td>-0.847297</td>
      <td>-0.753917</td>
      <td>-0.308126</td>
    </tr>
    <tr>
      <th>1</th>
      <td>0.944636</td>
      <td>0.111687</td>
      <td>-1.918813</td>
      <td>0.609801</td>
      <td>-0.800732</td>
    </tr>
    <tr>
      <th>2</th>
      <td>-1.452284</td>
      <td>-0.311735</td>
      <td>0.526410</td>
      <td>0.486475</td>
      <td>0.183785</td>
    </tr>
    <tr>
      <th>3</th>
      <td>1.159549</td>
      <td>-0.691184</td>
      <td>-0.671914</td>
      <td>0.411232</td>
      <td>-0.759693</td>
    </tr>
    <tr>
      <th>4</th>
      <td>-1.102834</td>
      <td>-0.442751</td>
      <td>-2.195439</td>
      <td>1.057525</td>
      <td>-1.611347</td>
    </tr>
    <tr>
      <th>5</th>
      <td>-0.628189</td>
      <td>0.088928</td>
      <td>-0.725967</td>
      <td>-0.728804</td>
      <td>-0.060732</td>
    </tr>
    <tr>
      <th>6</th>
      <td>-0.908476</td>
      <td>1.002714</td>
      <td>-0.038057</td>
      <td>1.407736</td>
      <td>-0.750645</td>
    </tr>
    <tr>
      <th>7</th>
      <td>2.446902</td>
      <td>1.916245</td>
      <td>1.000570</td>
      <td>-1.045217</td>
      <td>1.621034</td>
    </tr>
    <tr>
      <th>8</th>
      <td>0.890660</td>
      <td>2.575584</td>
      <td>-0.362869</td>
      <td>-1.074129</td>
      <td>-0.271362</td>
    </tr>
    <tr>
      <th>9</th>
      <td>1.430119</td>
      <td>-0.315331</td>
      <td>-0.768683</td>
      <td>-1.719671</td>
      <td>-1.754809</td>
    </tr>
  </tbody>
</table>
</div>

```python

```

**Comment by jreback** [comment]
see warning [in the docs](http://pandas.pydata.org/pandas-docs/stable/groupby.html#flexible-apply)

an apply may be executed multiple times to determine if their is mutation in a user-defined function in order to take a potentially faster path. this is an implementation detail.
