### ISSUE TITLE
pandas.DataFrame.div "MemoryError"

### ISSUE THREAD

**Issue by JohnNapier** [pydata/pandas#11204]
Using Pandas 0.16.2, NumPy 1.9.2.

This pairwise operation is completed without errors.
```python
df0=pd.DataFrame(np.random.normal(size=(10000,100)))
df1=df0.div(df0.sum(axis=1))
```

This one involves 10 times more rows. Memory never exceeds 50%, and yet a MemoryError comes up.

```python
df0=pd.DataFrame(np.random.normal(size=(100000,100)))
df1=df0.div(df0.sum(axis=1))
```

Same issue if I use the (now deprecated) method:

```python
df0=pd.DataFrame(np.random.normal(size=(100000,100)))
df1=df0/df0.sum(axis=1)
```

Thanks

**Comment by jorisvandenbossche** [comment]
@JohnNapier The result `df1` would be of shape  (100000, 100000), which be approximately be 74 GB, so the memory error is not surprising?

**Comment by jorisvandenbossche** [comment]
But maybe you want `df0.div(df0.sum(axis=1), axis=0)` ?

Further, why would `df0/df0.sum(axis=1)` be deprecated? (that is only for timeseries that the broadcasting will be changed to the same behaviour (matching on the columns) as for other types)

**Comment by shoyer** [comment]
Indeed, you are almost certainly getting confused by the way that pandas does "broadcasting" between operations. The elements of the series are aligned against the *columns* of the dataframe, not the rows. This follows the broadcasting rule from numpy, aligns from the last dimension.

**Comment by JohnNapier** [comment]
@jorisvandenbossche, you are right, I thought the default broadcasting axis was zero. Thanks for making this clear.

Otherwise, are we not supposed to use df0.div(df0.sum(axis=1), axis=0) rather than df0/df0.sum(axis=1)? When I use the latter, I get the warning:

```python
FutureWarning: TimeSeries broadcasting along DataFrame index by default is deprecated. Please use DataFrame.<op> to explicitly broadcast arithmetic operations along the index
  FutureWarning)
```

**Comment by jorisvandenbossche** [comment]
yes, indeed, when having a DatetimeIndex, there is a deviation from the standard rule (broadcasting on the columns or axis 1). But as this is inconsistent with all other types of indexes, this behaviour is deprecated and you have to use `div(.. , axis=0)`.

One of the main uses of `df.div(s)` method is actually the `axis=0` case, because with `axis=1 it is equivalent to just `df/s`
