### ISSUE TITLE
Dataframe.from_dict inconsistent behavior

### ISSUE THREAD

**Issue by szeitlin** [pydata/pandas#11213]
python 3.4, pandas version 0.16.2

this works:

        monthly = {'datetime_col_to_use':['START DATE'],
          'colnames': ["TYPE", "START DATE", "END DATE", "USAGE", "UNITS", "COST", "NOTES"],
          'header_size':4,
          'concat_datetime_cols': False}

        monthly_df = pd.DataFrame.from_dict(monthly, orient='index')

![screen shot 2015-09-30 at 5 32 06 pm](https://cloud.githubusercontent.com/assets/5185401/10210243/3ae55f3e-6799-11e5-9e12-fb8200a4c496.png)

but this doesn't:

        hourly = {'datetime_col_to_use': ['START TIME', 'DATE'],
         'colnames': ["TYPE", "DATE", "START TIME", "END TIME", "USAGE", "UNITS", "COST", "NOTES"],
         'header_size':4,
         'concat_datetime_cols': True}

        hourly_df = pd.DataFrame.from_dict(hourly, orient='index')

Full traceback:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-18-66cef4447f7e> in <module>()
----> 1 hourly_df = pd.DataFrame.from_dict(hourly, orient='index')
      2 #hourly_df.columns=['hourly']
      3 #hourly_df.head()

/home/vagrant/venv/lib/python3.4/site-packages/pandas/core/frame.py in from_dict(cls, data, orient, dtype)
    681             raise ValueError('only recognize index or columns for orient')
    682 
--> 683         return cls(data, index=index, columns=columns, dtype=dtype)
    684 
    685     @deprecate_kwarg(old_arg_name='outtype', new_arg_name='orient')

/home/vagrant/venv/lib/python3.4/site-packages/pandas/core/frame.py in __init__(self, data, index, columns, dtype, copy)
    249             if len(data) > 0:
    250                 if is_list_like(data[0]) and getattr(data[0], 'ndim', 1) == 1:
--> 251                     arrays, columns = _to_arrays(data, columns, dtype=dtype)
    252                     columns = _ensure_index(columns)
    253 

/home/vagrant/venv/lib/python3.4/site-packages/pandas/core/frame.py in _to_arrays(data, columns, coerce_float, dtype)
   4917     if isinstance(data[0], (list, tuple)):
   4918         return _list_to_arrays(data, columns, coerce_float=coerce_float,
-> 4919                                dtype=dtype)
   4920     elif isinstance(data[0], collections.Mapping):
   4921         return _list_of_dict_to_arrays(data, columns,

/home/vagrant/venv/lib/python3.4/site-packages/pandas/core/frame.py in _list_to_arrays(data, columns, coerce_float, dtype)
   4998     else:
   4999         # list of lists
-> 5000         content = list(lib.to_object_array(data).T)
   5001     return _convert_object_array(content, columns, dtype=dtype,
   5002                                  coerce_float=coerce_float)

pandas/src/inference.pyx in pandas.lib.to_object_array (pandas/lib.c:58728)()

TypeError: object of type 'bool' has no len()
```

**Comment by TomAugspurger** [comment]
These both raise `TypeError: object of type 'bool' has no len()` for me on master. I couldn't find which PR fixed it though.

**Comment by szeitlin** [comment]
haha! so which is the expected behavior? Error or no error?

**Comment by TomAugspurger** [comment]
This is a bit of an edge case. `DataFrame.from_dict` in this case (since there's just one row) should be equivalent to `pd.DataFrame(list(monthly.values())).T`, which raises, but `pd.DataFrame(list(reversed(list(monthly.values())))).T` (notice the reversed) works.

That's a long way to say that the constructor sees that `['START DATE']` is an array and starts looking for more arrays, but when it gets to False or 4, it errors since those aren't arraylike.

I'd say your safest bet is to avoid putting array-like objects into Series. Is this related to the problem you had in that slack channel?

**Comment by szeitlin** [comment]
yeah, I figured it was something like that. 

Yes, wondering about best way(s) to store array-like objects.
