### ISSUE TITLE
TST: fix some unreliable html_truncate tests

### ISSUE THREAD

**Issue by jreback** [pydata/pandas#11210]
These are occasionally failing on travis: https://github.com/pydata/pandas/commit/2f59a027a28ef50aeedb7753420a7605a2036aaa

don't fail for me locally, so not sure what's up.

**Comment by sinhrks** [comment]
I also can't reproduce it locally, but it is caused by ``div_style`` added if ipython 2.4.1 is installed (maybe for doc build?)

https://github.com/pydata/pandas/blob/master/pandas/core/format.py#L898

**Comment by jreback** [comment]
oh ok

so need to skip this test for < versions of ipython I guess

**Comment by kawochen** [comment]
but the tests had the same thing https://github.com/pydata/pandas/blob/master/pandas/tests/test_format.py#L18-L24

**Comment by jreback** [comment]
agreed something prob changed on Travis

**Comment by jreback** [comment]
this seems not to be happening any longer
