### ISSUE TITLE
AttributeError: 'DataFrame' object has no attribute 'bits'

### ISSUE THREAD

**Issue by mlotfi2005** [pydata/pandas#11222]
Hi, I am new here just started some tutorials learning python, can you plz help me 

'vw_bits_amazon.csv'
bits	loss
25	0.151731
24	0.151809
23	0.151951
22	0.151809

import pandas as pd
from matplotlib import pyplot as plt

input_file = 'vw_bits_amazon.csv'
d = pd.read_csv(input_file)
plt.plot(d.bits, d.loss)
plt.show()

I got 
AttributeError: 'DataFrame' object has no attribute 'bits'

**Comment by jreback** [comment]
you need to send a ``sep``

```
In [2]: pd.read_csv(StringIO(data))
Out[2]: 
     bits loss
0  25 0.151731
1  24 0.151809
2  23 0.151951
3  22 0.151809

In [3]: pd.read_csv(StringIO(data)).columns
Out[3]: Index([u'bits loss'], dtype='object')

In [4]: pd.read_csv(StringIO(data),sep='\s+')
Out[4]: 
   bits      loss
0    25  0.151731
1    24  0.151809
2    23  0.151951
3    22  0.151809
```

**Comment by mlotfi2005** [comment]
Thanks jreback,

I am sorry, I did not understand what do you mean by sep, please bear with me, I am new here, how I am going to change my code to work ?
Thanks

**Comment by jreback** [comment]
see the example I put above. you need to pass ``sep='\s+'`` for whitespace separators, also ready the docs [here](http://pandas.pydata.org/pandas-docs/stable/io.html#csv-text-files)

**Comment by mlotfi2005** [comment]
Thank you, it works, but without StringIO, where this come from ? because it was not recognized .

**Comment by jreback** [comment]
you still put your filename like before.

``pd.read_csv("filename",sep='\s+')``
