### ISSUE TITLE
Testing RC versions of pandas in conda

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [pydata/pandas#11254]
I got this ANN email from the PyData mailing list from @jreback:

> I'm pleased to announce the availability of the second release candidate of Pandas 0.17.0.
> ...
> Best way to get this is to install via conda from our development channel. Builds for osx-64,linux-64,win-64 for Python 2.7, Python 3.4, and Python 3.5 (for osx/linux) are all available.

> `conda install pandas -c pandas`

which is awesome! I can't wait for the new version to be out. I'd love to help with debugging, but when I tried to install the RC, I still got `0.16.2` in Python 3.5. See below:

```
$ conda install pandas -c pandas
Fetching package metadata: ........
Solving package specifications: ............
Package plan for installation in environment /Users/avazquez/anaconda3/envs/py35:

The following NEW packages will be INSTALLED:

    pandas: 0.16.2-np19py35_0

Proceed ([y]/n)? y

Linking packages ...
[ COMPLETE]
```

Same thing if I uninstall pandas first and then try `conda install pandas -c pandas` again. Any thoughts on what could be wrong?

**Comment by TomAugspurger** [comment]
What platform are you on, and I'm assuming python 3.5? We may not have a 3.5 build for your platform.

You can see the platforms / pytohns here: https://anaconda.org/pandas/pandas/files

**Comment by amelio-vazquez-reina** [comment]
Oh thanks. I'm on Python 3.5 in OS X 64 (El Capitan).

**Comment by amelio-vazquez-reina** [comment]
Hmm, that's interesting, based on that link, this version is available: `osx-64/pandas-v0.17.0rc2-py35_0.tar.bz2`.

**Comment by chris-b1** [comment]
I ran into this, for whatever reason it thinks the new rc is a lower version.    A workaround is 
`conda install -c pandas pandas=v0.17`

**Comment by amelio-vazquez-reina** [comment]
Thanks @chris-b1 Yes, that worked.
