### ISSUE TITLE
add set_index_ncol(ncol) to set first n columns as indices

### ISSUE THREAD

**Issue by cailiang9** [pydata/pandas#11264]
```
df = pd.read_sql('select idx1,idx2,metric1 from table1 ', dbcon)
df.set_index(list(df.columns)[:ncol]).T.to_dict('list')
```

such operations are very frequent in product

**Comment by jreback** [comment]
this would add needless api complexing and inference; you would run the problem of is this positional or label based.

``df.set_index(df.columns[:ncol])`` seems reasonable to me

**Comment by jorisvandenbossche** [comment]
Agree with @jreback 

One possible enhancement we could consider (specifically for the example you give) is the ability to specify the index cols in read_sql with integers like `pd.read_sql('select idx1,idx2,metric1 from table1 ', dbcon, index_col=[0,1])`
