### ISSUE TITLE
Using blosc compression in pandas causes heap corruption in Windows

### ISSUE THREAD

**Issue by xgdgsc** [pydata/pandas#11266]
When I run `df.to_hdf('filename', complib='blosc')` in windows , with anaconda python3.4. Python would crash. When I used anaconda python2.7, it didn' t crash. It doesn' t crash with anaconda python 3 in linux.
```
INSTALLED VERSIONS
------------------
commit: None
python: 3.4.3.final.0
python-bits: 64
OS: Windows
OS-release: 8
machine: AMD64
processor: Intel64 Family 6 Model 61 Stepping 4, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None

pandas: 0.16.2
nose: 1.3.7
Cython: 0.22.1
numpy: 1.9.3
scipy: 0.15.1
statsmodels: 0.6.1
IPython: 3.2.0
sphinx: 1.3.1
patsy: 0.3.0
dateutil: 2.4.2
pytz: 2015.4
bottleneck: 1.0.0
tables: 3.2.2
numexpr: 2.4.4
matplotlib: 1.4.3
openpyxl: 1.8.5
xlrd: 0.9.3
xlwt: 1.0.0
xlsxwriter: 0.7.3
lxml: 3.4.4
bs4: 4.3.2
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.0.5
pymysql: None
psycopg2: None
```

Some other people also experience this: http://stackoverflow.com/questions/32897866/using-blosc-compression-in-pandas-causes-heap-corruption .

**Comment by jreback** [comment]
try using latest of ``PyTables``, e.g. 3.2.2

can you show ``blosc`` version?

**Comment by xgdgsc** [comment]
As shown above tables: 3.2.2 is already latest. Blosc version should be the bundled v1.4.4 as shown in [PyTables/c-blosc at v.3.2.2 · PyTables/PyTables](https://github.com/PyTables/PyTables/tree/v.3.2.2/c-blosc).

**Comment by xgdgsc** [comment]
Seems an issue with anaconda build https://github.com/ContinuumIO/anaconda-issues/issues/458

**Comment by jreback** [comment]
yeh could be
