### ISSUE TITLE
COMPAT: drop support for Python 3.3

### ISSUE THREAD

**Issue by jreback** [pydata/pandas#11273]

**Comment by jreback** [comment]
any objections for 0.18.0 (early next year) here

@jorisvandenbossche @shoyer @cpcloud @TomAugspurger @sinhrks @wesm 

3.4 and 3.5 pretty well supported (and conda no longer building for 3.3)
though I can build/post them

**Comment by tacaswell** [comment]
Same as 2.6, mpl is going to officially drop 3.3 support for 2.0, but I do not anticipate mpl using any py3 features which are not in 3.3 as we are still supporting legacy python anyway.

**Comment by jreback** [comment]
@tacaswell when you are anticipating 2.0?

**Comment by tacaswell** [comment]
End of november/early December.  The current plan is for me and @mdboom to sort out the new default around pydata NYC.

**Comment by tacaswell** [comment]
3.3 might be 'officially' dropped from 1.5 which should be out it ~week as well.

**Comment by jreback** [comment]
@tacaswell ok gr8. we are not planning this till 0.18.0 prob early next year.
