### ISSUE TITLE
CLN/DEPR: remove engine='python' from to_csv

### ISSUE THREAD

**Issue by jreback** [pydata/pandas#11274]
the ``engine`` kw and older code: https://github.com/pydata/pandas/blob/master/pandas/core/format.py#L1364

let's deprecate in 0.17.1 and just remove in 0.18.0

This was never advertised / doc-ed so prob safe to remove

**Comment by taeold** [comment]
What does deprecation mean compared to removal? Are you looking for code emitting warning messages indicating that `engine=python` is no longer supported sufficient?

**Comment by jreback** [comment]
@taeold exactly what I mean, IOW, if ``engine=='python'`` (or actually is not ``None``), then we emit a Future Warning that we are going to remove it in a future version. Then at some future release we will.

**Comment by jreback** [comment]
closed by #11319
