### ISSUE TITLE
name and behavior mismatch in pct_change

### ISSUE THREAD

**Issue by lurgyman63** [pydata/pandas#11289]
Hi all,

I've enjoyed using pandas for a little while now. Thanks for developing such a useful and convenient tool!

A little nit has been nagging at me about pct_change function (and the .pct_change method of Series, DataFrame, etc.).  If I run a sequence of numbers that increase by 100% (python 0.16.2):

```python
import pandas as pd

series = pd.Series([0.5,1,2,4])
print series.pct_change()
```

the output is:

```
0   NaN
1     1
2     1
3     1
dtype: float64
```

Based on the name pct_change, I'd expect the result should the percentage change (i.e., scaled by 100):

```
0   NaN
1     100
2     100
3     100
dtype: float64
```

In general it looks to me like in general pct_change is really a _fractional_ change. Perhaps the name would suggest the behavior more closely if the function and method were called frac_change? I've become familiar with pandas enough now to know the expected behavior, but this could be a confusing turn-off for newer users.

**Comment by jreback** [comment]
usually it is left to the user to determine whether things are 0-100 or 0-1. This is the convention numpy/pandas have taken for quite a while.

**Comment by lurgyman63** [comment]
Hmm, I'm confused, obviously users can scale by whatever constant they would like, but seems like a different issue.  The name percentage implies 0-100, which is not what the function returns.

From https://en.wikipedia.org/wiki/Percentage - "In mathematics, a percentage is a number or ratio expressed as a fraction of 100." 

All examples I can find in numpy/scipy behave with 0-100 scaling:

http://docs.scipy.org/doc/numpy-dev/reference/generated/numpy.percentile.html
http://docs.scipy.org/doc/scipy-0.13.0/reference/generated/scipy.stats.percentileofscore.html
https://docs.scipy.org/doc/scipy-0.14.1/reference/generated/scipy.misc.imresize.html
http://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.scoreatpercentile.html
http://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.filters.percentile_filter.html

While obviously like you say, the user can scale the output by whatever number they'd like, bugs crop up if the scale isn't what they expect, no?  Why not make the function the same as what the user should expect, so that it is easiest to get the scaling to where it should be?

**Comment by jreback** [comment]
maybe 

but would be impossible to actually change this
as the function has been around for many years
and you cannot deprecate something like this
