### ISSUE TITLE
DEPR: google-analytics

### ISSUE THREAD

**Issue by jreback** [pydata/pandas#11308]
not supported / tested in quite some time. this should be spun off into a separate package.

let's deprecate at least in 0.17.1.

**Comment by jorisvandenbossche** [comment]
+1 to split this off into its own package

**Comment by DeliciousHair** [comment]
Taking up your suggestion for moving this to a separate package, I've done just that:

https://github.com/panalysis-gpl/Google2Pandas

Cheers!
