### ISSUE TITLE
DataFrame .sum() division now expands columns to include index

### ISSUE THREAD

**Issue by schwallie2** [pydata/pandas#11311]
```
dic = {'01/31/2015': {'A': 5, 'B': 10, 'C': 15}, 
          '02/28/2015': {'A': 1, 'B': 20, 'C': 2}}
df = pd.DataFrame.from_dict(dic, orient='index')
df * 100 / df.sum(axis=1)

Out[33]:
            01/31/2015  02/28/2015   A   B   C
01/31/2015         NaN         NaN NaN NaN NaN
02/28/2015         NaN         NaN NaN NaN NaN
```

What used to occur here was this, which I assume is expected behavior:

```
df.apply(lambda x: x * 100 / x.sum(), axis=1)

Out[34]:
                                A          C          B
01/31/2015  16.666667  50.000000  33.333333
02/28/2015   4.347826   8.695652  86.956522
```

**Comment by jreback** [comment]
pls ``pd.show_versions()``

**Comment by schwallie2** [comment]
Sorry,

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.10.final.0
python-bits: 64
OS: Darwin
OS-release: 14.5.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

pandas: 0.17.0
nose: 1.3.7
pip: 7.1.2
setuptools: 18.3.2
Cython: 0.22.1
numpy: 1.10.0.post2
scipy: 0.15.1
statsmodels: None
IPython: 4.0.0
sphinx: 1.3.1
patsy: 0.3.0
dateutil: 2.4.2
pytz: 2015.6
blosc: None
bottleneck: 1.0.0
tables: 3.2.0
numexpr: 2.4.3
matplotlib: 1.4.3
openpyxl: 2.2.6
xlrd: 0.9.3
xlwt: 1.0.0
xlsxwriter: 0.7.3
lxml: 3.4.4
bs4: 4.3.2
html5lib: None
httplib2: 0.9.1
apiclient: 1.4.2
sqlalchemy: 1.0.5
pymysql: None
psycopg2: 2.6.1 (dt dec pq3 ext lo64)

**Comment by jreback** [comment]
not sure what you mean by ``used to work``,  what you are doing never worked.

```
In [5]: df*100/df.sum()
Out[5]: 
                    A          C          B
01/31/2015  83.333333  88.235294  33.333333
02/28/2015  16.666667  11.764706  66.666667
```

**Comment by schwallie2** [comment]
So what you're saying is it was previously a bug that is now fixed.

I've had this piece of code running daily for ~3 months and it has worked the way I wanted it to work, only on the update to .17.0 has it changed to the new behavior.

**Comment by jreback** [comment]
and what version were you running before? This has not changed in quite a long time.

**Comment by schwallie2** [comment]
Worked fine on .16.2.

I could have neglected updating numpy somehow, and maybe when that updated it caused the problem? I guess this is all null and void, if this is expected behavior then it doesn't really matter when it changed to correct behavior!

**Comment by jreback** [comment]
I would guess that you were doing this:

Note the ``DatetimeIndex``. This warning has been there since 0.8.0. This is also documented [here](http://pandas.pydata.org/pandas-docs/stable/whatsnew.html#whatsnew-0170-prior-deprecations) in the whatsnew.

```
In [13]: df.index = pd.to_datetime(df.index)

In [14]: df
Out[14]: 
            A   C   B
2015-01-31  5  15  10
2015-02-28  1   2  20

In [15]: df / df.sum(axis=1)
/Users/jreback/miniconda/envs/pandas_0.16.2/lib/python2.7/site-packages/pandas/core/frame.py:3200: FutureWarning: TimeSeries broadcasting along DataFrame index by default is deprecated. Please use DataFrame.<op> to explicitly broadcast arithmetic operations along the index
  FutureWarning)
Out[15]: 
                   A         C         B
2015-01-31  0.166667  0.500000  0.333333
2015-02-28  0.043478  0.086957  0.869565
```

Your example above does not reproduce.

**Comment by schwallie2** [comment]
Just so if anyone else looks at this;

This code:

`df*100/df.sum()`

Does not produce the needed output. What we want is the percent of total by row, not by column. The lambda at the top works still.

**Comment by jreback** [comment]
@schwallie2 you need to adjust your code as the documentation states. This was a deprecation change that was warning since 0.8.0

you can simply do this

```
In [23]: 100*df.div(df.sum(axis=1),axis=0)
Out[23]: 
                    A          C          B
2015-01-31  16.666667  50.000000  33.333333
2015-02-28   4.347826   8.695652  86.956522
```
