### ISSUE TITLE
BUG: read_excel doesn't respect string data

### ISSUE THREAD

**Issue by chris-b1** [pydata/pandas#11331]
From [SO](http://stackoverflow.com/questions/33137686/python-loading-zip-codes-into-a-dataframe-as-strings/33137797#33137797)

```python
In [16]: df = pd.DataFrame({'a': ['001','002']})

In [17]: df.to_excel('temp.xlsx')

In [18]: pd.read_excel('temp.xlsx')
Out[18]: 
   a
0  1
1  2
```

I think it would probably make sense for `read_excel` to not try and convert strings to numeric, or at least have another keyword argument.

**Comment by jreback** [comment]
xref https://github.com/pydata/pandas/issues/8212

this should be done via the dtype kw (and not s converter) as it's more consistent with how the other parsers work

and it should be coercing normally as that is the expected behavior

**Comment by chris-b1** [comment]
I guess my point is that (unlike csv, etc) Excel numeric data will already be de-serialized as a python numeric type, so the only data that will be strings are those explicitly stored as strings in Excel.  So a different default could make sense?

**Comment by jreback** [comment]
zipcodes are usually stored as integers with a format
not sure u can detect this (but maybe it's not being taken into account)

**Comment by chris-b1** [comment]
Right, if that were the case I think the data should still be read as integers.  In this example case the zipcodes were stored as Excel text (i.e. if you typed `'00500`)

![image](https://cloud.githubusercontent.com/assets/1924092/10501873/64e0a592-72ab-11e5-85b2-b432faa14947.png)

```python
In [25]: ws = xlrd.open_workbook('test.xlsx').sheet_by_index(0)

In [26]: ws.cell_value(1, 0)
Out[26]: 55.0

In [27]: ws.cell_value(2, 0)
Out[27]: u'00500'
```

**Comment by jreback** [comment]
ok then might be a bug then

**Comment by stevemaughan** [comment]
Zipcodes are usually stored as strings. You also have zip+4 which also need to be stored as strings e.g. 32771-5407

**Comment by jreback** [comment]
dupe of #8212
