### ISSUE TITLE
0.17 changes behavior of division of DataFrame by Series in presence of DateTimeIndex

### ISSUE THREAD

**Issue by twiecki** [pydata/pandas#11336]
Older versions up to 0.16.2:
```python
import pandas as pd
print(pd.__version__)
index = pd.date_range(start='2000-1-1', end='2000-1-3')
pd.DataFrame({1: [3, 3, 3], 2: [6, 6, 6]}, index=index) / pd.Series([2, 2, 2], index=index)
```
```
0.14.0rc1-33-g8c1f550
1	2
2000-01-01	1.5	3
2000-01-02	1.5	3
2000-01-03	1.5	3
```

0.17:
```
0.17.0
2000-01-01 00:00:00	2000-01-02 00:00:00	2000-01-03 00:00:00	1	2
2000-01-01	NaN	NaN	NaN	NaN	NaN
2000-01-02	NaN	NaN	NaN	NaN	NaN
2000-01-03	NaN	NaN	NaN	NaN	NaN
```

Work-around:
Use `df.divide(series, axis='index')`. 

Is this change in API intentional? Couldn't find it in the release announcements.

**Comment by TomAugspurger** [comment]
Looks like [this deprecation](http://pandas.pydata.org/pandas-docs/stable/whatsnew.html#whatsnew-0170-prior-deprecations) on automatic time-series broadcasting, from https://github.com/pydata/pandas/issues/2304

**Comment by jreback** [comment]
@twiecki this is as expected and has a specific mention in the whatsnew [here](http://pandas.pydata.org/pandas-docs/stable/whatsnew.html#whatsnew-0170-prior-deprecations)

**Comment by twiecki** [comment]
Thanks @jreback. Never noticed the warning.

**Comment by jreback** [comment]
@twiecki yep. It has been around for quite a long time. Finally got around to removing it :)

**Comment by twiecki** [comment]
I have full confidence that it was the right move :).
