### ISSUE TITLE
Offline/behind proxy build can't have setup_requires

### ISSUE THREAD

**Issue by mbultrow** [pydata/pandas#11342]
I'm having problems with building a package depending on Pandas behind proxy, because setup_requires is specified in setup.py.
"pip install" calls setup.py egg_info, which in turn wants numpy, which it cannot find. Numpy is installed along with Pandas by pip, but setup.py can't know about this.

The same issue would also appear if I'd want install an offline package for the app I'm using.
This is why [pip documentation discourages setup_requires](https://pip.readthedocs.org/en/stable/user_guide/#ensuring-repeatability)

I see that there was a request opposite to mine (#3861) to make it usable with buildout... But maybe there's another way to use it with buildout? I think that pip is more of a Python standard than buildout...

**Comment by jreback** [comment]
you should simply use ``conda``, but if you'd like to see if you can fix this go right ahead. never seen this issue before.

**Comment by mbultrow** [comment]
The issue concerns only installation in offline/proxied environments, which may not be common for Pandas users. I don't know if we can use `conda`, because all things we are integrating would be required to use it or we would need to make some strange pip/conda mixing.

Anyway, it doesn't bother us at the moment, because we were just checking out one component, but if we'll need to automate things, then I'll maybe try to fix this. You know, I just wanted to let you know.

**Comment by jreback** [comment]
ok, pls reopen if needed then
