### ISSUE TITLE
ENH: logical operator "in" for pd.Term

### ISSUE THREAD

**Issue by michaelaye** [pydata/pandas#11348]
I don't know if this is possible with the current pytables implementation/interface, but I would find it useful to be able to do filtering like this on disk:

```python
df = pd.read_hdf(dbname, 'df', where='colname in ["a","b"]')
```

**Comment by jreback** [comment]
that already works

what are you trying to do?

**Comment by jreback** [comment]
```
In [1]: df = DataFrame({'A' : ['foo','bar','baz'], 'B' : range(3) })

In [2]: df.to_hdf('test.h5','df',mode='w',format='table',data_columns=True)

In [3]: pd.read_hdf('test.h5','df',where='A in ["bar","baz"]')
Out[3]: 
     A  B
1  bar  1
2  baz  2

In [4]: pd.read_hdf('test.h5','df',columns=['A'])             
Out[4]: 
     A
0  foo
1  bar
2  baz
```

**Comment by michaelaye** [comment]
Ah, thanks. I only saw `"columns in ['A', 'D']"` in the list of [allowed expressions](http://pandas.pydata.org/pandas-docs/stable/io.html#querying-a-table)  and even didn't try it then. (As this `columns` is of course reserved to select on columns themselves, not their content. I now see that the [section about pd.Categorical](http://pandas.pydata.org/pandas-docs/stable/io.html#categorical-data) is the first mentioning the `in` operator to be used to select rows. Should this maybe be mentioned in the upper general querying section of the docs?

**Comment by jreback** [comment]
yep could use an example in this section
http://pandas.pydata.org/pandas-docs/stable/io.html#querying
