### ISSUE TITLE
Error in dataframe when row is deleted

### ISSUE THREAD

**Issue by vikrantrathore** [pydata/pandas#11353]
After creating a dataframe from excel and then deleting some rows by column value like
```
df = df[df.Name != "TBC"]
```
 when need to iterate through the value of a column it throws key error as shown below. 

It works fine if I do not delete the rows.

"
---> 38 print df["Country"][19]

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pandas/core/series.pyc in __getitem__(self, key)
    549     def __getitem__(self, key):
    550         try:
--> 551             result = self.index.get_value(self, key)
    552 
    553             if not np.isscalar(result):

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pandas/core/index.pyc in get_value(self, series, key)
   1721 
   1722         try:
-> 1723             return self._engine.get_value(s, k)
   1724         except KeyError as e1:
   1725             if len(self) > 0 and self.inferred_type in ['integer','boolean']:

pandas/index.pyx in pandas.index.IndexEngine.get_value (pandas/index.c:3204)()

pandas/index.pyx in pandas.index.IndexEngine.get_value (pandas/index.c:2903)()

pandas/index.pyx in pandas.index.IndexEngine.get_loc (pandas/index.c:3843)()

pandas/hashtable.pyx in pandas.hashtable.Int64HashTable.get_item (pandas/hashtable.c:6525)()

pandas/hashtable.pyx in pandas.hashtable.Int64HashTable.get_item (pandas/hashtable.c:6463)()

KeyError: 19

**Comment by jreback** [comment]
```
In [4]: df = DataFrame({'A' : ['foo','bar','baz']})

In [5]: df[df.A!='bar']
Out[5]: 
     A
0  foo
2  baz

In [6]: df[df.A!='bar'][1]
KeyError: 1
```

you are looking up a value that is not represented, so this is as expected. Generally don't use the chain syntax for multiple selections, ``df.loc[df.A!='bar',1]`` is the canonical method.
