### ISSUE TITLE
memory issues when doing inplace operations and dataframe wide operations

### ISSUE THREAD

**Issue by arjay55** [pydata/pandas#11360]
Hi,

Whenever I do inplace operations in pandas, especially when performing operations like replace or astype. The memory blows up close or greater than 8GB(esp on values).  

Same happens when using values or concatenation of larger dataframes. 

The workaroud is to do a per column operation, even on concatenation(using column addition). But since this is becoming a common issue (or at least that what I see), can algorithms for efficient memory management be added whole dataframe operations, e.g., checking the memory of the machine and then splitting the operation into chunks so that the user won't be less concerned in having memory bottlenecks when executing such pandas commands.

Thanks in advance.

Example,
```python
allcols=allcols[0:400]
train=[eval('dftrain.'+allcols[0]).values]
del allcols[0]
for x in allcols:
    train=np.append(train,[eval('dftrain.'+x).values], axis=0)
del dftrain
```
if I used dftrain.values[x,y] command, the memory usage will blow up above 8GB, and the kernel will die.

**Comment by jreback** [comment]
pls read the warning http://pandas.pydata.org/pandas-docs/stable/merging.html#concatenating-objects

you are copying things in s completely inefficient mannner

what are you trying to do?

**Comment by arjay55** [comment]
I'm producing a numpy array which is a part of an original dataframe. The array will be used for classification algorithms from scikit learn.

**Comment by jreback** [comment]
well, you are doing a repeated append, which will blow up memory.

simply do

```allcols[0:400].values`` which is a view

**Comment by arjay55** [comment]
Hi. i tried doing

train=dftrain[:].values 

and my kernel died as well.


Regards,

Sent from Yahoo Mail on Android

**Comment by arjay55** [comment]
Hi jreback,

Can you reopen this issue, or, provide an explanation why this happened?

Thanks.

**Comment by jreback** [comment]
did you read the warning in the docs. that's the explanation.
