### ISSUE TITLE
Irregular TimedeltaIndex points being spaced regularly along x-axis

### ISSUE THREAD

**Issue by drichman** [pydata/pandas#11378]
This bug shows up when using the plot method of a Series or DataFrame (Series example below) that has a TimedeltaIndex. x-axis time points become regularly spaced rather than spaced according to real time spans.

```python
import pandas as pd

clock_times = pd.to_datetime(['12:00:00','12:23:00','12:30:00','12:45:00','13:54:00','14:15:00'])

elapsed_times = clock_times - clock_times[0]

test_data = pd.Series(data=[1,2,3,4,5,6], index=elapsed_times)

test_data.plot(style='o')
```

(Going straight to matplotlib is a workaround (plt.plot(test_data.index, test_data).)

INSTALLED VERSIONS
------------------
commit: None
python: 3.4.3.final.0
python-bits: 64
OS: Darwin
OS-release: 15.0.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

pandas: 0.16.2
nose: None
Cython: None
numpy: 1.9.3
scipy: 0.16.0
statsmodels: None
IPython: 4.0.0
sphinx: None
patsy: None
dateutil: 2.4.2
pytz: 2015.6
bottleneck: None
tables: None
numexpr: None
matplotlib: 1.4.3
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: None
pymysql: None
psycopg2: None

**Comment by jorisvandenbossche** [comment]
Yes, this is not yet implemented. See https://github.com/pydata/pandas/issues/8711
