### ISSUE TITLE
BUG: missing pandas.version submodule

### ISSUE THREAD

**Issue by rgommers** [pydata/pandas#11381]
The public ``pandas.version`` submodule seems to have been removed without any deprecation warning beforehand in gh-10370. This causes a number of test failures for statsmodels.

**Comment by jreback** [comment]
``pandas.version`` was a private, undocumented version string module.

``pandas.__version__`` has always been (and is) the version tag. the module just implemented it (which is what changed here)

apologize @josef-pkt

**Comment by rgommers** [comment]
That's a very strange definition of private. Anything that doesn't start with an underscore and is in the main namespace is public simply by being there in pretty much any Python project I know. And in this case the ``write_version`` approach was simply copied from numpy/scipy, where the ``version`` module is definitely public. 

But well, it's up to you to decide here...
