### ISSUE TITLE
Numpy 1.10 compatibility with Pandas types 

### ISSUE THREAD

**Issue by bazeli** [pydata/pandas#11380]
Previously when using Pandas 0.16.2 and Numpy 1.9.2 one could run various numpy funcs on a pandas Series and have the result returned back typed as a Series (instead of an NDarray).   Example:

```python
import numpy as np
import pandas as pd
df = pd.DataFrame(np.random.randn(10, 1))
dfn = np.nan_to_num(df[0])
print "dfn type: %s" % type(dfn)
```
renders the following output `dfn type: <class 'pandas.core.series.Series'>`

However, when using Numpy 1.10.1, the result is now typed as an NDarray.   While this obviously is a result of numpy internal changes, does Pandas 0.17.x resolve/work around this issue?  So far I've only tested `np.nan_to_num` but perhaps there are other funcs that exhibit the same behaviour.

**Comment by jreback** [comment]
yeh, numpy I think numpy should be calling to be honest is not calling ``__array_wrap__``. ufuncs call it, but I don't know when/why other numpy funcs should call it.

I would file these as upstream bugs.
