### ISSUE TITLE
truncate() raises IndexError on large timeseries

### ISSUE THREAD

**Issue by saroele** [pydata/pandas#11382]
Hi,

I found a bug, tested on pandas 0.16 and 0.17.  On large time series, the ``truncate()`` method throws an IndexError.  Here's code that reproduces the bug:

```python
>>> import pandas as pd

>>> # Works fine on small timeseries:
>>> small = pd.Series(data=range(int(2e3)), index=range(int(2e3)))
>>> small.truncate()
>>> small.truncate(before=0, after=3e3)

>>> # IndexError thrown on large timeseries:
>>> big = pd.Series(data=range(int(2e6)), index=range(int(2e6)))
>>> big.truncate()
>>> big.truncate(before=0, after=3e6)
```

Info version: 

INSTALLED VERSIONS

commit: None
python: 2.7.8.final.0
python-bits: 64
OS: Linux
OS-release: 3.16.0-41-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8

pandas: 0.17.0
nose: 1.3.4
pip: 7.1.2
setuptools: 5.5.1
Cython: 0.20.2
numpy: 1.8.2
scipy: 0.14.0
statsmodels: None
IPython: 3.0.0
sphinx: 1.2.2
patsy: None
dateutil: 2.4.2
pytz: 2015.6
blosc: None
bottleneck: None
tables: None
numexpr: None
matplotlib: 1.3.1
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: 4.3.2
html5lib: None
httplib2: 0.9
apiclient: None
sqlalchemy: 0.9.7
pymysql: None
psycopg2: None

**Comment by jreback** [comment]
actually what you are doing should raise a ``TypeError`` in both cases.

the input arguments have to be dates.

These are converted to dates (but incorrectly).

want to do a pull-request to fix?

**Comment by saroele** [comment]
so for integer indexes, I should use ``.loc[start:end]`` ? 
And check myself first if the start and end are contained in the index (raises an IndexError if not)?

I'll think about the pull-request.  I'm not a pandas developer yet, but maybe it's a good start and it will teach me a thing or two :-)

**Comment by jreback** [comment]
integer indexing is via iloc

docs are http://pandas.pydata.org/pandas-docs/stable/indexing.html

**Comment by gliptak** [comment]
@jreback Could you describe the expected behaviour?
The description of ```def truncate(self, before=None, after=None, axis=None, copy=True)``` refers to dates, while the implementation (and the comment in ```truncate```) uses ```slice``` on ```ax``` (only converting ```before/after``` if ```ax.is_all_dates```)

**Comment by jreback** [comment]
if this is not a dateindex the this should raise

**Comment by gliptak** [comment]
There are a number of tests failing after changing this (as per below), as they use ```truncate``` on non datetime indexes ...

https://travis-ci.org/gliptak/pandas/jobs/125287589
```
======================================================================

ERROR: test_truncate (pandas.tests.test_panel.TestLongPanel)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/gliptak/pandas/pandas/tests/test_panel.py", line 48, in wrapper

    return func(self, *args, **kwargs)

  File "/home/travis/build/gliptak/pandas/pandas/tests/test_panel.py", line 2409, in test_truncate

    trunced = self.panel.truncate(start, end).to_panel()

  File "/home/travis/build/gliptak/pandas/pandas/core/generic.py", line 4622, in truncate

    raise TypeError("not ax.is_all_dates")

TypeError: not ax.is_all_dates

======================================================================

ERROR: test_truncate_fillna_bug (pandas.tests.test_panel.TestPanel)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/gliptak/pandas/pandas/tests/test_panel.py", line 1558, in test_truncate_fillna_bug

    result = self.panel.truncate(before=None, after=None, axis='items')

  File "/home/travis/build/gliptak/pandas/pandas/core/generic.py", line 4622, in truncate

    raise TypeError("not ax.is_all_dates")

TypeError: not ax.is_all_dates
```
https://travis-ci.org/gliptak/pandas/jobs/125287587
```
======================================================================

ERROR: testOLSWithDatasets_copper (pandas.stats.tests.test_ols.TestOLS)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/gliptak/pandas/pandas/stats/tests/test_ols.py", line 92, in testOLSWithDatasets_copper

    self.checkDataSet(sm.datasets.copper.load())

  File "/home/travis/build/gliptak/pandas/pandas/stats/tests/test_ols.py", line 150, in checkDataSet

    self.checkMovingOLS('rolling', x, y)

  File "/home/travis/build/gliptak/pandas/pandas/stats/tests/test_ols.py", line 209, in checkMovingOLS

    x_iter[k] = v.truncate(before=prior_date, after=date)

  File "/home/travis/build/gliptak/pandas/pandas/core/generic.py", line 4622, in truncate

    raise TypeError("not ax.is_all_dates")

TypeError: not ax.is_all_dates

======================================================================

ERROR: testOLSWithDatasets_scotland (pandas.stats.tests.test_ols.TestOLS)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/gliptak/pandas/pandas/stats/tests/test_ols.py", line 96, in testOLSWithDatasets_scotland

    self.checkDataSet(sm.datasets.scotland.load())

  File "/home/travis/build/gliptak/pandas/pandas/stats/tests/test_ols.py", line 150, in checkDataSet

    self.checkMovingOLS('rolling', x, y)

  File "/home/travis/build/gliptak/pandas/pandas/stats/tests/test_ols.py", line 209, in checkMovingOLS

    x_iter[k] = v.truncate(before=prior_date, after=date)

  File "/home/travis/build/gliptak/pandas/pandas/core/generic.py", line 4622, in truncate

    raise TypeError("not ax.is_all_dates")

TypeError: not ax.is_all_dates
```

**Comment by gliptak** [comment]
@jreback How do you see this moving forward? Thanks

**Comment by jreback** [comment]
@gliptak sorry this is not related to the timeseries. something in ``index.pyx`` is raising a ``IndexError`` when it should be a ``KeyError`` (on big index)

**Comment by gliptak** [comment]
@jreback From what I understand this issue discusses datetime index vs,. other indices, and is reproducible with small indices.

**Comment by jreback** [comment]
@gliptak not sure what you mean. its a non-datetime large index.

**Comment by gliptak** [comment]
@jreback OK, I read this again. I think https://github.com/pydata/pandas/pull/12921 will correct ```IndexError vs KeyError```. But there is a second issue here, ```truncate``` documentation states it is only applicable for ```DateTimeIndex```, and you stated earlier in this issue, that it should raise ```TypeError``` when ```non DateTimeIndex```. I patched to raise, but testcases in ```pandas``` codebase use truncate for ```non DateTimeIndex```.

**Comment by jreback** [comment]
@gliptak yeah, maybe just update the doc-string. its 'sort of legit' to do this with a non-datetimelike (a bit odd, but that's ok).

**Comment by jreback** [comment]
@gliptak you are right, we just need a validation test for this (and doc-update).

**Comment by gliptak** [comment]
I wasn't correct, https://github.com/pydata/pandas/pull/12921 takes a different path ... So what do you see raised for these?
```
big = pd.Series(data=range(int(2e6)), index=range(int(2e6)))
big.truncate() # NOOP?
big.truncate(before=0, after=3e6) # what to raise?
```

**Comment by jreback** [comment]
@gliptak that example is correct. I think something fixed this issue. I would just write a confirming test for this (validating the existing behavior).

**Comment by gliptak** [comment]
@jreback I modified docstring and added tests to highlight current behaviour. Please review.
