### ISSUE TITLE
TST: Travis-CI failing due to URL not found

### ISSUE THREAD

**Issue by Dr-Irv** [pydata/pandas#11418]
I fired off a Travis-CI set of jobs, and all the jobs fail at this point:
> try:
> $ conda install -n root _license
Fetching package metadata: .......Error: Could not find URL: http://conda.binstar.org/pandas/linux-64/

I have no clue what to do to fix this.

**Comment by jreback** [comment]
try again. conda had some issues.

**Comment by Dr-Irv** [comment]
@jreback I did and got the same error.  See https://travis-ci.org/Dr-Irv/pandas/jobs/86933696

**Comment by jreback** [comment]
try again.....I fixed (you need to rebase on master)
