### ISSUE TITLE
incorrect warning for pandas.io.pytables.HDFStore()

### ISSUE THREAD

**Issue by shadowleaves** [pydata/pandas#11423]
calling pandas.io.pytables.HDFStore() function (or its alias pd.HDFStore) will generate the following warnings in pandas 0.17, which is incorrect since HDFStore is not part of pandas.io.data or pandas-datareader package.

The pandas.io.data module is moved to a separate package (pandas-datareader) and will be removed from pandas in a future version.
After installing the pandas-datareader package (https://github.com/pydata/pandas-datareader), you can change the import ``from pandas.io import data, wb`` to ``from pandas_datareader import data, wb``.
  FutureWarning)

**Comment by jreback** [comment]
how so?

show a vanilla Python sessions that shows what you are doing

**Comment by shadowleaves** [comment]
it was raised by some other calling of pandas.io.data functions instead. no worries...sorry about the confusion

**Comment by jreback** [comment]
np
