### ISSUE TITLE
Dropping a column not working in 0.17

### ISSUE THREAD

**Issue by jelmelk** [pydata/pandas#11420]
I'm executing the following code:

    import pandas as pd
    
    df = pd.read_csv('2015-09-25.csv', header=None,\
                     names=['ID', 'ORIG', 'LAT', 'LONG', 'CITY', 'STATE', 'TIMESTAMP'], \
                     parse_dates=['TIMESTAMP'], \
                     usecols=['ORIG','LAT', 'LONG', 'CITY', 'STATE'])
    
    
    df1 = df[df['ORIG']==1]
    df1.drop(df1.columns[0], inplace=True)

However, the last line will give me this error in 0.17, but works fine with 0.16.2. The 0.17 version of `pandas` is being used with `python 3.5`, while `pandas 0.16.2` is being used with `python 3.4`.

    Traceback (most recent call last):
      File "C:/Users/Leb/Desktop/Python/test2.py", line 29, in <module>
        df.drop(df.columns[0], inplace=True)
      File "C:\Program Files\Python 3.5\lib\site-packages\pandas\core\generic.py", line 1616, in drop
        new_axis = axis.drop(labels, errors=errors)
      File "C:\Program Files\Python 3.5\lib\site-packages\pandas\core\index.py", line 2736, in drop
        raise ValueError('labels %s not contained in axis' % labels[mask])
    ValueError: labels ['ORIG'] not contained in axis

I've also tried `df1.drop('ORIG', inplace=True)` but the same problem arises. This presist ever with `df`.

Output of `df.columns` or `df1.columns` will show:

    Index(['ORIG', 'LAT', 'LONG', 'CITY', 'STATE'], dtype='object')
    Index(['ORIG', 'LAT', 'LONG', 'CITY', 'STATE'], dtype='object')

Adding `axis=1` will result in an additional error of:

SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

    SettingWithCopyWarning: 
    A value is trying to be set on a copy of a slice from a DataFrame
    
    See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
      df1.drop(df1.columns[0], axis=1, inplace=True)

These errors only show up with `python3.5` and `pandas 0.17`.

**Comment by jreback** [comment]
pls put a copy-pastable example

and pd.show_versions()

**Comment by TomAugspurger** [comment]
You're also trying to drop `ORIG` from the index, not the columns. Do you want `df1.drop(df1.columns[0] , axis=1)`?

**Comment by jelmelk** [comment]
@TomAugspurger I did that, I get the `SettingWithCopyWarning: ` error.

@jreback Here's a copy-pastable example:

    import pandas as pd
    import io
    
    data="""ORIG    LAT    LONG
    1    3.2    4.4
    1    2.8    7.5
    1    4.9    7.7
    0    5.4    5.8
    1    7.6    9.5"""
    
    df = pd.read_csv(io.StringIO(data), delimiter='\s+')
    
    df1 = df[df['ORIG']==1]
    
    df1.drop(df1.columns[0], axis=1, inplace=True)

The error seems to be when including `inplace=True`. The opration works fine when doing  `df1 = df1.drop('ORIG', axis=1)`

**Comment by jelmelk** [comment]
INSTALLED VERSIONS
------------------
commit: None
python: 3.5.0.final.0
python-bits: 64
OS: Windows
OS-release: 
machine: AMD64
processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None

pandas: 0.17.0
nose: None
pip: 7.1.2
setuptools: 18.2
Cython: None
numpy: 1.9.3
scipy: 0.16.0
statsmodels: None
IPython: None
sphinx: None
patsy: None
dateutil: 2.4.2
pytz: 2015.6
blosc: None
bottleneck: None
tables: None
numexpr: None
matplotlib: 1.5.0rc2
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: None
pymysql: None
psycopg2: None
None

**Comment by jreback** [comment]
@jelmelk this is as expected.

you are trying to drop a column from a frame that is essentially a fitler of another. It *might* work depending on the dtypes, but you would need to copy it first.

**Comment by jelmelk** [comment]
@jreback thank you for the feedback. It was initially confusing as to why the same code works with 0.16.2 but not with 0.17

**Comment by jreback** [comment]
IIRC some bug fixes, you need to pay attention the ``SettingWithCopyWarnigns`` they are there for a reason. further, in general ``inplace`` is a bad idea.
