### ISSUE TITLE
Add `na=` parameter to str.isalnum() and other tests

### ISSUE THREAD

**Issue by Will-So** [pydata/pandas#11421]
I have a use case where I want to select all the rows in a column that are not numbers:

`lc.loc[lc.id.str.isalpha()]`

Some rows in the `id` column are nan so I get a value error:

`ValueError: cannot index with vector containing NA / NaN values`

The work around is to use:

`lc[lc.id.str.contains('[A-z]', na=False)]`

 I can provide a reproducible example if desired. 

It would be nice if there were an na parameter in the string tests as well. E.g., `lc.loc[lc.id.str.islapha(na=False)]`.

On a related note, the the pattern `fillna(False)` to avoid this error doesn't seem to be documented well.  My understanding is that this is just an arbitrary value and can easily have been True or 'apple'. Is this correct? 

I'd be happy to add this to the documentation if my understanding is accurate.

**Comment by jreback** [comment]
@Will-So if you have mixed actual ``objects`` e.g. floats and strings you are doing something odd, but in any event

```
lc = lc.astype(str)
lc.loc[lc.id.str.isalpha()]
```

is what you should do

**Comment by Will-So** [comment]
Thanks for the quick response. 

I'm finding all of the rows with letters so I can then delete them and then I can convert the column to `int`. That was the most straightforward way I could think to do it but maybe I was doing it in a weird way. 

Your solutions works too. Feel free to close.

**Comment by jreback** [comment]
the ``.str`` functions *should* raise if they encounter a non-string. That's part of the API.
