### ISSUE TITLE
Series.str.cat() with NaN in series returns NaN, rather than ignoring NaN

### ISSUE THREAD

**Issue by hack-c** [pydata/pandas#11435]
I find this surprising as the rest of the pandas `Series.str.*` API ignores NaN values.

```python
In [1]: import pandas as pd

In [2]: import numpy as np

In [3]: pd.__version__
Out[3]: u'0.17.0'

In [4]: s = pd.Series(['asdf','sdfg',np.nan,'qwer','wert'])

In [5]: s.str.cat(sep=' ')
Out[5]: nan
```
I think this should return
```python
In [5]: s.str.cat(sep=' ')
Out[5]:'asdf sdfg qwer wert'
```

**Comment by hack-c** [comment]
Didn't read the docs closely enough-- the na_rep keyword more or less takes care of this. It's still a little strange that even if you set 
```python
In [5]: s.str.cat(sep=' ', na_rep='')
Out[6]: 'asdf sdfg  qwer wetr'
```
You get a double sep around the NaN. Easy to fix with a regex, but shouldn't NaN just be ignored?

**Comment by hack-c** [comment]
I actually think `Series.str.cat()` should ignore NaN by default, to comply with expected behavior for the rest of the API. But I'm curious if there's a reason for why this is a bad idea.

**Comment by Winterflower** [comment]
I think this would benefit from an additional doc example involving ```na_rep```. I just read the API doc and it's not very clear from the explanation that doing ```Series.str.cat()``` without specifying anything for ```na_rep```.

**Comment by hack-c** [comment]
That sounds like a good approach. I can do a pull request for the docs. I opened another issue (#11334) for `str_cat` as well that I haven't gotten around to yet that might also be best solved with a doc example as opposed to changing internals.

**Comment by jorisvandenbossche** [comment]
I agree it seems more logical to ignore the NaN value by default.
