### ISSUE TITLE
Serious Floating point error v 0.16.2 and v0.17

### ISSUE THREAD

**Issue by apiszcz** [pydata/pandas#11454]
Python 3.4.3/64bit, Pandas 0.16.2 or 0.17

The operation is a addition. The results of the first two rows are correct most of the time, on occasion a value 1.5-315 appears. Every test performed with same input. Fail rate is about 3-5% of the time.

df['v1']+=10.0

I copied the dataframe results to numpy and perform the same addition with same values and it works correctly every time.

npyarr=df.reset_index().values
npyarr[:,1]+=10.0

After a few weeks of noticing these symptoms it appears to only affect the first two rows every time, the data frame has thousands of rows.

**Comment by jreback** [comment]
well, not sure that it is even pandas issue here. do you have ``bottleneck``,``numexpr`` installed? what does the frame look like. in what cases does the error happen? 

this bug report is lacking much information.

**Comment by apiszcz** [comment]
I disabled numexpr and bottleneck getting same error.

**Comment by jreback** [comment]
w/o a copy pastable example it's not clear what the problem is

**Comment by jreback** [comment]
if u want to post something that enables one to repro then all ears
