### ISSUE TITLE
null character '\x00' for lineseparator in read_csv not working

### ISSUE THREAD

**Issue by mas-dse-nbondugu** [pydata/pandas#11466]
pd.read_csv("x.txt", lineseparator="\x00") is still separating based on carriage return.
I have a file which has lot of \0 which are to be treated as line separator.

But above code is not separating based on '\0'.
Any fix for this?

**Comment by jreback** [comment]
well, the argument name is ``lineterminator``.

**Comment by jreback** [comment]
docs are [here[(http://pandas.pydata.org/pandas-docs/stable/io.html#csv-text-files)
