### ISSUE TITLE
parsers.py docs need to link to more complete documentation for iterator and chunksize

### ISSUE THREAD

**Issue by silentquasar** [pydata/pandas#11464]
I was very confused about the purpose of the iterator and chunksize parameters when looking at the [help for read_csv](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html). It wasn't until I Google'd upon [the docs for IO Tools](http://pandas.pydata.org/pandas-docs/stable/io.html) that I began to understand.

I propose that links to the IO Tools docs be included in the docstrings for the iterator and chunksize parameters.

**Comment by jreback** [comment]
I guess this could have a link the on-line docs (near the top of it I suppose).

want to do a pull-request?

**Comment by jreback** [comment]
closed by #11505
