### ISSUE TITLE
read_excel documentation does not mention names keyword

### ISSUE THREAD

**Issue by PBrockmann** [pydata/pandas#11468]
http://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_excel.html
does not mention the keyword "names"

```python
import pandas as pd
df = pd.read_excel('yourfile.xls', header=None, names=['Attribut', 'Value'])
```
is equivalent but simpler to

```python
df = pd.read_excel(file, sheetname='Metadata', header=None)
df.columns = ['Attribut', 'Value']
```
names keyword is defined as in read_csv
names: List of column names to use as column names. To replace header existing in file, explicitly pass header=0.

**Comment by jreback** [comment]
suppose that's reasonable. a number of parameters are actually passed thru to ``read_csv``.

a pull-request to add to the doc-string (and as a named parameter) would be helpful.
