### ISSUE TITLE
Time Series / Date functionality Holiday lookup - possible bug

### ISSUE THREAD

**Issue by vlmercado** [pydata/pandas#11477]
When trying to confirm if a specific date is an observed holiday using the specific date for the start and end range, the attempt fails to confirm a known observed holiday. It works as expected if I change the end date. When I try to use the same start and end date again, it works every time.

In 2015, the July 4th holiday was observed on July 3rd. Since a BDay() offset ignores holidays, a confirmation of an observed holiday failed when using July 3, 2015 for the start and end dates. See code below:

```python
from datetime import datetime
from pandas.tseries.holiday import get_calendar, HolidayCalendarFactory, GoodFriday

USFedCal = get_calendar('USFederalHolidayCalendar')

USFedCal.holidays(datetime(2015,7,3), datetime(2015,7,3)) # <-- same start and end dates
DatetimeIndex([], dtype='datetime64[ns]', freq=None)

USFedCal.holidays(datetime(2015,7,3), datetime(2015,7,6)) # <-- different start and end dates
DatetimeIndex(['2015-07-03'], dtype='datetime64[ns]', freq=None)

USFedCal.holidays(datetime(2015,7,3), datetime(2015,7,3)) # <-- same start and end dates
DatetimeIndex(['2015-07-03'], dtype='datetime64[ns]', freq=None)
```

**Comment by jreback** [comment]
hmm, that does seem odd.

cc @rockg

**Comment by rockg** [comment]
This is a little ugly.  Basically since the real holiday is on the 4th, the first call doesn't get the 4th to apply its observance rule to the 3rd (as it's not in the range).  The second call spans the 4th so the observance rule can be applied and the third call uses the cache from the second call.  I suppose a simple solution is to always move the end date out a few days so that observance rules can be applied and then filtered for the given date range.

**Comment by rockg** [comment]
That seems to work fine.  Will submit the PR tomorrow morning as I came across a few more things that were odd.

**Comment by rockg** [comment]
This seems a little counterintuitive but it makes sense to me:

```
USFederalHolidayCalendar().holidays(datetime(2015, 7, 3), datetime(2015, 7, 3))
DatetimeIndex(['2015-07-03'], dtype='datetime64[ns]', freq=None)

USFederalHolidayCalendar().holidays(datetime(2015, 7, 4), datetime(2015, 7, 4))
Index([], dtype='object')
```
