### ISSUE TITLE
rolling_* function timeseries usage

### ISSUE THREAD

**Issue by huaiweicheng** [pydata/pandas#11472]
here is my problem.
What I have is a DataFrame as follows:

    df:
    
    2013-10-24      1
    2013-10-25      2
    2013-11-27      3 
    2013-11-28      4
    2013-12-01      5 
    2013-12-02      6

What I want is a DataFrame such like this:

rolling_mean(df, window='1M'):

    2013-10      1.5
    2013-11      3.5
    2013-12      5.5 

rolling_mean(df, window='2M'):

    2013-10      NAN
    2013-11      2.5
    2013-12      4.5 

rolling_mean(df, window='3M'):

    2013-10      NAN
    2013-11      NAN
    2013-12      3.5 

rolling_mean(df, window='1Y'):

    2013-10      NAN
    2013-11      NAN
    2013-12      NAN

where 1M is '1 month', 2M is '2 months'. The window is not a int value, but a time interval such as '1M', '3M', '1Y' and so on. The function could groupby the dataframe by the time unit such as 'M', 'Y', and then rolling the dataframe through the number before the time unit such as 1, 3...

I need a rolling function such like this?
Could anybody help me? Did I give a clear description?
Many thanks.
p.s.
The new dataframe's Freq is the time unit such as 'M' or 'Y', which is not related to the number.

**Comment by jreback** [comment]
```
In [19]: df
Out[19]: 
       dates  value
0 2013-10-24      1
1 2013-10-25      2
2 2013-11-27      3
3 2013-11-28      4
4 2013-12-01      5
5 2013-12-02      6

In [16]: pd.rolling_mean(df.set_index('dates').resample('1M'),window=1)
Out[16]: 
            value
dates            
2013-10-31    1.5
2013-11-30    3.5
2013-12-31    5.5

In [17]: pd.rolling_mean(df.set_index('dates').resample('1M'),window=2)
Out[17]: 
            value
dates            
2013-10-31    NaN
2013-11-30    2.5
2013-12-31    4.5

In [18]: pd.rolling_mean(df.set_index('dates').resample('1M'),window=3)
Out[18]: 
            value
dates            
2013-10-31    NaN
2013-11-30    NaN
2013-12-31    3.5
```

**Comment by huaiweicheng** [comment]
Helpful. Many thanks. New to pandas.

**Comment by huaiweicheng** [comment]
@jreback 
I still have a puzzle.
I need to implement such a function which could calculate rolling standard deviation of every day, not resampled by month, but the window step unit is weighed by month.

In this scenario, 
what I have is also 
df:
    
    2013-10-24      1
    2013-10-25      2
    2013-11-27      3 
    2013-11-28      4
    2013-12-01      5 
    2013-12-02      6

pd.rolling_std(df.resample('1M'),window=1):

The result is 
    
    2013-10    NAN
    2013-11    NAN 
    2013-12    NAN

what I really is a dataframe like this(window = 1 ): 

    2013-10    0.5
    2013-11    0.5 
    2013-12    0.5

The first 0.5 is the standard deviation which can be calculated by np.sqrt([1,2]) from October.
Also 0.5 from the others are from [3,4] and [5,6].
However, no matter what how = 'xxx' method in the resample function, the result is not right.
The objective result of 2months is, 

df (window = 2 ): 

    2013-10    NAN
    2013-11    1.1180 
    2013-12    1.1180

The first 1.1180 is the standard deviation which can be calculated by np.sqrt([1,2,3,4]) from October and November.
1.1180 from 2013-12 are from [3,4,5,6] of 2013-11 and 2013-12.


p.s. 
The standard deviation is one of my functions which I want to implement rolling...

**Comment by jreback** [comment]
a std deviation of a 1 window is always NaN. doesn't make sense.

```
In [49]: df.set_index('dates').resample('1M')[0:2]      
Out[49]: 
            value
dates            
2013-10-31    1.5
2013-11-30    3.5

In [50]: df.set_index('dates').resample('1M')[0:2].std()
Out[50]: 
value    1.414214
dtype: float64

In [51]: pd.rolling_std(df.set_index('dates').resample('1M'),window=2)
Out[51]: 
               value
dates               
2013-10-31       NaN
2013-11-30  1.414214
2013-12-31  1.414214
```

**Comment by huaiweicheng** [comment]
You may misunderstand my puzzle.
The standard deviation in my dataframe is calculated by **daily** value, not **monthly** value.
For example, 
2013-10 np.sqrt([1,2]) not np.sqrt([1])

**Comment by jreback** [comment]
you can simply play around as I am not sure what you are after

**Comment by huaiweicheng** [comment]
Here is my code..

    df:
    
    2013-10-24      1
    2013-10-25      2
    2013-11-27      3 
    2013-11-28      4
    2013-12-01      5 
    2013-12-02      6

    context = []

    def myfunc(array_like):
        context.append(array_like.values)
        a =[]
        for item in context[-3:]:
            a.extend(item)
        return np.std(a)

    print df.resample('1M', how = myfunc)

The result is 

                   value
    datetime            
    2013-10-31  0.500000
    2013-11-30  1.118034
    2013-12-31  1.707825

0.500000 = np.std([1,2])
1.118034 = np.std([1,2,3,4])
1.707825 = np.std([1,2,3,4,5,6])

I think it is not a nice method...

**Comment by jreback** [comment]
docs are here: http://pandas.pydata.org/pandas-docs/stable/computation.html#moving-rolling-statistics-moments

Stackoverflow is a better resource for questions like this.

**Comment by lycanthropes** [comment]
there is no correct answer for rolling with monthly window
