### ISSUE TITLE
datetime slices with multiindex unexplained behaviour

### ISSUE THREAD

**Issue by thrasibule** [pydata/pandas#11474]
I don't think this is related to  #9732 or #10331, but maybe I'm missing something.

```python
index = pd.MultiIndex.from_product([pd.date_range('2015-01-01', '2015-04-01', freq='8H'), ['A', 'B', 'C']], names=['level1', 'level2'])
s = pd.Series(np.random.randn(813), index=index)
```
Now I'm trying to select a slice from s as follows:

```
idx = pd.IndexSlice
s_small = s.loc[idx['2015-01-01':'2015-01-08', :]]
```
Now this is very strange, if I select a slice smaller than 8 days then it  works fine, but for anything bigger the selection doesn't work:

```
>>> s.loc[idx['2015-01-01':'2015-01-08', :]].shape #(8 days times 3 8h periods times 3 levels)
(72,)
>>> s.loc[idx['2015-01-01':'2015-01-09', :]].shape #???
(569,)
>>>
```

**Comment by jreback** [comment]
this is exactly #9732 

partial string slicing in a multi-index is just not implemented
```
In [21]: s.loc[idx[pd.Timestamp('2015-01-01'):pd.Timestamp('2015-01-09'), :]].shape
Out[21]: (75L,)
```

**Comment by thrasibule** [comment]
Thanks for the explicit workaround. I got confused because it was working fine for some slices.

**Comment by jreback** [comment]
yeh, partial string slicing is for 'non-production' only :smile: e.g. better to be explicit about your bounds
