### ISSUE TITLE
fillna(method='ffill') fills all NA values with the same value.

### ISSUE THREAD

**Issue by languitar** [pydata/pandas#11482]
I have a series with a lot of NA values. However, there are still some valid observations in between. This can be seen in this plot:
![series-na](https://cloud.githubusercontent.com/assets/1336287/10843580/258a4852-7efa-11e5-9369-378ee5fed160.png)
If I now to:
```python
s.fillna(method='ffill').plot()
```
I end up with this result:
![series-filled](https://cloud.githubusercontent.com/assets/1336287/10843594/3a37ac22-7efa-11e5-87d8-79f77213d82f.png)

According to the documentation ffill should "propagate last valid observation forward to next valid". This is not what I see here.

The series I am testing with can be grabbed here (not allowed to upload on github :/):
http://wikisend.com/download/956820/series.msg

**Comment by jorisvandenbossche** [comment]
Can you show the output of `pd.show_versions()` ? 
Further, reading the file you provided gives an error for me, so I can't reproduce. Can you show some actual values (output of some rows before and after the incorrect filling to show the problem) instead of only a figure?

**Comment by languitar** [comment]
Sigh, alright, I found the issue... The index wasn't sorted. ffill doesn't respect the times but plot does. This is actually quite confusing from a user perspective. Maybe issuing a warning when having non-sorted DateTimeIndexes could help?
