### ISSUE TITLE
segfault with matplotlib 1.5.0

### ISSUE THREAD

**Issue by sebhahn** [pydata/pandas#11487]
The following example will lead to a segfault error (with pandas 0.17.0 and matplotlib 1.5.0)

`import pandas as pd`
`import matplotlib.pyplot as plt`
`df = pd.DataFrame({'data': range(10)})`
`df.plot()`
`plt.show()`

**Comment by jreback** [comment]
pls show

pd.show_versions()

**Comment by sebhahn** [comment]
INSTALLED VERSIONS
------------------
commit: None
python: 2.7.6.final.0
python-bits: 64
OS: Linux
OS-release: 3.19.0-31-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

pandas: 0.17.0
nose: 1.3.7
pip: 7.1.2
setuptools: 18.4
Cython: 0.23.4
numpy: 1.10.1
scipy: 0.16.0
statsmodels: 0.6.1
IPython: 4.0.0
sphinx: 1.3.1
patsy: 0.4.0
dateutil: 2.4.2
pytz: 2015.7
blosc: None
bottleneck: None
tables: None
numexpr: None
matplotlib: 1.5.0
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: None
pymysql: None
psycopg2: None
None

**Comment by TomAugspurger** [comment]
Can you post your versions of all matplotlib's [required dependencies](http://matplotlib.org/users/installing.html#required-dependencies)?

**Comment by sebhahn** [comment]
OS: Ubuntu 14.04.3 LTS (Trusty Tahr)

python: 2.7.6
numpy: 1.10.1
dateutil: 2.4.2
pyparsing: 2.0.5
pytz: 2015.7
cycler: 0.9.0

freetype-config --version: 17.1.11
libpng12-config --version: 1.2.50

**Comment by TomAugspurger** [comment]
And does just plotting with matplotlib produce the segfault?

```python
import matplotlib.pyplot as plt
import numpy as np

plt.plot(range(10))
plt.show()
```

**Comment by sebhahn** [comment]
works normal

**Comment by tacaswell** [comment]
How did you install matplotlib + pandas?

I can not reproduce this using a conda environment created via

```
conda create python=2.7 pandas matplotlib -c conda-forge
```

**Comment by sebhahn** [comment]
I've created a fresh environment and installed pandas and matplotlib.

`mkvirtualenv test_matplotlib`

This is the code I used to create a plot:

```python
>>> import matplotlib.pyplot as plt
>>> import pandas as pd
>>> x = pd.DataFrame({"data": range(10)})
>>> x.plot()
<matplotlib.axes._subplots.AxesSubplot object at 0x7f82e225ff90>
>>> plt.show()
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1489, in __call__
    return self.func(*args)
  File "/home/shahn/.virtualenvs/test_matplotlib/local/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 283, in resize
    self.show()
  File "/home/shahn/.virtualenvs/test_matplotlib/local/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 355, in draw
    tkagg.blit(self._tkphoto, self.renderer._renderer, colormode=2)
  File "/home/shahn/.virtualenvs/test_matplotlib/local/lib/python2.7/site-packages/matplotlib/backends/tkagg.py", line 30, in blit
    id(data), colormode, id(bbox_array))
TclError
```
And the following leads to
```python
>>> x['data'].plot()
<matplotlib.axes._subplots.AxesSubplot object at 0x7f82e14adc50>
>>> plt.show()
[1]    7748 segmentation fault  python
```

```python
>>> pandas.__version__
u'0.17.0
>>> matplotlib.__version__
'1.5.0'
```

Creating a standard  miniconda (3.16.0) environment using pyenv

package | version | 
------------ | -------------|------------ 
cairo          |           1.12.18       |                5  
fontconfig   |             2.11.1             |           5  
freetype     |             2.5.5               |          0  
libgfortran   |            1.0                 |          0  
libpng          |          1.6.17             |           0  
libxml2         |          2.9.2              |           0  
matplotlib      |          1.4.3            |   np110py27_2  
numpy           |          1.10.1         |          py27_0  
openblas        |          0.2.14       |                 3  
openssl           |        1.0.2d        |                0  
pandas        |            0.17.0       |       np110py27_0  
pip                |       7.1.2            |        py27_0  
pixman          |          0.26.2     |                   0  
py2cairo         |         1.10.0               |    py27_2  
pyparsing        |         2.0.3               |     py27_0  
pyqt               |       4.11.4                |   py27_0  
python            |        2.7.10             |           2  
python-dateutil   |        2.4.2          |          py27_0  
pytz         |             2015.7            |       py27_0  
qt             |           4.8.7                |         1  
readline       |           6.2              |             2  
setuptools     |           18.4          |           py27_0  
sip              |         4.16.9           |        py27_0  
six               |        1.10.0          |         py27_0  
sqlite            |        3.8.4.1       |                1  
tk                  |      8.5.18         |               0  
wheel            |         0.26.0     |              py27_1  
zlib                 |     1.2.8         |                0

and updating matplotlib to 1.5

```
    Uninstalling pyparsing-2.0.3:
      Successfully uninstalled pyparsing-2.0.3
  Found existing installation: matplotlib 1.4.3
    Uninstalling matplotlib-1.4.3:
      Successfully uninstalled matplotlib-1.4.3
Successfully installed cycler-0.9.0 matplotlib-1.5.0 pyparsing-2.0.5
```

However this time it works:

```python
>>> import matplotlib
>>> import matplotlib.pyplot as plt
>>> import pandas as pd
>>> pd.__version__
u'0.17.0'
>>> matplotlib.__version__
'1.5.0'
>>> x = pd.DataFrame({"data":range(10)})
>>> x.plot()
<matplotlib.axes._subplots.AxesSubplot object at 0x7f84b7be6f50>
>>> plt.show()
>>> x['data'].plot()
<matplotlib.axes._subplots.AxesSubplot object at 0x7f84d0614090>
>>> plt.show()
```

Do I need to update an external library, if I try to install everything with pip?

**Comment by ikajic** [comment]
I might be having the same problem. I have two virtual environments, one (`env1`) uses matplotlib installed from source, the other (`env2`) `pip install`-ed matplotlib. The version of  matplotlib is the same in both environments  and pandas is also installed from pip in both cases.

In `env1` this script:
```python
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt

print(pd.__version__)
print(matplotlib.__version__)

x = pd.DataFrame({"data":range(10)})
x['data'].plot()

plt.show()
```
returns:
```python
$ python miniscript.py 
0.17.0
1.5.0
Segmentation fault
```

whereas running the same script in the other environment `env2` works just fine.
My guess is that the installation from source is causing some problems.

**Comment by tacaswell** [comment]
@ikajic What OS?  Can someone who can reproduce this run it with gdb?

attn @mdboom

**Comment by ikajic** [comment]
```
$ uname -a
Linux ctn05 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u6 (2015-11-09) x86_64 GNU/Linux
```

**Comment by mdboom** [comment]
@ikajic: I also can't reproduce in a similar environment.  (Fedora 23, conda python, with matplotlib 1.5.0 installed from source).

Can you try getting us a `gdb` backtrace?

From the directory where you have `miniscript.py`, run

```
gdb `which python`
```

at the commandline

Then type `run miniscript.py`.  After it runs and segfaults, type `bt` and post all of the output here.

**Comment by ikajic** [comment]
Got it: https://gist.github.com/ikajic/da05205f5f8fac091c44#file-gistfile1-txt

**Comment by ikajic** [comment]
I managed to resolve this by cleaning the matplotlib repository and re-building [as suggested in matplotlib issues]( https://github.com/matplotlib/matplotlib/issues/3383). So it doesn't seems to be a pandas issue.
