### ISSUE TITLE
AssertionError: Number of Block dimensions (1) must equal number of axes (2)

### ISSUE THREAD

**Issue by ShivangiM** [pydata/pandas#11494]
The following code throws AssertionError
df = pd.DataFrame({"x-1": X[:,0], "x-2": X[:,1], "label": np.where(y==1, "Driver's License", "Check")})

**Comment by TomAugspurger** [comment]
What is `X`?

**Comment by ShivangiM** [comment]
X = pca.fit_transform(data)
and y is are the label,  def extrct_labels(filename):

    n = len(filename)
    y = np.zeros(n,dtype = np.int32)

    for i,filename in enumerate(filename): 
        # If 'check' string is in file name assign '0'
        if 'check' in str(filename):
            y[i] = 0
        else:
            y[i] = 1
    return y

**Comment by TomAugspurger** [comment]
Can you give a copy-pastable example that reproduces the problem?

**Comment by ShivangiM** [comment]
Ya sure:
from scipy.misc import imread
import numpy as np
import os
import numpy as np
from sklearn.decomposition import RandomizedPCA
import pandas as pd
import pylab as pl
img_dir = 'pics/'
pics = [img_dir+ f for f in os.listdir(img_dir)]
def extrct_labels(filename):

    n = len(filename)
    y = np.zeros(n,dtype = np.int32)

    for i,filename in enumerate(filename): 
        # If 'check' string is in file name assign '0'
        if 'check' in str(filename):
            y[i] = 0
        else:
            y[i] = 1
    return y
data = []
for pic in pics:
    img = imread(pic)
    img = img.flatten()
    data.append(img)

data = np.array(data)
pca = RandomizedPCA(n_components=2)
X = pca.fit_transform(data)
df = pd.DataFrame({"x-1": X[:,0], "x-2": X[:,1], "label": np.where(y==1, "Driver's License", "Check")})

**Comment by shoyer** [comment]
@ShivangiM we don't have your directory of images handy, and using scikit-learn obscures the origin of this problem (see http://sscce.org/). Please try reproducing the issue using only numpy and pandas, if possible.

**Comment by jreback** [comment]
pls provide a copy-pastable example that is runnable w/o your data (and ideally is just write before the DataFrame creation step).
