### ISSUE TITLE
Pandas display.date option not working

### ISSUE THREAD

**Issue by ProfPh** [pydata/pandas#11501]
pandas: 0.17.0
python: 3.5.0.final.0

```
import pandas as pd

list1 = {"Date":["01/11/15"]} #1st November 2015
pd.set_option('display.date_dayfirst', True)
#pd.set_option('display.date_yearfirst', False)
df = pd.DataFrame(list1, columns=['Date'])
df['Date'] = pd.to_datetime(df['Date'], dayfirst = [True])
df1 = df.sort_values(['Date'], ascending=[True])

print(df1)
```

Prints: 
```
        Date
0 2015-11-01
```

Setting both options to ```True``` and ```False``` doesn't work nor does only setting one. Printing df and df1 have the same result. And not specifying a ```dayfirst``` argument in ```pd.to_datetime``` doesn't change anything.

**Comment by jreback** [comment]
I don't think the actual display part of this was ever implemented.

the parsing is (though not tested with the actual option value).

pull-requests welcome on both counts!

**Comment by ProfPh** [comment]
So, currently, the only way to display sorted dates is Y-m-d ?

**Comment by jreback** [comment]
no this is just a display issue you can sort in many ways

**Comment by ProfPh** [comment]
Yeah that's what I meant, there's no way of displaying a sorted dataframe in other dateformats?

**Comment by jreback** [comment]
no, that's why its marked as an enhancement. though you could convert to string (e.g. via ``.strftime``) if you wanted to just display it that way.

**Comment by ProfPh** [comment]
If it's a string then it can't be sorted? But if it's a datetime object then the format must be the default one? Damn, that sucks :/

**Comment by jreback** [comment]
you are missing the point. you can sort however you want. this is just a display issue only.

**Comment by ProfPh** [comment]
I think we're on different pages too. If I have a sorted dataframe and I want to export this to a .csv or a .xlsx, I don't have any way of changing how the date format is displayed? If I wanted it to be shown as 01/11/15 instead of 2015-11-01 there's no way of doing that currently?

**Comment by ProfPh** [comment]
Apologies, I see what you were talking about. In the code I put, if I had just changed the format after I sorted it, then I would have had no problems,

**Comment by joooeey** [comment]
How is this completed? The example given in the OP still doesn't work as implied by the [docs for Pandas options](https://pandas.pydata.org/docs/user_guide/options.html).
