### ISSUE TITLE
Mixing CustomBusinessDay and BusinessHours Classes

### ISSUE THREAD

**Issue by r-pluss** [pydata/pandas#11514]
Is it currently possible to combine the CustomBusinessDay and BusinessHour classes in any way?

My use-case is that I want to be able to create a SubClass of BusinessHour that would skip over all time occurring in the 'holidays' or outside the 'weekmask' defined within a CustomBusinessDay instance. This would be incredibly useful for me, and, I suspect, many others.

I have currently tried subclassing BusinessHour and replacing the next_bday attribute with in an instance of a CustomBusinessDate. Unfortunately, it does not rollforward past days defined as holidays, and seems to function the same as a typical BusinessDay object.

If such functionality is not currently available, please consider this a feature request.

**Comment by sinhrks** [comment]
Currently no.

I **assume** it should work by replacing ``BusinessDay`` to ``CustomBusinessDay`` used in ``BusinessHour``. Pull request is appreciated!
