### ISSUE TITLE
create DataFrame from dict with different data type, cat't change value then.

### ISSUE THREAD

**Issue by xmduhan** [pydata/pandas#11510]
## I try to make a DataFrame from a dict, and need to change it's value then. I find when dict as different data type value, It does't work.

# dict has same data type, It works.
from pandas import DataFrame  
a = {'a': 1, 'b': 1}
df = DataFrame([a])
print df
rec = df.ix[0]
rec['a'] = 100
print df

out:
   a  b
0  1  1
     a  b
0  100  1

# dict has different data type, go wrong.
from pandas import DataFrame
a = {'a': 1, 'b': '1'}
df = DataFrame([a])
print df
rec = df.ix[0]
rec['a'] = 100
print df

out:
   a  b
0  1  1
   a  b
0  1  1

-c:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

**Comment by TomAugspurger** [comment]
That's working as expected. Have a look at the documentation in the [warning message](http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy), which explains that

> A multi-dtyped DataFrame (meaning it has say float and object data), will almost always yield a copy

```python
rec = df.copy()
rec.loc[0, 'a'] = 100
```

or if you want to modify `df`:

```python
df.loc[0, 'a'] = 100
```

**Comment by xmduhan** [comment]
@TomAugspurger Thank you! I got it!
