### ISSUE TITLE
Idea: Improving Bootstrap

### ISSUE THREAD

**Issue by chrisjluc** [pydata/pandas#11513]
I think we could improve bootstrap functionality because what we have [now](https://github.com/pydata/pandas/blob/master/pandas/tools/plotting.py#L577) is limited in terms of customization and functionality. Right now we only calculate mean, median and mid ranges and basically plot them all in the same figure.

 It would be nice to be able to pass in specific stat functions, have customizable parameters such as number of samples and sample sizes and different calculation methods, such as this [library](https://github.com/cgevans/scikits-bootstrap/blob/master/scikits/bootstrap/bootstrap.py#L20).

**Comment by TomAugspurger** [comment]
We've been cutting back on statistics and plotting to focus more on the core of pandas, so I doubt you'll find much interest in expanding that function. This one is statistics *and* plotting, so it's a hard sell :)

https://github.com/bashtage/arch#bootstrap also has nice support for bootstrapping.

**Comment by jreback** [comment]
out of scope of pandas. you can make a feature request to ``statsmodels``.
