### ISSUE TITLE
DataFrame.sum() behavior different in OSX

### ISSUE THREAD

**Issue by fernavid** [pydata/pandas#11528]
When I run this code in OSX, I get 0's for rows that only have NaN in them:

```
import pandas as pd
import numpy as np

df = pd.DataFrame.from_dict({'AAPL': [1,2,3,4,5,6,np.nan,np.nan], 'Date': [1,2,3,4,5,6,7,8]})
df = df.set_index('Date')
df.sum(axis=1)
```
```
Date
1    1
2    2
3    3
4    4
5    5
6    6
7    0
8    0
dtype: float64
```

When running in Ubuntu for example I get the expected output:

```
Date
1     1
2     2
3     3
4     4
5     5
6     6
7   NaN
8   NaN
dtype: float64
```

The only difference I have been able to attribute this to is the OS. They are both using 0.17 pandas and numpy 1.10. Can anyone replicate this error?

**Comment by maximilianr** [comment]
dupe https://github.com/pydata/pandas/issues/9422? (+ https://github.com/pydata/pandas/issues/11498)

**Comment by fernavid** [comment]
Yes it seems that this is the same issue and bottleneck is the variable between my two environments. Thanks.
