### ISSUE TITLE
Feature request : recognizable exception when calling read_csv on empty stream

### ISSUE THREAD

**Issue by windancert** [pydata/pandas#11530]
For me it would be extremely helpful if the read_csv function would raise a recognizable exception when it is called with an empty stream. Currently I'm checking the type and message of the exception raised to guess if this situation has occurred. It would be less fragile it an exception of a specific type would be raised.

Examples of the exception raised in different version of pandas

> \>>> import pandas
> \>>> from StringIO import StringIO
> \>>> pandas.read_csv(StringIO())
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "<some path to>\pandas\io\parsers.py", line 474, in parser_f
>     return _read(filepath_or_buffer, kwds)
>   File "<some path to>\pandas\io\parsers.py", line 250, in _read
>     parser = TextFileReader(filepath_or_buffer, **kwds)
>   File "<some path to>\pandas\io\parsers.py", line 566, in __init__
>     self._make_engine(self.engine)
>   File "<some path to>\pandas\io\parsers.py", line 705, in _make_engine
>     self._engine = CParserWrapper(self.f, **self.options)
>   File "<some path to>\pandas\io\parsers.py", line 1072, in __init__
>     self._reader = _parser.TextReader(src, **kwds)
>   File "pandas\parser.pyx", line 512, in pandas.parser.TextReader.__cinit__ (pandas\parser.c:4830)
> ValueError: No columns to parse from file
> \>>> pandas.version.version
> '0.16.2'
> \>>>

and

> \>>> import pandas
> \>>> from StringIO import StringIO
> \>>> pandas.read_csv(StringIO())
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "<some path to>\pandas\io\parsers.py", line 420, in parser_f
>     return _read(filepath_or_buffer, kwds)
>   File "<some path to>\pandas\io\parsers.py", line 218, in _read
>     parser = TextFileReader(filepath_or_buffer, **kwds)
>   File "<some path to>\pandas\io\parsers.py", line 502, in __init__
>     self._make_engine(self.engine)
>   File "<some path to>\pandas\io\parsers.py", line 610, in _make_engine
>     self._engine = CParserWrapper(self.f, **self.options)
>   File "<some path to>\pandas\io\parsers.py", line 972, in __init__
>     self._reader = _parser.TextReader(src, **kwds)
>   File "parser.pyx", line 483, in pandas.parser.TextReader.__cinit__ (pandas\parser.c:4616)
>   File "parser.pyx", line 605, in pandas.parser.TextReader._get_header (pandas\parser.c:6056)
> pandas.parser.CParserError: Passed header=0 but only 0 lines in file
> \>>> pandas.version.version
'0.13.1'
> \>>>

Of course I could try to find out if this situation occurs before calling read_csv but when working with streams this is not trivial. If the situation is easily flagged within pandas then that might be a more sane location to implement this.

**Comment by jreback** [comment]
not sure why the current ``ValueError`` is not recognizable. The 0.13.1 exception was changed quite a while ago.

**Comment by windancert** [comment]
What I am trying to say is that I have to check the actual message to try to infer that a an empty stream was passed. I would be more comfortable if I could check for a specific exception type. Say an `EmptyFileError`. Unless, of course, it is guaranteed that the `ValueError` is only thrown when an empty stream is passed.

**Comment by jreback** [comment]
well you are coming a relatively old version and a pretty new one. ``ValueError`` is a standard error message. Not sure that a special message is warranted here.

**Comment by windancert** [comment]
For sake of explicitness I am a proponent of a special message, even a special exception type. But if you feel this is not warranted then I'm fine with that. In the mean time I've implemented a workaround for the issue.

Thanks for you effort.

**Comment by jreback** [comment]
@windancert its simply easiest to catch the ``ValueError``. Not sure why you would actually need a work-around. If you are trying to use 2 different versions of pandas with the same code (not recommended at all!), then you will have to do version specific things.
