### ISSUE TITLE
Remove hard coded border property in pandas `to_html()`

### ISSUE THREAD

**Issue by vivekiitkgp** [pydata/pandas#11563]
Hi,

https://github.com/pydata/pandas/blob/e4cb0f8a6cbb5f0c89b24783baa44326e4b2cccb/pandas/core/format.py#L893

Currently, a `border="0"` seems to be hard coded in the pandas `to_html()` table output. I think it'd be more convenient to have that as a CSS property on `dataframe` than put directly like that.

**Comment by jreback** [comment]
this will be trivial to change/remove with #10250 , but I don't think we would remove it by default, this is pretty far ingrained.

**Comment by jreback** [comment]
We also discussed essentially having an option that creates the default HTML output, which a user could override.

**Comment by vivekiitkgp** [comment]
So, #10250 will take care of it, is it?

**Comment by TomAugspurger** [comment]
Yeah it *should* handle this. Right now I've got something like

<img width="963" alt="screen shot 2015-11-09 at 7 39 00 pm" src="https://cloud.githubusercontent.com/assets/1312546/11051951/99f52ece-8719-11e5-9e78-2446b03624be.png">

I need to cleanup the template a bit. If you have specific needs feel free to post them over in #10250.

**Comment by jreback** [comment]
yeh, so need to make a default styler that implements the current spec (then can take out the hard coded stuff)

**Comment by TomAugspurger** [comment]
One other thing is my `Styler`s pretty inefficient. We'll need to get it hooked into the truncated repr before we can hope to replace the current `DataFrame._repr_html_`
