### ISSUE TITLE
Dataframe resampling by groups

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [pydata/pandas#11578]
The examples that I see for [`resample`](http://pandas.pydata.org/pandas-docs/version/0.17.0/generated/pandas.DataFrame.resample.html) seem to only involve `pd.Series`, although the method is technically defined for a `pd.DataFrame`.

Can it be used to do the type of more complex resampling described [here](http://stackoverflow.com/questions/33662514/aggregation-every-x-days-in-pandas)? Can I perhaps do this combining `resample` with `transform` having it work on one-column at a time as in the examples with the `series`?

**Comment by jreback** [comment]
@hayd is should you something more complex than ``.resample`` actually grouping with a frequency based grouper (essentially a resample) and a regular type grouper.

``.resample`` works on ``DataFrames`` as well.
