### ISSUE TITLE
DOC: url for tips.csv leads a 404 in visualization doc

### ISSUE THREAD

**Issue by glyg** [pydata/pandas#11589]
Here is the bad address:
http://wesmckinney.com/files/tips.csv
Found here in the docs:
https://github.com/pydata/pandas/blob/master/doc/source/visualization.rst#trellis-plotting-interface

Alternative link found elsewhere in the code base:
https://raw.github.com/pydata/pandas/master/pandas/tests/data/tips.csv

PR for a fix follows

**Comment by jreback** [comment]
that's an OLD link. Want to do a pull-request to change

**Comment by glyg** [comment]
It's up here: #11590
