### ISSUE TITLE
ImportError: No module named pandas

### ISSUE THREAD

**Issue by datomnurdin** [pydata/pandas#11604]
I got this error message on python 2.7.10. Already installed pandas and openpyxl but still not working.

```
Traceback (most recent call last):
  File "analyze_tweets.py", line 9, in <module>
    import pandas as pd 
ImportError: No module named pandas
```

My code

```
import sys
sys.path.insert(0, "/usr/lib/python2.7/site-packages")
import json
import pandas as pd //error here
import matplotlib.pyplot as plt 
```

Please advice.

**Comment by jreback** [comment]
you don't have pandas installed

see instructions [here](http://pandas.pydata.org/pandas-docs/stable/install.html)


you are also not showing what you did, nor your platform, so impossible to advise anything

**Comment by datomnurdin** [comment]
I already installed Pandas and I'm using Centos 7.

**Comment by jreback** [comment]
if you can't import it then its not installed. and you shouldn't be pathing at all. this indicates a problem with how you installed things.

**Comment by datomnurdin** [comment]
You can check my output message here after I run sudo pip install pandas.

```
sudo pip install pandas
Requirement already satisfied (use --upgrade to upgrade): pandas in /usr/lib64/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): python-dateutil in /usr/lib/python2.7/site-packages (from pandas)
Requirement already satisfied (use --upgrade to upgrade): pytz>=2011k in /usr/lib/python2.7/site-packages (from pandas)
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.7.0 in /usr/lib64/python2.7/site-packages (from pandas)
Requirement already satisfied (use --upgrade to upgrade): six>=1.5 in /usr/lib/python2.7/site-packages (from python-dateutil->pandas)
```

**Comment by jreback** [comment]
same answer. you probably have multiple pythons installed. pls read the installation instructions and follow them.

**Comment by scls19fr** [comment]
I'm facing a similar issue.

Could you see here ?
https://travis-ci.org/scls19fr/pandas_confusion/builds
https://github.com/scls19fr/pandas_confusion

**Comment by AMFIRNAS** [comment]
I also had the same issue and had both python3, python versions installed.

**Comment by pavankat** [comment]
@datomnurdin @scls19fr @AMFIRNAS 

```
sudo pip3 install pandas
```

try that it worked for me.

**Comment by gfyoung** [comment]
> sudo pip3 install pandas

The original issue is for Python 2.x, so unfortunately, this suggestion is moot.  On Linux, do the following:

~~~
which python
which pip
~~~

and see where each is pointing to.  Something tells me you'll find a discrepancy.  If not, chase down where your "existing" `pandas` installation is located and see whether there is actually a `pandas` library installed there.

**Comment by vinrok** [comment]
# I am facing the following issue in my code:

`ImportError       Traceback (most recent call last)
<ipython-input-1-20d62f942773> in <module>()
----> 1 import pandas as pd
         2 
         3 import numpy as np
         4 
         5 import matplotlib.pyplot as plt

ImportError: No module named pandas`

# Even though I have installed pandas.
## I am using Jupyter notebook.

**Comment by RANAJITGIT** [comment]
I am facing the same issue.
I have python 3.6 and panda installed
import pandas as pd is working fine in jupyter notebook.
but I am getting error in python shell.
Please help...............

**Comment by gfyoung** [comment]
Do you have multiple python versions installed?  Try this in the Python shell:

~~~
import sys
print(sys.version_info)
~~~

**Comment by gfyoung** [comment]
Do you have multiple python versions installed?  Try this in the Python shell:

~~~python
import sys
print(sys.version_info)
~~~

**Comment by ram1421** [comment]
is the issue with fixed.  How ?

```
Traceback (most recent call last):
  File "e:\Learn\TensorFlow\script.py", line 5, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
```

**Comment by dduque10** [comment]
It is better to use a virtual environment to avoid these trouble https://stackoverflow.com/questions/49265260/pandas-unrecognized-by-python3/49265845#49265845

**Comment by RANAJITGIT** [comment]
I used pip install pandas in cmd and it works. The issue was not because of
multiple Python versions.

Because jupyter has panda configured so its working in jypyter. How ever to
run it on IDLE we need to panda in cmd.

Regards,
Ranajit

**Comment by kmbuki** [comment]
For macOs users `brew install install caskroom/cask/panda`

**Comment by TomAugspurger** [comment]
`caskroom/cask/panda` looks like a different piece of software.

@thomasschijf in general, you'll want to avoid `sudo pip`. That has a tendency to mess up your system's python install.

**Comment by AmnaKhan1** [comment]
My problem resolved by using pip3 install pandas.  Python version was 3.5.*.

**Comment by Sonupival6** [comment]
I am looking for simulation of KNN algorithm for temperature in python or in MATLAB . IF any one can provide me the code than that will be great.
cheers.

**Comment by mrparsaeian** [comment]
You probably have some .py files in your working directory with the same name as one of the modules you're trying to use. The names of modules should not be used as file names in your project.

**Comment by siposmiki** [comment]
`pip2 install pandas` worked for me. i'm planning to clear out everything and get rid of the plenty of different versions and use only one (or virtual environments as a lot of ppl suggested:))

**Comment by RobStelling** [comment]
If you installed pandas (with pip/conda) and it doesn't show up in python then probably the python in your path is not the same that pip/conda are updating.
Double check your conda directory (Usually: /home/<user>/anaconda3/bin/) and run the python instance on this folder. If pandas is installed there (and I bet it will be) then add this folder to the beginning of your path.

**Comment by Wessi** [comment]
I fixed the same problem with the below commands...
Type `python` on your terminal. If you see python version 2.x then run these two commands to install pandas: `sudo python -m pip install wheel` and `sudo python -m pip install pandas`. Else if you see python version 3.x then run these two commands to install pandas: `sudo python3 -m pip install wheel` and `sudo python3 -m pip install pandas`. Good Luck!

**Comment by Wessi** [comment]
> I am facing the same issue.
> I have python 3.6 and panda installed
> import pandas as pd is working fine in jupyter notebook.
> but I am getting error in python shell.
> Please help...............

https://github.com/pandas-dev/pandas/issues/11604#issuecomment-453545714

**Comment by akun1** [comment]
Just wanted to add to the answer provided by @pavankat

What he suggested worked for me, but I had to download Python 3.7 first!
