### ISSUE TITLE
bar-plots with wrong color using Matplotlib 1.5

### ISSUE THREAD

**Issue by marcomayer** [pydata/pandas#11614]
Hi there,

I'm not sure if this is a pandas/matplotlib or seaborn issue...but since I upgraded to Matplotlib 1.5 using anaconda I can't get the colors of my barplots right anymore, here's an example:

In ipython notebook:

```
import pandas as pd

%matplotlib inline

import seaborn as sns
sns.set_style('whitegrid')

# Works, color as expected in nice muted blue
pd.DataFrame([1,2,3,4,5,6]).plot(linewidth=10)


# Doesn't work, getting matplotlib "eye-cancer-blue"
pd.DataFrame([1,2,3,4,5,6]).plot(kind='bar')
```

I attached a screenshot one with matplotlib 1.4.x and one with 1.5:

![matplotlib_15](https://cloud.githubusercontent.com/assets/10881376/11185937/8f124a62-8c7f-11e5-9d8f-56991ffdc798.png)
![matplotlib_14](https://cloud.githubusercontent.com/assets/10881376/11185936/8f11b7c8-8c7f-11e5-8773-8dceaea7bd76.png)

Again I know this might well not be a pandas issue but maybe someone has an idea where the problem might be.

**Comment by TomAugspurger** [comment]
probably a pandas issue since `plt.bar(df.index, df[0])` gives the correct colors.

**Comment by amichaut** [comment]
hi, 
just to say the issue is still there in 0.17.1
