### ISSUE TITLE
DataFrame.add with disjoint indexes failing ramdomly in 0.17.0

### ISSUE THREAD

**Issue by educhana** [pydata/pandas#11629]
Sometimes DataFrame.add method fails when adding two dataframes. 
I have create the snippet below to reproduce. It will fail sooner or later (may take a while, 100000 or more iterations). 

I have reproduced the problem always in pandas 0.17.0 and windows x64 (linux x64 seems fine). Using both anaconda and winpython, under different versions of numpy (1.9 & 1.10) and python 3.4 & 3.5
Other pandas versions work ok.

```python
# -*- coding: utf-8 -*-
import pandas as pd
import numpy as np
from random import randint

print("pandas version:", pd.__version__)
print("numpy version:", np.__version__)


NROWS = 10000
NCOLS = 10
COLUMNS = [c+1 for c in range(NCOLS)]


def equalf(a, b, rtol=1e-05, atol=1e-08):
    return abs(a - b) <= (atol + rtol * abs(b))


def create_df():
    """
    :return: dataframe with indexes somewhat overlapping
    """
    nrows = randint(1, NROWS)
    offset = randint(0, NROWS)
    m = np.random.randn(nrows, NCOLS)
    return pd.DataFrame(data=m, index=[i for i in range(offset, offset + nrows)], columns=COLUMNS)


if __name__ == '__main__':
    pd.set_option('display.width', 1024)
    df0 = create_df()
    for n in range(1000000):
        if not n % 1000: print(n)
        df0_checksum = df0.values.sum()
        df1 = create_df()  
        df1_checksum = df1.values.sum()
        df = df0.add(df1, fill_value=0)  # sometimes doesnt add correctly  !!!!!!
        df_checksum = df.values.sum()
        if not equalf(df_checksum, df0_checksum + df1_checksum):
            print("error")
            print(df0, df0_checksum)
            print(df1, df1_checksum)
            print(df, df_checksum)
            print("df, df0 + df1 =", df_checksum, ",", df0_checksum + df1_checksum)
            assert equalf(df_checksum, df0_checksum + df1_checksum)
        df0 = df
```

**Comment by jreback** [comment]
show ``bottleneck/numexpr`` versions as well

**Comment by educhana** [comment]
Great!

Upgrading numexpr to 2.4.6 seems to solve the problem.

By the way, the previous versions were:

Anaconda3 (2.4.0) (failing):
* bottleneck not installed
* numexpr 2.4.4

WinPython 3.4.3.6 (fails):
* bottleneck 1.0.0
* numexpr 2.4.4

WinPython 3.4.3.5 (ok)
* bottleneck not installed
* numexpr 2.4.3

**Comment by jreback** [comment]
try doing:

``pandas.computation.expressions.set_use_numexpr(False)``

and see if you can replicate.

**Comment by jreback** [comment]
I think this is a bug fixed in numexpr 2.4.5/6: https://github.com/pydata/numexpr/blob/master/RELEASE_NOTES.rst

**Comment by educhana** [comment]
You are right,

disabling numexpr with set_use_numexpr(False) solves the problem as well.

**Comment by jreback** [comment]
ok, so I guess this is some kind of interaction that numexpr fixed. will keep on the lookout. thanks.
