### ISSUE TITLE
Conditional HTML styling hides MultiIndex structure

### ISSUE THREAD

**Issue by mattilyra** [pydata/pandas#11655]
I noticed that the styling doesn't quite work with `MultiIndex` data frames. For example if we have a dataframe with two cross validated scores and take their `mean`and `sem` using `groupby` to get a `MultiIndex` dataframe

    import itertools
    import pandas as pd
    import numpy as np

    jobs = itertools.product(['a', 'b', 'c', 'd'], np.arange(1e-4, 1e-3, .0003), range(10))
    rows = []
    for v, v2, itr in jobs:
        rows.append({'param_1': v, 'param_2': v2, 'iter': itr,
                     'score_1': np.random.randint(0, 100, size=(1,))[0],
                     'score_2': np.random.rand(1, )[0]})
    df_multi = pd.DataFrame(rows)
    agg = df_multi.groupby(by=['param_1', 'param_2'])[['score_1', 'score_2']].agg(['mean', 'sem'])
    agg.style.highlight_max()

![screen shot 2015-11-20 at 12 04 13](https://cloud.githubusercontent.com/assets/1055719/11298395/ef2e2bc6-8f7e-11e5-92f8-a7b1bfbaff77.png)

where as without the styling the index names are preserved and the `score_1` and `score_2` column headers span 2 columns which improves legibility.

![screen shot 2015-11-20 at 12 02 56](https://cloud.githubusercontent.com/assets/1055719/11298385/d644ad38-8f7e-11e5-9b7a-49e71c2b87b4.png)

**Comment by jreback** [comment]
IIRC this is 'not implemented', cc @TomAugspurger as wanted to get basic stuff working.

patches are welcome!

**Comment by jreback** [comment]
see last check box in #11610

**Comment by TomAugspurger** [comment]
Yep. This one isn't too bad to do, I just ran out of time. It's a matter of modifying the template to be aware of the index levels.

**Comment by mattilyra** [comment]
@jreback ah I see, didn't read the post properly. I guess in that case this issue is redundant and can be closed.

**Comment by jreback** [comment]
@mattilyra its fine. you can post a fix and directly reference this.

**Comment by jreback** [comment]
this still open @TomAugspurger ?

**Comment by TomAugspurger** [comment]
Yeah, still open.

**Comment by jreback** [comment]
@TomAugspurger did you have a fix for this already? (even if not prod ready), just want to give a try.

**Comment by TomAugspurger** [comment]
@jreback I can get something together tonight, if that's not too late.

The basic idea is to use the logic in `pandas.core.format._get_level_lengths` on each of the MI elements. We'll put a couple more pieces of state in the internal dict `is_visible`, `row_span` and `col_span`.

**Comment by jreback** [comment]
that would be totally fantastic!

**Comment by TomAugspurger** [comment]
@jreback OK, the minimal version (1 whole test) is here: https://github.com/TomAugspurger/pandas/tree/style-sparse-mi-2

I'll see what refactoring I can do and submit a pull request sometime soonish.

**Comment by jreback** [comment]
![image](https://cloud.githubusercontent.com/assets/953992/16652616/b221a88e-4419-11e6-8713-d7eae7b4624a.png)

hmm, doesn't seem to change the display. (using pandas 0.18.0 as a comparison). The column labels are not showing sparse (as what we normally do in an html display)

**Comment by TomAugspurger** [comment]
Ahh, only did index labels. Give me 20 minutes :)

**Comment by TomAugspurger** [comment]
@jreback pushed https://github.com/pydata/pandas/commit/4655534a40e65e0d380116607d983100c513da20 which fix it.

https://gist.github.com/643402b241e6d945118942cb8ccff3ac

Index names are messed up with a  MultiIndex, but if you just set those to `""` then the None shouldn't appear.

**Comment by jreback** [comment]
that looks great! thanks!

I realize that the CSS injection can be done thru ``set_table_style`` I think as well.

**Comment by jreback** [comment]
@TomAugspurger so this fixes the single level index case (I don't have a good repro :<
but); also only barely tested on a single level columns (this works with the multi-level nicley as that was the point).

```
def _get_level_lengths(index):
    '''
    Given an index, find the level lenght for each element.

    Result is a dictionary of (level, inital_position): span
    '''
    sentinel = com.sentinel_factory()
    levels = index.format(sparsify=sentinel, adjoin=False, names=False)

    if index.nlevels == 1:
        return { (0, i):1 for i, value in enumerate(levels) }
    
    lengths = {}
    for i, lvl in enumerate(levels):
        for j, row in enumerate(lvl):
            if row != sentinel:
                last_label = j
                lengths[(i, last_label)] = 1
            else:
                lengths[(i, last_label)] += 1

    return lengths
```
