### ISSUE TITLE
Rolling_median fails with large number of elements

### ISSUE THREAD

**Issue by ajspeck** [pydata/pandas#11697]
The new version of rolling_median from 0.17.1 fails with:
```python
pandas\algos.pyx in pandas.algos.roll_median_c (pandas\algos.c:36408)()

MemoryError: skiplist_insert failed 
```
when called with series containing large number of values.  In comparison, the previous version of 0.17.0 was robust and never showed this error.

On my win-64 computer, I can routinely trigger the error by the following command:
```python
import numpy as np
import pandas as pd
n=50000
pd.rolling_median(pd.Series(np.random.randn(n)), window=2, center=False)
```
while
```python
import numpy as np
import pandas as pd
n=5000
pd.rolling_median(pd.Series(np.random.randn(n)), window=2, center=False)
```
works fine.

The actual point at which the error begins appears to be non-deterministic but is somewhere around n=35,000. 

Versions are as follows:
INSTALLED VERSIONS
------------------
commit: None
python: 2.7.10.final.0
python-bits: 64
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None

pandas: 0.17.1
nose: 1.3.7
pip: 7.1.2
setuptools: 18.5
Cython: 0.23.4
numpy: 1.10.1
scipy: 0.16.0
statsmodels: 0.6.1
IPython: 4.0.0
sphinx: 1.3.1
patsy: 0.4.0
dateutil: 2.4.2
pytz: 2015.7
blosc: None
bottleneck: 1.0.0
tables: 3.2.2
numexpr: 2.4.4
matplotlib: 1.5.0
openpyxl: 2.2.6
xlrd: 0.9.4
xlwt: 1.0.0
xlsxwriter: 0.7.7
lxml: 3.4.4
bs4: 4.4.1
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.0.9
pymysql: None
psycopg2: None
Jinja2: None

**Comment by kawochen** [comment]
hmm... I will take a look.

**Comment by kawochen** [comment]
@ajspeck  How did you run the code? Did you run those four lines as a script or in the interpreter (if so, IPython or simply Python?) in interactive mode?  How much memory is your process using at peak?  I profiled the peak memory using `n=5000000` and the difference between 1.70.0 and 1.70.1 is negligible.  

I don't think it's likely, but one possibility is that your resources are very limited and need a garbage collection mid-`rolling_median` call.

**Comment by ajspeck** [comment]
I see the same error regardless of whether it is run in an interpreter (either ipython or python) or in a script.  

I have done some more debugging and it appears the issue is coming from the calculation of size in skiplist_insert (see https://github.com/pydata/pandas/blob/5bc191a689fdcd9a805a5a213e1de0cdfa330ccb/pandas/src/skiplist.h#L226).  If urand() returns 0.0, then the call to log2 returns infinity,  and the calculation of size overflows.  In particular at least for MSVC 2008, size is 0x80000001 and the calls to malloc in node_init fail.

I added a simple check for urand() = 0.0 and then replacing it with DBL_EPSILON if so and that looks to have fixed the issue.

**Comment by kawochen** [comment]
Ah!  I see.  
How about
```
static PANDAS_INLINE double urand_pos(void) {
  return ((double) rand() + 1)/ ((double) RAND_MAX + 2);
}
```

**Comment by ajspeck** [comment]
That change fixes it on my system.

**Comment by qucrazy** [comment]
I have a similiar issue.
I use the @ajspeck example.

I got the same error  when I used the follow code:

```
import numpy as np
import pandas as pd
n = 20000
pd.rolling_median(pd.Series(np.random.randn(n)), window=2, center=False)
pd.rolling_median(pd.Series(np.random.randn(n)), window=2, center=False)
```
while
```
import numpy as np
import pandas as pd
n=5000
pd.rolling_median(pd.Series(np.random.randn(n)), window=2, center=False)
```
works fine.

I don't know the issue is the same to ajspeck's.The change couldn't fix my issue.
Thanks!

**Comment by hal98x** [comment]
I see the same issue. I am running 0.17.1 from spyder? A reset seems to help. I have seen this occur with 2000 element series.

  File "pandas\algos.pyx", line 1586, in pandas.algos.roll_median_c (pandas\algos.c:36408)

MemoryError: skiplist_insert failed

When is 0.18.0 going to be released?
Can you really calculate a median with only 2 numbers? I am using 3 or 5, so I can reference off the center

**Comment by jreback** [comment]
0.18.0 has been out for 2 months
