### ISSUE TITLE
Style not able to take formatters

### ISSUE THREAD

**Issue by schwallie2** [pydata/pandas#11692]
When using the new CSS styling, there doesn't seem to be a way to add formatters for the numbers. So trying to make the number data display as $10,000 when using any styling options currently seems off the table.
Documented here:
http://stackoverflow.com/questions/33875937/apply-number-formatting-to-pandas-html-css-styling

Related to this PR: https://github.com/pydata/pandas/pull/11667

**Comment by mattilyra** [comment]
I suppose the formatting should be expanded to cover all the functions in `Styler` not just `.set_precision`, so the following should take some kind of `format={}` kwarg that defines the format per column.

- `.highlight_min`
- `.highlight_max`
- `.highlight_max`
- `.bar`

This is partly implemented in #11667.

**Comment by TomAugspurger** [comment]
API wise it'd be best to have a dedicated method for this, something like `.format` that takes a list of dictionaries mapping column to a python string formatting spec.

**Comment by schwallie2** [comment]
Agree with the .format being better than implementing this everywhere. Can
we reuse formatters from to_HTML?
On Nov 25, 2015 7:15 AM, "Tom Augspurger" <notifications@github.com> wrote:

> API wise it'd be best to have a dedicated method for this, something like
> .format that takes a list of dictionaries mapping column to a python
> string formatting spec.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pydata/pandas/issues/11692#issuecomment-159604111>.
>

-- 
This e-mail is only intended for the person(s) to whom it is addressed and 
may contain confidential information.  Any unauthorized review, use, 
disclosure, or distribution is prohibited. If you received this e-mail in 
error, please notify the sender by reply e-mail and then delete this 
message and any attachments from your system. Thank you for your 
cooperation.

**Comment by TomAugspurger** [comment]
> Can we reuse formatters from to_HTML?

Yeah we should match that API if possible.

I think our best bet implementation is to build up a more complicated dictionary outside of the template that contains another field with the formatted / to be displayed value. We'll look for that field in the template.
