### ISSUE TITLE
Inconsistent concat behavior between datetime64[ns] and tz-aware version in 0.17.1

### ISSUE THREAD

**Issue by brendene** [pydata/pandas#11693]
This edge case appears when concatenating a timezone aware datetime series with another that is filled with only pd.NaT.  This works if the second series is only partially filled with pd.NaT.  It also works if the second series is another timezone (in that case the resulting Series is timezone unaware).

```python
import pandas as pd
pd.__version__
x = pd.Series( pd.date_range('20151124 08:00', '20151124 09:00', freq = '1h') )
y = pd.Series( pd.date_range('20151124 10:00', '20151124 11:00', freq = '1h') )
pd.concat([x,y]) # Works

y[:] = pd.NaT
pd.concat([x,y]) # Works

x = pd.Series( pd.date_range('20151124 08:00', '20151124 09:00', freq = '1h', tz = "US/Eastern") )
y = pd.Series( pd.date_range('20151124 10:00', '20151124 11:00', freq = '1h', tz = "US/Eastern") )
pd.concat([x,y])

y[0] = pd.NaT
pd.concat([x,y]) # Works

y[:] = pd.NaT
pd.concat([x,y]) # Fails
```

**Comment by jreback** [comment]
0.17.1 I  c

can I see if this worked prior to 0.17.0?

**Comment by brendene** [comment]
This works in 0.16.2, the dtype of timezoned series is object.

**Comment by jreback** [comment]
hmm, looks like a bug, want to do a pull-request to fix?
