### ISSUE TITLE
Dropping rows from a DataFrame with MultiIndex does not remove index entries

### ISSUE THREAD

**Issue by tpietruszka** [pydata/pandas#11724]
Hello 
I am not sure, maybe this is the expected behaviour, but it was a big surprise for me (and a source of some bugs).

As the title states, dropping rows (whether inplace or not) does not delete corresponding index entries (when the frame has a multiIndex). If one later uses index values directly it causes really unexpected behaviour. 

An obvious work-around is to reset index and re-build it, but it is not really elegant code...
Simple example:

```python
>>> import pandas as pd
>>> df = pd.DataFrame([['A', 'a', 1], ['B', 'b', 2], ['C', 'c', 3]], columns=['upper', 'lower', 'num'])
>>> df = df.set_index(['upper', 'lower'])
>>> df = df.drop('A')
>>> df.index
MultiIndex(levels=[['A', 'B', 'C'], ['a', 'b', 'c']],
           labels=[[1, 2], [1, 2]],
           names=['upper', 'lower'])
>>> df.index.levels[0]
Index(['A', 'B', 'C'], dtype='object', name='upper')
```
Even though the row was deleted correctly.

show_versions():
```

INSTALLED VERSIONS
------------------
commit: None
python: 3.4.3.final.0
python-bits: 64
OS: Linux
OS-release: 4.2.0-18-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

pandas: 0.17.1
nose: 1.3.7
pip: None
setuptools: 18.4
Cython: 0.23.3
numpy: 1.10.1
scipy: 0.14.1
statsmodels: 0.6.1
IPython: 4.0.0
sphinx: 1.3.1
patsy: 0.4.1
dateutil: 2.4.2
pytz: 2015.7
blosc: None
bottleneck: None
tables: None
numexpr: 2.4.4
matplotlib: 1.5.0
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: 0.7.3
lxml: 3.4.4
bs4: 4.3.2
html5lib: 0.999
httplib2: 0.9
apiclient: None
sqlalchemy: None
pymysql: None
psycopg2: None
Jinja2: None

```

**Comment by jreback** [comment]
see #2770 

this is expected. it is non-performant to recompute the levels in general.

**Comment by TomAugspurger** [comment]
Could keep this open as a doc issue. Just a note in the docstring would be nice.

**Comment by tpietruszka** [comment]
Sorry for the duplicate then, 
But yes, I think a note about this in the docs  would be really useful. 

Also, is there a recommended way of getting an analog of df.index.levels[0] but without empty entries?
df.index.get_level_values(n).unique()?
