### ISSUE TITLE
Surprising results of pandas.to_datetime()

### ISSUE THREAD

**Issue by JanSchulz** [pydata/pandas#11725]
I just used `pd.to_datetime` on a string column and inspected the head of the dataframe and it looked good. Unfortunately, I had german dates (day.month.year) with high days in the first rows. These were converted correctly, but then I got dates (of the next month) with low days and the conversion switched to american style (month.day.year). I would expect that I at least get a warning that the date formats are different or that the first found date format is used for all dates:

```
>>> pd.to_datetime(["29.01.1945","1.3.1945", "02.03.1945"])
DatetimeIndex(['1945-01-29', '1945-01-03', '1945-02-03'], dtype='datetime64[ns]', freq=None)
```

**Comment by jreback** [comment]
you need to specify ``dayfirst`` (which defaults to ``False``)

```
In [4]: pd.to_datetime(["29.01.1945","1.3.1945", "02.03.1945"],dayfirst=True)
Out[4]: DatetimeIndex(['1945-01-29', '1945-03-01', '1945-03-02'], dtype='datetime64[ns]', freq=None)
```

**Comment by JanSchulz** [comment]
I know how to work around it, I'm just surprised that `pd.to_datetime()` can change the interpretation in between values of the same Series.

E.g. if `dayfirst == False`, then why does it sometimes use a month value as day?

**Comment by jorisvandenbossche** [comment]
@JanSchulz You are fully correct this is really confusing/problematic behaviour, but that is a limitation by the dependency on `dateutil`, as explained (briefly) in the docstring: http://pandas.pydata.org/pandas-docs/stable/generated/pandas.to_datetime.html

**Comment by jorisvandenbossche** [comment]
See also https://github.com/pydata/pandas/issues/3341
