### ISSUE TITLE
BUG: mpl_style 'default' gives AttributeError: Unknown property color_cycle with latest matplotlib 

### ISSUE THREAD

**Issue by jorisvandenbossche** [pydata/pandas#11727]
http://stackoverflow.com/questions/33995707/attributeerror-unknown-property-color-cycle

```
In [1]: matplotlib.__version__
Out[1]: '1.5.0'

In [2]: df = pd.DataFrame(np.random.randn(5,5))

In [4]: df.plot()
Out[4]: <matplotlib.axes._subplots.AxesSubplot at 0x7bc5c50>

In [5]: pd.set_option('display.mpl_style', 'default')

In [6]: df.plot()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
....

AttributeError: Unknown property color_cycle

In [7]: pd.__version__
Out[7]: '0.17.1'
```

**Comment by TomAugspurger** [comment]
I'm not sure exactly what's happening here based on a quick glance. I do [check for mpl1.5 and adjust our stylesheet](https://github.com/pydata/pandas/blob/0c43fcc5d128397becc0b67557311b4e8ee53100/pandas/tools/plotting.py#L137)

**Comment by jorisvandenbossche** [comment]
I jut see that some lines below, there is a harcoded `plt.rcParams.get('axes.color_cycle')` : https://github.com/pydata/pandas/blob/0c43fcc5d128397becc0b67557311b4e8ee53100/pandas/tools/plotting.py#L166

**Comment by TomAugspurger** [comment]
Ugh good find. That should be conditional on the matplotlib version. Should we just retroactively declare that stylesheet deprecated :grinning:?

**Comment by jorisvandenbossche** [comment]
+1!

**Comment by jorisvandenbossche** [comment]
+1!

**Comment by brian-pantano** [comment]
The correct fix is to change

  mpl_stylesheet['axes.prop_cycle'] = cycler.cycler('color_cycle', colors)

to

  mpl_stylesheet['axes.prop_cycle'] = cycler.cycler('color_cycle', colors)

There's no prop_cycle called `'color_cycle'`. I believe the prop_cycle you're looking for is `'color'`
