### ISSUE TITLE
 Large number of element use rolling_median twice or more

### ISSUE THREAD

**Issue by qucrazy** [pydata/pandas#11722]
I have a similiar issue with BUG #11697 but not same.
This issue is on win64. But  my macos is ok. 
Version:
python:2.7.10
pandas:0.17.1
numpy: 1.10.1
I use the @ajspeck example.

I got  the same error
```
  File "pandas\algos.pyx", line 1586, in pandas.algos.roll_median_c (pandas\algos.c:36408)
MemoryError: skiplist_insert failed 
```
when I used the follow code:
```
import numpy as np
import pandas as pd
n = 20000
pd.rolling_median(pd.Series(np.random.randn(n)), window=2, center=False)
pd.rolling_median(pd.Series(np.random.randn(n)), window=2, center=False)
```
while
```
import numpy as np
import pandas as pd
n=20000
pd.rolling_median(pd.Series(np.random.randn(n)), window=2, center=False)
```
works fine.

I found sum of n must  less than 25200
I don't know the issue is the same to ajspeck's.And the change couldn't fix my issue.
I guess the node is not destoried.
Thanks!

**Comment by jreback** [comment]
cc @kawochen

**Comment by kawochen** [comment]
@qucrazy did you recompile after applying the fix?

**Comment by kawochen** [comment]
embarrassingly, I can reproduce this error on windows myself, and the fix did fix the issue for me.  I think if you try a larger number like 100000, you don't need to do `rolling_median` twice to encounter the issue, because on windows `RAND_MAX` is small and you run into it returning 0 fairly soon.

**Comment by qucrazy** [comment]
when I  need several variables, I will do ```rolling_median``` several times. @kawochen

**Comment by kawochen** [comment]
@qucrazy I understand.  Did you do `python setup.py build_ext --inplace` after applying the fix?

**Comment by qucrazy** [comment]
@kawochen  unfortunately, it's useless.

**Comment by kawochen** [comment]
@qucrazy hmm... could you clarify -- did you succeed in recompiling the code after editing the header file?

**Comment by qucrazy** [comment]
I edit the skiplist:
```
static PANDAS_INLINE double urand(void) {
  return ((double) rand() + 1)/ ((double) RAND_MAX + 2);
}
```
and then I run
···
python setup.py build_ext --inplace
···
after that， I run
···
python setup.py install
···

**Comment by qucrazy** [comment]
wow...I recompile again, and it works!
perhaps,i made a mistake before.
THanks a lot!!! @kawochen

**Comment by kawochen** [comment]
thank YOU!

**Comment by jreback** [comment]
@kawochen why don't we add this as a test case in PR for #11697

**Comment by kawochen** [comment]
Will do.
