### ISSUE TITLE
Add option to hide index in pandas.Series.to_string

### ISSUE THREAD

**Issue by ccsv** [pydata/pandas#11729]
In the Dataframes.to_string function there is a option to not print the index:

index : bool, optional

    whether to print index (row) labels, default True

Can this be added to the Series function to_string?

http://pandas.pydata.org/pandas-docs/version/0.17.0/generated/pandas.Series.to_string.html

**Comment by jreback** [comment]
sure that could be made consistent, pull-requests accepted.

Though in general this routine is mostly used internally.
