### ISSUE TITLE
pandas.applymap converts None to NaN even though I didn't ask it to? 

### ISSUE THREAD

**Issue by tavistmorph** [pydata/pandas#11730]
I have a dataframe with some empty strings and some NaNs. I want to convert both of those to None. 
I'm calling applymap to convert the empty strings into None, which works; but it has the side-effect of converting all the existing Nones into NaN!
  Using pandas version 0.16:

    import pandas
    import numpy

    p = pandas.DataFrame({ 'x' : [ numpy.NaN, 1, 2 ], 'y' : [ '', 'hello', '' ] })
    #This line fixes the NaN in the first column but doesn't do anything 
    #about the empty strings in the second column. 
    p = p.where(pandas.notnull(p), None)
    #This line fixes the empty strings in the second column, but it messed up the first column!
    #It turns my None back into a Nan again! But why? Looks like the column was dtype 'object'
    #before and this is converting it to dtype=float, but why? I never asked it to do that. 
    p = p.applymap(lambda x: None if isinstance(x, str) and x is not None and len(x) <= 0 else x)

Is there any way to convert both the NaNs and the empty strings into None?

**Comment by jreback** [comment]
why would you want to do this at all? ``None`` is NOT a performant sigil for missing values, rather it is ``nan``, see docs [here](http://pandas.pydata.org/pandas-docs/stable/missing_data.html).

**Comment by tavistmorph** [comment]
1) It's necessary to replace the NaN with None if you want to insert the rows into a database using pyodbc -- the database won't let you insert NaN into a float column in the database.
  2) But let's not change the subject into "why do you want this" --  clearly Pandas does support None, so why does the applymap change the type of that first column when there was clearly no need to? That seems very unexpected behavior -- no one would expect that applymap to replace None with Nan like it did.

Sounds like you don't want to call it a bug, but is there a workaround?

**Comment by jreback** [comment]
simply use ``.to_sql`` it already does all of these things.

**Comment by tavistmorph** [comment]
Thanks, but no, .to_sql() doesn't produce the output I need for my case so that's not a workaround.

But that has nothing to do with the original question -- how can I make Pandas change all the NaN to None (or at least stop it from UN-changing it like in the code snippet above?)

**Comment by jreback** [comment]
```
In [27]: r = p.replace('',np.nan).astype(object)

In [28]: r
Out[28]: 
     x      y
0  NaN    NaN
1    1  hello
2    2    NaN

In [29]: r[r.isnull()] = None

In [30]: r
Out[30]: 
      x      y
0  None   None
1     1  hello
2     2   None
```

You are reinventing the wheel here by writing your own code to do this. good luck.

**Comment by tavistmorph** [comment]
Thanks, I'll use that workaround. But I think the original question is getting lost --  applymap() is changing columns that are dtype=object into dtype=float for no obvious reason. (And a side-effect of that is that Nones are translated into Nans). 
  Is that really the expected behavior? In the original code snippet above, would you really expect applymap() to change the column type like that?

**Comment by jreback** [comment]
yes I would. all pandas operations do inference. a float should try to remain a float for example.
