### ISSUE TITLE
to_csv(header=True) produces error:

### ISSUE THREAD

**Issue by Sereger13** [pydata/pandas#11739]
According to the latest doc `header` parameter can be 
> boolean or list of string, default True

However, the following code
```
import pandas as pd
pd.read_csv('test.csv', header=True)
```
Produces this error:
>TypeError: Passing a bool to header is invalid. Use header=None for no header or header=int or list-like of ints to specify the row(s) making up the column names.

Not sure what is expected behaviour but the code and the doc don't seem to agree with each other?

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.10.final.0
python-bits: 64
OS: Linux
OS-release: 2.6.18-238.9.1.el5
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US

pandas: 0.17.1

**Comment by TomAugspurger** [comment]
Your code uses `pd.read_csv`, but the documentation you quoted is from `DataFrame.to_csv`.

**Comment by Sereger13** [comment]
Yes I take it back - sorry for confusion - just realised myself.
