### ISSUE TITLE
axis keyword of Series.ptp() does not work with 'index' as argument

### ISSUE THREAD

**Issue by kesyog** [pydata/pandas#11748]
According to the [API](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.ptp.html?highlight=ptp#pandas.Series.ptp), the `ptp` method of Series should be able to handle 'index' as an argument for the `axis` keyword. But when I try the following code:

    x = pd.Series(range(15,20), index=range(5,10))
    x.ptp(axis='index')

I get an error: "TypeError: an integer is required for the axis"

I'm using Pandas 0.17.0

**Comment by jreback** [comment]
this was added 0.17.1
