### ISSUE TITLE
Broken link in 0.17.1 what's new and commercial support pages

### ISSUE THREAD

**Issue by ghost** [pydata/pandas#11744]
http://pandas.pydata.org/pandas-docs/version/0.17.1/whatsnew.html and http://pandas.pydata.org/commercialsupport.html has a link to the NumFocus announcement. The link points to http://numfocus.org/news/2015/10/09/numfocus-announces-new-fiscally-sponsored-project-pandas/, which is broken. The correct link is:

http://www.numfocus.org/blog/numfocus-announces-new-fiscally-sponsored-project-pandas

**Comment by jreback** [comment]
yeh, apparently the site was migrated and some of the posts didn't make it.

@jorisvandenbossche can you can this in the current docs?

**Comment by jorisvandenbossche** [comment]
a PR can be done to correct this in docs in master, and I will correct it in the html sources itself for the online docs (that will be the easiest I think)

**Comment by jreback** [comment]
gr8 thanks!

**Comment by jorisvandenbossche** [comment]
A bit later, but I fixed this in the online docs, and also in master with this commit: https://github.com/pydata/pandas/commit/030099ab4792a8d38d70d7521c6754e979b7f46c
