### ISSUE TITLE
read_html doesn't have infer_types parameter

### ISSUE THREAD

**Issue by wizard0530** [pydata/pandas#11764]
__infer_types__ is indicated in the "IO Tools page" (http://pandas.pydata.org/pandas-docs/stable/io.html#io-read-html), but not in the API Reference page (http://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_html.html) and library v0.17.1

**Comment by jreback** [comment]
yeh, that was removed finally in 0.17.0 IIRC (was deprecated for quite a while). it should be removed from the main docs.

**Comment by wizard0530** [comment]
I want to keep some numbers in String. How can I do? For example, '000322' is a code in String, not a number.

**Comment by srib** [comment]
#11765

**Comment by jorisvandenbossche** [comment]
This has already been asked in several issues (eg also https://github.com/pydata/pandas/issues/10684#issuecomment-125174870), but as far as I can see, the `dtype` argument is not passed to TextParser (https://github.com/pydata/pandas/blob/master/pandas/io/html.py#L623). It seems not very difficult to do this? 

Further I can imagine that others can also be useful, eg `decimal`, `converters`, `na_values`, ...
