### ISSUE TITLE
COMPAT: msgpack on windows 3.5 failing oddly

### ISSUE THREAD

**Issue by jreback** [pydata/pandas#11769]
@kawochen just updated the appveyor support (was not really running correctly before).

in [here](https://github.com/pydata/pandas/commit/5b84e49e44cb378cee211436f0966e53d89b08b1)

2.7 fully passes and 3.5 does except for some of these odd MemoryErrors, must be some sort of recursion issue, see build [here](https://ci.appveyor.com/project/jreback/pandas/build/1.0.1526/job/0meym8xg4j0bh9ea)

I cannot reproduce these locally, only on appveyor, any thoughts?

**Comment by kawochen** [comment]
The number of failures isn't the same every time either... (there is sometimes an HDF5 failure in case you didn't notice).
The failures seem to be related to `ExtType`.  I'm not seeing where a `MemoryError` could be raised.  I'll see if I can reproduce this.

**Comment by jreback** [comment]
yeh, ``MemoryError`` is prob just hiding something else. might have to do with the compilation of the ``ExtType`` (as 3.5 changed how things compile on windows :<)

**Comment by kawochen** [comment]
@jreback 
http://www.appveyor.com/docs/installed-software
So on the worker, Windows Driver Kit is installed.
This patch (https://github.com/ogrisel/python-appveyor-demo/commit/09a1c8672e5015a74d8f69d07add6ee803c176ec) here fixed this issue (https://connect.microsoft.com/VisualStudio/feedback/details/1610302/).  So maybe do the same and see?

**Comment by jreback** [comment]
trying out: https://ci.appveyor.com/project/jreback/pandas

**Comment by kawochen** [comment]
didn't work :|

**Comment by jreback** [comment]
yeh no dice :<

**Comment by jreback** [comment]
btw, you can log into appveyor with your github.... I think it will automatically build your own PR's

**Comment by kawochen** [comment]
@jreback you said you couldn't reproduce this -- how did you compile the extension?  I was able to trace it to a failed `Py_VaBuildValue` in the python function callback (e.g. `ExtType`).  I could make the tests pass by making trivial changes to the source code, like a few `printf` in c or `print` in Python.  Still not sure why...
