### ISSUE TITLE
ENH: Using built-in round on a series

### ISSUE THREAD

**Issue by Dr-Irv** [pydata/pandas#11763]
Is there some philosophical reason that round(Series) and round(Dataframe) is not defined?  See the example below.  Being able to write round() as a function of a Dataframe or Series, as opposed to doing it afterwards would be nice.  I'm willing to implement `__round__()` to make it work, but don't want to go down that path if there is some reason `__round__()` is not implemented.

Example:
```
    import pandas as pd
    import numpy as np
    df =  pd.DataFrame(np.random.randn(10, 3), columns=['A', 'B', 'C'])
    print (df.A.round())
    print (round(df))
```
Produces
```
0   -2
1    1
2   -1
3   -1
4    2
5    0
6    0
7    0
8   -2
9    0
Name: A, dtype: float64
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-8-9d2be9cbdc70> in <module>()
      3 df =  pd.DataFrame(np.random.randn(10, 3), columns=['A', 'B', 'C'])
      4 print (df.A.round())
----> 5 print (round(df))

TypeError: type DataFrame doesn't define __round__ method
```

**Comment by jreback** [comment]
sure you could define that

**Comment by srib** [comment]
@jreback `Series` has `.round` supported. `DataFrame` doesn't seem to have one. Did you mean otherwise in your comment?

I would be happy to send a PR for this.

**Comment by jreback** [comment]
add in 0.17.0: http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.round.html?highlight=round#pandas.DataFrame.round

**Comment by srib** [comment]
@jreback Thanks!

**Comment by Dr-Irv** [comment]
@jreback So I have something that works fine with Python 3, but Python 2 presents a problem because in Python 2, round(class) doesn't call class.__round__() .  In other words, you can't easily override the built-in round() behavior in Python 2. I'm not sure of the best way to handle this. I could just avoid the round() test in the testing code when doing a Python 2 test and we don't worry about supporting round(DataFrame) with Python 2.  Other suggestions welcome.

**Comment by jreback** [comment]
Python 2.7.10 |Continuum Analytics, Inc.| (default, Oct 19 2015, 18:31:17) 
Type "copyright", "credits" or "license" for more information.


Obviously you wouldn't actually call ``object.__round__``, but this works in py2.
```
In [3]: class F(float):
   ...:     def __round__(self):
   ...:         return object.__round__(self)
   ...:     

In [4]: F(5.2)
Out[4]: 5.2

In [5]: round(F(5.2))
Out[5]: 5.0
```

**Comment by Dr-Irv** [comment]
@jreback I don't think your example applies, because we want round(DataFrame) to work correctly, and your example worked OK because you were subclassing a float object.  If you changed ``return object.__round__(self)`` to ``return 98``, you'd see that. The issue is that in py2, round() calls float() and then does the rounding. py3 allows round() to be overridden on a class by implementing ``__round__()`` One can override float() by implementing ``__float__()``, but I don't think we want to override the float() behavior for pandas. Found this article on stackoverflow related to this.  http://stackoverflow.com/questions/9751476/float-and-round-in-python-2-and-3

**Comment by jreback** [comment]
@Dr-Irv ok, that IS an ugly hack. So just test this on PY3, that is fine. This is really just a convenience feature anyhow, it really breaks up the flow, but if people really want to use it then it would work e.g.

``df.round(....)`` vs ``round(df)``
