### ISSUE TITLE
read_hdf not supporting pathlib.Path

### ISSUE THREAD

**Issue by michaelaye** [pydata/pandas#11773]
According to the Enhancements text for 17.1:
> pd.read_* functions can now also accept pathlib.Path, or py._path.local.LocalPath objects for the filepath_or_buffer argument. (GH11033) 

all read_* functions should support pathlib.Path now. It works for me with `read_csv` but not for `read_hdf`. 
Interestingly, I find in the squashed PR for this issue, 0d3dcbb, only a comment regarding `read_csv` and `read_table`, while the merge 82f0033 talks about `read_*`. Is there something missing for `read_hdf` ?

**Comment by jreback** [comment]
yeh, this was not tested on all of the IO formats. pretty sure that ``csv/excel/stat/msgpack/json`` should work as they all use the same io calls. HDF uses a slightly different one as it doesn't support reading from buffers in the same way.

So need tests for each of these formats (and not just the IO call itself) on read/to
HDF test/fix

cc @flying-sheep

**Comment by flying-sheep** [comment]
jup, [you told me](https://github.com/pydata/pandas/issues/11033#issuecomment-138912214)

> [here](https://github.com/pydata/pandas/blob/master/pandas/io/common.py#L127) is where all of this path inference is done (well not 100% sure of all but vast majority)

PS: the link is broken by now (tip: press <kbd>y</kbd> on some github page to get a canonical url so that this doesn’t happen anymore)

**Comment by michaelaye** [comment]
`to_csv` also does not support pathlib.Path yet. (v0.17.1)
