### ISSUE TITLE
No more label rotation when secondary_y=True on the same data

### ISSUE THREAD

**Issue by alybel** [pydata/pandas#11782]
Pandas version I am using: 0.16.2

My initial chart is produced like this: 
```
combined['fraud_count'].unstack(-2).unstack(-1).fillna(0).plot()
```
which looks very neat and perfect, as expected.

In the next step, I am trying to use the secondary_y feature like this: 
```
combined['fraud_count'].unstack(-2).unstack(-1).fillna(0).plot()
combined['fraud_amount'].unstack(-2).unstack(-1).fillna(0).plot(secondary_y=True)
```
which doesn't produce a secondary axis. So, I do it this way: 
```
ax = combined['fraud_count'].unstack(-2).unstack(-1).fillna(0).plot()
ax2 = combined['fraud_amount'].unstack(-2).unstack(-1).fillna(0).plot(secondary_y=True, ax = ax)
```
which produces the chart I want. 

**However, the labels on the x-axis are not rotated any more but written horizontally and overlapping each other.**

I was trying some ways to get this fixed but none of them really seemed to work. 

I believe this is a quite common thing to do, so I'd be happy to hear how this could be done. Any help is welcome!

**Comment by TomAugspurger** [comment]
@alybel can you give a copy-pastable example and paste an image of what looks wrong? I think you'd be better off just clearing the xticklabels from the first plot.

```python
In [22]: df = pd.DataFrame(np.random.randn(10, 2), columns=['a', 'b'])

In [23]: ax = df.a.plot()

In [24]: ax.set(xticklabels=[])
Out[24]: [[]]

In [25]: df.b.plot(ax=ax, secondary_y=True)
```

**Comment by alybel** [comment]
I tried your suggestion, but it didn't quite work as hoped. 

I now run the following commands with sample data (just copy and paste):
```
import pandas as pd

df = pd.DataFrame.from_dict({'Company': {0: 'Company ABCDE',
  1: 'Company DEFGH',
  2: 'Company IOERGIUW',
  3: 'Company ERGWG',
  4: 'Company ERGEGRE',
  5: 'Company ERGWGH',
  6: 'Company ABCDE',
  7: 'Company DEFGH',
  8: 'Company IOERGIUW',
  9: 'Company ERGWG',
  10: 'Company ERGEGRE',
  11: 'Company ERGWGH'},
 'Metric1': {0: 1,
  1: 2,
  2: 3,
  3: 4,
  4: 5,
  5: 6,
  6: 6,
  7: 5,
  8: 1,
  9: 2,
  10: 4,
  11: 3},
 'Metric2': {0: 3,
  1: 4,
  2: 5,
  3: 6,
  4: 7,
  5: 8,
  6: 5,
  7: 8,
  8: 3,
  9: 7,
  10: 6,
  11: 4},
 'month': {0: 1,
  1: 1,
  2: 1,
  3: 1,
  4: 1,
  5: 1,
  6: 2,
  7: 2,
  8: 2,
  9: 2,
  10: 2,
  11: 2},
 'year': {0: 2015,
  1: 2015,
  2: 2015,
  3: 2015,
  4: 2015,
  5: 2015,
  6: 2015,
  7: 2015,
  8: 2015,
  9: 2015,
  10: 2015,
  11: 2015}})

df = df.set_index(['Company', 'year', 'month'])
ax = df.Metric1.unstack([-1,-2]).plot(kind='bar')
df.Metric2.unstack([-1,-2]).plot(secondary_y=True, ax = ax)
```
The last line adds a plot with a secondary y-axis as expected. However unfortunately, the x -axis labels are now displayed horizontally, which destroys the readibility. 

Thanks for any help on this!

**Comment by TomAugspurger** [comment]
Didn't realize that you were mixing plot types. Bar and line will have different ticks in general since bar will plot every label. I guess you could try reversing the order?

```python
In [10]: ax = df.Metric2.unstack([-1,-2]).plot()
In [11]: ax.set(xticks=[])
Out[11]: [[]]
In [13]: df.Metric1.unstack([-1,-2]).plot(kind='bar', ax=ax)
Out[13]: <matplotlib.axes._subplots.AxesSubplot at 0x10b6b1a20>
```

You're probably better off doing this all in matplotlib though. Once you start needing custom stuff the higher-level pandas API breaks down.

**Comment by alybel** [comment]
Thanks a lot, this clarified it!
