### ISSUE TITLE
Deprecate options.display.mpl_style

### ISSUE THREAD

**Issue by jorisvandenbossche** [pydata/pandas#11783]
Matplotlib now has support for enabling different styles, we don't use this anymore in our docs, and it only gives problems to keep supporting this with newer matplotlib versions (see eg #11727).

So to raise @TomAugspurger idea there in an issue: let's just deprecate it?

@sinhrks @jreback

**Comment by jreback** [comment]
lgtm

**Comment by sinhrks** [comment]
:+1:

**Comment by jreback** [comment]
someone want to do a PR for this?

**Comment by lvjiujin** [comment]
good, I know, if you use this option, there will be an error like 'No such keys(s): 'display.mpl_style'' 
we'd better not use it.
