### ISSUE TITLE
Wrong behavior due to Pandas : dict with the same key based on tuple extracted from DataFrame

### ISSUE THREAD

**Issue by Tux1** [pydata/pandas#11797]
Can you explain the behavior of the following :

    rows = pd.DataFrame([
    	(0, np.nan, np.nan, 'toto'),
    	(1, np.nan, np.nan, 'tata')
    ])
    
    dico = {}
    
    for row in rows.itertuples():
    	k = (row[2], row[3])
    	v = row[4]
    	print('hash(k) : {0}'.format(hash(k)))
    	v_prev = dico.setdefault(k, None)
    	if v_prev is None:
    		dico[k] = v
    
    print('dico : {0}'.format(dico))

Result :

    hash(k) : 3713080549408328131
    hash(k) : 3713080549408328131
    dico : {(nan, nan): 'toto', (nan, nan): 'tata'}

I manage to create a dict with the same key `(np.nan, np.nan)`. I have got this behavior only with `np.nan`. With `None` or whatever else, I get the usual result with only one key.

You can find some hints in my SO question : http://stackoverflow.com/questions/34163497/wrong-behavior-dict-with-the-same-key-based-on-tuple

It seems to be linked to `RichCompare`. The comparison operator `is` is not used in this case

**Comment by TomAugspurger** [comment]
What's the pandas issue here? Your iterating over a DataFrame but I don't see anything wrong with that.

**Comment by TomAugspurger** [comment]
I'm going to say this is working as intended (although maybe not as expected! working with NaN is trick). It's the same behavior as the standard library

```python
In [1]: d = {}

In [2]: d[(float('nan'),)] = 1

In [3]: d[(float('nan'),)] = 2

In [4]: d
Out[4]: {(nan,): 1, (nan,): 2}
```

**Comment by kawochen** [comment]
what's happening is that you don't get a `numpy.nan` out from a `DataFrame` -- you get `numpy.float64('nan')`, which doesn't behave like `numpy.nan`.

**Comment by Tux1** [comment]
Thank you @kawochen for your bright explanation. Do you know where I can get documentation about that ? and about RichCompare implementation in numpy especially

**Comment by kawochen** [comment]
@Tux1 numpy/numpy/core/src/umath/umathmodule.c
I don't think it has much to do with how `numpy` implements rich comparison for anything, tho.  You only need to know that `float64('nan') != float64('nan')`, which as @TomAugspurger said works just like the standard library `float('nan')`.  The reason `np.nan` seems to behave differently in dict is because it is the same object inside `numpy` that is being referred to, just like the global singletons (`None`, `...`, etc.) in python.  If you do `yourmodule.nan = float64('nan')` and use `yourmodule.nan` whenever you need a `nan`, then you get the behavior of `numpy`'s `nan`.

**Comment by Tux1** [comment]
Yes of course, I understand better. Thank you

On mer., déc. 9, 2015 at 6:30 AM, pydata/pandas
<reply@reply.github.com>
wrote:
@Tux1 [https://github.com/Tux1] numpy/numpy/core/src/umath/umathmodule.c
I don't think it has much to do with how numpy implements rich comparison for anything, tho. You only need to know that float64('nan') != float64('nan') , which as @TomAugspurger [https://github.com/TomAugspurger] said works just like the standard library float('nan') . The reason np.nan seems to behave differently in dict is because it is the same object inside numpy that is being referred to, just like the global singletons ( None , ... , etc.) in python. If you do yourmodule.nan = float64('nan') and use yourmodule.nan whenever you need a nan , then you get the behavior of numpy 's nan .

—
Reply to this email directly or view it on GitHub
[https://github.com/pydata/pandas/issues/11797#issuecomment-163115468] .[https://github.com/notifications/beacon/AGWku8LcPCt7hGbsamL6igH_v_mh6a92ks5pN7QLgaJpZM4GxUVg.gif]
