### ISSUE TITLE
pickling error when doing using dataframe with multiprocessing

### ISSUE THREAD

**Issue by andersonjacob** [pydata/pandas#11791]
When using python 3.4.3 or 3.5.0 and pandas 0.16.2, this simple example works

```
import pandas as pd
import multiprocessing as mp

def squareIt(row):
    return row[0]**2, row[1]**2

df = pd.DataFrame({'a': range(100), 'b': range(100)})

with mp.Pool(2) as pool:
    sq = pool.imap(squareIt, df.itertuples(False), chunksize=10)
    for x in sq:
        print(x)
```

when upgrading to 0.17.1 there is this error.

```
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/opt/Python-3.4.3/lib/python3.4/multiprocessing/pool.py", line 295, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "/opt/Python-3.4.3/lib/python3.4/multiprocessing/pool.py", line 689, in next
    raise value
  File "/opt/Python-3.4.3/lib/python3.4/multiprocessing/pool.py", line 383, in _handle_tasks
    put(task)
  File "/opt/Python-3.4.3/lib/python3.4/multiprocessing/connection.py", line 206, in send
    self._send_bytes(ForkingPickler.dumps(obj))
  File "/opt/Python-3.4.3/lib/python3.4/multiprocessing/reduction.py", line 50, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'pandas.core.frame.Pandas'>: attribute lookup Pandas on pandas.core.frame failed
```

Is there a better way to do some simple multi-threaded processing of a dataframe.  This had worked very well for me in the past.  I would rather not rewrite all of my analysis, but if there is a better way I could be convinced.

Thanks.

**Comment by MaximilianR** [comment]
I believe that's trying to pickle a namedtuple. You can either use a different pickler (dill works great), or use a different method than `itertuples` - you could just send each `Series`?

Note that pickling is fairly expensive, and so to make this worthwhile you're going to need to be doing a lot of compute on each piece of data. That example is going to be much faster in a single process.

**Comment by andersonjacob** [comment]
Yes this is just an example.  My normal dataframe is a few million rows and the computations are much more extensive.  I don't think that doing each series would work because the actual computation needs the information from the entire row.

I'll look into dill, but It would be nice to have back this basic functionality.

**Comment by MaximilianR** [comment]
By `Series`, I meant: don't send the row as a tuple. Instead do `df.iloc[i,:] for i in range(len(df.index))`, so you're not sending the rows as Series rather than tuples.

(that code is just a sketch - there are going to be cleaner ways to do it)

**Comment by shoyer** [comment]
You can use `df.itertuples(name=None)` to make these regular rather than named tuples.

This does seem to be an unfortunate downside of switching `itertuples` to return named tuples.

**Comment by MaximilianR** [comment]
If it's really important, I don't think there's anything inherently stopping this (SO has suggestions here: http://stackoverflow.com/questions/16377215/how-to-pickle-a-namedtuple-instance-correctly). 

We use dill (https://github.com/uqfoundation/dill) a lot, which handles all this. Highly recommended (and easy to swap out pickle for)

**Comment by andersonjacob** [comment]
I'm not really hopeful about passing `Series` as they do type conversion that could screw up integers.  I've read the documentation about this in Pandas and don't actually disagree with it.  I just know that I need to be careful of it.  I think that the better way to do it with series would be the `df.iterrows()` and then have your function deal with the index and `Series`.

@shoyer Your solution sounds like just what I'm looking for.  I guess when they switched to `namedtuples` they also added this parameter since I don't think it was there before.

@MaximilianR I haven't looked into `dill`.  In my research I think I saw that there is a fork of `multiprocessing` that uses dill over pickle.  I don't remember now off the top of my head about that one.  I may look into it some, but @shoyer seems to have a very simple solution.

Thanks for the help.  I guess correctly pickling `namedtuples` is beyond the scope of `pandas` library.

**Comment by jreback** [comment]
@andersonjacob what you are done is already done quite well (and a lot more and generally) by [dask](http://dask.readthedocs.org/en/latest/)

**Comment by andersonjacob** [comment]
@jreback I agree that dask looks interesting and I'm going to look into it more.  It is really overkill for what I'm trying to do.  I really need to parallel apply a function row by row without casting my ints to floats and have it return a complex set of objects.  Multiprocessing does that with only barely any additional code compared to my example above.  My quick look as dask tells me that it is a powerful and general tool and worth my future research.  Given my particular problem, I doubt it can actually do better than I already have done.
