### ISSUE TITLE
read_csv. when file has many np.object dtype columns consumes a lot of memory

### ISSUE THREAD

**Issue by educhana** [pydata/pandas#11803]
This is related to the old memory issues that pandas had when reading csv files. Now the situation is much better, but I've found that when the csv file has many string columns the memory consumption is increased a lot. Having numeric dtypes is handled correctly.

In pandas/io/parsers.py - TextFileReader.read method:
```python
ret = self._engine.read(nrows)

if self.options.get('as_recarray'):
    return ret

# May alter columns / col_dict
index, columns, col_dict = self._create_index(ret)

df = DataFrame(col_dict, columns=columns, index=index)
```

The first line reads the file correctly with linear memory usage, but the final line constructing the DataFrame has a memory peak which -in my case- seems to near double the memory needed. 

I've traced the issue down to the internals.py - block manager - form_blocks method. When treating the np.object dtypes is copying the data, and thus the memory peak.

Any ideas about how this can be mitigated?

**Comment by TomAugspurger** [comment]
@educhana is your text data suitable for Categorization (few distinct values relative to the number of rows)? That would be a relatively easy way to cut down the peak memory usage.

**Comment by educhana** [comment]
Thanks,

This is interesting, but not really applicable in this case, that contains many client_id, product_id with many possible values. 

Anyway, I was talking about the general case. Pandas is using too much memory than it should and has performance problems managing csv files that are loaded in R -for example-  with no problem at all.

**Comment by jreback** [comment]
@educhana 

pandas is quite good on the memory vs speed tradeoff vs most other parsers and R in particular. Most good parses uses 2x of the incoming memory; yes it can be worked around, but its quite expensive to do this (the tradeoff vs speed). 

If you are actually hitting a peak memory issue, then you need to either chunk read, use [dask](https://dask.readthedocs.org/) for OOC operations that auto-chunk, convert to a different (binary format), or select columns. All of these have tradeoffs as well. 

Furthermore the pandas model is to return a new copy of data when operations are performed, you will almost always needs > 2x your data to have a reasonable system for analysis; even then if you are bumping the memory limits, you can have to be very very careful about garbage collection and such.

**Comment by jreback** [comment]
closing as this is a well known idea/issue.

**Comment by educhana** [comment]
Thanks for the clarification,

I agree with you. Sooner or later you'll reach the memory limit and the reasoning about needing 2x is right.
