### ISSUE TITLE
Series.hist() potential bug.

### ISSUE THREAD

**Issue by mmitsui** [pydata/pandas#11807]
The following line of code prints the wrong distribution:

```python
import matplotlib.pyplot as plt
import pandas as pd

# df is a pd.DataFrame object.  Define df here...

plt.figure();
(df['x1'] - df['x2']).hist(normed=True)
plt.show();
```
It should print the green distribution, but it prints the blue instead (which is not even a proper distribution).  

I'm including the exact lists I used, x1 and x2, below.  These are ordered lists, so please insert them into your DataFrame accordingly.

(Pardon my presentation of the x-labels in the green figure.  Just shift them 1/2-bar length to the right.)

```python
x1 = [4, 4, 6, 4, 4, 4, 4, 5, 5, 6, 4, 4, 5, 6, 4, 4, 4, 4, 5, 5, 6, 5, 3, 6, 6, 7, 7, 7, 4, 6, 4, 5, 4, 5, 4, 3, 7, 7, 7, 5, 4, 5, 4, 3, 5, 4, 4, 5, 6, 5, 4, 4, 4, 5, 6, 4, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 6, 7, 6, 7, 7, 7, 7, 6, 7, 7, 7, 5, 7, 7, 7, 7, 7, 5, 7, 5, 5, 7, 6, 7, 6, 4, 6, 7, 6, 7, 1, 6, 7, 2, 7, 4, 6, 7, 6, 6, 4, 6, 7, 7, 7, 5, 7, 6, 7, 4, 6, 7, 7, 6, 5, 7, 6, 6, 6, 6, 5, 5, 5, 5, 5, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 4, 7, 4, 5, 7, 6, 7, 4, 5, 7, 7, 7, 7, 7, 7, 7, 7, 4, 4, 5, 5, 7, 7, 7, 7, 6, 7]

x2 = [4, 4, 6, 3, 4, 4, 4, 5, 6, 6, 4, 4, 5, 6, 4, 4, 4, 4, 5, 5, 5, 5, 5, 6, 6, 7, 7, 7, 5, 7, 2, 4, 4, 4, 6, 7, 7, 7, 7, 4, 5, 4, 5, 3, 5, 4, 5, 5, 6, 5, 5, 5, 4, 5, 6, 4, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 4, 7, 7, 7, 7, 7, 7, 7, 5, 5, 7, 7, 7, 5, 5, 5, 7, 7, 7, 7, 7, 7, 7, 7, 7, 6, 5, 6, 6, 5, 6, 7, 7, 7, 5, 7, 7, 6, 5, 5, 6, 6, 6, 5, 7, 5, 5, 5, 5, 4, 4, 3, 4, 7, 4, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 6, 6, 4, 4, 6, 5, 6, 4, 5, 7, 5, 7, 7, 7, 7, 7, 7, 5, 5, 7, 7, 7, 7, 7, 7, 7, 7]
```

![figure_correct](https://cloud.githubusercontent.com/assets/1490869/11700208/7aaacb3e-9e96-11e5-8e9a-4146ed81f2ee.png)

![figure_incorrect](https://cloud.githubusercontent.com/assets/1490869/11700205/77e43138-9e96-11e5-8cf4-98458b0452db.png)

**Comment by TomAugspurger** [comment]
Do you want a bar plot?

```python
In [10]: (df.x1 - df.x2).value_counts(normalize=True).sort_index().plot.bar()
```

Histograms bins and aggregates according to `n_bins`. See the matplotlib [docs](http://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.hist)

**Comment by TomAugspurger** [comment]
Going to close, let me know if a bar plot wasn't what you wanted.

**Comment by mmitsui** [comment]
The above code also unfortunately only prints the blue plot (a wrong solution), not the green one.

**Comment by TomAugspurger** [comment]
Can you be more specific about what is wrong with it?

This

```python
In [10]: (df.x1 - df.x2).value_counts(normalize=True).sort_index().plot.bar()
```

gives me this, which I think is identical to your desired outcome.

![gh](https://cloud.githubusercontent.com/assets/1312546/11781289/660c47d4-a22e-11e5-994f-fed13b5e2b83.png)

Maybe list out the x and y coordinates that you expect for each bar.

**Comment by mmitsui** [comment]
Ah, thanks for showing me the plot!  After seeing your plot, I decided to upgrade some of my packages.  The hist() command still doesn't give me the right output, but the command that you gave me now does.  Thanks! (Unfortunately I forgot to record the previous version of pandas before upgrading.)
