### ISSUE TITLE
Specify column format by name 

### ISSUE THREAD

**Issue by djchou** [pydata/pandas#11817]
Is it possible to specify a column format by the column name?

i.e. Dataframe has two columns, both containing a array of integers.  It would be great if the two columns could have different formats (i.e. one with commas, the other without, etc.)

**Comment by jreback** [comment]
see http://pandas.pydata.org/pandas-docs/stable/io.html#writing-a-formatted-string

use the formatters arg with a dict of column to function

**Comment by jreback** [comment]
```
In [33]: df = DataFrame({'A' : [1,2,3],'B': [4,5,6]})

In [34]: df.to_string(formatters={'A' : lambda x: "{0}.0".format(x)})
Out[34]: u'    A  B\n0 1.0  4\n1 2.0  5\n2 3.0  6'
```
