### ISSUE TITLE
"NA" value from Excel read by Pandas as nan

### ISSUE THREAD

**Issue by fitsoft** [pydata/pandas#11839]
When doing a:
df = pd.read_excel('cb2.xlsx') in the column 'Zone', in which there are strings like "APAC", "EUR", "NA"
Surprisingly, the value "NA" is interpreted by pandas as nan

[cb2.xlsx](https://github.com/pydata/pandas/files/61735/cb2.xlsx)

**Comment by jreback** [comment]
see the docs [here](http://pandas.pydata.org/pandas-docs/stable/io.html#na-values) and in the doc-string. NA is by default treated as missing.
