### ISSUE TITLE
Error storing cateogory values in HDFStore: NotImplementedError: cannot store a category dtype

### ISSUE THREAD

**Issue by esvhd** [pydata/pandas#11843]
Hi,

I'm having problems storing a dataframe with categorical columns as well some float64 and datetime64 columns into a HDFStore. 

The docs seems to suggest that you can store category values in HDF5 since `pandas v0.15.2` [here](https://pandas-docs.github.io/pandas-docs-travis/io.html#io-hdf5-categorical), but I got a `NotImplementedError` with my data and the code below. 

Did some googling but couldn't find much on this topic. Is this a bug or am I doing something wrong here? From the error message it seems to be related something that is not yet implemented? 

Environment:
Anaconda 2.4.1, Python 2.7.11
Pandas 0.17.1
PyTables 3.2.2

My DataFrame looks like this:

    quotes.info()
    output:
    <class 'pandas.core.frame.DataFrame'>
    Int64Index: 6295150 entries, 0 to 1474363
    Data columns (total 12 columns):
    price         float64
    broker        category
    g_spread      float64
    date          datetime64[ns]

When I tried to store it in a HDFStore I got a **`NotImplementedError: cannot store a category dtype`** error message. Here is what I did:

    test_store = pd.HDFStore('z:/pydata/test.h5', mode='w', format='table')
    test_store.put('quotes', quotes)

The error trace is as follows:

    ---------------------------------------------------------------------------
    NotImplementedError                       Traceback (most recent call last)
    <ipython-input-39-57832b6474fe> in <module>()
        ----> 1 test_store.put('quotes', quotes)

    C:\Developer\Anaconda2\lib\site-packages\pandas\io\pytables.pyc in put(self, key, value, format, append, **kwargs)
        812             format = get_option("io.hdf.default_format") or 'fixed'
        813         kwargs = self._validate_format(format, kwargs)
    --> 814         self._write_to_group(key, value, append=append, **kwargs)
        815 
        816     def remove(self, key, where=None, start=None, stop=None):

    C:\Developer\Anaconda2\lib\site-packages\pandas\io\pytables.pyc in _write_to_group(self, key, value, format, index, append, complib, encoding, **kwargs)
       1250 
       1251         # write the object
    -> 1252         s.write(obj=value, append=append, complib=complib, **kwargs)
       1253 
       1254         if s.is_table and index:

    C:\Developer\Anaconda2\lib\site-packages\pandas\io\pytables.pyc in write(self, obj, **kwargs)
       2787             # I have no idea why, but writing values before items fixed #2299
       2788             blk_items = data.items.take(blk.mgr_locs)
    -> 2789             self.write_array('block%d_values' % i, blk.values, items=blk_items)
       2790             self.write_index('block%d_items' % i, blk_items)
       2791 

    C:\Developer\Anaconda2\lib\site-packages\pandas\io\pytables.pyc in write_array(self, key, value, items)
       2498 
       2499         if com.is_categorical_dtype(value):
    -> 2500             raise NotImplementedError("cannot store a category dtype")
       2501 
       2502         if not empty_array:

    NotImplementedError: cannot store a category dtype

**Comment by jreback** [comment]
You are trying to store in a fixed store, which is not implemented. table stores are allowed.

passing ``format='table'`` to the constructor of ``HDFStore`` doesn't do anything. You need to specify on a per object basis.

```
In [2]: df = DataFrame({'A' : [1,2,3], 'B' : Series(list('aab')).astype('category')}) 

In [3]: df
Out[3]: 
   A  B
0  1  a
1  2  a
2  3  b

In [4]: df.dtypes
Out[4]: 
A       int64
B    category
dtype: object

In [5]: s = pd.HDFStore('test.h5')

In [6]: s.put('df',df)
---------------------------------------------------------------------------
NotImplementedError: cannot store a category dtype

In [8]: s.append('df2',df)

In [9]: s
Out[9]: 
<class 'pandas.io.pytables.HDFStore'>
File path: test.h5
/df2                                     frame_table  (typ->appendable,nrows->3,ncols->2,indexers->[index])             
/df2/meta/values_block_1/meta            series_table (typ->appendable,nrows->2,ncols->1,indexers->[index],dc->[values])
```

**Comment by esvhd** [comment]
Thanks @jreback ! This solved the problem. 

For completeness, one additional step that I had to do was to make sure that text strings used as categories are encoded as uft-8. Otherwise I get a unicode not supported exception. 

Great to know that `format='table'` in the constructor does nothing!

Btw, saw your talk at PyData NYC 2015, loved it.
