### ISSUE TITLE
efficient read+concat of multiple HDF files?

### ISSUE THREAD

**Issue by potash** [pydata/pandas#11849]
I have several HDF files about 500k x 500 (same columns and dtypes, mostly floats and strings). Currently I loop through and read them and then concatenate:

```
dfs = [pd.read_hdf(filename, 'df') for filename in filenames]
df = pd.concat(dfs)
```
Each of the read operations takes about 15 seconds but the concatenation takes minutes! Is there any way to speed this up? Since I know the dimensions in advance, is there any way to preallocate `df` and read into it?

**Comment by potash** [comment]
Has been discussed here: http://stackoverflow.com/questions/22750228/pytables-pandas-combining-reading-mutliple-hdf5-stores-split-by-rows

**Comment by shadymohsen** [comment]
@potash  could u please upload your full code please. thank you in advance
