### ISSUE TITLE
SettingWithCopyWarning false positive when using .loc

### ISSUE THREAD

**Issue by blitzd** [pydata/pandas#11845]
I have the following code, which produces the SettingWithCopyWarning:

```
segments = df_source1.Code.unique().tolist()

for segment in segments:
    seg = segment[-1]
            
    df_source1.loc[df_source1.Code == segment, 'Seg'] = seg
```

```
C:\Anaconda3\envs\jupyter\lib\site-packages\pandas\core\indexing.py:266: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[key] = _infer_fill_value(value)
```

I wouldn't expect to receive this warning since I'm using .loc exactly as it suggests I should be. It did occur to me that I could probably find a much better way to do this via apply, but I still run into this warning popping up all over the place, and it always makes me think I'm doing something wrong (which in this case I may be, performance wise).

**Comment by jreback** [comment]
``df_source1`` itself is a copy is why the warning is issued, not the lines you are pointing.
e.g. you are doing something like:

``df_source1 = df[....]`` higher in your code

The warning is somewhat generic as we cannot always tell exactly where your code is affected.

**Comment by blitzd** [comment]
That makes more sense - and I was able to eliminate the copy from earlier on and get rid of the warning now, thanks!
