### ISSUE TITLE
xz compression in to_csv()

### ISSUE THREAD

**Issue by ohadle** [pydata/pandas#11852]
I use compression directly in DataFrame.to_csv() to save on disk space / IO. Would be nice to have support for xz compression there.

Similar to https://github.com/pydata/pandas/issues/8654, but I think in to_csv this has more added value.

**Comment by jreback** [comment]
I suppose if someone wanted to add additional compressions, this would be ok.

can you point to the canonical package which implements this compressor?

**Comment by ohadle** [comment]
I haven't tried it myself, but it looks like for python 3 it would be https://docs.python.org/3/library/lzma.html. For 2.7 this looks like it: https://github.com/peterjc/backports.lzma

**Comment by jreback** [comment]
sure that looks reasonable.

**Comment by ohadle** [comment]
Thanks! I'll be using this immediately when the version comes out.
