### ISSUE TITLE
Define frequencies like "Last Xday of month"

### ISSUE THREAD

**Issue by wesm** [pydata/pandas#1185]
`WeekOfMonth` can't readily generate, say, US Thanksgivings which are the last Thursday of November each year

**Comment by chrisgilmerproj** [comment]
I believe this is done: https://github.com/pydata/pandas/blob/master/pandas/tseries/offsets.py#L1118-L1192

**Comment by jorisvandenbossche** [comment]
@chrisgilmerproj indeed it looks like that is the case! Thanks for noticing 

It was closed by #5004

**Comment by jorisvandenbossche** [comment]
It is listed in the table in the docs (http://pandas.pydata.org/pandas-docs/stable/timeseries.html#dateoffset-objects), but if you want to include a more expanded example of its usage, certainly welcome!
