### ISSUE TITLE
Code-of-Conduct?

### ISSUE THREAD

**Issue by alison985** [pydata/pandas#11873]
Hi,

I'm just wondering what your code of conduct is for this project?

Thanks,
Alison

**Comment by TomAugspurger** [comment]
Nothing formal at the moment, AFAIK it hasn't come up.

This would be a good discussion for the [mailing list](https://groups.google.com/forum/#!forum/pydata), as not everyone in the community tracks the issues. @alison985 could you propose something there?

**Comment by jreback** [comment]
I think we should steal this from other projects. prob ipython, numpy, scipy and others have this. we can modify.

**Comment by jorisvandenbossche** [comment]
NumFOCUS has apparantly a Code of Conduct: http://www.numfocus.org/code-of-conduct.html, and expect from all their sponsored and affiliated projects to adopt a code of conduct

**Comment by TomAugspurger** [comment]
That sounds good for me (that's based off version 1.2, there is a version [1.3 available](http://contributor-covenant.org/version/1/3/0/) too).

I can send out a notice to the mailing list if you all think we should formally adopt it.

**Comment by jorisvandenbossche** [comment]
Yes, sending to the mailing list is good 
Here is the discussion on the Jupyter mailing list about it: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/jupyter/XlunILbJUJ8/t7nIumg0AAAJ

Apart from the questions whether to adopt it and where to put it, the main question will be about how to report problems I think. In the convenant text, it is stated to contact a project maintainer / certain email address. In the jupyter discussion, Fernando suggest to

> An alternative would be to officially list a group in charge of handling these reports, staffed by say three volunteers.  By default we could suggest that reports be sent to all three to increase reporting response speeds, but that gives the option to the reporter of omitting someone if they feel uncomfortable with one of them for any reason (such as that person being the source of conflict, for example).

And on the NumFOCUS page, there is a NumFOCUS contact. But it is not clear to me if it is the intention that subprojects should use that.

**Comment by hayd** [comment]
Firstly: Big +1.

> such as that person being the source of conflict

(Clearly we would hope that this was an edge case!) IMO Sending emails to a private list has the benefits of a bigger paper trail so having people send complaints to a single person should NOT be the default - which I fear it would be if individual's email addresses were published there.

From the covenant:

> will result in a response that is deemed necessary and appropriate to the circumstances

What is the suggestion that the outcomes could be? Is this decided by a single person on the team? IMO this process must be transparent (whilst individual cases remain private).

I was going to suggest having a private list where these things can be discussed (if need be). This came up in julia quite recently, where someone was eventually banned from posting on GH, it helped for collaborators to privately discuss and agree on this (understandably hard) decision.

**Comment by TomAugspurger** [comment]
For the record: https://groups.google.com/forum/#!topic/pydata/ulfquSriMR0

**Comment by shoyer** [comment]
I'm also supportive of adopting a COC -- we've had at least one case I can think of in the past where this would be helpful. The NumFOCUS one looks fine to me.

**Comment by jreback** [comment]
@TomAugspurger you want to put the NumFOCUS one up as a PR?

**Comment by jart** [comment]
Code of conduct? Hahaha. I can't believe people take those things seriously. It's just childish rubbish promoted by people with a political agenda. Keep that nonsense out of engineering.

We don't need a code of conduct. FOSS is the first culture, in the history of mankind, that's truly international, post-monetary, and discrimination on the basis of race, sex, age, etc. is impossible. Welcome to the Internet. It unites the human race. And hackers invented it.

So we already know what we're doing. We did nothing wrong. But that of course doesn't stop whining babies from demanding padded wall policies. I guess they'd rather cry more and practice entryism than write code.

So the proper response is to just laugh at them and close the issue.

**Comment by TomAugspurger** [comment]
Going to submit a PR with a draft today. I think the appropriate place is pydata/pydata-governance, and then we link to it from our README, the website, the docs maybe, Stackoverflow tag, mailing list.

In [this](https://groups.google.com/d/msg/jupyter/XlunILbJUJ8/JdTRMtVeAAAJ) mail @ellisonbg mentioned he would add one to their governance repo, but I don't see one (Brian, was it added elsewhere? Or consider this a nudge if it fell through the cracks :wink:).

**Comment by jorisvandenbossche** [comment]
Yep, putting it https://github.com/pydata/pandas-governance seems good!

**Comment by TomAugspurger** [comment]
Submitted at https://github.com/pydata/pandas-governance/pull/2

**Comment by jorisvandenbossche** [comment]
This is moved to the pandas governance repo (https://github.com/pydata/pandas-governance/pull/2), so closing here.
