### ISSUE TITLE
no "stacked" option in Series.plot

### ISSUE THREAD

**Issue by cfblaeb** [pydata/pandas#11884]
It would be nice if there was a "stacked" option for Series.plot like there is for DataFrame.plot.

**Comment by jorisvandenbossche** [comment]
Can you give an example of how the result would look like? 
As for a dataframe, it are the different *columns* that are stacked or put next to each other (if not stacked). But when plotting a series, you only have one series of values to make a barplot for.

**Comment by cfblaeb** [comment]
So a barplot from a Series is, as you describe, a bar for each value. So I would expected a stacked bar plot of a Series to simply stack those individual bars on top of each other.

**Comment by jorisvandenbossche** [comment]
So to get a barplot with one bar?

You can always convert your series in a dataframe with one row, and then use `stacked=True`, as in `s.to_frame().T.plot(kind='bar', stacked=True)`

**Comment by cfblaeb** [comment]
Yes one, stacked, bar.

**Comment by jorisvandenbossche** [comment]
I would personally say it is not needed to add this to the series plot method (somewhat inconsistent + easily done by converting to dataframe row).

@TomAugspurger @sinhrks other opinions?

**Comment by TomAugspurger** [comment]
I'd also say that it's unnecessary

**Comment by sinhrks** [comment]
Agreed to not necessary. It sounds ``stacked=True`` to have inconsistent behavior (stacking over columns for DataFrame, over rows for Series).

@fblaeb Pls reopen if we misunderstand, or you have an idea for better API.
