### ISSUE TITLE
ENH/SQL: provide single value to 'dtype' argument in to_sql as dtype for all columns

### ISSUE THREAD

**Issue by jorisvandenbossche** [pydata/pandas#11886]
Idea from http://stackoverflow.com/questions/34383000/pandas-to-sql-all-columns-as-nvarchar

You can specify the sql type using the `dtype` argument in `to_sql`. Now, this argument has to be a dict (mapping of column name -> type). 
Letting `to_sql` recognize a single value as the sql type for all columns is not that difficult to add.

So instead of this:

```
df.to_sql(...., dtype={col_name: sqlalchemy.types.NVARCHAR for col_name in df})
```

you can do this:
```
df.to_sql(...., dtype=sqlalchemy.types.NVARCHAR)
```

**Comment by RahulHP** [comment]
Will it be alright if I:
1. First check if the dtype passed in is an instance of dict.
2. If Not, create a dictionary the same was as above ie. `{col_name: sqlalchemy.types.NVARCHAR for col_name in df}`
3. Pass this new dictionary onwards.

**Comment by oguzhanogreden** [comment]
It seems that this is not documented here: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_sql.html

**Comment by jorisvandenbossche** [comment]
@oguzhanogreden would you like to do a PR to add it?
