### ISSUE TITLE
DOC/DEV: update windows instructions for setting up dev environment for py3

### ISSUE THREAD

**Issue by Vutsuak16** [pydata/pandas#11901]
I am trying to set up a development environment for pandas in anaconda.
But I get the following error, while installing dependencies for windows:-
on running "conda install -n pandas_dev libpython"

Error: Unsatisfiable package specifications.
Hint: the following packages conflict with each other:
  - libpython
  - python 3.5*

is conda not compatible with python 3.5??

**Comment by jreback** [comment]
libpython is only necessary for py2 on Windows 
the conda recipe knows this but requirements.txt does not
I suppose this could be updated in the docs

**Comment by Vutsuak16** [comment]
@jreback i could update the docs , but the doc build won't work for sphinx version >1.3 . Mine is 1.3.1
When would this issue be solved??

**Comment by jreback** [comment]
iirc try a newer version of Sphinx / 1.3.3 works

**Comment by jreback** [comment]
note if on Windows u actually need to have a visual studio installed (for py3) so these instructions are a bit more complicated

**Comment by Vutsuak16** [comment]
well yeah and for python version>= 3.5 we actually need vc 2015

**Comment by jreback** [comment]
yeah these are a bit more work to setup
ideally we would have links directly to what u need to install (everything is free)

**Comment by Vutsuak16** [comment]
yeah I would love to work on updating the docs.  Just created a whole development environment on windows to edit docs, gave  me hell of a  time. Don't want other people to face that

**Comment by jorisvandenbossche** [comment]
@jreback I think this is closed in the meantime by https://github.com/pydata/pandas/pull/12428?

@Vutsuak16 Can you have a look at the latest contributing instructions to see if there is still something missing?

**Comment by Vutsuak16** [comment]
@jorisvandenbossche  well sure :)

**Comment by jreback** [comment]
yes, this is pretty good now.
