### ISSUE TITLE
Wrong behavior for df.groupby(())

### ISSUE THREAD

**Issue by kynnjo** [pydata/pandas#11922]
(I know that the following bug report will be dismissed, since what I refer to here as a "bug" is clearly intentional.  I'm posting it only for-the-record.)

Currently, an exception is raised if DataFrame.groupby is called with an empty tuple as argument:

    >>> df.groupby(by=())
    ...
    ValueError: No group keys passed!

Indeed, the underlying code is pretty direct about it:

    .../python2.7/site-packages/pandas/core/groupby.pyc in _get_grouper(obj, key, axis, level, sort)
       2277 
       2278     if len(groupings) == 0:
    -> 2279         raise ValueError('No group keys passed!')
       2280 

This is not the correct behavior for this condition.  It is therefore a "design bug".  The correct behavior should be returning a trivial grouping, consisting of exactly 1 group (containing, of course, all the rows).  This is consistent with the semantics "each group consists of the rows that agree on the grouping columns": when there are no grouping columns, all rows fall into one group.

In particular, the proposed behavior will render the expression

    df.groupby(by=tuple(df.columns))

valid even when `df` has no columns.  The expression above groups identical rows together, and it should work for all valid dataframes.  In a dataframe with no columns, all the rows are identical.

**Comment by kynnjo** [comment]
The title of this issue should be "Wrong behavior for df.groupby(by=())"

**Comment by jorisvandenbossche** [comment]
I think maybe the wording 'design *choice*' is better than 'design bug' :-) 
Because, there is indeed something to say for the logic you lay out, but there are certainly also good reasons to choose the current behaviour. You want to return one group, but if there is nothing to group by, how can you have a group? Eg, how would you call this group? `None`? What would be the index of the resulting frame if you do eg `df.groupby(by=()).mean()`?

**Comment by jreback** [comment]
yeah, IIRC this is really to catch errors as there are multiple specifiers ``by,axis,level``, so passing nothing is really a user error, where you want to fail fast.

Furthermore @jorisvandenbossche point is that this would essentially give rise to a single NaN keyed group, which are currently excluded. I suppose if that were relaxed (a bit non-trivial actually, #443) then this might be realistic.

**Comment by timwisefmg** [comment]
Groupby now supports the dropna argument. Can we please reopen this issue?

I propose that the group would be keyed by an empty tuple, inline with the keys for multi-column grouping.

**Comment by jreback** [comment]
you can open a new issue with a complete example (include what aggregations would do here)
