### ISSUE TITLE
Bug: UTC in to_datetime() not working in 0.17.1

### ISSUE THREAD

**Issue by yueatwork** [pydata/pandas#11934]
In the case below, setting `utc=True` in pandas.to_datetime actually removes the UTC attribute from the input:

    import pandas as pd
    import pytz
    start = pd.Timestamp('2014-01-01', tz=pytz.UTC)
    end = pd.Timestamp('2014-01-03', tz=pytz.UTC)
    date_range = pd.bdate_range(start, end)
    df = pd.DataFrame({'x':1}, index=date_range)
    df.index
    # DatetimeIndex([...], dtype='datetime64[ns, UTC]', freq='B')
    pd.to_datetime(df.index, utc=True)
    # DatetimeIndex([...], dtype='datetime64[ns]', freq='B')

the last function removes the UTC attribute from the input, even though `utc` is set to `True`.

This only happens in pandas 0.17.1.  pandas 0.16.x have a different implementation and does not have this issue.

**Comment by jreback** [comment]
This line should be: https://github.com/pydata/pandas/blob/master/pandas/tseries/tools.py#L308

``arg = arg.tz_convert(None).tz_localize('UTC')``

though to be honest this flag is just confusing IMHO. Users should simply use ``tz_convert``/``tz_localize`` after ``pd.to_datetime`` if desired. This feels too automagicy to me.
