### ISSUE TITLE
DataFrame.head(0) doesn't return an empty frame

### ISSUE THREAD

**Issue by trvrm** [pydata/pandas#11930]
```python
pandas.DataFrame({"stuff":[1,2,3,4,5]}).head(0)
```

returns
```python
   stuff
0      1
1      2
2      3
3      4
4      5

```

I would expect an empty data frame, in the same way that
```python
[1,2,3,4,5][0:0]
```
returns an empty list.

This is with pandas version 0.15.0.

The documentation (http://pandas.pydata.org/pandas-docs/version/0.17.0/generated/pandas.DataFrame.head.html) says ```head(n)``` returns 'first n rows', so I'd expect 0 rows if n is 0.

**Comment by trvrm** [comment]
The relevant line is https://github.com/pydata/pandas/blob/49b26600edf4c108a264c7982df8b28a46fac8b1/pandas/core/generic.py#L2135

```python
    def head(self, n=5):
        """
        Returns first n rows
        """
        l = len(self)
        if l == 0 or n==0:
            return self```

But  I don't see an explanation for this non-intuitive behaviour.

**Comment by jreback** [comment]
Looks like this was changed as a result of this issue: https://github.com/pydata/pandas/issues/5846

but don't really remember why this shouldn't return the same as ``.iloc[:n]``. I suppose its prob more consistent to return the empty.

@TomAugspurger @hayd any thoughts here

**Comment by TomAugspurger** [comment]
returning an empty frame is probably best.

**Comment by jreback** [comment]
yep, so prob a propogated 'bug'.

ok, @trvrm want to do a pull-request for this. will be an API change (but tiny).

**Comment by hayd** [comment]
+1

**Comment by trvrm** [comment]
https://github.com/pydata/pandas/pull/11937

**Comment by hayd** [comment]
FYI the Series and groupby version is already correct.
