### ISSUE TITLE
Excel encoding issue

### ISSUE THREAD

**Issue by methodds** [pydata/pandas#11949]
I want to read in Excel-Data (.xlsx) and have a problem with a wrong encoding of special characters. In the Excel-File, portuguese special characters, for example on "A", look like this:
![alt text](https://dl.dropboxusercontent.com/u/22352379/1excel_encoding.png)
**Á**

However, after reading in the data with Pandas Excel IO, they look like this:
![alt text](https://dl.dropboxusercontent.com/u/22352379/pandas_encoding.JPG)
**Ã**

I have no idea why this happens and how to solve this. Any help would be great.

**Comment by jreback** [comment]
pls show what you are actually doing (e.g. code), ``pd.show_versions()``, and pls have a look at using the ``encoding`` parameter in ``pd.read_excel``, which is passed thru to the parser.

**Comment by methodds** [comment]
The output from ``pd.show_versions()`` is:
```
INSTALLED VERSIONS
------------------
commit: None
python: 3.5.1.final.0
python-bits: 64
OS: Linux
OS-release: 3.19.0-32-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

pandas: 0.17.1
nose: 1.3.7
pip: 7.1.2
setuptools: 19.1.1
Cython: 0.23.4
numpy: 1.10.2
scipy: 0.16.1
statsmodels: 0.6.1
IPython: 4.0.1
sphinx: 1.3.1
patsy: 0.4.0
dateutil: 2.4.2
pytz: 2015.7
blosc: None
bottleneck: None
tables: 3.2.2
numexpr: 2.4.4
matplotlib: 1.5.0
openpyxl: 2.3.2
xlrd: 0.9.4
xlwt: 1.0.0
xlsxwriter: 0.7.7
lxml: 3.5.0
bs4: 4.4.1
html5lib: 0.9999999
httplib2: None
apiclient: None
sqlalchemy: 1.0.10
pymysql: None
psycopg2: None
Jinja2: None
```

The code for reading in is very simple without any special parameters:

```
dc = pd.read_excel('../Lista Freguesias_INE2.xls')
dc.head()
```

Do you need additional information?

**Comment by jreback** [comment]
just pass the encoding

**Comment by methodds** [comment]
Sorry I'm not sure what you mean as I did not specify an encoding opting while reading in the excel Data. Do you mean the encoding of the .xlsx file itself? I thought all .xlsx files are encoded in the same way.

**Comment by jreback** [comment]
``pd.read_excel('....', encoding='utf-8')``

**Comment by jreback** [comment]
closing as this is a usage question

**Comment by rmassa** [comment]
Hi, there is no encoding= parameters in read_excel I believe.
