### ISSUE TITLE
Add method to change the .name attribute on the axes

### ISSUE THREAD

**Issue by d10genes** [pydata/pandas#11965]
It would be nice to have a method to change the `.name` attribute on the columns/index, to permit it in a method chain. (This is a suggestion based on [this stackoverflow question](http://stackoverflow.com/questions/34598733/dataframe-method-for-renaming-axis).)

Instead of 

```
df.columns.name = 'A'
df.index.name = 'B'
df
    A   0   1
    B        
    0   9   4
    1  15   0
    2  17  16
```
it would allow something like

    df.rename_columns('A').rename_index('B')

or perhaps be a keyword argument to the existing `.rename()`. Does this seem like something that would fit in with pandas?

**Comment by TomAugspurger** [comment]
I've written up a PR for this a couple times, before discarding it, mostly since `rename` is probably the correct method name and it's not too bad to do with `.pipe`.

I'm +.5 on adding these methods or something like them. I don't think we should add anything to `.rename` since that's likely to create confusion.

**Comment by jreback** [comment]
this is related to #9494

**Comment by jreback** [comment]
if we implement  soln for #10797

then you could do:

``df = df.set_index(df.index.set_name('foo'))``

(though missing ability to set_columns atm, so only works for index)

**Comment by TomAugspurger** [comment]
I'll put something together for this and https://github.com/pydata/pandas/issues/9494

**Comment by d10genes** [comment]
@jreback the `df = df.set_index(df.index.set_name('foo'))` assignment looks useful, but I don't think it would be reliable in a chain of methods (e.g., after `.query` or renaming the axes)

Haven't tried it, but I guess another (pretty verbose) strategy would be to use `.assign(new_index_name=lambda x: x.index).set_index('new_index_name')`
