### ISSUE TITLE
DataFrame.to_csv convert int to float all the time

### ISSUE THREAD

**Issue by channingxiao** [pydata/pandas#11968]
When I use 
test_labels.to_csv("./data/test_label.csv", headers=True, index = False)
to write dataframe into csv file, it always convert inteders into float number,(I check the test_labels.dtype, it shows <type "int">. How can I let it not convert. Thanks

python 2.7.11, pandas 0.17.1, windows 10

**Comment by TomAugspurger** [comment]
Can you show an example of what's wrong? This looks correct to me

```python
In [1]: df = pd.DataFrame({"A": [1, 2, 3]})

In [2]: df
Out[2]:
   A
0  1
1  2
2  3

In [3]: df.dtypes
Out[3]:
A    int64
dtype: object

In [4]: df.to_csv('test.csv')

In [5]: !cat test.csv
,A
0,1
1,2
2,3
```

**Comment by TomAugspurger** [comment]
Going to close, let me know if the example I gave doesn't work for you, or if you can give a [working example](http://stackoverflow.com/help/mcve)

**Comment by ZurMaD** [comment]
@TomAugspurger when the `df.types` shows columns as the image as `objects` the function `df.to_csv()`  converts numbers into floats

![image](https://user-images.githubusercontent.com/28235457/80329214-3abf8500-8807-11ea-9114-35a08794b5d4.png)

![image](https://user-images.githubusercontent.com/28235457/80329254-5e82cb00-8807-11ea-85b0-9e9712ebac4d.png)

I'll try to create a minimal example.
