### ISSUE TITLE
Datetime index error?

### ISSUE THREAD

**Issue by vgoklani** [pydata/pandas#11973]
I have a dataframe of tweets, where the "created_at" column is stored as a datetime object. I just upgraded to the latest version of pandas, and now get this error:

```
df['created_at'].map(lambda d: d.strftime("%Y%m%d"))

TypeError: Argument 'arr' has incorrect type (expected numpy.ndarray, got DatetimeIndex)
```

strangely enough, everything works correctly if I do this:

```
df2 = df.set_index('created_at')
df2.index.map(lambda x: x.strftime("%Y%m%d"))
```
and this:

```
def f(d):
    return d['created_at'].strftime("%Y%m%d")

df.apply(lambda row: f(row), axis=1)
```
What is going on here?

**Comment by jreback** [comment]
pls show ``df.info()``, ``df.head()``, ``df.dtypes`` and ``pd.show_versions()``

**Comment by vgoklani** [comment]
pd.show_versions()



INSTALLED VERSIONS
------------------
commit: None
python: 2.7.11.final.0
python-bits: 64
OS: Darwin
OS-release: 15.3.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

pandas: 0.17.1
nose: 1.3.7
pip: 7.1.2
setuptools: 18.5
Cython: 0.23.4
numpy: 1.10.2
scipy: 0.16.0
statsmodels: 0.6.1
IPython: 4.0.1
sphinx: 1.3.1
patsy: 0.4.0
dateutil: 2.4.2
pytz: 2015.7
blosc: None
bottleneck: 0.9.0dev
tables: 3.2.2
numexpr: 2.4.4
matplotlib: 1.5.0
openpyxl: 2.2.6
xlrd: 0.9.4
xlwt: 1.0.0
xlsxwriter: 0.7.7
lxml: 3.4.4
bs4: 4.4.1
html5lib: 0.999
httplib2: 0.8
apiclient: None
sqlalchemy: 1.0.9
pymysql: None
psycopg2: None
Jinja2: None

df[['created_at', 'id']].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5498 entries, 4 to 42481
Data columns (total 2 columns):
created_at    5498 non-null datetime64[ns, <bson.tz_util.FixedOffset object at 0x1063cab50>]
id            5498 non-null object
dtypes: datetime64[ns, <bson.tz_util.FixedOffset object at 0x1063cab50>](1), object(1)
memory usage: 128.9+ KB

df[['created_at', 'id']].dtypes
created_at    datetime64[ns, <bson.tz_util.FixedOffset object at 0x1063cab50>]
id                                                                      object
dtype: object

df[['created_at', 'id']].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5498 entries, 4 to 42481
Data columns (total 2 columns):
created_at    5498 non-null datetime64[ns, <bson.tz_util.FixedOffset object at 0x1063cab50>]
id            5498 non-null object
dtypes: datetime64[ns, <bson.tz_util.FixedOffset object at 0x1063cab50>](1), object(1)
memory usage: 128.9+ KB

df[['created_at', 'id']].head()
	created_at	id
4	2015-01-01 00:05:06+00:00	550442555058692096
7	2015-01-01 00:08:53+00:00	550443507572563968
8	2015-01-01 00:10:10+00:00	550443831561584644
12	2015-01-01 00:14:35+00:00	550444940405530626
13	2015-01-01 00:15:24+00:00	550445145749864448

**Comment by jreback** [comment]
```
In [1]: df = DataFrame({'created_at' : pd.date_range('20130101',periods=3,tz='US/Eastern'), 'id' : range(3)})

In [2]: df
Out[2]: 
                 created_at  id
0 2013-01-01 00:00:00-05:00   0
1 2013-01-02 00:00:00-05:00   1
2 2013-01-03 00:00:00-05:00   2

# this is what you should do
In [4]: df.created_at.dt.strftime('%Y%m%d')
Out[4]: 
0    20130101
1    20130102
2    20130103
Name: created_at, dtype: object

# very inefficient
In [6]: df.created_at.dt.tz_localize(None).map(lambda d: d.strftime("%Y%m%d"))
Out[6]: 
0    20130101
1    20130102
2    20130103
Name: created_at, dtype: object
```
