### ISSUE TITLE
interation of set_eng_float_format and pivot_tables

### ISSUE THREAD

**Issue by ChristopherShort** [pydata/pandas#11981]
There appears to be an interaction between the option for float display length and pivot_table methods on integers. This issue arose when working on a dataset with both floats and integers - but this arose on operations on integers part of the dataset.

The following example throws an error from the `format.py` module.

Swap the comments on the formatting options  (undoing the setting for floats) and it runs fine.

In my dataset - there were no missing values following the pivot table operation and the error still occurs. In the sample code below, NaNs may be causing the formatting issue, but that didn't appear to be the case for me.

```python
import pandas as pd
import numpy as np

#pd.set_option('display.float_format', None)
pd.set_eng_float_format(accuracy=1)

df = pd.DataFrame(data = np.random.randint(25, size=(10, 3)), columns = list('abc'))
df.pivot_table(values='a', index='b', columns='c')
```

cheers
Chris

**Comment by jreback** [comment]
not so friendly, needs a nan-check before handing off to ``Decimal``.

want to do a pull-request?

**Comment by ChristopherShort** [comment]
OK - I'll have a go since you've classified it as a novice level issue. Last time I tried (with a csv issue in 2014), I got lost very quickly.  I'll get back to you in a week or so.

cheers

**Comment by jreback** [comment]
@ChristopherShort ok thanks. lmk.

**Comment by yaduart** [comment]
Hi,
I have fixed the bug. Is this fix going to released 0.18.2, or in the next major release. I am not sure about the file that I have to update in doc/source/whatsnew/vx.y.z.txt, would I need to update v0.18.2

Regards,
Yadu

**Comment by jreback** [comment]
0.18.2

**Comment by ChristopherShort** [comment]
yadu - thanks - this has been on my conscience for a couple of months (the 1 week blew right past).

I'll find something else I can contribute too.

**Comment by yaduart** [comment]
No worries. cheers.
