### ISSUE TITLE
How to concatenate two Panels without duplicating Items axis (i.e. like columns in DataFrames)?

### ISSUE THREAD

**Issue by esvhd** [pydata/pandas#11982]
I am trying to concatenating two Panels with duplicate `Items` (but different `major_axes`) together, without actually having to duplicate items... Did some searching but couldn't find much on SO.

Unfortunately I cannot upload pics to github at the moment.. **But screens are attached [here](http://stackoverflow.com/questions/34652835/pandas-how-to-concatenate-two-panels-without-duplicating-items-axis-i-e-colum).**

To illustrate what I mean:

    # create data
    import pandas as pd
    df1 = pd.DataFrame({'A' : [1, 2, 3], 'B' : [2, 5, 6]}, index={0, 1, 2})
    df2 = pd.DataFrame({'A' : [1, 2, 3], 'B' : [2, 5, 6]}, index={3, 4, 5})
    df3 = pd.DataFrame({'A' : [5, 2, 3], 'B' : [2, 5, 6]}, index={6, 7, 8})
    df4 = pd.DataFrame({'A' : [6, 2, 3], 'B' : [2, 5, 6]}, index={9, 10, 11})

    pan1 = pd.Panel({'X' : df1, 'Y': df2})
    pan2 = pd.Panel({'X' : df3, 'Y': df4})

    # concat these two panels above
    pan3 = pd.concat([pan1, pan2])

	pan3
	Output:
	<class 'pandas.core.panel.Panel'>
	Dimensions: 4 (items) x 12 (major_axis) x 2 (minor_axis)
	Items axis: X to Y
	Major_axis axis: 0 to 11
	Minor_axis axis: A to B

**Note that the `Items` axis for `pan3` is of length 4, while `pan1` and `pan2` both have `Items` axis of length 2.**

Looking at `pan3`'s `minor_axis`, I get duplicated columns in the frame below.  **This is my problem.**:

    pan3.loc[:, :, 'B']

Screenshot: See this [link on SO](http://stackoverflow.com/questions/34652835/pandas-how-to-concatenate-two-panels-without-duplicating-items-axis-i-e-colum)

**What I actually want to see** can be replicated as follows in a more complicated way... (Not more duplicated columns in the screenshot):

	df5 = pd.concat([df1, df3])
	df6 = pd.concat([df2, df4])
	pan4 = pd.Panel({'X':df5, 'Y':df6})
	pan4.loc[:, :, 'B']

Screenshot: See this [link on SO](http://stackoverflow.com/questions/34652835/pandas-how-to-concatenate-two-panels-without-duplicating-items-axis-i-e-colum)

**Is this something that can be done with `pd.concat`?** Thanks guys.

**Comment by jreback** [comment]
I answered your SO. you need to specify the axis of concatenation (it defaults to 0, the items axis)

```
In [12]: pd.concat([pan1, pan2],axis=1)
Out[12]: 
<class 'pandas.core.panel.Panel'>
Dimensions: 2 (items) x 12 (major_axis) x 2 (minor_axis)
Items axis: X to Y
Major_axis axis: 0 to 11
Minor_axis axis: A to B

In [13]: pd.concat([pan1, pan2],axis=1).loc[:,:,'B']
Out[13]: 
     X   Y
0    2 NaN
1    5 NaN
2    6 NaN
3  NaN   2
4  NaN   5
5  NaN   6
6    5 NaN
7    6 NaN
8    2 NaN
9  NaN   2
10 NaN   5
11 NaN   6
```

**Comment by esvhd** [comment]
Thank you @jreback ! The API docs could use some love on this.

**Comment by jreback** [comment]
http://pandas.pydata.org/pandas-docs/stable/merging.html#concatenating-objects

of course doc updates are welcome

**Comment by esvhd** [comment]
Let me figure out how to contribute!

**Comment by jreback** [comment]
http://pandas.pydata.org/pandas-docs/stable/contributing.html
