### ISSUE TITLE
select_dtypes fails on float16 typecode

### ISSUE THREAD

**Issue by jseabold** [pydata/pandas#11990]
I'll see if it's an easy fix.

```
import pandas as pd
import numpy as np

FLOAT_TYPES = list(np.typecodes['AllFloat'])

df = pd.util.testing.makeDataFrame()
df.select_dtypes(FLOAT_TYPES)

FLOAT_TYPES.remove('e')
df.select_dtypes(FLOAT_TYPES)
```

**Comment by jseabold** [comment]
Oh `getattr(np, dtype)` doesn't work for `e`, obviously.

**Comment by jseabold** [comment]
I'm not sure what is handled by `getattr(np, dtype)` that isn't handled by `np.dtype(dtype)`, actually.

**Comment by jreback** [comment]
have you had other issues with ``float16`` btw? its not support for *some* of the numeric ops (and will get upcast). what are you doing with it?

**Comment by jreback** [comment]
xref #9220, #10382

**Comment by jseabold** [comment]
I'm not doing anything with `float16`. I was just lazily trying to differentiate between numeric, integer, and object types to do e.g. continuous vs categorical data handling without more specific types than numpy primitives, and I noticed this.
