### ISSUE TITLE
API: column ordering on `get_dummies`

### ISSUE THREAD

**Issue by TomAugspurger** [pydata/pandas#12010]
I'm working on a `from_dummies` right now, and I'm trying to achieve (roughly)

```python
df = pd.from_dummies(pd.get_dummies(df))
```

One problem is that `get_dummies` will append all the dummy columns to the end of the DataFrame, after the numeric columns.

```python
In [15]: df = pd.DataFrame({"A": [1, 2], "B": ['a', 'b'], 'C': [1, 2]})
In [18]: pd.get_dummies(df)
Out[18]:
   A  C  B_a  B_b
0  1  1    1    0
1  2  2    0    1
```

So when we go to invert with `from_dummies` we don't know when column goes where. If instead we had

```python
   A  B_a  B_b  C
0  1    1    0  1
1  2    0    1  2
```

we'd know what the original ordering was by position.
Looking through the docs, I don't see anywhere where we say that the ordering must be this way, but it'll still be an API change and I'm not sure whether it's worth it.

**Comment by jreback** [comment]
I wouldn't change this, as typically you add new columns after existing ones.

**Comment by TomAugspurger** [comment]
Fair enough.
