### ISSUE TITLE
to_hdf emits PerformanceWarning when column names are unicode

### ISSUE THREAD

**Issue by jesaerys** [pydata/pandas#12016]
Here is a short example. The only difference between `df1` and `df2` is that the latter has unicode column names:

```python
import pandas as pd

data = [
    (11, 1.2),
    (21, 2.2),
    (31, 3.2),
    ]

df1 = pd.DataFrame(data, columns=['col1', 'col2'])
df2 = pd.DataFrame(data, columns=[u'col1', u'col2'])

df1.to_hdf('test1.h5', 'data')
df2.to_hdf('test2.h5', 'data')
```

The first write works as expected. But the second, `df2.to_hdf`, emits this warning:

```
/Users/z001j0s/anaconda/envs/boa2/lib/python2.7/site-packages/pandas/io/pytables.py:257: PerformanceWarning:
your performance may suffer as PyTables will pickle object types that it cannot
map directly to c-types [inferred_type->unicode,key->axis0] [items->None]

  f(store)
/Users/z001j0s/anaconda/envs/boa2/lib/python2.7/site-packages/pandas/io/pytables.py:257: PerformanceWarning:
your performance may suffer as PyTables will pickle object types that it cannot
map directly to c-types [inferred_type->unicode,key->block0_items] [items->None]

  f(store)
/Users/z001j0s/anaconda/envs/boa2/lib/python2.7/site-packages/pandas/io/pytables.py:257: PerformanceWarning:
your performance may suffer as PyTables will pickle object types that it cannot
map directly to c-types [inferred_type->unicode,key->block1_items] [items->None]

  f(store)
```

I'm testing with pandas 0.17.1 and python 2.7.11. I do *not* see this warning with python 3.5.1.

Is this warning intentional? In other words, should python 2 users know to avoid unicode column names? Or, should pandas somehow give the same experience between python 2 and python 3, making this a bug?

**Comment by jreback** [comment]
this is correct. ``fixed`` storage types do not support unicode in py2 directly. They must pickle the objects.  That's why a warning is emmited (it works but can potentially be slow).

Note that using ``table`` format works correctly in py2 (as it can natively store things).
