### ISSUE TITLE
`df.to_csv` on python3 throws `TypeError: a bytes-like object is required, not 'str'`

### ISSUE THREAD

**Issue by arokem** [pydata/pandas#12018]
The following code throws that error: 

    In [1]: import pandas as pd
    In [2]: import numpy as np
    In [3]: df = pd.DataFrame(np.random.randn(10, 5), columns=['a', 'b', 'c', 'd', 'e'])
    In [4]: import tempfile
    In [5]: tf = tempfile.NamedTemporaryFile()
    In [6]: df.to_csv(tf)

Am I missing something?

**Comment by TomAugspurger** [comment]
You'll want `tf = tempfile.NamedTemporaryFile(mode='w')` or `wt` since you're writing text, not bytes. Check if that works for you?

**Comment by arokem** [comment]
It does. Thanks!

**Comment by balaprasad18** [comment]
df.to_csv(tf)
how to read after this line?? i need to read tf, also need to mail the csv file

**Comment by balaprasad18** [comment]
how to check whether df.to_csv(tf) is properly exported as csv, df has data , tf has data may be not how to read and print tf?

**Comment by TomAugspurger** [comment]
@balaprasad18 You might try searching on stackoverflow under the pandas tag.
