### ISSUE TITLE
Bar and box plots always use the 'default' matplotlib colormap, even the style is changed

### ISSUE THREAD

**Issue by halflings** [pydata/pandas#12029]
I set the matplotlib style to "fivethirtyeight", which changes many settings in the axes, colors, etc.

This is what I get when doing a simple line plot:

    pd.DataFrame(dict(a=[1, 2, 3], b=[5, 10, 2])).plot.line()

![plot1](https://cloud.githubusercontent.com/assets/1626936/12292185/be56e276-b9eb-11e5-8c78-d412114a53cd.png)

The style matches what I was expecting.

(hist, area and other type of plots I tried work as well)

But when I want to get a bar plot, I get this:

    pd.DataFrame(dict(a=[1, 2, 3], b=[5, 10, 2])).plot.bar()

![plot2](https://cloud.githubusercontent.com/assets/1626936/12292188/c1733e1e-b9eb-11e5-9e90-48f8bb65588e.png)

Most elements of the style seem to be here, but the colors are the default matplotlib ones, not the ones in "fivethirtyeight" (and the same goes with a boxplot)

![plot3](https://cloud.githubusercontent.com/assets/1626936/12292249/1b43981c-b9ec-11e5-8656-a1c6a147a62e.png)

Any clue about what might be causing this?

These are the lines I used to style my plots:

    import matplotlib.pyplot as plt
    import matplotlib
    matplotlib.style.use('fivethirtyeight')

    %matplotlib inline

    COLORS = [(0.3333333333333333, 0.6588235294117647, 0.40784313725490196),
     (0.2980392156862745, 0.4470588235294118, 0.6901960784313725),
     (0.7686274509803922, 0.3058823529411765, 0.3215686274509804),
     (0.5058823529411764, 0.4470588235294118, 0.6980392156862745),
     (0.8, 0.7254901960784313, 0.4549019607843137),
     (0.39215686274509803, 0.7098039215686275, 0.803921568627451),
     (0.33999999999999997, 0.86, 0.57920000000000016)]

    plt.rcParams['figure.figsize'] = (14.0, 7.0)
    plt.rcParams['axes.prop_cycle'] = plt.cycler('color', COLORS)

**Comment by halflings** [comment]
For boxplots at least, the problem might come from this:

https://github.com/pydata/pandas/blob/03ee0c19c99583da915139fbaec855e66322f5f3/pandas/tools/plotting.py#L2668

(it's using a custom _get_colors that doesn't pass a colormap)

**Comment by jorisvandenbossche** [comment]
The bar plot issue should be solved in master (see issue https://github.com/pydata/pandas/issues/11614 and PR https://github.com/pydata/pandas/pull/11865/files). Are you able to test that?

The boxplots issue also seems OK when I try it with master, but probably it would be good to add a test for that as well.

**Comment by halflings** [comment]
Great, thanks Joris!

**Comment by halflings** [comment]
It turns out that this issue also arises when using matplotlib alone, without pandas. I filed an issue on the matplotlib repo referencing this one.

**Comment by halflings** [comment]
Just tested, and the issue is solved on master. Closing this issue. Thanks!
