### ISSUE TITLE
ENH missing decimal parameter in .to_latex and .to_html

### ISSUE THREAD

**Issue by nbonnotte** [pydata/pandas#12031]
`.to_csv` has a `decimal` parameter to specify the decimal mark for floats since version 0.16

It would be nice to have the same thing in `.to_latex` and `.to_html`.

I'll work on a PR.

This issue is a spin-off of #7061, in which @TomAugspurger  said:

> There’s a *possibility* that we’ll be able to replace some of the `to_latex` code with a Jinja template, similar to the Style stuff. So don’t spend too much time on it :)

**Comment by jreback** [comment]
think we had 2 issues (#12030)
