### ISSUE TITLE
Index.difference performance

### ISSUE THREAD

**Issue by Winand** [pydata/pandas#12044]
I need to append several big Series to a big categorical Series.
Trying to update categories FAST i've found out that `Index.difference` uses Python's `set`, which is slow on creating LARGE set (i have up to 500k categories and 1.3M values).
numpy's `setdiff1` is more than an order of magnitude faster (as of datetime64 Categorical):

    tmp_unique = tmp.unique()
    new_cats = pd.Index(pd.np.setdiff1d(tmp_unique[~pd.isnull(tmp_unique)], to.cat.categories))

Not so fast:

    new_cats = pd.Index(tmp_unique[~pd.isnull(tmp_unique)]).difference(to.cat.categories)

**Comment by jreback** [comment]
can u show the creation of tmp

**Comment by jreback** [comment]
and to

**Comment by Winand** [comment]
I've tried to implement this with string data and `difference` performed better. But `setdiff1d` is much better with `datetime64[ns]`

```
import pandas as pd, time

to=pd.Series(pd.DatetimeIndex(range(1000000))).astype('category')#pd.Series(("hello%d"%i for i in range(1000000))).astype('category')
cats = to.cat.categorical._categories.values
tmp=pd.Series(pd.DatetimeIndex(range(1000000, 1200000)))#pd.Series(("bye%d"%i for i in range(200000)))

tmp_unique = tmp.unique()
tmp_unique = tmp_unique[~pd.isnull(tmp_unique)]

_=time.clock()
new_cats = pd.Index(tmp_unique).difference(cats)
print("Index.difference:", time.clock()-_)

_=time.clock()
new_cats = pd.Index(pd.np.setdiff1d(tmp_unique, cats))
print("np.setdiff1d:", time.clock()-_)
```

**Comment by jreback** [comment]
interesting, the is the first numpy setop that actually is fast. 

ok, sure pull-requests are welcome (including an asv benchmark).

**Comment by jreback** [comment]
xref https://github.com/pydata/pandas/pull/11279

note that you would have to use base forms for some of the index types (e.g. ``.values``)

so might need to upgrade tests for this (in fact should consolidate all of the ``test_difference*`` tests in ``test_index.py``) and move them to ``Base`` for generic testing.

**Comment by MaximilianR** [comment]
@Winand I had a go at speeding this up, in the issue @jreback referenced. I didn't get it over the finish line, please do take the torch!

My understanding is that `set` is actually very fast. The slow part of the current implementation is the boxing & unboxing of values, for indexes that need to do conversions for each element for `list(self)`. So if you can delegated to `.values`, then `set` should be reasonable. numpy may still be faster - worth comparing apples to apples

**Comment by Winand** [comment]
@MaximilianR currently my prioritized task is to create Castra-like storage to be able to save/load big annual data fast.

As of "apples to apples" `setdiff1d` is much better with `datetime64` and long `int64` arrays. `set` is faster with strings.

P.S. funny things:
```
>>> import pandas as pd
>>> ds = pd.Categorical([pd.np.datetime64("2014-01-01"), pd.NaT])
>>> ds
[2014-01-01, 2014-01-01]
Categories (1, datetime64[ns]): [2014-01-01]
>>> ds[ds.isnull()]
[2014-01-01]
Categories (1, datetime64[ns]): [2014-01-01]
>>> ds[ds.isnull()].astype('datetime64')
array(['NaT'], dtype='datetime64[ns]')
```
