### ISSUE TITLE
ERR: read_csv with dtype specified on empty data

### ISSUE THREAD

**Issue by Sereger13** [pydata/pandas#12048]
File has this content:
```
A,A
3,3
```
When I do `pd.read_csv(filepath)` - all looks fine, however if I specify _skiprows_ and _dtype_ parameters it fails with the following error:

```
pd.read_csv(filepath, skiprows=1, dtype=str)
```
> AttributeError: type object 'str' has no attribute 'items'

---
INSTALLED VERSIONS
------------------
commit: None
python: 2.7.10.final.0
python-bits: 64
OS: Linux
OS-release: 2.6.18-238.9.1.el5
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US

**pandas: 0.17.1**

**Comment by jreback** [comment]
This is equivalent to this. So this doesn't have any data, so the dtype converter should handle this properly.

```
In [13]: read_csv(StringIO(data),header=0,skiprows=1)
Out[13]: 
Empty DataFrame
Columns: [3, 3.1]
Index: []

In [14]: data
Out[14]: 'A,A\n3,3'
```

So an even simpler repro is this.
```
In [16]: read_csv(StringIO('A,B'),dtype=str)
AttributeError: type object 'str' has no attribute 'items'
```

care to do a pull-request to fix?

**Comment by Sereger13** [comment]
Prepared the fix locally but getting this error when trying to send pull-request: 
'It seems you do not have permission to push your changes to this repository'.

**Comment by jreback** [comment]
see contributing docs [here](http://pandas.pydata.org/pandas-docs/version/0.17.1/contributing.html)

you need to fork, then push to your branch and open a PR.

you are trying to push to master
