### ISSUE TITLE
Export DataFrame with objects to Excel creates error.

### ISSUE THREAD

**Issue by sevaader** [pydata/pandas#12076]
pandas version 0.17.0

I'm using a Class Name to set names.

    from pandas import DataFrame
    
    class Name(object):
        def __init__(self, name):
            self.name = name
    
        def __repr__(self):
            return self.name
    
I want to create a simple DataFrame

    df = DataFrame([{"Hi":Name("hello"), "My":"Friend"}])
    # df = DataFrame([{Name("Hi"):"hello", "My":"Friend"}])

I try to export it in Excel with:

    from pandas import ExcelWriter
    xlw = ExcelWriter("welcome.xlsx")
    df.to_excel(xlw, "test")
    xlw.save()

but I have the following error:

[![error message trying to export df to excel][1]][1]

in the pandas/io/excel.py

    def _conv_value(val):
    # Convert numpy types to Python types for the Excel writers.
    if com.is_integer(val):
        val = int(val)
    elif com.is_float(val):
        val = float(val)
    elif com.is_bool(val):
        val = bool(val)
    elif isinstance(val, Period):
        val = "%s" % val
    elif com.is_list_like(val):
        val = str(val)
    # <---- a test is missing here.
    return val

adding else:
     val = str(val)   solve the pb.

the export is correct with 
 - df =  DataFrame([{"Hi":"hello", "My":"Friend"}])

  [1]: http://i.stack.imgur.com/v2hqX.png

**Comment by jreback** [comment]
if you really really want to do this (and its in general a bad idea to store things like this). Your need to make your class ``Name`` into a real scalar, or a real list-like. It is neither. So either define ``__iter__`` and ``__len__`` or ``__str__`` might work.

**Comment by sevaader** [comment]
I'd like to evaluate a function with

    df["function1"] = df.apply(lambda row: function1(row.Rn, row.Etude), axis=1)

    def function1(Rn, Etude):
        Ka, Kb, Kc = Rn.Ka, Rn.Kb, Rn.Kc
        return Ka*Kb*Kc*qr(Rn.name, Etude.name)

but I, only want to have Rn.name et Etude.name displayed on dataframe, so Rn and Etude are objects like Name, with other attributes

Why it's a bad idea to use objects in df ? is there another way to do it ?

**Comment by jreback** [comment]
@sevaader well, these are quite inefficient for doing things, you are missing all of the power of vectorized computation. generally you should keep each piece of data in its own column.
