### ISSUE TITLE
DataFrame.merge with Series should give nice error message

### ISSUE THREAD

**Issue by dan-tee** [pydata/pandas#12081]
Right now trying this results in "IndexError: list index out of range". It should say can't merge DataFrame with a Series...

I know this for quite a while now, but still get trapped on it every once in a while. This would be very helpful for beginners.

Other people also get confused: http://stackoverflow.com/questions/27281734/pandas-merge-on-index-not-working

**Comment by benjello** [comment]
:+1:

**Comment by jreback** [comment]
can you post a copy-pastable example that shows the error message.

**Comment by halflings** [comment]
import pandas as pd
    df = pd.DataFrame(dict(a=range(20)))
    pd.merge(df, df.a, left_index=True, right_index=True)

This gives:

    ---------------------------------------------------------------------------
    IndexError                                Traceback (most recent call last)
    <ipython-input-9-fae8bf77732c> in <module>()
          1 import pandas as pd
          2 df = pd.DataFrame(dict(a=range(20)))
    ----> 3 pd.merge(df, df.a, left_index=True, right_index=True)

    /usr/local/lib/python3.5/site-packages/pandas/tools/merge.py in merge(left, right, how, on, left_on, right_on, left_index, right_index, sort, suffixes, copy, indicator)
         33                          right_index=right_index, sort=sort, suffixes=suffixes,
         34                          copy=copy, indicator=indicator)
    ---> 35     return op.get_result()
         36 if __debug__:
         37     merge.__doc__ = _merge_doc % '\nleft : DataFrame'

    /usr/local/lib/python3.5/site-packages/pandas/tools/merge.py in get_result(self)
        194             self.left, self.right = self._indicator_pre_merge(self.left, self.right)
        195
    --> 196         join_index, left_indexer, right_indexer = self._get_join_info()
        197
        198         ldata, rdata = self.left._data, self.right._data

    /usr/local/lib/python3.5/site-packages/pandas/tools/merge.py in _get_join_info(self)
        304     def _get_join_info(self):
        305         left_ax = self.left._data.axes[self.axis]
    --> 306         right_ax = self.right._data.axes[self.axis]
        307
        308         if self.left_index and self.right_index:

    IndexError: list index out of range

**Comment by jreback** [comment]
thanks!. yes these could use more intuitive warnings. want to do a PR?

**Comment by dan-tee** [comment]
I'd love to give it a shot.

**Comment by dan-tee** [comment]
I've opened [PR #2112](https://github.com/pydata/pandas/pull12112). Would be happy about a review.
