### ISSUE TITLE
KeyError: 'version' on import

### ISSUE THREAD

**Issue by samzhang111** [pydata/pandas#12084]
I'm running pandas 0.17.1 on Python 2.7.10 on RHEL 7.12, and I am experiencing the following behavior:

```
In [1]: import pandas
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-1-d6ac987968b6> in <module>()
----> 1 import pandas

/var/lib/jenkins/jobs/Test-Client/workspace/venv/lib/python2.7/site-packages/pandas/__init__.py in <module>()
     60 # use the closest tagged version if possible
     61 import pdb; pdb.set_trace()
---> 62 from ._version import get_versions
     63 v = get_versions()
     64 __version__ = v.get('closest-tag',v['version'])

KeyError: 'version'
```

This appears with both Python and IPython. I've inserted a debugger into the `__init__` script and examined what get_versions returns at that time. It looks like this:

```
(Pdb) v
{u'e\x00r\x00r': None, u'f\x00u\x00l\x00l\x00-\x00r\x00e\x00v': u'6\x00c\x003\x000\x00c\x00b\x00e\x00c\x00f\x008\x00e\x005\x00a\x00e\x006\x001\x000\x00f\x002\x00a\x00', u'd\x00i\x00r': False, u'v\x00e\x00r\x00s': u'0\x00.\x001\x00'}
```

`get_versions()` just calls json.loads on a `version_json` dictionary in the `_version` file (generated by the versioneer). The `version_json` dictionary appears fine at time of import, however:

```
(Pdb) version_json
'\n{\n "dirty": false,\n "error": null,\n "full-revisionid": "6c30cbecf8e5ae610f2a37ba821116bd9f77044d",\n "version": "0.17.1"\n}\n'
```

It looks like the ultrajson library included with pandas works differently for me on the server than my local development machine. Both have ultrajson version 1.33.

I should also note that when I try to rerun `import pandas` in the same REPL, I get a different error:

```
In [2]: import pandas
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-d6ac987968b6> in <module>()
----> 1 import pandas

/var/lib/jenkins/jobs/Test-Client/workspace/venv/lib/python2.7/site-packages/pandas/__init__.py in <module>()
     11                       "pandas from the source directory, you may need to run "
     12                       "'python setup.py build_ext --inplace' to build the C "
---> 13                       "extensions first.".format(module))
     14 
     15 from datetime import datetime

ImportError: C extension: hashtable not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace' to build the C extensions first.
```

Thanks,
Sam

**Comment by samzhang111** [comment]
I should also note that when I try to rerun `import pandas` in the same REPL, I get a different error:

```
In [2]: import pandas
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-d6ac987968b6> in <module>()
----> 1 import pandas

/var/lib/jenkins/jobs/Test-Client/workspace/venv/lib/python2.7/site-packages/pandas/__init__.py in <module>()
     11                       "pandas from the source directory, you may need to run "
     12                       "'python setup.py build_ext --inplace' to build the C "
---> 13                       "extensions first.".format(module))
     14 
     15 from datetime import datetime

ImportError: C extension: hashtable not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace' to build the C extensions first.
```

**Comment by jreback** [comment]
not really sure what you are trying to do, e.g. are you trying to install a development version? if so see [here](http://pandas.pydata.org/pandas-docs/stable/contributing.html), if not, how are you installing.

**Comment by samzhang111** [comment]
It turns out that clearing the pip cache and reinstalling fixed the issue

**Comment by miraculixx** [comment]
I ran into the same problem. It turns out the root cause was that there were two python versions, one was from heroku's python buildpack, the other was installed as part of a conda setup. The former is compiled with `--enable-unicode=ucs2` while the latter uses `--enable-unicode=ucs4`, yet both where accessing the same `site-packages` where pandas is installed. 

Apparently, ultrajson gets confused by ucs2/ucs4  and returns a mangled dictionary. This happens even when `loads(dumps(...))` is used in the same python process.

The resolution was to use conda's python version only.

**Comment by jreback** [comment]
that is a weird one!

**Comment by miraculixx** [comment]
weird indeed, hopefully this saves someone else 1 day's work ;-)

**Comment by sulaksh451** [comment]
Please help me: on this error.

  File "C:/Users/SBoddula/IdeaProjects/Automation_IS/src/Vinaycode.py", line 5, in <module>
    import pandas as pd
  File "C:\Users\SBoddula\AppData\Local\Programs\Python\Python37\Lib\site-packages\pandas\__init__.py", line 185, in <module>
    v = get_versions()
  File "C:\Users\SBoddula\AppData\Local\Programs\Python\Python37\Lib\site-packages\pandas\_version.py", line 21, in get_versions
    return json.loads(version_json)
AttributeError: module 'json' has no attribute 'loads'
