### ISSUE TITLE
Adding a date_unit option to .read_csv to make parse_dates more flexible.

### ISSUE THREAD

**Issue by tamasgal** [pydata/pandas#12097]
When reading in a CSV file, you can easily convert a column into the `datetime` format using:

    pd.read_csv(filepath, parse_dates=['TIMESTAMP'])

If the column holding the original time information uses an unsupported format, you can currently pass a parser function to it too, for example if the timestamp is "unixtime in milliseconds":

    convert = lambda x: datetime.datetime.fromtimestamp(float(x) / 1e3)
    df = pd.read_csv(filepath, parse_dates=['TIMESTAMP'], date_parser=convert)

However, if the data is already read in, you can also do such conversions easily with `.to_datetime()` which provides a `unit` parameter for the most common cases:

    pd.to_datetime(df['UNIXTIME'], unit='ms')

I think it would be quite useful to have this `unit` parameter in `.read_csv()` too, calling it `date_unit` to avoid confusion. The example with the extra conversion function would then look like:

    df = pd.read_csv(filepath, parse_dates=['TIMESTAMP'], date_unit='ms')

Or using a list of units to allow multiple columns with different units:

    df = pd.read_csv(filepath, parse_dates=['TIMESTAMP', 'ANOTHER_TIMESTAMP], date_unit=['ms', 'us'])

**Comment by jreback** [comment]
this would further complicate an already enormous set of options. you are much better off doing date parsing afterwords as there are MANY more options in ``pd.to_datetime`` in any event (e.g. formatting, dayfirst, etc).
