### ISSUE TITLE
pytables.open prints to stdout when attempting to open a read-only HDF5 file

### ISSUE THREAD

**Issue by dadkins** [pydata/pandas#12106]
https://github.com/pydata/pandas/blob/master/pandas/io/pytables.py#L539

        try:
            self._handle = tables.open_file(self._path, self._mode, **kwargs)
        except (IOError) as e:  # pragma: no cover
            if 'can not be written' in str(e):
                print('Opening %s in read-only mode' % self._path)
                self._handle = tables.open_file(self._path, 'r', **kwargs)
            else:
                raise

The above code prints to stdout when attempting to read from a readonly file. This is a problem for programs which use stdout for their own output. It should either print to sys.stderr or whatever log the rest of the library uses.

**Comment by jreback** [comment]
this is only if you are passing the default mode which is ``a``, if you pass ``mode='r'`` then it will work just fine.

**Comment by dadkins** [comment]
Thanks for the workaround, but the issue is not that code path was executed, but that the diagnostic message was printed to stdout instead of stderr, where it mixed with regular output that was consumed by another process.
