### ISSUE TITLE
pandas.merge indicator is ignoring suffixes

### ISSUE THREAD

**Issue by dickreuter** [pydata/pandas#12105]
x=pd.merge(df1,df2,left_on..,right_on.. indicator=True, suffixes=['leftDataFrameSuffix','rightdfSuffix]

The output will show an indicator column which will show 'left', 'right' or 'both' instead of 'leftDataFrameSuffix', 'rightdfSuffix' or 'both'.

**Comment by jreback** [comment]
http://pandas.pydata.org/pandas-docs/stable/generated/pandas.merge.html?highlight=merge#pandas.merge

that's exactly what what it's supposed to do
