### ISSUE TITLE
Inconsistent results when subtracting two large float64 columns

### ISSUE THREAD

**Issue by canthonissen** [pydata/pandas#12120]
>>> test = numpy.DataFrame(numpy.random.normal(size=(80000,2)))
>>> k = test[0] - test[1]

Works most of the time, but sometimes gives a column of zero (or near zeros) as output.
Does not seem to affect small dataframes.

**Comment by jreback** [comment]
well if you are on windows and using ``numexpr=2.4.4`` or lower then its a dupe of: https://github.com/pydata/pandas/issues/12023

if not, pls ``pd.show_versions()``

**Comment by canthonissen** [comment]
Yup numexpr 2.4.4.
Thanks.
