### ISSUE TITLE
Series.map does not work with defaultdicts

### ISSUE THREAD

**Issue by seanv507** [pydata/pandas#12143]
map seems to remove the default behaviour - workaround is to use a lambda function

```python
import collections
import pandas as pd

a=pd.Series([1,2,3])
print 'a = '
print a

c=collections.defaultdict(int)

c[1]=1
c[2]=4
b=a.map(c)
print 'b = '
print  b
# b.iloc[2] set to Nan (ignoring defaultdict)

d=a.map(lambda x : c[x])
print 'd = '
print d
# d.iloc[2] set to 0 (desired default value)
pd.show_versions()

a = 
0    1
1    2
2    3
dtype: int64
b = 
0     1
1     4
2   NaN
dtype: float64
d = 
0    1
1    4
2    0
dtype: int64

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.11.final.0
python-bits: 64
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: en_GB

pandas: 0.17.1
nose: 1.3.7
pip: 7.1.2
setuptools: 18.5
Cython: 0.23.4
numpy: 1.10.1
scipy: 0.16.0
statsmodels: None
IPython: 4.0.1
sphinx: 1.3.1
patsy: 0.4.0
dateutil: 2.4.2
pytz: 2015.7
blosc: None
bottleneck: 1.0.0
tables: 3.2.2
numexpr: 2.4.4
matplotlib: 1.5.0
openpyxl: 2.2.6
xlrd: 0.9.4
xlwt: 1.0.0
xlsxwriter: 0.7.7
lxml: 3.4.4
bs4: 4.4.1
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.0.9
pymysql: None
psycopg2: 2.5.1 (dt dec pq3 ext)
Jinja2: None

**Comment by jreback** [comment]
This does as advertised. A passed ``dict`` is converted to a ``Series``, e.g.
```
In [14]: Series(d,index=a.keys())
Out[14]: 
0   NaN
1     1
2     4
dtype: float64
```

so 
```
In [1]: import collections

In [2]: c=collections.defaultdict(int)

In [3]: c[1]=1

In [4]: c[2]=4

In [5]: d = dict(c)

In [6]: a=pd.Series([1,2,3])

In [7]: a.map(d)
Out[7]: 
0     1
1     4
2   NaN
dtype: float64

In [8]: a.map(c)
Out[8]: 
0     1
1     4
2   NaN
dtype: float64
```

I suppose a nicer example in the doc-string would be helpful.

**Comment by seanv507** [comment]
the doc string says : "Map values of Series using input correspondence (which can be a dict, Series, or function)"... one would assume can also be defaultdict

**Comment by jreback** [comment]
pls re-read what I put above. ``dict`` and ``defaultdict`` work exactly the same.

**Comment by seanv507** [comment]
"dict and defaultdict work exactly the same".  That's my point, they are not the same class, defaultdict implements a default mapping, so I would expect the map dict behaviour to be equivalent to the function
lambda x : d[x]  [ so the same behaviour for both default dict and dict]

**Comment by jreback** [comment]
you would need a much stronger usecase for making to very similar classes that are coerced to a ``Series`` do something differnt. That would be much more confusing.

**Comment by seanv507** [comment]
OK I think what I am doing is a dumb application of defaultdict.  I should just use fillna. sorry to waste your time.
