### ISSUE TITLE
better docs for read_csv() argument infer_datetime_format

### ISSUE THREAD

**Issue by lexual** [pydata/pandas#12152]
This gives pretty decent explanation of the infer_datetime_format parameter:

http://pandas.pydata.org/pandas-docs/version/0.17.1/whatsnew.html#id55

The api docs are fairly opaque.

Improve api docs to make it clearer:

http://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html

**Comment by jreback** [comment]
xref #12061
