### ISSUE TITLE
Why does Series.plot() not have a kind='scatter' option?

### ISSUE THREAD

**Issue by connercowling** [pydata/pandas#12172]
I run into use-cases for this feature often. It seems so simple that it's hard to believe this is purely an oversight. 

So, why does `Series.plot()` not have a `kind='scatter'` option?

**Comment by TomAugspurger** [comment]
Most likely because of how it's implemented for DataFrames, which expects an `x` and `y` (not an index). You can get something similar with `Series.plot(style='.')`

**Comment by sinhrks** [comment]
Closing as usage question.
