### ISSUE TITLE
Reiindex_axis with copy=False return new object when expecting to change it inplace

### ISSUE THREAD

**Issue by aprotopopov** [pydata/pandas#12201]
I thought that `reindex_axis` with argument `copy=False` should change it inplace. From [docs](http://pandas.pydata.org/pandas-docs/version/0.17.0/generated/pandas.DataFrame.reindex_axis.html):

> **copy** : *boolean*, *default True*  
    Return a new object, even if the passed indexes are the same

However:

    df = pd.DataFrame({'A': [1], 'B': [2]})

    In [105]: df.reindex_axis(['B', 'A'], axis=1, copy=False)
    Out[105]:
       B  A
    0  2  1

    In [106]: df
    Out[106]:
       A  B
    0  1  2

Am I misunderstood that argument?

**Comment by jreback** [comment]
this is not the API it is just an opportunistic copy, not an inplace setting; in reality it is a mostly internal argument.
