### ISSUE TITLE
KeyError Iterating on empty HDFStore

### ISSUE THREAD

**Issue by toobaz** [pydata/pandas#12221]
list(pd.HDFStore("non_existing_store.hdf"))

should, I think, return ``[]``, instead it yields:

    KeyError: 'No object named 0 in the file'

**Comment by jreback** [comment]
has nothing to do with an empty store, ``HDFStore`` is an iterable (e.g. has ``__getitem__`` and ``__len__`` defined), but not ``__iter__``, so this essentially calls ``.get``. I suppose it should just raise a better error message.

you are probably looking for ``.keys()`` (though I suppose ``__iter__`` could just call that)

**Comment by toobaz** [comment]
Sorry, I was mislead by ``HDFStore().root`` being iterable. I will implement the ``__iter__`` you suggest.
