### ISSUE TITLE
Query on Series

### ISSUE THREAD

**Issue by MaximilianR** [pydata/pandas#12226]
I often find myself building a chain of logic, and then wanting to slice over some expression. Here's a contrived example:

```python
In [12]: pd.Series(range(10)).mul(5).pipe(lambda x: x**2).pipe(lambda x: x-500)
Out[12]: 
0    -500
1    -475
2    -400
3    -275
4    -100
5     125
6     400
7     725
8    1100
9    1525
dtype: int64
```

...and then having to assign to a separate variable and slice using that. Which is not the worst affliction that could strike western civilization, but can disrupt the flow in a repl a little.

```python

In [13]: s=pd.Series(range(10)).mul(5).pipe(lambda x: x**2).pipe(lambda x: x-500)

In [14]: s[s>200]
Out[14]: 
6     400
7     725
8    1100
9    1525
dtype: int64
```

Instead, would it be reasonable to extend query or filter to do this. For example:

`pd.Series(range(10)).mul(5).pipe(lambda x: x**2).pipe(lambda x: x-500).query('>200')`
or
`pd.Series(range(10)).mul(5).pipe(lambda x: x**2).pipe(lambda x: x-500).filter(lambda x: x>200)`

**Comment by jreback** [comment]
anything different from https://github.com/pydata/pandas/issues/11485 ?

**Comment by MaximilianR** [comment]
No that covers it!

Closing.

FWIW `Series.filter` seems a bit orphaned - not much in the docs, and its first arg `items` looks like nothing more than a slice. I wonder if this functionality could come from #11485.

**Comment by jreback** [comment]
@MaximilianR 

yeah ``.filter`` is only on labels. its a bit of an odd spelling, as typically ``.filter`` is on data.

I think we have an issue about this somewhere.
