### ISSUE TITLE
When reading CSV, float-like strings lacking exponent digits are accepted as floats

### ISSUE THREAD

**Issue by bennorth** [pydata/pandas#12237]
The data-frame

```python
DataFrame({'x': [2.5], 'y': [42], 'z': ['2E']})
```

does not round-trip correctly via CSV.  The string `'2E'` is interpreted as a valid float, but it should not be (according to man strtod(3), which seems a reasonable spec).

**Comment by bennorth** [comment]
Work underway in #12215.

**Comment by gfyoung** [comment]
@jreback : This should be closed since #12215 was merged in.
