### ISSUE TITLE
RLS: 0.18.0 schedule

### ISSUE THREAD

**Issue by jreback** [pydata/pandas#12245]
so I am thinking of a RC1, friday feb 12th & release on or about friday feb 26th assuming nothing major comes up.

any objections

@jorisvandenbossche @shoyer @wesm @cpcloud @TomAugspurger @sinhrks

**Comment by wesm** [comment]
This seems fine to me. 

Side issue: pandas is in need of an issue triage. We should probably move at least 500 issues to a feature deadpool to discuss and close. If we agree on a standard protocol for the triage, I can take on 50-100 personally.

For the triage, we should have 2 kinds of issues:

1) This belongs in pandas, but needs a champion to pick it up and do it
2) This probably does not belong in pandas, and should be closed

Separately: I would also like to split out a category for issues that can be resolved as part of the libpandas / pandas 1.0 experiment. I realistically am not going to have time to start moving the ball forward there until sometime in March. I'm still scoping all the moving pieces; if anyone has time to help with this scoping effort (and isolating pieces -- like Panel and friends -- that are heading for deprecation in 0.19.x) I would really appreciate it. As soon as we scope out the work to be done and all the moving pieces it will be relatively straightforward to start making linear progress on this, with a target completion date end of 2016 / early 2017.

**Comment by jreback** [comment]
@wesm sounds all good to me.

It might make sense to create a couple of milestones for these (or labels ok too): internal refactor / triage

I find milestones a bit 'more obvious' for grouping things like this. 

I also created 0.18.1 and 0.19.0 milestones.

I will (but haven't yet) created a deprecation issue of > 2 ndim.

**Comment by jreback** [comment]
release candidate is tagged: https://github.com/pydata/pandas/releases/tag/v0.18.0rc1

e-mail going out in a little

**Comment by jreback** [comment]
ok, was busy last week, but hoping to merge remaining PR's for 0.18.0 in next day or 2. Then going to do a v0.18.0rc2. Give that a week to bake then release.

**Comment by jreback** [comment]
ok ann for 0.18.0rc2 is sent [here](https://groups.google.com/forum/#!topic/pydata/XiyF7kpozqk). and builds are up on conda:

``conda install pandas=v0.18.0rc2 -c pandas``

unless major breaks will plan for a release early next week.

**Comment by jorisvandenbossche** [comment]
@jreback Thanks!

I want already note that I won't be able to build and upload the docs this time for 0.18.0 (I am finishing my phd the coming month, so my activity level will be lower anyhow :-)). You already cleaned up a lot, but there is still an issue with the accessor API docs.

Further, just to check:

- do we have confirmation of some major pandas-relying projects (seaborn, statsmodels, ..) their tests run fine?
- @jreback did you do a performance check (full suite since 0.17.1)? If so, maybe just post it here as well to record that? (Eg an update to http://pydata.github.io/pandas/# like you did for 0.17 would be nice.)

**Comment by jreback** [comment]
oh didn't realize you couldn't build the docs - ok I can do that - are instructions in the contributing up to date? (eg for pdf and latex) do u do anything special?

not going to hold things up for perf ATM 
can be addressed in next release

**Comment by TomAugspurger** [comment]
I can build the docs tonight. I’ve got latex already setup.

**Comment by jreback** [comment]
@TomAugspurger thanks! I usually push the version update tag commit first 
so u need to tag it locally and should be good
if u send me a public key ssh (email) I will setup so u can login to the server to deploy them (or I can do it)

**Comment by jorisvandenbossche** [comment]
> oh didn't realize you couldn't build the docs - ok I can do that - are instructions in the contributing up to date? (eg for pdf and latex) do u do anything special?

They should be perfectly be up to date! https://github.com/pydata/pandas/wiki/Building-and-uploading-the-official-documentation (apart from the 'setting up your environment' section, some new packages are missing, statsmodels and xarray for example)

@TomAugspurger It's for next week I think, for the final release

**Comment by jreback** [comment]
@jorisvandenbossche great!

actually the requirements are up to date
(I fixed the build in the last commit)

you have to

conda remove pandas --force to avoid removing stats models / xarray

**Comment by TomAugspurger** [comment]
Was able to build the PDF, with one change in https://github.com/pydata/pandas/pull/12586

I do have some strange style stuff for the codeblocks. They're all surrounded by boxes, and occasionally (not always) have a bunch of backslashes separating the input and output.

<img width="1120" alt="screen shot 2016-03-10 at 7 33 40 am" src="https://cloud.githubusercontent.com/assets/1312546/13670996/db2ba3e0-e692-11e5-9a3a-08c9d8eaceb7.png">

I had the same thing happen on 0.17.1 so presumably it's my LaTeX environment. Will keep working on it.

**Comment by jreback** [comment]
thanks @TomAugspurger fantastic!

**Comment by jreback** [comment]
so I update the conda version tag so now the following:

``conda install pandas -c pandas`` will get you the latest version (you don't have to explictly specify), and more importantly won't downgrade you if you later ``conda install pandas``.

We *had* strings  like 

``pandas-v0.18.0rc2-np110py27_2_g117bacf.tar.bz2``

now like this
``pandas-0.18.0rc2-np110py27_2_g117bacf.tar.bz2``

this is a buggy in conda as a leading v should be ignored.

**Comment by jorisvandenbossche** [comment]
BTW, regarding the docs build for release. Now that the travis docs include the API docs, it's maybe also possible to just take the build files from there and put those on the stable docs

**Comment by jreback** [comment]
GitHub making things better: https://github.com/blog/2119-pull-request-and-issue-reactions

**Comment by jreback** [comment]
@TomAugspurger ok, just pushed the v0.18.0 tag. Pls build docs, when ready I can upload (or set you up for that). lmk.

**Comment by jreback** [comment]
Release announcement: https://groups.google.com/forum/#!topic/pydata/VXPVa4QVVMI

big thanks to @TomAugspurger for building the docs!

let the bugs roll in :)

I had a slight issue uploading, so the ``pandas-0.18.0.zip`` didn't make it (the ``.tar.gz``) is there though on PyPi. Not sure if this is a real problem or not.

**Comment by wesm** [comment]
thank you, jeff!
