### ISSUE TITLE
timezones discarded when calling .values and .unique()

### ISSUE THREAD

**Issue by trevorstephens** [pydata/pandas#12264]
Calling `values` to get a column of timestamps seems to be dropping the timezone whether it is a standard column or an index. `unique` also has problems for df columns, though indexes appear to work. Running 0.17.1 through conda.

	>>> from pytz import timezone
	>>> import pandas as pd
	>>> EASTERN = timezone('US/Eastern')
	>>> df = pd.DataFrame({'Time': ['2016-02-08T13:55:00', '2016-02-08T13:56:00'],
	...                    'Value': [1, 2]})
	>>> df.Time = pd.to_datetime(df.Time)
	>>> df.Time = df.Time.dt.tz_localize(EASTERN)
	>>> df.Time[0]
	Timestamp('2016-02-08 13:55:00-0500', tz='US/Eastern')
	>>> df.Time.values[0]
	numpy.datetime64('2016-02-08T10:55:00.000000000-0800')
	>>> df.Time.unique()
	array(['2016-02-08T10:55:00.000000000-0800',
	       '2016-02-08T10:56:00.000000000-0800'], dtype='datetime64[ns]')
	>>> df = df.set_index('Time')
	>>> df.index[0]
	Timestamp('2016-02-08 13:55:00-0500', tz='US/Eastern')
	>>> df.index.values[0]
	numpy.datetime64('2016-02-08T10:55:00.000000000-0800')
	>>> df.index.unique()
	DatetimeIndex(['2016-02-08 13:55:00-05:00', '2016-02-08 13:56:00-05:00'], dtype='datetime64[ns, US/Eastern]', name=u'Time', freq=None)

**Comment by jreback** [comment]
these return numpy constructs which don't support timezones.

**Comment by jreback** [comment]
docs are here: http://pandas.pydata.org/pandas-docs/stable/timeseries.html#tz-aware-dtypes
