### ISSUE TITLE
ValueError when opening a read-only hdf twice 

### ISSUE THREAD

**Issue by toobaz** [pydata/pandas#12266]
In [3]: with pd.HDFStore('/tmp/file_I_can_only_read.hdf') as store:
       ...:     store['test'] = pd.Series(range(3))
       ...:     

    In [4]: os.chmod('/tmp/file_I_can_only_read.hdf', 0o400)

    In [5]: store1 = pd.HDFStore('/tmp/file_I_can_only_read.hdf')
    Opening /tmp/file_I_can_only_read.hdf in read-only mode

    In [6]: store2 = pd.HDFStore('/tmp/file_I_can_only_read.hdf')
    ---------------------------------------------------------------------------
    ValueError                                Traceback (most recent call last)
    <ipython-input-6-5b173bb4a3e8> in <module>()
    ----> 1 store2 = pd.HDFStore('/tmp/file_I_can_only_read.hdf')

    /home/pietro/nobackup/repo/pandas/pandas/io/pytables.py in __init__(self, path, mode, complevel, complib, fletcher32, **kwargs)
        402         self._fletcher32 = fletcher32
        403         self._filters = None
    --> 404         self.open(mode=mode, **kwargs)
        405 
        406     @property

    /home/pietro/nobackup/repo/pandas/pandas/io/pytables.py in open(self, mode, **kwargs)
        563                             hdf_version=tables.get_hdf5_version()))
        564 
    --> 565             raise e
        566 
        567         except (Exception) as e:

    /home/pietro/nobackup/repo/pandas/pandas/io/pytables.py in open(self, mode, **kwargs)
        538 
        539         try:
    --> 540             self._handle = tables.open_file(self._path, self._mode, **kwargs)
        541         except (IOError) as e:  # pragma: no cover
        542             if 'can not be written' in str(e):

    /usr/lib/python3/dist-packages/tables/file.py in open_file(filename, mode, title, root_uep, filters, **kwargs)
        308                     "The file '%s' is already opened, but "
        309                     "in read-only mode.  Please close it before "
    --> 310                     "reopening in append mode." % filename)
        311             # 'w' means that we want to destroy existing contents
        312             elif mode == 'w':

    ValueError: The file '/tmp/file_I_can_only_read.hdf' is already opened, but in read-only mode.  Please close it before reopening in append mode.

**Comment by jreback** [comment]
and what is the problem? you need to open with with ``mode='r'``.

**Comment by toobaz** [comment]
It is just incoherent (you don't need ``mode='r'`` the first time) and less practical. If you're saying it's not a crucial bug... well, I agree.

**Comment by jreback** [comment]
still unclear 

what exactly is incoherent? it works exactly as intended

you have to be explicit - the default is append

**Comment by toobaz** [comment]
The default on read-only stores is read, but as you prefer.

**Comment by jreback** [comment]
it's much better to have an explicit error
