### ISSUE TITLE
high temporary memory usage on creation of DataFrame from list

### ISSUE THREAD

**Issue by allthedata** [pydata/pandas#12262]
When I create a DataFrame from a list of arrays, it temporarily uses a lot more memory and is slower than if I convert the list to an array first (if you want to test this, make sure you have enough memory or change the size of `a`):
```python
In [1]: import numpy as np
   ...: import pandas as pd
In [2]: a = np.random.rand(10000000, 10)
In [3]: print(a.nbytes / 1024 / 1024)
762.939453125
In [4]: a = list(a)
In [5]: %time b = pd.DataFrame(np.array(a))  # used memory goes up 840 MB
Wall time: 3.83 s
In [6]: %time c = pd.DataFrame(a)  # used memory goes up 5 GB, then drops back to 840 MB above previous value
Wall time: 26.6 s
```

The same problem exists when creating a DataFrame from a list of lists, but definitely not as bad:
```python
In [1]: import numpy as np
   ...: import pandas as pd
In [2]: a = np.random.rand(10000000, 10)
In [3]: a = [list(i) for i in a]
In [4]: %time b = pd.DataFrame(np.array(a))  # used memory goes up 840 MB
Wall time: 9.73 s
In [5]: %time c = pd.DataFrame(a)  # used memory goes up 1.3 GB, then drops back to 840 MB above previous value
Wall time: 8.52 s
```

Versions:
```text
INSTALLED VERSIONS
------------------
commit: None
python: 3.5.1.final.0
python-bits: 64
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None

pandas: 0.17.1
nose: 1.3.7
pip: 8.0.2
setuptools: 19.6.2
Cython: 0.23.4
numpy: 1.10.4
scipy: 0.17.0
statsmodels: 0.6.1
IPython: 4.0.3
sphinx: 1.3.1
patsy: 0.4.0
dateutil: 2.4.2
pytz: 2015.7
blosc: None
bottleneck: 1.0.0
tables: 3.2.2
numexpr: 2.4.6
matplotlib: 1.5.1
openpyxl: 2.3.2
xlrd: 0.9.4
xlwt: 1.0.0
xlsxwriter: 0.8.4
lxml: 3.5.0
bs4: 4.4.1
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.0.11
pymysql: None
psycopg2: None
Jinja2: 2.8
```

**Comment by jreback** [comment]
a simpler way to look at this is with ``memory_profiler``

```
In [1]: arr = np.random.rand(100000, 10)

In [2]: %memit DataFrame(arr)
peak memory: 67.15 MiB, increment: 0.15 MiB

In [3]: %memit DataFrame(np.array(arr))
peak memory: 74.82 MiB, increment: 7.64 MiB

In [4]: arr2 = np.array(arr)

In [6]: %memit np.array(arr)
peak memory: 82.47 MiB, increment: 7.63 MiB

In [5]: %memit DataFrame(arr2)
peak memory: 74.83 MiB, increment: 0.01 MiB
```

This is all as expected. What exactly do you think is a problem here?
a list-of-lists need to be copied to a numpy array structure

**Comment by allthedata** [comment]
I'm saying that if I use numpy to explicitly convert the list-of-arrays to an array first, it saves a lot of memory compared to letting pandas convert it. I'm assuming pandas does something like `np.array()` to convert the input if it realizes that it needs to be converted, so ideally it should use the same amount of memory as me explicitly converting it. Sorry if I'm missing something, but in your post there are no lists to be converted.

```python
In [1]: import numpy as np
   ...: import pandas as pd

In [2]: %load_ext memory_profiler

In [3]: arr = np.random.rand(100000, 10)

In [4]: list1 = list(arr)  # list of arrays

In [5]: %memit pd.DataFrame(list1)
peak memory: 140.37 MiB, increment: 49.91 MiB

In [6]: %memit pd.DataFrame(np.array(list1))
peak memory: 99.64 MiB, increment: 8.03 MiB

In [7]: list2 = [list(i) for i in arr]  # list of lists

In [8]: %memit pd.DataFrame(list2)
peak memory: 150.22 MiB, increment: 13.89 MiB

In [9]: %memit pd.DataFrame(np.array(list2))
peak memory: 140.18 MiB, increment: 5.34 MiB
```

**Comment by jreback** [comment]
@allthedata 

``np.array(list_of_array)`` is converting a singular dtype structure, then pandas simply takes a view on this and you are done.

However a list-of-list is not the same thing as it might have multiple dtypes and we cannot use ``np.array`` at all as it mostly does the wrong things.

Try this with a list of things that are not exactly the same dtype.

so not really sure what if anything one could do here, while preserving the input semantics. you are welcome to take a look.

if you find something interesting, pls reopen the issue.
