### ISSUE TITLE
python-statsmodels required for s390x arch?

### ISSUE THREAD

**Issue by coreycb** [pydata/pandas#12273]
The debian/control file has some logic that, in our case on ubuntu, only requires python-statsmodels for 390x.  Is it really required for s390x?

**Comment by jreback** [comment]
``statsmodels`` is only an optional dependency. In 0.18.0 (RC1 coming end of the week), all of the uses are deprecated, so it will be removed as an optional dep in the future.  No reason to have it depend in debian any longer.

**Comment by coreycb** [comment]
Thanks for the quick reply.
