### ISSUE TITLE
BUG: Pandas.DataFrame.where() behaves unexpectedly in v0.17.0 and up under Windows 8 x64

### ISSUE THREAD

**Issue by zk42** [pydata/pandas#12305]
Under Windows 8 (x64), with Pandas v0.17.0 (from Anaconda) and up, Pandas.DataFrame.where() function is found to behave sporadically, sometimes returning the expected result and sometimes returning a dataframe filled with zeros. 

The following code demonstrates this behavior, observed for dataframes that have larger than 361 rows and columns.

I observed that this problem does NOT exist in Pandas v0.16.2 on the same machine (Windows 8 x64, Anaconda), and in Pandas v0.17.1 under Mac OS (Anaconda).

```python
import numpy as np
import pandas as pd

n = 400
n_trials = 1000

df_1 = pd.DataFrame(data=np.random.random((n,n)), index=np.arange(0,n), columns=np.arange(0,n))
df_2 = pd.DataFrame(data=np.random.random((n,n)), index=np.arange(0,n), columns=np.arange(0,n))

count = 0
for i in xrange(0,n_trials):
  res = df_1.where(df_2 > 0.5)
  if (res < 1e-6).all().all():
    count += 1
print "number of unexpected cases: ", count
```
returns non-zero counts.

**Comment by jreback** [comment]
duplicate: https://github.com/pydata/pandas/issues/12023

install ``numexpr>=2.4.6`` and all will be well.

**Comment by zk42** [comment]
Thanks!
