### ISSUE TITLE
read_csv behavior with large floats

### ISSUE THREAD

**Issue by rbiswas4** [pydata/pandas#12340]
I have a data file in text which has 4 columns
```
$head sample.txt
SourceID Photons AvgX AvgY
6144039378640938.000000 71 1457.802817 2692.802817
6144053114071082.000000 8 1498.125000 2696.375000
6145000614093866.000000 0 nan nan
6145000614092842.000000 0 nan nan
6144137763642410.000000 0 nan nan
```
The 0th column really ought to have been int, but this is how the data file looks.
On trying to read it into a pandas, the [0, 0] element is read in as 6144039378640936.0. 
The behavior is correct is numpy, and might be related to the floating point representation of this huge
float. However, checking the dtypes both numpy and pandas seem to be using the same type.

(The sample file and an ipython notebook is also in https://github.com/rbiswas4/pandasProblem/blob/master/checkproblem.ipynb)
```
python
>>> import pandas as pd
>>> df = pd.read_csv('sample.txt', sep='\s+')
>>> df.ix[0,0]
6144039378640936.0

>>>import numpy as np
>>> ddf = pd.read_csv('sample.txt', sep='\s+', dtype={'SourceID': np.int64})
>>> ddf.ix[0, 0]
6144039378640936.0

>>> arr = np.loadtxt('sample.txt', skiprows=1)
>>> arr[0,0]
6144039378640938.0

>>> df.dtypes
SourceID    float64
Photons       int64
AvgX        float64
AvgY        float64
dtype: object
>>> ddf.dtypes
SourceID      int64
Photons       int64
AvgX        float64
AvgY        float64
dtype: object
>>> arr.dtype
dtype('float64')
>>> pd.show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.11.final.0
python-bits: 64
OS: Darwin
OS-release: 14.4.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

pandas: 0.17.1
nose: 1.3.7
pip: 8.0.2
setuptools: 19.6
Cython: 0.23.4
numpy: 1.10.4
scipy: 0.15.1
statsmodels: 0.5.0
IPython: 4.0.1
sphinx: 1.3.1
patsy: 0.3.0
dateutil: 2.4.2
pytz: 2015.7
blosc: None
bottleneck: None
tables: 3.2.2
numexpr: 2.4.4
matplotlib: 1.5.1
openpyxl: 1.8.5
xlrd: 0.9.3
xlwt: 0.7.5
xlsxwriter: 0.5.7
lxml: 3.4.0
bs4: 4.3.2
html5lib: 0.99999
httplib2: None
apiclient: None
sqlalchemy: 0.9.7
pymysql: None
psycopg2: None
Jinja2: None
```

**Comment by jreback** [comment]
you can try specifying the float_precision: http://pandas.pydata.org/pandas-docs/stable/io.html#specifying-method-for-floating-point-conversion

**Comment by rbiswas4** [comment]
Setting float_precision='high' fixes this problem. So, thanks!

But it would have seemed that (a) when I provide dtype, that should have taken care of this (b) If this is really np.float64 as indicated by printing out dtype, should this not have had the same behavior as numpy.

**Comment by jreback** [comment]
why would providing a dtype have anything do with this? this is all about parsing precision, where for virtually all cases the speed/precision tradeoff is good. otherwise you should use ``high_precision`` as indicated.

numpy's parser is different (and in python), while this is a c-parser. (you could get python semantics by using ``engine='python'`` but parsing speed is dramatically slower.
