### ISSUE TITLE
Inconsistencies in index comparisons

### ISSUE THREAD

**Issue by csiz** [pydata/pandas#12346]
Comparing indexes returns two different data types. This is problematic since one of the types is a bool while the other is a Series which [explicitly can't be treated in a bool context](http://pandas.pydata.org/pandas-docs/stable/gotchas.html#using-if-truth-statements-with-pandas). Not to mention that the next section says `==` returns a Series object.

```
import pandas as pd

print pd.__version__
# 0.14.0

index = pd.Int64Index([1, 2, 3])

print index == pd.Int64Index([])
# False
print index == pd.Int64Index([1])
# [True, False, False]
print index == pd.Int64Index([1, 2])
# False
print index == pd.Int64Index([4, 5, 6])
# [False, False, False]

series = pd.Series([1, 2, 3])

print series == pd.Series([1, 2])
# ValueError: Series lengths must match to compare

```

I'd suggest that comparing indexes with different lengths raise a `ValueError` like `Series` do. Possibly keeping the 1 element vs many as a special case

**Comment by jreback** [comment]
You are using a pretty old version of pandas, IIRC this was corrected in 0.16.1 or so. Current is 0.17.1, and 0.18.0 is coming out shortly

```
In [81]: index = pd.Int64Index([1, 2, 3])

In [82]: index == pd.Int64Index([])
ValueError: Lengths must match to compare

In [83]: index == pd.Int64Index([1])
ValueError: Lengths must match to compare

In [85]: index == pd.Int64Index([1, 2])
ValueError: Lengths must match to compare

In [86]: index == pd.Int64Index([4, 5, 6])
Out[86]: array([False, False, False], dtype=bool)
```
