### ISSUE TITLE
How to remove the " punctuation using .to_csv method?

### ISSUE THREAD

**Issue by rylanchiu** [pydata/pandas#12347]
I have a data frame as below:

    #user	 item	rating	time 	word_count	review
    3        2      4.0     131600  123         1 1 3 3 3 4 4 5 ..
    ......

The number in review denotes the word_id. When I apply the `to_csv` function:

    df.to_csv("data.votes", sep = " ", cols = ['user','item','rating','time','word count','review'], header = False, index = False)

The resulting text file is like:

    3 2 4.0 131600 123 "1 1 3 3 3 4 4 5...  101 "

How can I remove the annoying `"` ? It has a bad effect on running my model. Thank you in advance!

**Comment by jreback** [comment]
looks like you asked already on [SO](http://stackoverflow.com/questions/35434668/how-to-remove-the-punctuation-using-to-csv-method-in-pandas).

you are keeping a space delimited field in a dataframe, which is not recommended, but if you want then you cannot use a spec delimited output file w/o quoting. you can use a different output separator.
