### ISSUE TITLE
unexpected shape: np.nanmax returns Series when ran on a Series, unlike np.nanmean, np.max

### ISSUE THREAD

**Issue by DSLituiev** [pydata/pandas#12383]
When ran on a pd.Series np.nanmax returns Series, while `np.nanmean` and `np.max` return a scalar:

#### Code Sample, a copy-pastable example if possible
```
li = [1,2,3,4,5]
ds = pd.Series(li, index= ["%s"%x for x in li])

# these returns a scalar
print(np.nanmean(ds))
print(np.max(ds))

#this returns a Series
print(np.nanmax(ds))
```

#### Expected Output
a scalar

#### output of ``pd.show_versions()``

```

INSTALLED VERSIONS
------------------
commit: None
python: 3.4.3.final.0
python-bits: 64
OS: Linux
OS-release: 3.13.0-73-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

pandas: 0.17.1+306.g8cdfd4d
nose: 1.3.7
pip: 8.0.2
setuptools: 20.0
Cython: 0.23.4
numpy: 1.10.4
scipy: 0.16.1
statsmodels: 0.6.1
IPython: 4.0.3
sphinx: 1.2.2
patsy: 0.3.0
dateutil: 2.4.2
pytz: 2015.7
blosc: None
bottleneck: None
tables: 3.2.0
numexpr: 2.4.3
matplotlib: 1.5.1
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: 4.3.2
html5lib: 0.999
httplib2: 0.8
apiclient: None
sqlalchemy: 0.9.8
pymysql: None
psycopg2: None
jinja2: 2.7.3
```

**Comment by jreback** [comment]
this is a numpy issue, see [here](https://github.com/numpy/numpy/blob/master/numpy/lib/nanfunctions.py#L340). I don't know when/how this changed, but it looks like a different impl that ``nanmean``. I don't really know the reason this would be done. pls bring it up there. I guess will leave this open, but there is nothing pandas can do about this. 

Well there is if they properly handle ``__array_wrap__`` and returned something to know that we have a reduced function, but I don't think we need to go down that road.

**Comment by jreback** [comment]
This is numpy not testing subclasses & subclass-likes.

```
In [14]: np.nanargmax(ds)
Out[14]: 4
```
