### ISSUE TITLE
DataFrame.apply behaves inconsistently when a list returned by the function

### ISSUE THREAD

**Issue by pkch** [pydata/pandas#12415]
#### Code Sample, a copy-pastable example if possible
    import pandas as pd
    df = pd.DataFrame({'a':[1,2,3], 'b':[4,5,6]})
    assert type(df.apply(lambda column: [1,2])) == pd.Series
    assert type(df.apply(lambda column: [1,2,3])) == pd.DataFrame
    # when list length matches the relevant df size, the result is DF; otherwise, a Series of lists
#### Expected Output
This behavior is not documented, but more importantly it's really dangerous. A slight change in the inputs may cause a really hard-to-track bug. I think only two alternatives are safe:

1) When the function in `apply` returns a list, the result should always be a Series of lists. 
2) When the function in `apply` returns a list with the correct size, the result should be a DataFrame; otherwise, an error should be raised.

Approach 2) is obviously too restrictive, so I'd recommend approach 1).

On a related note, it would be nice to be able to explicitly tell `apply` whether I want a Series of lists or a DF as a result.

#### output of ``pd.show_versions()``
INSTALLED VERSIONS
------------------
commit: None
python: 3.5.0.final.0
python-bits: 64
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 70 Stepping 1, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None

pandas: 0.17.0
nose: None
pip: 8.0.2
setuptools: 18.2
Cython: 0.23.4
numpy: 1.10.1
scipy: 0.16.0
statsmodels: None
IPython: 4.0.0
sphinx: None
patsy: 0.4.1
dateutil: 2.4.2
pytz: 2015.6
blosc: None
bottleneck: None
tables: None
numexpr: 2.5
matplotlib: 1.5.0
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: None
pymysql: None
psycopg2: None
>>>

**Comment by jreback** [comment]
not really sure what you are asking. ``.apply`` does its best to infer what you arbitrary function is doing. using lists as elements of a pandas (or numpy object) is just completely non-performant / wrong idiom anyhow. What are you expecting?

**Comment by pkch** [comment]
It is wrong for large dataframes, for sure. But it's not prohibited by pandas, and for small dataframes it causes no harm. My problem is that the behavior is so unexpected - literally the Series becomes a DataFrame depending on the exact number of columns in the input. Just hard to debug.

**Comment by jreback** [comment]
well, you can try looking at it, but I dont suspect this is doable. ``.apply`` tries to figure out what is coming out and based the makeup return an appropriate object. As I said, having embedded lists then doing a non-reducing operation is quite weird.
