### ISSUE TITLE
WARN: matplotlib warnings

### ISSUE THREAD

**Issue by jreback** [pydata/pandas#12436]
anyone know the reason for these?  https://travis-ci.org/pydata/pandas/jobs/111469225
only seem to be on py3.

```
/home/travis/miniconda/envs/pandas/lib/python3.5/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
/home/travis/miniconda/envs/pandas/lib/python3.5/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
```

**Comment by jreback** [comment]
@TomAugspurger 
cc @tacaswell 
cc @mdboom

**Comment by tacaswell** [comment]
Odd that you are only seeing it on python3, should be seeing in everywhere (unless you are caching the font caches?).

On import systems with all the adobe fonts installed can take forever so a user warning got added.

See https://github.com/matplotlib/matplotlib/issues/5836

**Comment by jreback** [comment]
looks like nothing to be done on our side :<

**Comment by tacaswell** [comment]
You can cache the fontcache on travis which will also suppress the warning
