### ISSUE TITLE
to_html local float_format decimal representation

### ISSUE THREAD

**Issue by paulogp** [pydata/pandas#12445]
Hello,

 Because of the decimal symbol I'm forced to use the following code. The problem is when the using is "big", for example: 1 356 747 -> 1,35675e+06. Is there any work around?

import locale
loc = locale.getlocale()  # get current locale
locale.setlocale(locale.LC_NUMERIC, "Portuguese_Portugal")
html_table = df.to_html(header=True, index=False, na_rep="", float_format="{:n}".format, justify="center")
locale.setlocale(locale.LC_NUMERIC, loc)  # restore saved locale
print(html_table)

#### Code Sample, a copy-pastable example if possible
<tr>
      <td>AMOUNT</td>
      <td>1,35675e+06</td>
      <td>95 524</td>
      <td>179 347</td>
      <td>255 691</td>
    </tr>
#### Expected Output
<tr>
      <td>AMOUNT</td>
      <td>1 356 747</td>
      <td>95 524</td>
      <td>179 347</td>
      <td>255 691</td>
    </tr>
#### output of ``pd.show_versions()``
INSTALLED VERSIONS
------------------
commit: None
python: 3.5.1.final.0
python-bits: 64
OS: Windows
OS-release: 2012ServerR2
machine: AMD64
processor: Intel64 Family 6 Model 47 Stepping 2, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None

pandas: 0.17.1
nose: None
pip: 8.0.2
setuptools: 20.1.1
Cython: None
numpy: 1.10.4
scipy: 0.17.0
statsmodels: None
IPython: None
sphinx: None
patsy: None
dateutil: 2.4.2
pytz: 2015.7
blosc: None
bottleneck: None
tables: None
numexpr: None
matplotlib: 1.5.1
openpyxl: 2.3.2
xlrd: 0.9.4
xlwt: None
xlsxwriter: 0.8.4
lxml: None
bs4: None
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: None
pymysql: None
psycopg2: None
Jinja2: None
None

**Comment by jreback** [comment]
this was recently merged: https://github.com/pydata/pandas/pull/12417

and will be available in forthcoming 0.18.0 (its not in 0.18.0rc1).

this adds the ``decimal`` parameter which I think should work.

cc @nbonnotte

**Comment by nbonnotte** [comment]
Yes, `df.to_html(decimal=',')` should work in 0.18.0.

Until then, a workaround could be for instance `df.to_html(float_format=lambda x: '{:n}'.format(x).replace('.', ',', 1))`.

**Comment by paulogp** [comment]
Thank you very much for the help.
