### ISSUE TITLE
Cannot set with indexer when indexer is of length 1

### ISSUE THREAD

**Issue by grutts** [pydata/pandas#12444]
When setting using an indexer which is of length one I get AttributeError on assignment. The same error occurs with series of length greater than 1 and with indexer of length 1, but does not occur in the latter scenario if the indexer is of length greater than one. The .iloc[indexer] below returns a Series. 

Encountered in version 0.15.2, reproduced in 0.17.1

```python
>>> import pandas as pd
>>> import numpy as np
>>> import datetime

>>> mi = pd.MultiIndex.from_tuples([(3465, datetime.datetime.utcnow())])
>>> foo1 = pd.Series([5], index=mi); foo1
3465  2016-02-25 13:06:21.639667+00:00    5
3466  2016-02-25 13:06:21.639674+00:00    6
dtype: int64

>>> foo2 = pd.Series(['foo'], index=mi);foo2
3465  2016-02-25 13:06:21.638573+00:00    foo
dtype: object

>>> indexer= np.where(foo2);indexer
(array([0]),)

>>> foo1.iloc[indexer] = foo2.iloc[indexer]

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-87-320a8afb0fd6> in <module>()
----> 1 foo1.iloc[indexer] = foo2.iloc[indexer]

/python2.7/site-packages/pandas/core/indexing.pyc in __setitem__(self, key, value)
    115     def __setitem__(self, key, value):
    116         indexer = self._get_setitem_indexer(key)
--> 117         self._setitem_with_indexer(indexer, value)
    118 
    119     def _has_valid_type(self, k, axis):

/python2.7/site-packages/pandas/core/indexing.pyc in _setitem_with_indexer(self, indexer, value)
    365             # indexer here
    366             if (len(labels) == 1 and
--> 367                     isinstance(self.obj[labels[0]].axes[0], MultiIndex)):
    368                 item = labels[0]
    369                 obj = self.obj[item]

AttributeError: 'numpy.int64' object has no attribute 'axes'
``` 

#### output of ``pd.show_versions()``

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.6.final.0
python-bits: 64
OS: Linux
OS-release: 3.13.0-48-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: None

pandas: 0.17.1
nose: 1.3.7
pip: 1.4.1
setuptools: 17.0
Cython: 0.23.4
numpy: 1.9.0
scipy: 0.14.0
statsmodels: None
IPython: 4.0.0
sphinx: None
patsy: None
dateutil: 1.5
pytz: 2015.6
blosc: None
bottleneck: None
tables: None
numexpr: None
matplotlib: 1.5.0
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: 3.4.4
bs4: None
html5lib: 0.999
httplib2: 0.9
apiclient: 1.1
sqlalchemy: None
pymysql: None
psycopg2: None
Jinja2: None

**Comment by jreback** [comment]
your exampmle is not repro; don't use an import which is not required by pandas (django), nor is indexer2 defined

**Comment by grutts** [comment]
Apologies, indexer2 was meant to be indexer and I have imported datetime as opposed to timezone. Updated in original post.

**Comment by jreback** [comment]
``indexer`` is a tuple of an array which is not a valid indexer, ``np.where`` returns this so you must use ``indexer[0]``.

**Comment by jreback** [comment]
not really sure what you are trying to do. you generally don't even need to use ``np.where``, just use pandas indexing (which uses this under the hood).
