### ISSUE TITLE
Spark Translation Layer 

### ISSUE THREAD

**Issue by danfrankj** [pydata/pandas#12485]
Hey folks, I'm starting to use the pyspark.ml library and it'd be cool to create a translation layer from pandas to spark to make it easy for local code to easily translate into spark. I have two ideas and would would be great to hear feedback. If positive I'd be happy to create a PR. 

1) Direct translation  
```
spark_df = pandas_df.to_spark(spark_context)
```

2) Pseudo translation: only permit spark compatible operations on this DataFrame 
```
restricted_spark_df = pandas_df.restrict_spark()
```
Would error if any operation that would not work on a spark df were performed on this df. Harder, but potentially useful for seeing if code designed for local use can be used for spark, without even installing spark.

**Comment by jreback** [comment]
why do you think this should be in pandas rather than ``PySpark``?

**Comment by danfrankj** [comment]
@jreback 

I did notice that pyspark.sql.createDataFrame accepts a pandas.DataFrame so most of the work is done  but having it linked from pandas might be nice so that it's more discoverable? I guess I don't have terribly strong feelings about the translation layer living in pyspark instead but pandas does link into other DataFrame-like objects with some of the pandas.DataFrame.to_* methods and wouldn't be hard to have a to_spark method.

**Comment by jreback** [comment]
@danfrankj I am not saying this is hard. But *why* this should be a good thing to live in pandas. It is *already* in ``PySpark``. Why does pandas have to know about this? what good is that?

**Comment by danfrankj** [comment]
@jreback thinking about it some more, I think you're right. Probably best for this to just live in pyspark. Closing issue. Thanks!
