### ISSUE TITLE
DOC: Include unrendered style notebook in git, execute in build

### ISSUE THREAD

**Issue by TomAugspurger** [pydata/pandas#12521]
Did this for statsmodels the other week, works pretty well. Something like

```bash
jupyter nbconvert --ExecutePreprocessor.timeout=600 --to html --execute style.ipynb
```

https://nbconvert.readthedocs.org/en/latest/execute_api.html

**Comment by jreback** [comment]
yep - even better this actually catches errors
say you have a missing import

the only issue is if you have a deliberate exception (u need to put it in a markdown block instead)

**Comment by TomAugspurger** [comment]
This will have to wait on nbconvert 4.2,  which let's you specify the kernel when executing. I believe it's being released soon.

**Comment by jorisvandenbossche** [comment]
Closed by https://github.com/pydata/pandas/pull/13225
