### ISSUE TITLE
Allow .where to accept callable as condition

### ISSUE THREAD

**Issue by sinhrks** [pydata/pandas#12533]
#### Code Sample, a copy-pastable example if possible

Allow ``.where`` and ``.mask`` to accept ``callable`` as cond. This is useful if ``DataFrame`` is changed during method chaining.

```
df = pd.DataFrame(np.random.randn(2, 2))
df.where(lambda x: x > 0)
# currently raises ValueError
```

#### Expected Output

Should be the same as:

```
df.where(df > 0)
#           0         1
# 0  0.689202       NaN
# 1       NaN  0.261644
```

**Comment by jreback** [comment]
yeah I link to the master issue for this #11485; ``.query``, ``.where``, and indexers should accept callables
