### ISSUE TITLE
BLD: Math not rendered in Travis-built docs

### ISSUE THREAD

**Issue by evectant** [pydata/pandas#12543]
Travis-built docs do not appear to have math rendered correctly. See https://pandas-docs.github.io/pandas-docs-travis/computation.html#exponentially-weighted-windows for one example.

**Comment by evectant** [comment]
Apparently due to: `WARNING: LaTeX command 'latex' cannot be run (needed for math display), check the pngmath_latex setting`.

**Comment by jorisvandenbossche** [comment]
Yes, that is what I thought would be the reason, but it is strange that this warning is raised, as I explicitly added install of latex just for this.

But anyway, we maybe better switch to mathjax

**Comment by jorisvandenbossche** [comment]
Thanks for the report BTW!

**Comment by jreback** [comment]
not sure this is the problem. ``tex`` does appear to be unpacked. All that said my knowledge of how the latex is actually rendered is really small.

**Comment by jreback** [comment]
@jorisvandenbossche since you merged this I'll stand corrected!

**Comment by jorisvandenbossche** [comment]
Well, we'll see if it now shows correctly in the docs. But in any case, the warning disappeared from the travis logs.
