### ISSUE TITLE
Do pandas support a supervised binning?

### ISSUE THREAD

**Issue by Heipiao** [pydata/pandas#12542]
i want use qcut() to process my data?but i don't want to direct to binning by width.
so i want use a supervised binning.such as Entropy-bor based Binning.or can you tell another package for this?
thank you?

**Comment by sinhrks** [comment]
No, I think supervised learning is not the focus of pandas. scikit-learn has some issues, see here:

https://github.com/scikit-learn/scikit-learn/issues/5778
