### ISSUE TITLE
Provide logo as vector graphic

### ISSUE THREAD

**Issue by MaxNoe** [pydata/pandas#12575]
For presentations etc. it would be nice to be able to use
the pandas logo in any size.

Could you provide it as svg or pdf?

**Comment by jreback** [comment]
yeah still working on this. This is only a ``.png``, so we are creating a new one for this. :<

**Comment by MaxNoe** [comment]
Ah, nice. Not so fond of the old one.

**Comment by TomAugspurger** [comment]
Available at https://github.com/pydata/pandas/blob/master/doc/logo/pandas_logo.svg and the source code is [here](https://github.com/pydata/pandas/blob/master/doc/logo/pandas_logo.py)
