### ISSUE TITLE
SignedJwtAssertionCredentials has been removed from oauth2client version 2.00 breaking read_gbq

### ISSUE THREAD

**Issue by ctylerjda** [pydata/pandas#12572]
In pandas/io/gbq.py there is the function:

`def _test_google_api_imports():

    try:
        import httplib2  # noqa
        from apiclient.discovery import build  # noqa
        from apiclient.errors import HttpError  # noqa
        from oauth2client.client import AccessTokenRefreshError  # noqa
        from oauth2client.client import OAuth2WebServerFlow  # noqa
        from oauth2client.client import SignedJwtAssertionCredentials  # noqa
        from oauth2client.file import Storage  # noqa
        from oauth2client.tools import run_flow, argparser  # noqa
    except ImportError as e:
        raise ImportError("Missing module required for Google BigQuery "
                          "support: {0}".format(str(e)))`

This will fail for users with oauth2client version higher than 2.0.0 since SignedJwtAssertionCredentials  has been removed from the module. 

Google suggests other ways of handling service account credentials. See:
https://github.com/google/oauth2client/blob/master/CHANGELOG.md#v200

**Comment by jreback** [comment]
can you ``pd.show_versions()``

**Comment by jreback** [comment]
cc @tworec 
cc @parthea 
cc @andrewryno
cc @andrioni 
cc @jacobschaer

**Comment by ctylerjda** [comment]
>>> pd.show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.11.final.0
python-bits: 64
OS: Windows
OS-release: 8.1
machine: AMD64
processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None

pandas: 0.18.0rc1
nose: 1.3.7
pip: 8.1.0
setuptools: 20.2.2
Cython: None
numpy: 1.10.4
scipy: 0.17.0
statsmodels: None
xarray: None
IPython: None
sphinx: None
patsy: None
dateutil: 2.4.2
pytz: 2015.7
blosc: None
bottleneck: None
tables: None
numexpr: None
matplotlib: None
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
httplib2: 0.9.2
apiclient: 1.3.1
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.8
