### ISSUE TITLE
Panel.to_json NotImplemented but documented

### ISSUE THREAD

**Issue by MaxNoe** [pydata/pandas#12571]
Using pandas 0.17.1 i was trying to use `panel.to_json`,
like documented here:
http://pandas.pydata.org/pandas-docs/stable/generated/pandas.Panel.to_json.html

This raises an `NotImplementedError`.

**Comment by jreback** [comment]
oh this should be removed from the docs

it's not supported

**Comment by yjkimjunior** [comment]
Hello! I'd like to work on this as a starting point to further contributions to the pandas library. 

Is this simply a matter of deleting the line Panel.to_json in api.rst under Serialization/IO/Conversion in the docs? I'm still familiarizing myself with the codebase and sphinx.

**Comment by jreback** [comment]
yep
