### ISSUE TITLE
`apply` to multiple columns consumes a lot of memory

### ISSUE THREAD

**Issue by Noctune** [pydata/pandas#12584]
I was encouraged to post here after asking a [question on stackoverflow](stackoverflow.com/questions/35911319/pandas-apply-into-multiple-columns-consuming-lots-of-memory).

#### Code Sample, a copy-pastable example if possible
```
import numpy as np
import pandas as pd

# placeholder for real function
def process(x):
    return np.random.rand(100)

s = pd.Series(range(2700000))
df = s.apply(lambda x: pd.Series(process(x)))
```
#### Expected Output
Never finishes on my machine, as it consumes in excess of 16GB of RAM.

If I instead write `df = s.apply(lambda x: process(x))` then it finishes quite quickly and without consuming that much memory, but in an incorrect layout for my use. I would expect the above to perform close to the same, as the only difference is in the layout of the dataframe.

#### output of ``pd.show_versions()``
INSTALLED VERSIONS
------------------
commit: None
python: 3.4.3.final.0
python-bits: 64
OS: Linux
OS-release: 4.4.3-300.fc23.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_DK.UTF-8

pandas: 0.17.1
nose: None
pip: 7.1.0
setuptools: 18.0.1
Cython: None
numpy: 1.9.2
scipy: 0.14.1
statsmodels: None
IPython: 3.2.1
sphinx: None
patsy: None
dateutil: 2.4.2
pytz: 2015.4
blosc: None
bottleneck: 0.6.0
tables: 3.2.2
numexpr: 2.4.6
matplotlib: 1.4.3
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 0.9999999
httplib2: None
apiclient: None
sqlalchemy: 1.0.11
pymysql: None
psycopg2: None
Jinja2: None

**Comment by jreback** [comment]
what exactly are you trying to do?

In your example you are creating 100 rows x 2.7M columns. I doubt this is what you are expecting.
```
In [14]: s = pd.Series(range(10))

In [15]: s.apply(lambda x: pd.Series(process(x))).shape
Out[15]: (10, 100)
```

**Comment by Noctune** [comment]
>what exactly are you trying to do?

This is mostly just a demonstration of the problem. In my application I have a function that, given a value, computes a numpy array of size 100. I want to apply this function to a series and put the resulting list items in each column of the resulting data frame.

>In your example you are creating 100 rows x 2.7M columns.

Uh, no. I just tried replacing 2700000 with 1000, and I got 1000 rows and 100 columns. In your example there are 10 rows and 100 columns as well.

**Comment by jreback** [comment]
what exactly are you expecting to do?
are you meaning to apply row-wise?

you can just pass the series to your function.

**Comment by Noctune** [comment]
>what exactly are you expecting to do?

Just forget the function, it's not important. The core of my problem is this: given a series of *n* numpy arrays, each of length *m*, I want to return an *n* x *m* dataframe where each row is equal to the corresponding numpy array in the series.

The above does this just fine. It just consumes a massive amount of RAM in the process.

>are you meaning to apply row-wise?

Row-wise? But it's a series. I do not quite get what you mean.

>you can just pass the series to your function.

I can't. The function does not work with a pandas series, and is function from another library so I have no control over it. Hence why I want to apply it to each item in a series.

**Comment by Noctune** [comment]
A better example to demonstrate the problem:
```
# placeholder for actual data
s = pd.Series(range(2700000)).apply(lambda x: np.random.rand(100))

# consumes way to much memory and dies   :c
s.apply(lambda x: pd.Series(x))
```

**Comment by jreback** [comment]
that's the same as your above example

what are you expecting as output?

**Comment by Noctune** [comment]
For this particular example, I would expect something equivalent to `pd.DataFrame(np.random.rand(2700000, 100))`.

**Comment by jreback** [comment]
``.apply`` is expecting you to return a scalar, it *will* deal with a 2-dim structure but its not very efficient.

I would simply do this.

```In [10]: np.concatenate([ process(x) for x in s ])``

**Comment by Noctune** [comment]
>`.apply` is expecting you to return a scalar, it will deal with a 2-dim structure but its not very efficient.

Right, that is the bug I am reporting. At least, it seems like a bug to me. I have found a similar workaround in the stackoverflow question posted above.

**Comment by jreback** [comment]
that's not a bug but a convenience feature
u r expecting optimal perf when u r returning arbitrary things

**Comment by jreback** [comment]
The fundamental issue is that when these Series are put back together they need to align. And in this case you are looping over the alignment code (in python). You *could* make this faster by doing:

```
# this should be the same length as your function returns
In [17]: index = Index(range(100))

In [18]: s.apply(lambda x: Series(process(x), index=index))
```

Then the alignment is cheap as its the same index. So you are doing an operation constructed in such a way to use none of pandas power. You are essentially doing a python loop. I would suggest you re-think how you are going about this, and why you need the alignment.
