### ISSUE TITLE
sum(skipna=True) doesn't handle NAs as per docs

### ISSUE THREAD

**Issue by drbig** [pydata/pandas#12592]
#### Code Sample, a copy-pastable example if possible

```
In [50]: df
Out[50]: 
    a   b   c
0 NaN NaN NaN
1   1   1   1
2   1 NaN NaN

In [51]: df['total'] = df[['a', 'b', 'c']].sum(axis=1, skipna=True)

In [52]: df
Out[52]: 
    a   b   c  total
0 NaN NaN NaN      0
1   1   1   1      3
2   1 NaN NaN      1

In [53]: 
```
#### Expected Output

```
In [51]: df['total'] = df[['a', 'b', 'c']].sum(axis=1, skipna=True)

In [52]: df
Out[52]: 
    a   b   c  total
0 NaN NaN NaN      NaN
1   1   1   1      3
2   1 NaN NaN      1

In [53]: 
```

#### output of ``pd.show_versions()``

```
In [68]: pd.show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.11.final.0
python-bits: 64
OS: Linux
OS-release: 4.4.3-1-ARCH
machine: x86_64
processor: 
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8

pandas: 0.17.1
nose: 1.3.6
pip: 7.1.2
setuptools: 18.2
Cython: 0.23.4
numpy: 1.10.1
scipy: 0.16.0
statsmodels: 0.6.1
IPython: 4.0.0
sphinx: None
patsy: 0.4.0
dateutil: 2.4.2
pytz: 2015.6
blosc: None
bottleneck: 1.0.0
tables: 3.2.2
numexpr: 2.4.6
matplotlib: 1.4.3
openpyxl: 2.2.6
xlrd: 0.9.4
xlwt: None
xlsxwriter: None
lxml: 3.4.4
bs4: None
html5lib: 0.9999999
httplib2: 0.9.1
apiclient: 1.4.2
sqlalchemy: 1.0.11
pymysql: 0.6.6.None
psycopg2: 2.6.1 (dt dec pq3 ext lo64)
Jinja2: None

In [69]: 
```

####  Comment

As per [docs](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.sum.html): `Exclude NA/null values. If an entire row/column is NA, the result will be NA`.

So for a row where all columns are NA expected output is NA, not a zero. Same behaviour also happens for a `Series`.

**Comment by TomAugspurger** [comment]
That looks like the same issue as https://github.com/pydata/pandas/issues/9422. Can you confirm that, and close this issue if so?

The short version is, this is a difference in behavior between numpy/bottleneck and pandas.

**Comment by jreback** [comment]
though I suppose we could add a note to the doc-string to note this difference.

**Comment by jreback** [comment]
@drbig would take a PR for a doc-update.

**Comment by drbig** [comment]
Yes, it does indeed look like a duplicate, and yes if this is the intended behaviour (what a weird choice though...) then the docs need to be fixed (which I might PR, but nobody should hold their breath over that).

Thanks for quick response!
