### ISSUE TITLE
API: rename Index.sym_diff to Index.symmetric_difference

### ISSUE THREAD

**Issue by xflr6** [pydata/pandas#12591]
Following builtin `set`, I would expect the method name to be `symmetric_difference`.

How about deprecating `sym_diff` in favour of this (see also #6016, #8226)?

**Comment by TomAugspurger** [comment]
@xflr6, well said, We should have included `sym_diff` -> `symmetric_difference` along with the `diff` -> `difference` change.

Would you be interested in submitting a pull requests to deprecate `sym_diff` in favor of `symmetric_difference`?

**Comment by xflr6** [comment]
Sounds managable, sure.
