### ISSUE TITLE
Python Panda - No cell generated

### ISSUE THREAD

**Issue by datomnurdin** [pydata/pandas#12593]
#### Code Sample, a copy-pastable example if possible

I got no error messages but there are no cell generated after I execute my python script. I'm using EI-Capitan and python 2.7.

    import pandas as pd
    import warnings
    import seaborn as sns
    import matplotlib.pyplot as plt
    sns.set(style="white", color_codes=True)
    adult = pd.read_csv("data.csv")
    adult.head()

#### Expected Output

![screenshot 2016-03-11 21 09 48](https://cloud.githubusercontent.com/assets/5416242/13702902/c0c59c78-e7cc-11e5-9381-4f3fcd9dc92f.png)

#### output of ``pd.show_versions()``

```
INSTALLED VERSIONS
------------------
commit: None
python: 2.7.11.final.0
python-bits: 64
OS: Darwin
OS-release: 15.0.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: en_US.UTF-8
LANG: en_US.UTF-8

pandas: 0.17.0
nose: 1.3.7
pip: 8.1.0
setuptools: 19.4
Cython: 0.23.4
numpy: 1.10.4
scipy: 0.16.1
statsmodels: None
IPython: 4.0.0
sphinx: None
patsy: None
dateutil: 1.5
pytz: 2015.7
blosc: None
bottleneck: None
tables: None
numexpr: None
matplotlib: 1.5.0
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
httplib2: 0.9.2
apiclient: 1.4.2
sqlalchemy: None
pymysql: None
psycopg2: None
```

Please advice. Thank you.

**Comment by jreback** [comment]
pls show what your input file is.

**Comment by datomnurdin** [comment]
Just fixed the problem, insert `print` command.
