### ISSUE TITLE
Bug: Pandas Series name attribute can be array

### ISSUE THREAD

**Issue by chinskiy** [pydata/pandas#12610]
#### Code Sample

```
import pandas as pd
import numpy as np

ndarr = np.array([1,2,3])
series1 = pd.Series(ndarr, name=['series1'])
series2 = pd.Series([1,2,3], name='series2')

series1.name
##['series1']

result_df = pd.concat([series1, series2], axis=1)
result_df
##give **type error**

##also

series3 = pd.Series(ndarr, name=['series1', 'series2'])
series3.name
##['series1', 'series2']
```

#### Expected Output
get error when result_df try to be created with array name attribute,
or give error when try to create Series object with array argument in name attribute.
#### output of ``pd.show_versions()``
------------------
commit: None
python: 2.7.6.final.0
python-bits: 64
OS: Linux
OS-release: 4.2.0-30-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8

pandas: 0.18.0
nose: 1.3.7
pip: 8.1.0
setuptools: 20.2.2
Cython: 0.23.4
numpy: 1.10.4
scipy: 0.17.0
statsmodels: 0.6.1
xarray: None
IPython: 4.1.2
sphinx: 1.3.6
patsy: 0.4.1
dateutil: 2.5.0
pytz: 2015.7
blosc: None
bottleneck: None
tables: None
numexpr: None
matplotlib: 1.5.1
openpyxl: 2.3.3
xlrd: 0.9.4
xlwt: None
xlsxwriter: 0.8.4
lxml: 3.5.0
bs4: 4.4.1
html5lib: 1.0b8
httplib2: 0.9.2
apiclient: None
sqlalchemy: 1.0.12
pymysql: None
psycopg2: 2.6.1 (dt dec pq3 ext lo64)
jinja2: 2.8
boto: None

**Comment by jreback** [comment]
there was an old issue somewhat related: https://github.com/pydata/pandas/pull/9193

but this *should* be caught. want to investigate and see where this is happening?

**Comment by chinskiy** [comment]
Okay, I'll try.
