### ISSUE TITLE
Use DataFrame.join with just some levels of a multiindex

### ISSUE THREAD

**Issue by wolever** [pydata/pandas#12628]
It would be nice if there was some way to join based on just some levels of a MultiIndex. For example, given a DataFrame like:

```
>>> df = pd.DataFrame({"a": [1, 1, 2], "b": [11, 12, 13], "c": [21, 22, 23]}).set_index(["a", "b"])
>>> df
       c
a b     
1 11  21
  12  22
2 13  23
```

I'd like to join it to another DataFrame along, for example, just the first level of the index:

```
>>> other = pd.DataFrame({"a": [1, 2], "x": [91, 92]}).set_index("a")
>>> other
    x
a    
1  91
2  92
>>> df.join(other, left_index=["a"])
       c   x
a b         
1 11  21  91
  12  22  91
2 13  23  92
```

Or something similar.

As far as I can tell, the only way to do this now is with a combination of `reset_index` and `set_index`:

```
>>> df.reset_index().join(other, on="a").set_index(["a", "b"])
       c   x
a b         
1 11  21  91
  12  22  91
2 13  23  92
```

**Comment by jreback** [comment]
This will already work if the the names match.

```
In [18]: df.join(other)
Out[18]: 
       c   x
a b         
1 11  21  91
  12  22  91
2 13  23  92
```

Or even with a swapped level.
```
In [22]: df.swaplevel(0,1).join(other)
Out[22]: 
       c   x
b  a        
11 1  21  91
12 1  22  91
13 2  23  92
```

This is the point of named Indexes, they *can* do this kind of auto-joining.
