### ISSUE TITLE
BUG: Series.rename treats Series as list-like instead of mapping

### ISSUE THREAD

**Issue by TomAugspurger** [pydata/pandas#12623]
```python
#### Code Sample, a copy-pastable example if possible

In [6]: s = pd.Series([0, 1])

In [5]: s.rename(pd.Series({0: 10, 1: 20}))
Out[5]:
0    0
1    1
Name: [10, 20], dtype: int64
```

Problem is [here](https://github.com/pydata/pandas/blob/4f5099b4ee5f5c32f6b299de93902c9a074ac228/pandas/core/series.py#L2336) using an `isinstance(,MutableMapping)` instead of `com.is_dict_like`. [`rename_axis`](https://github.com/pydata/pandas/blob/4f5099b4ee5f5c32f6b299de93902c9a074ac228/pandas/core/generic.py#L705) should be fine, but will add tests for both.

**Comment by jreback** [comment]
Indexes are NOT dict_like though (Series ARE). so something else happening.

```
In [3]: pandas.core.common.is_dict_like(pd.RangeIndex(10))
Out[3]: False

In [4]: pandas.core.common.is_dict_like(pd.Index([1,2,3]))
Out[4]: False
```

**Comment by TomAugspurger** [comment]
Ah.... my bad. I thought I didn't reproduce it with a non-RangeIndexed series, but I must have been mistaken.

```python
In [52]: s.rename(pd.Series({'a': 'A', 'b': 'B'}))
Out[52]:
a    0
b    1
Name: [A, B], dtype: int64
```

I'll update.

**Comment by jreback** [comment]
somewhat related to #12610 (IOW setting the ``.name`` with a list should just fail), but you don't need to explicity check for this (well, you do but for a different reason, namely that you are doing something different with it)

**Comment by TomAugspurger** [comment]
Updated, can't believe I missed this. Will have a fix tonight.
