### ISSUE TITLE
add pandas.read_text for complex text/log parsing

### ISSUE THREAD

**Issue by AbsoluteMSTR** [pydata/pandas#12646]
Current method is using read_table/read_csv and placing logic in sep field is a bruteforce way to process log files, but isn't clean as you will get two padded columns of NaN at the start and end and does not handle parameter of regex for column names.

#### Code Sample, a copy-pastable example if possible

df = pd.read_table("file.log",
              sep=r'^(?P<datetime>[\d\-]+? [\d:]+?) (?P<level>.+?) \[(?P<name>.+?)\] \((?P<filename>.+?):(?P<lineno>\d+?)\) \- (?P<message>.*?)$',
             )

df currently would produce...

 | 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7
-------|-------|-------|-------|-------|-------|-------|-------|-------
0 | NaN | 2015-01-01 00:00:00 | INFO | main | main.java | 10 | Hello World | NaN
1 | NaN | 2015-01-01 00:00:00 | ERROR | main | main.java | 11 | Ouch! | NaN
#### Expected Output

 |datetime | level | name | filename | lineno | message
-------|------|-------|-------|-------|-------|-------
0|2015-01-01 00:00:00 | INFO | main | main.java | 10 | Hello World
1|2015-01-01 00:00:00 | ERROR | main | main.java | 11 | Ouch!

#### output of ``pd.show_versions()``

INSTALLED VERSIONS
------------------
commit: None
python: 3.5.1.final.0
python-bits: 64
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 63 Stepping 2, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None

pandas: 0.18.0
nose: 1.3.7
pip: 8.1.0
setuptools: 20.2.2
Cython: 0.23.4
numpy: 1.10.4
scipy: 0.17.0
statsmodels: 0.6.1
xarray: 0.7.1
IPython: 4.1.1
sphinx: 1.3.1
patsy: 0.4.0
dateutil: 2.5.0
pytz: 2016.1
blosc: None
bottleneck: 1.0.0
tables: 3.2.2
numexpr: 2.5
matplotlib: 1.5.1
openpyxl: 2.3.3
xlrd: 0.9.4
xlwt: 1.0.0
xlsxwriter: 0.8.2
lxml: 3.5.0
bs4: 4.4.1
html5lib: 0.9999999
httplib2: 0.9.2
apiclient: None
sqlalchemy: 1.0.12
pymysql: 0.7.1.None
psycopg2: None
jinja2: 2.8
boto: 2.39.0

**Comment by jreback** [comment]
how is this any different that passing to read_csv?

exactly what would your function do that the 50+ options in read_csv cannot?

**Comment by AbsoluteMSTR** [comment]
read_csv, read_table can do this, however you're hooking into sep field, which serves for how to seperate the values, however some log files do not use a common separator and hence you are injecting regular expression logic on how to read a file and it doesn't handle parameters from a regex.

**Comment by TomAugspurger** [comment]
Wouldn't it be better to write a generator expression to extract the fields from a file object, and then construct a DataFrame from that? What would the advantage of having a dedicated method be?

**Comment by jreback** [comment]
@AbsoluteMSTR you would have to show a sample file (small sample), and how a better API would help here.

**Comment by AbsoluteMSTR** [comment]
@TomAugspurger, It's entirely possible to utilize a generator as an alternative to read_csv, read_table, but the question becomes if pandas should be able to provide api support toward complex text files like a log file.

@jreback a generic example can be an access.log file generated by Apache HTTPd
```
127.0.0.1 - - [13/Sep/2013:01:38:09 -0400] "GET / HTTP/1.1" 200 - "-" "-"
127.0.0.1 - - [13/Sep/2013:01:38:09 -0400] "GET /testing HTTP/1.1" 200 - "-" "-"
127.0.0.1 - - [13/Sep/2013:01:38:10 -0400] "GET /index.html HTTP/1.1" 200 - "-" "-"
```

**Comment by jreback** [comment]
@AbsoluteMSTR this parses really easily, and will be WAY more performant that using a regex.

```
In [7]: pd.read_csv('test.log',sep='\s+',header=None)
Out[7]: 
           0  1  2                      3       4                         5    6  7  8  9
0  127.0.0.1  -  -  [13/Sep/2013:01:38:09  -0400]            GET / HTTP/1.1  200  -  -  -
1  127.0.0.1  -  -  [13/Sep/2013:01:38:09  -0400]     GET /testing HTTP/1.1  200  -  -  -
2  127.0.0.1  -  -  [13/Sep/2013:01:38:10  -0400]  GET /index.html HTTP/1.1  200  -  -  -
```

sure it needs some cleanup, but this is straightforward.

**Comment by jreback** [comment]
closing as needs more justification.
