### ISSUE TITLE
API: why are we importing pandas.tseries.period.pnow into the pd namespace?

### ISSUE THREAD

**Issue by jreback** [pydata/pandas#12641]
from ``pandas.tseries.api``

if someone can take a look and see when this was added?

I don't think this is useful at all. Let's just deprecate and remove this function entirely. Could always add a ``Period.now()``.

**Comment by jorisvandenbossche** [comment]
Added already a long time ago: https://github.com/pydata/pandas/commit/13d435b3354022366b3264c3cb2cc33edcefd672

But I agree we can deprecate it

**Comment by jreback** [comment]
closing, will be tracked in #13790
