### ISSUE TITLE
COMPAT: read_excel not supporting pathlib.Path

### ISSUE THREAD

**Issue by mangecoeur** [pydata/pandas#12655]
According to the 0.17.1 release notes:

> pd.read_* functions can now also accept pathlib.Path, or py._path.local.LocalPath objects for the filepath_or_buffer argument. (#11033)

Doing so with read_excel gives `ValueError: Must explicitly set engine if not passing in buffer or path for io.`

See also #11773

#### output of ``pd.show_versions()``
python: 3.5.1.final.0
python-bits: 64
OS: Darwin
OS-release: 15.3.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8

pandas: 0.18.0
nose: 1.3.7
pip: 8.1.0
setuptools: 20.2.2
Cython: 0.23.4
numpy: 1.10.4
scipy: 0.17.0
statsmodels: 0.6.1
xarray: 0.7.1
IPython: 4.1.2
sphinx: 1.3.5
patsy: 0.4.0
dateutil: 2.4.2
pytz: 2015.7
blosc: None
bottleneck: 1.0.0
tables: 3.2.2
numexpr: 2.4.6
matplotlib: 1.5.1
openpyxl: 2.3.2
xlrd: 0.9.4
xlwt: 1.0.0
xlsxwriter: 0.8.4
lxml: 3.5.0
bs4: 4.4.1
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.0.11
pymysql: None
psycopg2: 2.6.1 (dt dec pq3 ext)
jinja2: 2.8
boto: 2.39.

**Comment by jreback** [comment]
that was not a fully specified release note. certainly tests/fixes welcome. This is pretty straightforward to do.
