### ISSUE TITLE
ERR: better error message on invalid window when using .rolling

### ISSUE THREAD

**Issue by anntzer** [pydata/pandas#12669]
xref #12765. Let's pick up this as a test case and give a more meaningful error message. e.g. for ``Window`` the ``win_type`` is missing, so this should be the error.

```
In [15]: pd.DataFrame(np.arange(10)).rolling(2., center=True).median()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-15-73c4e557093d> in <module>()
----> 1 pd.DataFrame(np.arange(10)).rolling(2., center=True).median()

/usr/lib/python3.5/site-packages/pandas/core/window.py in median(self, **kwargs)
    811     @Appender(_shared_docs['median'])
    812     def median(self, **kwargs):
--> 813         return super(Rolling, self).median(**kwargs)
    814 
    815     @Substitution(name='rolling')

/usr/lib/python3.5/site-packages/pandas/core/window.py in median(self, how, **kwargs)
    592         if self.freq is not None and how is None:
    593             how = 'median'
--> 594         return self._apply('roll_median_c', how=how, **kwargs)
    595 
    596     _shared_docs['std'] = dedent("""

/usr/lib/python3.5/site-packages/pandas/core/window.py in _apply(self, func, window, center, check_minp, how, **kwargs)
    473             # calculation function
    474             if center:
--> 475                 offset = _offset(window, center)
    476                 additional_nans = np.array([np.NaN] * offset)
    477 

/usr/lib/python3.5/site-packages/pandas/core/window.py in _offset(window, center)
   1356 def _offset(window, center):
   1357     if not com.is_integer(window):
-> 1358         window = len(window)
   1359     offset = (window - 1) / 2. if center else 0
   1360     try:

TypeError: object of type 'float' has no len()
```
Note that `pd.DataFrame(np.arange(10)).rolling(2.).median()` works fine.

pandas 0.18.0.

**Comment by jreback** [comment]
yeah looks like the validation is only in place for a ``Window`` and not the ``Rolling`` and sub-classes. It should be an int, or raise a nicer message.

pull-requests welcome.

**Comment by shoyer** [comment]
I would prefer requiring an int raising with an informative `TypeError` in this case.

**Comment by anntzer** [comment]
I'm also in favor of requiring ints too.

**Comment by pt247** [comment]
Dose this look all right? I don't think we need ' whatsnew entry'. Do we?

**Comment by jreback** [comment]
@pt247 pls comment on PRs directly - always need a whatsnew entry

**Comment by gliptak** [comment]
The input validation is inconsistent in ```window.py```. I was proposing to reuse ```_prep_window`` to unify behaviour. Could somebody familiar with the code offer guidance (instead of spot fixes)? Thanks

**Comment by jreback** [comment]
@gliptak these DO have different validations, as ``Window`` can accept an integer or an integer array, while ``Rolling`` can only accept an integer. This does not require a big change.

**Comment by gliptak** [comment]
I closed https://github.com/pydata/pandas/issues/12714, https://github.com/pydata/pandas/pull/12718 is closer to the approach described.

**Comment by jreback** [comment]
ok, that's fine.
