### ISSUE TITLE
Installation issue: Exception: Cython-generated file 'pandas/index.c' not found

### ISSUE THREAD

**Issue by dunk** [pydata/pandas#12670]
I'm attempting to install pandas via pip on Ubuntu 14.04 (inside Docker, for what it's worth, so doing it as root with no virtualenv - the Docker container serves that purpose.). I get the following exception:

```
    Exception: Cython-generated file 'pandas/index.c' not found.
                    Cython is required to compile pandas from a development branch.
                    Please install Cython or download a release package of pandas.
```

This is strange, because earlier this week the exact same configuration built correctly. What's changed? Is there something else I ned to do?

**Comment by jreback** [comment]
are you trying to install the development version?

**Comment by jreback** [comment]
pls comment if you are still having issues

**Comment by yuvraj2987** [comment]
Hi,
I am also running into this issue and I am trying to install pandas using pip.

**Comment by jorisvandenbossche** [comment]
The error message says "Please install Cython or download a release package of pandas." Did you try that?

**Comment by yuvraj2987** [comment]
@jorisvandenbossche as far as I understand pip package shouldn't worry about cython. Its required if you are building from source. But may be I am wrong.
Another addition, I am able to pip install package on CentOS7 and cython module is not installed there as well.
So may be this is only specific to CentOS6.6.

**Comment by jorisvandenbossche** [comment]
I am afraid you have to worry about cython. There are no binary wheels available for linux (or: not yet), so pip does install pandas from source, which needs cython to build the extensions

**Comment by yuvraj2987** [comment]
But why then it works on CentOS7?
