### ISSUE TITLE
ERR: dont' allow ambiguous usecols

### ISSUE THREAD

**Issue by jreback** [pydata/pandas#12678]
https://github.com/pydata/pandas/pull/12551 and comment: https://github.com/pydata/pandas/pull/12512#discussion_r56771668

``usecols=['a',1]`` should raise

**Comment by gfyoung** [comment]
@jreback : I'll tackle this one as a follow-up in terms of fixing documentation and enforcement.  In the meantime, I'll remove the tests I added that had the ambiguous columns.

**Comment by jorisvandenbossche** [comment]
Shouldn't we also just raise on duplicates in `usecols` ? eg `['a', 'a']`

**Comment by gfyoung** [comment]
@jorisvandenbossche : `usecols` is a set, so you won't ever have such a problem.

**Comment by jreback** [comment]
https://github.com/pydata/pandas/issues/11823

**Comment by jorisvandenbossche** [comment]
@gfyoung aha, I didn't know that, but then adding tests for the behaviour for duplicates values in `usecols` as we are doing in https://github.com/pydata/pandas/pull/11882 makes no sense?

**Comment by jreback** [comment]
what we could do is:

- don't allow mixed-integers (e.g. 'a', 1) as these are ambiguous
- still use a set for ``usecols``, so duplicates are gone, but handle this as a set-selection operation against ``.names/columns`` (IOW if names is passed or a header is read in). If there are duplicates there its ok, this ``usecols`` just sub-selects. Duplicate handling will be solely there.

**Comment by gfyoung** [comment]
@jreback : What do you mean by "duplicate" handling?  Is that what #11823 will be doing?

**Comment by jreback** [comment]
This is on master.

```
In [12]: pd.read_csv(StringIO("""1,2,3"""), engine='c', header=None, 
   ....:             names=['a', 'b', 'a'], usecols=['a','a'])
Out[12]: 
   a  a
0  1  1

In [13]: pd.read_csv(StringIO("""1,2,3"""), engine='python', header=None, 
            names=['a', 'b', 'a'], usecols=['a','a'])
Out[13]: 
   a
0  1
```

but I think that these should BOTH output

```
   a   a
0 1    3
```

IOW, the ``usecols`` is just a filter as a set (so its ``'a'`` in this case).

Then names takes over and you get the 0th and 2nd columns (that are named 'a')

**Comment by jreback** [comment]
cc @sxwang

**Comment by gfyoung** [comment]
@jreback : AFAICT, such behaviour will be fixed in #11823 right?

**Comment by jorisvandenbossche** [comment]
@jreback I agree

@gfyoung Well the PR for that issue is https://github.com/pydata/pandas/pull/11882, and currently there it is not yet this behaviour (but still in reviewing phase)

**Comment by gfyoung** [comment]
Okay, but in terms of allocation, that issue should be tackled there, and I could just handle the enforcing non-ambiguous `usecols`, right?

**Comment by jorisvandenbossche** [comment]
@gfyoung yes, that's right!

**Comment by jreback** [comment]
yep that sounds right. let's restrict this issue to ambiguous errors
