### ISSUE TITLE
Regression: date_range closed parameter not honoured in pandas 0.18.0

### ISSUE THREAD

**Issue by PH82** [pydata/pandas#12684]
The behaviour of the method [date_range](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.date_range.html) appears to have changed between version 17 and 19. the below example changes the starting bound of the index returned?

`print pd.date_range(start=datetime.datetime(2016,3,18,0,0), end=datetime.datetime(2016,3,22,0,0), freq='D', tz='UTC', closed='right')`

**pandas 0.17.0 Output**
DatetimeIndex(['2016-03-19', '2016-03-20', '2016-03-21', '2016-03-22'], dtype='datetime64[ns, UTC]', freq='D')

**pandas 0.18.0 Output**
DatetimeIndex(['2016-03-18', '2016-03-19', '2016-03-20', '2016-03-21', '2016-03-22'],
              dtype='datetime64[ns, UTC]', freq='D')

python: 2.7.11.final.0

**Comment by jreback** [comment]
this was originally this issue: https://github.com/pydata/pandas/issues/11804
and fixed here: https://github.com/pydata/pandas/pull/11806

**Comment by jreback** [comment]
yeah this coerces to the basic data (i8) right before the closed detection which is incorrect.

pull-requests welcome!

**Comment by jreback** [comment]
cc @hcontrast 
cc @thrasibule

**Comment by jreback** [comment]
right about [here](https://github.com/pydata/pandas/blob/master/pandas/tseries/index.py#L531)

**Comment by PH82** [comment]
Okay thanks, I'll keep an eye out for the fix.

**Comment by jreback** [comment]
@PH82 if you'd like to submit a patch would be helpful.
