### ISSUE TITLE
df.sample() much slower than df.iloc[randint]

### ISSUE THREAD

**Issue by aewhatley** [pydata/pandas#12703]
It seems like the Dataframe sample function is much slower than directly selecting a randomly indexed row:

import pandas as pd
import numpy as np
from time import time

>>> test_df = pd.DataFrame(np.random.randint(0, 100, size = (400, 600)))
>>> def f():
...  start = time()
...  for _ in range(100):
...   test_df.sample()
...  print(time() - start)
... 
>>> def g():
...  start = time()
...  for _ in range(100):
...   test_df.iloc[np.random.randint(0, test_df.shape[0])]
...  print(time() - start)
... 
>>> f()
0.571173906326
>>> g()
0.0156011581421

**Comment by jreback** [comment]
these are not the same thing. 

- ``.sample`` takes the the number of rows (when axis=0, the default), in this case its 1
- ``.sample`` uses ``np.random.choice`` which allows replacement (or not), default is not to replace

This takes about 5ms not sure this can actually matters anyhow.
