### ISSUE TITLE
ERR: validation options that accept callables

### ISSUE THREAD

**Issue by jreback** [pydata/pandas#12706]
https://github.com/pydata/pandas/issues/12704#issuecomment-200554983

```
In [1]: pd.describe_option('float_format')
display.float_format : callable
    The callable should accept a floating point number and return
    a string with the desired format of the number. This is used
    in some places like SeriesFormatter.
    See core.format.EngFormatter for an example.
    [default: None] [currently: None]
```

This should raise
```
In [2]: pd.set_option('float_format','%.1f')
```

**Comment by jreback** [comment]
the issue is that in ``core/config_init.py`` ``float_format`` doesn't have a validator.

**Comment by tdhopper** [comment]
Right: [here](https://github.com/pydata/pandas/blob/eb87db9e3dffe7febb575b82bf26065e807c028b/pandas/core/config_init.py#L282). 

Is [`callable`](https://docs.python.org/2/library/functions.html#callable) sufficient?

**Comment by jreback** [comment]
you could prob just create a ``is_callable = callable`` [here](https://github.com/pydata/pandas/blob/master/pandas/core/config.py#L800)

and ``validator=is_callable`` would work I think
