### ISSUE TITLE
Performance degradation with new pandas version

### ISSUE THREAD

**Issue by enzoFerrazzano** [pydata/pandas#12709]
Hi there, 
I noticed that there is some serious degradation in the performance with groupby and aggregate:
For instance, if I run this code:

import pandas as pd, numpy as np,time
nsim=10000
ncol=3000
np.random.seed(42)
index=np.random.randint(0,100,nsim)
values=np.random.normal(size=(nsim, ncol))
df=pd.DataFrame(index=index,data=values)
t=time.time()
df.groupby(lambda x:x,sort=False).agg(np.argmax)
time.time()-t

with the current version (0.18.0) I get:
>> 34.31084680557251
with the previous version (0.17.1):
>> 20.637927055358887

For my code performance is very important, so I would be glad if that could be solved.

Thank you very much,
Vincenzo Ferrazzano

#### output of ``pd.show_versions()``
INSTALLED VERSIONS
------------------
commit: None
python: 2.7.11.final.0
python-bits: 64
OS: Darwin
OS-release: 15.4.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: it_IT.UTF-8

pandas: 0.18.0  ( other version: 0.17.1)
nose: 1.3.7
pip: 8.1.1
setuptools: 20.3
Cython: 0.23.4
numpy: 1.10.4
scipy: 0.17.0
statsmodels: 0.6.1
xarray: None
IPython: 4.1.2
sphinx: 1.3.5
patsy: 0.4.0
dateutil: 2.5.1
pytz: 2016.2
blosc: None
bottleneck: 1.0.0
tables: 3.2.2
numexpr: 2.5
matplotlib: 1.5.1
openpyxl: 2.3.2
xlrd: 0.9.4
xlwt: 1.0.0
xlsxwriter: 0.8.4
lxml: 3.6.0
bs4: 4.4.1
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.0.12
pymysql: None
psycopg2: None
jinja2: 2.8
boto: 2.39.0

**Comment by jreback** [comment]
What you are doing is pretty odd (generating a random index). You need to use built-in functions.

```
In [125]: nsim = 10000

In [126]: ncol = 3000

In [127]: index=np.random.randint(0,100,nsim)

In [128]: values=np.random.normal(size=(nsim, ncol))

In [129]: df=pd.DataFrame(index=index,data=values)

In [119]: r1 = df.groupby(lambda x:x,sort=False).idxmax()
In [121]: r2 = df.groupby(lambda x:x,sort=False).agg(np.argmax)

In [124]: r2.astype(int).equals(r1)
Out[124]: True

In [130]: %timeit df.groupby(lambda x:x,sort=False).idxmax()
1 loop, best of 3: 794 ms per loop
```

**Comment by enzoFerrazzano** [comment]
Hi, thank you for you quick reply!
I am sorry, I generate the wrong behaviour.
What I need is rather

df.groupby(lambda x:x,sort=False).agg(lambda x: (x.values).argmax())
that is, return the position within the group of the maximum.

**Comment by jreback** [comment]
you are still doing a pure-python operation (if anything its worse now).

try this, will give you an indexer into the frame.
```df.reset_index(drop=True).groupby(df.index,sort=False).idxmax()```

**Comment by enzoFerrazzano** [comment]
Great, that works like a charm!
Thank you!
