### ISSUE TITLE
pd.rolling_mean for window = 1 does not exactly match input time series

### ISSUE THREAD

**Issue by FXLab91** [pydata/pandas#12708]
In order to have a more generic notation in my code, I want to express my original time series as a moving average over 1 period.
Quite unexpectedly, using pandas pd.rolling_mean function, the two are not exactly the same:

    import pandas as pd
    import numpy as np

    np.random.seed(1)

    ts = pd.Series(np.random.rand(1000))

    mavg = pd.rolling_mean(ts, 1)

    (ts - mavg).describe()
    Out[120]: 
    count    1.000000e+03
    mean     6.284973e-16
    std      3.877250e-16
    min     -3.330669e-16
    25%      3.330669e-16
    50%      5.551115e-16
    75%      8.881784e-16
    max      1.554312e-15
    dtype: float64

    any((ts - mavg).dropna()>0)
    Out[121]: True
    
Clearly the difference is very small and due to float rounding. Still I wonder if the function should not simply default to return the input when window = 1

**Comment by jreback** [comment]
this is within floating point tolerance. This special case is only true for sum/mean ops, not generally, so not worth special casing (and then you would have to special case ``min_periods`` and all kinds of things). not worth it.
