### ISSUE TITLE
upload to Requires.io?

### ISSUE THREAD

**Issue by gliptak** [pydata/pandas#12720]
Could a project organization member upload pandas to https://requires.io/ ? I will add badge to README after. Thanks

**Comment by jreback** [comment]
can u point to some larger projects that use this and why ?

**Comment by gliptak** [comment]
While not larger project, I noted this used with
https://requires.io/github/xmlrunner/unittest-xml-reporting/requirements/?branch=master
letting us know which dependencies are to be bumped (keeping up with latest patches from those projects).

**Comment by shoyer** [comment]
I'm afraid this would not be useful for pandas. We maintain a very minimal set of dependencies with only minimal, not pinned versions and don't have a requirements.txt file. Moreover, our testing infrastructure runs on conda, which is not even supported by requires.io.

This sort of service is really targeted at applications, for which you want to use pinned, known working versions of all dependencies. It's not very relevant for libraries like pandas.
