### ISSUE TITLE
Allow .expanding() to be called on groupby object

### ISSUE THREAD

**Issue by lminer** [pydata/pandas#12738]
Right now when I want to have expanding operate at the level of a group I have to apply a convenience function like so:

```python
def expanding_sum(s):
    return s.expanding().sum()

expanded_sum = df.groupby('mygroup')['mynum'].apply(expanding_sum)
```

Would be nice to be able to call a method directly on a groupby object:

```python
expanded_sum = df.groupby('mygroup')['mynum'].expanding().sum()
```

**Comment by jreback** [comment]
related to #12486 

yes this should be possible - have to manage the dispatching correctly
