### ISSUE TITLE
Random seg fault ?

### ISSUE THREAD

**Issue by mehdigmira** [pydata/pandas#12744]
The code below randomly generates a seg fault. I'm just doing the exact same thing 10000 times. The segfault happens randomly, even if the first iterations have succeeded. Sometimes the whole code will run with no problem.
The bug appears more often when using ipython. It also appears when using a regular python sheel but it's difficult to reproduce.

```
import pandas as pd
pool_data = pd.read_csv('repro2.csv')
for i in range(10000):
    print i
    b = ((pool_data['day_x'] >= -5) & (pool_data['day_x'] <= -10) & (pool_data['cabine'] == 1))
    adj = pool_data.loc[b]
```

data:
https://drive.google.com/file/d/0B1VHOF9GpzXOdVBRSktyelJsM2s/view?usp=sharing

I did some tests. On ipython:

Run n°1: segfault at iteration 2666
Run n°2: no segfault
Run n°3: segfault at iteration 5157
Run n°4: segfault at iteration 3191
Run n°5: segfault at iteration 3422

On regular python shell:

Run n°1: no segfault
Run n°2: segfault at iteration 2593
Run n°3: no segfault
Run n°4: no segfault
Run n°5: segfault at iteration 6220

#### output of ``pd.show_versions()``
INSTALLED VERSIONS
------------------
commit: None
python: 2.7.6.final.0
python-bits: 64
OS: Linux
OS-release: 3.19.0-56-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

pandas: 0.18.0
nose: 1.3.4
pip: 6.0.6
setuptools: 20.3.1
Cython: 0.23.4
numpy: 1.11.0
scipy: 0.16.1
statsmodels: 0.6.1
xarray: None
IPython: 4.1.2
sphinx: None
patsy: 0.4.1
dateutil: 2.5.2
pytz: 2016.3
blosc: None
bottleneck: None
tables: None
numexpr: None
matplotlib: 1.5.0
openpyxl: 2.3.1
xlrd: None
xlwt: None
xlsxwriter: None
lxml: 3.4.0
bs4: None
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 0.9.8
pymysql: None
psycopg2: 2.5.4 (dt dec pq3 ext)
jinja2: 2.8
boto: None

**Comment by jreback** [comment]
so I ran on almost the exact same setup. same cpu / linux, with numpy 1.11, both pandas 0.18.0 & master. my only difference is using python 2.7.11.final. didn't have any faults. (ran many times).

what you are doing looks perfectly fine. 

assume you are NOT trying to do anything with theads. if so then that is a no-no as this is certainly not threadsafe.

if you manage to have a more repro will certainly take a look.

just make sure that you are indeed running under this exact environment (e.g. if you had ``numexpr`` installed that DOES use threads).
