### ISSUE TITLE
empty DataFrame applymap methods returns an empty Series

### ISSUE THREAD

**Issue by soujiro86** [pydata/pandas#12746]
I have an empty DataFrame which can be empty in some cases, when i cast applymap() and return the value it is a Series object.

**v 0.18 and v 0.17.1**

**Comment by soujiro86** [comment]
Duplicated issue, original one: https://github.com/pydata/pandas/issues/8222

Sorry guys!

**Comment by jreback** [comment]
@soujiro86 np. that is not too hard to fix, if you want to have a go.
