### ISSUE TITLE
Allow dtype option to from_records constructor

### ISSUE THREAD

**Issue by lminer** [pydata/pandas#12751]
It would be nice to be able to specify `dtype` of the various columns to a `DataFrame` in the `DataFrame.from_records()` constructor. Mostly because this is the constructor used by Spark in its [toPandas()](https://github.com/apache/spark/blob/master/python/pyspark/sql/dataframe.py#L1366) method.

Something like this would make it easier to either preserve type information from a Spark dataframe, or take advantage of pandas types without having to load dates, categoricals, etc as objects first.

**Comment by jreback** [comment]
not sure what else you would need. This is by-definition a record array that has dtypes already specified.

```
In [6]: arr = np.zeros((2,), dtype=('i4,f4,a10'))

In [7]: arr[:] = [(1, 2., 'Hello'), (2, 3., "World")]

In [8]: arr
Out[8]: 
array([(1, 2.0, 'Hello'), (2, 3.0, 'World')], 
      dtype=[('f0', '<i4'), ('f1', '<f4'), ('f2', 'S10')])

In [9]: df = DataFrame.from_records(arr)

In [10]: df.dtypes
Out[10]: 
f0      int32
f1    float32
f2     object
dtype: object
```

**Comment by lminer** [comment]
Ah. My mistake. I thought it was for json!
