### ISSUE TITLE
executemany in pd.to_sql?

### ISSUE THREAD

**Issue by MaximilianR** [pydata/pandas#12760]
Currently, the generic SQLTable uses `execute` rather than `executemany`. I'm fairly green on these issues, but my understanding is that it's materially slower, depending on the driver used.
https://github.com/pydata/pandas/blob/master/pandas/io/sql.py#L745

The SQLite version *does* use `executemany`: https://github.com/pydata/pandas/blob/master/pandas/io/sql.py#L1441

Does anyone know why this uses `execute`? Or whether my assumptions on the speed difference are incorrect?

CC @zzzeek

**Comment by zzzeek** [comment]
SQLAlchemy connections don't have an executemany() method like the Python DBAPI does; executemany() is used internally automatically.  http://docs.sqlalchemy.org/en/rel_1_0/core/tutorial.html#executing-multiple-statements

**Comment by MaximilianR** [comment]
Great, thanks @zzzeek. 

My mistake was that this only applies where we don't have SQLAlchemy installed: 

>The SQLite version does use executemany: https://github.com/pydata/pandas/blob/master/pandas/io/sql.py#L1441

Closing
