### ISSUE TITLE
Should be a faster way to get numerical values for categorical data

### ISSUE THREAD

**Issue by Poincare** [pydata/pandas#12788]
#### Code Sample, a copy-pastable example if possible
Running the following with a huge DataFrame with lots of variance within "huge_col" can often cause massive memory overuse:
`pd.get_dummies(huge_df["huge_col"]).values.argmax(1) #times out`

The point here, of course, is to be able to convert the elements of "huge_col" into a column of integers rather than the one-hot coded vectors that `pd.get_dummies()` returns. However, this method of doing so is inefficient since it expands out the one-hot coded vectors in memory. Adding an option to `get_dummies` to allow for integer return values or introducing a different function seems like an ideal solution to this issue. If there is an alternative, straightforward solution that's recommended, please do suggest!

Thanks.

**Comment by jreback** [comment]
pls show a copy-pastable example of what you are doing (just on a smaller frame)

**Comment by sinhrks** [comment]
Maybe ``.factorize`` is what you want.

```
s = pd.Series(['A', 'B', 'C', 'A'])
fac, _ = pd.factorize(s)
fac
# array([0, 1, 2, 0])
```

**Comment by jreback** [comment]
or using a ``categorical``, see [here](http://pandas.pydata.org/pandas-docs/stable/categorical.html), which is what ``pd.get_dummies`` is essentially doing

**Comment by Poincare** [comment]
These make sense. I'll close this issue.
