### ISSUE TITLE
fromnumeric.py compatibility with GroupBy, Window, and tslib functions

### ISSUE THREAD

**Issue by gfyoung** [pydata/pandas#12811]
In #12810, it was decided that compatibility for `groupby` (including `resample.py`) and `window` functions would be left for a separate PR / discussion, which seems reasonable given how massive #12810 already is.  This issue serves a reminder to tackle this after landing #12810, as it seems like this can be easily addressed afterwards.

**Comment by gfyoung** [comment]
@jreback : Adding timestamps and timedeltas as well to this issue given my question about `tslib.pyx`.

**Comment by gfyoung** [comment]
With my initial `fromnumeric.py` PR merged, it seems like a good idea to revisit this.  The major files that I think merit examination for `numpy` compatibility are:
`pandas/core/window/window.py`
`pandas/tseries/resample.py`
`pandas/core/groupby.py`
`pandas/tslib.pyx`

**Comment by jreback** [comment]
how so, I don't really care to be compat with numpy for anything beyond very basic stuff. pls show an example.

**Comment by gfyoung** [comment]
Examples:
`tslib.round(self, freq)`
`window.max(self, how=None, **kwargs)`
`resample.var(self, ddof=1)`
`groupby.mean(self)`
All I was thinking of doing was putting validation calls in the implementation, similar to what was done in my previous PR and nothing more than that.

**Comment by jreback** [comment]
```
In [1]: df = DataFrame({'A' : [1,2,1], 'B' : [1,2,3]})

In [2]: g = df.groupby('A')

In [3]: g.mean()
Out[3]: 
   B
A   
1  2
2  2

In [4]: np.mean(g)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-fdcd38489fcb> in <module>()
----> 1 np.mean(g)

/Users/jreback/miniconda/lib/python2.7/site-packages/numpy/core/fromnumeric.pyc in mean(a, axis, dtype, out, keepdims)
   2878         try:
   2879             mean = a.mean
-> 2880             return mean(axis=axis, dtype=dtype, out=out)
   2881         except AttributeError:
   2882             pass

TypeError: mean() got an unexpected keyword argument 'axis'
```

**Comment by jreback** [comment]
ok that doesn't seem unreasonable

**Comment by jorisvandenbossche** [comment]
Do we actually *want* something like `np.mean(g)` to work? 
A groupby object is not an array-like such as a Series. IMO we shouldn't put effort in enabling such usage

**Comment by gfyoung** [comment]
@jorisvandenbossche : I'll leave that for you to debate with @jreback .  To reiterate, I am perfectly fine either way.  This is not a serious compatibility issue as the previous one I raised in #12644.
