### ISSUE TITLE
How to select content store in the Panel using 'item' index

### ISSUE THREAD

**Issue by Fredericxian** [pydata/pandas#12820]
#### wp
```
Out[50]: 
<class 'pandas.core.panel.Panel'>
Dimensions: 2 (items) x 55640 (major_axis) x 9 (minor_axis)
Items axis: 0 to 1
Major_axis axis: 0 to 55639
Minor_axis axis: TradingDay to AskVolume1

store.select('wp','items>0')
Traceback (most recent call last):

  File "<ipython-input-51-79d40b638607>", line 1, in <module>
    store.select('wp','items>0')

  File "C:\Anaconda3\lib\site-packages\pandas\io\pytables.py", line 680, in select
    return it.get_result()

  File "C:\Anaconda3\lib\site-packages\pandas\io\pytables.py", line 1364, in get_result
    results = self.func(self.start, self.stop, where)

  File "C:\Anaconda3\lib\site-packages\pandas\io\pytables.py", line 673, in func
    columns=columns, **kwargs)

  File "C:\Anaconda3\lib\site-packages\pandas\io\pytables.py", line 3671, in read
    if not self.read_axes(where=where, **kwargs):

  File "C:\Anaconda3\lib\site-packages\pandas\io\pytables.py", line 3222, in read_axes
    self.selection = Selection(self, where=where, **kwargs)

  File "C:\Anaconda3\lib\site-packages\pandas\io\pytables.py", line 4584, in __init__
    self.condition, self.filter = self.terms.evaluate()

  File "C:\Anaconda3\lib\site-packages\pandas\computation\pytables.py", line 586, in evaluate
    self.filter = self.terms.prune(FilterBinOp)

  File "C:\Anaconda3\lib\site-packages\pandas\computation\pytables.py", line 117, in prune
    res = pr(left.value, right.value)

  File "C:\Anaconda3\lib\site-packages\pandas\computation\pytables.py", line 112, in pr
    encoding=self.encoding).evaluate()

  File "C:\Anaconda3\lib\site-packages\pandas\computation\pytables.py", line 276, in evaluate
    self)

  File "C:\Anaconda3\lib\site-packages\pandas\core\base.py", line 42, in __str__
    return self.__unicode__()

  File "C:\Anaconda3\lib\site-packages\pandas\computation\pytables.py", line 228, in __unicode__
    "[{1}]".format(self.filter[0], self.filter[1]))

TypeError: 'NoneType' object is not subscriptable
```

if I use item==0, it can be selected successfully.

```
store.select('wp','items==0')
Out[52]: 
<class 'pandas.core.panel.Panel'>
Dimensions: 1 (items) x 55640 (major_axis) x 9 (minor_axis)
Items axis: 0 to 0
Major_axis axis: 0 to 55639
Minor_axis axis: AskPrice1 to UpdateTime
```

#### output of ``pd.show_versions()``
INSTALLED VERSIONS
------------------
commit: None
python: 3.5.1.final.0
python-bits: 64
OS: Windows
OS-release: 8.1
machine: AMD64
processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: zh_CN

pandas: 0.18.0
nose: 1.3.7
pip: 8.1.1
setuptools: 20.3
Cython: 0.23.4
numpy: 1.10.4
scipy: 0.17.0
statsmodels: None
xarray: None
IPython: 4.0.3
sphinx: 1.3.1
patsy: 0.4.0
dateutil: 2.4.2
pytz: 2015.7
blosc: None
bottleneck: 1.0.0
tables: 3.2.2
numexpr: 2.4.6
matplotlib: 1.5.1
openpyxl: 2.3.2
xlrd: 0.9.4
xlwt: 1.0.0
xlsxwriter: 0.8.4
lxml: 3.5.0
bs4: 4.4.1
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.0.11
pymysql: None
psycopg2: None
jinja2: 2.8
boto: 2.39.0

**Comment by jreback** [comment]
pls show how you stored the panel.

**Comment by jreback** [comment]
You are treating the index like they are numbers, but they are not, they are just labels. You *can* select if things are stored in certain ways, pls read the docs [here](http://pandas.pydata.org/pandas-docs/stable/io.html#querying-a-table). The 0th axis in general cannot be indexed like this, you will need to store your panel with swapped dimensions.

```
In [9]: p = tm.makePanel()

In [10]: p.to_hdf('test.hdf','p',format='table')

In [11]: pd.read_hdf('test.hdf','p',where='items="ItemA"')
Out[11]: 
<class 'pandas.core.panel.Panel'>
Dimensions: 1 (items) x 30 (major_axis) x 4 (minor_axis)
Items axis: ItemA to ItemA
Major_axis axis: 2000-01-03 00:00:00 to 2000-02-11 00:00:00
Minor_axis axis: A to D

In [12]: pd.read_hdf('test.hdf','p',where='items in ["ItemA","ItemB"]')
Out[12]: 
<class 'pandas.core.panel.Panel'>
Dimensions: 2 (items) x 30 (major_axis) x 4 (minor_axis)
Items axis: ItemA to ItemB
Major_axis axis: 2000-01-03 00:00:00 to 2000-02-11 00:00:00
Minor_axis axis: A to D

In [13]: p
Out[13]: 
<class 'pandas.core.panel.Panel'>
Dimensions: 3 (items) x 30 (major_axis) x 4 (minor_axis)
Items axis: ItemA to ItemC
Major_axis axis: 2000-01-03 00:00:00 to 2000-02-11 00:00:00
Minor_axis axis: A to D
```

**Comment by Fredericxian** [comment]
Thanks for your quick response! 
My whole process of storing the panel is:

wp=pd.Panel([tick_data_final.values,tick_data_final.values],major_axis=tick_data_final.index,minor_axis=tick_data_final.columns,dtype=int)


wp
Out[9]: 
<class 'pandas.core.panel.Panel'>
Dimensions: 2 (items) x 55640 (major_axis) x 9 (minor_axis)
Items axis: 0 to 1
Major_axis axis: 0 to 55639
Minor_axis axis: TradingDay to AskVolume1

store =pd.HDFStore(U'C:\\tinysoft_data\\table_int2.h5',"a",complevel=9,complib='zlib')

 store.append('wp',wp)

 store
Out[19]: 
<class 'pandas.io.pytables.HDFStore'>
File path: C:\tinysoft_data\table_int3.h5
/wp            wide_table   (typ->appendable,nrows->500760,ncols->3,indexers->[major_axis,minor_axis])

The items index of panel, I set it as number. When I query 
store.select('wp','items==0')
It can be successfully execute, the result is:

<class 'pandas.core.panel.Panel'>
Dimensions: 1 (items) x 55640 (major_axis) x 9 (minor_axis)
Items axis: 0 to 0
Major_axis axis: 0 to 55639
Minor_axis axis: AskPrice1 to UpdateTime

But the question is that I want to query the table from n to m!
like
store.select('wp','items>0') # I want the table from the second table to the last, but it happen the error above

Actually, I don't want to use suck a complex way to query the data. Because If I just use pd.DataFrame to store the data, we only can call the data using their names.
 
For example
store
Out[50]: 
<class 'pandas.io.pytables.HDFStore'>
File path: C:\tinysoft_data\table_int4.h5
/table1            frame_table  (typ->appendable,nrows->8,ncols->1,indexers->[index])
/table2            frame_table  (typ->appendable,nrows->8,ncols->1,indexers->[index])
/table3            frame_table  (typ->appendable,nrows->8,ncols->1,indexers->[index])
/table4            frame_table  (typ->appendable,nrows->8,ncols->1,indexers->[index])
 
How can I query table2 to table4, are there any easy way like wp.iloc[1:4]

The other question is how to store the mixed data type panel into the hdf5
if the dtype not equal to the same type 
wp=pd.Panel([tick_data_final.values,tick_data_final.values],major_axis=tick_data_final.index,minor_axis=tick_data_final.columns)

store.append('wp',wp)

TypeError: Cannot serialize the column [0] because
its data contents are [mixed] object dtype

**Comment by Fredericxian** [comment]
last but no least, how can I update the Panel data stored in the hdf5

wp
Out[125]: 
<class 'pandas.core.panel.Panel'>
Dimensions: 2 (items) x 55546 (major_axis) x 9 (minor_axis)
Items axis: 0 to 1
Major_axis axis: 0 to 55545
Minor_axis axis: TradingDay to AskVolume1

wp1=pd.Panel([tick_data_final.values,tick_data_final.values],items=[2,3],major_axis=tick_data_final.index,minor_axis=tick_data_final.columns,dtype=str)

wp1
Out[127]: 
<class 'pandas.core.panel.Panel'>
Dimensions: 2 (items) x 55546 (major_axis) x 9 (minor_axis)
Items axis: 2 to 3
Major_axis axis: 0 to 55545
Minor_axis axis: TradingDay to AskVolume1

store.append('wp',wp1)
Traceback (most recent call last):

  File "<ipython-input-128-4be9357a8c3c>", line 1, in <module>
    store.append('wp',wp1)

  File "C:\Anaconda3\lib\site-packages\pandas\io\pytables.py", line 919, in append
    **kwargs)

  File "C:\Anaconda3\lib\site-packages\pandas\io\pytables.py", line 1264, in _write_to_group
    s.write(obj=value, append=append, complib=complib, **kwargs)

  File "C:\Anaconda3\lib\site-packages\pandas\io\pytables.py", line 3787, in write
    **kwargs)

  File "C:\Anaconda3\lib\site-packages\pandas\io\pytables.py", line 3415, in create_axes
    item in items))

ValueError: cannot match existing table structure for [0,1] on appending data
