### ISSUE TITLE
Time Zone problem with tz_localize

### ISSUE THREAD

**Issue by LorenzoBottaccioli** [pydata/pandas#12823]
Hi All,

I'm having a issue with tz_localize, maybe is my misunderstanding.

I'm importing a dataframe and I want to se the timezone for central Europe:
 
So if I use **Eurpe/Rome** I get:
```
In [303]: df.index.tz_localize('Europe/Rome')
Out[303]: 
DatetimeIndex(['2012-12-15 00:00:00+01:00', '2012-12-15 00:15:00+01:00',
               '2012-12-15 00:30:00+01:00', '2012-12-15 00:45:00+01:00',
               '2012-12-15 01:00:00+01:00', '2012-12-15 01:15:00+01:00',
               '2012-12-15 01:30:00+01:00', '2012-12-15 01:45:00+01:00',
               '2012-12-15 02:00:00+01:00', '2012-12-15 02:15:00+01:00',
               ...
               '2015-10-20 21:30:00+02:00', '2015-10-20 21:45:00+02:00',
               '2015-10-20 22:00:00+02:00', '2015-10-20 22:15:00+02:00',
               '2015-10-20 22:30:00+02:00', '2015-10-20 22:45:00+02:00',
               '2015-10-20 23:00:00+02:00', '2015-10-20 23:15:00+02:00',
               '2015-10-20 23:30:00+02:00', '2015-10-20 23:45:00+02:00'],
              dtype='datetime64[ns, Europe/Rome]', name=u'Date Time', length=8064, freq=None)
```
But I dont want to use dst because my timeseries is with no dst so I tried to use **Etc/GMT+1**

```
In [305]: df.index.tz_localize('Etc/GMT+1')
Out[305]: 
DatetimeIndex(['2012-12-15 00:00:00-01:00', '2012-12-15 00:15:00-01:00',
               '2012-12-15 00:30:00-01:00', '2012-12-15 00:45:00-01:00',
               '2012-12-15 01:00:00-01:00', '2012-12-15 01:15:00-01:00',
               '2012-12-15 01:30:00-01:00', '2012-12-15 01:45:00-01:00',
               '2012-12-15 02:00:00-01:00', '2012-12-15 02:15:00-01:00',
               ...
               '2015-10-20 21:30:00-01:00', '2015-10-20 21:45:00-01:00',
               '2015-10-20 22:00:00-01:00', '2015-10-20 22:15:00-01:00',
               '2015-10-20 22:30:00-01:00', '2015-10-20 22:45:00-01:00',
               '2015-10-20 23:00:00-01:00', '2015-10-20 23:15:00-01:00',
               '2015-10-20 23:30:00-01:00', '2015-10-20 23:45:00-01:00'],
              dtype='datetime64[ns, Etc/GMT+1]', name=u'Date Time', length=8064, freq=None)
```
I don't get why now I have -1 in stead of +1.
If I use **Etc/GMT-1**  I get:
```
In [304]: df.index.tz_localize('Etc/GMT-1')
Out[304]: 
DatetimeIndex(['2012-12-15 00:00:00+01:00', '2012-12-15 00:15:00+01:00',
               '2012-12-15 00:30:00+01:00', '2012-12-15 00:45:00+01:00',
               '2012-12-15 01:00:00+01:00', '2012-12-15 01:15:00+01:00',
               '2012-12-15 01:30:00+01:00', '2012-12-15 01:45:00+01:00',
               '2012-12-15 02:00:00+01:00', '2012-12-15 02:15:00+01:00',
               ...
               '2015-10-20 21:30:00+01:00', '2015-10-20 21:45:00+01:00',
               '2015-10-20 22:00:00+01:00', '2015-10-20 22:15:00+01:00',
               '2015-10-20 22:30:00+01:00', '2015-10-20 22:45:00+01:00',
               '2015-10-20 23:00:00+01:00', '2015-10-20 23:15:00+01:00',
               '2015-10-20 23:30:00+01:00', '2015-10-20 23:45:00+01:00'],
              dtype='datetime64[ns, Etc/GMT-1]', name=u'Date Time', length=8064, freq=None)
```

Central Europe should be **Etc/GMT+1** is it rigth?

Tnx

**Comment by jreback** [comment]
``pd.show_versions()`` pls

**Comment by jreback** [comment]
and pls show your original index construction, IOW a copy-pastable example.

**Comment by jreback** [comment]
not really sure what your question is.

**Comment by LorenzoBottaccioli** [comment]
```
In [307]: pd.show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.6.final.0
python-bits: 64
OS: Linux
OS-release: 4.2.0-35-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: it_IT.UTF-8

pandas: 0.17.1
nose: None
pip: 1.5.4
setuptools: 3.3
Cython: None
numpy: 1.8.2
scipy: 0.13.3
statsmodels: None
IPython: 1.2.1
sphinx: None
patsy: None
dateutil: 1.5
pytz: 2012c
blosc: None
bottleneck: None
tables: None
numexpr: None
matplotlib: 1.5.1
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 0.999
httplib2: 0.8
apiclient: None
sqlalchemy: None
pymysql: None
psycopg2: 2.4.5 (dt dec mx pq3 ext)
Jinja2: None
```

**Comment by LorenzoBottaccioli** [comment]
The question is:
If Central Euorpe is GTM+1 why is is use tz_localize('Etc/GMT+1) I get -1 in the index? Here you find the file I have used.

Tnx 
[test.zip](https://github.com/pydata/pandas/files/208735/test.zip)

**Comment by jreback** [comment]
this is a pure timezone question, you might want to ask on ``pytz`` or ``dateutil`` (btw you are using VERY old versions of those)

**Comment by LorenzoBottaccioli** [comment]
I have update pytz but I get same results!

**Comment by jreback** [comment]
I StaticTZ's are a funny beast they don't handle DST properly, so they are rarely used. I don't know what you are after. Showing a file and say here it is, is not useful. Pls show a copy-pastable example. I have no idea what you did with that file.
```
In [8]: pytz.timezone('Etc/GMT-1')
Out[8]: <StaticTzInfo 'Etc/GMT-1'>

In [9]: pytz.timezone('Etc/GMT+1')
Out[9]: <StaticTzInfo 'Etc/GMT+1'>

In [10]: pytz.timezone('Europe/Rome')
Out[10]: <DstTzInfo 'Europe/Rome' RMT+0:50:00 STD>
```

**Comment by LorenzoBottaccioli** [comment]
Hi Jeff,
The file I have send you is a copy of the time series that I have to
manage. I know for sure that on the date time column, dst has not been
applied. The point is why if you set GMT+1 you get -1 in the index and if
you put GMT-1 you get +1. Central Europe (Rome or Amsterdam) should be
GMT+1, if I'm not wrong.

Best,
Lorenzo
Il 07 apr 2016 6:28 PM, "Jeff Reback" <notifications@github.com> ha scritto:

**Comment by EbrahimKaram** [comment]
Did anyone solve this?
I'm using pandas version 1.00

Here is my pd.show_versions() output.
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.8.1.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 142 Stepping 9, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United States.1252

pandas           : 1.0.0
numpy            : 1.18.1
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 41.2.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.1
IPython          : 7.12.0
pandas_datareader: None
bs4              : 4.8.2
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.2.1
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : None
pyxlsb           : None
s3fs             : None
scipy            : 1.4.1
sqlalchemy       : 1.3.15
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : None
None
[Finished in 4.956s]
