### ISSUE TITLE
 pd.get_dummies(s) with s being a logical test

### ISSUE THREAD

**Issue by randomgambit** [pydata/pandas#12849]
Hi, 

I am using Pandas more and more for preparing my dataset before feeding it to other statistical software. 

I believe something really useful and, somehow, missing from the current version of Pandas is a simple way to generate dummy variables based on a logical test. 

Dummy variable coding (0-1) is everywhere in the academic literature (I have a phd in economics) and are a key component of many statistical tests.

Something like 

` pd.get_dummies(df.A > df.C)` that would generate a dummy that is one if A>C and zero otherwise, allowing the user to 

- include/exclude missing variables
- specify what happens when columns have mixed types (see (https://stackoverflow.com/questions/36373681/how-to-create-dummy-variables-in-pandas-when-columns-can-have-mixed-types)

Of course, we can always generate the dummies above manually, but the experience shows that this simply dummy variable creation can be, at times, tricky.

What do you think?

**Comment by jreback** [comment]
can you show a small concrete example.

**Comment by randomgambit** [comment]
master=pd.DataFrame({'A':pd.date_range('2012-02-02','2012-02-07'),
                     'B':[1,1,'jreback',1,1,5],
                     'C':[0,0,0,0,2,np.nan]})

master
Out[158]: 
           A        B    C
0 2012-02-02        1  0.0
1 2012-02-03        1  0.0
2 2012-02-04  jreback  0.0
3 2012-02-05        1  0.0
4 2012-02-06        1  2.0
5 2012-02-07        5  NaN

something like 
pd.get_dummies(master.B > master.C, mixed_types_eval=False, na_eval=False)

would give a clean dummy

dummy
Out[161]: 
0    1
1    1
2    0
3    1
4    0
5    0
dtype: int64

with perfect control over the (inevitable) string to float comparison and float to null comparison. This is important. For instance, in Stata missing values are evaluated as +infinity. So something like 2> NaN would be False. In Sas, this is the opposite. We need control over this.

**Comment by randomgambit** [comment]
similar logic would of course apply for logical tests based on dates comparisons (useful for time-series regressions)

**Comment by randomgambit** [comment]
actually, it would be even more precise to define the following options

- comparing string to numeric = return NA or zero
- comparing numeric to na = return NA, zero (implicitly assuming NA=infinity) or 1 (implicitly assuming NA=-infinity)

**Comment by randomgambit** [comment]
last: this also applies to string comparison. say master.A=="jreback"

**Comment by TomAugspurger** [comment]
So, ignoring all the dtype issues, your main desire is a

> simple way to generate dummy variables based on a logical test.

I'd say this is done with `(df.B > df.C).astype(int)`, right? Again, assuming all the types are OK.

Bringing back the dtype issues, makes thing tricker from a library perspective, and a bit more difficult for the user.

> - comparing numeric to string= return nan or 0

I think we've been moving towards being stricter about this recently. It's better to put the burden on the user rather than guess at what they want. So that means you'd need.

```python
master['B'] = pd.to_numeric(master['B'], errors='coerce')
In [41]: (master['B'] > master['C']).astype(int)
Out[41]:
0    1
1    1
2    0
3    1
4    0
5    0
dtype: int64
```
to fill the NaNs. Or create a new column if you need to keep the original around.

> - comparing numeric to na = return nan OR zero (implicitly assumingnan=+ infinity) OR 1 (implicitly assuming nan=- infinity)

This goes against python / numpy / IEEE behavior of all numeric : NaN comparisons evaluating false.
If you want the nan to be like `-inf`, then `(master['B'] > master['C']) | pd.isnull(master).any(1)`.

**Comment by jreback** [comment]
of after @TomAugspurger coercion step.
```
In [6]: pd.get_dummies(master.loc[master['B'] > master['C'], 'B'].astype('category'))
Out[6]: 
   1.0
0  1.0
1  1.0
3  1.0
```

@randomgambit pandas is all about building pipelines of simple operations and combining them, rather than trying to do everything with lots of options in a single function (not mentioning R here :)

**Comment by jreback** [comment]
@randomgambit you might want to read [working with text data](http://pandas.pydata.org/pandas-docs/stable/text.html) and [indexing](http://pandas.pydata.org/pandas-docs/stable/indexing.html) where these topics are covered quite a bit.

**Comment by randomgambit** [comment]
fair enough.

I agree with you that my suggestions above may be too 'greedy' from a Pandas philosophical point of view. After all, what is really important here is predictability and control.

My point is that it is somewhat frustrating to have a powerfull dummy variable creation tool such as get_dummies, that can in a single coding line generate legit dummy variables out of columns looking like.

```
Out[6]: 
0  "jreback randomgambit"
1  "tom randomgambit"
3  "jreback"

```

but I have to rely on the two step process `to_numeric` followed by `get_dummies` and `astype`. Consider how many lines I need to write if I create dummies based on multiple columns (which happens, well, every time).

Maybe the simplest solution to my suggestion would be to come up with 

> pd.get_dummiesc(**logical condition involving several columns**, errors='coerce')

which give zeros every time there is an exception.

**Comment by jreback** [comment]
@randomgambit 

the point of pandas is to clean your data, there are tremendous variations. I am not sure I understand why any of this is a problem. A simple pipeline is all that is needed. How do I know that [16] is NOT legititmate? it looks fine to me, but you may disagree, so this requires the user to do something with it. pandas CANNOT just guess at this.

```
In [14]: s = Series(["jreback randomgambit", "tom randomgambit", "jreback"])

In [15]: s
Out[15]: 
0    jreback randomgambit
1        tom randomgambit
2                 jreback
dtype: object

In [16]: 

In [16]: (s.str
   ....:    .extract('(\w+)', expand=False)
   ....:    .pipe(pd.get_dummies)
   ....: )
Out[16]: 
   jreback  tom
0      1.0  0.0
1      0.0  1.0
2      1.0  0.0
```

**Comment by randomgambit** [comment]
hi @jreback thanks for your feedback. I think you may have misunderstood my point. sorry if I was not clear.

all im saying is that it is somehow frustrating to see that get_dummies is able to generate dummies out of complex string columns as you describe, but is unable to get dummies out of basic columns comparisons.

now, i totally agree with you that if we agree to disagree, the choice should be left to the final user. :)

**Comment by jreback** [comment]
@randomgambit oh I get your point. But we are not going to be adding lots of options to a method, where there is already a clear way of doing this. If you have a convincing example pls show it.

**Comment by TomAugspurger** [comment]
@randomgambit thanks.

I think we'll close this one for now, with the understanding that a dedicated method for this kind of comparison isn't a good fit for pandas. Rather, we'd encourage separately handling the dtype issues, the comparisons, and then the `get_dummies` (but I think `.astype(int)` suffices here).

But please do raise issues as you discover more usability concerns. It makes me happy to see others with an economics background using pandas :)

**Comment by randomgambit** [comment]
ok, i gave full hearths to both of you :D
thanks!
