### ISSUE TITLE
read_excel with names keyword argument not working

### ISSUE THREAD

**Issue by swkoh** [pydata/pandas#12870]
With pandas 0.18,  pd.read_excel() with name keyworkd does not work anymore.  (pandas 0.17 works fine.) pandas 0.18 has a change to add names as a keyword argument in excel.py at line 76.

#### Code Sample, a copy-pastable example if possible
filename = 'test.xlsx'
column_names = ['field1', 'field2']
df = pd.read_excel(filename, index_col=None,  names=column_names)

#### Expected Output
column_names associated with keyword argument names is supposed to pass down to kwds at C:\Python27\Lib\site-packages\pandas\io\excel.py:177.

kwds is supposed to carry the arguments from application (in this case, column_names above) but it does not get passed. 

#### output of ``pd.show_versions()``
INSTALLED VERSIONS
------------------
commit: None
python: 2.7.11.final.0
python-bits: 32
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None

pandas: 0.18.0
nose: None
pip: 8.1.1
setuptools: 18.3.2
Cython: 0.23.5
numpy: 1.11.0
scipy: None
statsmodels: None
xarray: None
IPython: 4.0.0
sphinx: None
patsy: None
dateutil: 2.5.2
pytz: 2016.3
blosc: None
bottleneck: None
tables: None
numexpr: 2.5
matplotlib: 1.5.1
openpyxl: 2.2.2
xlrd: 0.9.3
xlwt: 1.0.0
xlsxwriter: 0.7.3
lxml: None
bs4: 4.3.2
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.0.12
pymysql: None
psycopg2: None
jinja2: 2.8
boto: None

**Comment by jreback** [comment]
xref #11874 ; the ``names`` param was documented as it was in the signature but not the doc-string. But it appears to not be passed thru.
```
In [26]: df = DataFrame({'A' : [1,2,3], 'B' : ['foo','bar','baz']})

In [27]: df.to_excel('test.xlsx')

In [28]: pd.read_excel('test.xlsx')
Out[28]: 
   A    B
0  1  foo
1  2  bar
2  3  baz

In [29]: pd.read_excel('test.xlsx',names=['A'])
Out[29]: 
   A    B
0  1  foo
1  2  bar
2  3  baz
```

**Comment by jreback** [comment]
cc @jorisvandenbossche
