### ISSUE TITLE
BUG: resample with empty DatetimeIndex/TimedeltaIndex buggy

### ISSUE THREAD

**Issue by jreback** [pydata/pandas#12886]
xref ``PeriodIndex`` addressed in #12874 

[here](https://github.com/pydata/pandas/commit/2ba977a917ac5c092378a2f172f59d53b14de968) is the reverted commit. Note this should be rolled in the ``test_resample_empty`` test itself

**Comment by MaximilianR** [comment]
@jreback closed by #13079
