### ISSUE TITLE
COMPAT: 0.18.0 scipy dev changes causing interpolation failures

### ISSUE THREAD

**Issue by jmwoloso** [pydata/pandas#12887]
#### Code Sample, a copy-pastable example if possible
python -c 'import pandas;pandas.test()'
#### Expected Output
No errors/failures
#### output of ``pd.show_versions()``
```

INSTALLED VERSIONS
------------------
commit: None
python: 3.4.3.final.0
python-bits: 64
OS: Linux
OS-release: 3.19.0-32-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

pandas: 0.18.0
nose: 1.3.7
pip: 8.1.1
setuptools: 20.7.0
Cython: 0.23.4
numpy: 1.12.0.dev0+47b6c2b
scipy: 0.18.0.dev0+609facc
statsmodels: None
xarray: None
IPython: 4.1.1
sphinx: 1.3.5
patsy: 0.4.0
dateutil: 2.4.2
pytz: 2015.7
blosc: 1.2.8
bottleneck: 1.0.0
tables: None
numexpr: 2.5.2
matplotlib: 1.5.1
openpyxl: 2.3.5
xlrd: 0.9.4
xlwt: 1.0.0
xlsxwriter: 0.7.7
lxml: 3.4.4
bs4: 4.4.1
html5lib: 0.9999999
httplib2: 0.9.2
apiclient: 1.4.2
sqlalchemy: 1.0.9
pymysql: 0.6.7.None
psycopg2: None
jinja2: 2.8
boto: 2.39.0
```

Hello All,

Can anyone provide any insight into these errors and failures (see attachment)
[pandas_test.txt](https://github.com/pydata/pandas/files/216306/pandas_test.txt)

**Comment by jreback** [comment]
pls try with pandas master

though almost all of these are I think some changes in scipy

**Comment by jmwoloso** [comment]
Ok, cool. I'll try that now. Thank you! FYI and for anyone else that might read this, the NumPy and SciPy dev versions that I have installed (see above) _**actually**_ pass all the tests on my Linux box with MKL and the -O3 compiler setting (a first in my experience!). Hence the reason I'm using them. I'll report back in a few about the Master build.

**Comment by jmwoloso** [comment]
Here are the results using the Master build (ouch!) I'll down grade to the -O1 flag for NumPy/SciPy if I need to. Pandas is too critical to my work. Really, SciPy is the only one that gives issues now with the -O3 setting. NumPy always builds fine and Pandas usually does as well. Any further suggestions? I've attached the results. Thanks for your help. I appreciate it.
[pandas_tests.txt](https://github.com/pydata/pandas/files/216426/pandas_tests.txt)

**Comment by jreback** [comment]
I think you are having some compiling issues as you are failing on msgpack/sparse things. We don't have any failures with numpy master (except 1 known ATM). We use scipy latest released. If they have changed things it may have broken something (looks like some changes in interpolation).

Why would you compile & run from unreleased versions? this is very very odd.

**Comment by jreback** [comment]
@TomAugspurger if you'd have a look at the interpolation issues would be great. And maybe see what actually happened.

**Comment by jmwoloso** [comment]
Well, I was experimenting/attempting to get the -O3 flag to work for the MKL. Pandas 0.17.0 plus these versions of NumPy & SciPy worked on my system before.

**Comment by jreback** [comment]
ok I have a branch that tests from scipy master now: https://travis-ci.org/jreback/pandas/jobs/122835131

@jmwoloso if you could look and see what scipy is changing would be great thanks!

**Comment by jreback** [comment]
ok so now the 3.5-dev build has scipy installed [here](https://github.com/pydata/pandas/commit/6f1ade19601ca947a161e0baa7a8cb3c5687f96a)

14 failures from scipy (which is probably all of them). obviously something moved around. So we should push back that this is not compat.

**Comment by jmwoloso** [comment]
@jreback The date of the last SciPy master I cloned was February 11th with the commit for that happening the day before on the 10th. The commit hash was 609facc07ae8437a8480157cc6da500d929eb00c so quite a bit has changed since then. Unfortunately, the last SciPy version I had before that was 0.15.1. Should I track down the last appearance of that in SciPy or should we wait to hear from the SciPy folks regarding the issue you opened (or both)?

**Comment by jreback** [comment]
it appears that function was deprecated a while back - we really don't see the deprecation notices

so need a fix to provide compat with old and new methods

should be straightforward to do

**Comment by TomAugspurger** [comment]
@jmwoloso are you able to submit a PR for this? The methods are [here](https://github.com/pydata/pandas/blob/1c8816f891c693d81b6e2593543eb310e069ff62/pandas/core/missing.py#L81) and some documentation to fix here. Probably need to remove it from the tests as well.

**Comment by ev-br** [comment]
Like I was saying in the scipy issue, `BPoly.from_derivatives` was cooked up specifically as a replacement for the `PiecewisePolynomial`.

``` 
In [39]: x = np.arange(11, dtype=float)

In [40]: y = x**2

In [41]: y = y.reshape(-1, 1)

In [42]: p = PiecewisePolynomial(x, y)

In [43]: xx = (x[1:] + x[:-1]) /2

In [44]: p(xx)
Out[44]: array([  0.5,   2.5,   6.5,  12.5,  20.5,  30.5,  42.5,  56.5,  72.5,  90.5])

In [45]: from scipy.interpolate import BPoly

In [46]: b = BPoly.from<TAB>
BPoly.from_derivatives  BPoly.from_power_basis  

In [46]: b = BPoly.from_derivatives(x, y)

In [47]: b(xx)
Out[47]: array([  0.5,   2.5,   6.5,  12.5,  20.5,  30.5,  42.5,  56.5,  72.5,  90.5])
```

**Comment by jreback** [comment]
thanks @ev-br yes that's what I would do here. detect scipy version and go with old function < 0.18 and new after.

**Comment by jmwoloso** [comment]
@TomAugspurger Sure, I'll give it a shot!

**Comment by jmwoloso** [comment]
@TomAugspurger Quick question, I'm just removing <code>piecewise_polynomial</code> altogether correct? Or am I replacing it with <code>BPoly.from_derivatives</code> (suggested in scipy/scipy#6063 and above by @ev-br) in the list in <code>pandas.core.missing</code> and from the docs in <code>pandas.core.generic</code>?

**Comment by jreback** [comment]
you need to place conditionally depending on the version of scipy

**Comment by TomAugspurger** [comment]
So you'll check the scripy version and raise and error of it's too old. The tests should be similar, skipping if the version is too old.

**Comment by jmwoloso** [comment]
@jreback @TomAugspurger Ok, perfect.

**Comment by jreback** [comment]
no I would simply switch the function for newer versions

for scipy <= 0.17 it should be unchanged

**Comment by jmwoloso** [comment]
@jreback Will do.

**Comment by jreback** [comment]
@jmwoloso if you could do this would be great.

**Comment by jmwoloso** [comment]
Yeah, you can assign it to me if you'd like. I've forked the repo and got everything set up to contribute (this is my first time with any project) and now I'm just trying to get a lay of the land with the code I'll be changing so I understand what is doing what, if that makes sense?

**Comment by jreback** [comment]
@jmwoloso great!. contributing docs are [here](http://pandas.pydata.org/pandas-docs/stable/contributing.html). Just trying to get 0.18.1 done soon.

**Comment by jmwoloso** [comment]
@jreback Awesome. Yeah, I checked out the contributing docs already, they do a great job of explaining how to set everything up to help out. Working on it now, I'll post questions here if I have any.

**Comment by jmwoloso** [comment]
@jreback @TomAugspurger Apologies, I thought your responses to the pull request would show up here as well, but they were just going to my mailing list folder. I'm working on your suggestions now and will push an update once I'm done. Thank you for the feedback thus far!

**Comment by jreback** [comment]
@jmwoloso they show up on whatever issue we were writing them on, in this case the PR itself.
