### ISSUE TITLE
read_html: support "decimal" argument for parsing numbers, like read_csv

### ISSUE THREAD

**Issue by educhana** [pydata/pandas#12907]
read_csv has support for declaring the decimal and thousands separator.

read_html is missing the 'decimal' parameter. it'd be useful and more consistent to accept it too.

Example:
```
pd.read_html(html, thousands='.', decimal=',')
```

**Comment by jreback** [comment]
this is a dupe of #8200 but we'll close that issue. This should be straightforward and just need to pass this thru to the parser. Pull-requests are welcome.

**Comment by sldion** [comment]
I don't think that `TextParser` supports passing the decimal keyword in python. The functionality probably needs to be added to PythonParser
