### ISSUE TITLE
Import statements in period.pyx significantly impact performance

### ISSUE THREAD

**Issue by rs2** [pydata/pandas#12903]
The following imports in pandas/src/period.pyx significantly impact performance when dealing with multiple Period objects. A quick win, guys. 

```cython
    def __init__(self, value=None, freq=None, ordinal=None,
                 year=None, month=1, quarter=None, day=1,
                 hour=0, minute=0, second=0):
        from pandas.tseries import frequencies
        from pandas.tseries.frequencies import get_freq_code as _gfc

        # freq points to a tuple (base, mult);  base is one of the defined
        # periods such as A, Q, etc. Every five minutes would be, e.g.,
        # ('T', 5) but may be passed in as a string like '5T'
```

Just profile the code below and observe the number of times `_find_and_load` gets called:

```python
import pandas as pd

for _ in range(1000):
    pd.Period('2015-04-26')
```

https://github.com/pydata/pandas/commit/bfa80660c67076b0f5457056d1d857fc3204a620 is the commit that has introduced the problem.

I will submit a pull request that rectifies the incorrect fix to the circular dependency.

**Comment by sinhrks** [comment]
Thanks for the catch. Moving some frequency related codes to offset.pyx is one idea (#11214).

**Comment by jreback** [comment]
so this is the same issue behind #11831

**Comment by rs2** [comment]
@jreback Correct. I'll submit a pull request after lunch. Tested the fix
locally and ran unit tests. It's all good.

**Comment by rs2** [comment]
See https://github.com/pydata/pandas/pull/12909
