### ISSUE TITLE
pandas logo has a latex typo

### ISSUE THREAD

**Issue by jseabold** [pydata/pandas#12911]
Someone pointed this out on twitter (sorry, forgot who), but it you should be `y_{it} = ` not `y_it` as it looks like it might be now. The `t` should also be subscript.

**Comment by jreback** [comment]
cc @mdboom

**Comment by mdboom** [comment]
I just put up a gist with the matplotlib script I used to create the (new) logo, with the corrected LaTeX expression:

https://gist.github.com/mdboom/06578d2edbb21807d0e216c8553bdf82

If you have a good suggestion about where in the pandas tree this should live permanently, I can make a PR with this stuff.

**Comment by jreback** [comment]
thanks @mdboom why don't you do a PR with this in ``pandas/doc/logo`` (new dir). If you can put the generated logo there as well. thanks.

**Comment by mdboom** [comment]
Sure: see #12919.
