### ISSUE TITLE
pd.isnull gives different value for pd.Series and np.array

### ISSUE THREAD

**Issue by songhuiming** [pydata/pandas#12942]
#### Code Sample, a copy-pastable example if possible
``
pd.isnull(np.array([np.nan, 1, 2, "s"]))
Out[120]: array([False, False, False, False], dtype=bool)
``

``
pd.isnull(pd.Series([np.nan, 1, 2, "s"]))
Out[116]: 
0     True
1    False
2    False
3    False
``
#### output of ``pd.show_versions()``

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.10.final.0
python-bits: 64
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None

pandas: 0.16.2
nose: 1.3.7
Cython: 0.22.1
numpy: 1.9.2
scipy: 0.15.1
statsmodels: 0.6.1
IPython: 3.2.0
sphinx: 1.3.1
patsy: 0.3.0
dateutil: 2.4.2
pytz: 2015.4
bottleneck: 1.0.0
tables: 3.2.0
numexpr: 2.4.3
matplotlib: 1.4.3
openpyxl: 1.8.5
xlrd: 0.9.3
xlwt: 1.0.0
xlsxwriter: 0.7.3
lxml: 3.4.4
bs4: 4.3.2
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.0.5
pymysql: None
psycopg2: None

**Comment by songhuiming** [comment]
is it becaseu `np.array([np.nan, 1, 2, "s"])` convert `np.nan` to str?

**Comment by jreback** [comment]
exactly. numpy is rather odd to do this, it should simply coerce to ``object``. IIRC there is an issue about this on the numpy issue tracker

```
In [3]: arr = np.array([np.nan, 1, 2, "s"])

# numpy stringifies
In [4]: arr
Out[4]: 
array(['nan', '1', '2', 's'], 
      dtype='|S32')

In [5]: pd.isnull(arr)
Out[5]: array([False, False, False, False], dtype=bool)

In [6]: s = pd.Series([np.nan, 1, 2, "s"])

In [7]: pd.isnull(s)
Out[7]: 
0     True
1    False
2    False
3    False
dtype: bool

# if you truly want to preserver things make your an an object dtype
In [8]: pd.isnull(np.array([np.nan, 1, 2, "s"],dtype='object'))
Out[8]: array([ True, False, False, False], dtype=bool)
```
