### ISSUE TITLE
Feature Request: N-Dimensional DataFrames

### ISSUE THREAD

**Issue by jolespin** [pydata/pandas#12940]
**I want to be able to create `n-dimensional` dataframes.**  I've heard of a method for 3D dataframes using `panels` in `pandas` but, if possible, I would like to extend the dimensions past 3 dims by combining different datasets into a *super dataframe*

I made a random test dataset with arbitrary axis data trying to mimic a real situation; there are 3 axis (i.e. patients, years, and samples).  I tried adding a bunch of dataframes to a list and then making a dataframe with that but it didn't work :(  I even tried a `panel` as in the 2nd link above but I couldn't get it to work either.

**It would be really helpful to have a method to create a N-dimensional pandas dataframe w/ labels**

The first way I tried: 

```
    #Reproducibility
    np.random.seed(1618033)
    
    #Set 3 axis labels/dims
    axis_1 = np.arange(2000,2010) #Years
    axis_2 = np.arange(0,20) #Samples
    axis_3 = np.array(["patient_%d" % i for i in range(0,3)]) #Patients
    
    #Create random 3D array to simulate data from dims above
    A_3D = np.random.random((years.size, samples.size, len(patients))) #(10, 20, 3)
    
    #Create empty list to store 2D dataframes (axis_2=rows, axis_3=columns) along axis_1
    list_of_dataframes=[]
    
    #Iterate through all of the year indices
    for i in range(axis_1.size):
        #Create dataframe of (samples, patients)
        DF_slice = pd.DataFrame(A_3D[i,:,:],index=axis_2,columns=axis_3)
        list_of_dataframes.append(DF_slice)
    #     print(DF_slice) #preview of the 2D dataframes "slice" of the 3D array
    #           patient_0  patient_1  patient_2
    #      0    0.727753   0.154701   0.205916
    #      1    0.796355   0.597207   0.897153
    #      2    0.603955   0.469707   0.580368
    #      3    0.365432   0.852758   0.293725
    #      4    0.906906   0.355509   0.994513
    #      5    0.576911   0.336848   0.265967
    #     ...
    #     19   0.583495   0.400417   0.020099
    
    # DF_3D = pd.DataFrame(list_of_dataframes,index=axis_2, columns=axis_1)
    # Error
    # Shape of passed values is (1, 10), indices imply (10, 20)
```

I could do something like this I guess, but I really like `pandas` and would rather use one of their methods if one exists:

```
    #Set data for query
    query_year = 2007
    query_sample = 15
    query_patient = "patient_1"
    
    #Index based on query
    A_3D[
         (axis_1 == query_year).argmax(),
         (axis_2 == query_sample).argmax(),
         (axis_3 == query_patient).argmax()
    ]
    #0.1231212416981845
```
    

It would be awesome to access the data in this way: 

```
    DF_3D[query_year][query_sample][query_patient]
    #Where DF_3D[query_year] would give a list of 2D arrays (row=sample, col=patient)
    # DF_3D[query_year][query_sample] would give a 1D vector/list of patient data for a particular year, of a particular sample.
    # and DF_3D[query_year][query_sample][query_patient] would be a particular sample of a particular patient of a particular year
```

My apologies if this isn't the right place for feature requests.

**Comment by MaximilianR** [comment]
https://github.com/pydata/xarray
😄

**Comment by jreback** [comment]
as max points out xarray is the new way of doing this

**Comment by jolespin** [comment]
wow that worked perfect for my data . are you guys thinking about merging them or keeping them separate?

**Comment by jreback** [comment]
no its a separate library. doing this allows pandas to have a different impl more conducive and more responsive to table like things.

We recently added a ``.to_xarray()`` method (and they have the converse)

**Comment by jolespin** [comment]
awesome, I'm looking at the docs now. excited to implementing the methods in my data . thanks for responding so quickly .
