### ISSUE TITLE
unexpected result from df = pd.DataFrame({'a': [1, 2]}, index={'two', 'one'})

### ISSUE THREAD

**Issue by ayanamirei00** [pydata/pandas#12954]
#### Code Sample, a copy-pastable example if possible
df = pd.DataFrame({'a': [1, 2]}, index={'two', 'one'})
df

df = pd.DataFrame({'a': [1, 2]}, index={'one', 'two'})
df

got the same result :    
        a
two  1
one  2

#### Expected Output
    a
two  1
one  2

    a
one  1
two  2
#### output of ``pd.show_versions()``
INSTALLED VERSIONS
------------------
commit: None
python: 2.7.10.final.0
python-bits: 32
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None

pandas: 0.18.0
nose: 1.3.7
pip: 8.1.1
setuptools: 16.0
Cython: None
numpy: 1.11.0
scipy: 0.16.1
statsmodels: None
xarray: None
IPython: 4.1.2
sphinx: None
patsy: None
dateutil: 2.5.2
pytz: 2016.3
blosc: None
bottleneck: None
tables: None
numexpr: None
matplotlib: 1.5.1
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.8
boto: None

**Comment by ayanamirei00** [comment]
df = pd.DataFrame({'a': [1, 2,3,4]}, index={'a', 'b','c','d'})
df
the index seems to be random, would expect the order when they are specified in "index"
   a
a  1
c  2
b  3
d  4

**Comment by MaximilianR** [comment]
Are you sure?

```python
In [5]: df = pd.DataFrame({'a': [1, 2]}, index={'two', 'one'})

In [6]: df
Out[6]: 
     a
two  1
one  2

In [7]: 

In [7]: df = pd.DataFrame({'a': [1, 2]}, index={'one', 'two'})

In [8]: df
Out[8]: 
     a
one  1
two  2
```

**Comment by MaximilianR** [comment]
You're supplying a set for the index, which is unordered. You need to supply a list
