### ISSUE TITLE
How to change all the specified values to another value?

### ISSUE THREAD

**Issue by ayanamirei00** [pydata/pandas#12955]
#### Code Sample, a copy-pastable example if possible

import numpy as np
import pandas as pd
df = pd.DataFrame(np.arange(0, 15).reshape(5, 3), 
               index=['a', 'b', 'c', 'd', 'e'], 
               columns=['c1', 'c2', 'c3'])

How to change all the places where c1==0 to c1=5 for example? (In this example only the [a][c1] is changed, but could be multiple places if there are more 0 in the c1 column.)
Thinking of something like df[df.c1==0].c1=5. 
(This is similar to fill na with a pecified value)

**Comment by sinhrks** [comment]
Use ``df.loc[df.c1==0, "c1"] = 5``.

**Comment by sinhrks** [comment]
Also, pls use stackoverflow for usage question.
