### ISSUE TITLE
ImportError on RangeIndex

### ISSUE THREAD

**Issue by jslovan** [pydata/pandas#12957]
- In system env, I am not able to import pandas after updating to 0.18.0.  Installed/updated by conda on Win 8.1.   
- running
 1. ```conda remove pandas```
 2. ```conda install pandas```

 does not help
- after installing into fresh new virtual env, import works.

Probably it is bad state of the environment, could you please advise me how to fix it?

#### ImportError on importing
```bash
C:\WINDOWS\system32>python
Python 2.7.11 |Anaconda 2.3.0 (64-bit)| (default, Feb 16 2016, 09:58:36) [MSC v.
1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import pandas
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Anaconda\lib\site-packages\pandas\__init__.py", line 44
, in <module>
    from pandas.core.api import *
  File "C:\Program Files\Anaconda\lib\site-packages\pandas\core\api.py", line 10
, in <module>
    from pandas.core.groupby import Grouper
  File "C:\Program Files\Anaconda\lib\site-packages\pandas\core\groupby.py", lin
e 18, in <module>
    from pandas.core.frame import DataFrame
  File "C:\Program Files\Anaconda\lib\site-packages\pandas\core\frame.py", line
5230, in <module>
    _EMPTY_SERIES = Series([])
  File "C:\Program Files\Anaconda\lib\site-packages\pandas\core\series.py", line
 216, in __init__
    index = _default_index(len(data))
  File "C:\Program Files\Anaconda\lib\site-packages\pandas\core\common.py", line
 1867, in _default_index
    from pandas.core.index import RangeIndex
ImportError: cannot import name RangeIndex
```

#### conda information
C:\WINDOWS\system32>conda list pandas
\# packages in environment at C:\Program Files\Anaconda:
\#
pandas                    0.18.0              np110py27_0

#### output of ``pd.show_versions()``
Not available.

**Comment by jslovan** [comment]
OK,
- ```conda remove pandas```
- go and manually remove Lib/site-packages/pandas
- ```conda install pandas```

Everything works.

**Comment by jreback** [comment]
how did you install in the first place?

**Comment by jslovan** [comment]
Years ago, by Anaconda.

But while updating, I had a Jupyter notebook running.
The installation finished all OK, but (probably) some files stayed not updated.
The same then held for removing and installing again. Only when system did not allow me to remove the directory I realized there was a python running.

**Comment by jreback** [comment]
ahh older versions of conda would fail on Windows if another process was open with that package 

So you can do a: conda update conda to prevent this in the future

**Comment by jslovan** [comment]
Thanks.
