### ISSUE TITLE
plot.bar misalignment when width=1

### ISSUE THREAD

**Issue by kdebrab** [pydata/pandas#12979]
Two minor issues with the width optional argument of plot.bar() in Pandas 0.18.0:

1) Using width=1 (integer) causes misalignment of the x-axis
```python
import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.random((6, 5)) * 10, index=list('abcdef'), columns=list('ABCDE'))
df.plot.bar(stacked=True, width=1)
```
![figure_1](https://cloud.githubusercontent.com/assets/1150402/14782442/ade46c52-0ae9-11e6-9b90-729d413861d1.png)

Compare this with the correct behaviour when defining width as a float:
```python
df.plot.bar(stacked=True, width=1.)
```
![figure_2](https://cloud.githubusercontent.com/assets/1150402/14782452/b29a70fc-0ae9-11e6-9b72-031fccc5714f.png)

2) Using width=None causes a TypeError, where I would expect the default behaviour.

**Comment by TomAugspurger** [comment]
For the first one, I don't see a problem:

![gh](https://cloud.githubusercontent.com/assets/1312546/14783086/05828a3e-0ab3-11e6-89c1-08dd73e72b83.png)

Could you post the output of `pd.show_versions()` along with your OS information?

For the default, it's 0.5 but we haven't finished documenting all the keyword arguments after the `.plot` namespace was added in 0.17.

**Comment by kdebrab** [comment]
As requested, output of pd.show_versions():

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.10.final.0
python-bits: 32
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 42 Stepping 7, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None

pandas: 0.18.0
nose: 1.3.7
pip: 8.1.1
setuptools: 20.3.1
Cython: 0.20
numpy: 1.10.4
scipy: 0.16.0b2
statsmodels: 0.6.1
xarray: None
IPython: 4.1.2
sphinx: 1.3.6
patsy: 0.3.0
dateutil: 2.5.1
pytz: 2016.2
blosc: None
bottleneck: 0.8.0
tables: None
numexpr: None
matplotlib: 1.5.1
openpyxl: 1.6.2
xlrd: 0.9.2
xlwt: 0.7.5
xlsxwriter: None
lxml: None
bs4: 4.3.2
html5lib: 0.999999
httplib2: 0.9.1
apiclient: None
sqlalchemy: 0.7.9
pymysql: None
psycopg2: None
jinja2: 2.8
boto: None

Seeing the style of your figure, I'd guess you're using matplotlib 2.x (development)? Thus, it seems the first issue originates in matplotlib and is fixed in the development version of matplotlib, but not in the latest stable matplotlib version 1.5.1?

With regard to the second issue, I knew the default is 0.5. It is just a matter of usability/consistency. Most optional arguments use the default value (i.c. 0.5) when one explicitly sets them to None. Apparently this isn't the case for the 'width' argument. Not very important of course, but I just thought of mentioning this.

The fix/workaround is rather trivial. Adding the line `width = float(width or 0.5)` fixes both issues for me.

**Comment by sinhrks** [comment]
As you use python2, looks to be caused by somewhere uses division by integer. PR is appreciated:)

- https://github.com/pydata/pandas/blob/master/pandas/tools/plotting.py#L1874
