### ISSUE TITLE
ENH: classmethods for pd.period_range & pd.date_range

### ISSUE THREAD

**Issue by MaximilianR** [pydata/pandas#12984]
Floating an idea: `pd.PeriodIndex.from_range` & `pd.DatetimeIndex.from_range` as `classmethod`s to mirror `pd.period_range` & `pd.date_range` respectively. This encapsulates constructors on the class.

Also could have `pd.DatetimeIndex.from_dataframe` for https://github.com/pydata/pandas/pull/12967

**Comment by jreback** [comment]
@MaximilianR why? that's seems like more typing to me.

**Comment by MaximilianR** [comment]
> why? that's seems like more typing to me.

For the encapsulation - i.e. the ways of creating an instance are all listed on the class. It's also a nice pythonic approach. 

While I wouldn't think removing the existing methods would be worth the effort (and maybe that makes adding these new ones a non-starter), the approach of putting constructors on classes in future also helps to keep the `pd.` namespace cleaner

**Comment by jreback** [comment]
you realize that these are convenience functions that just call the constructor now (albeit with a default for the freq) Not sure why adding something is helpful here. It would just be another name.

**Comment by MaximilianR** [comment]
I didn't realize they were such a thin wrapper. Closing for now.
