### ISSUE TITLE
reset_index() not working properly when DataFrame columns are MultiIndex

### ISSUE THREAD

**Issue by Qu-Bit** [pydata/pandas#12990]
## sample input file
[ml_col_idx_read.xlsx](https://github.com/pydata/pandas/files/236380/ml_col_idx_read.xlsx)

## Code Sample 1
```
ddf = pd.read_excel('ml_col_idx_read.xlsx', header=(0,1))
ddf.info()
ddf.reset_index()
```
## Output 1
```
<class 'pandas.core.frame.DataFrame'>
Int64Index: 4 entries, 1 to 4
Data columns (total 2 columns):
(A2, bar)    4 non-null object
(A3, baz)    4 non-null int64
dtypes: int64(1), object(1)
memory usage: 96.0+ bytes
```
```
A1  index   A2  A3
foo        bar baz
0       1  yes  15
1       2   no  10
2       3   no   4
3       4  yes   1
```
### expected output:
```
      A1    A2  A3
      foo   bar baz
0       1  yes  15
1       2   no  10
2       3   no   4
3       4  yes   1
```

## Code Sample 2
*  ``index_col=None`` should be default anyways...
```
# ddf = pd.read_excel('ml_col_idx_read.xlsx', header=(0,1),)
# OR
ddf = pd.read_excel('ml_col_idx_read.xlsx', header=(0,1), index_col=None)
ddf.info()
pint(ddf)
```
## Output 2
* **non-respected default** behavior, **non-respected explicit** behavior
* column 0 is still used for index
```
<class 'pandas.core.frame.DataFrame'>
Int64Index: 4 entries, 1 to 4
Data columns (total 2 columns):
(A2, bar)    4 non-null object
(A3, baz)    4 non-null int64
dtypes: int64(1), object(1)
memory usage: 96.0+ bytes
```
```
A1    A2  A3
foo  bar baz
1    yes  15
2     no  10
3     no   4
4    yes   1
```
### expected output:
```
      A1    A2  A3
      foo   bar baz
0       1  yes  15
1       2   no  10
2       3   no   4
3       4  yes   1
```

##  ``pd.show_versions()``
INSTALLED VERSIONS
------------------
commit: None
python: 3.4.3.final.0
python-bits: 64
OS: Linux
OS-release: 3.13.0-43-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: de_AT.UTF-8

pandas: 0.18.0+git114-g6c692ae
nose: 1.3.6
pip: None
setuptools: 18.4
Cython: 0.23.3
numpy: 1.8.2
scipy: 0.14.1
statsmodels: None
xarray: None
IPython: 2.3.0
sphinx: None
patsy: 0.4.1
dateutil: 2.2
pytz: 2014.10
blosc: None
bottleneck: None
tables: 3.2.2
numexpr: 2.4.3
matplotlib: 1.4.2
openpyxl: None
xlrd: 0.9.4
xlwt: None
xlsxwriter: 0.7.3
lxml: None
bs4: 4.3.2
html5lib: 0.999
httplib2: 0.9
apiclient: None
sqlalchemy: 1.0.8
pymysql: None
psycopg2: None
jinja2: 2.8
boto: None
pandas_datareader: None

**Comment by jreback** [comment]
this is correct, you are resetting the ``index`` which is an ``Int64Index``, not a ``MultiIndex``.

**Comment by jreback** [comment]
you might be confused by the names which are on the columns.

```
In [11]: ddf.columns
Out[11]: 
MultiIndex(levels=[[u'A2', u'A3'], [u'bar', u'baz']],
           labels=[[0, 1], [0, 1]],
           names=[u'A1', u'foo'])
```
