### ISSUE TITLE
equals method of dataframe doesn't return the same as (df1 == df2).all().all()

### ISSUE THREAD

**Issue by d-chambers** [pydata/pandas#13023]
I have created two dataframes with earthquake data that I am trying to compare. The elements in the dataframes should be equal. The files are attached below.

[broken_df.zip](https://github.com/pydata/pandas/files/241604/broken_df.zip)

#### Code Sample, a copy-pastable example if possible
```python
import pandas as pd
df1 = pd.read_pickle('d1.pkl') # these files are attached in the .zip
df2 = pd.read_pickle('d2.pkl') 
df1.equals(df2) # returns False
(df1 == df2).all().all() # returns True
```
However, If I save the dataframes as csv files (also attached), load them and rerun the same code it returns True for both checks as expected.  

#### Expected Output
```Python
True
True
```
#### output of ``pd.show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.11.final.0
python-bits: 64
OS: Linux
OS-release: 3.13.0-85-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

pandas: 0.17.1
nose: 1.3.7
pip: 8.1.0
setuptools: 20.7.0
Cython: 0.23.4
numpy: 1.10.4
scipy: 0.17.0
statsmodels: None
IPython: 4.0.3
sphinx: 1.3.5
patsy: 0.4.0
dateutil: 2.4.2
pytz: 2015.7
blosc: None
bottleneck: 1.0.0
tables: 3.2.2
numexpr: 2.4.6
matplotlib: 1.5.1
openpyxl: 2.3.2
xlrd: 0.9.4
xlwt: 1.0.0
xlsxwriter: 0.8.4
lxml: 3.5.0
bs4: 4.4.1
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.0.11
pymysql: None
psycopg2: None
Jinja2: None

**Comment by d-chambers** [comment]
Doing more research this might be a data type issue. I found [this SO post](http://stackoverflow.com/questions/26552116/contract-of-pandas-dataframe-equals) on a similar issue.

**Comment by jreback** [comment]
So these have different dtypes, so they are not equal. ``==`` *may* work, but if things are typed as ``object`` this will be completely non-performant. (and ``==`` will not work for things that sometimes 'look' equal but are not actually, e.g. a float and integer will compare equal but are not the same).
```
In [5]: df1.dtypes
Out[5]: 
year               int64
month              int64
day                int64
hour               int64
minute             int64
sec              float64
latd               int64
latc              object
lond               int64
lonc              object
ampmag           float64
numphases          int64
azgap              int64
stadist            int64
rms              float64
peazimuth          int64
pedip              int64
perror           float64
ieazimuth          int64
```
```
In [6]: df2.dtypes
Out[6]: 
year             object
month            object
day              object
hour             object
minute           object
sec              object
latd             object
latc             object
lond             object
lonc             object
ampmag           object
numphases        object
azgap            object
stadist          object
rms              object
peazimuth        object
pedip            object
```
