### ISSUE TITLE
Feature request: pandas.DataFrame.to_sas

### ISSUE THREAD

**Issue by mhooreman** [pydata/pandas#13031]
Hello,

I find very usefull `pandas.read_sas` but, as I'm collaborating a lot with SAS users, I'm wondering if there are some plans to implement `pandas.DataFrame.to_sas`?

Up to now, the only possibility I see is to pass through common file formats like `pandas.DataFrame.to_csv`.

Thanks a lot for your help.

Best regards.

P.S.: Sorry to push that as an issue, but I don't find how to suggest new features.

**Comment by jreback** [comment]
see #4052 

cc @kshedden 

AFAIK this is not possible. ``read_sas`` was reverse engineered, but writing out a valid sas file is not easy at all. I suppose its possible, but testing is not easy/possible. Further we generally don't want to write to a proprietary format.
