### ISSUE TITLE
API: sparse.cumsum should default to stats axis

### ISSUE THREAD

**Issue by jreback** [pydata/pandas#13048]
xref #12810 

```
In [1]: sp = pd.SparseDataFrame([1, 2, 3])

In [2]: np.cumsum(sp)
ValueError: No axis named None for object type <class 'pandas.sparse.frame.SparseDataFrame'>

In [3]: np.cumsum(sp, axis=0)
Out[3]: 
     0
0  1.0
1  3.0
2  6.0

In [4]: np.cumsum(sp, axis=1)
Out[4]: 
     0
0  1.0
1  2.0
2  3.0
```

**Comment by jreback** [comment]
cc @gfyoung merging #12810

but I think this should default. Need to systematically check all of the cum functions.
(axis = 0). dense already does this. (yes the ``axis`` is passed as ``None`` but its set if its ``None``.

cc @sinhrks

**Comment by jreback** [comment]
e.g. [6] works

```
In [4]: np.cumsum(sp, axis=0)
Out[4]: 
     0
0  1.0
1  3.0
2  6.0

In [5]: np.cumsum(sp.to_dense(), axis=0)
Out[5]: 
     0
0  1.0
1  3.0
2  6.0

In [6]: np.cumsum(sp.to_dense())
Out[6]: 
     0
0  1.0
1  3.0
2  6.0
```

**Comment by gfyoung** [comment]
@jreback : I'm not sure I fully understand.  How do you want to handle the case when `axis=None` (when you say "stats" axis)?

**Comment by jreback** [comment]
see the dense impl

it needs to be 0 (which is the stats axis)

**Comment by gfyoung** [comment]
Ah, I see.  Just a simple:
~~~python
if axis is None:
   axis = self._stat_axis_number
~~~

**Comment by jreback** [comment]
yep but merging soon
do after and need tests

**Comment by gfyoung** [comment]
Yes, indeed, certainly!
