### ISSUE TITLE
pip/PyPI not updated with 0.18.1

### ISSUE THREAD

**Issue by MattDMo** [pydata/pandas#13085]
I was on PyPI just now, and the [only versions](https://pypi.python.org/pypi/pandas) of pandas available are 0.17.1 and 0.18.0. Trying https://pypi.python.org/pypi/pandas/0.18.1 leads to a 404 page. I tried installing via `pip`, and it can't find 0.18.1 either. Is there an issue communicating with PyPI, or is something else going on?

**Comment by jreback** [comment]
I haven't quite released it yet

**Comment by jreback** [comment]
just updated PyPi. enjoy!
