### ISSUE TITLE
REGRP: Series.quantile returns NaN

### ISSUE THREAD

**Issue by gieseke** [pydata/pandas#13098]
#### Code Sample, a copy-pastable example if possible
```python
import pandas as pd
import numpy
s = pd.Series([1, 2, 3, 4, numpy.nan])
s.quantile(0.5)
nan
```

#### Expected Output
I would expect 2.5 as output (as with version 0.17.1).

#### output of ``pd.show_versions()``

commit: None
python: 2.7.6.final.0
python-bits: 64
OS: Linux
OS-release: 3.13.0-85-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: de_DE.UTF-8

pandas: 0.18.1
nose: None
pip: 1.5.4
setuptools: 2.2
Cython: None
numpy: 1.11.0
scipy: 0.16.1
statsmodels: None
xarray: None
IPython: None
sphinx: None
patsy: None
dateutil: 2.5.3
pytz: 2016.4
blosc: None
bottleneck: None
tables: None
numexpr: None
matplotlib: 1.5.1
openpyxl: 2.3.2
xlrd: 0.9.4
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: None
boto: None
pandas_datareader: None

**Comment by jreback** [comment]
Hmm, this did break somewhere.
```
In [1]: s = pd.Series([1, 2, 3, 4, numpy.nan])

In [2]: s.quantile(0.5)
Out[2]: 2.5

In [3]: pd.__version__
Out[3]: u'0.18.0'
```

**Comment by jreback** [comment]
xref #12772
