### ISSUE TITLE
BUG/API: Index.equals should check input class?

### ISSUE THREAD

**Issue by sinhrks** [pydata/pandas#13107]
#### Code Sample, a copy-pastable example if possible

Decide the behavior if non ``Index`` with same values is passed. Currently, there is incompatibility between dtypes. 

```
pd.Index([1], dtype=object).equals(pd.Series([1], dtype=object))
# False

pd.Index([1]).equals(pd.Series([1]))
# True
```

#### output of ``pd.show_versions()``

on current master

**Comment by jreback** [comment]
these have to be dtype compat as well as values

right so the top should work

**Comment by sinhrks** [comment]
@jreback OK, always return ``False`` if input is not ``Index``.  Regarding ``dtype``, there are some tests which allows the difference.

- https://github.com/pydata/pandas/blob/master/pandas/tests/indexes/test_numeric.py#L523

You mean following must be ``False``?

```
pd.Index([1, 2]).equals(pd.Index([1., 2.]))
# True
```

**Comment by jreback** [comment]
no what I mean is another ``Index`` is ok, but NOT a ``Series``.
