### ISSUE TITLE
pandas.DataFrame.to_json() date in MongoDB Extended JSON format

### ISSUE THREAD

**Issue by mbourqui** [pydata/pandas#13126]
#### Additional option for the `date_format` parameter
'isomongo'

#### Expected Output
{ "$date": "YYYY-MM-DDTHH:mm:ss.mmm<+/-Offset>" }
See https://docs.mongodb.com/manual/reference/mongodb-extended-json/#date

**Comment by jreback** [comment]
```
In [2]: DataFrame({'A' : pd.date_range('20130101',periods=3)}).to_json(date_format='iso')
Out[2]: '{"A":{"0":"2013-01-01T00:00:00.000Z","1":"2013-01-02T00:00:00.000Z","2":"2013-01-03T00:00:00.000Z"}}'
```

**Comment by jreback** [comment]
docs are [here](http://pandas.pydata.org/pandas-docs/stable/io.html#id1)

**Comment by mbourqui** [comment]
The output from the docs is not what I am looking for. I'd like to have the `$date` keyword included.

**Comment by jreback** [comment]
and how would you propose to create this? what is the source data. pls provide an example. This kind of specific tagging is very back-end specific.

**Comment by mbourqui** [comment]
I checked pandas' source code, it does not look feasible. This would require to change the python.json.dumps() function first.
