### ISSUE TITLE
df.query bug giving RuntimeWarning: divide by zero encountered in log10 in align.py", line 98, in _align_core     ordm = np.log10(abs(reindexer_size - term_axis_size)) 

### ISSUE THREAD

**Issue by aliabbasjp** [pydata/pandas#13135]
Getting the following bug:

RuntimeWarning: divide by zero encountered in log10
C:\Users\Nick\Anaconda3\lib\site-packages\pandas\computation\align.py:98: 
  ordm = np.log10(abs(reindexer_size - term_axis_size))
while running query().

dtypes:

CGI            int64
SITEID         int32
LONGITUDE    float64
LATITUDE     float32
dtype: object
Query:

towerData = towerData.query('CGI != 0')

once you get this runtime warning it just halts everything  and you have to restart the program.

This bug happens only in multithreaded calls to query function. I am using the concurrent.futures module for the same.

runs fine for non threaded application

**Comment by sinhrks** [comment]
Thanks for the report. Do you have minimal copy-pastable example?

**Comment by rkern** [comment]
Note: I'll be avoiding that warning explicitly in my fix for #13109. The numpy error state is thread-local IIRC, so the current fire-and-forget `np.seterr(all='ignore')` probably only takes effect in the main thread. Why the OP's program halts after the warning, I don't know.

**Comment by grove80904** [comment]
I'm having a similar issue even without threading.  See example code below.

`
import pandas as pd
import numpy as np
df = pd.DataFrame.from_items([('A', [1, 2, 3, 4, 5]), 
                              ('B', [14, 15, 16, 17, 18]), 
                              ('C', list(np.random.randn(5)))])
df.set_index(['A', 'B'], inplace = True)
df.query('15 <= B <= 17')

C:\Anaconda3\lib\site-packages\pandas\computation\align.py:98: 
RuntimeWarning: divide by zero encountered in log10
ordm = np.log10(abs(reindexer_size - term_axis_size))
Out[1]: 
             C
A B 
2 15 -0.852411
3 16 -0.665470
4 17  0.132162
`
