### ISSUE TITLE
pd.tslib._Timestamp should not be capable of crashing python.exe

### ISSUE THREAD

**Issue by rs2** [pydata/pandas#13155]
#### Code Sample, a copy-pastable example if possible

```python
python -c "import pandas as pd; print(pd.__version__); pd.tslib._Timestamp(42, 7, 13)"
```

Crashes python.exe on Windows 7, 10. Tested with  Python 3.3, 3.4, 3.5, pandas 0.16.2,  0.17.1, 0.18.0. ipython.exe crashes on exit when this code is executed.

#### Expected Output

Raise a suitable exception instead.

**Comment by jorisvandenbossche** [comment]
It should maybe not crash, but is there a reason you are using a private class?

**Comment by jreback** [comment]
this is not a public API and needs special construction inside the public class

**Comment by rs2** [comment]
Let me find an example of public API crashing python.exe. The above was the easiest way to point out that you may not always get an exception.

**Comment by jreback** [comment]
generally when you mess with cython things its pretty easy to crash python. If you find something in the public API that segfaults, pls reopen / new issue.
