### ISSUE TITLE
x_compat has no effect

### ISSUE THREAD

**Issue by methodds** [pydata/pandas#13182]
When trying to use x_compat on an x-axis with string indicators the use of x_compat has no effect. What I would like is the plot to show every x-value and twist the angle, like in the corresponding [visualization example](http://pandas.pydata.org/pandas-docs/stable/visualization.html#suppressing-tick-resolution-adjustment).

#### Code Sample

`````
posts.plot(figsize=(8,6), fontsize=10, x_compat = True);
``````

#### Output
![x_compat](https://cloud.githubusercontent.com/assets/7460499/15272687/952dc4c2-1a81-11e6-95a7-8160c1443c3f.png)

#### ``pd.show_versions()``

------------------
commit: None
python: 3.5.1.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None

pandas: 0.18.1
nose: 1.3.7
pip: 8.1.1
setuptools: 20.7.0
Cython: 0.24
numpy: 1.10.4
scipy: 0.17.1
statsmodels: None
xarray: None
IPython: 4.2.0
sphinx: 1.3.1
patsy: 0.4.1
dateutil: 2.5.3
pytz: 2016.4
blosc: None
bottleneck: 1.0.0
tables: 3.2.2
numexpr: 2.5.2
matplotlib: 1.5.1
openpyxl: 2.3.2
xlrd: 0.9.4
xlwt: 1.0.0
xlsxwriter: 0.8.6
lxml: 3.6.0
bs4: 4.4.1
html5lib: 0.9999999
httplib2: None
apiclient: None
sqlalchemy: 1.0.12
pymysql: None
psycopg2: None
jinja2: 2.8
boto: 2.40.0
pandas_datareader: None

**Comment by TomAugspurger** [comment]
`x_compat` only has an effect with a DatetimeIndex. You should be able to use the `rot` parameter.

```python
posts.plot(figsize=(8,6), fontsize=10, rot=45);
```

**Comment by jreback** [comment]
should we raise / warn of this is passed when not a DTI?

**Comment by methodds** [comment]
thank your for the hint to use ```rot```. Is there a similar parameter which prevents pandas from only showing every second label on the x-axis?

**Comment by TomAugspurger** [comment]
@jreback I thought we had an issue about stricter keyword arg handling as part of the followup to the `.plot` namespace change, but haven't been able to find it. I'll keep looking.

@methodds to get any features like that you would need to use a real datetimeindex, `posts.index = pd.to_datetime(posts.index)`. IIRC, pandas doesn't have any controls over the precision, it's setup for dynamically choosing good values. The [matplotlib.dates](http://matplotlib.org/api/dates_api.html#module-matplotlib.dates) let's you control all that.
