### ISSUE TITLE
ValueError: invalid literal for float(): 25:13:15

### ISSUE THREAD

**Issue by kennetham** [pydata/pandas#13211]
Hi, I am running my own dataset with scikit-learn. My dataset contains '2016/02/28', '20:12:22', '100' and 'string', Date, time, integer and string.

I have successfully parsed the data with Pandas and have reached CLF using SVM to test out.
However, upon clf.fit(X, y), an error was returned ValueError: invalid literal for float(): 25:13:15, apparently in my dataset, there is a time of 25:13:15 which reflect 02:13:15am.

Am I able to convert datetime into float or numeric array?

Please advise how should I go about fixing this issue.

Thank you.

**Comment by jreback** [comment]
pls show a copy pastable example and pd.show_versions()

**Comment by kennetham** [comment]
_Arrival time_ and _Departure time_ contains a time value `23:12:15` with the exception that this raw data also contains up to `24:12:14` and `25:13:14` time range, which technically isn't parsable by Pandas am I right?

I tried finding resource on stackoverflow but failed to find one that fits my case. Please advise.

```python
dataset = pd.read_csv("out2.csv", header=0)
X_train = dataset[['Capacity', 'Station', 'Arrival time', 'Departure time', 'Delay seconds']]
Y_train = dataset.drop(['Capacity', 'Station', 'Arrival time', 'Departure time', 'Delay seconds'], axis=1)
```

```log
INSTALLED VERSIONS
------------------
commit: None
python: 2.7.10.final.0
python-bits: 32
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None

pandas: 0.18.1
nose: 1.3.7
pip: 8.1.2
setuptools: 21.0.0
Cython: 0.24
numpy: 1.11.0
scipy: 0.15.1
statsmodels: 0.6.1
xarray: None
IPython: 4.2.0
sphinx: 1.4.1
patsy: 0.4.1
dateutil: 2.5.3
pytz: 2016.4
blosc: 1.3.2
bottleneck: 1.0.0
tables: 3.2.0
numexpr: 2.5.2
matplotlib: 1.5.1
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: 4.4.1
html5lib: 0.9999999
httplib2: None
apiclient: None
sqlalchemy: 1.0.12
pymysql: None
psycopg2: None
jinja2: 2.8
boto: None
pandas_datareader: None
None
```

**Comment by jreback** [comment]
copy pastable pls - meaning I can simply copy the code and it will work as for you

**Comment by kennetham** [comment]
Yup this is the exact code I am testing at the moment.

_test.py_
```python
from sklearn import svm
import pandas as pd

dataset = pd.read_csv("out2.csv", header=0)
X_train = dataset[['Capacity', 'Station', 'Arrival time', 'Departure time', 'Delay seconds']]
Y_train = dataset.drop(['Capacity', 'Station', 'Arrival time', 'Departure time', 'Delay seconds'], axis=1)

clf = svm.SVC(gamma=0.001, C=100.)
print clf
print clf.fit(X_train, Y_train)
```

_out2.csv_
```csv
100,Jurong,03:40:17,03:41:15,0
100,Jurong,14:50:45,14:51:17,0
100,Jurong,22:55:16,22:56:16,0
100,Jurong,24:12:43,24:13:15,0
100,Jurong,25:12:43,25:13:15,0
```

**Comment by jreback** [comment]
well this is not your example, because it doesn't even have a header. In any event you need to parse dates/timedeltas.

```
In [16]: dataset
Out[16]: 
     0       1         2         3  4
0  100  Jurong  03:40:17  03:41:15  0
1  100  Jurong  14:50:45  14:51:17  0
2  100  Jurong  22:55:16  22:56:16  0
3  100  Jurong  24:12:43  24:13:15  0
4  100  Jurong  25:12:43  25:13:15  0

In [17]: pd.to_timedelta(dataset[2],errors='coerce')
Out[17]: 
0   0 days 03:40:17
1   0 days 14:50:45
2   0 days 22:55:16
3   1 days 00:12:43
4   1 days 01:12:43
Name: 2, dtype: timedelta64[ns]

```

or
```
In [18]: pd.to_datetime(dataset[2],errors='coerce')
Out[18]: 
0   2016-05-18 03:40:17
1   2016-05-18 14:50:45
2   2016-05-18 22:55:16
3                   NaT
4                   NaT
Name: 2, dtype: datetime64[ns]
```

**Comment by TomAugspurger** [comment]
@kennetham your problem isn't directly related to pandas. Your input in `svm.SVC` has to be a numpy array with a *single* dtype. The `X_train` dataset has a mix of ints and objects (strings).

 I would suggest doing the conversion yourself, rather than relying on scikit-learn to try to do it.

You have two types that need to be converted

- "Station" should probably be dummy-encoded with http://pandas.pydata.org/pandas-docs/stable/generated/pandas.get_dummies.html or scikit-learn OneHotEncoder
- "Arrival time" and "Departure time": it's up to you how to represent this. I would convert them to seconds since midnight probably. Maybe search or ask on stackoverflow about the best way to do that.

**Comment by kennetham** [comment]
Sorry I left out the header, due to confidentiality of the dataset, I couldn't send the full dataset.
@TomAugspurger I get you, i realized the I had to sanitize the data further, I was wondering if pandas could do that for me.

Thank you

**Comment by jreback** [comment]
I think the examples speak for themselves

pandas certainly. can sanitize data but you have to give it some hints

**Comment by kennetham** [comment]
Right. I'll dive deeper, thank you @jreback!
