### ISSUE TITLE
Pandas incorrectly parses maturity code for yahoo options

### ISSUE THREAD

**Issue by yigu-2000** [pydata/pandas#13245]
Pandas's option.get_all_data incorrectly parses the maturity dates for all options, so 2017 options from Yahoo will be parsed to 2020 option. This is because a problem logic  to use to_datetime() to convert the date string.  A simple and practical fix is to append "20" in front of the string before calling to_datetime().  Line to fix is in data.py's _process_data function.  - Yi Gu 2016
#frame["Expiry"] = to_datetime("20"+frame.Rootexp.str[-6:])

# sample code to produce the error
from pandas.io.data import Options
myopt = Options("GS", "yahoo")
data = myopt.get_all_data()
print data.ix[0].name

#### Expected Output
(310.0, Timestamp('2020-01-17 00:00:00'), 'put', u'GS170120P00310000')
After the code correction, the correct output should be
(310.0, Timestamp('2017-01-20 00:00:00'), 'put', u'GS170120P00310000')

#### output of ``pd.show_versions()``
INSTALLED VERSIONS
------------------
commit: None
python: 2.7.11.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: AMD64 Family 22 Model 48 Stepping 1, AuthenticAMD
byteorder: little
LC_ALL: None
LANG: None

pandas: 0.18.0
nose: 1.3.7
pip: 8.1.1
setuptools: 20.7.0
Cython: 0.23.4
numpy: 1.10.4
scipy: 0.16.0
statsmodels: 0.6.1
xarray: None
IPython: 4.0.1
sphinx: 1.3.1
patsy: 0.4.0
dateutil: 2.5.2
pytz: 2016.3
blosc: None
bottleneck: 1.0.0
tables: 3.2.2
numexpr: 2.4.4
matplotlib: 1.5.0
openpyxl: 2.2.6
xlrd: 0.9.4
xlwt: 1.0.0
xlsxwriter: 0.7.7
lxml: 3.4.4
bs4: 4.4.1
html5lib: 0.9999999
httplib2: None
apiclient: None
sqlalchemy: 1.0.9
pymysql: None
psycopg2: None
jinja2: 2.8
boto: 2.38.0

**Comment by jreback** [comment]
``datareader`` has been deprecated since 0.17.0 in pandas main, you can direct this issue to:

https://github.com/pydata/pandas-datareader
