### ISSUE TITLE
TST: assert that IncompatibleFrequency is raise (rather than ValueError)

### ISSUE THREAD

**Issue by jreback** [pydata/pandas#13251]
https://github.com/pydata/pandas/pull/13079#issuecomment-220780044

just need to make sure that we are raising IncompatibleFrequency as appropriate (and testing explicity for this rather than ValueError) when constructing Periods.

**Comment by jreback** [comment]
#13250  prob convers most/all of this.

**Comment by sinhrks** [comment]
Yes, covered in #13250.

**Comment by jreback** [comment]
thanks
