### ISSUE TITLE
Dividing Time-series

### ISSUE THREAD

**Issue by fccoelho** [pydata/pandas#13269]
Dividing time-series does not work as expected;

#### Code Sample, a copy-pastable example if possible
```python
ts1 = pd.TimeSeries(range(10))
ts2 = pd.TimeSeries(range(10))
ts1[1:]/ts2[:-1]
```
the output of this operation is:
```
0    NaN
1    1.0
2    1.0
3    1.0
4    1.0
5    1.0
6    1.0
7    1.0
8    1.0
9    NaN
```
#### Expected Output
What I expected is the same as the division of two `np.ndarray`s
```python
ts1.values[1:]/ts2.values[:-1]
```
array([        inf,  2.        ,  1.5       ,  1.33333333,  1.25      ,
        1.2       ,  1.16666667,  1.14285714,  1.125     ])

#### output of ``pd.show_versions()``

INSTALLED VERSIONS
------------------
commit: None
python: 3.5.1.final.0
python-bits: 64
OS: Linux
OS-release: 4.2.0-12-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: pt_BR.UTF-8

pandas: 0.18.1
nose: 1.2.1
pip: 8.1.2
setuptools: 20.1.1
Cython: 0.24
numpy: 1.11.0
scipy: 0.17.1
statsmodels: 0.6.1
xarray: None
IPython: 4.2.0
sphinx: 1.3.5
patsy: 0.4.1
dateutil: 2.5.3
pytz: 2016.4
blosc: None
bottleneck: None
tables: None
numexpr: None
matplotlib: 1.5.1
openpyxl: None
xlrd: 0.9.4
xlwt: None
xlsxwriter: 0.7.3
lxml: None
bs4: 4.4.1
html5lib: 0.999
httplib2: 0.9.1
apiclient: None
sqlalchemy: 1.0.12
pymysql: 0.7.2.None
psycopg2: 2.6.1 (dt dec pq3 ext lo64)
jinja2: 2.8
boto: 2.39.0
pandas_datareader: None

**Comment by jreback** [comment]
pandas by definition aligns things. ``TimeSeries`` is deprecated.

```
In [4]: ts1 = pd.Series(range(10))

In [5]: ts2 = pd.Series(range(10))

In [6]: ts1/ts2.shift(1)
Out[6]: 
0         NaN
1         inf
2    2.000000
3    1.500000
4    1.333333
5    1.250000
6    1.200000
7    1.166667
8    1.142857
9    1.125000
dtype: float64
```
