### ISSUE TITLE
Import error: No module named 'pandas.compat.numpy'

### ISSUE THREAD

**Issue by SabS99** [pydata/pandas#13268]
Hi there!

Just installed Anaconda for Windows (pandas 0.18.1, numpy 1.11.0) and cannot fix the following problem, when I try to import pandas:

import pandas as pd

Traceback (most recent call last):

File "C:\Users\Username\AppData\Roaming\Python\Python35\site-packages\IPython\core\interactiveshell.py", line 2885, in run_code
exec(code_obj, self.user_global_ns, self.user_ns)

File "", line 1, in
import pandas as pd

File "C:\Program Files (x86)\JetBrains\PyCharm 2016.1.3\helpers\pydev_pydev_bundle\pydev_import_hook.py", line 21, in do_import
module = self._system_import(name, args, *kwargs)

File "C:\Users\Username\AppData\Roaming\Python\Python35\site-packages\pandas__init__.py", line 22, in
from pandas.compat.numpy import *

File "C:\Program Files (x86)\JetBrains\PyCharm 2016.1.3\helpers\pydev_pydev_bundle\pydev_import_hook.py", line 21, in do_import
module = self._system_import(name, args, *kwargs)

ImportError: No module named 'pandas.compat.numpy'

**Comment by jreback** [comment]
you were probably running with an old conda, which on windows can fail to install an upgrade if you are actively using the process (eg. you have pandas imported somewhere).

here are the latest

```
# packages in environment at /Users/jreback/miniconda:
#
anaconda-client           1.0.2                    py27_0    defaults
conda                     4.0.6                    py27_0    defaults
conda-build               1.20.3                   py27_0    defaults
conda-env                 2.4.5                    py27_0    defaults
```

so ``conda update conda``
kill all of your python sessions
```
conda remove pandas -f
conda install pandas
```

**Comment by SabS99** [comment]
Thanks for your quick answer!

`conda update conda` yields:

```
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ....
# All requested packages already installed.
# packages in environment at C:\Users\Username\AppData\Local\Continuum\Anaconda3
:
#
conda                     4.0.6                    py35_0
```

and `conda remove pandas -f` yields

```
usage: conda-script.py [-h] [-V] [--debug] command ...
conda-script.py: error: unrecognized arguments: -f
```

**Comment by SabS99** [comment]
```
# packages in environment at C:\Users\Username\AppData\Local\Continuum\Anaconda
:
#
anaconda-client           1.4.0                    py35_0
conda                     4.0.6                    py35_0
conda-build               1.20.3                   py35_0
conda-env                 2.4.5                    py35_0
```

**Comment by jreback** [comment]
``conda remove pandas --force``

you also have to configure pydev to find the environment. no idea how to do that.

**Comment by SabS99** [comment]
Now it works. Thanks! But what does the second line mean?

```
import pandas
Backend Qt4Agg is interactive backend. Turning interactive mode on.
```

**Comment by jreback** [comment]
that's from matplotlib and/or PyCharm
