### ISSUE TITLE
defining min_itemsize creates "data_columns"

### ISSUE THREAD

**Issue by costas821** [pydata/pandas#13289]
I am trying to write results from a dataframe to hdf using the append (or .to_hdf) function. A few of my columns are large string whose length will vary (around 1k characters). Because its length will vary, I have to set, min_itemsize, for each of the variable columns. I do not want these fields to be treated as data_columns, but each time I define the column in the field min_itemsize, they become data_columns when looking at the result in hdf.

```
>>> df = pd.DataFrame(columns=['long string', 'a', 'b', 'longstring2'])
>>>df.to_hdf('test', 'key', data_columns=['a'])  # => only a is a data_column
>>>df.to_hdf('test', 'key', data_columns=['a'], min_itemsize={'long string': 1000, 'lonstring2': 1000}) # => now a, longstring2, and long string are datacolumns.
```

Is there any way to define min_itemsizes but not make those fields data_columns? I ask because when I make them data_columns I get warnings that my rowsize is too large.

**Comment by jreback** [comment]
this is by-definition. Specifying ``min_itemsize`` stores this as a separate fixed-width column (as opposed to storing with other string columns).

Not sure you should actually care about this as its an implementation detail. The warnings are because you are truncating. You are ultimately storing in a fixed-width column, so you must truncate (or you can pre-truncate).

**Comment by costas821** [comment]
All I am aiming to do is store very large tables containing millions of rows and about 10 string columns (strings in most columns will vary in string length) to a file, and later retrieve subsets of all of the information very rapidly using a well defined fixed column (not the long string columns mentioned above). But currently performance seems not as fast as just dumping everything to a csv file and then sorting that csv file on the specific column outside of python...I don't really want to do this because its hacky.

Based on your response, I feel as though I may be using the wrong strategy/implementing to_hdf incorrectly. 

1) First, when you say "I must truncate"  I assume this means that, if i truncate, when I try to retrieve that record at a later time, I will only be shown a truncated version of the string? If so that is not an option for me as the entire string is important, but in the past when I have set the min_itemsize for a column string to an extremely long length then I get an error, not a warning.

2) With regard to it being an implementation detail, will adding these large strings as data_columns impact my query performance if I am querying on a separate column? Or is the warning message about I/O performance and memory usage not actually relevant in this situation.

3) In the end is there any way to use  to_hdf but have a string column not be a data column and its length be 'variable'?

**Comment by jreback** [comment]
@costas821 if the warnings bother you then you can truncate. If you don't it WILL be truncated. So you need to choose a min_itemsize that encompasses your entire width you want to save. These are saved as fixed-width strings. Storing variable length strings is not supported.

You can try using categoricals if you have some repeats.

making this a data_column will not be a problem for query performance.

You must have something funny going on. HDF write perf is WAY faster than csv.

**Comment by costas821** [comment]
@jreback 

Maybe you can see if Im doing something wrong. I did some time tests below to get an idea of what to expect

df.shape = (235114, 12)

Just using to_csv: ~ 18 seconds
```
t1 = time.time()
for i in range(5):
    if i == 0:
        df.to_csv('testdf.txt', sep='\t')
    else:
        df.to_csv('testdf.txt', sep='\t', header=False, mode='a')
t2 = time.time()
t2-t1
```

Using to_hdf where we set item_sizes: ~ 115 seconds
```
# I only really care about indexing columns c5-c8, but will ignore for now
max_item_sizes = {
    'c1': 60,
    'c2': 10,
    'c3': 1000,
    'c4': 1000,
    'c5': 10,
    'c6': 10,
    'c7': 15,
    'c8': 15,
    'c9': 25,
    'c10': 25
}
t1 = time.time()
for i in range(5):
    df.to_hdf("testhdf.h5", 'df', min_itemsize=max_item_sizes,  data_columns=None, append=True, format='t')
t2 = time.time()
t2-t1
```

Using to_hdf where we ignore item_sizes (raises an error if appending columns with different lengths later on): ~ 46 seconds
```
t1 = time.time()
for i in range(5):
    df.to_hdf("testhdf2.h5", 'df', data_columns=None, append=True, format='t')
t2 = time.time()
t2-t1
```

**Comment by jreback** [comment]
@costas821 you should need to show something that creates a facimile of your data.

So here's a little sample. You basically are exceeding the limits of PyTables. Storing very wide text data (which you are doing) is not that efficient, nor fast. This is designed really for mostly numbers. That said it will work.

```
In [10]: df = DataFrame({ c:''.join(['A'] * v) for c, v in max_item_sizes.items()},index=range(10000))

In [11]: df.info()
<class 'pandas.core.frame.DataFrame'>
Int64Index: 10000 entries, 0 to 9999
Data columns (total 10 columns):
c1     10000 non-null object
c10    10000 non-null object
c2     10000 non-null object
c3     10000 non-null object
c4     10000 non-null object
c5     10000 non-null object
c6     10000 non-null object
c7     10000 non-null object
c8     10000 non-null object
c9     10000 non-null object
dtypes: object(10)
memory usage: 859.4+ KB

In [12]: df.head()
Out[12]: 
                                                  c1                        c10          c2                                                 c3                                                 c4  \
0  AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA...  AAAAAAAAAAAAAAAAAAAAAAAAA  AAAAAAAAAA  AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA...  AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA...   
1  AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA...  AAAAAAAAAAAAAAAAAAAAAAAAA  AAAAAAAAAA  AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA...  AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA...   
2  AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA...  AAAAAAAAAAAAAAAAAAAAAAAAA  AAAAAAAAAA  AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA...  AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA...   
3  AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA...  AAAAAAAAAAAAAAAAAAAAAAAAA  AAAAAAAAAA  AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA...  AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA...   
4  AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA...  AAAAAAAAAAAAAAAAAAAAAAAAA  AAAAAAAAAA  AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA...  AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA...   

           c5          c6               c7               c8                         c9  
0  AAAAAAAAAA  AAAAAAAAAA  AAAAAAAAAAAAAAA  AAAAAAAAAAAAAAA  AAAAAAAAAAAAAAAAAAAAAAAAA  
1  AAAAAAAAAA  AAAAAAAAAA  AAAAAAAAAAAAAAA  AAAAAAAAAAAAAAA  AAAAAAAAAAAAAAAAAAAAAAAAA  
2  AAAAAAAAAA  AAAAAAAAAA  AAAAAAAAAAAAAAA  AAAAAAAAAAAAAAA  AAAAAAAAAAAAAAAAAAAAAAAAA  
3  AAAAAAAAAA  AAAAAAAAAA  AAAAAAAAAAAAAAA  AAAAAAAAAAAAAAA  AAAAAAAAAAAAAAAAAAAAAAAAA  
4  AAAAAAAAAA  AAAAAAAAAA  AAAAAAAAAAAAAAA  AAAAAAAAAAAAAAA  AAAAAAAAAAAAAAAAAAAAAAAAA  

In [13]: %timeit df.to_csv('test.csv')
1 loop, best of 3: 317 ms per loop
```

```
def f():
    store = pd.HDFStore('test.h5',mode='w')

    for c, mi in max_item_sizes.items():
        store.append(c,df[c],min_itemsize=mi)

    store.close()

In [29]: f()

In [30]: %timeit f()
1 loop, best of 3: 508 ms per loop

```
