### ISSUE TITLE
API: New callable indexing makes storing functions in a Series difficult

### ISSUE THREAD

**Issue by evanpw** [pydata/pandas#13299]
Example of something that previously worked (before 7bbd031104ee161b2fb79ba6f5732910661f94f8):

``` .python
>>> s = pd.Series([lambda x: x] * 10)
>>> s[s.index > 5] = lambda x: x + 1
```

But now the second line tries to apply the function in the rhs to the elements of the Series, rather than assigning them (and throws an exception). This is very counter-intuitive when using ``__setitem__`` rather than calling ``Series.where`` directly.

**Comment by jreback** [comment]
this is quite odd to store callables in a Series

what is the purpose of doing that?

**Comment by jreback** [comment]
hmm, this is simple to fix (we just don't evaluate a callable for ``other`` in ``.where``).

@sinhrks do we have a valid use of ``other`` as a callable?

**Comment by evanpw** [comment]
We're choosing a function based on some columns in a DataFrame, and then applying them on other column values / external data. Since there might be a different function for each row, it's convenient to store them in the same place.

**Comment by jreback** [comment]
@evanpw I think you might be able to just remove the ``_maybe_callable(other...)`` and this will work. Not really sure of the original purpose of testing for a callable on the other (e.g. it works, but IMHO not that useful).

If you want to give this a shot and see what it looks like would be great.

**Comment by evanpw** [comment]
Yes, deleting this line from `where` in generic.py fixes the problem for me:

``` .python
other = com._apply_if_callable(other, self)
```

**Comment by sinhrks** [comment]
The usage in my mind was chaining like:

```
pd.DataFrame({'A': [1, 2, 1, 2], 'B': [1, 2, 3, 4]}).groupby('A').sum().where(lambda x: x < 5, lambda x: -x)
#    B
# A   
# 1  4
# 2 -6
```

I think it is more likely rather than storing callable.

CC: @TomAugspurger

**Comment by evanpw** [comment]
I think that makes sense when calling `where` directly. What about making it configurable, and turned off when using `__setitem__`?

**Comment by jreback** [comment]
yes that is a bug I think.
