### ISSUE TITLE
order not preserved when constructing DataFrame from a list of OrderedDicts

### ISSUE THREAD

**Issue by ilrico** [pydata/pandas#13304]
issue is explained here:
http://stackoverflow.com/questions/37484738/pandas-dataframe-construction-from-a-list-of-ordereddict-preserving-columns-ord?noredirect=1#comment62465925_37484738

workaround with constructor option "columns" works but not elegant.

**Comment by jreback** [comment]
pls post a copy-pastable reproducible example at the top of the PR.

yes this could be an enhancement. pull-requests are welcome.

**Comment by gfyoung** [comment]
Here's one:
~~~python
>>> from pandas.compat import OrderedDict
>>> from pandas import DataFrame
>>>
>>> data = OrderedDict()
>>> data['c'] = 2
>>> data['b'] = 1
>>> data
OrderedDict([('c', 2), ('b', 1)])
>>> DataFrame([data])
   b  c
0  1  2
~~~

**Comment by gfyoung** [comment]
I should point out though that if you pass in the `OrderedDict` with _arrays_ as the values, the order is in fact preserved!
~~~python
>>> from pandas.compat import OrderedDict
>>> from pandas import DataFrame
>>>
>>> data = OrderedDict()
>>> data['c'] = [2]
>>> data['b'] = [1]
>>>
>>> data
OrderedDict([('c', [2]), ('b', [1])])
>>>
>>> DataFrame([data])
   c  b
0  2  1
~~~

**Comment by gfyoung** [comment]
"Bug" traces back to the initialization of arrays from the list of dictionaries.  The initialization sorts the keys at the end, so we just need a boolean to tell it not to sort when we have `OrderedDict`.  Can take this one home.
