### ISSUE TITLE
API: skipfooter or skip_footer?  read_csv can't seem to decide

### ISSUE THREAD

**Issue by gfyoung** [pydata/pandas#13349]
`skipfooter`  : "This line <a href="https://github.com/pydata/pandas/blob/master/pandas/io/parsers.py#L729">here</a> says I am the right choice."

`skip_footer` : "This line <a href=https://github.com/pydata/pandas/blob/master/pandas/io/parsers.py#L519">here</a> says I am the right choice."

Whatever the case is, something should certainly be done to avoid having duplicate arguments for the same thing, as can be seen <a href="https://github.com/pydata/pandas/blob/master/pandas/io/parsers.py#L582">here</a>

**Comment by jreback** [comment]
The full-list is here: https://github.com/pydata/pandas/issues/4988

Yeah should prob fix this. I think the ``_`` are better (though I wouldn't change for example ``usecols``)
and ``skiprows`` is in-line with ``skipfooter``.

We should see what changes to make this reasonable and minimze the deprecations (including maybe doing nothing).

**Comment by gfyoung** [comment]
Yeah, not sure what is best yet.  Just wanted to mention this problem since having duplicate arguments in the API isn't a good thing.  A more careful analysis of the API / code would be needed to make sure that we don't change too much unnecessarily.

**Comment by gfyoung** [comment]
I'm inclined to deprecate `skipfooter` because the `_` is used internally throughout the code.  I'll take a look at that first and change any relevant tests as well to use the "correct" one.
