### ISSUE TITLE
Datetime is failing silently for one date

### ISSUE THREAD

**Issue by AnnamalaiNagappan** [pydata/pandas#13342]
#### Code Sample, a copy-pastable example if possible
pd.to_datetime("06/2015") **# When my system date is 5/31/2016, it returns a string (06/2015)**
#### Expected Output
Timestamp('2015-06-01 00:00:00')
#### output of ``pd.show_versions()``
'0.16.2'

**Comment by jreback** [comment]
this works on 0.16.2 and master. so not sure what your issue is. you can try a more recent version of pandas.

**Comment by AnnamalaiNagappan** [comment]
Have you tried changing your system date to 5/31/2016, and tried running the same. It fails for me

**Comment by jorisvandenbossche** [comment]
@AnnamalaiNagappan Do you mean actually changing the date (why would you want to do that?), or just the style? If so, can you show a reproducible example with setting a locale that fails for you?

**Comment by AnnamalaiNagappan** [comment]
It's because on that day alone (5/31/2016), the code failed. The immediate next day it seems to working fine.PFA screenshots
![correct](https://cloud.githubusercontent.com/assets/1428796/15847014/0a115c10-2ca0-11e6-99ae-2d5e25464c97.PNG)
![datetime](https://cloud.githubusercontent.com/assets/1428796/15847015/0a1307ae-2ca0-11e6-9c02-7a085e128fb0.PNG)
