### ISSUE TITLE
Why 'axis=1' denote different axis in different cases?

### ISSUE THREAD

**Issue by RosinLee** [pydata/pandas#13367]
In `df.apply(f, axis=1)` , it means applying `f` on rows. However, In `df.drop([column_name], axis=1)`, it means dropping columns. 
So, what is the trick to determine in which cases `axis=1` means functioning on rows while in other cases it means functioning on columns ?

**Comment by jreback** [comment]
``.apply`` has a convenience signature so we can easily write ``df.apply(function_for_columns)``, which means this function works on the columns themselves. Yes I guess this is a bit odd. 

This is different that an operation to do something *on an axis itself*, which is what ``.drop`` is doing, IOW saying drop FROM THIS AXIS.

```
In [8]: DataFrame.apply?
Signature: DataFrame.apply(self, func, axis=0, broadcast=False, raw=False, reduce=None, args=(), **kwds)
Docstring:
Applies function along input axis of DataFrame.

Objects passed to functions are Series objects having index
either the DataFrame's index (axis=0) or the columns (axis=1).
Return type depends on whether passed function aggregates, or the
reduce argument if the DataFrame is empty.

Parameters
----------
func : function
    Function to apply to each column/row
axis : {0 or 'index', 1 or 'columns'}, default 0
    * 0 or 'index': apply function to each column
    * 1 or 'columns': apply function to each row
broadcast : boolean, default False
    For aggregation functions, return object of same size with values
```
