### ISSUE TITLE
BUG: .extractall() throws AssertionError if capture group length > 1

### ISSUE THREAD

**Issue by GeraintDuck** [pydata/pandas#13382]
Code to replicate error:
```
import pandas as pd
s = pd.Series(["a13a23", "b13", "c13"], index=["A", "B", "C"])
s.str.extractall("[ab](\d\d)")
```

Note that the regex `[ab](\d)` from the documentation page works, whereas `[ab](\d\d)` above doesn't. It seems that any captured group with a length of > 1 causes this error.

Though playing with this a bit more, the following regex's all seem to work correctly without error:
```
([ab])(\d\d)
()[ab](\d+)
(a13)(\d\d)
```

I've reproduced the issue in both versions 0.18.0 and 0.18.1. I'll admit I've not checked against the master branch though.

Note: I posted this to the mailing list, but haven't had any responses - thus I assume this is a bug.
I'm unsure what the underlying cause is here (maybe it doesn't like the first regex character not being within a capture group?).

**Comment by jreback** [comment]
cc @tdhock

yeah this looks buggy. welcome to have you step thru and see where the error is / pull-request.

**Comment by GeraintDuck** [comment]
I've narrowed it down to the list comprehension on [this](https://github.com/pydata/pandas/blob/master/pandas/core/strings.py#L711) line. When the tuple is of length 1, it separates out the _string_ into individual chars, rather than iterating over the (single) tuple value(s).

```
>>> [x for x in ('ab', 'xy')]
['ab', 'xy']
>>> [x for x in ('ab')]
['a', 'b']
```

I suppose code can be added beforehand to check for this particular case (though checking the length has the same issue - both examples above are length 2), but is there a cleaner fix?

**Comment by jreback** [comment]
you can just make a list of the capture groups i think


```
In [9]: [ x for x in ('ab')]
Out[9]: ['a', 'b']

In [10]: [ x for x in ['ab']]
Out[10]: ['ab']
```
