### ISSUE TITLE
Series.nonzero() method not listed in API reference

### ISSUE THREAD

**Issue by ankostis** [pydata/pandas#13384]
I cannot find the `Series.nonzeros()` method in the [API Reference](http://pandas.pydata.org/pandas-docs/stable/api.html#series) documentation-page for `pandas <= 0.18.1`.

**Comment by jreback** [comment]
http://pandas.pydata.org/pandas-docs/version/0.18.0/generated/pandas.Series.nonzero.html?highlight=nonzero#pandas.Series.nonzero

you have to look at a specific version. Note this is only a wrapper around a numpy rountine.

**Comment by ankostis** [comment]
Maybe the inline link was not that clear.
I'm not referring to the documentation. I can indeed find this page in any pandas-version.

I'm referring to this page listing ALL functions of pandas (possibly even numpy wrappers): http://pandas.pydata.org/pandas-docs/stable/api.html#series

**Comment by jreback** [comment]
[see listing here of the open issues](https://github.com/pydata/pandas/search?q=api+doc&state=open&type=Issues&utf8=%E2%9C%93) to document things in the API.rst. This was/is pretty manual. If someone wants to step up and actually add these, great. Even better would be an automated scripts to fail builds that has functions not listed.
