### ISSUE TITLE
COMPAT: comparisons with as_recarray breaking on older numpies

### ISSUE THREAD

**Issue by jreback** [pydata/pandas#13388]
https://travis-ci.org/pydata/pandas/jobs/135897420

cc @gfyoung

**Comment by jreback** [comment]
xref #13373

**Comment by gfyoung** [comment]
Nitpick: can we change the title, as AFAICT that machine is using `1.7.1`

**Comment by gfyoung** [comment]
Arghh...`array_equal` in `numpy` wasn't implemented for `recarray` back in `1.7.1`, meaning that I can't check the correctness of `as_recarray` in that test using `tm.assert_numpy_array_equal`.  @jreback How to proceed?

**Comment by jreback** [comment]
oh, you can put in a path if its a recarry, just maybe assert that both sides are recarray and listify (and assert_almost_equal)? (e.g. that will minimize impact on other code)

**Comment by gfyoung** [comment]
Hmm...well it isn't actually `numpy.recarray` that's the issue.  Rather, it's `numpy` arrays like this:
~~~python
>>> m
array([(1, 2.0), (3, 4.0)], 
      dtype=[('a', '<i8'), ('b', '<f8')])
>>> np.array_equal(m, m)  # should return True
NotImplemented
~~~
Might need to do `try-except` with specific checking of the error message.
