### ISSUE TITLE
BLD: should we use tempita for cython templating

### ISSUE THREAD

**Issue by jreback** [pydata/pandas#13399]
see [here](http://pythonpaste.org/tempita/)

might replace some of the manual code paths in ``generate_code.py``

**Comment by jreback** [comment]
@gfyoung can you comment on your experience

**Comment by gfyoung** [comment]
+1 from me - it's currently used in `scipy` and `numpy` and I in fact put it to good use in one of my PR's against `numpy` in fact.  Also, since `tempita` comes with `Cython` (`Cython.Tempita`), if it's possible to use it in order to cut down on manual code, certainly!

**Comment by sinhrks** [comment]
Quite interesting. I'm just adding new cython templates to support more sparse dtypes, and it can be much simpler using it.

**Comment by jreback** [comment]
@gfyoung can u post a link to the PR where u r using this?

**Comment by gfyoung** [comment]
Link to PR <a href="https://github.com/numpy/numpy/pull/6938">here</a>.  Key file to examine is `randint_helpers.pxi.in` and the templating code <a href="https://github.com/numpy/numpy/pull/6938/files#diff-6e2c9b85250e2af0fe46f180ace4283cR104">here</a>

Useful discussion points regarding Tempita in my PR start <a href="https://github.com/numpy/numpy/pull/6938#issuecomment-224208311">here</a>

**Comment by jreback** [comment]
thanks @gfyoung 

note that I have found fused types pretty useful as well. [here](https://github.com/pydata/pandas/blob/master/pandas/src/util.pxd#L27) is an example of a ``numeric`` type which is used in ``window.pyx`` & some of the ``algos.pyx``. These are pretty easy to define and work with; and somewhat remove the need for templating.

**Comment by gfyoung** [comment]
@jreback : yes, I remember you mentioning that in that same PR <a href=https://github.com/numpy/numpy/pull/6938#discussion_r64143615">here</a>.  I guess not all maintainers are a fan of it though.

**Comment by jreback** [comment]
right they are in newer cython (though our min 0.19.1 certainly has it)

**Comment by gfyoung** [comment]
well different repository, different rules :smile: - `fused_types` may not be as applicable in this case though given that there are some things in the template to `generate_code.py` that aren't fuse-type-able FLOABW.

**Comment by jreback** [comment]
@gfyoung yeah, though if I *could* use a fused type I think we should. Just easier to read/maintain. They seem to act very much like 'real' types, with a tiny exception. You need to this to avoid warnings when compiling.

```
cdef numeric val

if numeric in cython.floating and val == val:
     # do something if we are not-NaN
```

**Comment by shoyer** [comment]
I agree that fused types are nice, but in my experience they end up falling short. Tempita looks pretty nice, better than our ad-hoc current system.
