### ISSUE TITLE
is there pandas.filter for values (not row or column labels)?

### ISSUE THREAD

**Issue by denfromufa** [pydata/pandas#13414]
Right now I have to do the following:

```python
ix=None
for ixi in [res[col].str.contains('string') for col in res.columns]:
    if ix is not None:
        ix = ix | ixi
    else:
        ix = ixi
res[ix]
```

**Comment by jreback** [comment]
can you show a complete example.

**Comment by denfromufa** [comment]
http://stackoverflow.com/questions/37735403/is-there-pandas-filter-for-values-not-row-or-column-labels

**Comment by jreback** [comment]
the answer is idiomatic 

applying across the columns is fine

**Comment by denfromufa** [comment]
how about adding option to filter values (not axis) to pd.filter()?

**Comment by jreback** [comment]
filter is being deprecated

you can filter values with indexing eg loc
