### ISSUE TITLE
ERR: invalid input to .str.replace does not raise

### ISSUE THREAD

**Issue by jreback** [pydata/pandas#13438]
This should raise; ``None`` is not an allowed option for the replacement.

```
In [2]: s = pd.Series(['a', 'b', None])

In [3]: s
Out[3]: 
0       a
1       b
2    None
dtype: object

In [4]: s.str.replace('a', None)
Out[4]: 
0   NaN
1   NaN
2   NaN
dtype: float64
```

cc @kwsmith

**Comment by jorisvandenbossche** [comment]
It's not only None that gives non-sensical output, also eg numerical values:

```
In [115]: s.str.replace('a', 3)
Out[115]:
0   NaN
1   NaN
2   NaN
dtype: float64
```

So rather than checking for None, maybe just check that the replacement is string-like?

**Comment by priyankjain** [comment]
Gotcha, is the following output valid:

>`s.str.replace('','a')

0     aaa
1     aba
2    None
dtype: object`

**Comment by jorisvandenbossche** [comment]
Hmm, not sure about that one. At first, it seems invalid as well, but this is the standard behaviour of `str.replace`:

```
In [125]: 'a'.replace('', 'b')
Out[125]: 'bab'
```

**Comment by priyankjain** [comment]
I think it makes more sense to consider this as valid, since that's how str.replace works. Also it would make sense to throw TypeError instead of ValueError:
```
'abc'.replace('a', None)

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-19-51f0617eaa9d> in <module>()
----> 1 'abc'.replace('a', None)

TypeError: Can't convert 'NoneType' object to str implicitly

```
