### ISSUE TITLE
installlation error 

### ISSUE THREAD

**Issue by cracker111** [pydata/pandas#13437]
traceback(most recet call last):
file "setup,py" , line 33 , in <module>
ver =Cython. __version__ 
atrribute error: 'module' object has no attribute ' __version__ '

**Comment by jorisvandenbossche** [comment]
What version of cython are you using?

**Comment by cracker111** [comment]
Cython - 0.24

**Comment by jorisvandenbossche** [comment]
Can you specify a bit more what you did?
