### ISSUE TITLE
API: NaT/nan mixed input coerces to timedelta64

### ISSUE THREAD

**Issue by sinhrks** [pydata/pandas#13467]
#### Code Sample, a copy-pastable example if possible

``Index``/``Series`` results in ``datetime64`` dtype if all inputs are ``pd.NaT``.

```
pd.Index([pd.NaT, pd.NaT])
# DatetimeIndex(['NaT', 'NaT'], dtype='datetime64[ns]', freq=None)

pd.Series([pd.NaT, pd.NaT])
# 0   NaT
# 1   NaT
# dtype: datetime64[ns]
```

However, it coerces to ``timedelta64`` if ``np.nan`` is included. 

```
pd.Index([pd.NaT, np.nan])
# TimedeltaIndex([NaT, NaT], dtype='timedelta64[ns]', freq=None)

pd.Series([pd.NaT, np.nan])
# 0   NaT
# 1   NaT
# dtype: timedelta64[ns]
```

This looks to be caused by following internals:

```
pd.tslib.is_timestamp_array(np.array([pd.NaT, np.nan]))
# False
pd.lib.is_timedelta_array(np.array([pd.NaT, np.nan]))
# True
```

#### Expected Output

``datetime64`` dtype?

#### output of ``pd.show_versions()``

on current master

**Comment by jreback** [comment]
``tslib.is_timestamp_array`` looks totally out of place / is old, need to remove that and replace with routine from ``src/inference.pyx`` (which is where ``is_timedelta_array`` is defined, along with all other inference routines).

but your result should be the same (e.g. ``M8[ns]``)

**Comment by sinhrks** [comment]
OK. Also there is no tests to guarantee the behavior. Will submit a PR.

**Comment by sinhrks** [comment]
Found there are inconsistencies depending on the order. Is it OK that all these must be datetime64?

```
# OK
pd.Index([np.nan, pd.NaT])
# DatetimeIndex(['NaT', 'NaT'], dtype='datetime64[ns]', freq=None)

# NG, must be DatetimeIndex
pd.Index([pd.NaT, np.nan])
# TimedeltaIndex([NaT, NaT], dtype='timedelta64[ns]', freq=None)
```

```
# OK
pd.lib.infer_dtype([np.nan, pd.NaT])
# 'datetime64'

# NG, msut be 'datetime64'
pd.lib.infer_dtype([pd.NaT, np.nan])
# 'mixed'
```

**Comment by sinhrks** [comment]
Actually it is not simple than I initially thought. On current master, we don't distinguish datetime64/timedelta64 NaT. Thus below input is regarded as ``timedelta``.

```
pd.lib.infer_dtype(np.array([np.datetime64('nat'), pd.Timedelta('1 day')]))
# 'timedelta'
```

However, if input is all nan/nat like, it is inferred using last element.

```
pd.lib.infer_dtype(np.array([np.datetime64('nat'), np.timedelta64('nat')], dtype=object))
# 'timedelta'

pd.lib.infer_dtype(np.array([np.timedelta64('nat'), np.datetime64('nat')], dtype=object))
# 'datetime64'
```

If we regard np.datetime/timedelta nat as the same as ``pd.NaT``, the both results should be "datetime64". Otherwise, np.datetime/timedelta mixture should be infered as "mixed".

**Comment by jreback** [comment]
ahh I c. Since we have a single ``pd.NaT`` for both M8 and m8, I think we need to keep that all nan -> M8 if not-specified.
