### ISSUE TITLE
Feature Request: Expose more parsing options in html_read

### ISSUE THREAD

**Issue by gte620v** [pydata/pandas#13461]
I am trying to parse some HTML and would love to have `converters` (https://github.com/pydata/pandas/blob/master/pandas/io/parsers.py#L1582-L1586) exposed to the `read_html` function.  

Is there a reason why more parsing/all parsing options aren't exposed to `TextParser` at https://github.com/pydata/pandas/blob/master/pandas/io/html.py#L631-L634 ?  

If not, would it be of interest to have a PR that adds this functionality?

**Comment by jreback** [comment]
thought we had an issue about this, but closest is #10534 about passing dtypes thru. So this is quite similiar. It *should* be straightforward to implement.

**Comment by gte620v** [comment]
Cool. I'm happy to give it a shot if it is a feature that might get merged.  Is it?

**Comment by jreback** [comment]
yes
