### ISSUE TITLE
Enhancement request for .get_values()

### ISSUE THREAD

**Issue by mcocdawc** [pydata/pandas#13479]
#### Code Sample, a copy-pastable example if possible
Hello,

At the moment I have to call two methods, if I want to extract a numpy array from a 
DataFrame with a specific type.
Let's assume for this example that `example_frame` contains only integers. 
If I want to force `int64` numbers, I have to write:
```
example_frame.get_values().astype('int64')
```
#### Expected Output
It would be a bit nicer if, `get_values(dtype=None)` works per default as before,
but allows to write:
```
example_frame.get_values(dtype='int64')
```
#### output of ``pd.show_versions()``

INSTALLED VERSIONS
------------------
commit: None
python: 3.5.1.final.0
python-bits: 64
OS: Linux
OS-release: 3.16.0-73-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

pandas: 0.18.0
nose: 1.3.7
pip: 8.1.1
setuptools: 20.3
Cython: 0.23.4
numpy: 1.10.4
scipy: 0.17.0
statsmodels: 0.6.1
xarray: None
IPython: 4.1.2
sphinx: 1.3.5
patsy: 0.4.0
dateutil: 2.5.1
pytz: 2016.2
blosc: None
bottleneck: 1.0.0
tables: 3.2.2
numexpr: 2.5
matplotlib: 1.5.1
openpyxl: 2.3.2
xlrd: 0.9.4
xlwt: 1.0.0
xlsxwriter: 0.8.4
lxml: 3.6.0
bs4: 4.4.1
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.0.12
pymysql: None
psycopg2: None
jinja2: 2.8
boto: 2.39.0

**Comment by jreback** [comment]
you will have to show something more specific about what you are requesting.

first, ``.get_values()`` is public, though mostly for internal API reasons. You should simply use ``.values``. Not sure why astyping matters here; once you get to numpy you are in charge of that.
