### ISSUE TITLE
Incorrect use of super() in pandas core module

### ISSUE THREAD

**Issue by dirkbike** [pydata/pandas#13482]
#### Existing Code
In the pandas core module `base.py`, the `__sizeof__` member of the `PandasObject` class uses the following line:
```
return super(self, PandasObject).__sizeof__()
```
#### Expected Code
This is an incorrect use of `super`, which is supposed to have the type argument before the object argument ([reference](https://docs.python.org/3/library/functions.html#super)).  This also results in a known problem with the memory tracking tool `pympler` ([reference](http://stackoverflow.com/a/37681457)).  The corrected line should instead be:
```
return super(PandasObject, self).__sizeof__()
```
#### output of ``pd.show_versions()``
```
INSTALLED VERSIONS
------------------
commit: None
python: 3.4.3.final.0
python-bits: 64
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 15 Stepping 11, GenuineInte
byteorder: little
LC_ALL: None
LANG: None

pandas: 0.18.1
nose: None
pip: 8.1.2
setuptools: 22.0.5
Cython: 0.23.1
numpy: 1.11.0
scipy: 0.17.1
statsmodels: 0.6.1
xarray: None
IPython: 3.2.1
sphinx: None
patsy: 0.3.0
dateutil: 2.5.3
pytz: 2016.4
blosc: None
bottleneck: None
tables: None
numexpr: 2.4.3
matplotlib: 1.4.2
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 0.9999999
httplib2: None
apiclient: None
sqlalchemy: 1.0.13
pymysql: None
psycopg2: None
jinja2: 2.7.3
boto: None
pandas_datareader: None
```

**Comment by jreback** [comment]
this is already closed by https://github.com/pydata/pandas/pull/12924
