### ISSUE TITLE
ValueError on eval after 'from pandas import *'

### ISSUE THREAD

**Issue by Espri** [pydata/pandas#13495]
#### Test  code
[20160621 eval problem.txt](https://github.com/pydata/pandas/files/325599/20160621.eval.problem.txt)

#### Expected Output
Raises Value Error when using 'from pandas import *'. Executes as expected using 'import pandas'.
Issue was raised originally at bugs.Python.org - Issue: 27361 but from there pointed to pandas. I'm not clear whether the bug is in pandas, or eval or import.

I ran this under anaconda (condo version 4.0.7) with Python 3.4.4 under OS X 10.11.5

#### output of ``pd.show_versions()``
INSTALLED VERSIONS
------------------
commit: None
python: 3.4.4.final.0
python-bits: 64
OS: Darwin
OS-release: 15.5.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: None

pandas: 0.16.2
nose: 1.3.7
Cython: 0.22.1
numpy: 1.9.2
scipy: 0.15.1
statsmodels: 0.6.1
IPython: 4.2.0
sphinx: 1.3.1
patsy: 0.3.0
dateutil: 2.4.2
pytz: 2015.4
bottleneck: 1.0.0
tables: 3.2.0
numexpr: 2.4.3
matplotlib: 1.4.3
openpyxl: 1.8.5
xlrd: 0.9.3
xlwt: 1.0.0
xlsxwriter: 0.7.3
lxml: 3.4.4
bs4: 4.3.2
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.0.5
pymysql: None
psycopg2: None

**Comment by TomAugspurger** [comment]
Pandas defines an `eval` function, which clobbers `__builtin__.eval` when you `import *`. You'd be better of using a qualified import `import pandas as pd`
