### ISSUE TITLE
Adding 'String search filter' functionality

### ISSUE THREAD

**Issue by shivam6294** [pydata/pandas#13498]
Hey everyone,

I was working on a project that involves working with data acquired via the world bank pandas api (i.e. `pandas.io.wb`). This library has a function called `pandas.io.wb.search(str)` which is very useful. In data transformation terms, it's basically does this- given a string 's', filter the dataframe by retaining only the tuples where a string match occurs with the given string 's'.

This operation occurs in my workflow on a regular basis, and I was wondering if anyone else feels the need to have this function natively in pandas. Would be a huge time saver in my opinion!

Was thinking of a function that looks like this:
`DataFrame.search(search_str, is_ignore_case=True, is_match_full_word=False, **kwargs)`

Would love to hear from the community! :)

**Comment by TomAugspurger** [comment]
Could you make a small example (with data) of what this would look like? IIUC you want to filter the DataFrame to the rows where *any* column contains a string `s`?

**Comment by jreback** [comment]
This seems very duplicative of ``Series.str`` functionaility with boolean indexing. http://pandas.pydata.org/pandas-docs/stable/text.html

**Comment by TomAugspurger** [comment]
That's my thought as well. I'd say a user-defined helper method and `DataFrame.apply` + boolean indexing is the way to go, not a dedicated `search` method.

**Comment by shivam6294** [comment]
Oh yea, that sounds like a good solution. Apologies, didn't come across that earlier! :)
