### ISSUE TITLE
DOC: better warning on chained resample(...)

### ISSUE THREAD

**Issue by chris-b1** [pydata/pandas#13520]
#### Code Sample, a copy-pastable example if possible

```python
In [49]: df = pd.DataFrame({'a': 1.}, index=pd.date_range('2014-01-01', '2015-12-31'))

In [50]: df.resample('M').pct_change()
FutureWarning: .resample() is now a deferred operation
use .resample(...).mean() instead of .resample(...)
  if __name__ == '__main__':
Out[50]: 
              a
2014-01-31  NaN
<snip>
```
#### Expected Output
no warning

#### output of ``pd.show_versions()``

```
INSTALLED VERSIONS
------------------
commit: None
python: 2.7.11.final.0
python-bits: 64
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None

pandas: 0.18.1
nose: 1.3.7
pip: 8.1.0
setuptools: 20.2.2
Cython: 0.22.1
numpy: 1.10.4
scipy: 0.16.0
statsmodels: 0.6.1
xarray: None
IPython: 4.0.3
sphinx: 1.2.3
patsy: 0.3.0
dateutil: 2.4.2
pytz: 2015.7
blosc: None
bottleneck: 1.0.0
tables: 3.2.2
numexpr: 2.5
matplotlib: 1.5.1
openpyxl: 2.0.2
xlrd: 0.9.3
xlwt: 1.0.0
xlsxwriter: 0.7.3
lxml: 3.4.4
bs4: 4.3.2
html5lib: 0.999
httplib2: 0.9.2
apiclient: 1.5.0
sqlalchemy: 1.0.5
pymysql: None
psycopg2: None
jinja2: 2.8
boto: 2.38.0
pandas_datareader: 0.2.0
```

**Comment by chris-b1** [comment]
Actually, this isn't spurious - what I meant to write is this.  I'll leave this open - I think the warning could be better, to make it really clear that the `mean` of the data is being taken.

`df.resample('M').last().pct_change()`

**Comment by jorisvandenbossche** [comment]
Do you have a suggestion for a better warning? (PR's welcome :-))

> `df.resample('M').last().pct_change()`

It's not fully clear what you mean with this

**Comment by chris-b1** [comment]
I'll do a PR, what I want it to say is (in essence, hopefully in less words) - 

```
.resample() is a deferred operation.  You used that deferred object as if it were a {klass} - this materializes the deferred object by taking the mean() of each date group, which is deprecated behavior.  Update your code <...>
```

**Comment by jreback** [comment]
yes this is mainly for back-compat.

basically in < 0.18.0 you should have been doing

```
df.resample('M', how='mean').pct_change()
```
and so in >= 0.18.0 you implicity get this. It IS correct actually. I think the warning *could* also include the deferred op reference (e.g. ``pct_change()``) I suppose, BUT the warning actually comes out before.

You might have a look at ``Resampler.plot()``.
