### ISSUE TITLE
groupby on single col df results in ValueError on Master, works on 0.18.1

### ISSUE THREAD

**Issue by alan-wong** [pydata/pandas#13530]
On 0.18.1 the following works without error

```
df = pd.DataFrame({'a':list('abssbab')})
df.groupby('a').count()

```

this results in an empty df:
```
Out[255]:
Empty DataFrame
Columns: []
Index: [a, b, s]
```

On Master it results in an error see related: https://github.com/pydata/pandas/issues/13393

**Comment by jorisvandenbossche** [comment]
Hmm, it now *does* work on master:

```
In [1]: df = pd.DataFrame({'a':list('abssbab')})

In [2]: df.groupby('a').count()
Out[2]:
Empty DataFrame
Columns: []
Index: [a, b, s]

In [3]: pd.__version__
Out[3]: '0.18.1+156.g3944a36'
```

I fetched an rebuilt in the meantime, so maybe my pandas master was not built correctly when I tested that. 

Anyway, the empty frame is the correct result I think, so we could add a test for this. Do you want to do a PR for this?

**Comment by alan-wong** [comment]
Wish I could but I can't compile pandas on my dev machine due to compiler issues

**Comment by jorisvandenbossche** [comment]
@alan-wong If you want tro try to solve those issues and have questions about that, just ask! (but better on https://gitter.im/pydata/pandas, that's a better medium for this instead in an issue)

**Comment by alan-wong** [comment]
@jorisvandenbossche thanks for the link I was completely unaware of that channel I'll join now

**Comment by sinhrks** [comment]
Will add tests and close this.
