### ISSUE TITLE
[Feature Request] Pandas.Series.info

### ISSUE THREAD

**Issue by dragonator4** [pydata/pandas#13540]
It would be great if Pandas Series got an info method, like Pandas DataFrame. My main interest is to find out memory usage.

**Comment by jreback** [comment]
http://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.memory_usage.html?highlight=memory_usage#pandas.Series.memory_usage

**Comment by jreback** [comment]
duplicate of https://github.com/pydata/pandas/issues/5167

**Comment by dragonator4** [comment]
Cool. #5167 did not turn up in a Google search. Sorry for the duplicate.
