### ISSUE TITLE
Dont do selection by callable if not wanted

### ISSUE THREAD

**Issue by Chaoste** [pydata/pandas#13558]
#### Copy-pastable Code Sample
```python
import pandas as pd
import pandas.util.testing as tm

class myClass1:
    def __call__(self):
        return "Result 1"
    def __str__(self):
        return "Class 1"

class myClass2:
    def __call__(self):
        return "Result 2"
    def __str__(self):
        return "Class 2"

obj1 = myClass1()
obj2 = myClass2()
df = pd.DataFrame([], index=[0], columns=[obj1, obj2])
 # Throws error because new pandas version wants to select by callable
df[obj1] = obj1()
df[obj2] = obj2()
```
#### Expected Output
```python
expected = pd.DataFrame([["Result 1", "Result 2"]], columns=[obj1, obj2])
tm.assert_frame_equal(df, expected)
```

#### How I fixed the test for the moment
```python
class myClass1:
    def __call__(self, *args):
        if args:
            return self
        return "Result 1"
    def __str__(self):
        return "Class 1"

class myClass2:
    def __call__(self, *args):
        if args:
            return self
        return "Result 2"
    def __str__(self):
        return "Class 2"
```

If pandas invokes a callable object it passes the frame itself as a parameter. Because i dont need arguments for my call function i can prevent this call by checking if a argument is passed. Is there a better way of doing this or can you add an option so i can disable the new behavior.

#### output of ``pd.show_versions()``
```python
commit: None
python: 3.4.3.final.0
python-bits: 32
OS: Windows
OS-release: 8
machine: AMD64
processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None

pandas: 0.18.1
nose: None
pip: 8.1.2
setuptools: 19.6.2
Cython: None
numpy: 1.11.0
scipy: 0.16.1
statsmodels: None
xarray: None
IPython: 4.2.0
sphinx: 1.4.1
patsy: None
dateutil: 2.5.3
pytz: 2016.4
blosc: None
bottleneck: None
tables: None
numexpr: None
matplotlib: 1.5.1
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: 4.4.1
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.8
boto: None
pandas_datareader: None
```

**Comment by sinhrks** [comment]
Thanks for the report. ``__setitem__`` is now fixed not to apply callable. Can u check #13516 covers your use case?

**Comment by jorisvandenbossche** [comment]
@sinhrks I don't think this is solved by that. The PR was to not executes the values that are stored (RHS, so to store callables in the dataframe), while here it is the key that should not be executed.

I don't think there is any solution for this. Pandas will never know whether a callable inside `[]` should be executed or should be used as label without executing (unless we provide an option to disable the executing of keys inside [])

**Comment by sinhrks** [comment]
Ah correct. I think options are:

1. enclose ``_apply_if_callable`` with ``try-except`` 
2. check if key is a function, not callable class

Though using  ``Index`` containing custom classes is not very performance efficient.

**Comment by jreback** [comment]
I guess option 1 is fine or just close as non supported

this is abuse of pandas by passing in callables that behave differently with args or not - very odd, and not idiomatic nor pythonic 

honestly just close and user beware (unless it's a trivial fix)

**Comment by sinhrks** [comment]
@jreback it's true, added option 3 (not support)

CC @jorisvandenbossche @shoyer

**Comment by shoyer** [comment]
I would pick the "not support" option 3. Adding complex logic to attempt to fall back gracefully here would be un-Pythonic.

**Comment by jorisvandenbossche** [comment]
I would also vote to not do any additional work in pandas to support this. 
@Chaoste you can of course keep using your current workaround (checking the args)
