### ISSUE TITLE
Deprecation of Panel4D/PanelND

### ISSUE THREAD

**Issue by jorisvandenbossche** [pydata/pandas#13564]
Related to https://github.com/pydata/pandas/issues/13563 (deprecation of Panels), we could/should also deprecate Panel4D / PanelND. 
(xref https://github.com/pydata/pandas/issues/5049)

Deprecating Panel4D/ND could probably be done sooner than deprecating Panels (e.g. actually deprecating in 0.19.0 ?)

**Comment by jorisvandenbossche** [comment]
cc @pydata/pandas

**Comment by wesm** [comment]
I'm very in favor of this. I will leave some comments on #13563

**Comment by jorisvandenbossche** [comment]
Let's do this in 0.19.0 then
