### ISSUE TITLE
Series.str.zfill() doesn't check type

### ISSUE THREAD

**Issue by toobaz** [pydata/pandas#13598]
#### Code Sample, a copy-pastable example if possible

```
In [5]: pd.Series(['a', 'b']).str.zfill('hi')
Out[5]: 
0   NaN
1   NaN
dtype: float64

```

#### Expected Output

A ``ValueError``.

#### output of ``pd.show_versions()``

```

In [3]: pd.show_versions()

INSTALLED VERSIONS
------------------
commit: a63bd12529ff309d957d714825b1753d0e02b7fa
python: 3.5.1.final.0
python-bits: 64
OS: Linux
OS-release: 4.5.0-2-amd64
machine: x86_64
processor: 
byteorder: little
LC_ALL: None
LANG: it_IT.utf8
LOCALE: it_IT.UTF-8

pandas: 0.18.1+174.ga63bd12
nose: 1.3.7
pip: 1.5.6
setuptools: 18.4
Cython: 0.23.4
numpy: 1.10.4
scipy: 0.16.0
statsmodels: 0.8.0.dev0+111ddc0
xarray: None
IPython: 5.0.0.dev
sphinx: 1.3.1
patsy: 0.3.0-dev
dateutil: 2.2
pytz: 2012c
blosc: None
bottleneck: 1.1.0dev
tables: 3.2.2
numexpr: 2.5
matplotlib: 1.5.1
openpyxl: None
xlrd: 0.9.4
xlwt: 1.1.2
xlsxwriter: 0.7.3
lxml: None
bs4: 4.4.0
html5lib: 0.999
httplib2: 0.9.1
apiclient: 1.5.0
sqlalchemy: 1.0.11
pymysql: None
psycopg2: None
jinja2: 2.8
boto: 2.38.0
pandas_datareader: 0.2.1

```

**Comment by jreback** [comment]
yep that's an error

**Comment by sinhrks** [comment]
Rather than adding type check logics on everywhere, adding a dummy call (like `` " ".zfill(width)`` may be easier.

**Comment by jreback** [comment]
not sure about that. Most strings can only accept string-likes, OR integers. Having a couple of common routines might help readablity.

``_assure_string``, ``_assure_integer``

**Comment by sahildua2305** [comment]
@jreback I'd like to fix this one as well. Can I go ahead and put a check in `zfill` or should I create separate routine as you mentioned?

**Comment by jreback** [comment]
I think make a separate check

**Comment by sahildua2305** [comment]
Is there any place where such common routines are kept? If not, where should I keep this one?
