### ISSUE TITLE
Resampler: IPython 5.0 triggers wrong FutureWarning

### ISSUE THREAD

**Issue by jorisvandenbossche** [pydata/pandas#13618]
With the latest IPython:

```
In [1]: rng = pd.date_range('20130101', periods=10, freq='T')
   ...: ts = pd.Series(np.arange(len(rng)), index=rng)

In [3]: r = ts.resample('2T')

In [4]: r
Out[4]: c:\users\vdbosscj\scipy\ipython-joris\IPython\utils\dir2.py:65: FutureWa
rning: .resample() is now a deferred operation
use .resample(...).mean() instead of .resample(...)
  canary = getattr(obj, '_ipython_canary_method_should_not_exist_', None)
DatetimeIndexResampler [freq=<2 * Minutes>, axis=0, closed=left, label=left, con
vention=start, base=0]

In [5]: import IPython

In [6]: IPython.__version__
Out[6]: '5.0.0'

In [7]: pd.__version__
Out[7]: '0.18.1+184.g15c2a3a'
```

while using IPython 4.2:

```
In [1]: rng = pd.date_range('20130101', periods=10, freq='T')

In [2]: ts = pd.Series(np.arange(len(rng)), index=rng)

In [3]: r = ts.resample('2T')

In [4]: r
Out[4]: DatetimeIndexResampler [freq=<2 * Minutes>, axis=0, closed=left, label=l
eft, convention=start, base=0]

In [5]: import IPython

In [6]: IPython.__version__
Out[6]: '4.2.0'

In [7]: pd.__version__
Out[7]: '0.18.1+184.g15c2a3a'
```

**Comment by jorisvandenbossche** [comment]
@takluyver This seems to be related to https://github.com/ipython/ipython/pull/9289 (previously, it was first checked if `method` is a callable, and only then it was checked if it could retrieve a non-existing attribute, while now the callable check is moved to the end of `get_real_method`). 
The problem is that the deprecation warning is only triggered once you "do" something with it, and now it is triggered by displaying its repr

**Comment by takluyver** [comment]
That's unfortunate. But if our check for the canary attribute triggers this, won't our checks for `_repr_pretty_`, `_repr_json_`, etc. also trigger it?

**Comment by jorisvandenbossche** [comment]
Apparently not. Where are those checks in the IPython code?

**Comment by takluyver** [comment]
`IPython.core.formatters` - they're somewhat hidden in infrastructure, but if you search for `print_method` in that module, it should be possible to work out what's going on.

**Comment by jorisvandenbossche** [comment]
Ah, I was in a terminal, so I suppose there only the plain text displayer will be used? 
If I try it in a notebook, but using IPython 4.2, the same issue already shows up

**Comment by takluyver** [comment]
I thought the same machinery would check for `_repr_pretty_` even in the terminal, but maybe it's done a bit differently.

**Comment by jorisvandenbossche** [comment]
@takluyver We solved it at our side! (at least, @chris-b1  did :-) )
