### ISSUE TITLE
Add option to use Standard SQL dialect in BigQuery

### ISSUE THREAD

**Issue by RoyalTS** [pydata/pandas#13615]
BigQuery now sports a SQL dialect that's compatible with the 2011 SQL standard. Queries are still run using BigQuery's Legacy SQL dialect at the moment (see https://cloud.google.com/bigquery/sql-reference/enabling-standard-sql) but they may soon switch to Standard SQL by default. `pandas.io.gbq.read_gbq()` should therefore have an argument that determines the SQL dialect that's used to run the query.

**Comment by jorisvandenbossche** [comment]
cc @parthea @aaront @jacobschaer
