### ISSUE TITLE
COMTRADE Import

### ISSUE THREAD

**Issue by idahogray** [pydata/pandas#13620]
I am curious if there would be any interest in having COMTRADE import functionality in core pandas. This is a file format used to record electrical transient measurements in a power system. It is defined by [IEEE C37.111](https://en.wikipedia.org/wiki/Comtrade). I have an implementation that reads the files and creates a pandas dataframe. I would be willing to devote some time to creating a read_comtrade() method in pandas if there is interest. Otherwise, I will just create a third-party library.

**Comment by TomAugspurger** [comment]
Seems a bit too specific for inclusion in pandas. Reminds me of the root file format (used pretty much exclusively by physicists AFAICT). xref https://github.com/pydata/pandas/issues/9378 which didn't really get settled.

**Comment by jorisvandenbossche** [comment]
Indeed, I agree with @TomAugspurger. There are very many possible formats that could be included in pandas, so we have to limit the scope of core pandas to keep it manageable. 
But, I certainly want to encourage you just make a package of it, and we can certainly highlight it in the docs as third-party extensions!

**Comment by idahogray** [comment]
Great, thanks for the feedback. I will close this issue and create a third-party library.

**Comment by jsgaleano** [comment]
i'm very interested in seeing this application
