### ISSUE TITLE
DOC/BLD: IPython 5.0 breaks doc building

### ISSUE THREAD

**Issue by jreback** [pydata/pandas#13639]
https://travis-ci.org/pydata/pandas/jobs/144343193

@jorisvandenbossche 
@TomAugspurger 
@sinhrks 

I just restarted the build, but failed the same way. 

version change?

**Comment by jorisvandenbossche** [comment]
Aha, I suppose IPython 5.0 has landed in the conda repo's :-) 
And apparantly that breaks the ipython directive  ..

**Comment by jorisvandenbossche** [comment]
Pinned it to 4.x for now: https://github.com/pydata/pandas/commit/06103dd7735335e51fcd77a36b2e8a714286a059 
Will investigate 5.0 later

**Comment by jreback** [comment]
https://travis-ci.org/pydata/pandas/jobs/144416030

:<

**Comment by jorisvandenbossche** [comment]
Ah, sorry, when you use that on the command line (conda install ipython=4) it works .. (thought of quickly fixing it, thought wrongly :-))

**Comment by jorisvandenbossche** [comment]
We should pin it to the exact version then (4.2.0)

**Comment by jorisvandenbossche** [comment]
Closed by #14004
