### ISSUE TITLE
`df.to_hdf(...format='table')` writes in different format than I'd expect, having used pytables before.

### ISSUE THREAD

**Issue by moritz-lotze** [pydata/pandas#13651]
I'm dissatisfied with the current way `DataFrame.to_hdf(...format='table')` works. Take this simple example:
```python
import numpy as np
import pandas as pd
import tables

data = {
    'foo': np.zeros(5, dtype=float),
    'bar': np.ones(5, dtype=float),
    'baz': 2 * np.ones(5, dtype=float),
}
df = pd.DataFrame.from_dict(data)
df.to_hdf('bla.h5', '/mu', mode='a', format='table',
          complevel=5, complib='zlib', fletcher32=True)
```

Now if we inspect the file with pytables, there are some issues with this:

```
In [1]: h5 = tb.open_file('bla.h5')
In [2]: h5.root.mu
Out[2]:
/mu (Group) ''
  children := ['table' (Table)]

In [3]: h5.root.mu.table
Out[3]:
/mu/table (Table(5,), shuffle, zlib(5)) ''
  description := {
  "index": Int64Col(shape=(), dflt=0, pos=0),
  "values_block_0": Float64Col(shape=(3,), dflt=0.0, pos=1)}
  byteorder := 'little'
  chunkshape := (2048,)
  autoindex := True
  colindexes := {
    "index": Index(6, medium, shuffle, zlib(1)).is_csi=False}

In [4]: h5.root.mu.table.dtype
Out[4]: dtype([('index', '<i8'), ('values_block_0', '<f8', (3,))])
```

I've been using pytables + numpy so far to write Dataframes / structured arrays to HDF5 Tables. Compared to that, the pandas way of writing tables has 2 issues:

- What I'd have expected from the above example is that it'd create a table (not a group) called `mu` sitting right at the root node. Instead, it uses the `mu` as _Groupname_, and names the table itself just `table`, which is not exactly informing.
- The Table datatype does not hold the full information. Since all the Dataframe columns I passed are float, it just creates a _single table column_ holding 3-tuples. But I'd like it to create 3 separate Float columns, with the column names reflecting `DataFrame.columns`.

#### Workaround
I've been circumventing this issue so far by using `Dataframe.to_records()` to convert it to a structured numpy array & then use pytables directly to write the table to disc. This works without issues.
I'll whip up a Pull Request later I suppose.

#### output of ``pd.show_versions()``

```
[?1034h
INSTALLED VERSIONS
------------------
commit: None
python: 2.7.8.final.0
python-bits: 64
OS: Linux
OS-release: 2.6.32-573.12.1.el6.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

pandas: 0.18.1
nose: 1.3.7
pip: 8.1.2
setuptools: 21.0.0
Cython: 0.24
numpy: 1.11.1
scipy: 0.17.1
statsmodels: None
xarray: None
IPython: 4.2.0
sphinx: None
patsy: None
dateutil: 2.5.3
pytz: 2016.4
blosc: None
bottleneck: None
tables: 3.2.3.1
numexpr: 2.6.0
matplotlib: 1.5.1
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.8
boto: None
pandas_datareader: None

```

**Comment by jreback** [comment]
for the 1st 'issue': this is an implementation detail facilitiation multiple meta-data at a single level. furthermore this has existed many years like this. finally, I don't see any reason why you think changing the actual storage representation is better.

for the 2nd 'issue', simple read the documentation [here](http://pandas-docs.github.io/pandas-docs-travis/io.html#query-via-data-columns) about how to do this
