### ISSUE TITLE
Obtaining options data from yahoo is broken

### ISSUE THREAD

**Issue by rajanshah** [pydata/pandas#13667]
I am not sure, but it appears that obtaining options data from yahoo is broken as it results into following error at the end.

#### Code Sample, a copy-pastable example if possible

from pandas.io.data import Options
aapl = Options('aapl', 'yahoo')
data = aapl.get_all_data()

#### Expected Output

AAPL options data for near-term expiry dates

#### output of ``pd.show_versions()``

pandas: 0.18.1+204.gd7c028d
pandas_datareader: 0.2.1

#### output of self._get_expiry_dates()

pandas/io/data.py in _get_expiry_dates_and_links(self)
   1191
   1192         if len(expiry_dates) == 0:
   1193             raise RemoteDataError('Data not available')
   1194
   1195         expiry_links = dict(zip(expiry_dates, links))

RemoteDataError: Data not available

**Comment by jorisvandenbossche** [comment]
@rajanshah the `io.data` module is deprecated in pandas and moved to `pandas-datareader`. Can you report the issue over there? (https://github.com/pydata/pandas-datareader/issues) Thanks!

**Comment by jorisvandenbossche** [comment]
Although it seems the issue is already reported there: https://github.com/pydata/pandas-datareader/issues/212
