### ISSUE TITLE
Keyerror if set_index list

### ISSUE THREAD

**Issue by jesrael** [pydata/pandas#13685]
Sample:

    import pandas as pd
    import numpy as np
    
    df = pd.DataFrame({'A':[1,2],
                        'B':[3,4],
                        'C':[5,6]}, index=['a','b'])
    
    print (df)
       A  B  C
    a  1  3  5
    b  2  4  6

This works nice:
    
    L = ['c','d']
    df = df.set_index(np.array(L))
    print (df)
       A  B  C
    c  1  3  5
    d  2  4  6

    df = df.set_index(pd.Index(L))
    print (df)
       A  B  C
    c  1  3  5
    d  2  4  6

But if check [docs](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.set_index.html) this can works too, but  **KeyError**:

    df = df.set_index(L)
    KeyError: 'c'

It is also in [SO](http://stackoverflow.com/questions/38421170/cant-set-index-of-a-pandas-data-frame-getting-keyerror).

    print (pd.show_versions())
    INSTALLED VERSIONS
    ------------------
    commit: None
    python: 3.5.1.final.0
    python-bits: 64
    OS: Windows
    OS-release: 7
    machine: AMD64
    processor: Intel64 Family 6 Model 42 Stepping 7, GenuineIntel
    byteorder: little
    LC_ALL: None
    LANG: sk_SK
    
    pandas: 0.18.1
    nose: 1.3.7
    pip: 8.1.1
    setuptools: 20.3
    Cython: 0.23.4
    numpy: 1.10.4
    scipy: 0.17.0
    statsmodels: None
    xarray: None
    IPython: 4.1.2
    sphinx: 1.3.1
    patsy: 0.4.0
    dateutil: 2.5.1
    pytz: 2016.2
    blosc: None
    bottleneck: 1.0.0
    tables: 3.2.2
    numexpr: 2.5
    matplotlib: 1.5.1
    openpyxl: 2.3.2
    xlrd: 0.9.4
    xlwt: 1.0.0
    xlsxwriter: 0.8.4
    lxml: 3.6.0
    bs4: 4.4.1
    html5lib: None
    httplib2: None
    apiclient: None
    sqlalchemy: 1.0.12
    pymysql: None
    psycopg2: None
    jinja2: 2.8
    boto: 2.39.0
    pandas_datareader: None
    None

**Comment by jreback** [comment]
this is as expected 

you can set_index with a same length Index but not a list otherwise it's ambiguous 

you normally would not do this and simply assign

df.index which is the idiomatic way

i suppose he docs could be expanded but they are correct
