### ISSUE TITLE
Broken link in wiki 

### ISSUE THREAD

**Issue by dhpaulino** [pydata/pandas#13707]
The 

> Download zipped PWT data and calculate 5yr averages

 link is bronken in the cookbook section of the wiki

**Comment by sinhrks** [comment]
Thx for the report. It looks out of date, shall we delete the page?

Now we have cookbook on official doc:

- http://pandas.pydata.org/pandas-docs/stable/cookbook.html

**Comment by sinhrks** [comment]
Let me remove the wiki if there is no objection within few days.

**Comment by jorisvandenbossche** [comment]
Yes, that page can be deleted I think

**Comment by sinhrks** [comment]
thx, done.
