### ISSUE TITLE
pd.merge_asof() matches out of tolerance when timestamps are duplicated

### ISSUE THREAD

**Issue by chrisaycock** [pydata/pandas#13709]
This is a continuation of #13695.

Starting with the original DataFrames from that issue:

```
df1 = pd.DataFrame({'time':pd.to_datetime(['2016-07-15 13:30:00.030']), 'username':['bob']})
df2 = pd.DataFrame({'time':pd.to_datetime(['2016-07-15 13:30:00.000', '2016-07-15 13:30:00.030']), 'version':[1, 2]})
```

I now get the null:

```
In [82]: pd.merge_asof(df1, df2, on='time', allow_exact_matches=False, tolerance=pd.Timedelta('10ms'))
Out[82]:
                     time username  version
0 2016-07-15 13:30:00.030      bob      NaN
```

However, if I change the first DataFrame to have duplicate timestamps:

```
df1 = pd.DataFrame({'time':pd.to_datetime(['2016-07-15 13:30:00.030', '2016-07-15 13:30:00.030']), 'username':['bob', 'charlie']})
```

then the bug reappears:

```
In [85]: pd.merge_asof(df1, df2, on='time', allow_exact_matches=False, tolerance=pd.Timedelta('10ms'))
Out[85]:
                     time username  version
0 2016-07-15 13:30:00.030      bob        1
1 2016-07-15 13:30:00.030  charlie        1
```

This is in pandas version 0.18.0+418.gc46dcfa.

**Comment by chrisaycock** [comment]
I can take a stab at this. I should dive into the asof internals anyway.

**Comment by jreback** [comment]
great @chrisaycock yeah the fix is trivial, BUT it breaks the full on test, not entirely sure why, so its not exactly right

**Comment by chrisaycock** [comment]
Alright, I've issued a pull request:

https://github.com/pydata/pandas/pull/13836

I just rewrote the Cython logic to compare the factorized keys directly since that was the easiest way forward. Though we don't actually have to factorize the keys at all; we could just compare the timestamps directly, which would be even faster.
