### ISSUE TITLE
read_table raises EmptyDataError when called with filename and engine="c"

### ISSUE THREAD

**Issue by daler** [pydata/pandas#13711]
Hi,

I noticed that `pd.read_table` raises EmptyDataError, but only when using a filename rather than StringIO and when `engine="c"`.

Possibly related to #13652?

#### Code Sample, a copy-pastable example if possible
```python
import pandas as pd
from io import StringIO

s = 'a\tb\tc\n1\t2\t3\n'

with open('a.tsv', 'w') as fout:
    fout.write(s)

for label in ('StringIO', 'filename'):
    for engine in ('python', 'c'):
        print('input={}, engine={}'.format(label, engine))
        if label == 'StringIO':
            data = StringIO(s)
        else:
            data = 'a.tsv'
        print(pd.read_table(data, engine=engine))
```

Output:
```
input=StringIO, engine=python
   a  b  c
0  1  2  3
input=StringIO, engine=c
   a  b  c
0  1  2  3
input=filename, engine=python
   a  b  c
0  1  2  3
input=filename, engine=c

---------------------------------------------------------------------------
EmptyDataError                            Traceback (most recent call last)
...
pandas/parser.pyx in pandas.parser.TextReader.__cinit__ (pandas/parser.c:5214)()

EmptyDataError: No columns to parse from file
```

#### Expected Output
```
input=StringIO, engine=python
   a  b  c
0  1  2  3
input=StringIO, engine=c
   a  b  c
0  1  2  3
input=filename, engine=python
   a  b  c
0  1  2  3
input=filename, engine=c
   a  b  c
0  1  2  3
```

#### output of ``pd.show_versions()``
```
INSTALLED VERSIONS
------------------
commit: None
python: 3.5.2.final.0
python-bits: 64
OS: Linux
OS-release: 3.13.0-24-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

pandas: 0.18.1
nose: 1.3.7
pip: 8.1.2
setuptools: 23.0.0
Cython: 0.24
numpy: 1.11.1
scipy: 0.17.1
statsmodels: 0.6.1
xarray: None
IPython: 5.0.0
sphinx: 1.4.1
patsy: 0.4.1
dateutil: 2.5.3
pytz: 2016.4
blosc: None
bottleneck: 1.1.0
tables: 3.2.2
numexpr: 2.6.0
matplotlib: 1.5.1
openpyxl: 2.3.2
xlrd: 1.0.0
xlwt: 1.1.2
xlsxwriter: 0.9.2
lxml: 3.6.0
bs4: 4.4.1
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.0.13
pymysql: None
psycopg2: None
jinja2: 2.8
boto: 2.40.0
pandas_datareader: None
```

**Comment by gfyoung** [comment]
1) Your `pandas` version is `0.18.1`, so you couldn't have picked up that PR, which is for `0.19.0`

2) I cannot reproduce this, even with the version of `pandas` that you are using or with `master`

~~~
INSTALLED VERSIONS
------------------
commit: None
python: 3.5.1.final.0
python-bits: 64
OS: Linux
OS-release: 3.19.0-65-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8

pandas: 0.18.1
nose: 1.3.7
pip: 8.1.2
setuptools: 23.0.0
Cython: 0.24
numpy: 1.11.1
scipy: 0.17.1
statsmodels: 0.6.1
xarray: None
IPython: 4.2.0
sphinx: None
patsy: 0.4.1
dateutil: 2.5.3
pytz: 2016.4
blosc: None
bottleneck: None
tables: None
numexpr: None
matplotlib: 1.5.1
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: 4.4.1
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: None
pymysql: None
psycopg2: 2.6.1 (dt dec pq3 ext lo64)
jinja2: 2.8
boto: None
pandas_datareader: 0.2.1
~~~

**Comment by daler** [comment]
I just tried this again on multiple machines and can no longer reproduce. My guess is that the original issue was due to unrelated environmental variables. Sorry for having taken up your time with this.

**Comment by gfyoung** [comment]
No worries!  Thanks for bringing it to our attention.  In the future, you could try double checking that the error persists overall multiple runs of the code OR try running your code in different Python environments (conda OR virtualenv would be good for this)

**Comment by daler** [comment]
I actually did, in multiple conda envs. This morning I thought I was going crazy because I couldn't reproduce.

But I figured it out: I can now reproduce the problem *but only on particular mounts*. I have several mounted directories from our cluster, and on 2 of the 7 mounts I see this problem. Local drive works fine, too. So this seems to be hardware specific problem, but one that popped up recently.

You likely won't be able to reproduce yourself, but could you point me to any recent changes in the C parser (for files but not StringIO) that might be affected by something like a laggy NFS? I'm starting a `git bisect`, but given compile times it might take a while to figure out myself.

**Comment by gfyoung** [comment]
Oh!  Okay, this is very useful info, but unfortunately, I cannot point to anything that would directly be affected by a laggy NFS.  You seem to be suggesting that there was a regression: when was this last working for you?

**Comment by daler** [comment]
Digging through all my conda envs and command histories, I've been using 0.17.1, 0.18.0 and 0.18.1 successfully. I'm interpreting this to be a change in hardware such that I'm only seeing the error now, rather than a change in pandas. I'll submit a ticket to the cluster admins to see if anything changed recently.

I confirmed the likely hardware interaction by checking earlier versions: v15.0 gives the same error as above; v14.0 and v13.0 give a different error:

```
  File "/miniconda3/envs/pd-bisect/lib/python3.5/site-packages/pandas-0.14.0-py3.5-linux-x86_64.egg/pandas/io/parsers.py", line 1032, in __init__
    self._reader = _parser.TextReader(src, **kwds)
  File "pandas/parser.pyx", line 483, in pandas.parser.TextReader.__cinit__ (pandas/parser.c:4897)
  File "pandas/parser.pyx", line 605, in pandas.parser.TextReader._get_header (pandas/parser.c:6605)
pandas.parser.CParserError: Passed header=0 but only 0 lines in file
```

Interestingly, in the demo above if I change this line:

```python
print('input={}, engine={}'.format(label, engine))
```
to
```python
print('input={}, engine={}'.format(label, engine))
print(open('a.tsv').read())
```
the file is opened and read correctly even just before the error, as in this output:
```
input=StringIO, engine=python
a	b	c
0	1	2	3

   a  b  c
0  1  2  3
input=StringIO, engine=c
a	b	c
0	1	2	3

   a  b  c
0  1  2  3
input=filename, engine=python
a	b	c
0	1	2	3

   a  b  c
0  1  2  3
input=filename, engine=c
a	b	c
0	1	2	3

...
  File "pandas/parser.pyx", line 523, in pandas.parser.TextReader.__cinit__ (pandas/parser.c:5214)
pandas.io.common.EmptyDataError: No columns to parse from file
```
So even if it's a laggy NFS, the Python side apparently is seeing the file but not the Cython side?

Anyway, if you consider this a bug I'm happy to do any testing you need; otherwise I'll use the `engine="python"` workaround.

**Comment by gfyoung** [comment]
@jreback , @jorisvandenbossche : what are your thoughts on this issue?

**Comment by jreback** [comment]
w/o a reproducible test this is out of pandas control. if you can gin up a test that reproduces w.r.t. your hardware setup, then pls reopen.

**Comment by daler** [comment]
Will do, thanks all.
