### ISSUE TITLE
DEPR/ENH: isleapyear

### ISSUE THREAD

**Issue by jreback** [pydata/pandas#13727]
xref #13706 

should deprecate ``pandas.util.isleapyear``
and impement as an accessort to ``DTI``, ``Timestamp`` and ``.dt``

**Comment by jorisvandenbossche** [comment]
@jreback from https://github.com/pydata/pandas/pull/13706#issuecomment-234097643

> I think is_leapyear is fine

> leapyear is really the common english word (I see though already getting inconsistent as we should really do is_year_leap)?

No native speaker, but the correct word is "leap year" I think? (and seems also the one most used based on google search). 
If that is the case, I think `is_leap_year` is maybe more consistent with the other options?

**Comment by jreback** [comment]
ok that's fine (slightly inconsistent with is_year_* but oh well)
