### ISSUE TITLE
Too many backslashes stripped in documentation generation

### ISSUE THREAD

**Issue by kokes** [pydata/pandas#13738]
I've noticed the generated documentation for [to_csv](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.to_csv.html) strips backslashes in the newline character

> line_terminator : string, default ‘n’

I thought it was a case of slash stripping, but I checked [the code](https://github.com/pydata/pandas/blob/master/pandas/core/frame.py#L1346) and it's double backslashed there - so the doc generation is a bit aggressive. The [IO doc](http://pandas.pydata.org/pandas-docs/stable/io.html#writing-to-csv-format) is fine, [its code](https://github.com/pydata/pandas/blob/master/doc/source/io.rst) is the same - double backslashed.

**Comment by jorisvandenbossche** [comment]
Thanks for reporting. The ``read_csv`` docs seem to have the same problem (http://pandas-docs.github.io/pandas-docs-travis/generated/pandas.read_csv.html) for the `sep` and `delim_whitespace` keywords.

Probably easiest solved by making it raw strings of some of them (`r"..."`). Interested in trying to fix this?

**Comment by shawnheide** [comment]
I looked into this and made the changes to fix it. Just for reference, it also impacted read_table, as it was tied into the docs with read_csv.
