### ISSUE TITLE
DataFrame.quantile and DataFrame.describe Not Handling NaN

### ISSUE THREAD

**Issue by chris-sheehan** [pydata/pandas#13744]
### Code
```python
>>> import numpy as np
>>> import pandas as pd
>>> df = DataFrame([1, 2, 3, np.nan], columns = ['x'])
>>> print df.x.quantile(0.5)
```

...outputs NaN, where would expect it to handle NaN values and return 2.0

### Versions
pandas: 0.18.1
numpy: 1.11.0

In [NumPy 1.10.1](http://docs.scipy.org/doc/numpy/release.html#numpy-1-10-0-release-notes), the behavior of numpy.median and numpy.percentile are changed to not handle NaN...

>>> Median warns and returns nan when invalid values are encountered... Similar to mean, median and percentile now emits a Runtime warning and returns NaN in slices where a NaN is present. To compute the median or percentile while ignoring invalid values use the new nanmedian or nanpercentile functions.

Since pandas.DataFrame uses numpy.percentile for .describe and .quantile, neither handle NaN values when paired with numpy >= 1.10.0.

**Comment by jorisvandenbossche** [comment]
@chris-sheehan Thanks for reporting! This has been fixed in the meantime in the development version. See https://github.com/pydata/pandas/issues/13098
