### ISSUE TITLE
CLN: template hashtable.pyx

### ISSUE THREAD

**Issue by jreback** [pydata/pandas#13786]
use Tempita support to provide templates for routines in ``hashtable.pyx``. Lots of duplicated code by dtype that can easily use fused types, so code generation is needed. Following along the lines of #13716 would be nice.

**Comment by sinhrks** [comment]
I'm going to handle. What do you think adding other dtypes like ``int32``, etc (related to #701?).

**Comment by jreback** [comment]
yes int32/float32 are reasonable (but could be hone later)
