### ISSUE TITLE
DEPR: deprecate Term & Expr in the pd.* namespace

### ISSUE THREAD

**Issue by jreback** [pydata/pandas#13785]
This is imported via ``pandas.io.api``. I think making a sub-class might work that has the deprecation.

This is used internally, just want to remove the external visibility (as not been necessary for quite a few releases).

**Comment by jorisvandenbossche** [comment]
It's still used in the docs: http://pandas-docs.github.io/pandas-docs-travis/io.html#query-via-data-columns and http://pandas-docs.github.io/pandas-docs-travis/io.html#experimental

**Comment by jorisvandenbossche** [comment]
Maybe unrelated, but there is also the `pd.Expr` in the top-level namespace, and I don't think that is used in the docs. Would that also be a candidate for deprecation as a public top-level function?

**Comment by jreback** [comment]
yes both of these should be removed from the ``pd`` namespace

**Comment by jreback** [comment]
I think they need to have a proxy-object to provide the deprecation and then return the current object.

**Comment by jorisvandenbossche** [comment]
or would a subclass work? (in pandas/__init__.py or in io.api.py):

```
class Expr(pandas.computation.expr.Expr)

    def __init__(self, *args, **kwargs):
        warnings.warn(...)
        super(Expr, self).__init__()
```

**Comment by jreback** [comment]
yes a public subclass would work (and leave the current names)

**Comment by jreback** [comment]
closing in favor of #13790
