### ISSUE TITLE
ERR: disallow RangeIndex()

### ISSUE THREAD

**Issue by jreback** [pydata/pandas#13793]
xref #13749 

this is not consistent with other Indexes where we don't allow them to be constructed with no data passed (it can be ``None``), but that's the idea. ``start`` must be not-None.

IOW this should raise ``ValueError``
```
In [3]: pd.RangeIndex()
Out[3]: RangeIndex(start=0, stop=0, step=1)
```

**Comment by sinhrks** [comment]
will send a PR soon. Shouldn't the error be `TypeError` compat with `Index`?

```
pd.Index(None)
# TypeError: Index(...) must be called with a collection of some kind, None was pa
ssed
```

**Comment by jreback** [comment]
yep - was looking at something else
