### ISSUE TITLE
pd.Series.min(skipna=True) is not working on a slice

### ISSUE THREAD

**Issue by d-me-tree** [pydata/pandas#13816]
#### Code Sample, a copy-pastable example if possible
```Python
s = pd.Series(data=[1, 3, datetime(2016,7,27).date(), datetime(2015,7,27).date(), datetime(2017,7,27).date(), np.nan])
s

0             1
1             3
2    2016-07-27
3    2015-07-27
4    2017-07-27
5           NaN
dtype: object


s.iloc[2:]

2    2016-07-27
3    2015-07-27
4    2017-07-27
5           NaN
dtype: object


s.iloc[2:].min(skipna=True)
# ...
# TypeError: can't compare datetime.date to float
```

#### Expected Output
`'2015-07-27'`

#### output of ``pd.show_versions()``
INSTALLED VERSIONS
------------------
commit: None
python: 2.7.11.final.0
python-bits: 64
OS: Darwin
OS-release: 15.6.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8

pandas: 0.18.1
nose: None
pip: 8.1.1
setuptools: 21.2.1
Cython: 0.24
numpy: 1.10.2
scipy: 0.16.1
statsmodels: None
xarray: None
IPython: 4.2.0
sphinx: None
patsy: None
dateutil: 2.5.3
pytz: 2016.4
blosc: None
bottleneck: None
tables: None
numexpr: None
matplotlib: 1.5.1
openpyxl: None
xlrd: 0.9.4
xlwt: None
xlsxwriter: None
lxml: None
bs4: 4.4.1
html5lib: 0.999
httplib2: 0.9.2
apiclient: None
sqlalchemy: 1.0.13
pymysql: 0.6.7.None
psycopg2: 2.6.1 (dt dec pq3 ext)
jinja2: 2.8
boto: None
pandas_datareader: None

**Comment by TomAugspurger** [comment]
I don't think this is related to the`skipna`. If you use either


```python
In [14]: s.min()
```

or

```python
In [14]: s.dropna().min()
```

you get the same exception. It's (correctly) saying that comparing integers and datetimes isn't well defined.

In general you'll be better off with a single datatype per column. Maybe checkout the `pd.to_datetime` method here.

**Comment by jreback** [comment]
we have no choice but to raise in the case of mixed data like this. You should not put actual mixed python objects in a ``Series``; this defeats the entire point of using pandas.
