### ISSUE TITLE
Arithmetic Broadcasting

### ISSUE THREAD

**Issue by raddy** [pydata/pandas#13841]
Okay, so the following "new" syntax is fine.

import pandas as pd
import random as randy
df = pd.DataFrame({'A': range(1000), 'B': randy.sample(range(1000),1000)},\
                  index=randy.sample(pd.date_range('2013-02-01 09:00:00.000000',periods=1e6,freq='U'),1000)).sort_index()

df.sub(df['A'],axis=0)

But, at some point, this has been broken:

df - df['A']

When did this overload change?

**Comment by shoyer** [comment]
This has been deprecated since v0.8 and was removed in v0.17. See "Removal of automatic time-series broadcasting" in this section:
http://pandas.pydata.org/pandas-docs/version/0.18.1/whatsnew.html#whatsnew-0170-prior-deprecations

**Comment by raddy** [comment]
Hmnn, it's too bad that it doesn't yield an error.

**Comment by shoyer** [comment]
@raddy Agreed. I think that's part of why we left it deprecated for so long.
