### ISSUE TITLE
COMPAT: windows builds breaking after #13788

### ISSUE THREAD

**Issue by jreback** [pydata/pandas#13863]
see [here](https://github.com/pydata/pandas/pull/13788#issuecomment-236409748)

looks like a pointer specification, see #13788

**Comment by jreback** [comment]
cc @pijucha 
cc @ivannz

**Comment by ivannz** [comment]
Sorry, for that. I can make PR fixing this right away.

**Comment by ivannz** [comment]
Unfortunately I am abel to test the build only on win7 64bit virtual machine with anaconda 4.1.1 and python 2.7.12 using the [VC for python2.7](https://www.microsoft.com/en-us/download/details.aspx?id=44266). I can't get VS2015 just yet.

**Comment by ivannz** [comment]
I tested the build on python 3.5 with VS2015 and on python 2.7 with VS2008 as outlined [here](http://pandas.pydata.org/pandas-docs/stable/contributing.html#contributing-windows) and it was successful.

**Comment by jreback** [comment]
we have appveyor CI which does not agree: https://ci.appveyor.com/project/jreback/pandas-465/build/1.0.825

this also fails locally for me as well.

**Comment by ivannz** [comment]
I am terribly sorry, I meant the build of the branch for the PR I am currently making.
