### ISSUE TITLE
Pandas threading crash

### ISSUE THREAD

**Issue by targon** [pydata/pandas#13883]
The following code crashes Pandas 0.18.1 with SIGSEGV:

```
#!/usr/bin/env python3

import threading
import pandas as pd
import numpy as np

def lets_crash():
    t = 0.02 * np.arange(100000)                                                                          
    data = pd.DataFrame({'t': t})
    data['t'] * 1.5  

threads = []
for i in range(100):
    t = threading.Thread(target=let_crash)
    t.daemon = True
    t.start()
    threads.append(t)

for t in threads:
    t.join()
```
(from [http://stackoverflow.com/questions/25782912/pandas-and-numpy-thread-safety](http://stackoverflow.com/questions/25782912/pandas-and-numpy-thread-safety))

Note that the threads run independently from each other, so I don't know how to avoid this short of serialising all access to Pandas.

I tried to get a stack trace, but it seems to crash in several different places.

#### Expected Output

None, but gives SIGSEGV instead

#### output of ``pd.show_versions()``

INSTALLED VERSIONS
------------------
commit: None
python: 3.5.2.final.0
python-bits: 64
OS: Linux
OS-release: 4.4.0-31-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: de_DE.UTF-8

pandas: 0.18.1
nose: None
pip: None
setuptools: None
Cython: None
numpy: 1.11.0
scipy: 0.17.0
statsmodels: None
xarray: None
IPython: 2.4.1
sphinx: None
patsy: None
dateutil: 2.4.2
pytz: 2014.10
blosc: None
bottleneck: None
tables: 3.2.2
numexpr: 2.4.3
matplotlib: 1.5.1
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: 4.4.1
html5lib: 0.999
httplib2: None
apiclient: None
sqlalchemy: 1.0.11
pymysql: None
psycopg2: 2.6.1 (dt dec pq3 ext lo64)
jinja2: None
boto: None
pandas_datareader: None

I can also reproduce the bug with python 2.7.12, and also with pandas 0.17.

**Comment by jreback** [comment]
http://pandas.pydata.org/pandas-docs/stable/whatsnew.html#v0-18-0-march-13-2016

try a different version of ``numexpr``; 2.4.4 is known buggy for threading, its possible 2.4.3 is as well.

**Comment by jreback** [comment]
actually that's a different bug; numexpr is not threadsafe < 2.5 (and that's what's causing the crash).

**Comment by targon** [comment]
Thanks for the quick response! I can confirm that upgrading numexpr (using `pip install numexpr --upgrade`, which installed numexpr 2.6.1 and numpy 1.11.1) resolved the bug.

**Comment by jreback** [comment]
great!
