### ISSUE TITLE
CLN: resource warnings

### ISSUE THREAD

**Issue by jreback** [pydata/pandas#13932]
https://travis-ci.org/pydata/pandas/jobs/150623749

so we have warnings enabled on the 3.5/dev build. Lots of resource warnings....

**Comment by jreback** [comment]
@gfyoung an odd one here.

```
................................./home/travis/build/pydata/pandas/pandas/io/parsers.py:1904: FutureWarning: split() requires a non-empty pattern match.
  yield pat.split(line.strip())
```

**Comment by gfyoung** [comment]
That's due to a `regex` matching the empty string somewhere in one of the tests.  Can try to patch that.

As for the other `ResourceWarnings`, I think it's because files are being closed before being destroyed, but in this instance, not sure why that would be happening given our test construction.

**Comment by jreback** [comment]
these only happen in PY3 fyi.

**Comment by gfyoung** [comment]
Yes, it's because that warning was introduced in Python 3.  Again, not 100% sure why they are occurring, since that implies that the file object is getting deleted before it is closed, and we're using `with` statements everywhere in the tests.
