### ISSUE TITLE
pd.read_clipboard in Jupyter makes python 3.5 crash on windows

### ISSUE THREAD

**Issue by jmarrec** [pydata/pandas#13946]
Disclaimer: I'm not quite sure if the problem is really on pandas' side or on jupyter's.

I have seen #4561 but this isn't the same problem.

#### Code Sample, a copy-pastable example if possible

Given the following code:

```
import pandas as pd
pd.read_clipboard()
```

If I use it in a python file, it works fine.

If I use ipython in cmd.exe, it works fine.

Now if I use it in a Jupyter notebook, it consistently makes my kernel die.

#### output of ``pd.show_versions()``

INSTALLED VERSIONS
------------------
commit: None
python: 3.5.2.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None

pandas: 0.18.1
nose: 1.3.7
pip: 8.1.2
setuptools: 25.1.6
Cython: 0.24.1
numpy: 1.11.1
scipy: 0.18.0
statsmodels: 0.6.1
xarray: None
IPython: 5.0.0
sphinx: 1.3.1
patsy: 0.4.1
dateutil: 2.5.3
pytz: 2016.6.1
blosc: None
bottleneck: None
tables: 3.2.2
numexpr: 2.6.1
matplotlib: 1.5.1
openpyxl: 2.3.2
xlrd: 1.0.0
xlwt: 1.1.2
xlsxwriter: 0.9.2
lxml: 3.6.1
bs4: 4.4.1
html5lib: 0.9999999
httplib2: None
apiclient: None
sqlalchemy: 1.0.13
pymysql: None
psycopg2: None
jinja2: 2.8
boto: 2.40.0
pandas_datareader: 0.2.1

##### Jupyter info:

jupyter                   1.0.0                    py35_3
jupyter_client            4.3.0                    py35_0
jupyter_console           5.0.0                    py35_0
jupyter_core              4.1.0                    py35_0
ipython                   5.0.0                    py35_0
ipython-notebook          4.0.4                    py35_3
ipython-qtconsole         4.0.1                    py35_4
ipython_genutils          0.1.0                    py35_0

**Comment by jreback** [comment]
you should report to jupyter instead

**Comment by jmarrec** [comment]
Maybe you're closing this too hastily.

I did report it to Jupyter as higlighted by the linked issue, and they're saying it's a pandas issue.

**Comment by jreback** [comment]
don't think so. This has existed for several years w/o changes, and it works in the terminal.

**Comment by takluyver** [comment]
I don't know what the issue is, but it seems more likely that Jupyter/IPython is making this code hit some corner case it doesn't usually encounter than that some bug in Jupyter is breaking completely correct ctypes code.

**Comment by jreback** [comment]
![image](https://cloud.githubusercontent.com/assets/953992/17517849/49c124f4-5e13-11e6-8d9a-8bf6217f0767.png)

**Comment by jreback** [comment]
so it could be a windows 10/7 thing.

**Comment by takluyver** [comment]
@jmarrec Do you get this regardless of what's on the clipboard, or does it depend what you copied when you try to use it?

**Comment by jmarrec** [comment]
Yes, whatever I have or don't have (`echo off | clip` to empty the clipboard) it'll crash

**Comment by jvaldiviezo9** [comment]
Hi, I think I locate the error, I can see that this fails in the function def _pasteWindows(): inside pandas\util\clipboard.py

one workaround that I found was to change inside pandas\io\clipboard.py to the following, and there is no more problem

![bug](https://cloud.githubusercontent.com/assets/18518204/19609980/ad89266a-979f-11e6-8038-d3525c950b0f.PNG)

**Comment by aravindsd** [comment]
See Pandas documentation to use **read_clipboard** (Anaconda Package)
It seems pandas read_clipboard need optional dependencies which are not yet compatible with **python 3.5**. I guess that's hindrance for _**read_clipboard**_ 

http://pandas.pydata.org/pandas-docs/stable/install.html#optional-dependencies

![image](https://cloud.githubusercontent.com/assets/19371042/20247366/58a93212-a9f0-11e6-8a5b-a22eb8ba036d.png)

Doesn't have any issue in Python 3.4 (Anaconda Package)
