### ISSUE TITLE
DOC: read_excel() documentation for na_values should show default na values

### ISSUE THREAD

**Issue by bklaas** [pydata/pandas#13967]
I'd like to see read_excel show the same valid information for na_values as read_csv does. This ended up taking a lot of digging to find because it was unclear what the defaults were with read_excel().

#### read_csv() documentation shows the following for na_values
na_values : str or list-like or dict, default None
Additional strings to recognize as NA/NaN. If dict passed, specific per-column NA values. By default the following values are interpreted as NaN: ‘’, ‘#N/A’, ‘#N/A N/A’, ‘#NA’, ‘-1.#IND’, ‘-1.#QNAN’, ‘-NaN’, ‘-nan’, ‘1.#IND’, ‘1.#QNAN’, ‘N/A’, ‘NA’, ‘NULL’, ‘NaN’, ‘nan’.

#### read_excel() documentation does not include default NaN values
na_values : list-like, default None
List of additional strings to recognize as NA/NaN

**Comment by sinhrks** [comment]
Thx for the suggestion. PR is appreciated!

**Comment by souravsingh** [comment]
I wish to work on the issue. How do I start?

**Comment by jorisvandenbossche** [comment]
First, look at the contributing docs (http://pandas.pydata.org/pandas-docs/stable/contributing.html) which explains how to set-up a development environment and to make a pull request. 

Specifically for this change, you can take a look at the `read_csv` docstring, which includes the correct values for `na_values`. So you could just copy the explanation from there.
