### ISSUE TITLE
Feature request:  Save Jupyter rendering of pd.DataFrame as a .png or .pdf

### ISSUE THREAD

**Issue by jolespin** [pydata/pandas#14023]
I've been screenshotting the dataframes from Jupyter in my notes but it would be really cool if you could save the actual renderings.  I looked it up and I think this guy figured out how to do it http://stackoverflow.com/questions/19726663/how-to-save-the-pandas-dataframe-series-data-as-a-figure  

Feature request:

DF = pd.DataFrame(somedata)

DF.to_render(path/to/file, format = "pdf")

or something along those lines to get something like:
![screen shot 2016-08-05 at 8 49 06 am](https://cloud.githubusercontent.com/assets/9061708/17748015/49b460de-646c-11e6-9fa5-ab7472b21b78.png)

**Comment by TomAugspurger** [comment]
Seems out of scope for pandas to me.

That's just HTML, so you can save that to a file with `df.to_html()` and convert it with something like [phantomjs](http://phantomjs.org/screen-capture.html)

**Comment by jreback** [comment]
agreed. out of scope.

**Comment by jolespin** [comment]
@TomAugspurger thanks Ill make a wrapper for it.

**Comment by famargar** [comment]
I think it would be great to have that in pandas. The solution already exist (see above) and the demand for the feature is clearly high (50k views on the two StackOverflow questions on the subject)

**Comment by liu431** [comment]
I see this would be useful as we need the rendered table in the formal writing of a data project.

**Comment by janosh** [comment]
I assume upvotes in a closed issue go unnoticed. So bumping this to see if @famargar's post can sway maintainers' stance here?
