### ISSUE TITLE
0.18.1 to_csv ignoring columns argument

### ISSUE THREAD

**Issue by jonathanlandy** [pydata/pandas#14036]
The issue discussed [here](https://github.com/pydata/pandas/issues/3454) is occurring for me in 0.18.1: The columns optional argument of to_csv is being ignored.

**Comment by jreback** [comment]
you will have to show a self contained example and pd.show_versions() as that issue was fixed 3 yrs ago

**Comment by jonathanlandy** [comment]
Sorry, my mistake -- I was using "cols" as the argument not "columns".  It is indeed working with the latter.
