### ISSUE TITLE
keep consistency in calling to_csv either dataframe or series

### ISSUE THREAD

**Issue by FrankMN** [pydata/pandas#14054]
When I call to_csv of dataframe object, I am not required to explicitly set path parameter. The default one is None and will return a string. I thought the same thing for series object. This time the path parameter becomes explicitly required. I wonder if it is better to keep consistency between them.

**Comment by jreback** [comment]
Can u show an explicit example and pd.show_versions()

**Comment by gfyoung** [comment]
@jreback : There is no need.  @FrankMN is referring to a signature mismatch, which you can see <a href="https://github.com/pydata/pandas/blob/51b20de44fdcb998f25392558e029621e10c451c/pandas/core/series.py#L2536">here</a> and <a href=https://github.com/pydata/pandas/blob/51b20de44fdcb998f25392558e029621e10c451c/pandas/core/frame.py#L1302>here</a>.  IMO we should default `path=None` for `Series`.  This shouldn't be a breaking API change.
