### ISSUE TITLE
Can't install pandas-0.18.1

### ISSUE THREAD

**Issue by ponomarevvl90** [pydata/pandas#14091]
Try to install pandas via pip, but it is failed:
[error.txt](https://github.com/pydata/pandas/files/439154/error.txt)

**Comment by TomAugspurger** [comment]
What OS are on, and what version of pip are you using? We have wheels up now for every platform, so it should be pulling that and not trying to compile the extensions.

**Comment by ponomarevvl90** [comment]
Os: Ubuntu 15.10
pip: pip 8.1.2

**Comment by chris-b1** [comment]
Looks like you're installing into a PyPy environment?  `pandas` only works on CPython

`Complete output from command /home/ponomarev/.virtualenvs/test/bin/pypy `

**Comment by jreback** [comment]
ok so pandas does not support pypy
