### ISSUE TITLE
Kernel dies when exporting large dataframe to json

### ISSUE THREAD

**Issue by iuliacioroianu** [pydata/pandas#14193]
### Problem
The kernel dies when I try to export relatively large data to json. No problems with short test data, it gets exported as it should. Also, exporting a large df to_csv works just fine, but to_json fails. 
These are datasets of either tweets or newspaper articles, so at least one of the fields contains strings of different lengths. 
 
#### Code Sample
>df
[...]
[557807 rows x 25 columns]
df.to_json('data.json')
>It seems the kernel died unexpectedly. Use 'Restart kernel' to continue using this console.

#### output of ``pd.show_versions()``

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.10.final.0
python-bits: 32
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 61 Stepping 4, GenuineIntel
byteorder: little
LC_ALL: None
LANG: en_GB

pandas: 0.16.2
nose: 1.3.7
Cython: None
numpy: 1.9.2
scipy: 0.15.1
statsmodels: None
IPython: 2.4.1
sphinx: 1.3.2
patsy: 0.3.0
dateutil: 2.4.2
pytz: 2015.4
bottleneck: 1.0.0
tables: 3.2.0
numexpr: 2.4.3
matplotlib: 1.4.3
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: 3.4.4
bs4: 4.3.2
html5lib: 0.99999
httplib2: None
apiclient: None
sqlalchemy: 1.0.6
pymysql: None
psycopg2: None

**Comment by jreback** [comment]
you need a more modern version of pandas, we have had 3 major releases since then (17, 18, and 19rc is out now).
