### ISSUE TITLE
to_sql doesn't support decimal types - stored as text in database

### ISSUE THREAD

**Issue by seanv507** [pydata/pandas#14212]
I am using postgresql database

#### Code Sample, a copy-pastable example if possible
a=pd.DataFrame({'a':[decimal.Decimal('0.1'), decimal.Decimal('0.1'), decimal.Decimal('0.1'), decimal.Decimal('0.3')]})

#### Expected Output
conn is sql alchemy connection
 a.to_sql('testdec',conn)
what is produced:
CREATE TABLE testdec
(
  index bigint,
  a text
)
I would have expected the use of decimal type?
#### output of ``pd.show_versions()``

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.11.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: de_DE

pandas: 0.18.0
nose: 1.3.7
pip: 8.1.1
setuptools: 20.3
Cython: 0.23.4
numpy: 1.10.4
scipy: 0.17.0
statsmodels: 0.6.1
xarray: None
IPython: 4.1.2
sphinx: 1.3.5
patsy: 0.4.0
dateutil: 2.5.1
pytz: 2016.2
blosc: None
bottleneck: 1.0.0
tables: 3.2.2
numexpr: 2.5
matplotlib: 1.5.1
openpyxl: 2.3.2
xlrd: 0.9.4
xlwt: 1.0.0
xlsxwriter: 0.8.4
lxml: 3.6.0
bs4: 4.4.1
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.0.12
pymysql: None
psycopg2: 2.5.1 (dt dec pq3 ext)
jinja2: 2.8
boto: 2.39.0

**Comment by jreback** [comment]
we don't support ``decimal`` types in pandas generally, so I woudn't expect this to be supported. you can however, specify the ``dtype`` keyword.
