### ISSUE TITLE
ENH: add "by" attribute to all plot methods

### ISSUE THREAD

**Issue by dacoex** [pydata/pandas#14223]
#### Code Sample, a copy-pastable example if possible

- boxplot has a grouby attribute "by" which makes it easy to plot all months of a year in a facet grid of subplots: http://stackoverflow.com/a/37687386
-  It would be greta to have this also for other plot types such as scatter, line, historgram

I checked and other isssues on subplot & grouby are rather related to histogramms.

This here aims for a quick method how to create subplot facet grid for the same variable(s) on different sections or intervals of the dataframe:
* 1 plot for every year of a multi-year timeseries
* 1 plot for each average day of a full year series

In theory, this would a facet grid of subplots where each plot is made from a column of a 2-d pivot table, e.g. a table with teh 12 months on x-axis and values on x-axis.

#### Expected Output

- https://plot.ly/~MattSundquist/11035.png from http://blog.plot.ly/post/117105992082/time-series-graphs-eleven-stunning-ways-you-can & http://nbviewer.jupyter.org/gist/mkcor/0ee7c73d9ba4c68ddc1a/
- http://i.stack.imgur.com/dGhai.png from http://stackoverflow.com/a/37126436

Similar functionality is provided by [calmap](https://github.com/martijnvermaat/calmap)

==> I hope this suggestion is not beyond the scope of pandas.
--> similar functonality but with less convenience is provided by seaborn
http://stanford.edu/~mwaskom/software/seaborn/generated/seaborn.FacetGrid.html

**Comment by TomAugspurger** [comment]
I think this would be a decent amount of work, for something that seaborn handles well already.

For the specific issue about multiple plots by year, one solution is to use unstuck and subplots

```python
In [18]: import pandas.util.testing as tm

In [19]: ts = tm.makeTimeSeries(nper=1000)

In [20]: ts.index = pd.MultiIndex.from_arrays([ts.index.year, ts.index.month, ts.index.day])

In [21]: ts.unstack(0).plot(subplots=True, layout=(2, 2))
```

**Comment by dacoex** [comment]
OK, agree. 
Thanks for the example. Maybe will add to the cookbook albeit requires still to tweak the x-axis (date). I though that date labels was supported natively by pandas plots.
