### ISSUE TITLE
Faulty nogil assumption in _Py_HashDouble

### ISSUE THREAD

**Issue by deepankarsharma** [pydata/pandas#14238]
Pandas uses _Py_HashDouble as the hash function for hashing floats. () in the 0.17.x and 0.18.x releases. This hash function is used within nogil sections within hashtable.pyx on both these releases. However the definition of this function as implemented on Python 2.x can call into the Python api depending on the values being hashed. This causes crashes if there is another thread using holding the GIL which is executing simultaneously. I see that master no longer uses this hash function. But can this fix be backported for the 0.17.x / 0.18.x branches?

**Comment by jreback** [comment]
this is in 0.18.2 see the fix https://github.com/pydata/pandas/commit/f98b4b541e7a9d1b0d8f6674a84dc10080c2568b

we don't backport fixes

**Comment by deepankarsharma** [comment]
Any eta on when 0.18.2 will be on pypi?

**Comment by jreback** [comment]
0.18.2 was renamed to 0.19.0

0.19.0 is releasing shortly; the rc is available now https://github.com/pydata/pandas/releases/tag/v0.19.0rc1

**Comment by wesm** [comment]
@deepankarsharma we are open to creating maintenance / bugfix / backport-only branches, but at the moment we do not have the committer bandwidth to support this. we would require invested corporate partners to help us do this
