### ISSUE TITLE
TST: 2.7-compat build

### ISSUE THREAD

**Issue by jreback** [pydata/pandas#14276]
https://travis-ci.org/pydata/pandas/jobs/161159735

xref #14208
 
cc @llllllllll 

``np.full_like`` must be newer, can you skip on older builds (this build is with 1.7.1)

**Comment by llllllllll** [comment]
I can change this to `np.full` and pass the index's shape explicitly.

**Comment by jreback** [comment]
thanks

funny thing i thought the idiom was 

.empty
.fill

but .full makes sense

**Comment by llllllllll** [comment]
I will use empty and fill, `full` and `full_like` were added in 1.8.0

**Comment by chris-b1** [comment]
Closed by https://github.com/pydata/pandas/commit/dfb6373b3925ff458e64242584725ff069277d6b
