### ISSUE TITLE
I would like to write a hardcore groupby tutorial

### ISSUE THREAD

**Issue by randomgambit** [pydata/pandas#14296]
Hello

After some thoughts, I think I would be useful for everybody if I wrote some nasty, hardcore groupby tutorial with all the crazy data manipulations I use in my code.

I work in a large company, have a phd in finance/economics and many times I pushed Pandas to the limits with 80GB datasets and others.

To do the best tutorial possible, I would be nice if someone from the community could review my tutorial and possibly improve it a bit. @TomAugspurger would you like to have a look?

Objective: making pandas better!

Thanks guys!

**Comment by TomAugspurger** [comment]
Happy to give feedback when I can, though you might be better off posting to the mailing list so more people can review it. 

I think I'll close this issue for now, though if you come across specific issues with the docs, please raise them. 

One last bit, I don't think your "nasty", "hardcore" analogy adds anything, and is will possibly drive people away.

**Comment by randomgambit** [comment]
haha great. btw by nasty and hardcore i simply means groupby operationa beyond a simple mean by groups 😜

**Comment by JoaoAparicio** [comment]
So, where can we find this?

**Comment by randomgambit** [comment]
hey @joaoaparicio I have to write it up 😱 but I will keep you posted and send it to the mailing list for review! thanks guys and keep up the good work
