### ISSUE TITLE
BUG: DataFrame.align() should throw a ValueError when trying to align a DataFrame with a Series and specifying axis=1

### ISSUE THREAD

**Issue by Khris777** [pydata/pandas#14300]
#### A small, complete example of the issue

```
import pandas as pd
import numpy as np

N = 1000
L = np.random.randn(N)
F = pd.DataFrame({'X':L})
S = pd.Series(L)

X = F.align(S,axis=1)
```

This code should throw `ValueError: No axis named 1 for object type <class 'pandas.core.series.Series'>` just like `S.align(S,axis=1)` would, instead it goes through and creates a huge NxN-sized dataframe filled with nothing but `NaN`. For bigger values of `N` this behaviour leads to `MemoryError`.

#### Output of ``pd.show_versions()``
<details>
python: 2.7.12.final.0
pandas: 0.18.1
</details>

**Comment by jreback** [comment]
how do you *know* that this should not align?

**Comment by jreback** [comment]
The docs explicity show an example of DataFrame & Series.

http://pandas.pydata.org/pandas-docs/stable/basics.html#aligning-objects-with-each-other-with-align

**Comment by Khris777** [comment]
Okay, I think I understand this particular result now, so it's not a bug.

But I have another question:
In the specifications for `align`:

http://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.align.html

http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.align.html

It says 

> axis : allowed axis of the other object, default None

And that is what confuses me.

When I'm doing `S.align(F,axis=1)`, that is aligning a Series with a DataFrame, the _other_ object is a dataframe, yet I get this error `ValueError: No axis named 1 for object type <class 'pandas.core.series.Series'>`.

Why does `F.align(S,axis=1)` on the other hand work if the _other_ object is a Series?

**Comment by jreback** [comment]
``S.align(F,axis=1)``, the axis is the alignment access to align TO, no on ``other``. So this is an error, while the reverse: ``F.align(S, axis=0|1)`` works.
