### ISSUE TITLE
DatetimeIndex.append not working

### ISSUE THREAD

**Issue by httassadar** [pydata/pandas#14306]
#### A small, complete example of the issue

```python
# Your code here
xx = pd.to_datetime(['2000-01-01','2000-02-01'])
xx.append(xx[0])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda\lib\site-packages\pandas\tseries\index.py", line 1058, in append
    return factory(to_concat)
  File "C:\Anaconda\lib\site-packages\pandas\tseries\index.py", line 2240, in <lambda>
    factory_func = lambda x: klass(concat(x), name=name, **kwargs)
ValueError: all the input arrays must have same number of dimensions

# insert works as expected
xx.insert(0, xx[0])
DatetimeIndex(['2000-01-01', '2000-01-01', '2000-02-01'], dtype='datetime64[ns]', freq=None)

```

#### Expected Output
append one item at the end of xx

#### Output of ``pd.show_versions()``

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.12.final.0
python-bits: 64
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 44 Stepping 2, GenuineIntel
byteorder: little
LC_ALL: None
LANG: en_GB

pandas: 0.18.1
nose: 1.3.7
pip: 8.1.0
setuptools: 0.6c11
Cython: 0.21
numpy: 1.10.1
scipy: 0.16.0
statsmodels: 0.6.1
xarray: None
IPython: 5.1.0
sphinx: 1.3.1
patsy: 0.4.0
dateutil: 2.4.2
pytz: 2015.7
blosc: None
bottleneck: None
tables: 3.1.1
numexpr: 2.4.4
matplotlib: 1.4.3
openpyxl: 1.8.5
xlrd: 0.9.3
xlwt: 0.7.5
xlsxwriter: 0.5.7
lxml: 3.5.0
bs4: 4.4.1
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 0.9.7
pymysql: None
psycopg2: None
jinja2: 2.8
boto: 2.32.1
pandas_datareader: None
<details>

</details>

**Comment by chris-b1** [comment]
`append` expects another `Index` (or really an array-like), so to append a single element, you could, for instance, take a length 1 slice.  

Note that in general, appending or inserting single elements to arrays is expensive (full copy each time), so often best to avoid if you can (e.g. use a python list to build up your values, then convert to an `Index`)

```
In [24]: xx.append(xx[0:1])
Out[24]: DatetimeIndex(['2000-01-01', '2000-02-01', '2000-01-01'], dtype='datetime64[ns]', freq=None)

In [25]: pd.DatetimeIndex.append?
Signature: pd.DatetimeIndex.append(self, other)
Docstring:
Append a collection of Index options together

Parameters
----------
other : Index or list/tuple of indices

Returns
-------
appended : Index
Type:      function
```
