### ISSUE TITLE
Expose pandas.json.dump in the public API?

### ISSUE THREAD

**Issue by nzjrs** [pydata/pandas#14321]
I could not find any public documentation for `pandas.json.dump`, so I guess this makes it private? Or is it public and I can depend on it?

Would you consider making this function public, or at least as public as `pandas.json.dumps` which are at least imported into/as `pandas.io.json.dumps`. 

I find the performance of `pandas.json.dump` to be an improvement on the normal json module.

**Comment by jreback** [comment]
The ``.json`` module itself should actually be private (and only expose *some* API functions), so this is not likely to be exposed either. Further it is not completely API compat with the python JSON module (its pretty close in functionaility though).

its based on the same underlying code here: https://pypi.python.org/pypi/ujson
