### ISSUE TITLE
TST: Error when running nosetests pandas on ubuntu 64bit

### ISSUE THREAD

**Issue by MattRijk** [pydata/pandas#14356]
I'm getting this error after I installed pandas and run the tests

```
======================================================================
ERROR: test_readonly_axis_zlib_to_sql (pandas.io.tests.test_packers.TestCompression)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/matt/pandas-mattrijk/pandas/io/tests/test_packers.py", line 738, in test_readonly_axis_zlib_to_sql
    df.to_sql('test', eng, if_exists='append')
  File "/home/matt/pandas-mattrijk/pandas/core/generic.py", line 1200, in to_sql
    chunksize=chunksize, dtype=dtype)
  File "/home/matt/pandas-mattrijk/pandas/io/sql.py", line 460, in to_sql
    pandas_sql = pandasSQL_builder(con, schema=schema, flavor=flavor)
  File "/home/matt/pandas-mattrijk/pandas/io/sql.py", line 530, in pandasSQL_builder
    return SQLDatabase(con, schema=schema, meta=meta)
  File "/home/matt/pandas-mattrijk/pandas/io/sql.py", line 960, in __init__
    meta = MetaData(self.connectable, schema=schema)
TypeError: __init__() got an unexpected keyword argument 'schema'

----------------------------------------------------------------------
Ran 11101 tests in 1117.090s

FAILED (SKIP=255, errors=1)


```

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: 5033a4a799c77fdc7e868a9f332384eabcc332b8
python: 2.7.12.final.0
python-bits: 64
OS: Linux
OS-release: 4.4.0-38-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: None.None

pandas: 0.19.0rc1+39.g5033a4a.dirty
nose: 1.3.7
pip: 8.1.2
setuptools: 27.2.0
Cython: 0.24.1
numpy: 1.11.1
scipy: 0.18.1
statsmodels: None
xarray: None
IPython: 5.1.0
sphinx: 1.4.6
patsy: 0.4.1
dateutil: 2.5.3
pytz: 2016.6.1
blosc: None
bottleneck: 1.1.0
tables: 3.2.3.1
numexpr: 2.6.1
matplotlib: 1.5.3
openpyxl: 2.0.3
xlrd: 1.0.0
xlwt: 1.1.2
xlsxwriter: 0.4.6
lxml: 3.6.4
bs4: 4.2.1
html5lib: 1.0b2
httplib2: None
apiclient: None
sqlalchemy: 0.7.1
pymysql: 0.6.2.None
psycopg2: None
jinja2: 2.8
boto: None
pandas_datareader: None

</details>

**Comment by chris-b1** [comment]
That's a very old version of `sqlalchemy` in the docs we recommend 0.8.1, but don't list a minimum version.  So probably need to document / check a minimum version.

http://pandas.pydata.org/pandas-docs/stable/install.html#optional-dependencies

**Comment by jorisvandenbossche** [comment]
We have 0.7.8 in of the ci requirement files, so as low as that one should be tested. But it seems you are using 0.7.1

**Comment by MattRijk** [comment]
I did requirements_all.txt with anaconda and got 0.7.1 for some reason. I updated sqlalchemy to 0.8.1 and all tests pass

**Comment by gfyoung** [comment]
@jorisvandenbossche , @chris-b1 : Looks like this issue can be closed.
