### ISSUE TITLE
merge_asof timeseries don't preserve categories  Pandas 0.19.0

### ISSUE THREAD

**Issue by existeundelta** [pydata/pandas#14351]
from the timeseries realease example: [http://pandas.pydata.org/pandas-docs/version/0.19.0/whatsnew.html#merge-asof-for-asof-style-time-series-joining](http://pandas.pydata.org/pandas-docs/version/0.19.0/whatsnew.html#merge-asof-for-asof-style-time-series-joining)
making ticker as category:
```python
trades.ticker = trades.ticker.astype('category') 
quotes.ticker = quotes.ticker.astype('category') 

merge = pd.merge_asof(trades, quotes,
                  on='time',
                  by='ticker')
```
#### Expected Output
merge.dtypes
Out[31]:
time        datetime64[ns]
ticker            category
price              float64
quantity             int64
bid                float64
ask                float64

geting :
time        datetime64[ns]
ticker              object
price              float64
quantity             int64
bid                float64
ask                float64

**Comment by chris-b1** [comment]
Yes, this would be nice to support and is essentially a special case of #10409.

**Comment by jreback** [comment]
xref this to the duplicate issue.
