### ISSUE TITLE
DOC: Series.sum skipna= param defaults to None

### ISSUE THREAD

**Issue by jabellcu** [pydata/pandas#14387]
http://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.sum.html

Docs for pandas.Series.sum state that "skipna=None" in the function name, but then reads "skipna : boolean, default True" in the "parameters" section.

**It is not clear whether the default is "None" or "True".** 

Many thanks.

**Comment by chris-b1** [comment]
The default behavior is `skipna=True`, it just happens that the default value for the keyword argument is `None`.

I'm not seeing an obvious reason why the default is `None` - sometimes this is deliberately done to detect whether the argument was passed - but not here.  So you are welcome to try that change and see if anything breaks - it would be here:
https://github.com/pydata/pandas/blob/d98e982ecb0f6b7f3478a63caac34e0be238895c/pandas/core/generic.py#L5602

**Comment by jabellcu** [comment]
I have tested skipna=True instead of setting it to true in the function´s body. I ran the nosetests and nothing seems to break. It seems to me an unnecessary change, though, so I will leave it. Thanks for your answer.
