### ISSUE TITLE
Unexpected Pandas Division Behavior

### ISSUE THREAD

**Issue by ZhijieWang** [pydata/pandas#14395]
Test Code

    import pandas as pd
    import numpy as np
    a = pd.DataFrame(np.random.randint(0,100,size=(100, 4)))
    a.tail(1)/a.head(1)

Expected Behavior:
some float point value

Actual Behavior:

```  
   0   1   2   3
0  NaN NaN NaN NaN
99 NaN NaN NaN NaN
```

Confirmed on OSX python3, Pandas v0.19.0 v0.18.1

**Comment by gfyoung** [comment]
Documentation I think explains this <a href="https://github.com/pydata/pandas/blob/d98e982ecb0f6b7f3478a63caac34e0be238895c/pandas/core/ops.py#L1088">here</a>.  You can see this for yourself by typing `help(a.__div__)`.

**Comment by ZhijieWang** [comment]
@gfyoung thanks for the quick response. And confirmed after checking docs and playing around with reindex.
