### ISSUE TITLE
Support for bimonthly/weekly timerules

### ISSUE THREAD

**Issue by JWCornV** [pydata/pandas#1543]
Any change of getting bi-monthly (1st and 15th) of the month, or bi-weekly (every two weeks) supported?

I could probably do this.

**Comment by dbinetti** [comment]
FWIW, bi-monthly means "every two months"; what you are asking for is more precisely called "semi-monthly".  Also forgive me for the "please-add-this-but-i-can't-write-a-patch" comment, but having bi* (unit * 2) and semi* (unit / 2) frequencies would be helpful in many applications.

**Comment by adrienemery** [comment]
Any word on if this will be included in an upcoming release? If not I can put together a patch for Semi-Monthly.

I propose:

`SM` for Semi-Monthly Month End (15th and last day of month)
`SMS` for Semi-Monthly Month Start (1st and 15th)

**Comment by jreback** [comment]
This would be a straightforward extension. patches are welcome.
