### ISSUE TITLE
API design discussion

### ISSUE THREAD

**Issue by halleygithub** [pydata/pandas#1844]
kk=DataFrame({'a':[1,0,3,5],'b':[2,4,6,8]})
kk['c']=kk.b/kk.a

>>> kk
   a  b  c
0  1  2  2
1  0  4  0
2  3  6  2
3  5  8  1

Two issues: 
(1) I don't think  kk[1,'c']=0 is a suitable answer
(2) I don't think  kk[3,'c']=1 is a suitable answer, it should be 1.6

while kk['c']=1.0*kk.b/kk.a  give an OK answer

>>> kk
   a  b    c
0  1  2  2.0
1  0  4  NaN
2  3  6  2.0
3  5  8  1.6

So pls treat 'int/int' to 'float/float', for current 'int/int' treatment will cause difficult checking error

**Comment by jreback** [comment]
pandas defaults true div since 0.14 IIRC. The other issue mentioned is detailed in several issues.
