### ISSUE TITLE
Option to exclude certain columns for plotting

### ISSUE THREAD

**Issue by changhiskhan** [pydata/pandas#2099]
Also maybe auto-exclude non-numerical columns by default like groupby agg?

http://stackoverflow.com/questions/13003051/how-do-i-exclude-a-few-columns-from-a-dataframe-plot

**Comment by ispmarin** [comment]
It would be great to have a way to slice the df and get only a few columns for plotting, for example.

Something like

    df[:,'2010':'2015']

on a data frame with years as columns, ranging from 2008 to 2015.

**Comment by jorisvandenbossche** [comment]
@ispmarin does `df.loc[:,'2010':'2015'].plot()` do what you want?
