### ISSUE TITLE
Documentation plotting

### ISSUE THREAD

**Issue by thomas-haslwanter** [pydata/pandas#2354]
Currently the abilities of "pandas" seem to outstrip the documentation massively. for example, there is no link to "tools.plotting" in the whole documentation, and commands like "scatter_plot" don't show up in the documentation at all. To make pandas usable for "outsiders", the documentation should be made more complete.

**Comment by kokes** [comment]
Is this still relevant? Documentation on [tools.plotting](http://pandas.pydata.org/pandas-docs/stable/visualization.html#visualization-tools) seems to have caught up over the years.

**Comment by jreback** [comment]
yeah this is just an old issue!
