### ISSUE TITLE
ENH: add append keyword to csv writer for easy multiple call appending

### ISSUE THREAD

**Issue by jreback** [pydata/pandas#3077]
http://stackoverflow.com/questions/15462344/writing-the-result-of-multiple-calls-on-a-manipulated-dataframe

**Comment by gfyoung** [comment]
@jreback : you're going to have to explain what this means, since the SO link is dead now.

**Comment by jreback** [comment]
iirc this was to add and append=False kw (rather than having to specify mode)

but since no other issues this must be not a problem
