### ISSUE TITLE
Row oriented CSV and Series

### ISSUE THREAD

**Issue by lrq3000** [pydata/pandas#3343]
Pandas does not handle Series in CSV format very well.

First problem: read_csv(squeeze=True) does not work, see:
http://stackoverflow.com/questions/15760856/how-to-read-a-pandas-series-from-a-csv-file/15767171

Secondly: both read_csv() and pandas.Series.from_csv() can't handle row-oriented CSV files. As an example, try to read the following as a Series:

import StringIO
string = "somefeature,anotherfeature,f3,f4,f5,f6,f7,lastfeature"
s = StringIO.StringIO(string)
X = pandas.Series.from_csv(s)

Result: X =
somefeature    anotherfeature
dtype: object

**Comment by josham** [comment]
```python
from StringIO import StringIO
import pandas as pd

s = "somefeature,anotherfeature,f3,f4,f5,f6,f7,lastfeature"
x = pd.read_csv(StringIO(s), lineterminator=',', header=None, squeeze=True)
x
0       somefeature
1    anotherfeature
2                f3
3                f4
4                f5
5                f6
6                f7
7       lastfeature
Name: 0, dtype: object

  ```

**Comment by gfyoung** [comment]
@jreback : I would reclassify this as an enhancement because the issues brought up here seem to be resolved.  Nevertheless, reading, horizontal CSV files would be a good feature to have.

**Comment by jreback** [comment]
yeah this should be closed as the squeeze parameter fixes this

**Comment by lrq3000** [comment]
The squeeze parameter fixes the issue when one uses `read_csv()` but not `Series.from_csv()` because it does not exist for the latter. Maybe this should be added?

**Comment by gfyoung** [comment]
@lrq3000: read the documentation on what squeeze does, and you'll see why that doesn't apply to Series.from_csv.

**Comment by lrq3000** [comment]
Yes I know about it, I was just suggesting that maybe a similar parameter
with the same code snippet could be transposed to this function to support
row CSV, but if pandas devs think it's better to rewrite something
specifically for this purpose then that's for the best, you guys know
better than anyone else :)

2016-08-01 16:53 GMT+02:00 gfyoung <notifications@github.com>:
