### ISSUE TITLE
Possible cyclic references in pandas

### ISSUE THREAD

**Issue by y-p** [pydata/pandas#3351]
recent change in test_perf (now worked around, but present in d7617d3 for example) 
disabled the gc when doing multiple runs on the same vb (just in case).

Though usage, this appears to cause memory exhaustion for large N, which is
an indication that cyclic refs are being created somewhere. invoking gc.collect()
clears the memory (so it's not the malloc.trim issue from #2659) 

It might be another dependency, not pandas that's causing this but need to check.

repro:
```
git reset --hard d7617d3
python ./setup.py develop
./test_perf.sh -H -N 500 -r frame_get_numeric_data
# monitor memory
```

See also comments in https://github.com/pydata/pandas/issues/4491

**Comment by jreback** [comment]
closing as stale
