### ISSUE TITLE
Nanoseconds being truncated in asof

### ISSUE THREAD

**Issue by schwallie** [pydata/pandas#3375]
match_time = get_info.index.asof(trade_time)
match_price = get_info[match_time]['Bid Price']

The actual index value:
\<Timestamp: 2013-04-10 10:22:01.696815975-0500 CDT, tz=US/Central>

The error returned:
KeyError: u'no item named 2013-04-10 10:22:01.696815-05:00'

It seems to me that it is cutting off the last digits of the timestamp in this example.

**Comment by jreback** [comment]
IIRC this is fixed by some recent work in 0.15.0. If still not working, pls open a new issue.
