### ISSUE TITLE
Multicharacter delimiters + non-UTF8 encoding doesn't work correctly in parsers

### ISSUE THREAD

**Issue by wesm** [pydata/pandas#3404]
The new C parser handles user-specified encoding properly. The Python parser not so much (I think it may only be an issue when regular-expression parsing is used).

**Comment by gfyoung** [comment]
@jreback : is it me, or is this no longer an issue?  The `common.py` tests have several encoding ones.

**Comment by jorisvandenbossche** [comment]
But I don't see directly any test with the combination of an encoding and a multi-character `sep`? (so maybe we should add a test for that?)
