### ISSUE TITLE
Deprecating the trellis rplot module

### ISSUE THREAD

**Issue by y-p** [pydata/pandas#3445]
Original title: rplot.rst needs cleaning up

----

http://pandas.pydata.org/pandas-docs/dev/rplot.html

plot style, dimensions, grids, legend.

**Comment by jreback** [comment]
older thread but anybody for killing trellis plotting in 0.16.0 and just pointing to seaborn?

**Comment by TomAugspurger** [comment]
We should at least start warning / deprecating.

**Comment by jreback** [comment]
yes let's do that at least (maybe a nice box at the top of the section)

**Comment by jorisvandenbossche** [comment]
@TomAugspurger Did you already have some examples of how to do it in seaborn? I vaguely can remember you posted it once in an issue? 
@JanSchulz would you be interested in giving some examples of `ggplot`? So basically for some of the current examples, just give the exact equivalent in ggplot

**Comment by jorisvandenbossche** [comment]
Started with a deprecation warning in #9357

**Comment by JanSchulz** [comment]
@jorisvandenbossche I've added a bugreport in ggplot, but I think currently we are nto ready yet (faceting and categorical are not so nice in ggplot currently ...)

**Comment by jorisvandenbossche** [comment]
Closed by  #9357

**Comment by haohanyang** [comment]
Good good you guys have done!
