### ISSUE TITLE
Trellis plot: wrong encoding by shape (rplot.scaleshape)

### ISSUE THREAD

**Issue by dalito** [pydata/pandas#3484]
The trellis plot shown in the documentation (http://pandas.pydata.org/pandas-docs/stable/_images/rplot7_tips.png) that uses ScaleShape to encode the data column "size" by shape shows a bug:

The same shape is used for "Sun, 5" and "Sun, 6" although they should have different shapes. Also "Thur, 4" and "Thur, 5" have the same shape (not visible in linked image).

The image also shows that gridlines are not correcly drawn on all panels.

**Comment by jreback** [comment]
xref #3445 I suppose we would take a patch for this, but other more supported plot libs out there.
