### ISSUE TITLE
Check whether google analytics results contain sampled data

### ISSUE THREAD

**Issue by changhiskhan** [pydata/pandas#3514]
Had a preview issue where the summary of returned results don't match the google analytics web portal results. This is probably why.

Need to look at the top level element for "containsSampledData".

https://developers.google.com/analytics/devguides/reporting/core/v3/reference#sampling

in pandas.io.ga.GDataReader.get_data, there’s the `_read` nested function which contains a call to execute the query object from google’s library. Pandas is looking for the results in the ‘rows’ attribute, I bet containsSampledData is also in there.

**Comment by jreback** [comment]
closing as deprecating ga in #11308
