### ISSUE TITLE
Vectorized localized to naive DatetimeIndex operation

### ISSUE THREAD

**Issue by wesm** [pydata/pandas#3653]
per http://stackoverflow.com/questions/16628819/convert-pandas-timezone-aware-datetimeindex-to-naive-timestamp-but-in-certain-t

Once localized, the underlying timestamps are in UTC and remain in UTC, to revert to naive / no-timezone format with UTC timestamps corresponding to the equivalent local time is not a straightforward op.

**Comment by jreback** [comment]
this is closed by ``t.tz_localize(None)`` already implemented IIRC 0.15.0
