### ISSUE TITLE
ENH: resample(..., how='range', start=a, stop=b)

### ISSUE THREAD

**Issue by danielballan** [pydata/pandas#3685]
Carrying over from [SO comments](http://stackoverflow.com/questions/16697869/getting-specific-median-from-data/16698053?noredirect=1#comment24034122_16698053)

Is it worth adding kwargs ``start`` and ``stop`` to enable this succinct usage?

    df.resample('D', how='range', start=0, stop=3)

**Comment by jreback** [comment]
this is xref in #7387  already
