### ISSUE TITLE
BUG: rplot.GeomDensity2D flips axes

### ISSUE THREAD

**Issue by flo-rian** [pydata/pandas#3753]
The axes drawn by rplot.GeomDensity2D are flipped.
line 565 reads:
        `ax.contour(Z, extent=[x_min, x_max, y_min, y_max])`
but should read:
        `ax.contour(Z.T, extent=[x_min, x_max, y_min, y_max])`
The following test code gives the results shown below:

```python
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pandas.tools.rplot as rplot

x = np.arange(1,30)
y = x*x
x = x + np.random.normal(size=x.shape)
y = y + np.random.normal(size=y.shape)
data = data = pd.DataFrame({'x': x, 'y': y})
plot = rplot.RPlot(data, x='x', y='y')
plot.add(rplot.GeomScatter())
plot.add(rplot.GeomDensity2D())
plot.add(rplot.GeomPolyFit(degree=2))
plot.render(plt.gcf())
plt.show()
```

![density_as_is](https://f.cloud.github.com/assets/4612277/606348/ce6e5b74-cd28-11e2-9c2d-575eef4a8186.png)

![density_fixed](https://f.cloud.github.com/assets/4612277/606349/ce706be4-cd28-11e2-8ac9-ea5a730c033c.png)

**Comment by jreback** [comment]
xref #3445
