### ISSUE TITLE
int handling by ScaleGradient

### ISSUE THREAD

**Issue by fonnesbeck** [pydata/pandas#3798]
If the data series passed to `ScaleGradient` in `plot` is integer-valued, it does not generate a correct color gradient. Here is a sequence consisting of integers used in a call to `ScaleGradient`:

![screen shot 2013-06-07 at 5 01 47 pm](https://f.cloud.github.com/assets/81476/626384/238abd72-cfbe-11e2-8495-da40a02c7698.png)

And the same after casting to floats:

![screen shot 2013-06-07 at 5 04 23 pm](https://f.cloud.github.com/assets/81476/626386/43b98308-cfbe-11e2-8eda-2a9c98a9bd37.png)

**Comment by jreback** [comment]
deprecating rplot in 0.16.0, so closing this.
