### ISSUE TITLE
ENH: add compression / direct calls to inline-msgpack

### ISSUE THREAD

**Issue by jreback** [pydata/pandas#3832]
link to #3831

- compression is actually enabled (via blosc/zlib), pass ``compress='blosc'``, but
need to pass this on packing AND unpacking, so defering this to 0.12
- maybe should make ``blosc`` an included library as well (as ``blosc``
vastly outperforms ``zlib``)
- direct calls to inline ``msgpack`` interface to increase pack/unpack perf

**Comment by pganssle** [comment]
I know that the second point is not fixed, but I think the first point in this issue is now addressed, correct?

**Comment by jreback** [comment]
right, closed by #8031
