### ISSUE TITLE
Breakpoint analysis feature in Pandas

### ISSUE THREAD

**Issue by bulli92** [pydata/pandas#3933]
Hi,

as far as I know, pandas does not support yet the analysis of time series homogeneity and the detection of breakpoints.

Would be really great if such a feature could be implemented. What I am thinking about is similar to the following R-project, called bfast (http://bfast.r-forge.r-project.org/).

Would be great if some people would be interested in this.

Alex

**Comment by sinhrks** [comment]
closing as out of scope.
