### ISSUE TITLE
API: bool dtype casts to object arrays with np.array

### ISSUE THREAD

**Issue by jseabold** [pydata/pandas#3966]
Bug? Did this used to work?

```
np.array(pandas.DataFrame.from_dict(dict(a=np.random.rand(50), b=np.random.randint(2, size=50).astype(bool))))
```

We would expect that this casts to a plain float ndarray.

See https://github.com/statsmodels/statsmodels/issues/880

**Comment by jreback** [comment]
this is as expected.
