### ISSUE TITLE
Better long-to-wide reshaping (inverse of melt-type operation)

### ISSUE THREAD

**Issue by wesm** [pydata/pandas#4061]
http://stackoverflow.com/questions/17333644/pandas-dataframe-transforming-frame-using-unique-values-of-a-column

**Comment by cdagnino** [comment]
Now (version 0.18.1) this stackoverflow question can be solved simply by:

`df.pivot_table(values="Val", index=['date', 'Country'], columns='Type')`

Which  maybe is enough to close this issue?

**Comment by jreback** [comment]
i would note the version of pandas in your answer as the 'cleanups' are some older bug fixes

**Comment by cdagnino** [comment]
Good point! Added Pandas version.
