### ISSUE TITLE
ENH: add to cython groupby functions

### ISSUE THREAD

**Issue by jreback** [pydata/pandas#4095]
- [ ] shift [here](http://stackoverflow.com/questions/17401197/how-to-speed-up-pandas-multilevel-dataframe-shift-by-group) and [here](http://stackoverflow.com/questions/25298659/faster-alternative-to-grouby-shift)
- [ ] [cumsum](http://stackoverflow.com/questions/28453238/cumsum-in-pandas-groupby-is-slow)
- [ ] [cumprod](http://stackoverflow.com/questions/32138067/quick-pandas-groupby-calculations)

**Comment by iwschris** [comment]
I've started looking at this one.

**Comment by iwschris** [comment]
@jreback I have a good start here on `shift`, but I need a little guidance to make sure that I don't reinvent something that's already in place. There's a fair amount of logic in `groupby.py` that expects the output of a groupby op to be compressed. However `shift` and `cumsum` shouldn't compress their result. The output length will be the same as the input length.

Currently I've done this by creating a list of ops that won't compress (currently just `shift` and `cumsum` I think) and then everywhere that the shape is expected to get compressed, I've added logic to keep it from doing so. Is that the right approach or has this already been done with some other groupby op that I'm not aware of?

**Comment by jreback** [comment]
these are kind of like (and I think should be implemented like) transform ops

another example is fillna
these return a same sized object as the input 

can u show a branch that u have so far?

**Comment by iwschris** [comment]
Alright, that helps. Let me get this cleaned up a little bit and I'll start a PR so that we can look at real code.

**Comment by chris-b1** [comment]
[cumprod](http://stackoverflow.com/questions/32138067/quick-pandas-groupby-calculations)

**Comment by jreback** [comment]
closed by #10901

**Comment by Oleg-Krivosheev** [comment]
Looks like there might be a problem http://stackoverflow.com/questions/33903624/python-pandas-memoryerror-skiplist-failed-when-using-rolling-median-and-apply

**Comment by randomgambit** [comment]
@jreback sorry to revive this but in my dataframe, a simple

`df['duration']=df.groupby('prop', sort=False).sale_dt.transform(lambda x: x.shift(-1)-x)`

takes just forever. Is this just because the data is big, or this is related to the old problems that are mentioned here? Happy to help if I can

**Comment by jreback** [comment]
anything with a lambda function will by definition be slow its basically a python loop.

but what you are doing is NOT a transform, which must return a scalar per group.

**Comment by jreback** [comment]
you probably want

``df.sale_dt - df.groupby('prop').sale_dt.transform('shift', -1)``

**Comment by randomgambit** [comment]
Thanks Jeff

> but what you are doing is NOT a transform, which must return a scalar per group.

wait my understanding is that transform is either one scalar per group (I compute the mean of x for every group, I and I want that mean merged back to the original data), OR some variation of the same data (aka some transformation, such as standardizing the values in the dataframe by dividing by the standard error). Have I missed something?

**Comment by jreback** [comment]
that's what I said
you can use apply if you want 
but using a lambda will simply be slow always

**Comment by randomgambit** [comment]
got it thanks.

by the way `df.sale_dt - df.groupby('prop').sale_dt.transform('shift', -1) ` is perfect

**Comment by randomgambit** [comment]
I think I will write a book soon:

100 most common errors any Pandas user has to make

bestseller on amazon for sure
