### ISSUE TITLE
DOC: Expand View vs copy in the docs

### ISSUE THREAD

**Issue by hayd** [pydata/pandas#4183]
At the moment it's a common source of confusion as to what returns a view vs a copy. The [docs are fairly light on this atm](http://pandas.pydata.org/pandas-docs/dev/indexing.html#indexing-view-versus-copy).
Need to expand this section with lots of example, and update with what now returns a view.

I've said before to @jreback I'd do this but tbh, am not fully confident on the ins and outs so perhaps we can post a few examples here to get started.

**Comment by jreback** [comment]
this is pretty good now
