### ISSUE TITLE
ENH: add rounding method to DatetimeIndex/TimedeltaIndex

### ISSUE THREAD

**Issue by jreback** [pydata/pandas#4314]
xref #8184
 
to say round by minute
http://stackoverflow.com/questions/17781159/round-pandas-datetime-index

by hour
https://github.com/pydata/pandas/issues/4314

might be simpler to use numpy astype here
http://stackoverflow.com/questions/23315163/merging-two-pandas-timeseries-shifted-by-1-second
```
In [75]: index = pd.DatetimeIndex([ Timestamp('20120827 12:05:00.002'), Timestamp('20130101 12:05:01'), Timestamp('20130712 15:10:00'), Timestamp('20130712 15:10:00.000004') ])

In [79]: index.values
Out[79]: 
array(['2012-08-27T08:05:00.002000000-0400',
       '2013-01-01T07:05:01.000000000-0500',
       '2013-07-12T11:10:00.000000000-0400',
       '2013-07-12T11:10:00.000004000-0400'], dtype='datetime64[ns]')

In [78]: pd.DatetimeIndex(((index.asi8/(1e9*60)).round()*1e9*60).astype(np.int64)).values
Out[78]: 
array(['2012-08-27T08:05:00.000000000-0400',
       '2013-01-01T07:05:00.000000000-0500',
       '2013-07-12T11:10:00.000000000-0400',
       '2013-07-12T11:10:00.000000000-0400'], dtype='datetime64[ns]')
```

**Comment by shoyer** [comment]
This *does* seem like a good idea.

**Comment by jreback** [comment]
straightforward too :)

**Comment by TomAugspurger** [comment]
Very useful. Would we have an option to always round down? I've needed something like postgres' [`DATE_TRUC`](http://www.postgresql.org/docs/9.1/static/functions-datetime.html#FUNCTIONS-DATETIME-TRUNC) a few times.

**Comment by jreback** [comment]
note that I had originally implemented this for ``Timedelta``, see [here](https://github.com/pydata/pandas/blob/master/pandas/tslib.pyx#L1815) as needed for partial-string indexing. But ``Timestamp`` and both index types need and impl.

**Comment by shoyer** [comment]
I've been looking into the rounding down part. In theory, I think this might be what `DatetimeIndex.snap` is supposed to do, but it doesn't seem to work for me. We might also call this `asfreq`.

Here's what I came up with:
```
def asfreq(dt, freq, how='start'):
    resample_how = {'start': 'first', 's': 'first', 'end': 'last', 'e': 'last'}[how]
    resampled = pd.Series(t, t).resample(freq, how=resample_how).index
    return resampled[resampled.get_indexer(t, method='ffill')]
```

I've been doing this with a combination of `to_period()`/`to_timestamp()` and `astype('datetime64[%s]' % freq)`, but neither of those handle uneven timesteps well.

**Comment by TomAugspurger** [comment]
Yeah I've been doing something similar. Thankfully my data has had a regular interval.

**Comment by jorisvandenbossche** [comment]
Yes indeed a good idea! I already wanted to do this for some time, but never found the time ..

@shoyer for the rounding down part, can't you also do the same as above, but use floor instead of round:

```
def datetime_round(dt, freq):
    from pandas.tseries.frequencies import to_offset
    freq = to_offset(freq).nanos
    return pd.DatetimeIndex(((np.floor(dt.asi8/(float(freq)))*freq).astype(np.int64)))
```

**Comment by jorisvandenbossche** [comment]
BTW, never heard of `DatetimeIndex.snap` ! 
But indeed, it does not really seems to work as I expected ..

**Comment by jreback** [comment]
for a ``Timestamp``
```
In [25]: def round(t, freq):
    # round a Timestamp to a specified freq
    return pd.Timestamp((t.value/freq.delta.value)*freq.delta.value)
```
