### ISSUE TITLE
What do you guys think about a DataFrame.drop_consecutive_duplicates?

### ISSUE THREAD

**Issue by numpand** [pydata/pandas#4543]
It would work similar to drop_duplicates (same interface), but would only remove consecutive duplicates (like Unix's uniq does).  So to in order to remove all duplicates with this function, the DataFrame would need to be sorted by the same criteria.  This function can be useful when order is important and non-consecutive duplicates convey useful information.

**Comment by tvyomkesh** [comment]
I think I can submit a PR for this one if it is not being looked into by anyone else.

**Comment by sinhrks** [comment]
dupe with #10540
