### ISSUE TITLE
MultiIndex column headings misaligned in to_html(index=False)

### ISSUE THREAD

**Issue by patricksurry** [pydata/pandas#4896]
Dropping the index column with index=False normally works OK, but if the column headings are from a MultiIndex, it fails to drop the empty ```<th></th>``` spacers at the start of the header, so data rows are not aligned properly: 
 
```
df = pd.DataFrame([[1,1],[1,2],[2,3]], 
                  columns=pd.MultiIndex.from_tuples([('a','b'),('a', 'c')]))
df.to_html(index=False)
```

**Comment by kokes** [comment]
Duplicated in #10344, [fixed in 0.17.0](http://pandas.pydata.org/pandas-docs/stable/whatsnew.html#whatsnew-0170-bug-fixes). (Check out this [gist](https://gist.github.com/kokes/af3caf88e24f3830be3e) that replicates your code.)
