### ISSUE TITLE
ENH: Generalize GA to work with MCF API

### ISSUE THREAD

**Issue by tshauck** [pydata/pandas#4919]
Right now the Google Analytics functionality is too specific to the Core Reporting API.  It should be generalized to handle MultiChannel Attribution as well.

For example, 

````
def _get_col_names(header_info):
    return [x['name'][3:] for x in header_info]
```

Would break because headers in are prepended with `mcf:` in the MultiChannel Attribution API.

**Comment by jreback** [comment]
closing as deprecating ga in #11308
