### ISSUE TITLE
rolling_apply only applicable to numeric columns

### ISSUE THREAD

**Issue by aschilling** [pydata/pandas#4964]
Hi everybody,

I discovered that the rolling_apply function is only applicable to numeric columns. I think this should be changed as this seems too limited to me. Let's take the following example, 
```
    import datetime as DT
    df = pd.DataFrame({
    'Buyer': 'Carl Mark Carl Joe Joe Carl'.split(),
    'Quantity': [1,3,5,8,9,3],
    'Date' : [
        DT.datetime(2013,9,1,13,0),
        DT.datetime(2013,9,1,13,5),
        DT.datetime(2013,10,1,20,0),
        DT.datetime(2013,10,3,10,0),
        DT.datetime(2013,12,2,12,0),                                      
        DT.datetime(2013,12,2,14,0),
        ]}).set_index('Date')
```

Now I want to count all new customers each 10 days.

    buyers = []

    def novices(x):
        new = [n for n in x if n not in buyers]
    
        if (len(new) > 0): buyers.extend(new) 
    
        return len(new)

    pd.rolling_apply(df['Buyer'], 10, novices)

throws an exception  "ValueError: could not convert string to float: Carl"

However, although meaningless a call with a numeric column such as: 

    pd.rolling_apply(df['Quantity'], 2, novices)

works.

**Comment by dashesy** [comment]
is it possible to ignore string columns and apply the rolling function to the rest?

**Comment by jreback** [comment]
going to repurpose this issue to skip nuiscance columns in a dataframe

In [4]: df = DataFrame({'A' : pd.date_range('20130101',periods=3),'B' : range(3)})

```
In [5]: df
Out[5]: 
           A  B
0 2013-01-01  0
1 2013-01-02  1
2 2013-01-03  2
```

This is a supported op
```
In [7]: df.rolling(window=2).count()
Out[7]: 
     A    B
0  1.0  1.0
1  2.0  2.0
2  2.0  2.0
```

This works
```
In [9]: df.rolling(window=2).B.sum()
Out[9]: 
0    NaN
1    1.0
2    3.0
Name: B, dtype: float64
```

```
df.rolling(window=2).sum()
```
should work (but excluded ``A``) from the results.

**Comment by jreback** [comment]
closing in favor of #12537

**Comment by Darel13712** [comment]
@jreback Hello is there any possibility to get rolling.apply for objects in 2018?) It still ignores objects as of 0.22.0.


```
idx = pd.date_range(pd.to_datetime('2017-01-01'), pd.to_datetime('2017-01-03'))
df = pd.DataFrame([[1, 's'],[2, 't'],[3, 'r']], index=idx)
```
|            | 0 | 1 |
|------------|---|---|
| 2017-01-01 | 1 | s |
| 2017-01-02 | 2 | t |
| 2017-01-03 | 3 | r |

it's ok to ignore objects with built-in functions
```
df.rolling(2, min_periods=1).sum()
```
|            | 0 | 1 |
|------------|---|---|
| 2017-01-01 | 1 | s |
| 2017-01-02 | 3 | t |
| 2017-01-03 | 5 | r |

but why can't i handle objects myself?

```
def const(x):
    return 5
df.rolling(2, min_periods=1).apply(const)
```
|            | 0 | 1 |
|------------|---|---|
| 2017-01-01 | 5 | s |
| 2017-01-02 | 5 | t |
| 2017-01-03 | 5 | r |

This example above is not really useful but I want to be able to apply function to a column that contains objects.

The best solution I've found is to create your own DataFrame/Series type https://stackoverflow.com/questions/44479384/pandas-rolling-apply-doesnt-do-anything

But I really think this should be in pandas by default.

**Comment by jreback** [comment]
would always take a PR for this
