### ISSUE TITLE
Document the "default NaN values" in Parser

### ISSUE THREAD

**Issue by cancan101** [pydata/pandas#5153]
For example from docs (http://pandas.pydata.org/pandas-docs/stable/generated/pandas.io.parsers.read_csv.html):
```
keep_default_na : bool, default True
If na_values are specified and keep_default_na is False the default NaN values are overridden, otherwise they’re appended to
```

But it is not clear what those default values are.

**Comment by gfyoung** [comment]
@jreback : IINM, the <a href="http://pandas.pydata.org/pandas-docs/version/0.18.1/generated/pandas.read_csv.html?highlight=read_csv">docs</a> now enumerate the default values.  IMO, this is no longer an issue.

**Comment by jreback** [comment]
yes this is ok

**Comment by jorisvandenbossche** [comment]
Closed by https://github.com/pydata/pandas/pull/14030
