### ISSUE TITLE
Simple way of adding/removing column to DataFrame Not in Place

### ISSUE THREAD

**Issue by cancan101** [pydata/pandas#5451]
See SO question: http://stackoverflow.com/questions/19802708/add-column-to-pandas-dataframe-not-in-place

I would suggest something like:

```
df_new  = df.alter(new_col_name=existing_series)
```

where alter would wake one or more columns:
```
df_new  = df.alter(
new_col_name1=existing_series1,
new_col_name2=existing_series2,
)
```

This can further be a superset of ```drop``` allowing columns to be removed by setting them to ```None```
```
df_new  = df.alter(old_col_name=None)
```

Thoughts?

**Comment by jorisvandenbossche** [comment]
The added `DataFrame.assign` a while ago closes this issue I think
