### ISSUE TITLE
netCDF IO suport

### ISSUE THREAD

**Issue by jhamman** [pydata/pandas#5487]
I'd like to propose `read_netcdf` ([netCDF (Network Common Data Format)](http://www.unidata.ucar.edu/software/netcdf/)) a new Pandas I/O api feature with a similar top level interface as the other reader functions.  This format is widely used in the scientific community.   Furthermore, netCDF4 is implemented on top of the HDF5 library, making this a natural extension to functionality already in the api.  

Most likely this would sit on top of the exiting [Python/numpy interface to netCDF](https://code.google.com/p/netcdf4-python/), and because each variables metadata is stored in the file header, no complicated parsing would necessary. Multidimensional variables could be handled in a similar manner as hdf.

This may have been brought up in the past but my search here and on the google didn't bring anything up.

**Comment by jhamman** [comment]
@shoyer and @jreback, 

Have there been any other discussions on this recently?  I've been using `xray` to handle most of my netCDF I/O and the `xray.Dataset.to_pandas()` method has been meeting all my needs in terms of reading netCDF data into `Pandas` data types.  I'm not sure I see much benefit in building a separate netCDF reader for `Pandas` given the functionality that `xray` provides.

**Comment by shoyer** [comment]
To add to what @jhamman writes, NetCDF is a highly structured data format that isn't a great fit for existing pandas data structures, except in some special cases. This would be a little different if we had working nd panels, but you'd still end up reading a netcdf file into a dict of nd panels -- pretty ugly and not very useable. Pandas itself is never going to have the right data structures for netcdf.

This is, of course, the motivation for why I wrote xray. I'm not saying xray is the end all solution here, but it does add no additional dependencies (beyond itself and a library to read netcdf files) and makes it quite straightforward to read netcdf into pandas, with explicit choices about how to handle edge cases along the way.

**Comment by jorisvandenbossche** [comment]
I was just thinking, maybe we could add somewhere in the IO docs a reference to this? (saying that if you want to import NetCDF -> use xray, and you can always convert that (or part of the data) to pandas dataframes)

**Comment by jhamman** [comment]
Thanks @shoyer for elaborating on my point.  

@jorisvandenbossche - seems reasonable to point to xray as a way to get netCDF data into pandas.

**Comment by shoyer** [comment]
@jorisvandenbossche good idea, just made a PR for that (#10027)
