### ISSUE TITLE
enh: api cleanup... tostring, to_string, to_html, etc.

### ISSUE THREAD

**Issue by gregglind** [pydata/pandas#577]
There is a lot of semi-duplication / differences in the ``Series()`` and ``DataFrame()`` methods.

Maybe it's worth taking a look through them and regularising.

Fwiw, I prefer  ``tostring`` vs. ``to_string``

Also, would be nice to have `tohtml` on things, though expanding it is beyond the scope of this.

**Comment by naught101** [comment]
Dunno whether it's worth opening a new issue, but `df.as_matrix` should be renamed to `df.as_array` - it returns a `numpy.ndarray`, not a `numpy.matrixlib.defmatrix.matrix`. And in the case of Series, Panels and Panel4Ds it returns 1D, 3D and 4D arrays respectively, which clearly aren't matrices.

I would suggest that it might be worth adopting a convention like `df.as_*` for conversion to other data types (`df.as_matrix`, `df.as_dict`, `df.as_list`, etc), and `df.to_*` for export to files or other streams (`df.to_clipboard`, `df.to_csv`, `df.to_html`, etc).

**Comment by naught101** [comment]
Also, I agree that underscores are better - what the hell is a `tost ring`? Not to mention "asof" (wtf?), and "top anel" :P 

camelCase would also be ok, it's much clearer than no word definition, and it's shorter than underscores.

Re: "a bit too late". Wouldn't it be easy enough to just make aliases for each method, and raise warnings when they're called, noting that they're deprecated? Those aliases could be removed later (and the warnings could state which version they will be removed in).

**Comment by wesm** [comment]
Closing -- please open issues addressing specific existing inconsistencies.
