### ISSUE TITLE
datetools.parse interface

### ISSUE THREAD

**Issue by jseabold** [pydata/pandas#5886]
- [ ] document in docstring / cookbook / timeseries.rst usage of combing integer columns into YYYYMMDD and parsing to datetimes
- [ ] clean up imports of ``_parse/parse`` from dateutils
- [ ] ``to_period``  to create ``PeriodIndex``

I started to make a PR #5885 to fix what I thought was a typo before realizing that this was intentional. It still doesn't make much sense to me though why I would want this return of datetime, _result, resolution. Maybe the whole approach could use a refactor. Otherwise what am I missing?

My typical use case for datetools.parse is something like

`dates = map(lambda x : parse('  '.join(x)), zip(df.day, df.month, df.year))`

A couple of questions.

1. Is there a better way to do this vectorized to datetime operation? AFAICT pd.to_datetime doesn't actually use the 'advanced' parsing for quarterly and monthly dates.
2. Should this all be unified? Assuming I haven't missed it, should there be, e.g., a function `pd.parse_dates` that is a general parser for both strings and works on array-like input, deprecating datetools.parse, datetools.parse_time_string, and datetools.to_datetime. This function could also have a flag to return Period or TimeStamp objects with frequency information instead of the current return of the parsed object and resolution. Given that I'm having to do things like

`dates = [x[0] for x in map(lambda x : parse('  '.join(x)), zip(df.day, df.month, df.year))]`

Thoughts?

**Comment by jreback** [comment]
mentioned in [SO](http://stackoverflow.com/questions/30539982/convert-string-to-datetime-feb-month-not-parsed/30540653#30540653)

**Comment by gfyoung** [comment]
@jreback : Is this issue even relevant anymore?  IINM, `pd.datetools.parse` doesn't exist anymore.

**Comment by jreback** [comment]
look at the imports they are * so yes

**Comment by gfyoung** [comment]
@jreback : I don't understand what you mean by that.

**Comment by jreback** [comment]
do a dir() on the namespace

**Comment by gfyoung** [comment]
Again, do not follow.  Just try the following:
~~~python
>>> import pandas as pd
>>> pd.datetools.parse
...
AttributeError: module 'pandas.core.datetools' has no attribute 'parse'
~~~

**Comment by jreback** [comment]
dir()

**Comment by gfyoung** [comment]
Again, do not follow.  Just try the following:
~~~python
>>> import pandas as pd
>>> 'parse' in dir(pd)
False
>>> 'parse' in dir(pd.datetools)
False
~~~
I'm really not understanding what you're saying here.

**Comment by jreback** [comment]
I guess it's gone 

all of these issues are either fixed then or elsewhere (to_period needs a standalone issue)

**Comment by jreback** [comment]
http://pandas.pydata.org/pandas-docs/stable/whatsnew.html#whatsnew-0181-enhancements-assembling

**Comment by jreback** [comment]
@gfyoung if u would create an issue for to_period would've great
cc @sinhrks

**Comment by gfyoung** [comment]
`to_period` for `DatetimeIndex` I presume?

**Comment by jreback** [comment]
no it's like to_datetime but creates PeriodIndexes

**Comment by gfyoung** [comment]
Yep, done: #14108
