### ISSUE TITLE
API/DOC: status of low_memory kwarg of read_csv/table

### ISSUE THREAD

**Issue by cancan101** [pydata/pandas#5888]
I am getting the following warning:
```
/usr/local/lib/python2.7/dist-packages/pandas-0.13.0rc1_78_g142ca62-py2.7-linux-x86_64.egg/pandas/io/parsers.py:1050: 
DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  data = self._reader.read(nrows)
```

but I can find no documentation for ```low_memory```

**Comment by jorisvandenbossche** [comment]
@mdmueller @selasley As csv parser experts, somebody interested in looking into this? (What does `low_memory` do exactly? Do we still need it (should it be deprecated or not)? And depending on that, document it or really deprecate it (and remove as suggestion in one of the warnings).

This came up again at SO: http://stackoverflow.com/questions/28697501/how-to-know-line-and-col-when-the-read-csv-method-of-pandas-thows-exception/28702078#28702078

**Comment by jondo** [comment]
Why is this not visible [in the online documentation](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html) yet?

Should this documentation also be added for [pandas.read_table](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_table.html) (which has the same behavior)?

**Comment by jreback** [comment]
it's in the 0.19.0 and greater docs
https://github.com/pandas-dev/pandas/pull/13293/files

**Comment by jondo** [comment]
Will this change also become visible in the pd.read_table documentation?

**Comment by jorisvandenbossche** [comment]
Ah, apparantly there is something wrong with the `read_csv` page. This is still from 0.18.1, although the main docs under 'stable' are for 0.19.1. So, @jreback apparently something went wrong when I uploaded the docs and the generated pages were not updated

**Comment by jorisvandenbossche** [comment]
@jondo docs should be fixed now (be sure to refresh your browser). Thanks for noticing!

**Comment by jondo** [comment]
It's me who has to thank you!
Yes, now the pages of `read_csv` and `read_table` both contain the added text.
