### ISSUE TITLE
Add row filtering operator

### ISSUE THREAD

**Issue by elyase** [pydata/pandas#5900]
This would allow chaining operations like:
```python
pd.read_csv('imdb.txt')
  .sort(columns='year')
  .filter(lambda x: x['year']>1990)   # <---this is missing in Pandas
  .to_csv('filtered.csv')
```
For current alternatives see:

http://stackoverflow.com/questions/11869910/pandas-filter-rows-of-dataframe-with-operator-chaining

**Comment by naught101** [comment]
Might it be possible with patsy to make a filter method that uses a formula string?

```{python}
pd.read_csv('imdb.txt')
  .sort(columns='year')
  .filter('year >1990')
  .to_csv('filtered.csv')
```

**Comment by shoyer** [comment]
@naught101 Using strings to filter dataframes is already possible. The method is `query`, e.g.,
`pd.DataFrame({'x': [1, 2, 3, 4, 5]}).query('x > 3')`

**Comment by jreback** [comment]
I suppose ``.query`` *could* take lambda to provide this in-line type of chaining

**Comment by jreback** [comment]
dupe of #11485 (which has more examples)
