### ISSUE TITLE
HDF5 Select with Filter gives incorrect results when using Iteration

### ISSUE THREAD

**Issue by CarstVaartjes** [pydata/pandas#5913]
Linked Issue: https://github.com/PyTables/PyTables/issues/319

Hi,

I have a dataframe saved in HDF5 with 6.7 million records (about 425MB). As you can see below, it gives an incorrect result when it has to do multiple iterations (which is a serious issue for me actually). ->

    # prepare
    fact_hdf = pd.HDFStore('iteration_test3.h5', mode='r')
    store_name = 'store_0'
    column_list = ['o', 'm101']
    where = [('o', '=', [-15534, -16280, -17113, -14786, -14790, -18074])]
    
    # describe
    fact_hdf[store_name]
    '''
    <class 'pandas.core.frame.DataFrame'>
    Int64Index: 6708525 entries, 0 to 6708524
    Columns: 27 entries, a1007 to m105_b
    dtypes: float64(11), int64(16)
    '''
    
    # non iterated
    fact_hdf.select(store_name, columns=column_list, where=where)['o'].unique()
    '''
    array([-14790, -16280, -15534, -14786, -18074, -17113])
    '''
    
    # iterated by 1mln
    chunksize = 1000000 # 1 mln
    for sub_df in fact_hdf.select(store_name, columns=column_list, where=where, iterator=True, chunksize=chunksize):
        sub_df['o'].unique()
    
    '''
    array([-14790, -16280, -15534, -14786, -18074, -17113])
    array([-14786, -14790, -15534, -18074, -16280, -17113])
    array([-14790, -18074, -15534, -14786, -16280, -17113])
    array([-16280, -14790, -15534, -18074, -14786, -17113])
    array([-14790, -14786, -15534, -18074, -16280, -17113])
    array([-18511, -17074, -17099, -16876, -18060, -15965, -14733, -16300,
           -15534, -14790, -16280, -14786, -18074, -17113])
    array([-16280, -14790, -18074, -15534, -14786, -17113])
    '''
    
    # iterated by 10mln
    chunksize = 10000000 # 1 mln
    for sub_df in fact_hdf.select(store_name, columns=column_list, where=where, iterator=True, chunksize=chunksize):
        sub_df['o'].unique()
    
    '''
    array([-14790, -16280, -15534, -14786, -18074, -17113])
    '''

Reproducing the bug can be hard (not all files have the same issue), but this specific case happens again (it's not a corrupted HDF5 file, if you write away the dataframe it happens again).

I can share the file with pandas/pytables developers if needed (it has to be personal though / not uploaded to a public location; message me for a sftp link)

Some technical stuff
 - Pandas 0.12
 - Pytables 3.0
 - Ubuntu 12.04LTS 64bit
 - File is saved with BLOSC, complevel=9

Kind regards,

Carst

**Comment by jreback** [comment]
this was closed by the linked Pytables issue
