### ISSUE TITLE
time series indexing KeyError on non-monotonic index

### ISSUE THREAD

**Issue by michaelaye** [pydata/pandas#5931]
I just stumbled over time series indexing with a non-monotonic time series that came about because I concatenated data that should not have existed even. (JPL just got a bug report. ;)
So, if I have a dataframe like this, with the index clearly out of order:

```python
0	1	2
2011-07-19 10:00:01.824000	-0.071762	-0.708509	-0.764987
2011-07-19 10:00:01.952000	 1.487533	-0.111620	 0.858629
2011-07-19 10:00:00.038000	 0.600555	 0.183954	-0.635211
```
Here as a json string, but: When you recreate it, the index is in order, so you got to do some magic to roll it around (how would i do that?)
```python
'{"0":{"1311069601824":-0.0717615221,"1311069601952":1.4875326599,"1311069600038":0.6005551597},"1":{"1311069601824":-0.7085093684,"1311069601952":-0.111620072,"1311069600038":0.1839544789},"2":{"1311069601824":-0.7649867899,"1311069601952":0.8586288484,"1311069600038":-0.6352107949}}'
```
and I try an indexing with an automatically determined hour start, I get KeyError:
```python
import datetime as dt
start = dt.datetime(2011, 7,19,10)
try:
    df2[start:]
except KeyError as e:
    print KeyError, e
```
I get
```python
<type 'exceptions.KeyError'> Timestamp('2011-07-19 10:00:00', tz=None)
```
Leaving out the last, non-monotonic, index, it works:
```python
df.iloc[:-1][start:]
```
Out:
```python
0	1	2
2011-07-19 10:00:00.038000	 0.600555	 0.183954	-0.635211
2011-07-19 10:00:01.824000	-0.071762	-0.708509	-0.764987
```
I understand why it is happening (I think), but I believe it should be handled better, or at least a better error message so that the user knows what's happening.

Edit: This is on v0.13

**Comment by jreback** [comment]
this is as expected
