### ISSUE TITLE
MIGRATE: move stats code to statsmodels / deprecate in pandas

### ISSUE THREAD

**Issue by jreback** [pydata/pandas#6077]
related #5884

- [ ] OLS https://github.com/statsmodels/statsmodels/blob/master/statsmodels/regression/linear_model.py
- [ ] plm (regression for panels)
- [ ] fama_macbeth
- [ ] VAR https://github.com/statsmodels/statsmodels/tree/master/statsmodels/tsa/vector_ar

**Comment by jreback** [comment]
let's deprecate some of these in 0.18.0

**Comment by jdmarino** [comment]
I'm going to miss `pd.stats.ols.MovingOLS` when it's gone.
