### ISSUE TITLE
ENH: pprint index/columns?

### ISSUE THREAD

**Issue by jseabold** [pydata/pandas#6295]
I haven't looked at the source yet, but do columns ever get pretty printed? It looks like indices do if it's a DatetimeIndex, but not otherwise.

I often find myself doing

    df.columns.tolist()

otherwise it's not really readable.

**Comment by jreback** [comment]
xref #9741 

To do this right is actually a bit non-trivial. and will require some refactoring to gather all of the scattered bits of code.
