### ISSUE TITLE
Losing index and sort on merge

### ISSUE THREAD

**Issue by jseabold** [pydata/pandas#6437]
I'm almost positive I've filed an issue about this before, but I don't find it. This is a pretty common operation when working with panel data. You want to merge in some constant values into a DataFrame that has repeated keys but unique index.

    df = pd.util.testing.makeDataFrame() # yes!
    df["group"] = 0
    df.ix[range(0, 20, 2), "group"] = 1.
    df["time"] = np.random.randint(5, size=len(df))
    df_x = pd.DataFrame(np.c_[np.r_[np.arange(5), np.arange(5)], 
                            np.repeat([0,1], 5)], 
                        columns=["time", "group"])
    df_x["constant_info"] = np.random.randn(len(df_x))

    df.merge(df_x, on=["time", "group"])

Where'd my index go? Where'd my sort go, so I could even recover the index?

    [~/]
    [65]: pd.version.version
    [65]: '0.13.1-254-g150f323'

**Comment by jreback** [comment]
closing as stale. pls reopen if still an issue.

**Comment by marcdelabarrera** [comment]
This is an old issue, but is it still the case that when I have a panel data where the index is the date, and I want to add a column to it using a 1 to 1 matching on `col`, the best practice is:

```
df.reset_index().merge(other_table, on='col').set_index('date')
```

For example, I have a dataset with `date`, the `subject_code`, and how many students were in that semester. `date` is the index and I have another table with the `subject_code` and `subject_name`. I want to add `subject_name` to the previous table. Is there any reason why it does not exist a `keep_index=True` option?
