### ISSUE TITLE
BUG: to_csv extra header line with multiindex columns

### ISSUE THREAD

**Issue by dsm054** [pydata/pandas#6618]
This seems strange to me, but I don't often use a MultiIndex so I might be missing something obvious.

```
>>> pd.__version__
'0.13.1-420-g6899ed6'
>>> df2 = pd.DataFrame([1], columns=pd.MultiIndex.from_arrays([[1],[2]]))
>>> df2
   1
   2
0  1

[1 rows x 1 columns]
>>> df2.columns
MultiIndex(levels=[[1], [2]],
           labels=[[0], [0]])
>>> print df2.to_csv()
,1
,2
,
0,1
```

Is there supposed to be that empty line at the end of the header?  Compare

```
>>> print df2.to_csv(header=False)
0,1
```

**Comment by ronanpaixao** [comment]
It appears this bugs still manifests itself if using to_excel:

```python
>>> df = pd.DataFrame([[1,2,3],[4,5,6]], columns=pd.MultiIndex.from_tuples([('A',''),('B','C'),('B','D')]))
>>> df
   A  B
      C  D
0  1  2  3
1  4  5  6
>>> df.to_excel("out.xlsx")
```
This outputs the spreadsheet with an additional (and pretty much useless) blank line (3):
![pandas_to_excel_bug](https://user-images.githubusercontent.com/7624997/31996526-394f6b8c-b95f-11e7-9619-22d87768998e.png)

[This](https://stackoverflow.com/a/45581984/3754432) is some workaround, but is really worse for cases like my example, where the upper row in the MultiIndex gets repeated (see `df['B']`).

**Comment by tsznxx** [comment]
A workaround to fix this is to save the headers and table contents separately.

writer = pandas.ExcelWriter("test.xlsx")

# writer headers as data frame
df.columns.to_frame().transpose().to_excel(writer,"test")

# writer table body without headers
df.to_excel(writer,"test",header=False,startrow=2))

writer.save()
writer.close()

This trick can also be used when saving pandas style to Excel, because pandas style doesn't support multiindex.

**Comment by jstefaniakk** [comment]
The solution given above by tsznxx worked for me, however a line:
`df.columns.to_frame().transpose().to_excel(writer,"test")`
generates two rows of data with names of the columns and when I had less than 3 rows of data in my dataframe it actually was printed into the excel. Instead, I propose to first write your empty dataframe to excel :
```
df.drop(df.index).to_excel(writer,"test")`
 and then follow it up with dataframe data without headers.  So the whole example would look like:
writer = pandas.ExcelWriter("test.xlsx")
# write only column names
df.columns.to_frame().transpose().to_excel(writer,"test")
# writer table body without headers
df.to_excel(writer,"test",header=False,startrow=2))
writer.save()
writer.close()

```
