### ISSUE TITLE
Slice timeseries with "pro-rata" behaviour at endpoints

### ISSUE THREAD

**Issue by mjwillson** [pydata/pandas#6669]
Hi all

Suppose I have a timeseries indexed by a PeriodIndex at day resolution, and I want to numerically integrate it over a range whose start- and end-point are known to a higher time resolution (say, to the exact second).

As the first step towards this, it'd help to take a slice of my timeseries in which the values at the start and end are computed "pro rata" according to the proportion of that calendar day Period which is included in the range.

I was looking for a way to do this with `reindex`, but it's not really a reindexing, more a slicing kind of operation with special-casing of the endpoints. Is there a way to do this in pandas? Seems like it could be a useful addition if not, I imagine it could be useful for various accounting applications too.

(Even better would be a way to numerically integrate a timeseries directly while specifying endpoints at higher time resolution than the index. Unfortunately this doesn't seem possible with the sample-based integrators in `scipy.integrate`.)

Cheers!

**Comment by jreback** [comment]
closing. this might involve a transformation of the series to weight by durations. but would need a concrete use case here.
