### ISSUE TITLE
OMP Error on Series experssions

### ISSUE THREAD

**Issue by davidljung** [pydata/pandas#6720]
from SO: http://stackoverflow.com/questions/23537265/inconsistent-system-error-with-pandas-0-13-series-operation/23542455#23542455

When performing some expressions involving Series returned from DataFrame column indexing (Pandas 0.13.1 with Numpy 1.8.0 in Windows 7), a new pythonw.exe console window appears (empty) but the initiating GUI indicates the following error text was returned:
```
OMP: Error #134: Cannot set thread affinity mask.
OMP: System error #87: The parameter is incorrect.
```

It occurs with expressions such as:
```df = df.loc[(df['timediff'] > -20) & (df['timediff'] < 20),:]```
and
```df['GP'] = (df['Price'] - df['Cost'] - (df['Discount'] / df['Qty'])) * df['Qty']```

(this is on moderately small DataFrames < 10 million rows)

As a workaround, disabling numexpr operations seems to avoid it:
```
pandas.computation.expressions.set_use_numexpr(False)
``` 
as suggested in issue #3434.

Possibly related (at least by error text):
http://software.intel.com/en-us/forums/topic/279406

**Comment by JohnNapier** [comment]
Please find here (https://github.com/pydata/pandas/issues/9328) code to reproduce this issue.

**Comment by jreback** [comment]
closing as related to the Enthought distro
