### ISSUE TITLE
Log scaled histograms readability with default display.mpl_style can be improved

### ISSUE THREAD

**Issue by acorbe** [pydata/pandas#6851]
I use quite frequently log scaled histograms with `histtype='step'` option.

I noticed that with the suggested `default display.mpl_style` (which I like), readability of such histograms is quite improvable.

Consider this (from ipython notebook)

    %pylab inline

    import pandas as pd
    import numpy as np
    import matplotlib
    import matplotlib.pyplot as plt

    matplotlib.rcParams['savefig.dpi'] = 300

    pd.set_option('display.mpl_style', 'default')

    val = np.random.normal(size=1000000)
    val2 = np.random.normal(scale = .5, size=1000000)
    df = pd.DataFrame({'A' : val , 'B' : val2 , 'C' : val2})

    df.hist(bins = 80, log=True,histtype='step')

    plt.figure()
    df.A.hist(bins = 80 , log=True,histtype='step',normed=True )
    df.B.hist(bins = 80 , log=True,histtype='step',normed=True )

![pandas_hist1](https://cloud.githubusercontent.com/assets/2300692/2658524/92125cf0-c009-11e3-9c9a-934de51c0554.png)
![pandas_hist2](https://cloud.githubusercontent.com/assets/2300692/2658528/94deb17c-c009-11e3-8538-8b7e52f198bd.png)

The secondary grid looks too thick and confusing; IMHO it damages readability. This problem shows up only with log scaled hist.

Consider the following as a comparison
![pandas_hist3](https://cloud.githubusercontent.com/assets/2300692/2658585/32c32102-c00a-11e3-97a0-1c7302651289.png)

**Comment by jorisvandenbossche** [comment]
Closing this since `display.mpl_style` is deprecated now
