### ISSUE TITLE
read_csv is inefficient for wide tables

### ISSUE THREAD

**Issue by jdavidheiser** [pydata/pandas#7048]
I was loading some relatively large CSV files (roughly three hundred by one million), and noticed that the layout of those CSVs is actually critical to Pandas' ability to read them to memory.  A "wide" format uses large amounts of memory and takes an extremely long time to run (killed the process after a half hour).  The exact same data, but presented in a "tall" format (ie 300 columns and one million rows) reads within about sixty seconds.  Given there is no sort of "warning" message regarding the number of columns when reading the CSV file, I could easily see this confusing a new user and leading them to believe that Pandas is simply unable to handle that volume of data, when in fact it can, given that the data is formatted correctly.  Perhaps some broader documentation on wide vs tall inputs would be appropriate.

**Comment by rontho1992** [comment]
What is the best way to overcome this issue of wide tables? I've got tables that are approx 2-20 million rows by 2k columns. It gets to be an issue for the data sets that go above 10 million (can take up to half hour to load).

**Comment by jreback** [comment]
the soln is in #9969 which I would take a PR
closing this as a dupe
