### ISSUE TITLE
BUG: na_values with a dict of scalars

### ISSUE THREAD

**Issue by jseabold** [pydata/pandas#7119]
I can't get `na_values` to work with a dictionary.

    from StringIO import StringIO
    import pandas as pd

    dta = pd.read_csv(StringIO("""var1,var2,var3,var4
    1,2,3,MISSING
    2,3,4,4.5
    """), na_values={3 : 'MISSING'})

    dta = pd.read_csv(StringIO("""var1,var2,var3,var4
    1,2,3,MISSING
    2,3,4,4.5
    """), na_values={'var4' : 'MISSING'})

    dta = pd.read_csv(StringIO("""var1,var2,var3,var4
    1,2,3,MISSING
    2,3,4,4.5
    """), na_values=['MISSING'])

On

    [~/]
    [10]: pd.version.version
    [10]: '0.13.1-753-g4614ac8'

**Comment by gfyoung** [comment]
@jreback : #14056 resolves the second example.  However, the behaviour for the first one is not entirely clear from documentation.  Should we be able to accept column indices?  At the moment, the answer appears to be no:
~~~python
>>> from pandas.compat import StringIO
>>> from pandas import read_csv
>>> data = 'a\nfoo\n1'
>>>
>>> read_csv(StringIO(data), na_values={0: 'foo'}, engine='c')
...
TypeError: Expected list, got set
>>> read_csv(StringIO(data), na_values={0: 'foo'}, engine='python')
     a
0  foo
1    1
~~~

**Comment by jreback** [comment]
@gfyoung I think column indices are ok, except if a header is passed (in which case they must be the names; easiest to avoid conflict here).

**Comment by gfyoung** [comment]
@jreback : Hmm...okay.  In any case, I think the issue should be closed in favor of another one that specifically states that we can correctly process column indices.

**Comment by jreback** [comment]
ok can u make one?

**Comment by gfyoung** [comment]
@jreback : Done --> #14203.
