### ISSUE TITLE
BUG: _repr_html_ doesn't use `display.colheader_justify`

### ISSUE THREAD

**Issue by TomAugspurger** [pydata/pandas#7235]
![screen shot 2014-05-25 at 9 59 50 am](https://cloud.githubusercontent.com/assets/1312546/3077252/416a4118-e41d-11e3-92e8-885eb0d31e99.png)

It is used correctly in `str(df)` and the terminal repr; I think just `_html` is the problem. I'll see if I can track it down quick.

**Comment by jreback** [comment]
closing as refered to an ipython bug
