### ISSUE TITLE
Performance degradation in pandas 0.13/0.14

### ISSUE THREAD

**Issue by davaco** [pydata/pandas#7493]
I reported previously on issue #7208. It was noted that .ix was slower as of pandas 0.13 but that this should be only noticeable in non-vectorized code. I sometimes however have trouble vectorizing everything. Please consider the following code in which I have a rather big correlation matrix, using multi-indexed columns. I would like to set the diagonal elements equal to 1.

```
from pandas import *
import numpy as np
import pandas
import string

def diag(cor, assets):
    for asset in assets:
        cor.ix[:, (asset, asset)] = 1

# create a multi-indexed column axis like ('A', 'A'), ('A', 'B'), ...
assets = list(string.ascii_uppercase)
columns = MultiIndex.from_tuples([(a, b) for a in assets for b in assets])

# create the correlation matrix
cor = DataFrame(np.random.rand(10000,676), index=date_range('1977/1/1', periods=10000, freq='D'), columns=columns)

%time diag(cor, assets)
```

On my machine this takes approx. 9 ms in pandas 0.12, 5.3 seconds using pandas 0.14 (!).
Maybe the above code could be vectorized, then I would be curious on the how. However my concern is that I cannot always vectorize, in which case Pandas to me seems to display performance degradation each time when I go to the next version, from 0.11 onwards. Any comments / help will be greatly appreciated!

**Comment by jreback** [comment]
closing as stale
