### ISSUE TITLE
Pandas 14.0 Dataframe Clears sys.exc_info() When pprinted

### ISSUE THREAD

**Issue by keeganmccallum** [pydata/pandas#7590]
I am running into an issue with error handing in my current project after upgrading to pandas 14.0. The issue is that when I use pprint to render the dataframe as part of the traceback message, it for some reason silently clobbers the sys.exc_info(), which makes it impossible to re-raise the error after my processing using a 'raise' command with no arguments. To reproduce (using the iris.csv from tests/data):
    
    import pandas as pd
    import sys
    from pprint import pprint

    df = pd.DataFrame.from_csv("./data/iris.csv")

    try:
        raise KeyError()
    except:
        # info is populated correctly here
        print sys.exc_info()
        pprint(df)
        # info is now (None, None, None)
        print sys.exc_info()
        # trying to re-raise error causes TypeError as it is trying to raise 'None'
        raise

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.6.final.0
python-bits: 32
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None

pandas: 0.14.0
nose: 1.3.3
Cython: None
numpy: 1.8.1
scipy: 0.14.0
statsmodels: 0.5.0
IPython: 2.1.0
sphinx: 1.2.2
patsy: 0.2.1
scikits.timeseries: 0.91.3
dateutil: 2.2
pytz: 2014.3
bottleneck: 0.8.0
tables: 3.1.1
numexpr: 2.4
matplotlib: 1.3.1
openpyxl: 1.8.6
xlrd: 0.9.3
xlwt: 0.7.5
xlsxwriter: 0.5.5
lxml: 3.3.5
bs4: 4.3.2
html5lib: 0.999
bq: None
apiclient: None
rpy2: None
sqlalchemy: 0.9.4
pymysql: None
psycopg2: None

**Comment by jreback** [comment]
closing as stale. pls reopen if still an issue.
