### ISSUE TITLE
ENH: DataFrame.to_csv support for "compression='gzip'"

### ISSUE THREAD

**Issue by francescomalandrino** [pydata/pandas#7615]
the DataFrame.to_csv method seems to accept a "compression" named parameter:

```
import numpy as np,pandas as pd
data=np.arange(10).reshape(5,2)
df=pd.DataFrame(data,columns=['a','b'])
df.to_csv('test.csv.gz',compression='gzip')
```

However, the file it creates is not compressed at all:
francesco@i3 ~/Desktop $ cat test.csv.gz 
,a,b
0,0,1
1,2,3
2,4,5
3,6,7
4,8,9

How about either (i) actually implementing compression, or at least (ii) raise an error? The current behavior is confusing...

**Comment by dhimmel** [comment]
+1, a compression argument for `DataFrame.to_csv` would spare many user headaches.

In Python 3.4, I use the following workaround:

```python
with gzip.open('path_to_file', 'wt') as write_file:
    data_frame.to_csv(write_file)
```

**Comment by shoyer** [comment]
@dhimmel If you're interested in putting in the work, I think we're still open to a PR to add this feature.

**Comment by dhimmel** [comment]
@shoyer, okay I will keep this in mind. I have a [bit to learn](https://github.com/pydata/pandas/blob/master/CONTRIBUTING.md) first.

**Comment by rbrito** [comment]
Thank you so much for implementing this! Besides the aesthetics POV and fixing the asymmetry between read/write, this is a huge improvement to some people like me.

**Comment by jsmedmar** [comment]
This did not work for me, the output file isn't compressed. I'm using Pandas 0.18.1

**Comment by TomAugspurger** [comment]
@jsmedmar could you open a new issue with that demonstrating the problem? Thanks.

**Comment by indera** [comment]
@jsmedmar I see the "compression" argument is properly documented and it is working 
http://pandas.pydata.org/pandas-docs/version/0.19.0/generated/pandas.DataFrame.to_csv.html

One confusing thing is that if you run the following code 

```
import numpy as np
import pandas as pd

data = np.arange(10).reshape(5, 2)
df = pd.DataFrame(data, columns=['a', 'b'])
print(df)
df.to_csv('test.csv.gz', compression='gzip')
"""
   a  b
   0  0  1
   1  2  3
   2  4  5
   3  6  7
   4  8  9
"""

```

you get a compressed file, but opening it in vim automatically decompresses it, so to verify that compression happened use the "head" command:

$ head test.csv.gz
D5X�test.csv�70
