### ISSUE TITLE
Plot method ignores upper and lower error bar arguments

### ISSUE THREAD

**Issue by theandygross** [pydata/pandas#7643]
This seems to be specific to Pandas as opposed to matplotlib.  Worked as desired as of a few months ago when I last updated from master.

This is the desired behavior in matplotlib:

```python
barh([0,1], [.3, .5], xerr=[[.1,.2], [.3,.4]],
     color = ['red','green'],
     ecolor='black')
```
![image](https://cloud.githubusercontent.com/assets/1308430/3450982/6507afc8-0189-11e4-9ea6-2cb3b417a9c0.png)

In the Pandas call, it seems to ignore the second error bar argument, both the upper and lower bounds of the error bar are the same:

```python
s = pd.Series([.3,.5])
s.plot(kind='barh', xerr=[[.1,.2], [.3,.4]],
       color = ['red','green'],
       ecolor='black')
```
![image](https://cloud.githubusercontent.com/assets/1308430/3450991/928769fc-0189-11e4-9b16-670a6c98ce66.png)

**Comment by jreback** [comment]
closing as stale. pls reopen if still an issue.
