### ISSUE TITLE
BUG: sqrt not implemented in df.eval 

### ISSUE THREAD

**Issue by acorbe** [pydata/pandas#7677]
In the following scenario:

    import pandas as pd
    import numpy as np

    a = np.random.rand(1000)
    df = pd.DataFrame({'a' : a })

This call doesn't work (while it is supposed to, I guess)

    df.eval('sqrt(a)')

         NotImplementedError: 'Call' nodes are not implemented

while this one does

    df.eval('(a)**(.5)')

I guess this is a bug.

**Comment by xmnfw** [comment]
The same problem with log function.

**Comment by jreback** [comment]
this was closed by #10953 and is available in 0.17.0
