### ISSUE TITLE
COMPAT:  drop support for python 2.6

### ISSUE THREAD

**Issue by cpcloud** [pydata/pandas#7718]
will close #8760 at same time 

The slowest of the slow of Linux distributions (RHEL) has upgraded their version of Python to 2.7. I think if they're happy with not supporting 2.6, then we can be too. Supporting it is not a *huge* deal, but it would be nice to really encourage people to move forward with upgrading to later versions of Python which would provide the community with momentum towards Python 3. While we can't force everyone to use Python 3, I think dropping support for Python 2.6 is reasonable. The last binary release of Python 2.6 was 2.6.6 and that was in 2010. By now, most people are using python 2.7.

**Comment by jreback** [comment]
any objections to slating this for 0.18.0 (prob next year)

cc @jorisvandenbossche @cpcloud @shoyer @wesm @sinhrks @TomAugspurger

**Comment by wesm** [comment]
Sounds fine to me.

**Comment by jreback** [comment]
and conda no longer building for 2.6 (though I can build those as well)

**Comment by cpcloud** [comment]
Fine by me

**Comment by tacaswell** [comment]
As a data point, mpl is dropping support for py2.6 with 1.5/2.0.  Both should still work with 2.6, but our 2.1 is going to include things which break on 2.6 (traitlets and ordered dicts).

Sorry to be forcing your hand here a bit.

**Comment by jreback** [comment]
@tacaswell no, its really that lots of others are dropping this support, e.g. conda builds and such. We don't *have* to do this, but its been slated for a while.
