### ISSUE TITLE
read_csv C engine hangs on my server

### ISSUE THREAD

**Issue by JakeEhrlich** [pydata/pandas#7752]
so I have a web application where users need to be able to upload csv files. If I use the c engine the whole thing hangs indifferently. I was able to read_csv hanging. 

code:
data = smart_unicode(data) #convert to unicode properly
frames = {"default":pandas.read_csv(io.StringIO(data))}

where 'data' is a Unicode string output by Django's 'smart_unicode'. The same issue occurs if you use data = data.decode('utf-8'). The issue does not occur if I use the python engine however. 

I am running an apache 2 server with django 1.6 and mod_wsgi. I have no clue what is causing this however.

**Comment by jreback** [comment]
closing as not repro
