### ISSUE TITLE
Pandas import blocking in Pycharm debug mode

### ISSUE THREAD

**Issue by myisis** [pydata/pandas#7755]
I'm not sure about the exact circumstances and am unable to create a minimal example, but when trying to run an application importing pandas in debug mode through Pycharm, it freezes. I followed the call stack to:
```
try:
    import numexpr as ne
    _NUMEXPR_INSTALLED = ne.__version__ >= LooseVersion('2.0')
except ImportError:  # pragma: no cover
    _NUMEXPR_INSTALLED = False
```
in `expressions.py` (the actual import). I continued to trace the call stack a bit more into `numepxr` to `cpuinfo.py` at `cpu = cpuinfo()` (`DarwinCPUInfo` where it calls `command_info` which eventually forks a new process ("machine") and never returns).

I'm running Mac OS X Maverick, Python 2.7.5, pandas 0.14.0 and numexpr 2.4. This problem doesn't occur when running the application in Pycharm (as opposed to running in debug mode and setting breakpoints). It also doesn't happen when I import pandas right at the beginning of the application (my failed attempt to construct a minimal example).

**Comment by jreback** [comment]
closing as stale. pls reopen if still an issue.
