### ISSUE TITLE
pivot_table / groupby with miss value in Index

### ISSUE THREAD

**Issue by cloga** [pydata/pandas#7837]
Hello,

When I try to use multi-index which has some miss value, to build a pivot table, I find pandas take a strange behavior.

Pandas will autofill nan value with the value just above this index value, and this may give a wrong result , which make the value of second last index equal to its value plus nan value.

萧玮                                   0
ＮＨＫソフトウェア                            0
Name: 5, Length: 27137, dtype: int64

（監督） - 楠葉宏三          1
ＮＨＫソフトウェア         8827
Name: 5, Length: 27137, dtype: int64

As you can see above, I use director to group movie data ,  and some movie has no director data.

The first one is I just use director to groupby data ,  and it will auto ignore nan index, so the value ＮＨＫソフトウェア is low.

The second is I use director and other value to do multi-index pivot_table and then I groupby the value with director to see the data about director. This last data (ＮＨＫソフトウェア) has a very high value. Pandas auto fill the nan index with the index value just above it , in this situation is  ＮＨＫソフトウェア .

Is it a issue or I need do some work before do pivot_table with nan index?

**Comment by jreback** [comment]
closing as stale. pls reopen if still an issue.
