### ISSUE TITLE
Give all NotImplementedErrors a description

### ISSUE THREAD

**Issue by hayd** [pydata/pandas#7872]
Currently some NotImplementedErrors don't have a description (most do!) .

    raise NotImplemented
    # should be
    raise NotImplemented("short description of thing which isn't implemented")

I think this would be pretty useful, and makes it less confusing for users, and at least they would be pointed in the right direction to request said feature (and know which bit of specifically is NotImplemented)...

You can find them all with grep (probably more usefully the same regex in your text editor):

    grep "NotImplementedError$" pandas/**/*.py -r -n

**Comment by hoh** [comment]
Starting to work on this

**Comment by hoh** [comment]
The regular expression above is not perfect, sometimes `NotImplementedError()` is raised.

**Comment by jreback** [comment]
thanks!
