### ISSUE TITLE
Api: shared axis of plot

### ISSUE THREAD

**Issue by rlmajewski** [pydata/pandas#7919]
I know that Series.plot() of dataframe.plot() has sharey and sharex arguments, but would'nt it be nicer if it wasnt only boolean, but also could be used to set axe which should be common ? 
Example:
```
fig, axes = plt.subplots(3,2)
seriesA.plot(ax=axes[1][0])
seriesB.plot(ax= axes[2][1], sharey=axes[1][0])
```

even though matplotlib's plot has that kind of argument, i cannot acces it via kwds because sharey and sharex are already used as arguments in pandas

**Comment by jreback** [comment]
closing as stale. pls reopen if still an issue.
