### ISSUE TITLE
pandas MultiIndex series "unstack" to scipy sparse array functionality

### ISSUE THREAD

**Issue by cottrell** [pydata/pandas#8048]
related #4343
 
I have found myself on occasion writing code to convert from a pandas Series (with n-level MultiIndex) to a scipy sparse n-dim array (plus dimension labels) and back. I am not terribly familiar with the newer sparse data structure features but my impression is that it provides a totally different kind of functionality. Does this kind of functionality exist somewhere? If not, would something like this be of interest?

**Comment by jreback** [comment]
closed by #9076

**Comment by kernc** [comment]
Does anyone object to `SparseSeries` [no longer having a `to_coo()`/`from_coo()` methods](https://github.com/pandas-dev/pandas/issues/15634) in favor of `SparseDataFrame` providing roughly the same API (accepting sparse matrices in the constructor and implementing a somewhat simpler `to_coo()`)?

Please discuss here in https://github.com/pandas-dev/pandas/issues/15634.

**Comment by cottrell** [comment]
I haven't read through the new SparseDataFrame api yet but I think the main convenience with the _coo methods was for the to_coo in the case len(row_levels)>1 or len(column_level)>1 where you need to effectively turn an index of tuples into a single index and get at the codes. There are probably better ways to do this by directly accessing the internals (index labels and hashing tricks on arrays).

For my understanding, is there a replacement function that passes the tests for to_coo and only uses the SparseDataFrame api or would this be a bit of a feature drop (probably fine if no one else is using this stuff)?

**Comment by kernc** [comment]
@cottrell sorry for the delay. Scipy sparse only supports 2d matrices, so with a multi-level indexed series, one would first transform/unstack into a 2d sparse dataframe and then call `.to_coo()` on it. Like:
```py
# Old .to_coo()
>>> ss = pd.SparseSeries(
...     [3.0, 1.0, 3.0],
...     index=pd.MultiIndex.from_tuples([(1, 2, 'a', 0),
...                                      (1, 1, 'b', 0),
...                                      (1, 1, 'b', 1)],
...                                      names=['A', 'B', 'C', 'D']))
>>> ss
A  B  C  D
1  2  a  0    3.0
   1  b  0    1.0
         1    3.0
dtype: float64
BlockIndex
Block locations: array([0], dtype=int32)
Block lengths: array([3], dtype=int32)
>>> A, rows, columns = ss.to_coo(row_levels=['A', 'B'],
...                              column_levels=['C', 'D'],
...                              sort_labels=True)
>>> A.toarray()
array([[ 0.,  1.,  3.],
       [ 3.,  0.,  0.]])
>>> rows
[(1, 1), (1, 2)]
>>> columns
[('a', 0), ('b', 0), ('b', 1)]

# Instead, we could ... (new)
>>> ss2 = ss.copy()
# ... use any means to make a two-level index
>>> ss2.index = pd.MultiIndex.from_tuples([(v[:2], v[2:])
...                                        for v in ss.index.values],
...                                       names=['AB', 'CD'])
>>> ss2
AB      CD    
(1, 2)  (a, 0)    3.0
(1, 1)  (b, 0)    1.0
        (b, 1)    3.0
dtype: float64
BlockIndex
Block locations: array([0], dtype=int32)
Block lengths: array([3], dtype=int32)

# Would work either way because series unstacks into a sparse data frame ...
>>> sdf = ss2.unstack()
>>> sdf
Out[34]: 
CD      (a, 0)  (b, 0)  (b, 1)
AB                            
(1, 1)     NaN     1.0     3.0
(1, 2)     3.0     NaN     NaN

# ... which has .to_coo()
>>> A = sdf.to_coo()
>>> A
<2x3 sparse matrix of type '<class 'numpy.float64'>'
	with 3 stored elements in COOrdinate format>
>>> A.toarray()
array([[ 0.,  1.,  3.],
       [ 3.,  0.,  0.]])
>>> sdf.index  # rows
Index([(1, 1), (1, 2)], dtype='object', name='AB')
>>> sdf.columns.tolist()  # columns, as a list
[('a', 0), ('b', 0), ('b', 1)]
```
Unstacking `SparseSeries` [currently doesn't work](https://github.com/pandas-dev/pandas/issues/16614), but is fixed in https://github.com/pandas-dev/pandas/pull/16616.

**Comment by cottrell** [comment]
Yeah, that functionally seems to cover it. I have a feeling from_tuples is pretty bad performance wise. 

It seems like all the usefulness of that features really comes down to just being able to efficiently create codes for groups of levels (merging levels like you show above). After that, it is just record keeping to get the labels. Do you know if there is a more efficient version of something like this somewhere in the pandas code base?
```

def index_hash(*codes):
    m = len(codes[0])
    n = len(codes)
    a = np.empty((m, n), dtype=np.int64)
    for i in range(n):
        a[:,i] = codes[i]
    a = np.apply_along_axis(lambda x: hash(x.data.tobytes()), 1, a)
    return a

def index_hash_from_df(df, levels=None, catcols=None):
    assert (levels is not None) or (catcols is not None), 'Must not both be None'
    codes = list()
    if levels is not None:
        for level in levels:
            codes.append(df.index.labels[df.index._get_level_number(level)].values())
    if catcols is not None:
        for catcol in catcols:
            codes.append(df[catcol].cat.codes.values)
    return index_hash(*codes)
```

**Comment by jreback** [comment]
@cottrell looks like you need generalized data hashing, try

```pandas.util.hash_pandas_object``` these are highly performant (and used internally in indexing)
