### ISSUE TITLE
read_html parse_dates not working

### ISSUE THREAD

**Issue by mjsu** [pydata/pandas#8159]
Hi,

I am using read_html to pull data from a table. Several of the columns are parsed as dates incorrectly. If I use parse_dates=False this has no effect. Using infer_types=False works, but it is going to be deprecated.

Sorry if I'm not reporting this correctly, new to GitHub ;-)

```python
import pandas as pd
url = "http://www.ironman.com/triathlon/events/emea/ironman/france/results.aspx?p=1&rd=20050618#axzz38t1BwRL6"
dfs = pd.io.html.read_html(url, attrs = {'id': 'eventResults'}, parse_dates=False)#, infer_types=False)
print dfs[0]
```
------------------
commit: None
python: 2.7.8.final.0
python-bits: 64
OS: Darwin
OS-release: 13.3.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8

pandas: 0.13.1
Cython: 0.20.1
numpy: 1.8.1
scipy: 0.14.0
statsmodels: 0.5.0
IPython: 2.1.0
sphinx: 1.2.2
patsy: 0.2.1
scikits.timeseries: None
dateutil: 1.5
pytz: 2014.3
bottleneck: None
tables: 3.1.1
numexpr: 2.3.1
matplotlib: 1.3.1
openpyxl: 2.0.2
xlrd: 0.9.3
xlwt: 0.7.5
xlsxwriter: 0.5.5
sqlalchemy: 0.9.4
lxml: 3.3.5
bs4: 4.3.1
html5lib: 0.999
bq: None
apiclient: None

**Comment by jreback** [comment]
closing as stale. pls reopen if still an issue.
