### ISSUE TITLE
BUG: data frame plot hangs when logx True and some x are zero

### ISSUE THREAD

**Issue by danfrankj** [pydata/pandas#8216]
In [1]: import pandas as pd
    In [2]: import matplotlib.pyplot as plt
    In [3]: import numpy as np
    In [8]: pandas.version.version 
    Out[8]: '0.14.1'
    In [9]: x = [1,0]
    In [10]: y= [2,3]
    In [11]: df = pd.DataFrame()
    In [12]: df['x'] = x
    In [13]: df['y'] = y
    In [14]: df
    Out[14]: 
       x  y
    0  1  2
    1  0  3
    In [15]: df.plot('x', 'y', kind = 'scatter')
    Out[15]: <matplotlib.axes.AxesSubplot at 0x10d366590>
    In [16]: plt.show() # this works
    In [17]: df.plot('x', 'y', logx = True, kind = 'scatter')
    Out[17]: <matplotlib.axes.AxesSubplot at 0x10d39bf10>
    In [18]: plt.show() # hangs forever

**Comment by jreback** [comment]
closing as stale. pls reopen if still an issue.
