### ISSUE TITLE
read_csv() little problem with file_path containing accentuated characters

### ISSUE THREAD

**Issue by danielboone** [pydata/pandas#8228]
Bonjour,
The pd.read_csv() function crash when common latin1 characters (ex: éàèç) occurs in the file path. We can use the following workaround in python 2.7 (Note: I use pandas 0.14 and from __future__ import unicode_literals):
>>> import locale
>>> os_codec = locale.getdefaultlocale()[1]    # this is 'cp1252' on winXP
>>> data = pd.read_csv(myfilepath.encode(os_codec))
However in python 3.4 I can't figure how to do it. We get the following error message:
IOError: Expected file path name or file-like object, got \<class 'byte'\> type.

It would be nice if the getdefaultlocale() could be managed inside pandas instead of at the user level?
Thanks

**Comment by jreback** [comment]
closing as stale. pls reopen if still an issue.
