### ISSUE TITLE
INT: support DatetimeBlock with timezones

### ISSUE THREAD

**Issue by jreback** [pydata/pandas#8260]
to allow real support / conversions of timezone aware Series.
xref #9560; ``DatetimeIndex.to_series()`` can be changed to preserve the tz always

**Comment by ssanderson** [comment]
@jreback I think this affects github.com/zipline in a pretty significant way.  What's involved in implementing this?

**Comment by jreback** [comment]
what do u mean significant way?

**Comment by ssanderson** [comment]
meaning, we do a lot of operations on timezone-aware datetime data in pandas, and from reading https://github.com/pydata/pandas/issues/10192 it looks like that has a nontrivial performance impact.
