### ISSUE TITLE
when a column contains alpha numeric ending with 'e', pandas converts these to float64

### ISSUE THREAD

**Issue by Siva1018** [pydata/pandas#8272]
I'm reading some excel spreadsheets (xlsx format) into pandas using read_excel, which generally works great. The problem I have is that when a column contains alpha numeric ending with 'e', pandas converts these to float64 type without 'e' in its value, and I would like them to be treated as strings. After reading them in, I can convert the column to str:
![screenshot from 2014-09-15 15 26 42](https://cloud.githubusercontent.com/assets/8776889/4269673/36786de8-3cbf-11e4-9d9a-831a6a94edba.png)

dataset = read_excel(excel_file,sheet_name,na_values=[" "])
while reading this excel file to dataset it shows loan id as a number without 'e'

![screenshot from 2014-09-15 15 32 01](https://cloud.githubusercontent.com/assets/8776889/4269740/efee364a-3cbf-11e4-98f7-446f1ad9b8b9.png)

**Comment by jreback** [comment]
closing, but pls reopen if the issue persists.
