### ISSUE TITLE
CLN: Generalized PEP8 Enforcement

### ISSUE THREAD

**Issue by iwschris** [pydata/pandas#8317]
Per @jorisvandenbossche (https://github.com/pydata/pandas/pull/8286#issuecomment-56043336), we need to discuss a generalized way of enforcing PEP8 on the entire pandas code base.

Matplotlib has something similar here: https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/tests/test_coding_standards.py, and here's the PR discussion: https://github.com/matplotlib/matplotlib/pull/1945

Some discussion is probably needed on the PEP8 rules we're alright with ignoring as well as whether or not we want to use 80 or 100 lines for max-line-length (http://legacy.python.org/dev/peps/pep-0008/#maximum-line-length).

**Comment by lexual** [comment]
Perhaps a tool such as yapf could be of use this area also?

https://github.com/google/yapf

**Comment by jreback** [comment]
closing in favor of #11928
