### ISSUE TITLE
Use airspeed velocity for benchmarking

### ISSUE THREAD

**Issue by cpcloud** [pydata/pandas#8361]
Since `vbench` was (at least in part) an inspiration for [Airspeed Velocity](https://github.com/spacetelescope/asv/) (`asv`), I think getting something like this set up for `pandas` would be useful and extremely helpful for us and for `asv`. We have a *ton* of `vbench` code and we'd probably be a great project for pushing the boundaries of and finding edge cases in `asv`. This would also be a great for someone to get to know the scale of datasets for which pandas was designed.

Here's a nice demo of `astropy` using `asv`: http://mdboom.github.io/astropy-benchmark

**Comment by jorisvandenbossche** [comment]
Apparently @qwhelan did already some work on this: https://github.com/spacetelescope/asv/issues/194
