### ISSUE TITLE
Read_csv not correctly opening file

### ISSUE THREAD

**Issue by ChrisLeahy** [pydata/pandas#8380]
I'm trying to open part of a csv file using pandas read_csv. The section I am opening has a header on line 746, and goes to line 1120.

  ```python
 df = read_csv(inputfile,header=746,nrows=374,index_col=False)
```

I then get an error

CParserError: Error tokenizing data. C error: Expected 9 fields in line 1121, saw 17

The error makes sense, because in line 1121 of the file, the data changes from 9 fields to 17. What doesn't make sense is why it is trying to read line 1121, as the nrows and header should only open lines up to 1120.

I can get it to work by decreasing the number of rows to below 232. This still works even if I increase the header number so it starts further down the file (eg increase it to 800).

There doesn't seem to be anything special about the last line it will read, and it will read lines further in the file if I increase the header number. Other similar files work fine.

The file is available at  http://filedropper.com/lowerove

**Comment by jreback** [comment]
closing, but pls reopen if the issue persists.
