### ISSUE TITLE
DataFrame.from_csv doesn't use universal mode file opening

### ISSUE THREAD

**Issue by antgonza** [pydata/pandas#8495]
`DataFrame.from_csv` doesn't account for Windows' new lines. In the current implementation it returns a single row `DataFrame`, which is not accurate. The online suggested solution is to do something like: `mydata = csv.reader(open(mypath,'rU'))` but implementing within that method might be better. 

cc: @ElDeveloper

**Comment by jreback** [comment]
closing, but pls reopen if the issue persists.

**Comment by ElDeveloper** [comment]
It seems to have been fixed now, thanks!
