### ISSUE TITLE
Feature request: Series.flatmap, DataFrame.flatmap

### ISSUE THREAD

**Issue by kay1793** [pydata/pandas#8517]
I'm working on some language analysis and using pandas to munge the data and grab some descriptive stats. This is just an illustrative example, I'm doing all kinds of slighty different things.

Suppose I have a series containing chunks of text, and I want to turn the line into multiple lines, preserving the index values. Here are the naive results:

```python
In [53]: s=pd.Series(['This is text No 1.', 'and here is no. 2','and 3'],index=['Alice','Bob','Alice'])
    ...: s
Out[53]: 
Alice    This is text No 1.
Bob       and here is no. 2
Alice                 and 3
dtype: object

In [54]: s.map(lambda x: x.split(' '))
Out[54]: 
Alice    [This, is, text, No, 1.]
Bob       [and, here, is, no., 2]
Alice                    [and, 3]
dtype: object

In [55]: s.apply(lambda x: pd.Series(x.split(' ')))
Out[55]: 
          0     1     2    3    4
Alice  This    is  text   No   1.
Bob     and  here    is  no.    2
Alice   and     3   NaN  NaN  NaN
```

What I'd like is to be able to do is (Made up example):

```python
In [67]: s.flatmap(lambda x: x.split(' '))
Out[67]: 
Alice    This
Alice    is
Alice    text
Alice    No
Alice    1.
Bob     and
Bob    here
Bob    is
Bob    no.
Bob    2
Alice   and
Alice  3
dtype: object
```
In general, I'd like to be able to explode a single row in a dataframe into multiple rows, by transforming one column value into multiple values, each becoming a new row with the value of other columns prserved, for example:
```python
In [69]: df=pd.DataFrame([['2014-01-01','Alice',"A B"],['2014-01-02','Bob','C D']],columns=['dt','name','text'])
    ...: df
Out[69]: 
           dt   name text
0  2014-01-01  Alice  A B
1  2014-01-02    Bob  C D

In [70]: df.flatmap(lambda x: x.split(),on='text')
           dt   name text
0  2014-01-01  Alice  A
1  2014-01-01  Alice  B
2  2014-01-01    Bob  C
3  2014-01-01    Bob  D
```

Perhaps there's another way to do this, but that's how my natural instict suggests this should be done, flatmap is a fairly universal concept.
Groupby already does similar things based on return type, It doesn't have to be limited to groupby though.

**Comment by jreback** [comment]
closing, but pls reopen if the issue persists.

**Comment by rcompton** [comment]
Just came across this and I think it's worth reopening.

Some sugar for `flatmap`/`explode` would be nice. There are several workarounds circulating and none of them are quite the same, eg.

+ http://www.markhneedham.com/blog/2015/03/23/python-equivalent-to-flatmap-for-flattening-an-array-of-arrays/
+ https://stackoverflow.com/questions/31080258/pysparks-flatmap-in-pandas
+ https://stackoverflow.com/questions/32468402/how-to-explode-a-list-inside-a-dataframe-cell-into-separate-rows

**Comment by jreback** [comment]
We would take a cookbook of the recipes (the https://stackoverflow.com/questions/31080258/pysparks-flatmap-in-pandas) is most idiomatic.

**Comment by rcompton** [comment]
Which of the solutions in https://stackoverflow.com/questions/31080258/pysparks-flatmap-in-pandas accomplishes this task?

**Comment by timotta** [comment]
This how I'm doing for now. It's not the more performatic way, but works:

```
def flatmap(df, func):
    rows = []
    cols = df.columns
    for r in df.values:
        index = 0
        row = {}
        for col in cols:
            row[col] = r[index]
            index += 1
        multrows = func(row)
        for rr in multrows:
            rows.append(rr)
    return pd.DataFrame.from_records(rows)
```

```
flatfunc = lambda r: [{"userId": r["userId"], "rating": r["rating"], "genre": genre} for genre in r["genreList"]]
flattened = flatmap(df, flatfunc)
```

**Comment by wesm** [comment]
i'm supportive of adding a `flatmap` function to pandas. Even more so I would like to have a first class list/array type.

**Comment by rcalsaverini** [comment]
Is this being considered? I think having a flatMap or bind operation would be very interesting and useful. 

I had a use-case today. I have a dataframe of events, with start time and end time:


event | start_time           | end_time             |
------|----------------------|----------------------|
  A   | 2014-01-01 12:00:00  | 2014-01-01 13:45:00  |
  B   | 2014-01-01 12:45:00  | 2014-01-01 12:55:00  |
 ...  |        ...           |       ...            |


And we'd like to transform this to a dataframe that has a row for each minute where an event where actually happening:

 event | time                   |
 ------|------------------------|
   A   | 2014-01-01 12:00:00    |
   A   | 2014-01-01 12:01:00    |
   A   | 2014-01-01 12:02:00    |
   A   | 2014-01-01 12:03:00    |
  ...  |          ...           |
   A   | 2014-01-01 13:44:00    |
   A   | 2014-01-01 13:45:00    |
   B   |          ...           |


There are lots of ways to do this, but if we had a flatMap method this would be almost trivial.

**Comment by rcompton** [comment]
I've been using @timotta 's function above which has been surprisingly fast

**Comment by BLMeltdown** [comment]
The topic I reference in the above link (https://stackoverflow.com/questions/12680754/split-pandas-dataframe-string-entry-to-separate-rows) also leads to https://stackoverflow.com/questions/17116814/pandas-how-do-i-split-text-in-a-column-into-multiple-rows.

**Comment by hkhatod** [comment]
I have a long text in one of the dataframe columns I need to be able to split the text 2 or more columns depending on the length of that cell

**Comment by stuz5000** [comment]
Was this closed because of opposition of storing lists in dataframes/series?

I don't think that flatmap requires this, and the lack of flatmap is a fairly big problem with non-trivial and non-performant solutions. (+scala, spark, many other functional system have it as a first class operation).

**Comment by jreback** [comment]
see https://github.com/pandas-dev/pandas/issues/16538 which has a PR
associated with it

**Comment by tantofish** [comment]
> This how I'm doing for now. It's not the more performatic way, but works:
> 
> ```
> def flatmap(df, func):
>     rows = []
>     cols = df.columns
>     for r in df.values:
>         index = 0
>         row = {}
>         for col in cols:
>             row[col] = r[index]
>             index += 1
>         multrows = func(row)
>         for rr in multrows:
>             rows.append(rr)
>     return pd.DataFrame.from_records(rows)
> ```
> 
> ```
> flatfunc = lambda r: [{"userId": r["userId"], "rating": r["rating"], "genre": genre} for genre in r["genreList"]]
> flattened = flatmap(df, flatfunc)
> ```

Works great for me. Thanks!

Slightly modified to simplify and be more similar to the original poster's wishing syntax:
```python
def flatmap(self, func):
    rows = []
    for idx, row in self.iterrows():
        multrows = func(row)
        rows.extend(multrows)
    return pd.DataFrame.from_records(rows)

pd.DataFrame.flatmap = flatmap

df.flatmap(lambda x: ....)
```
