### ISSUE TITLE
DataFrame throws MemoryError (pandas/lib.c:9308)

### ISSUE THREAD

**Issue by jbrockmendel** [pydata/pandas#8525]
I didn't find any search results for this particular Exception:

```
>>> df2 = pandas.DataFrame(df_data, index=df_ind, columns=df_cols)
python(86000,0x7fff7a7aa310) malloc: *** mach_vm_map(size=200447690256384) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/pandas/core/frame.py", line 243, in __init__
    arrays, columns = _to_arrays(data, columns, dtype=dtype)
  File "/Library/Python/2.7/site-packages/pandas/core/frame.py", line 4639, in _to_arrays
    dtype=dtype)
  File "/Library/Python/2.7/site-packages/pandas/core/frame.py", line 4760, in _list_of_dict_to_arrays
    content = list(lib.dicts_to_array(data, list(columns)).T)
  File "lib.pyx", line 443, in pandas.lib.dicts_to_array (pandas/lib.c:9308)
MemoryError
```

If it matters, df_data is a list of dictionaries, on the order of 10^4 entries, with about 10 keys apiece.  df_ind and df_cols are lists of datetime objects and integers, respectively.  Before this error was thrown, Activity Monitor registered this process as taking about 200 MB of memory.  I can recreate the contents of these lists if needbe.

Shortly afterwards I tried the same thing without passing columns:

```>>> df3 = pandas.DataFrame(df_data, index=df_ind)```

This crashed my system, but I got a screenshot before rebooting:
![dataframescreenshot](https://cloud.githubusercontent.com/assets/8078968/4586172/3e9e5332-5012-11e4-8a3c-e5d9be2975a0.png)

![activitymonitorscreenshot](https://cloud.githubusercontent.com/assets/8078968/4586167/39f9dfae-5012-11e4-892a-9b8cb9c253a6.png)

Immediately before this command, PID 86000 was at ~200 MB and kernel_task was ~1 GB.  After I killed the process, kernel_task fell pretty quickly.

Possibly relevant version information:

```
>>> import pandas
>>> from pandas.util.print_versions import show_versions
>>> show_versions()
INSTALLED VERSIONS
------------------
commit: None
python: 2.7.5.final.0
python-bits: 64
OS: Darwin
OS-release: 13.4.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

pandas: 0.14.0
nose: 1.3.3
Cython: 0.20.2
numpy: 1.8.1
scipy: 0.14.0
statsmodels: 0.5.0
IPython: 2.1.0
sphinx: None
patsy: 0.2.1
scikits.timeseries: None
dateutil: 2.2
pytz: 2013b
bottleneck: None
tables: 3.1.1
numexpr: 2.4
matplotlib: 1.3.1
openpyxl: 1.8.5
xlrd: 0.9.3
xlwt: None
xlsxwriter: None
lxml: 3.3.5
bs4: 4.3.2
html5lib: None
bq: None
apiclient: None
rpy2: None
sqlalchemy: None
pymysql: None
psycopg2: None
```

Let me know if I can provide any more useful information.

**Comment by jreback** [comment]
closing, but pls reopen if the issue persists.
