### ISSUE TITLE
to_datetime conversion inconsistency in 0.15.0

### ISSUE THREAD

**Issue by pmart123** [pydata/pandas#8615]
to_datetime is not converting input consistently between a pandas series or a python list of either strings or datetime objects.  for example:

import pandas as pd
s = pd.Series(['102214','102314'])
df = pd.Series({'dates':['102214','102314']})
lst = ['102214','102314']

pd.to_datetime(s,format='%m%d%y') and pd.to_datetime(df['dates'],format='%m%d%y') return a numpy.datetime64 ndarray, while pd.to_datetime(lst,format='%m%d%y') returns a pandas.DateTimeIndex object.  Is this behavior an expected result in 0.15.0?

**Comment by jorisvandenbossche** [comment]
This was closed by #8921
