### ISSUE TITLE
PERF: perform .str operations on categoricals

### ISSUE THREAD

**Issue by jreback** [pydata/pandas#8627]
So huge win to perform .str operations on the ``.categories`` of a ``Categorical`` (versus actually doing these on an object array), when you have << number of categories relative to the number of objects.

**Comment by JanSchulz** [comment]
IMO, this should be closed in favor of #8640...

**Comment by jreback** [comment]
@JanSchulz you mean #10661  right? (which mostly solves the problem ,though does blow back to ``object`` arrays), I suspect you get almost all of the perf gains.   I fact want to add a little benchmark in the perf suite?

**Comment by JanSchulz** [comment]
Nope: I understand this issue that you want all `.str` function work on a shrinked down dataset of unique values.

You could actually do that now by simple calling the `codes, categories = factorize(values, sort=True)` and using that as a kind of categorical. On the other hand, that would do a factorice on *all* string methods (and does not cache it), so the penalty is still there.

Today (as of  #10661) you can do `s.astype("categorical").str.whatever()` and get that behaviour (if you cache the cat yourself). But this has the problem that you get the categorical behaviour: no `s+s`, no arbitrary new string values,...

IMO the real solution is to build a "PandasString" class in the same spirit as "Categorical" and use that:  `s.astype("pdstring").str.whatever()`. And that's #8640

**Comment by jreback** [comment]
closing in favor of #8640
