### ISSUE TITLE
0.15.0 test_stata  strikes back on various less common platforms on 

### ISSUE THREAD

**Issue by yarikoptic** [pydata/pandas#8688]
e.g. 64bit big-endian
https://buildd.debian.org/status/fetch.php?pkg=pandas&arch=s390x&ver=0.15.0-1&stamp=1414699796
and others
https://buildd.debian.org/status/package.php?p=pandas
(some have other failures as well, yet to find a moment to "analyze", but e.g. hurd-i386 fails test_precise_conversion)

could/should all stata tests be skipped on big-endians?

**Comment by bashtage** [comment]
@yarikoptic This patch should fix.  Thanks for your help with the SPARC account.
