### ISSUE TITLE
API/ENH: support datetime.time in a Timedelta

### ISSUE THREAD

**Issue by jreback** [pydata/pandas#8698]
So this as expected. Though I its pretty straightforward to add support for this directly to a Timedelta, after the notion is the same, *though* a ``time`` object can support a time-zone so not sure if this is odd (or maybe we should add an optional tz to Timedelta).

```
In [5]: from datetime import time

In [6]: time(secIn [8]: pd.Timedelta(time(second=1))
ValueError: Value must be Timedelta, string, integer, float, timedelta or convertible

In [9]: pd.Timedelta('1s')          
Out[9]: Timedelta('0 days 00:00:01')
```

**Comment by jorisvandenbossche** [comment]
What is the best way to convert a column of times to a timedelta? As 

```
pd.to_timedelta(hours=df['time'].dt.hour, minutes=df['time'].dt.minute, seconds=df['time'].dt.second)
```
or 
```
df['time'].apply(lambda x: datetime.timedelta(hours=x.hour, minutes=x.minute, seconds=x.second))
```

seems not very concise

**Comment by jreback** [comment]
actually this is a dupe of  #8343

**Comment by jreback** [comment]
as I said, I think this type is useless. Those solns's are fine for the very limited amount this comes up. An in-between soln is to allow conversion directly to ``Timedelta`` which is not that hard.

**Comment by jorisvandenbossche** [comment]
@jreback I think it are two different things, how I understand it.

In this issue, it is proposed that you can provide a `datetime.time` object to `pd.to_timedelta` to convert it to a timedelta (just as you can also provide strings, ints, ..). 
#8343 is about integrating `datetime.time` in the pandas internals as a timedelta (which will lead to automatic conversion of `datetime.time` to timedeltas), which is a much more profound question (and not something I am in favor of)
