### ISSUE TITLE
DataReader should cache queries.

### ISSUE THREAD

**Issue by femtotrader** [pydata/pandas#8713]
Hello,

each request using `pandas.io.data.DataReader` ends by a server request.
That's not reasonable.
Maybe a cache for DataReader should be considered.

Kind regards

**Comment by kay1793** [comment]
> I think this is out-of-scope for pandas directly. That said if someone wanted to implemented this (via the requests library, I think we would accept it).

This is another jreback-ism that is crazy confusing to me (like [opt-in features disrupt performance](https://github.com/pydata/pandas/issues/8578) and [segfaults are not a problem](https://github.com/pydata/pandas/issues/9205)). 

If it is out of scope why would you accept a PR from someone? strange to see when at the same time #8961 (etc') talks about pandas suffering from feature creep.

**Comment by jreback** [comment]
@kay1793 let try to have constructive comments
thank you for all you contributions

**Comment by kay1793** [comment]
@jreback, I'm trying but you censoring criticism and erasing comments isn't helping.
Would you please explain what you mean by it is out of scope but will accept PR? I still find this confusing.

**Comment by MichaelWS** [comment]
I will step in.  This is a discussion about separating pandas datareader functionality from pandas.

Pandas is intended to be a middleware data layer.

**Comment by davidastephens** [comment]
This was added to pandas-datareader v0.2.1, so this issue can be closed.
