### ISSUE TITLE
ERR: parser.pyx raises lots of nonspecific IOErrors

### ISSUE THREAD

**Issue by ischwabacher** [pydata/pandas#8738]
For example:

```python
In [1]: import pandas as pd

In [2]: pd.read_csv('/root')
---------------------------------------------------------------------------
IOError                                   Traceback (most recent call last)
...
IOError: Initializing from file failed
```

The ones I've noticed so far can be fixed by calling the appropriate `PyErr_*` function at the site of the error in `io.c` and fixing the `cdef extern from "parsers/io.h"` section to `except NULL` from the modified functions.

There's even one instance of `raise IOError` that only happens on ENOMEM.  :/

**Comment by jreback** [comment]
these are reported nicely in even 0.18.1

```
In [1]: pd.read_csv('/root')

IOError: File /root does not exist
```

so if you have another example on a more current pandas, pls open a new issue.
