### ISSUE TITLE
Qt support reworked.

### ISSUE THREAD

**Issue by datalyze-solutions** [pydata/pandas#8788]
I've rewritten the current qtpandas model and uploaded it to my pandas fork:
https://github.com/datalyze-solutions/pandas/tree/qt4/pandas/sandbox

Its still in sandbox. An example can be found in tests named TestApp.py. I just testet Qt4 and python2.7, Qt5 might be interesting.

Any reviews are welcome! :smiley:

**Comment by jreback** [comment]
closing as qt support is now deprecated, see #9615
