### ISSUE TITLE
ENH: add .normalize() to Timestamp?

### ISSUE THREAD

**Issue by jorisvandenbossche** [pydata/pandas#8794]
From http://stackoverflow.com/questions/26882499/reset-time-part-of-a-pandas-timestamp#26882499

There is now a `DatetimeIndex.normalize()` method to set times to midnight. 
Would it be useful to also have this method available on the individual `Timestamp` object?

Further, this method could also be added to the `.dt` accessor (udpate: for this, there already is a similar issue: #5502).

**Comment by jreback** [comment]
closed by #9623
