### ISSUE TITLE
API: preferred way to check if column/Series has Categorical dtype

### ISSUE THREAD

**Issue by jorisvandenbossche** [pydata/pandas#8814]
From http://stackoverflow.com/questions/26924904/check-if-dataframe-column-is-categorical/26925340#26925340

What is the preferred way to check for categorical dtype?

I now answered:

```
In [42]: isinstance(df.cat_column.dtype, pd.core.common.CategoricalDtype)
Out[42]: True

In [43]: pd.core.common.is_categorical_dtype(df.cat_column)
Out[43]: True
```

But:

- this seems somewhat buried in pandas. Should there be a more top-level function to do this?
- we should add the preferred way to the categorical docs.

**Comment by shoyer** [comment]
Another option (see #9629) is that the preferred way to check if a series is categorical should be `hasattr(s, 'cat')`. This will work with pandas 0.16 or newer and sidesteps the numpy comparison issues...
