### ISSUE TITLE
HDF corrupts data when using complib='blosc:zlib'

### ISSUE THREAD

**Issue by bashtage** [pydata/pandas#8874]
I'm not sure if this is supported or not -- it isn't in the doc string for HDFStore, but it seems to be allowed by the HDFStore (nothing is raised).

Unfortunately so far I can only get it to show the bad behavior on a proprietary dataset, which is storing a `pd.Panel` which contains items of of mixed types.  

Some of the float values are be changed from small (|x|<1.0) to very large (3.xe+308).

Is the compressor just passed through to pytables? If so, this might be a pytables issue.

```
pd.show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.8.final.0
python-bits: 64
OS: Linux
OS-release: 2.6.32-431.23.3.el6.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

pandas: 0.15.1-24-g54e237b
nose: 1.3.4
Cython: 0.21.1
numpy: 1.9.1
scipy: 0.14.0
statsmodels: 0.7.0.dev-c8e980d
IPython: 2.3.1
sphinx: 1.2.3
patsy: 0.3.0
dateutil: 1.5
pytz: 2014.9
bottleneck: None
tables: 3.1.1
numexpr: 2.3.1
matplotlib: 1.4.2
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
httplib2: None
apiclient: None
rpy2: None
sqlalchemy: 0.9.8
pymysql: None
psycopg2: None
```

**Comment by jreback** [comment]
closed by #10341
