### ISSUE TITLE
File size increase by import/export from/to Stata

### ISSUE THREAD

**Issue by ozak** [pydata/pandas#9062]
Hi,

I have noticed that importing/exporting data from/to Stata seems to increase file size a lot (sometimes more than double). I thought it mostly was caused by export to Stata, where string variables would be initially set to a length of 256 or something like that (usually after exporting I have to run the compress command in Stata and save the file again in order to save space). But now I noticed that importing data in Stata format and then exporting it to CSV causes similar increases in file size, even after dropping variables from the original file (so one would expect the file to be smaller). Any ideas of what is going on? 

An example of a stata file with the exported csv file and script can be found [here](https://www.dropbox.com/s/xdimn6k40t7fmf4/Export_filesize_issue.zip?dl=0).

I ran the following commands in a script (included in the zip file):

    #!/usr/bin/env python
    # coding: utf-8
    from __future__ import division
    import sys, os, time
    # Math, data
    import numpy as np
    import pandas as pd
    
    # Print filesize original
    print('Original filesize= '+str(os.path.getsize('./cn59_mat.dta'))) #Original filesize= 2883761
    # Load data
    df=pd.read_stata('cn59_mat.dta')
    # Drop one variable
    df.drop('index', axis=1, inplace=True)
    # Export
    df.to_csv('cn59.csv', encoding='utf-8', index=False)
    # Print filesize original
    print('New filesize= '+str(os.path.getsize('./cn59.csv'))) #New filesize= 4984671

So as you can see it doubled in size. I am using Python 2.7.6 with Pandas 0.15.1 on OS X 10.9.

**Comment by bashtage** [comment]
The increase in CSV is natural - floats require 4 bytes and double require 8 bytes when binary, but can require > 8 characters to represent in ACSII, and so are larger.

The stata file is virtually identical in size.

**Comment by jreback** [comment]
closing as not an issue
