### ISSUE TITLE
API: datetimeindex subtraction

### ISSUE THREAD

**Issue by jreback** [pydata/pandas#9094]
from [SO](http://stackoverflow.com/questions/27502406/convert-pandas-datetimeindex-to-fractional-day-of-year) and previous discussions

currently you cannot subtract 2 datetimeindexes ('-' is actually a set op). This is the ONLY valid numerical type of operation (e.g. you cannot add dti).

We current support pretty much the fully gamut of obvious ops, with ``dti-dti`` being the exception.

full list of tests are here: https://github.com/pydata/pandas/blob/master/pandas/tseries/tests/test_base.py#L434

I will propose

``dti.sub(dti)`` to rectify this

thoughts

**Comment by jorisvandenbossche** [comment]
@jreback I think we should revisit this for 0.16 (or at least the deprecation)

We do want to be able to do numeric operations, so we should deprecate the set operation (in theory this was already deprecated in 0.15, but for datimeindexes, there was not deprecation warning raised)

on master:
```
In [6]: dti = pd.date_range('2012-01-01', periods=2)

In [7]: dti - dti
Out[7]: Index([], dtype='object')
```

**Comment by jreback** [comment]
yes could deprecate the actual subtraction op (which is the only thing left) on dti - dti for 0.16
(as .difference is the way to go)

**Comment by jreback** [comment]
@jorisvandenbossche this is in 0.19.0rc1 right? (need to check the issue)

**Comment by jorisvandenbossche** [comment]
Yes, indeed, but this issue was in the end for raising the deprecation warning, so I didn't reference it from the PR (but is could be referenced). PR that changed the setop to timedelta is https://github.com/pydata/pandas/pull/14164
