### ISSUE TITLE
Groupby "negative dimensions are not allowed" error and bad key behaviour when there are NaNs values.

### ISSUE THREAD

**Issue by jordeu** [pydata/pandas#9096]
On a groupby with a composed key if the product of all possible values is bigger than 2^63 we get a `ValueError "negative dimensions are not allowed"` when we call `len(grouped_data)`.

A simple version to reproduce it:
```python
values = range(55109)
data = pd.DataFrame.from_dict({'a': values, 'b': values, 'c': values, 'd': values})
grouped = data.groupby(['a', 'b', 'c', 'd'])
len(grouped)
```

A side effect of this error is that if there are NaN values as possible keys it won't ignore them, it will replace the NaN values with some other values present in the index.

Here there is a complete IPython notebook example to reproduce it:
http://nbviewer.ipython.org/gist/jordeu/cd86fc99f5f89451cf93

**Comment by mpschr** [comment]
any progress on this issue?

**Comment by jreback** [comment]
well, pull-requests are welcome.

This of course should be fixed, but you can avoid by not grouping by all available columns (which causes the error).

**Comment by jreback** [comment]
give a try on master, just merged in #9380 which fixes this.

**Comment by jordeu** [comment]
Perfect, I've tested on master and now it's working. Thanks!

**Comment by rth** [comment]
Just got this issue when doing a groupby on a large number of columns with high cardinality with pandas 1.0.3. I'm not sure it was fully fixed. Also there is https://github.com/pandas-dev/pandas/issues/31355.

**Comment by wangxiaoying** [comment]
> Just got this issue when doing a groupby on a large number of columns with high cardinality with pandas 1.0.3. I'm not sure it was fully fixed. Also there is #31355.

got the same problem in pandas 1.0.3

**Comment by lisovskey** [comment]
got this error too with `groupby`

**Comment by jreback** [comment]
you will have to open. new issue with a reproducible example in the latest released version and even better showing something exists in master
