### ISSUE TITLE
API: dedicated plot methods like plot.scatter as an alternative to using kind

### ISSUE THREAD

**Issue by shoyer** [pydata/pandas#9124]
Currently, we use the `plot` for every possible kind of plot, and switch between them using the `kind` keyword argument.

From an API design and discoverability perspective, this seems less than ideal. If we had separate methods, standard introspection tools like IPython and autocomplete could help users figure out which arguments are applicable for which type of plot with less reliance on the documentation. 

Another option is to make a `.plot` also an accessor, so we could have `df.plot.scatter` and so forth. But I suspect `.plot_scatter` would be a bit more discoverable.

**Comment by shoyer** [comment]
It sounds like there is support for preserving the `kind` argument to `plot`, while also making `plot` an accessor with more specific sub-methods?

**Comment by dalejung** [comment]
+1. I like the idea of typing `plot.<TAB>` and getting a list of the plotting universe.

**Comment by TomAugspurger** [comment]
I'm Ok with this too. As far as implementation goes, do we have a df/series.plot callable that dispatches off the kind argument and then add the different .bar, .line ... methods as attributes? Do we have any examples of similar methods?

**Comment by jreback** [comment]
for implementation see here: https://github.com/pydata/pandas/blob/master/pandas/tseries/common.py#L55

just create a subclass of PandasDelegate and this is quite easy

**Comment by sinhrks** [comment]
Yeah, having both should be better. `kind` is for programming and `plot` accessor. 

I think reason of current plotting complexity is also caused by lots of options which are rarely used. Let me list up as separate issue.

**Comment by shoyer** [comment]
I have a preliminary PR up at #9321. This should be a reasonable framework (I've verified that introspection seems to work properly with IPython), but I could definitely use help assembling appropriate function signatures and docstrings :).
