### ISSUE TITLE
Wired behavior: 0 / dataframe = inf while 0.0 / dataframe = 0.0

### ISSUE THREAD

**Issue by skinnymonkey** [pydata/pandas#9144]
```
In [3]: s = pd.Series([1.0, 2.0])

In [4]: 0 / s
Out[4]:
0    inf
1    inf
dtype: float64

In [5]: 0.0 / s
Out[5]:
0    0
1    0
dtype: float64
```

This is seems quite wired. Should not 0/s be 0 as well?

**Comment by Garrett-R** [comment]
Good catch @skinnymonkey!  I think there's actually two problems related problems.  The other was that:

    Series([0, 1]) / 0

turned out to evaluate to `Series([np.inf, np.inf])` instead of `Series([np.nan, np.inf])`.
