### ISSUE TITLE
Runtime terminate it in an unusual way

### ISSUE THREAD

**Issue by adriangeostat** [pydata/pandas#9150]
Hello Pandas developers. 

Running any python script with the pandas produce 'Runtime to terminate it in an unusual way'

To reproduce the error use:
- Pandas version 0.15.2, C Python 
- Python 2.7.6 (default, Nov 10 2013, 19:24:18) [MSC v.1500 32 bit (Intel)] on win32
- SO windows 7

create a python script (myfile.py) with the line of code 
import pandas as pd

run the code with 
c:\my_path>python myfile.py
This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

Kind regards 
Adrian

**Comment by jreback** [comment]
it is not recommended to actually compile on windows. and if you do, you need to use MS C++.
see [here](http://pandas.pydata.org/pandas-docs/stable/install.html) for installation instructions.

not exactly sure what version/libraries are shipped with XY Python. I have compiled successfully using ``conda`` (and ``libpython`` on windows however).

**Comment by superlou** [comment]
When not compiling Pandas on Windows, what is the suggested source?  I have tried `pip install pandas`, `pip install --upgrade pandas`, and `pip install (whl file)` from the [unofficial Python extension] builds(http://www.lfd.uci.edu/~gohlke/pythonlibs/).  All give the same exception when doing `python -c "import pandas"`.  I'm on Windows Python 2.7 32-bit trying to install Pandas 0.18.1.
