### ISSUE TITLE
import pandas hangs save file matplotlib dialog

### ISSUE THREAD

**Issue by AlexanderKUA** [pydata/pandas#9153]
Hello, such code
```python
    import pandas
    import matplotlib.pyplot as plt
    plt.plot([1, 2, 3])
    plt.show()
```
freezes  matplotlib file save dialog (the same issue with wxpython FilePickerCtrl).

![pyplothang](https://cloud.githubusercontent.com/assets/4736996/5553536/bd49ddae-8c2c-11e4-8084-0ba68d378550.png)

What is the reason of such issue? How to avoid it?

**Comment by AlexanderKUA** [comment]
No, no problems if don't import pandas.

**Comment by jreback** [comment]
pls ``pd.show_versions()`` and how you installed pandas.

**Comment by AlexanderKUA** [comment]
INSTALLED VERSIONS
    ------------------
    commit: None
    python: 2.7.7.final.0
    python-bits: 64
    OS: Windows
    OS-release: 8
    machine: AMD64
    processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
    byteorder: little
    LC_ALL: None
    LANG: None

    pandas: 0.14.0
    nose: 1.3.3
    Cython: 0.20.1
    numpy: 1.8.1
    scipy: 0.14.0
    statsmodels: 0.5.0
    IPython: 2.1.0
    sphinx: 1.2.2
    patsy: 0.2.1
    scikits.timeseries: None
    dateutil: 1.5
    pytz: 2014.3
    bottleneck: 0.8.0
    tables: 3.1.1
    numexpr: 2.3.1
    matplotlib: 1.3.1
    openpyxl: 1.8.6
    xlrd: 0.9.3
    xlwt: 0.7.5
    xlsxwriter: 0.5.7
    lxml: 3.3.5
    bs4: 4.3.1
    html5lib: None
    bq: None
    apiclient: 1.2
    rpy2: None
    sqlalchemy: 0.9.4
    pymysql: None
    psycopg2: None

I've installed using `pip install pandas`

**Comment by AlexanderKUA** [comment]
Can't reproduce in 0.16.1
