### ISSUE TITLE
area plots are causing my unit tests to fail

### ISSUE THREAD

**Issue by argriffing** [pydata/pandas#9161]
I'm using the latest matplotlib and pandas.  If you run the following code, do the legends look right to you?  The unit tests don't like them.
```python
df = DataFrame(
            np.random.rand(10, 3),
            index=list(string.ascii_letters[:10]))
df.plot(kind='area', subplots=True, sharex=True, legend=True)
```

**Comment by jreback** [comment]
ok, so this is a reverse-bug fix, e.g. when matplotlib 1.5 is out, pandas needs to compensate?

**Comment by tacaswell** [comment]
Yes, but I think it should (eventually) result in simplification of your code.  

Can someone point me to where the relevant bit of code is and I can try to provide said compensation.

**Comment by jreback** [comment]
@TomAugspurger 
cc @sinhrks 

can you provide a link?

**Comment by sinhrks** [comment]
@tacaswell , @jreback
Here it is. Maybe `AreaPlot._add_legend_handle` can be removed after 1.5?
https://github.com/pydata/pandas/blob/master/pandas/tools/plotting.py#L1756
