### ISSUE TITLE
Index._shallow_copy does not handle data types

### ISSUE THREAD

**Issue by behzadnouri** [pydata/pandas#9170]
integer index with float data types:

    >>> i
    Int64Index([1, 2], dtype='int64')
    >>> i._shallow_copy(i.values.astype('f8'))
    Int64Index([1.0, 2.0], dtype='float64')

another issue: an index which is not equal to its copy:

    >>> i
    Float64Index([1.0, 2.0], dtype='float64')
    >>> j = i._shallow_copy(i.values.astype('O'))
    >>> j
    Float64Index([1.0, 2.0], dtype='object')
    >>> j.equals(i)
    False
    >>> j.equals(j.copy())
    False

**Comment by jreback** [comment]
this is an internal routine. I suppose the documentation could be improved. This has an implicit guarantee that the user behaves correctly. Changing the dtype is not allowed.
