### ISSUE TITLE
Implement a DataFrame.view() method to interactively display data

### ISSUE THREAD

**Issue by wavexx** [pydata/pandas#9179]
R has a very rudimentary function (utils::View()) to display data interactively. On X11 it's so broken I basically never used it, yet, it would be very nice if pandas had something similar.

With python, there's tabview: https://github.com/firecat53/tabview/

which can be used as a module as well:

    import tabview.tabview as t
    t.view([matrix data])

This runs a full-screen curses interfaces with a simple spreadsheet like display, which is actually *much* nicer than what R offers.

I've started to use and customize the cli wrapper a lot (display X,Y coordinates, etc), to the point that I would like direct integration with DataFrame.

Would such a patch be accepted?

**Comment by jreback** [comment]
@wavexx are you proposing including ``tabview`` as an included library with pandas? or something else?

**Comment by wavexx** [comment]
On 01/02/2015 06:11 PM, jreback wrote:
> @wavexx are you proposing including ``tabview`` as an included
> library with pandas? or something else?

I'm open for ideas.

It could start with a "view()" method that tries to import tabview, with
tabview being only a suggested package.

But we could add a submodule if having it as part of the package is a
desirable thing. I would be a bit against a flat copy, since I'd like
the development of tabview to continue also as a stand-alone viewer.

I would also love to have some sort of flexible viewer mechanism such as
the "PAGER" environment variable, but for data. Setting TABVIEW=tabview
could allow other tools to emerge. One example would be an X11
alternative if DISPLAY is set. The only downside is that it would
require saving/parsing the data again, so the built-in tabview is still
desiderable when TABVIEW is empty.

**Comment by scls19fr** [comment]
Hello,

a quite ugly solution is available here

    import pandas.io.data as web
    import datetime
    start = datetime.datetime(2010, 1, 1)
    end = datetime.datetime(2013, 1, 27)
    panel = web.DataReader(["F", "YHOO"], 'yahoo', start, end) # Panel
    df = panel.loc[:,:,"F"] # DataFrame
    ts=df['Adj Close'] # Series

    t.view(df.reset_index().transpose().reset_index().transpose().values)

    t.view(ts.reset_index().transpose().reset_index().transpose().values)

    t.view(panel.to_frame().reset_index().transpose().reset_index().transpose().values)

I hope it can helps.

Kind regards

Sébastien

**Comment by wavexx** [comment]
Why the double transpose?

    with df.reset_index() as df:
        t.view([df.columns.tolist()] + df.values.tolist()

seems to work.

**Comment by scls19fr** [comment]
Because of the double `reset_index()` (one for index, one for columns)

**Comment by wavexx** [comment]
On 01/05/2015 01:29 PM, scls19fr wrote:
> Because of the double `reset_index()` (one for index, one for
> columns)

I guessed, but why not just concatenating the columns separately as I
did in the last example?

If Series are the reason, I would put a specialized view() method in its
class.

**Comment by scls19fr** [comment]
I thought that converting numpy array to list and concatenating 2 python lists wasn't a great idea. But `timeit` could show us that.

    In [10]: %timeit df.reset_index().transpose().reset_index().transpose().values
    100 loops, best of 3: 6.81 ms per loop

    In [11]: %timeit [df.columns.tolist()] + df.values.tolist()
    1000 loops, best of 3: 351 µs per loop

and I was wrong

**Comment by scls19fr** [comment]
I wonder if on Pandas side we shouldn't have only

    import tabview.tabview as t
    t.view(self)

inside Pandas DataFrame, Series and Panel `view()` method
and some update of `tabview` to support Pandas inputs like https://github.com/firecat53/tabview/pull/59

**Comment by wavexx** [comment]
The idea of having a generic view method that could be overridden is good. Specialized methods in DataFrame/Series/Panel could reuse it in an uniform way.

This would solve the problem of having a _generic_ data visualizer.

Still, pandas should come with a built-in/working method in order for the feature to catch on.
I'm hoping to fix a couple of issues with tabview in order to be used as a module and them re-visit the proposal.

**Comment by wavexx** [comment]
We're pulling in native support for Pandas into tabview itself, so I consider this no longer an issue for Pandas.
