### ISSUE TITLE
_SQL_TYPES restriction causing data to be truncated

### ISSUE THREAD

**Issue by hanleyhansen** [pydata/pandas#9196]
Why is this hardcoded to 63?

https://github.com/pydata/pandas/blob/master/pandas/io/sql.py#L1212

It's causing my data to be truncated. Should I submit a PR to change it to text?

-Hanley

**Comment by rockg** [comment]
I, too, have always found this frustrating.  However, I don't think that changing to TEXT is necessarily what we want to do given this [SO](http://stackoverflow.com/questions/2023481/mysql-large-varchar-vs-text).  Maybe that is invalid and it always makes sense to have TEXT.  If not, we should at least make the length a settable parameter and add a warning if there is any string length larger than that value.  Also, one should be able to change the column type to TEXT if one so pleases.

To get around this, I always truncated my data adjusted the table and then reinserted.

**Comment by hanleyhansen** [comment]
That makes sense. I'm having a hard time tracking down what it is exactly that is causing the failure among all this random. I'm using Pandas to convert a legacy filePro system to a mysql table that I use to actually curate the data I need. That said, I can't do much about the original data.

**Comment by jorisvandenbossche** [comment]
There has been a report/discussion about this previously, and I don't know if there is any good reason apart from historical one ("it has been like that before", but I don't know why it was done this way initially).

But anyway, you should **not** be using this code anymore, but update to use the new version depending on `sqlalchemy`. Firstly, this older mysql support is deprecated and will be removed in 0.16 or 0.17. And secondly, the new version with sqlalchemy is much more flexible and will not have this problem by default.

**Comment by jorisvandenbossche** [comment]
To specify more, using the new sqlalchemy version (providing a sqlalchemy engine to `to_sql`) uses `TEXT` by default (for the reason to not have to specify a default max length, among ohers. But this also causes some probems, see #7957 ), but you can always specify another type: http://pandas.pydata.org/pandas-docs/stable/io.html#sql-data-types.

**Comment by hanleyhansen** [comment]
Makes sense. I'll close this ticket. Thank you!

**Comment by jorisvandenbossche** [comment]
@hanleyhansen And thanks for reporting! I have to agree it is an odd behaviour.

**Comment by hanleyhansen** [comment]
@jorisvandenbossche weird...

It was driving me nuts that I was already on 0.15.2 and still facing issues. Then I realized that I was doing my own thing with chunks and 0.15.2 supported chunks with `to_sql`.

```python
def write_to_db(engine, frame, table_name, chunk_size):

    start_index = 0
    end_index = chunk_size if chunk_size < len(frame) else len(frame)

    frame = frame.where(pd.notnull(frame), None)
    if_exists_param = 'replace'

    while start_index != end_index:
        print "Writing rows %s through %s to %s" % (start_index, end_index, table_name)
        frame.iloc[start_index:end_index, :].to_sql(con=engine, name=table_name, if_exists=if_exists_param)
        if_exists_param = 'append'

        start_index = min(start_index + chunk_size, len(frame))
        end_index = min(end_index + chunk_size, len(frame))
```

I removed that and everything worked all of a sudden. No data truncation error.

**Comment by jorisvandenbossche** [comment]
And `NaN`s should now also be supported out of the box, so the `frame = frame.where(pd.notnull(frame), None)` is also not needed anymore!
