### ISSUE TITLE
Syntax error thrown by python at pandas/scripts/windows_builder/check_and_build.py +52

### ISSUE THREAD

**Issue by tvyomkesh** [pydata/pandas#9224]
Syntax error on line 52 of pandas/scripts/windows_builder/check_and_build.py?

$ python scripts/windows_builder/check_and_build.py
  File "scripts/windows_builder/check_and_build.py", line 52
    password=############
                        ^
SyntaxError: invalid syntax 

Fix: password='############' ?

**Comment by jreback** [comment]
this script is just for reference w/o the password. The point is to have it fail because the password is not there.

**Comment by tvyomkesh** [comment]
ok thanks
