### ISSUE TITLE
read_stata failing with URL

### ISSUE THREAD

**Issue by jseabold** [pydata/pandas#9231]
I'm not entirely sure the root cause yet. It's something to do with the default encoding I think. I'm pretty sure Stata uses `iso-8859-1` not `cp1252`. Changing this inside `pandas.io.maybe_read_encoded_stream` works, but changing the encoding in StataReader breaks something else that I don't have time to debug.

Can someone sanity check me. Does this work on Python 2?

    dta = pd.read_stata("http://www.stata-press.com/data/r13/fullauto.dta")

**Comment by TomAugspurger** [comment]
I get a 

```
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 2644: character maps to <undefined>
```

in python 2.

**Comment by jreback** [comment]
the default encoding is passed (even to a url), so prob should be a bit more inference here.

**Comment by bashtage** [comment]
Is there someone permanent to place a dta file at a URL for testing?

**Comment by bashtage** [comment]
Fixed, waiting for final green.
