### ISSUE TITLE
pip install pandas not working

### ISSUE THREAD

**Issue by PatrickEGorman** [pydata/pandas#9233]
I entered "pip install pandas" in my terminal window to install it into a local environment but the installation looped infinitely and threw up a bunch of errors.  I'm not sure if it is something wrong with pip or my virtual environment but I wanted to see if anybody else was having trouble with this.

**Comment by TomAugspurger** [comment]
Can you post more info about your environment. Platform, python version, how python was installed, pip version, etc.

**Comment by PatrickEGorman** [comment]
OS X 10.9.5
Python 2.7.8
PyCharm Professional 3.4

Environment includes:

Cython==0.20.2
Flask==0.10.1
Flask-Login==0.2.11
Flask-Migrate==1.2.0
Flask-SQLAlchemy==1.0
Flask-Script==2.0.5
Flask-WTF==0.10.0
Jinja2==2.7.3
Mako==1.0.0
MarkupSafe==0.23
Pygments==2.0.1
SQLAlchemy==0.9.7
Sphinx==1.2.3
Tempita==0.5.2
WTForms==2.0.1
Werkzeug==0.9.6
alembic==0.6.7
argparse==1.2.1
decorator==3.4.0
docutils==0.12
facebook-sdk==1.0.0-alpha
gunicorn==19.1.0
invoke==0.9.0
itsdangerous==0.24
-e git+https://github.com/CenterForOpenScience/modular-file-renderer.git@3c78e74ee3827b8a00b4a7f7d075a71981421cfa#egg=mfr-dev
mock==1.0.1
pbr==0.10.0
psycopg2==2.5.3
py==1.4.26
pytest==2.6.4
requests==2.3.0
six==1.7.3
sqlalchemy-migrate==0.9.1
stevedore==0.15
tox==1.8.1
virtualenv==1.11.6
virtualenv-clone==0.2.5
virtualenvwrapper==4.3.1
wheel==0.24.0
wsgiref==0.1.2
wtf==0.1


After a little reading, I see that numpy is required.  Could that be the problem?

**Comment by shoyer** [comment]
@PatrickEGorman Yes, that will be a problem. I definitely recommend installing numpy first. pip is not very well behaved for installing binary dependencies.

**Comment by jreback** [comment]
yep, pip does not install deps automatically. using ``conda`` is also quite easy (which will satisfy deps)
