### ISSUE TITLE
Dataframe.query regex support

### ISSUE THREAD

**Issue by tanmaig** [pydata/pandas#9240]
Hi,
I was wondering if I could make a regex query (re.search say) in the query expression. 
Dataframe.filter supports it. Is there any particular reason that query does not?

**Comment by TomAugspurger** [comment]
As of now, no function calls are allowed within the query. I suspect that it'd be very difficult to implement. Also the idea of writing regexes inside strings, and all the escaping that would probably be needed doesn't sound fun :)

Do you have a small example in mind? I'm guessing you know about `Series.str.match/extract`, but you're trying to do something involving multiple columns?

**Comment by jreback** [comment]
@tanmaig no advantage of doing a regex as it is simply evaluated in pytho space (and cannot use ``numexpr`` which backs ``.query``. you should use ``.str`` as @TomAugspurger indicates
