### ISSUE TITLE
First assignment with logical indexing is slow for Series (but OK for DataFrames)

### ISSUE THREAD

**Issue by vfilimonov** [pydata/pandas#9241]
First assignment with logical indexing is 1000 slower than second, third, etc. for pandas.Series:
```
import pandas.io.data as web
f = web.DataReader("MSFT", 'yahoo')['Adj Close']
%time f[f==0] = np.NaN
%time f[f==0.1] = np.NaN
```
It gives
```
CPU times: user 1.52 s, sys: 1.65 ms, total: 1.52 s
Wall time: 1.52 s
CPU times: user 704 µs, sys: 22 µs, total: 726 µs
Wall time: 720 µs
```

But for DataFrames everything is OK:
```
import pandas.io.data as web
f = web.DataReader(["MSFT","GOOG"], 'yahoo')['Adj Close']
%time f[f==0] = np.NaN
%time f[f==0.1] = np.NaN
```
gives
```
CPU times: user 1.28 ms, sys: 1e+03 ns, total: 1.28 ms
Wall time: 1.28 ms
CPU times: user 1.23 ms, sys: 1 µs, total: 1.23 ms
Wall time: 1.24 ms
```

I used here data from Yahoo!Finance with datetimeindex since I was not able to reproduce this behavior in Series with integer index.

My versions:
pandas: 0.15.2
Cython: 0.21.2
numpy: 1.9.1
dateutil: 2.4.0
pytz: 2014.10
numexpr: 2.4

**Comment by jreback** [comment]
```
In [9]: f = web.DataReader("MSFT", 'yahoo')['Adj Close']

In [12]: f1 = f.copy(deep=True)

In [13]: f2 = f.copy(deep=True)

In [14]: %timeit f[f==0] = np.nan
1000 loops, best of 3: 409 us per loop

In [15]: %timeit f2[f2==0.1] = np.nan
1000 loops, best of 3: 395 us per loop
```

not sure why you would be seeing that

**Comment by jorisvandenbossche** [comment]
@jreback you are using `timeit`, so that will already run it multiple times and not show the (first) slowest

```
In [1]: import pandas.io.data as web

In [2]: f = web.DataReader("MSFT", 'yahoo')['Adj Close']

In [3]: %time f[f==0] = np.nan
Wall time: 49 ms

In [4]: %time f[f==0] = np.nan
Wall time: 3 ms
```

**Comment by vfilimonov** [comment]
Strangely, some overhead related to IPython notebook. In IPython measurements are close to those of @jorisvandenbossche (i.e. ~17 times difference, not 1000):
```
In [4]: %time f[f==0] = np.nan
CPU times: user 17.3 ms, sys: 334 µs, total: 17.7 ms
Wall time: 17.5 ms

In [5]: %time f[f==0] = np.nan
CPU times: user 886 µs, sys: 233 µs, total: 1.12 ms
Wall time: 925 µs
```

in pure python difference is also about 12 for me:
```
>>> import time
>>> f = web.DataReader("MSFT", 'yahoo')['Adj Close']
>>> start = time.time()
>>> f[f==0] = np.nan
>>> print time.time()-start
0.0131120681763
>>> start = time.time()
>>> f[f==0] = np.nan
>>> print time.time()-start
0.00110197067261
```

Checked for `pandas.DataFrame` - there are almost no difference in python/IPython as well.

**Comment by jreback** [comment]
So the first time the assignment happens. The assignment is checked for ``SettingWithCopy``; this involves a ``gc.collect(2)`` to detect the references.


You can avoid this by avoiding this dangling reference in the first place by explictiy copying. (you can also simply set ``sf.is_copy=None``

```
In [3]: import  pandas.io.data as web
In [4]: f = web.DataReader("MSFT", 'yahoo') 

In [6]: sf = f['Adj Close'].copy()

In [7]: %time sf[sf==0] = np.nan
CPU times: user 936 us, sys: 183 us, total: 1.12 ms
Wall time: 950 us

In [8]: %time sf[sf==0] = np.nan
CPU times: user 897 us, sys: 290 us, total: 1.19 ms
Wall time: 871 us
```

**Comment by vfilimonov** [comment]
@jreback, many thanks!
Sorry for the false alarm.

**Comment by jreback** [comment]
np, thanks for raising this. sometimes these are bugs.
