### ISSUE TITLE
*__tmp_to_csv_deprecated_options__ are left behind

### ISSUE THREAD

**Issue by yarikoptic** [pydata/pandas#9249]
which fills up the /tmp on a test box:
```
/tmp# ls -l *tmp_to_csv* | nl | tail
    56  -rw------- 1 buildslave buildslave 1509 Jan 13 08:22 tmpuI3G3o__tmp_to_csv_deprecated_options__
    57  -rw------- 1 buildslave buildslave 1514 Jan 13 06:04 tmpVmc8Qa__tmp_to_csv_deprecated_options__
    58  -rw------- 1 buildslave buildslave 1513 Jan  6 00:19 tmpwHmsVO__tmp_to_csv_deprecated_options__
    59  -rw------- 1 buildslave buildslave 1511 Jan 10 19:19 tmpwmWIUl__tmp_to_csv_deprecated_options__
    60  -rw------- 1 buildslave buildslave 1513 Dec 28 19:57 tmpx480b9bk__tmp_to_csv_deprecated_options__
    61  -rw------- 1 buildslave buildslave 1523 Jan  4 23:21 tmpYpSmZM__tmp_to_csv_deprecated_options__
    62  -rw------- 1 buildslave buildslave 1520 Dec 28 21:47 tmpz55nmj_u__tmp_to_csv_deprecated_options__
    63  -rw------- 1 buildslave buildslave 1526 Jan 10 12:56 tmpzczy25oz__tmp_to_csv_deprecated_options__
    64  -rw------- 1 buildslave buildslave 1513 Dec 28 20:03 tmpZGClRm__tmp_to_csv_deprecated_options__
    65  -rw------- 1 buildslave buildslave 1511 Jan 12 19:56 tmpzktpvkfo__tmp_to_csv_deprecated_options__
```
which seems to come from one of the test_frame tests which is not among failing tests (http://nipy.bic.berkeley.edu/builders/pandas-py2.x-sid-sparc/builds/1141/steps/shell_5/logs/stdio) so should be cleaned up:

**Comment by jreback** [comment]
yeh, these should all be done with the ``ensure_clean`` as a context manager to clean up.

**Comment by jreback** [comment]
```
jreback-~/pandas] grin tmp_to_csv
./pandas/tests/test_frame.py:
 5897 :         pname = '__tmp_to_csv_deprecated_options__'
 5914 :         pname = '__tmp_to_csv_from_csv__'
 6062 :         path = '__tmp_to_csv_moar__'
 6254 :         pname = '__tmp_to_csv_no_index__'
 6268 :         pname = '__tmp_to_csv_headers__'
 6283 :         pname = '__tmp_to_csv_multiindex__'

 # these ok
 #6427 :         with ensure_clean('__tmp_to_csv_float32_nanrep__.csv') as path:
 #6439 :         with ensure_clean('__tmp_to_csv_withcommas__.csv') as path:

13551 :         pname = '__tmp_to_csv_date_format__'
```

**Comment by yarikoptic** [comment]
I only saw the *__tmp_to_csv_deprecated_options__

On Wed, 14 Jan 2015, jreback wrote:

>  jreback-~/pandas] grin tmp_to_csv
>  ./pandas/tests/test_frame.py:
>   5897 :         pname = '__tmp_to_csv_deprecated_options__'
>   5914 :         pname = '__tmp_to_csv_from_csv__'
>   6062 :         path = '__tmp_to_csv_moar__'
>   6254 :         pname = '__tmp_to_csv_no_index__'
>   6268 :         pname = '__tmp_to_csv_headers__'
>   6283 :         pname = '__tmp_to_csv_multiindex__'

>   # these ok
>   #6427 :         with ensure_clean('__tmp_to_csv_float32_nanrep__.csv') as path:
>   #6439 :         with ensure_clean('__tmp_to_csv_withcommas__.csv') as path:

>  13551 :         pname = '__tmp_to_csv_date_format__'

>    -
>    Reply to this email directly or view it on GitHub.

>    Link: https://github.com/pydata/pandas/issues/9249#issuecomment-69922986

-- 
Yaroslav O. Halchenko, Ph.D.
http://neuro.debian.net http://www.pymvpa.org http://www.fail2ban.org
Research Scientist,            Psychological and Brain Sciences Dept.
Dartmouth College, 419 Moore Hall, Hinman Box 6207, Hanover, NH 03755
Phone: +1 (603) 646-9834                       Fax: +1 (603) 646-1419
WWW:   http://www.linkedin.com/in/yarik

**Comment by gliptak** [comment]
I reviewed the occurences of ```__tmp_``` in HEAD and they all use ```ensure_clean```.  Consider closing this issue.

**Comment by jreback** [comment]
we don't need ANY paths explicity set when they are not directly in a ``with ensure_clean``.
I think the ``_tmp_to_csv_moar`` might not be wrapped in a context manger. 
```
pandas/tests/frame/test_to_csv.py:
   41 :         pname = '__tmp_to_csv_from_csv__'
  217 :         path = '__tmp_to_csv_moar__'
  431 :         pname = '__tmp_to_csv_no_index__'
  454 :         pname = '__tmp_to_csv_headers__'
  469 :         pname = '__tmp_to_csv_multiindex__'
  635 :         with ensure_clean('__tmp_to_csv_float32_nanrep__.csv') as path:
  647 :         with ensure_clean('__tmp_to_csv_withcommas__.csv') as path:
 1025 :         pname = '__tmp_to_csv_date_format__'
```

**Comment by gliptak** [comment]
@jreback Yes, I did change the ```__tmp_to_csv_moar__``` flow.
