### ISSUE TITLE
Setting with enlargement fails in presence of MultiIndex

### ISSUE THREAD

**Issue by FedericoV** [pydata/pandas#9250]
```
In [1]:

import pandas as pd
import numpy as np
 
print pd.__version__
 
a = np.linspace(0, 10, 11)
idx = [('test1', i) for i in range(5)]
idx.extend([('test2', i) for i in range(6)])
 
idx = pd.MultiIndex.from_tuples(idx)
0.15.2-80-ge69deae
In [2]:

a = pd.Series(a, idx)
a
Out[2]:
test1  0     0
       1     1
       2     2
       3     3
       4     4
test2  0     5
       1     6
       2     7
       3     8
       4     9
       5    10
dtype: float64
In [3]:

a.loc[('test1', 2)] = 13
a
Out[3]:
test1  0     0
       1     1
       2    13
       3     3
       4     4
test2  0     5
       1     6
       2     7
       3     8
       4     9
       5    10
dtype: float64
In [4]:

a.loc[('test', 17)] = 13
---------------------------------------------------------------------------
IndexingError                             Traceback (most recent call last)
<ipython-input-4-157acf13152f> in <module>()
----> 1 a.loc[('test', 17)] = 13

/home/federico/Python_Libraries/pandas/pandas/core/indexing.pyc in __setitem__(self, key, value)
    114                 if len(key) > self.ndim:
    115                     raise IndexingError('only tuples of length <= %d supported' %
--> 116                                         self.ndim)
    117                 indexer = self._convert_tuple(key, is_setter=True)
    118             else:

IndexingError: only tuples of length <= 1 supported

In [5]:

a.ix[('test', 17)] = 13
---------------------------------------------------------------------------
IndexingError                             Traceback (most recent call last)
<ipython-input-5-89467846f8af> in <module>()
----> 1 a.ix[('test', 17)] = 13

/home/federico/Python_Libraries/pandas/pandas/core/indexing.pyc in __setitem__(self, key, value)
    114                 if len(key) > self.ndim:
    115                     raise IndexingError('only tuples of length <= %d supported' %
--> 116                                         self.ndim)
    117                 indexer = self._convert_tuple(key, is_setter=True)
    118             else:

IndexingError: only tuples of length <= 1 supported
```

Somehow - the enlarging fails.  Any clue how to get it to work?  I have also noticed that the 'fast' indexing methods, iat and at fail with DataFrames that are multi indexed.

**Comment by jreback** [comment]
pls pd.show_versions()

**Comment by FedericoV** [comment]
I will do that asap tomorrow, since it was on my machine at work and I
cannot SSH.  However, it was the very last version, pulled from master and
built ~1 minute before posting that issue.

**Comment by jreback** [comment]
hmm, this should work. I'll mark it as an enhancement. pull-requests are welcome. You can of course use ``append`` to achieve what you want.

``iat/at`` *should* work. pls post an example if that is not the case.

**Comment by FedericoV** [comment]
INSTALLED VERSIONS
------------------
commit: None
python: 2.7.8.final.0
python-bits: 64
OS: Linux
OS-release: 3.13.0-44-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

pandas: 0.15.2-80-ge69deae
nose: 1.3.4
Cython: 0.21
numpy: 1.10.0.dev-d98e57c
scipy: 0.15.0.dev-c3d8771
statsmodels: 0.5.0
IPython: 2.3.0
sphinx: 1.3a0
patsy: 0.2.1
dateutil: 2.2
pytz: 2014.4
bottleneck: None
tables: 3.1.0
numexpr: 2.3.1
matplotlib: 1.3.1
openpyxl: 1.8.2
xlrd: 0.9.3
xlwt: 0.7.5
xlsxwriter: 0.5.2
lxml: 3.3.1
bs4: 4.3.1
html5lib: None
httplib2: 0.9
apiclient: None
rpy2: 2.3.6
sqlalchemy: 0.9.2
pymysql: None
psycopg2: None

**Comment by FedericoV** [comment]
I didn't want to use append because I was using the dataframe as a structure to hold some simulation within a loop, and I wanted to avoid extra copies if possible.

**Comment by jreback** [comment]
it's going to copy with enlargement in either case - you never w
