### ISSUE TITLE
Clipboard functions don't support Unicode on Windows

### ISSUE THREAD

**Issue by jcjf** [pydata/pandas#9263]
Recent versions of pyperclip (``pandas.util.clipboard``) use CF_UNICODETEXT getting data from and putting data to the WIndows Clipboard.

**Comment by jreback** [comment]
what needs to change? what is the probemetic statement? want to do a pull-request? 

pls ``pd.show_versions()``

**Comment by jcjf** [comment]
Currently, git master for pandas is based on pyperclip 1.3, the latest version is 1.5.7. The Unicode features for Windows were added very recently. I'd be tempted to replace the code ``pandas.util.clipboard`` with https://github.com/asweigart/pyperclip/blob/master/pyperclip/__init__.py. I don't know how to compile and test pandas on Windows (I've always used Christoph Gohlke's binaries).

My use case at the office was that I was trying to load clipboard data from Excel that was in Spanish. The current code in ``pandas.util.clipboard`` couldn't handle this. I am at home now but I think a UnicodeDecodeError was thrown - it should be easy to reproduce this issue with non-ASCII clipboard data.

**Comment by jreback** [comment]
ahh, ok. Yes we can just update in master to the new version. Though would like some tests for validation.

**Comment by jcjf** [comment]
Since pyperclip is now a PyPI package, is it better to make it an optional dependency?

**Comment by jreback** [comment]
we could update the ``pyperclip`` package. Don't want to add *another* specific dep (e.g. that you might have to download).

**Comment by jreback** [comment]
closed by #11712
