### ISSUE TITLE
uin8 should be uint8 in io/parsers.py

### ISSUE THREAD

**Issue by rmorgans** [pydata/pandas#9266]
while using read_fwf I had a bug that had this line from parsers.py

https://github.com/pydata/pandas/blob/072e40b0b5beab36c2adda9e0bcbb26755e1928f/pandas/io/parsers.py#L989

in which there is a np.uin8 which I'm pretty sure should be a np.uint8

apologise if this has already been submitted - I did a search on uin8 and only got the offending line in the code.

I just fixed on my arch source code to keep working on my problem (I'm an engineer not a software guy!). I will try and find time for a patch and test (I failed on my last one)

CHeers

Rick

**Comment by jreback** [comment]
can you show some code that actually triggered this? (I agree its buggy/not tested). and I think I know what you did, but just to be clear. Pls show ``pd.show_versions()`` as well.

**Comment by rmorgans** [comment]
Hi - attached is some self contained code that reproduces the bug -
including pd.show_versions. It's basically a head of the file I was trying
to load in and the code that triggered the bug. When I next get some time
I'll try and make this smaller & more suitable for a unit test.

Cheers

Rick

python test_pandas_uin8_bug.py
INSTALLED VERSIONS
------------------
commit: None
python: 3.4.2.final.0
python-bits: 64
OS: Linux
OS-release: 3.14.28-1-lts
machine: x86_64
processor:
byteorder: little
LC_ALL: None
LANG: en_AU.UTF-8
pandas: 0.15.2
nose: 1.3.4
Cython: 0.21.2
numpy: 1.9.1
scipy: 0.15.0
statsmodels: 0.6.1
IPython: 2.3.1
sphinx: 1.2.3
patsy: 0.3.0
dateutil: 2.4.0
pytz: 2014.10
bottleneck: 0.8.0
tables: 3.1.1
numexpr: 2.4
matplotlib: 1.4.2
openpyxl: 2.1.4
xlrd: 0.9.3
xlwt: None
xlsxwriter: 0.6.5
lxml: 3.4.1
bs4: None
html5lib: 0.999
httplib2: None
apiclient: None
rpy2: None
sqlalchemy: 0.9.8
pymysql: None
psycopg2: 2.5.4 (dt dec pq3 ext)
None
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/pandas/io/parsers.py", line 987,
in _convert_to_ndarrays
    values = lib.map_infer(values, conv_f)
  File "pandas/src/inference.pyx", line 1046, in pandas.lib.map_infer
(pandas/lib.c:57158)
  File "test_pandas_uin8_bug.py", line 13, in <lambda>
    'dst':lambda x: int(x,16),
ValueError: invalid literal for int() with base 16: ''
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "test_pandas_uin8_bug.py", line 15, in <module>
    index_col='time')
  File "/usr/lib/python3.4/site-packages/pandas/io/parsers.py", line 496,
in read_fwf
    return _read(filepath_or_buffer, kwds)
  File "/usr/lib/python3.4/site-packages/pandas/io/parsers.py", line 251,
in _read
    return parser.read()
  File "/usr/lib/python3.4/site-packages/pandas/io/parsers.py", line 710,
in read
    ret = self._engine.read(nrows)
  File "/usr/lib/python3.4/site-packages/pandas/io/parsers.py", line 1563,
in read
    data = self._convert_data(data)
  File "/usr/lib/python3.4/site-packages/pandas/io/parsers.py", line 1600,
in _convert_data
    self.verbose, clean_conv)
  File "/usr/lib/python3.4/site-packages/pandas/io/parsers.py", line 989,
in _convert_to_ndarrays
    mask = lib.ismember(values, na_values).view(np.uin8)
AttributeError: 'module' object has no attribute 'uin8'


On Fri, Jan 16, 2015 at 10:59 PM, jreback <notifications@github.com> wrote:

> can you show some code that actually triggered this? (I agree its
> buggy/not tested). and I think I know what you did, but just to be clear.
> Pls show pd.show_versions() as well.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pydata/pandas/issues/9266#issuecomment-70247302>.
>



-- 
Rick Morgans
http://au.linkedin.com/in/rickmorgans
mobile: +61412886830
skype: rick.morgans

**Comment by rmorgans** [comment]
```python
import pandas as pd
print(pd.show_versions())
with open('test.txt','w') as f:
    f.write(
"""1421302964.213420    PRI=3 PGN=0xef00      DST=0x17 SRC=0x28    04 154 00 00 00 00 00 127
1421302964.226776    PRI=6 PGN=0xf002               SRC=0x47    243 00 00 255 247 00 00 71"""
    )
d=pd.read_fwf('test.txt',
              colspecs=[(0,17),(25,26),(33,37),(49,51),(58,62),(63,1000)],
              names=['time','pri','pgn','dst','src','data'],
              converters={'pgn':lambda x: int(x,16),
                          'src':lambda x: int(x,16),
                          'dst':lambda x: int(x,16),
                          'data':lambda x: len(x.split(' '))},
              index_col='time')
```

running this gives

```bash
python test_pandas_uin8_bug.py
INSTALLED VERSIONS
------------------
commit: None
python: 3.4.2.final.0
python-bits: 64
OS: Linux
OS-release: 3.14.28-1-lts
machine: x86_64
processor:
byteorder: little
LC_ALL: None
LANG: en_AU.UTF-8
pandas: 0.15.2
nose: 1.3.4
Cython: 0.21.2
numpy: 1.9.1
scipy: 0.15.0
statsmodels: 0.6.1
IPython: 2.3.1
sphinx: 1.2.3
patsy: 0.3.0
dateutil: 2.4.0
pytz: 2014.10
bottleneck: 0.8.0
tables: 3.1.1
numexpr: 2.4
matplotlib: 1.4.2
openpyxl: 2.1.4
xlrd: 0.9.3
xlwt: None
xlsxwriter: 0.6.5
lxml: 3.4.1
bs4: None
html5lib: 0.999
httplib2: None
apiclient: None
rpy2: None
sqlalchemy: 0.9.8
pymysql: None
psycopg2: 2.5.4 (dt dec pq3 ext)
None
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/pandas/io/parsers.py", line 987,
in _convert_to_ndarrays
    values = lib.map_infer(values, conv_f)
  File "pandas/src/inference.pyx", line 1046, in pandas.lib.map_infer
(pandas/lib.c:57158)
  File "test_pandas_uin8_bug.py", line 13, in <lambda>
    'dst':lambda x: int(x,16),
ValueError: invalid literal for int() with base 16: ''
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "test_pandas_uin8_bug.py", line 15, in <module>
    index_col='time')
  File "/usr/lib/python3.4/site-packages/pandas/io/parsers.py", line 496,
in read_fwf
    return _read(filepath_or_buffer, kwds)
  File "/usr/lib/python3.4/site-packages/pandas/io/parsers.py", line 251,
in _read
    return parser.read()
  File "/usr/lib/python3.4/site-packages/pandas/io/parsers.py", line 710,
in read
    ret = self._engine.read(nrows)
  File "/usr/lib/python3.4/site-packages/pandas/io/parsers.py", line 1563,
in read
    data = self._convert_data(data)
  File "/usr/lib/python3.4/site-packages/pandas/io/parsers.py", line 1600,
in _convert_data
    self.verbose, clean_conv)
  File "/usr/lib/python3.4/site-packages/pandas/io/parsers.py", line 989,
in _convert_to_ndarrays
    mask = lib.ismember(values, na_values).view(np.uin8)
AttributeError: 'module' object has no attribute 'uin8'
```

**Comment by axeltidemann** [comment]
This bug is still present in the 1.6.2 release, and in the 1.7 development branch. I did the same as rmorgans, fixed it in my source code and recompiled. Maybe it should not be marked as closed?

**Comment by jreback** [comment]
this is issue is still open
there have been several pull requests to fix but haven't been followed thru - u are welcome to pick one up and finish up the tests

**Comment by jreback** [comment]
note - iirc there were several big reports to this - u might be looking at one of those

**Comment by axeltidemann** [comment]
I would be more than happy to help out, as I think it is a fantastic piece of software - but the overhead for me to fix just this small typo is a bit big for me right now, unfortunately. Sorry.

**Comment by captainsafia** [comment]
I think I'll take this on.

I'll try to write some solid tests for it.

PR coming soon.
