### ISSUE TITLE
test.sh shows couple of failures on OSX 10.10.1

### ISSUE THREAD

**Issue by tvyomkesh** [pydata/pandas#9281]
Not sure if this is reproducible by others in their enviroment/platform but here is what I am seeing on my machine.

****
FAIL: test_now (pandas.tseries.tests.test_tslib.TestTimestamp)
\----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/tvyomkesh/pandas/pandas/tseries/tests/test_tslib.py", line 343, in test_now
    self.assertTrue((ts_from_string_tz.tz_localize(None) - ts_from_string) < delta)
AssertionError: False is not true
****
FAIL: test_today (pandas.tseries.tests.test_tslib.TestTimestamp)
\----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/tvyomkesh/pandas/pandas/tseries/tests/test_tslib.py", line 359, in test_today
    self.assertTrue((ts_from_string_tz.tz_localize(None) - ts_from_string) < delta)
AssertionError: False is not true

****
Ran 7309 tests in 500.577s
FAILED (SKIP=468, failures=2)

**Comment by jreback** [comment]
pls show ``pd.show_versions()``.

**Comment by tvyomkesh** [comment]
<pre>
In [2]: pd.show_versions()

INSTALLED VERSIONS
------------------
commit: d8a03dae7728e5d9a2f12f0b7b0c784a15c7f322
python: 2.7.9.final.0
python-bits: 64
OS: Darwin
OS-release: 14.0.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

pandas: 0.15.2-95-g5886a1d
nose: 1.3.4
Cython: 0.21.2
numpy: 1.9.1
scipy: 0.14.1
statsmodels: None
IPython: 2.3.1
sphinx: 1.2.3
patsy: None
dateutil: 2.4.0
pytz: 2014.10
bottleneck: None
tables: None
numexpr: None
matplotlib: None
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
httplib2: None
apiclient: None
rpy2: 2.4.2
sqlalchemy: 0.9.8
pymysql: None
psycopg2: None
</pre>

**Comment by sinhrks** [comment]
I'm using OSX 10.10.1 also, and unable to reproduce the issue.

My assumption is a test problem, ``ts_from_string_tz.tz_localize(None)`` which convert tz-aware timestamp to normal timestamp. Maybe your timezone is later than 'US/Eastern'?

My timezone (UTC+9) and each calculation results are as below: 

```
self.assertTrue((ts_from_string_tz.tz_localize(None) - ts_from_string) < delta)
```

- ``ts_from_string_tz.tz_localize(None)``:  2015-01-18 11:52:33.726936
- ``ts_from_string``: 2015-01-17 21:52:33.727108
- ``ts_from_string_tz.tz_localize(None) - ts_from_string)``: -1 days +10:00:00.000172
