### ISSUE TITLE
DOC: Revise "Merge, join, and concatenate" doc with graphical examples

### ISSUE THREAD

**Issue by sinhrks** [pydata/pandas#9301]
I think the doc is little difficult for beginners, because examples use slicing to prepare input which cannot imagine immediately. 

- http://pandas.pydata.org/pandas-docs/stable/merging.html

The alternative is using diagrams like below. I've prepared a function to output it using #6661, thus it can be generated during the doc build. If looks useful, I'll work on it.

![01](https://cloud.githubusercontent.com/assets/1696302/5802744/2ccfbad2-a03b-11e4-93aa-4261242d7abd.png)

![21](https://cloud.githubusercontent.com/assets/1696302/5802759/4bc003e8-a03b-11e4-8d97-d88fcfcb9bf5.png)

**Comment by jorisvandenbossche** [comment]
+1 times a lot

See also http://www.rstudio.com/wp-content/uploads/2015/01/data-wrangling-cheatsheet.pdf for some nice examples how it can be explained graphical (they use some colors as wel to indicate where the orignal data ended up in the result)

**Comment by jreback** [comment]
+1 on this as well
pictures are worth many words!

**Comment by JanSchulz** [comment]
Wow, this is great!
