### ISSUE TITLE
RFE: support dateutil 2.x

### ISSUE THREAD

**Issue by sergiopasra** [pydata/pandas#9305]
Pandas requires dateutil 1.5. This version was released in 2010. There is also a dateutil 2.x series that is currentlu updated. It would be nice if pandas supports datautil 2.x as linux distributions are strating to move away from dateutil 1.5

**Comment by jreback** [comment]
it requires a minimum of 1.5

2.x works just fine

is their some kind of issue?

**Comment by sergiopasra** [comment]
Good to know, but the webpage says datautil 1.5

http://pandas.pydata.org/pandas-docs/version/0.15.2/install.html#dependencies

Perphaps "datautil 1.5 or higher" is better?

**Comment by jreback** [comment]
sure 
would take a pull request to update the doc
