### ISSUE TITLE
bug: read_csv and german umlaut (ä,ö,ü) in filename

### ISSUE THREAD

**Issue by Helgeb** [pydata/pandas#9315]
The following code

    import pandas
    df = pandas.read_csv('C:\\exampleä\\test.csv')

thows an `OSError: File b'C:\\example\xc3\xa4\\test.csv' does not exist`.

This `df = pandas.read_excel('C:\exampleä\test.xlsx', 'test')` and this `open(r'C:\exampleä\test.csv', newline='')` works perfectly.

**Comment by shoyer** [comment]
Can you share `pd.show_versions()`? This is quite likely to be dependent on whether you're running Python 2 or 3.

**Comment by Helgeb** [comment]
INSTALLED VERSIONS
------------------
commit: None
python: 3.3.5.final.0
python-bits: 64
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 42 Stepping 7, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None

pandas: 0.13.1
Cython: 0.20.1
numpy: 1.8.1
scipy: 0.13.3
statsmodels: 0.5.0
IPython: 2.0.0
sphinx: 1.2.2
patsy: 0.2.1
scikits.timeseries: None
dateutil: 2.2
pytz: 2013.9
bottleneck: None
tables: 3.1.1
numexpr: 2.3.1
matplotlib: 1.3.1
openpyxl: None
xlrd: 0.9.3
xlwt: None
xlsxwriter: None
sqlalchemy: 0.9.4
lxml: None
bs4: None
html5lib: None
bq: None
apiclient: None

Now i've tried 
   pandas.read_csv(open('C:\exampleä\example.csv'))
which works.

**Comment by TomAugspurger** [comment]
@Helgeb try this:

`pd.read_csv(u'C:\\exampleä\\test.csv')`

I think it's a unicode issue with the actual string being passed in.

**Comment by shoyer** [comment]
@TomAugspurger This is Python 3. Every string is unicode. I don't think this should make a difference...

**Comment by shoyer** [comment]
@Helgeb Does this work?
```
from urllib.request import urlopen
urlopen('C:\\exampleä\\test.csv').read()
```

**Comment by TomAugspurger** [comment]
Oops, didn't see that in the version info. That's strange.

**Comment by ayr0** [comment]
I wonder if this is windows specfic.  I cannot reproduce this errant behavior on my linux box with either Python 2 or Python 3 and pandas 0.15.2.

**Comment by Helgeb** [comment]
Hi, it works with pandas: 0.14.1, so the bug is already fixed.

**Comment by jmatejka** [comment]
I am having this problem in 15.2 with python 2.7.7, so I'm not sure that it has been fixed (at least in 2.7.7)

Is there a workaround?

**Comment by shoyer** [comment]
@jmatejka Please open a new issue and include the output of `pd.show_versions()`.

**Comment by jmatejka** [comment]
Ok, have done, #9438
