### ISSUE TITLE
Performance regression in .ffill()

### ISSUE THREAD

**Issue by twiecki** [pydata/pandas#9326]
Under pandas 0.12:
```python
In [4]: from pandas import *

In [5]: from numpy.random import randn

In [6]: In [14]: df = DataFrame({'one' : Series(randn(3), index=['a', 'b', 'c']),
   ....:                 'two' : Series(randn(4), index=['a', 'b', 'c', 'd']),
   ....:                 'three' : Series(randn(3), index=['b', 'c', 'd'])})

In [7]: df
Out[7]: 
        one     three       two
a -0.899073       NaN  2.164487
b  0.142272  0.158407 -1.387754
c  0.583869  1.063867  0.542845
d       NaN  0.739295  1.527532

In [8]: df.ffill()
Out[8]: 
        one     three       two
a -0.899073       NaN  2.164487
b  0.142272  0.158407 -1.387754
c  0.583869  1.063867  0.542845
d  0.583869  0.739295  1.527532

In [9]: %timeit df.ffill()
10000 loops, best of 3: 64.4 µs per loop
```
With pandas 0.15:
```python
In [7]: %timeit df.ffill()
The slowest run took 7.81 times longer than the fastest. This could mean that an intermediate result is being cached 
10000 loops, best of 3: 101 µs per loop
```

**Comment by jreback** [comment]
@twiecki this is barely a couple of method calls. Your frame is way to small for this to even matter. Timings should involved at least 10k elements. Pls show your actual usecase.

**Comment by twiecki** [comment]
```
In [49]: size = 20000

In [50]: df = pd.DataFrame(np.random.randn(size, 5))

In [51]: idx = np.random.randint(0, size, size=size*.2)

In [52]: df.values[idx] = np.nan
In [28]: %timeit -n 10000 df.ffill()
10000 loops, best of 3: 561 µs per loop
```

With Pandas 0.15:
```
In [63]: %timeit -n 10000 df.ffill()
10000 loops, best of 3: 604 µs per loop
```

We're upgrading pandas from 0.12 to 0.15.2 on zipline and find some performance regressions in our use of the history function which creates a RollingPanel under the hood: https://github.com/quantopian/zipline/blob/master/zipline/utils/data.py#L28. We're not sure yet what's going on but find a very steep slow down and this is one hypothesis.

**Comment by dalejung** [comment]
fwiw, master and 0.15.2 are faster on my machine.

**Comment by rockg** [comment]
I think there has to be another culprit here.  That kind of change in performance (43 microseconds if I'm reading it right) would be unnoticeable.

**Comment by jreback** [comment]
@twiecki yeh this is a tiny difference 
if u have a more substantive diff pls reopen
