### ISSUE TITLE
read_hdf does not work with auto_close argument 

### ISSUE THREAD

**Issue by wikiped** [pydata/pandas#9327]
When trying to create DataFrame from HDF Store with `auto_close=True` or `False` it breaks with error:
  
    somedf = pd.DataFrame({'a':[1,2], 'b':[3,4]})
    somedf.to_hdf('hdf_file', 'somekey', format='t', mode='w')
    newdf = pd.read_hdf('hdf_file', 'somekey', auto_close=True)
    newdf

error:

	d:\Anaconda\envs\py2k\lib\site-packages\pandas\io\pytables.pyc in <lambda>(store, auto_close)
		303 
		304     f = lambda store, auto_close: store.select(
	--> 305         key, auto_close=auto_close, **kwargs)
		306 
		307     if isinstance(path_or_buf, string_types):

	TypeError: select() got multiple values for keyword argument 'auto_close'

The same without `auto_close` argument works fine:

    newdf = pd.read_hdf('hdf_file', 'somekey')
    newdf

yielding:

       a  b
    0  1  3
    1  2  4

pandas 0.15.2, pytables 3.1.1 on Win8.1x64

**Comment by jreback** [comment]
you don't need to pass this argument to ``read_hdf``,  by definition these are opened/closed correctly.

**Comment by TomAugspurger** [comment]
Should probably remove that from the docstring then. Is there ever a case where auto_closing isn't desired? Performance-sensitive tasks maybe?

**Comment by jreback** [comment]
this is an internal argument for all intents (so maybe change to ``_auto_close``). Because it needs to be called in context.
