### ISSUE TITLE
Partial indexing of MultiIndex fails with empty tuple

### ISSUE THREAD

**Issue by benkuhn** [pydata/pandas#9329]
Indexing the entire MultiIndex works with the empty tuple, and partial indexing works with non-empty tuples, but partial indexing with an empty tuple doesn't. Here's a repro:

```
import pandas as pd
import numpy as np
import itertools

ix_str = pd.MultiIndex.from_tuples(list(itertools.product([('a')], ['a','b','c'])))
ix_tup = pd.MultiIndex.from_tuples(list(itertools.product([()], ['a','b','c'])))

df_str = pd.DataFrame(np.random.rand(10, 3), columns=ix_str)
print df_str[('a')].columns     # Index([u'a', u'b', u'c'], dtype='object')
df_tup = pd.DataFrame(np.random.rand(10, 3), columns=ix_tup)
print df_tup[(), 'a'].index     # Int64Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype='int64')
print df_tup[()].columns
```

PS Thanks for maintaining Pandas, it's awesome!

**Comment by shoyer** [comment]
To get what (I think) you're looking for, try `df_tup[(),]`.

An empty tuple is a pretty pathological key. Checking explicitly for it *is* possible, but I'm not sure it's worth it given it would slow down all indexing.

**Comment by benkuhn** [comment]
Sounds reasonable, and the comma works. Thank you!
