### ISSUE TITLE
Windows wheel package (.whl) on Pypi

### ISSUE THREAD

**Issue by mcarans** [pydata/pandas#9334]
Please make Windows wheel packages and put them on Pypi.

Currently it is possible to download Windows wheel packages for pandas here: http://www.lfd.uci.edu/~gohlke/pythonlibs/#pandas

It would be great if the wheels were directly available on the Pypi server https://pypi.python.org/pypi/ so that they can be installed with pip.

**Comment by jreback** [comment]
hmm what happened to the installers that were there?
 I didn't know he was posting wheels

**Comment by mcarans** [comment]
He decided to replace all the exe files with whl files a few days ago which forced the author of WinPython to make a new version available with an updated Control panel that can install whl files as I understand it.

And so the wheels turn!

**Comment by TomAugspurger** [comment]
It would be nice to offer wheels. I know scikit-learn uses Appveyor (some docs [here](https://packaging.python.org/en/latest/appveyor.html)). We could do something similar.

**Comment by jreback** [comment]
I uploaded the built wheels to pypi. Not sure why no more execs though.

@TomAugspurger I had installed a configuration file for appveyor. But its way slow. Better to just have the windows builds by grohlke for now.

**Comment by mcarans** [comment]
Thanks alot!
