### ISSUE TITLE
convert_objects(convert_dates='coerce') is not coercing to date

### ISSUE THREAD

**Issue by lminer** [pydata/pandas#9342]
Shouldn't `convert_objects(convert_dates='coerce')` be coercing a series of strings to NaTs?

```python
df = pd.DataFrame({'date': ['a', 'b', 'c', 'd']})
df.convert_objects(convert_dates='coerce')
  date
0    a
1    b
2    c
3    d

```

**Comment by jreback** [comment]
this is not completely aggressive. meaning that if EVERYTHING Is coerced its a mistake and doesn't do anything.So this is not a bug but defined behavior.

If you really want this, then you can do:

```
In [10]: pd.to_datetime(['a','b','c'],coerce=True)
Out[10]: 
<class 'pandas.tseries.index.DatetimeIndex'>
[NaT, ..., NaT]
Length: 3, Freq: None, Timezone: None
```
