### ISSUE TITLE
pd.to_timedelta returns Timedelta(0)

### ISSUE THREAD

**Issue by scls19fr** [pydata/pandas#9349]
Hello,

I noticed:

    In [1]: pd.to_timedelta('00:00:00.1')
    Out[1]: Timedelta('0 days 00:00:00.100000')

but

    In [2]: pd.to_timedelta('0.1')
    Out[2]: Timedelta('0 days 00:00:00')

same for

    In [3]: pd.to_timedelta(0.1)
    Out[3]: Timedelta('0 days 00:00:00')

I was expecting it returns `Timedelta('0 days 00:00:00.100000')`

Kind regards

**Comment by jreback** [comment]
```
In [4]: pd.to_timedelta('0.1',unit='s')
Out[4]: Timedelta('0 days 00:00:00.100000')
```

neither of these are legit formats, specify the unit if you want
