### ISSUE TITLE
to_timedelta returns an object of different type depending of Python version

### ISSUE THREAD

**Issue by femtotrader** [pydata/pandas#9353]
Hello,

    import pandas as pd
    from datetime import timedelta
    td=pd.to_timedelta('00:00:15')
    
Python 2

    td
    Timedelta('0 days 00:00:15')

    isinstance(td, timedelta)
    True

but with Python 3

    td
    numpy.timedelta64(15000000000,'ns')

    isinstance(td, timedelta)
    False

Kind regards

**Comment by jreback** [comment]
pls shiw_versions

**Comment by femtotrader** [comment]
In [15]: pd.show_versions()

    INSTALLED VERSIONS
    ------------------
    commit: None
    python: 3.3.5.final.0
    python-bits: 64
    OS: Darwin
    OS-release: 14.0.0
    machine: x86_64
    processor: i386
    byteorder: little
    LC_ALL: None
    LANG: fr_FR.UTF-8

    pandas: 0.14.1
    nose: 1.3.4
    Cython: 0.21
    numpy: 1.9.0
    scipy: 0.14.0
    statsmodels: 0.5.0
    IPython: 2.2.0
    sphinx: 1.2.3
    patsy: 0.3.0
    scikits.timeseries: None
    dateutil: 2.1
    pytz: 2014.7
    bottleneck: None
    tables: 3.1.1
    numexpr: 2.3.1
    matplotlib: 1.4.0
    openpyxl: 1.8.5
    xlrd: 0.9.3
    xlwt: None
    xlsxwriter: 0.5.7
    lxml: 3.4.0
    bs4: 4.3.2
    html5lib: 0.999
    httplib2: None
    apiclient: None
    rpy2: None
    sqlalchemy: 0.9.7
    pymysql: None
    psycopg2: None

**Comment by femtotrader** [comment]
In [2]: pd.show_versions()

    INSTALLED VERSIONS
    ------------------
    commit: None
    python: 2.7.9.final.0
    python-bits: 64
    OS: Darwin
    OS-release: 14.0.0
    machine: x86_64
    processor: i386
    byteorder: little
    LC_ALL: None
    LANG: fr_FR.UTF-8

    pandas: 0.15.2
    nose: 1.3.4
    Cython: 0.21
    numpy: 1.9.1
    scipy: 0.15.0
    statsmodels: 0.5.0
    IPython: 2.3.1
    sphinx: 1.2.3
    patsy: 0.3.0
    dateutil: 1.5
    pytz: 2014.9
    bottleneck: None
    tables: 3.1.1
    numexpr: 2.3.1
    matplotlib: 1.4.0
    openpyxl: 1.8.5
    xlrd: 0.9.3
    xlwt: 0.7.5
    xlsxwriter: 0.5.7
    lxml: 3.4.0
    bs4: 4.3.2
    html5lib: 0.999
    httplib2: None
    apiclient: None
    rpy2: None
    sqlalchemy: 0.9.7
    pymysql: None
    psycopg2: None

**Comment by jreback** [comment]
try 0.15 or greater 
this is changed quite substantially

**Comment by femtotrader** [comment]
Sorry I didn't noticed that my pandas version was different on Py 2 and Py 3
