### ISSUE TITLE
PERF: nunique perf can be improved by using len(unique) rather than value_counts

### ISSUE THREAD

**Issue by jreback** [pydata/pandas#9354]
xref #7784

**Comment by gtnx** [comment]
Gave it a try in #9364

**Comment by gtnx** [comment]
Done with commit ff124f9efec602ad6de552a0ba41428d69615612 no?

**Comment by jreback** [comment]
originally closed here: https://github.com/pydata/pandas/commit/ff124f9efec602ad6de552a0ba41428d69615612
