### ISSUE TITLE
DataFrame modification operations should return number of rows modified

### ISSUE THREAD

**Issue by bytesemantics** [pydata/pandas#9366]
For situations where an operation on a DataFrame causes a modification to the data in that DataFrame - it would be extremely useful to know how many rows are affected by the modification.

From a debugging, data flow audit perspective - having this "modified rows" value would avoid an extra data query to determine those rows in their "new state".

**Comment by jreback** [comment]
pls show an example of what you are looking for ; code or pseudo code

**Comment by bytesemantics** [comment]
Sure.

I'm reluctant to suggest a change which fundamentally could alter many existing APIs, and so would suggest the following:

A function made available on Panel, Series, and DataFrame called 'lastOpStatus'

This would return a tuple of:
(
    numRowsModified,
    op: { expr: "expresssion executed",
            status: "Fail" | "Success"}
)

where:
"numRowsModified" (number of rows affected by the last operation),
 "op" is a dict containing info on the last operation executed on self, and the status of that execution
(0 (Fail), 1(Success))

Any operations which affect the structure of self, alter values of any rows or columns in self would be expected to populate internal data members such that a subsequent call to 'lastOpStatus' would be correctly populated.

**Comment by jreback** [comment]
You should do this external with a wrapper of your own. This would completely break the API.

Just sum the boolean indexers before and you can see what will change. Or compare the before and after frames to see what actually changed. It really depends on your usecase.
```
In [20]: df = DataFrame(np.random.randn(1000,2),columns=list('AB'))

In [21]: mask = (df['A']>0) & (df['B']<0)

In [22]: len(df)
Out[22]: 1000

In [23]: sum(mask)
Out[23]: 234

In [24]: df[mask] *= 2
```

**Comment by bytesemantics** [comment]
We've written an extensive ETL layer using Pandas. To write code which executes a filter - to determine how many changes will be made - prior to using the filter in an .ix or .loc call breaks the DRY principle.

I'm aware of how to check and count what changes. I'm asking for this function to be provided so that I don't violate DRY.

Can you explain how this proposal breaks the API - when it extends the API - and doesn't propose any changes to existing API methods ? (Internal implementation changes only).

**Comment by jreback** [comment]
well I can think of several issue here:

- this would be a drag on performance, since updating just overwrites a memory space, determing if something changed would involved quite a few (non-cheap) operations. IOW to do this 'correctly' you actually have to compare the before/after data, not just the filter
- errors should be obvious and fail fast, iow, these setter should raise and exception and not silently return a status if they succeed/fail (this always overrides DRY btw).
- you seem to want to keep some additional state in the object itself, e.g. the last ops thingy). This opens a whole host of issues in propogation of data (violating pure object principles).

So while in theory its a decent idea. In practice I think at best this would have to be an optional feature that is layered is such a way as not to interfere with anything else. Hence out of scope for pandas.

**Comment by bytesemantics** [comment]
Thanks for the feedback - it helps a lot.

I've clearly miscommunicated here - as I wasn't suggesting changing any of the existing approaches to error handling and in fact I'd be happy to drop the lastOp/status features.

But in terms of being able to retrieve a "how many rows were affected by that last executed operation"..... could we not add that ?

Alternative data manipulation tools  generally provide information indicating how many rows were changed by the last executed command. Its a very useful piece of feedback which helps when presenting audit trails of ETL dataflows.

Can we not add this ?

**Comment by jreback** [comment]
how exactly would add that?
you would need to do a full comparison to the before and after. which is quite expensive to do in the general case
and how exactly would you return this to the user?

**Comment by TomAugspurger** [comment]
@bytesemantics I've used decorators in the past for logging this sort of stuff. It really helps keep things DRY. Essentially, every operation is a function that takes one DataFrame (or two if you're doing a merge) and `**kwargs`. Then you can add decorators to each function. I've used ones that log the size going in and out, the number of `NaN`s. I've never done one for the number of rows affected. It may be something as simple as `(original_df != transformed_df).any(1).sum()` if the shape is the same.

But that operation will be somewhat expensive to calculate, and will only work in certain situations. I guess what I'm saying is that I think this really has to be implemented by the end-user.

If you haven't used decorators before, [this](http://chimera.labs.oreilly.com/books/1230000000393/ch09.html) is the best reference.
