### ISSUE TITLE
Natural name convention broken for "size" in non-interactive mode.

### ISSUE THREAD

**Issue by mamikony** [pydata/pandas#9367]
If there is a column named "size", the member syntax return the NumPy .size property instead of the contents of the column:
```
$ python -c "import pandas; df=pandas.DataFrame({'size':range(3)}); print df.size; print df['size']"
```
prints
```
3
0    0
1    1
2    2
Name: size, dtype: int64
```

**Comment by shoyer** [comment]
This is as expected: please read the "Warning" section of the documentation on attribute style access:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access

**Comment by mamikony** [comment]
`size` is *not* an "existing method name." I don't quite understand which of the conditions in the warning to which you pointed covers this case. Furthermore, this used to work in previous versions.

**Comment by jreback** [comment]
@mamikony see here: https://github.com/pydata/pandas/pull/8847
this was for Numpy compat

**Comment by mamikony** [comment]
I see, thanks.
