### ISSUE TITLE
Performance degradation in __setitem__ from 0.12 to 0.15.2

### ISSUE THREAD

**Issue by twiecki** [pydata/pandas#9371]
```
In [1]: import pandas as pd

In [2]: print pd.__version__
0.12.0

In [3]: s = pd.Series({'AAPL': 20.})

In [4]: %timeit s['AAPL'] = 25.
1000000 loops, best of 3: 1.29 µs per loop
```

VS

```
In [1]: import pandas as pd

In [2]: print pd.__version__
0.15.2

In [3]: s = pd.Series({'AAPL': 20.})

In [4]: %timeit s['AAPL'] = 25.
100000 loops, best of 3: 6.05 µs per loop
```

Slow down of ~470%. Is this expected? Any way to speed this up?

**Comment by twiecki** [comment]
Passing some wrappers and directly calling `set_value` I can get this down to:
```
In [20]: %timeit s.index._engine.set_value(s.values, 'AAPL', 25.)
100000 loops, best of 3: 3.1 µs per loop
```
with Pandas 0.15.2.

**Comment by jreback** [comment]
There is a quite a lot more checking in later versions. How is this a practical regression? Its so by 4.5 us on a single call. This might be several function calls. 

If you want to disregard all checking and possible errors.
```
In [6]: %timeit s.values[s.index.get_loc('AAPL')] = 25
100000 loops, best of 3: 2.8 us per loop
```

**Comment by jreback** [comment]
I'll reiterate. If this kind of setting actually matters, then you are doing things wrong. You need to set in a vectorized way. Setting single elements like this is not a good use of pandas.

**Comment by twiecki** [comment]
Thanks @jreback. The `get_loc` takes about 3.01µs on my machine so still quite a bit slower but I'll think of other ways to do the updating.

**Comment by jreback** [comment]
@twiecki as I said, maybe show the bigger issue and what you are doing. There are much better ways to update that individual series.

**Comment by twiecki** [comment]
@jreback I'm afraid this one would require some larger-scale refactoring on our side. Basically, we are maintaining a Series object that keeps track of the last stock price of a security. This gets updated a lot so as we're trying to upgrade pandas, this showed up as one bottleneck that caused `zipline` to run much slower:
https://github.com/quantopian/zipline/blob/master/zipline/finance/performance/period.py#L152

**Comment by jreback** [comment]
you should just make it a dict
a series is way heavy weight for that

**Comment by twiecki** [comment]
Yeah, I tried that but it does need to get converted to Series at one point which induces object creation cost.

**Comment by twiecki** [comment]
Just out of curiosity, why is the old Series still faster here? It seems that `s.values[s.index.get_loc('AAPL')]` is just doing the minimum that's required so I wonder where the difference stems from. I suppose it has to be that the index lookup is more expensive.

**Comment by dalejung** [comment]
```python
loc_map = dict(zip(s.index, range(len(s))))
values = s.values

values[loc_map['AAPL']] = 25 # should be real fast
```

Try that, you'd need to store the `loc_map` and `values` somewhere and invalidate when you append to the Series. I'm assuming that the Series itself doesn't change its index often.
