### ISSUE TITLE
Status of the examples

### ISSUE THREAD

**Issue by jorisvandenbossche** [pydata/pandas#9391]
@tvyomkesh opened some issues (#9384, #9389) on errors in the examples (and some PRs to fix this). This raised the following question to me:

Apart from fixing the examples, I think we should think for a moment what we want to do with these examples. Why do we want them? What is their function?
And depending on that, do we want to update/extend them? Or maybe move them to the docs?

I personally never looked at these examples. And they are also quite outdated. Eg using the ols from pandas is somewhat (unofficially) deprecated for the use of statsmodels, and the finance module in matplotlib is deprecated starting from matplotlib 1.4. And to get such data, I think pandas-datareader should be used.

@jreback @TomAugspurger @shoyer

**Comment by jreback** [comment]
repeat of my comment:

I think that these should be checked to see if they are in the docs ; if not and appropriate add any
then blow away the entire directory
these are just duplicate, not maintained, not tested and pretty much superfluous to the docs

**Comment by shoyer** [comment]
Agreed -- they really should go away. I wouldn't even bother fixing them up.

**Comment by tvyomkesh** [comment]
Yeah, I found it strange that only two examples were there that too outdated. I have closed the other fix related PRs and submitted a new one with deletes the examples folder

**Comment by tvyomkesh** [comment]
Will check any potential additions to documentation and update PR accordingly.
