### ISSUE TITLE
15.2 series.ravel() may not work

### ISSUE THREAD

**Issue by murphsp1** [pydata/pandas#9407]
Ravel doesn't seem to flatten lists in a series.

```python

import pandas as pd
df = pd.DataFrame({ 'data':[[1,2],3]})
df['data'].ravel()

Out[3]: array([[1, 2], 3], dtype=object)

df.data.values.ravel()

Out[4]: array([[1, 2], 3], dtype=object)
```

Or, in iPython Notebook

![screen shot 2015-02-03 at 1 55 54 pm](https://cloud.githubusercontent.com/assets/925757/6026920/799ed948-abac-11e4-81d6-38c99e55a4cd.png)

Seen this issue on two versions:

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.6.final.0
python-bits: 64
OS: Darwin
OS-release: 14.0.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

pandas: 0.15.2
nose: 1.3.4
Cython: None
numpy: 1.9.1
scipy: None
statsmodels: None
IPython: 2.4.0
sphinx: None
patsy: None
dateutil: 2.4.0
pytz: 2014.10
bottleneck: None
tables: None
numexpr: None
matplotlib: 1.4.2
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: 4.3.2
html5lib: None
httplib2: None
apiclient: None
rpy2: None
sqlalchemy: 0.9.8
pymysql: None
psycopg2: 2.5.4 (dt dec pq3 ext)

and 

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.9.final.0
python-bits: 64
OS: Darwin
OS-release: 14.1.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

pandas: 0.14.1
nose: 1.3.4
Cython: 0.21
numpy: 1.9.1
scipy: 0.14.0
statsmodels: 0.5.0
IPython: 2.2.0
sphinx: 1.2.3
patsy: 0.3.0
scikits.timeseries: None
dateutil: 2.2
pytz: 2014.7
bottleneck: None
tables: 3.1.1
numexpr: 2.4
matplotlib: 1.4.0
openpyxl: 1.8.5
xlrd: 0.9.3
xlwt: 0.7.5
xlsxwriter: 0.5.7
lxml: 3.4.0
bs4: 4.3.2
html5lib: None
httplib2: 0.8
apiclient: 1.2
rpy2: None
sqlalchemy: 0.9.7
pymysql: None
psycopg2: None

**Comment by jreback** [comment]
well keeping lists in a series (or frame) element is in general not a good idea as it makes it an object dtype. Numpy doesn't collapse these either.

```
In [143]: np.array([[1, 2], 3], dtype=object).ravel()
Out[143]: array([[1, 2], 3], dtype=object)
```
