### ISSUE TITLE
date_range performance

### ISSUE THREAD

**Issue by echu79** [pydata/pandas#9408]
Hello - can anything be done about the performance of date_range?  I've noticed a big degradation in performance from 0.11.0 (I know it's old) to 0.15.2.

*0.11.0:*
```
%timeit pandas.date_range(start='1/1/1995', end='2/3/2015', freq='B')
1000 loops, best of 3: 412 us per loop
```

*0.15.2:*
```
%timeit pandas.date_range(start='1/1/1995', end='2/3/2015', freq='B')
10 loops, best of 3: 134 ms per loop
```

Thanks

**Comment by jreback** [comment]
Well, not sure if the behavior of 0.11 is correct (IIRC it doesn't handle certain edge cases), but in any event this seems pretty good to me. After all this is almost always a 1-time cost. You should not be generating dates like this many times.
```
In [140]: %timeit pandas.date_range(start='1/1/1995', end='2/3/2015', freq='B')
10 loops, best of 3: 49 ms per loop
```

If you really wanted to do it faster, you can do this.
```
In [138]: def f():
   .....:     dr = pandas.date_range(start='1/1/1995', end='2/3/2015', freq='D')
   .....:     return dr[dr.weekday<5]
   .....: 

In [139]: %timeit f()
100 loops, best of 3: 2.02 ms per loop


```
