### ISSUE TITLE
Vectorizing pandas Date Functions

### ISSUE THREAD

**Issue by aschneiderman** [pydata/pandas#9412]
pandas has great methods for manipulating index dates, which works well for timeseries data. But for other kinds of data, to manipulate a date column you have to use lambda (or set that column to be the index).  For example, a lot of the beginners I'm training work with transactional data that looks something like this:

```python
purchases = pd.DataFrame({
'Purchase_Date': ['9/9/2013', '9/9/2013', '9/10/2013', '9/28/2013', '10/6/2013', '10/7/2013',
'10/18/2013', '10/18/2013', '11/1/2013'],
'Delivery_Date': ['9/11/2013', '9/11/2013', '9/18/2013', '10/2/2013', '10/8/2013', '10/8/2013', '10/22/2013', '10/22/2013', '11/8/2013'],
'Size': ['Medium', 'Small', 'Large', 'Small', 'Medium', 'Small', 'Large', 'Medium', 'Small'],
'Color': ['Red', 'Blue', 'Green', 'Red', 'Red', 'Green', 'Purple', 'Purple', 'Black']})
```
Here's what you have to do now to get the delivery purchase month:
```python
purchases["Delivery_Month"] = purchases["Delivery_Date"].apply(lambda x: pd.to_Datetime(x).month)
```
For beginners who don't have a science or programming background, using apply and lambda is pretty confusing. And since one of the first things these beginners want to do is analyze their data by dates, it's a potential stumbling block to their adopting pandas.

It would be great if date functions could be vectorized the way strings have so that for example you could instead write:
```python
purchases["Delivery_Month"] = purchases["Delivery_Date"].month
```
I think this change might help make pandas more accessible to a wider audience. For example, as part of [Data Chefs](http://datachefs.org), I'm working with a group of folks to create an online course and cookbook on slicing & dicing data with pandas. Having vectorized date functions would remove a small but important barrier to our target audience becoming comfortable using pandas.

**Comment by jreback** [comment]
you mean like this? http://pandas.pydata.org/pandas-docs/version/0.15.1/basics.html#basics-dt-accessors

**Comment by aschneiderman** [comment]
Excellent!  That's exactly what I was looking for.
