### ISSUE TITLE
to_datetime parsing odd strings to dates

### ISSUE THREAD

**Issue by lminer** [pydata/pandas#9423]
Some strings that clearly aren't dates are being parsed as dates. This may be expected behavior, but thought I'd flag just in case.

```python
pd.to_datetime('0067000000M2M3HAAV')
Timestamp('2015-02-05 00:02:03')
```
Not sure how this matches to 2015! But this is fine:
```python
pd.to_datetime('0067000000M2LkvAAF')
'0067000000M2LkvAAF'
```

**Comment by jorisvandenbossche** [comment]
This is `dateutil.parser.parse` behaviour:

```
In [9]: import dateutil

In [10]: dateutil.parser.parse('0067000000M2M3HAAV')
Out[10]: datetime.datetime(2015, 2, 5, 0, 2, 3)

```

**Comment by lminer** [comment]
So should I file a bug with dateutil?

**Comment by lminer** [comment]
Seems like a valid albeit esoteric parse.
