### ISSUE TITLE
'infer_freq' can return timerule (WOM-5MON) that 'to_offset' does not support

### ISSUE THREAD

**Issue by craustin** [pydata/pandas#9425]
```python
import pandas as pd
index = [pd.Timestamp('2014-03-31 00:00:00'),
         pd.Timestamp('2014-06-30 00:00:00'),
         pd.Timestamp('2015-03-30 00:00:00'),
         pd.Timestamp('2015-06-29 00:00:00')]
freq = pd.infer_freq(index)  # WOM-5MON
pd.datetools.to_offset(freq)  # ValueError: Could not evaluate WOM-5MON
```

Instead of supporting WOM-5###, I think we can easily modify _get_wom_rule() to return None for this set of dates so it doesn't get inferred.  Agree?

**Comment by jreback** [comment]
well the inferer is technically correct here. and the ``to_offset`` doesn't work for that offset (see #7985)

I think you could add a ``strict`` keyword that would tell the inferer how hard to try (e.g. only produce the default frequencies, don't get the more esoteric ones).

**Comment by craustin** [comment]
The problem comes up when pandas itself uses the inferred frequency here: https://github.com/pydata/pandas/blob/master/pandas/tseries/index.py#L823

If I go with your suggestion above, do you suggest I change the inferred_freq to strict?

**Comment by jreback** [comment]
well I think its better to have ``to_offset`` actually work with these frequencies (separately can be decided to infer this from data). I think we should normally NOT infer these special frequencies (IOW, I would be in favor of adding ``strict=True`` to give the option to not try to hard to infer these; and if it fails on the inference then it returns ``None`` as the result frequency.)
