### ISSUE TITLE
BUG: Timestamp from "y-m-d H" string

### ISSUE THREAD

**Issue by sjpfenninger** [pydata/pandas#9434]
I have datetime strings of the form ``"1996-4-7 0"``, where the ``0`` is supposed to be equivalent to ``00:00`` (i.e. hour 0). I want to turn them into timestamps, but this causes ValueErrors:

  ```python
pd.Timestamp('1996-4-7 0')    # Result: ValueError
```

These work, on the other hand:

```python
pd.Timestamp('1996-4-7 00')   # Result: Timestamp('1996-04-07 00:00:00')
pd.Timestamp('1996-4-7')      # Result: Timestamp('1996-04-07 00:00:00')
  ```

Maybe this is intentional behavior but looks like a bug to me, or at least an inconsistency. Note the same happens for any single-digit hour, but not for two-digit hours:

```python
pd.Timestamp('1996-4-7 8')     # Result: ValueError
pd.Timestamp('1996-4-7 11')    # Result: Timestamp('1996-04-07 11:00:00')
```

Problem occurs in both stable 0.15.2 and 0.15.2-163-g671b384.

**Comment by jreback** [comment]
``Timestamp`` only accepts ISO formats. You should use ``pd.to_datetime`` which is much more general for string parsing. (and you will need to specify a format string here).

```
In [13]: pd.to_datetime('1996-4-7 0',format='%Y-%m-%d %H')
Out[13]: Timestamp('1996-04-07 00:00:00')

In [14]: pd.to_datetime('1996-4-7 00',format='%Y-%m-%d %H')
Out[14]: Timestamp('1996-04-07 00:00:00')
```
