### ISSUE TITLE
sort=False ignored in Series groupby on MultiIndex levels

### ISSUE THREAD

**Issue by cottrell** [pydata/pandas#9444]
Example:

    import pandas
    def geta():
        i = pandas.MultiIndex.from_tuples([(1, 2, 'a', 0),
                                  (1, 2, 'a', 1),
                                  (1, 1, 'b', 0),
                                  (1, 1, 'b', 1),
                                  (2, 1, 'b', 0),
                                  (2, 1, 'b', 1)], names=['a', 'b', 'c', 'd'])
        a = pandas.Series([0, 1, 2, 3, 4, 5], index=i)
        return(a)

    for dosort in [True, False]:
        a = geta()
        b = a.groupby(level=['a', 'b'], sort=dosort).first()
        a = None
        print('%s, sort=%s, \n%s' % (geta.__name__, dosort, b))

Output:

    geta, sort=True,
    a  b
    1  1    2
       2    0
    2  1    4
    dtype: int64
    geta, sort=False,
    a  b
    1  1    2
       2    0
    2  1    4
    dtype: int64

Also see: https://github.com/pydata/pandas/pull/9076
Possibly related to: https://github.com/pydata/pandas/issues/8868

**Comment by cottrell** [comment]
This seems to fix it. There might be a few more sort args missing elsewhere, for example in groupby._indexer_from_factorized. 

    diff --git a/pandas/core/groupby.py b/pandas/core/groupby.py
    index cb5dedc..06fbb55 100644
    --- a/pandas/core/groupby.py
    +++ b/pandas/core/groupby.py
    @@ -1378,7 +1378,7 @@ class BaseGrouper(object):
             else:
                 if len(all_labels) > 1:
                     group_index = get_group_index(all_labels, self.shape)
    -                comp_ids, obs_group_ids = _compress_group_index(group_index)
    +                comp_ids, obs_group_ids = _compress_group_index(group_index, sort=self.sort)
                 else:
                     ping = self.groupings[0]
                     comp_ids = ping.labels

**Comment by jreback** [comment]
try on master - iIIRC this all is fixed

**Comment by cottrell** [comment]
Just tried on the master at the commit below and I am seeing no difference.

commit 107cb10c51beee903064c9792e0a3ad29b5a9792
Merge: c4a996a f9031c2
Author: Joris Van den Bossche <jorisvandenbossche@gmail.com>
Date:   Sun Feb 8 14:35:47 2015 +0100

    Merge pull request #9417 from cel4/plot_error

    improved error message for invalid chart types

**Comment by jreback** [comment]
@cottrell can you do a separate PR for this (with a test), (and a release note). You can then rebase the ``to_coo`` on top. thxs.

**Comment by jreback** [comment]
this might interact with #9445
