### ISSUE TITLE
3D ndarray (NxNxN) to DataFrame (NxNxN rows and 4 columns = 3 indices + 1 value)

### ISSUE THREAD

**Issue by anderflash** [pydata/pandas#9488]
I have a ndarray (between 4 or 6 dimensions), but let's talk about 3D data.
so if I have an index like:
~~~ python
data[i,j,k] = 30
~~~
How can I create a excel sheet where the first 3 colunns are the indices like:
~~~ python
>>> frame
  i     j     k       X
  0     0     0    1023
...
  0     0   255       3
...
  0     1     0      34
...
255   255   255      23
~~~
So, if I have a 256x256x256 ndarray cube, I would like 256x256x256 rows, and 4 columns (3 for indices and 1 for value). I tried to use `Panel`, `to_frame` and `to_csv`, but the third dimension are the columns.

Thanks

**Comment by jreback** [comment]
pls show how you are creating the structure you are trying to transform (e.g. code), as well as ``pd.show_versions()``

**Comment by anderflash** [comment]
it's a 3D histogram, like `hist = np.array((256,256,256))`, and I use OpenCV to fill it. But my teacher wants the indices to be columns of a table, to be opened by a spreadsheet software. So I have 3 columns (Ex: R, G and B), ranging from 0,0,0 to 255,255,255 (16 milion lines), and a fourth column to be the value of the color at indices (R,G,B). 3 nested loops are so slow to create a table, so I would ask whether there is a better tool. 
Thanks.

**Comment by jreback** [comment]
Showing actual code is much more helpful

```
In [28]: df = DataFrame(np.repeat(np.arange(256),3).reshape(256,3),columns=list('RGB'))

In [29]: df['value'] = (df['R'] + df['G'] + df['B']) % 256

In [30]: df
Out[30]: 
       R    G    B  value
0      0    0    0      0
1      1    1    1      3
2      2    2    2      6
3      3    3    3      9
4      4    4    4     12
5      5    5    5     15
6      6    6    6     18
7      7    7    7     21
8      8    8    8     24
9      9    9    9     27
..   ...  ...  ...    ...
246  246  246  246    226
247  247  247  247    229
248  248  248  248    232
249  249  249  249    235
250  250  250  250    238
251  251  251  251    241
252  252  252  252    244
253  253  253  253    247
254  254  254  254    250
255  255  255  255    253

[256 rows x 4 columns]
```

**Comment by anderflash** [comment]
Thanks for the attention, but it's not what I want. I already have a ndarray histogram (256,256,256), I'm not creating one new. I want just to transform from (256,256,256) to (256*256*256,4), where the first 3 columns are the indices of the 16 milion colors
0 0 0
0 0 1
0 0 2
...
0 0 255
0 1 0
0 1 1
...
255 255 255

and the fourth column are the value of the already known histogram.

Well, I'm able to create the three columns based on this [gist](https://gist.github.com/hernamesbarbara/68d073f551565de02ac5). But I don't know a way without loops to get the value from the 3D histogram.
Thanks

**Comment by jreback** [comment]
Why don't you show a simple example of what you want. Code that can be copy-pasted.

**Comment by rockg** [comment]
You probably want something like the below.  `MultiIndex.from_product` I believe is what you are after.

```
df = DataFrame(range(256**3), index=MultiIndex.from_product([range(256), range(256), range(256)]))
df
Out[6]: 
                    0
0   0   0           0
        1           1
        2           2
        3           3
        4           4
        5           5
        6           6
...               ...
255 255 226  16777186
        227  16777187
        228  16777188
        229  16777189
        230  16777190
        231  16777191
```

**Comment by anderflash** [comment]
I join your idea with the cartesian gist, like this:
~~~ python
# ndarray((16777216, 3)), from [0 0 0] to [255 255 255]
histoIndices = cartesian([range(256)]*3) 
histoTable   = pd.DataFrame(histoIndices,columns=['R','G','B'])
# Looking up values from old ndarray histogram which is 3D (256,256,256)
histoTable['Value'] = histogram[histoTable['R'],histoTable['G'],histoTable['B']]
~~~
Now I can create 2D Frames with indices from a 3D hist as columns.
This can be extended to N-dimensional matrices, which can be converted to N+1 column DataFrame.

Ex: If you have a 7D ndarray (10, 10, 10, 10, 10, 10, 10), you can create a 10+1 column DataFrame with 10^7 rows representing it.

Thanks

**Comment by anderflash** [comment]
I didn't see your last answer. I also like your suggestion. Just one correction: enclose `range(256**3)` with `np.array()`.
