### ISSUE TITLE
Chainable Series.set_name()

### ISSUE THREAD

**Issue by wavexx** [pydata/pandas#9494]
It's sometimes convenient to assign/replace the name of a Series, especially if the result is going to be a DataFrame column, for example:

    df.groupby([]).size().set_name('GRP_SIZE').reset_index()

This should be as simple as:

    def set_name(self, name):
        self.name = name
        return self

Comments?

**Comment by jreback** [comment]
this is kind of like #9239 functionaility wise 
@TomAugspurger 

what about having ``set_meta(name=...)`` (maybe in addition to this)?

@jorisvandenbossche

**Comment by TomAugspurger** [comment]
What else would go in `set_meta`?

And of course, we need to be careful about not modifying the original `self`.

**Comment by jreback** [comment]
I think we could move ``.assign`` to generic and just have it set the info-items (e.g. ``columns`` for frames, ``items`` for Panel). I guess then for series it would set elements (e.g. like append). rather than ``_meta`` elements (of which ``name`` is the only one ATM).

**Comment by jreback** [comment]
ok, @wavexx want to do a pull-request to add ``set_name`` (on Series) only. I think that is fine.

**Comment by wavexx** [comment]
On 02/16/2015 03:03 PM, jreback wrote:
> ok, @wavexx want to do a pull-request to add ``set_name`` (on Series) only. I think that is fine.

What about modifying self?
Should we return a copy by default and add an inplace argument as well?

**Comment by jreback** [comment]
I think this needs to copy by default. Though on a series this is quite cheap (as its a view).

**Comment by shoyer** [comment]
Another option is to repurpose `Series.rename` for this instead of adding a new method -- if the argument is a string (or any hashable?), it renames the Series. This is [what I chose to do for xray's equivalent of a Series](http://xray.readthedocs.org/en/stable/generated/xray.DataArray.rename.html).

This does overload `rename` to do two (somewhat) different things (often a sign of poor API design), but  `rename` *is* the obvious place to look for this functionality.

**Comment by jreback** [comment]
I would be ok with that!

@shoyer it was my thought about too much o reloading
but I agree it does make sense

and already has the inplace option 

@wavexx want to do a PR?

**Comment by wavexx** [comment]
On 02/17/2015 11:54 AM, jreback wrote:
> I would be ok with that!
> 
> @shoyer it was my thought about too much o reloading
> but I agree it does make sense
> 
> and already has the inplace option 
> 
> @wavexx want to do a PR?

I'll give it a shot, but not this week.

**Comment by wavexx** [comment]
Thanks a lot for this.

**Comment by TomAugspurger** [comment]
Not a problem. We should have a 0.18 release candidate out soon, if you're willing / able to try it out and report back any bugs!
