### ISSUE TITLE
Horizontal barplot

### ISSUE THREAD

**Issue by wavexx** [pydata/pandas#9495]
I just want to flip the direction of the bars in a barplot, but currently, the orientation of a barplot cannot be set to 'horizontal':

    pd.Series([1,2], index=pd.Index([1,2], name='x')).plot(kind='bar', orientation='horizontal')

yelds an:

    AssertionError: incompatible sizes: argument 'left' must be length 1 or scalar

**Comment by TomAugspurger** [comment]
That's handled by the `kind` argument. `df.plot(kind='barh')`

**Comment by wavexx** [comment]
On 02/16/2015 02:17 PM, Tom Augspurger wrote:
> That's handled by the `kind` argument. `df.plot(kind='barh')`

Ah, missed that.

Why a different plot type though?

I would have expected orientation to work the same as kind='box' or 'hist'.

**Comment by TomAugspurger** [comment]
It's a different plot type in [matplotlib](http://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.barh), which we're just wrapping.

We're planning to redesign the plot method to hopefully make which keyword args apply to which plot kinds clearer. It will still be `barh` but the `orientation` keyword won't 
won't be visible in the docstring.
