### ISSUE TITLE
DateTimeIndex appending with loc inconsistency in handling numpy datetime64

### ISSUE THREAD

**Issue by dashesy** [pydata/pandas#9516]
This is in Pandas `0.15.2` (but I also tried it on '0.15.2-148-g484f668'):

```python
df = pd.DataFrame()
df.loc[np.datetime64(datetime.datetime.now()),'one'] = 100
df.loc[np.datetime64(datetime.datetime.now()),'one'] = 100
```

This is the output:
```text
                               one
2015-02-18 14:50:05.606510     100
1970-01-17 11:37:51.007748755  100
```

It seems the the first usage of `loc` correctly works around limitations of `datetime64` but I cannot explain the second one.

**Comment by jnmclarty** [comment]
I had a quick peek.  Inside ```_NDFrameIndexer._setitem_with_indexer()```, this line here: ```self.obj._data = self.obj.reindex_axis(labels, i)._data``` is where the labels go from good to bad.  The first reference to labels inside ```NDFrame.reindex_axis(...)``` is erroneous...

This code might help somebody more senior than I:

```
from pandas import DataFrame
from numpy import datetime64 as d64
from datetime import datetime as dt

df = DataFrame()

df.loc[d64(dt(2015,1,1,1,1,0)),'C1'] = 'GOOD'
df.loc[d64(dt(2015,1,1,1,1,1)),'C1'] = 'BAD'
df.loc[d64(dt(2015,1,1,1,1,2)),'C1'] = 'sec'
df.loc[d64(dt(2015,1,1,1,2,1)),'C1'] = 'min'
df.loc[d64(dt(2015,1,1,2,1,3)),'C1'] = 'hr'
df.loc[d64(dt(2015,1,2,1,1,4)),'C1'] = 'day'
df.loc[d64(dt(2015,2,1,1,1,5)),'C1'] = 'mth'
```

```
>>> df
                              C1
2015-01-01 01:01:00         GOOD
1970-01-17 10:27:54.061000   BAD
1970-01-17 10:27:54.062000   sec
1970-01-17 10:27:54.121000   min
1970-01-17 10:27:57.663000    hr
1970-01-17 10:29:20.464000   day
1970-01-17 11:12:32.465000   mth
```
Notice the date component dropped,  And the month/day/hour specified is incrementing hour/minute/seconds.

**Comment by jreback** [comment]
@jnmclarty this is now fixed in master

**Comment by jnmclarty** [comment]
@jreback  Yah, saw that.  Good stuff.
