### ISSUE TITLE
Bad x-axis dates when plotting two time-series with different indexes (start, end, and freq)

### ISSUE THREAD

**Issue by ocefpaf** [pydata/pandas#9524]
The two DataFrames are from 2014, but from the figure you can see that pandas throws one of them to the year 2050!

![bad_pandas](https://cloud.githubusercontent.com/assets/950575/6272178/7ec299a6-b844-11e4-81a7-c47c1a3293bf.png)

I am using pandas 0.15.2 and the notebook below describes the problem and show a few workarounds that might help debug this:

http://nbviewer.ipython.org/gist/ocefpaf/e7e085c84fd3ea7dbc24

Here is a quick SSCCE to generate the figure above:
```python
import numpy as np                                                                               
import pandas as pd                                                                              
                                          
index = pd.date_range(start='2014-06-01 00:00:00', end='2014-09-01 00:00:00', freq='H')          
data = np.random.rand(len(index))                                                                
df0 = pd.DataFrame(data=data, index=index, columns=['DF0'])                                      
index = pd.date_range(start='2014-04-07 10:57:00', end='2014-10-29 09:32:00', freq='D')          
data = np.random.rand(len(index))                                                                
df1 = pd.DataFrame(data=data, index=index, columns=['DF1'])                                      
                                                                                                 
ax = df0.plot(legend=True, figsize=(12, 4))                                                      
ax = df1.plot(ax=ax)                                                                             
```

Thanks!

**Comment by TomAugspurger** [comment]
Thanks for the report. It seems to be tripping up our Autoformatter.

The easiest workaround is to pass the `x_compat=True` [parameter](http://pandas.pydata.org/pandas-docs/version/0.15.2/visualization.html#suppressing-tick-resolution-adjustment) to your first plot call. 

```python
ax = df0.plot(legend=True, figsize=(12, 4), x_compat=True)
ax = df1.plot(ax=ax)                                                                             
```

**Comment by ocefpaf** [comment]
Thanks @TomAugspurger!  Tthat worked nicely.

I updated the notebook to show `x_compat=True` as a preferable workaround to this bug.

PS: `x_compat` is not documented, correct?

**Comment by shoyer** [comment]
Thanks @ocefpaf for the report and @TomAugspurger for the fix! I actually encountered the same issue today when comparing daily and hourly data:
![image](https://cloud.githubusercontent.com/assets/1217238/6280966/dcb0566c-b86b-11e4-83f7-11e610fcbe56.png)

**Comment by jreback** [comment]
@TomAugspurger close this? as this is a usage question, or need docs? or is it a bug?

**Comment by TomAugspurger** [comment]
Closing for now. This would need a big refactor of our datetime plotting to support this properly, which I won't be able to get to anytime soon.
