### ISSUE TITLE
float_format string error

### ISSUE THREAD

**Issue by quebbs** [pydata/pandas#9531]
The float_format string works for single values i.e. float_format='%.1f', but it does not appear to work for a formatted string of columns. For example, If I had four columns with increasing significant digits, separated with tabs:

    fmt_string='%.1f\t%.2f\t%.3f\t%.4f'

Then for some DataFrame X, I should be able to use:

    X.to_csv('./out.txt',float_format=fmt_string,index=False)

But it unfortunately balks at me:

    TypeError: not enough arguments for format string

**Comment by jreback** [comment]
see #4668 

I think there is a wish to support a ``float_format=dict_of_formatters``, but it is not implemented
want to submit a pull-request?
