### ISSUE TITLE
attempted relative import in non-package with Pandas

### ISSUE THREAD

**Issue by ososos73** [pydata/pandas#9538]
I am using python 2.6.2 64 bit with windows 8.1. I am very new to python and I have downloaded some libraries such as pandas. My main focus is not python, rather it is on the integration of some simulation software that I use with python.  This integration requires downloading some libraries (pandas, numpy, .. etc). So, I was trying to run the __init__.py associated with pandas open source library. Every time I run it I receive the following message:

Attempted relative import in non-package
Traceback (most recent call last):
  File "c:\Python26\Lib\site-packages\pandas\__init__.py", line 7, in <module>
    from . import hashtable, tslib, lib
value error: Attempted relative import in non-package

the hashtable, tslib, and lib files are .pyd files that are located in the same folder as the __init__.py file.

Any idea what is wrong here and what needs to be done to overcome that problem?

**Comment by shoyer** [comment]
I think the trouble here is that you are attempting to run pandas with somethings like `python __init__.py`.

This isn't how pandas is intended to be used. Instead, [install pandas](http://pandas.pydata.org/pandas-docs/version/0.15.2/install.html#installing-pandas) and include `import pandas` from another Python file anywhere on disk.

**Comment by ososos73** [comment]
Thank you so much, Shoyer.

After a good struggle to understand how your answer can help me, as I had to copy some modules to anaconda installation folder. Things are finally working perfectly. Thank you so much.
