### ISSUE TITLE
String value for DataFrame.quantile() axis parameter

### ISSUE THREAD

**Issue by fbrundu** [pydata/pandas#9543]
Hi all,
I don't know if this could be an enhancement but: why do not use string values such as `'index'` or `'columns'` in the axis parameter for `DataFrame.quantile()` function? Such as in `DataFrame.div()`..
I think that it would be more straightforward to use.
Thanks

Francesco

**Comment by jreback** [comment]
sure - it's a quite easy change
want to do a pull request?

**Comment by fbrundu** [comment]
Yes, I am doing it in a few minutes.

Thanks

**Comment by fbrundu** [comment]
My pull request is here: https://github.com/pydata/pandas/pull/9544
I also found and fixed a bug.
Thanks

**Comment by jreback** [comment]
closed by #9544
