### ISSUE TITLE
Resample is bugging in timeseries for certain start date indexes [edited]

### ISSUE THREAD

**Issue by KevinLourd** [pydata/pandas#9547]
Hi guys,

For certain values of start dates, the method `resample` seems to bug.
 
I explain with an example :
```
rng = pd.date_range('20110105 12:20:00',periods=5*60,freq='min')
tsMin=pd.Series(range(len(rng)), index=rng)
tsMin
2011-01-05 12:20:00     0
2011-01-05 12:21:00     1
2011-01-05 12:22:00     2
2011-01-05 12:23:00     3
...
2011-01-05 17:18:00    298
2011-01-05 17:19:00    299
Freq: T, Length: 300
```
When trying to resample in `300 minutes` it comes:
```
tsMin.resample("300min")
2011-01-05 10:00:00     79.5
2011-01-05 15:00:00    229.5
Freq: 300T, dtype: float64
``` 

The result is not what expected...

What is wired is that it works when I replace `2011-01-05 12:20:00` by `2011-01-05 00:00:00`

Thank you for your help

**Comment by KevinLourd** [comment]
`pd.show_versions()`
```
INSTALLED VERSIONS
------------------
commit: None
python: 3.4.2.final.0
python-bits: 64
OS: Darwin
OS-release: 14.1.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

pandas: 0.15.2
nose: 1.3.4
Cython: 0.21
numpy: 1.9.1
scipy: 0.15.1
statsmodels: 0.5.0
IPython: 2.3.1
sphinx: 1.2.3
patsy: 0.3.0
dateutil: 2.1
pytz: 2014.9
bottleneck: None
tables: 3.1.1
numexpr: 2.3.1
matplotlib: 1.4.0
openpyxl: 1.8.5
xlrd: 0.9.3
xlwt: None
xlsxwriter: 0.5.7
lxml: 3.4.0
bs4: 4.3.2
html5lib: None
httplib2: None
apiclient: None
rpy2: None
sqlalchemy: 0.9.7
pymysql: 0.6.3.None
psycopg2: None
```

**Comment by jreback** [comment]
what would you expect as a result here? ``300T``, e.g. ``5H`` does not divide 24 hours evenly (unlike say ``6H`` which does. The result frequency needs to follow the resample frequency. So how would you calculate where to start the resample?

**Comment by KevinLourd** [comment]
I would expect only one row starting at 12:20:00 :
```
tsMin.resample("300min")
2011-01-05 12:20:00     149.5
Freq: 300T, dtype: float64
```
Indeed, this is the result I obtain when I start my data at `2011-01-05 00:00:00`. 

What I am trying to do is to aggregate any timeserie into N equal parts.

**Comment by KevinLourd** [comment]
In financial timeseries, we sometimes need to aggregate say `300` one-minute OHLC candlesticks (starting at `2011-01-05 12:20:00`) into say `one` (or it may be 2, 3, ..) candlestick starting at `2011-01-05 12:20:00`

**Comment by jreback** [comment]
``12:20:00`` does not conform to your resampled frequency.

**Comment by KevinLourd** [comment]
`The result frequency needs to follow the resample frequency` : I am not sure to understand what it means ?

Do you mean there is no way to do so ?

If yes, I think about it as an enhancement proposal. In financial timeseries it is useful to *aggregate* a set of candlesticks starting at `date t` into a fewer number of candlesticks starting ate `date t`

**Comment by jreback** [comment]
what I mean is that the point of resample is to return a specific frequency of data; essentially a rounded to that frequency for that index. For the data you have ``10:00,15:00`` are the correct frequencies. You can try using the ``base`` argument if you want.

**Comment by KevinLourd** [comment]
It works perfectly using `base`, even if it requires a preliminary calculation to get the shift.
Thanks a lot
