### ISSUE TITLE
Disable class level caching in AbstractHolidayCalendar

### ISSUE THREAD

**Issue by dhirschfeld** [pydata/pandas#9552]
By caching at the *class* level it prevents instances from defining different rules - e.g.
```python
import numpy as np
from pandas.tseries.holiday import AbstractHolidayCalendar, Holiday

class HolidayCalendar(AbstractHolidayCalendar):
    def __init__(self, rules):
        self.rules = list(np.atleast_1d(rules))

jan1 = HolidayCalendar(Holiday('jan1', year=2015, month=1, day=1))
jan2 = HolidayCalendar(Holiday('jan2', year=2015, month=1, day=2))


jan1.holidays()
Out[2]: 
<class 'pandas.tseries.index.DatetimeIndex'>
[2015-01-01]
Length: 1, Freq: None, Timezone: None

jan2.holidays()
Out[3]: 
<class 'pandas.tseries.index.DatetimeIndex'>
[2015-01-01]    <--------------------------- uses cached result from *other* instance!
Length: 1, Freq: None, Timezone: None
```

```python
import numpy as np
from pandas.tseries.holiday import AbstractHolidayCalendar, Holiday

class HolidayCalendar(AbstractHolidayCalendar):
    def __init__(self, rules):
        self.rules = list(np.atleast_1d(rules))

jan1 = HolidayCalendar(Holiday('jan1', year=2015, month=1, day=1))
jan2 = HolidayCalendar(Holiday('jan2', year=2015, month=1, day=2))


jan2.holidays()
Out[2]: 
<class 'pandas.tseries.index.DatetimeIndex'>
[2015-01-02]
Length: 1, Freq: None, Timezone: None

jan1.holidays()
Out[3]: 
<class 'pandas.tseries.index.DatetimeIndex'>
[2015-01-02]    <--------------------------- uses cached result from *other* instance!
Length: 1, Freq: None, Timezone: None
```
https://github.com/pydata/pandas/blob/a72d95163b4d268012709255d7a52bbe5c1a7eb6/pandas/tseries/holiday.py#L351-L357

**Comment by rockg** [comment]
The expected use of this is that there is only one set of rules per holiday class.  Namely there is a one-to-one mapping between holiday calendars and rules.  Ideally, if you change the rules you would create a new class.  However, this isn't exactly obvious from how things work and I don't see the harm in making the cache on the instance rather than the class (see #6719) for some design discussion.

**Comment by dhirschfeld** [comment]
That seems like a strange design to me - if the rules are a class level attribute then there is no instance   level data stored on the class and all the methods could be classmethods and the user would never have to actually instantiate the subclass to use it.

It also seems contrary to [`AbstractHolidayCalendar.__init__`](https://github.com/pydata/pandas/blob/a72d95163b4d268012709255d7a52bbe5c1a7eb6/pandas/tseries/holiday.py#L281) which specifically allows overriding the rules at an instance-level.
