### ISSUE TITLE
BUG: isnull of a PeriodIndex object array failing when NaT

### ISSUE THREAD

**Issue by msdrahcir** [pydata/pandas#9553]
Pandas isnull failing for NaT period index

>s= pd.PeriodIndex([pd.NaT,'2014-01-01'],freq='M')
>pd.isnull(s)
>
>array([False, False], dtype=bool)

**Comment by jreback** [comment]
this was fixed [here](https://github.com/pydata/pandas/issues/9129) and will be in forthcoming 0.16.0
