### ISSUE TITLE
DataFrame.from_csv undocumented behavior of index_col

### ISSUE THREAD

**Issue by EntilZha** [pydata/pandas#9556]
Took me a while to find this (in the end by stackoverflow), but I ran into the problem while trying to parse a csv file. Panda kept parsing the first column as the index column instead of generating a new index. I could not find a way to disable this after reading the docs here:

http://pandas.pydata.org/pandas-docs/dev/generated/pandas.DataFrame.from_csv.html

As it turns out, due to the line of code below, if the argument is set to False, then it has the behavior I desired. This is completely undocumented and would be very helpful to have. I haven't contributed before to Pandas, so if it is more than a quick change a maintainer can make, I could put the work in for a PR, even if its just documentation changes.

https://github.com/pydata/pandas/blob/master/pandas/io/parsers.py#L1064

**Comment by jorisvandenbossche** [comment]
Please have a look at the docstring of read_csv: http://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html

I think there this feature is explained. `from_csv` should actually be deprecated and the docs should just refer to `read_csv` (see #4191)

**Comment by EntilZha** [comment]
I would agree with #4191 which points to #4916 that it should be deprecated. For the short term, could the docs be updated to reflect that from_csv will be deprecated or that users should use read_csv instead (perhaps additionally document the False usage).

**Comment by jorisvandenbossche** [comment]
Yes I will do a PR. At least the 'deprecation' can be documented by removing the current doctring and just pointing to `read_csv` (and noting the one difference in the default value of `parse_dates`)

**Comment by jorisvandenbossche** [comment]
or if you would like to do a PR for this, certainly welcome!

**Comment by EntilZha** [comment]
I would be good with either. Should be a quick change, most of the time tbh would be in forking and generating the docs. I could probably work on it tonight/tomorrow.

**Comment by jorisvandenbossche** [comment]
Give it a go! (I would also work at it this weekend at the earliest). Normally, for such a small change, building the full docs should not be necessary (but of course, it can be a good exercise to try to build them), just have a look at the existing docstrings for the format (and here for a description of the format: https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt#docstring-standard)
