### ISSUE TITLE
ImportError: No module named style in python2.7.9

### ISSUE THREAD

**Issue by Ron256** [pydata/pandas#9557]
Hi all, I am using python 2.7.9 on linux centos which I just installed

When I execute my python script to produce an excel report,

I get a traceback error as:

Traceback (most recent call last):
  File "./bin/si_under_development_iml_orders_last_120_days.py", line 285, in <module>
    main()
  File "./bin/si_under_development_iml_orders_last_120_days.py", line 274, in main
    con=run_report(con,date_pattern)
  File "./bin/si_under_development_iml_orders_last_120_days.py", line 236, in run_report
    output_worksheet(out_filename,current_date,imlL,last_n_days_ago)
  File "./bin/si_under_development_iml_orders_last_120_days.py", line 59, in output_worksheet
    from openpyxl.style import Color, Fill
ImportError: No module named style

I installed the openpyxl module.

How can I resolve this?

Thanks,

Ron

**Comment by jorisvandenbossche** [comment]
What version of pandas and openpyxl are you using? (please show the output of `pd.show_versions()`)

**Comment by Ron256** [comment]
Sorry the silly question but where I do issue this command  pd.show_versions()?

**Comment by jorisvandenbossche** [comment]
just in a python console (after `import pandas as pd`)

**Comment by Ron256** [comment]
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas as pd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named pandas
>>>

I don't  have the pandas module.

**Comment by jorisvandenbossche** [comment]
But you are posting on the *pandas* issue tracker?

**Comment by Ron256** [comment]
INSTALLED VERSIONS
------------------
commit: None
python: 2.7.9.final.0
python-bits: 64
OS: Linux
OS-release: 2.6.32-431.29.2.el6.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

pandas: 0.15.2
nose: None
Cython: None
numpy: 1.9.1
scipy: None
statsmodels: None
IPython: None
sphinx: None
patsy: None
dateutil: 2.4.0
pytz: 2014.10
bottleneck: None
tables: None
numexpr: None
matplotlib: None
openpyxl: None
xlrd: 0.9.3
xlwt: 0.7.5
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
httplib2: None
apiclient: None
rpy2: None
sqlalchemy: None
pymysql: None
psycopg2: 2.6 (dt dec pq3 ext)

**Comment by Ron256** [comment]
When I look at the logs, it indicates that openpyxl is not installed which I did. I will reinstall again.

**Comment by Ron256** [comment]
I got this resolved by re installing openpyxl, https://pypi.python.org/packages/source/o/openpyxl/openpyxl-1.8.6.tar.gz 

Thanks for the pd.show_version() command.

**Comment by datomnurdin** [comment]
Even I'm using @Ron256 , the problem still not fix.
