### ISSUE TITLE
API/DOC: to_series keep_tz behaviour for UTC timezone

### ISSUE THREAD

**Issue by jorisvandenbossche** [pydata/pandas#9562]
The docstring of `to_series` says for `keep_tz=True`: *"If the timezone is not set or is UTC, the resulting Series will have a datetime64[ns] dtype. Otherwise the Series will have an object dtype."*

http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DatetimeIndex.to_series.html

But is seems that also for UTC, `keep_tz=True` does the conversion to object/Timestamp?

```
In [1]: idx = pd.date_range('1/1/2000', periods=20, freq='1H', tz='UTC')

In [2]: idx
Out[2]:
<class 'pandas.tseries.index.DatetimeIndex'>
[2000-01-01 00:00:00+00:00, ..., 2000-01-01 19:00:00+00:00]
Length: 20, Freq: H, Timezone: UTC

In [3]: idx.to_series()[0]
Out[3]: Timestamp('2000-01-01 00:00:00')

In [4]: idx.to_series(keep_tz=True)[0]
Out[4]: Timestamp('2000-01-01 00:00:00+0000', tz='UTC', offset='H')
```

**Comment by jorisvandenbossche** [comment]
@jreback you put this in I think. Should be change the docs, or change the implementation? 

I would find it more logical to not make this exception for UTC (so keep the behaviour and change the docs)

**Comment by jorisvandenbossche** [comment]
Ah, but, this behaviour seems to have changed from 0.14 to 0.15. Originally in 0.14, the behaviour was as described in the docs

**Comment by jreback** [comment]
this was a bug in that we do want to actually preserve the UTC tz on the resulting Series (IOW it becomes ``object`` dtype). So I think the doc-string is wrong. The behavior is correct, otherwise a UTC tz is effectively lost (by being converted to naive)

**Comment by jreback** [comment]
closed by https://github.com/pydata/pandas/commit/8ef921f31b6d0ebb949a79c05e7a9b6d840ab0ee

**Comment by jreback** [comment]
FYI, I think that we could basically drop this paramater (which is an API change because the default would change), and automatically preserve the character of the index when converting to a series, once DatetimeTZBlock blocks become a reality. (I added this originally because the perf impact is pretty big once you convert to object dtypes)

**Comment by jorisvandenbossche** [comment]
Yes, once a timezone aware DatetimeBlock is in place, we can certainly consider that.
