### ISSUE TITLE
Licenses update required?

### ISSUE THREAD

**Issue by H0R5E** [pydata/pandas#9564]
Hi,

I was just wondering if all the licenses are up to date? I only ask because I notice a dependency is python-dateutil (which is BSD licensed) but no copy of its license is in the licenses folder.

Nothing major, I have just been considering how to license my own code, that uses Pandas as a library, and my impression was I would have to restate your licence along with my own.

Am I wrong?

Mat

**Comment by shoyer** [comment]
> Am I wrong?

I think so, yes :). As a rule, you only need to include another project's license when you copy code from it. If you're just using it as a library, nothing is required.

**Comment by H0R5E** [comment]
OK, I think I see the argument here.

If I'm not modifying the source or supplying a binary of the BSD licensed library then I do not need to reproduce the original licence. But if I modify / copy or package the code / binary then I should.

Where does subclassing fit? Say if I wanted to subclass Dataframe to provide additional output options. Is this redistribution of source at this point?

**Comment by shoyer** [comment]
I'm not a lawyer, but I don't think subclassing counts a "redistribution" in source or binary form any more than normal use. Writing `class MyDataFrame(pandas.DataFrame)` in a file does not make that file a redistribution of pandas anymore than `import pandas`.

**Comment by H0R5E** [comment]
OK great! Thanks a lot for your help Stephan. It's just really hard to find clear explanation as to the implications of various licenses in relation to python.
