### ISSUE TITLE
Difference between C and Python parser engine for pandas.read_csv

### ISSUE THREAD

**Issue by SvenWambecq** [pydata/pandas#9565]
In the code snippet below, I expect that both the values in the c1 and c2 column both are 4.5. 
When the Python parser engine is used, this gives me 4 iso 4.5. When using the C parser engine, I get 4.5. 

Is this expected behaviour? 

```python

import StringIO
import pandas

csv = """
c1,c2
45e-1,45.0e-1
"""
stream = StringIO.StringIO(csv)
pandas.read_csv(stream, engine='python')

  ```
I used the following versions: (pandas.show_versions)

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.5.final.0
python-bits: 32
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None

pandas: 0.15.2
nose: None
Cython: None
numpy: 1.9.1
scipy: 0.14.0
statsmodels: None
IPython: 2.3.1
sphinx: None
patsy: None
dateutil: 2.1
pytz: 2014.7
bottleneck: None
tables: None
numexpr: None
matplotlib: 1.3.0
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
httplib2: None
apiclient: None
rpy2: None
sqlalchemy: 0.9.4
pymysql: None
psycopg2: None

**Comment by jreback** [comment]
closed by #10133
