### ISSUE TITLE
.plot() method slow compared to Matplotlib

### ISSUE THREAD

**Issue by rubennj** [pydata/pandas#9567]
When plotting large datasets, pandas.plot() is much slower than the direct use of Matplotlib:
```python
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df = pd.DataFrame(data=np.random.normal(0, 1, (1, 1000)))

%timeit df.plot()
1 loops, best of 3: 11.2 s per loop

%timeit plt.plot(df.index, df.values)
1 loops, best of 3: 2.1 s per loop
```

INSTALLED VERSIONS
------------------
commit: None
python: 3.4.1.final.0
python-bits: 32
OS: Windows
OS-release: 8
machine: x86
processor: x86 Family 6 Model 55 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None

pandas: 0.15.0
nose: 1.3.4
Cython: 0.21
numpy: 1.9.1
scipy: 0.15.1
statsmodels: 0.6.1
IPython: 2.4.1
sphinx: 1.2.3
patsy: 0.3.0
dateutil: 2.1
pytz: 2014.9
bottleneck: None
tables: 3.1.1
numexpr: 2.3.1
matplotlib: 1.4.2
openpyxl: 1.8.5
xlrd: 0.9.3
xlwt: None
xlsxwriter: 0.5.7
lxml: 3.4.0
bs4: 4.3.2
html5lib: None
httplib2: None
apiclient: None
rpy2: None
sqlalchemy: 0.9.7
pymysql: None
psycopg2: None

**Comment by jreback** [comment]
you are not doing the same things here. you have a 1 row x 1000 column frame. try ``df.T.plot(....)``

**Comment by rubennj** [comment]
You are right. I wanted to make a simplified model and I have just run it without seeing the graphs. I wanted to plot a column, but anyway here are both cases (row and column) and they are slower than direct MPL.
```
df = pd.DataFrame(data=np.random.normal(0, 1, (1,1000)))
dfT = pd.DataFrame(data=np.random.normal(0, 1, (1000,1)))

%timeit plt.plot(df.index, df.values)
1 loops, best of 3: 2.15 s per loop
%timeit df.plot()
1 loops, best of 3: 11.1 s per loop

%timeit plt.plot(dfT.index, dfT.values)
100 loops, best of 3: 3.64 ms per loop
%timeit dfT.plot()
1 loops, best of 3: 236 ms per loop
```

**Comment by jreback** [comment]
You are still not comparing the right plots. Here is an apples-apples comparison in that they produce the same number of graphs with the same layout. Pandas does quite a bit of inference then simply calls ``plt.plot()``.

```
In [5]: %timeit dfT[0].plot()
1 loops, best of 3: 9.46 ms per loop

In [10]: %timeit plt.plot(dfT[0].index,dfT[0].values)
1000 loops, best of 3: 864 us per loop
```

**Comment by jorisvandenbossche** [comment]
An example of what pandas also does is making a legend by default:

```
In [16]: %timeit df.plot()
1 loops, best of 3: 3.45 s per loop

In [17]: %timeit df.plot(legend=False)
1 loops, best of 3: 2.24 s per loop
```

So that is already a big part of the difference in this case.
