### ISSUE TITLE
DOC: fix autodoc Documenter for Accessor 

### ISSUE THREAD

**Issue by jorisvandenbossche** [pydata/pandas#9599]
See my comment here: https://github.com/pydata/pandas/pull/9322#issuecomment-71385126

For the methods on `dt` and `str` I fixed the api docs (https://github.com/pydata/pandas/commit/9b5a5ea18aceddecc3e033bc21f93c12e58bd313), but not yet for `dt` and `str`. Ideally, this needs to be done for the docs for final 0.16

**Comment by jreback** [comment]
@jorisvandenbossche moved to 0.17.0

**Comment by jorisvandenbossche** [comment]
ah, but this was fixed by #9721 that I just merged, forgot that I had an issue for this
