### ISSUE TITLE
BUG: hist plot secondary-y doesn't work

### ISSUE THREAD

**Issue by TomAugspurger** [pydata/pandas#9610]
The labels overlap

```python
In [1]: df = pd.DataFrame(np.random.randn(30, 4), columns=list('abcd'))

In [2]: ax = df.a.plot(legend=True)

In [3]: df.b.plot(ax=ax, legend=True)
Out[3]: <matplotlib.axes._subplots.AxesSubplot at 0x10938f6a0>
```

![hist](https://cloud.githubusercontent.com/assets/1312546/6541625/112de2b4-c4a2-11e4-8004-edb939520b04.png)

**Comment by TomAugspurger** [comment]
Actually not specific to `hist`.

**Comment by sinhrks** [comment]
After 9812: Because the code above seems to be different, I've used following code:

``` 
df = DataFrame(np.random.randn(30, 4), columns=list('abcd'))

# primary -> secondary
ax = df['a'].plot(kind='hist', legend=True)
df['b'].plot(kind='hist', ax=ax, legend=True, secondary_y=True)
```

![9610](https://cloud.githubusercontent.com/assets/1696302/6995307/006c4a08-db7a-11e4-8ada-046d7f4b4bf8.png)
