### ISSUE TITLE
fillna not accepting a None value

### ISSUE THREAD

**Issue by Cynddl** [pydata/pandas#9633]
In a DataFrame, it's not possible to use ``fillna`` to replace NaN values by ``None``:

```python
df = pandas.DataFrame([np.nan, 42])
df.fillna(value=None)
```
returns a ``ValueError`` exception (_ValueError: must specify a fill method or value_). Any other value is of course accepted.

I'm not sure if it's a good idea to call ``fillna`` for that, but it should at least be explained in the documentation that ``None`` cannot be used.

**Comment by jreback** [comment]
see docs here: http://pandas.pydata.org/pandas-docs/stable/missing_data.html

``NaN`` are missing values for numeric & object dtypes, ``None`` is also considered missing. In general you cannot fill ``None`` for other things. what you are doing is de-factor ``df.fillna()`` so you are missing the parameter; I think the exception documents this.

If you feel the docs are inadequate, pls submit a pull-request to improve doc-strings and/or docs.
