### ISSUE TITLE
DataFrame.plot error when both 'color' and 'style' arguments are passed

### ISSUE THREAD

**Issue by davidbrochart** [pydata/pandas#9671]
In pandas 0.15.2, when passing both arguments 'color' and 'style' to the plot method, there is an error which I think should be raised only when there is a color symbol in the style string. But in the example below, the error is raised even though there is no color symbol in the line string:

    from pandas import DataFrame
    import numpy as np
    df = DataFrame({'a': np.random.rand(10), 'b': np.random.rand(10), 'c': np.random.rand(10)})
    df.plot(color = ['red', 'black', 'blue'], style = ['-', '--', '-'])

The error is not clear (TypeError: expected string or buffer). This should be fixed, although it is easy to work around:

    df.plot(style = ['r-', 'k--', 'b-'])

**Comment by TomAugspurger** [comment]
It looks like your example is supposed to work, it's just that our regex in [this block](https://github.com/pydata/pandas/blob/master/pandas/tools/plotting.py#L873) checking for the color is expecting a string, not a list of strings. Notice that `df.a.plot(color = 'red', style = '-')` works correcly.

It should be a pretty quick fix, just check if `style` is an array-like of strings and check if any of those match the regex. Interested in submitting a PR?

**Comment by davidbrochart** [comment]
Sure, submitting a PR will be a first time for me, but there is always a first time ;-)

**Comment by TomAugspurger** [comment]
There is indeed! We're [here](https://gitter.im/pydata/pandas) if you have troubles. The only trick is to correctly determine whether it's a string or list. There's a function in pandas/core/common.py `is_list_like`. You should be able to use it with `com.is_list_like`.

**Comment by davidbrochart** [comment]
It looks like I've submitted a PR ;-)
https://github.com/pydata/pandas/pull/9673

**Comment by davidbrochart** [comment]
I've submitted a new PR #9674 with a test for the bug fix.

**Comment by TomAugspurger** [comment]
Closed via https://github.com/pydata/pandas/pull/9674
