### ISSUE TITLE
need for 'save_dataframe'

### ISSUE THREAD

**Issue by GregStG** [pydata/pandas#9677]
Saving and Retrieving are basic to data operations.  The defacto save / retrieve in 
pandas, at least from Wes's book, seems to be  to_csv and .read_csv  These are great, 
but what is saved is not what is returned:

In [49] frame
Out[49]: 
     fun        people  state
0   pinball   Joe       OH
1   food     Mary       NJ
 
In[50] frame.to_csv('experiment.csv')

In[51] new_frame=pd.read_csv('experiment.csv')

In[52]  new_frame
Out[52]: 
    
      Unnamed: 0   fun           people    state
0          0               pinball     Joe         OH
1          1               food         Mary       NJ

As you can see, a new index column is added.  I think it would probably be very easy to
write a 'save_DataFrame' and a 'read_DataFrame' that would save the index and the columns
and restore them as they were saved.

I realize this is no big deal once you know the program and the suggstion is, admittedly, mostly philosophical and to make things easier for newbies.   But I think this is the correct structure for
a data manipulation program.

This is just my opinion and I will only write this once.  I don't want to argue about it.
Please do not write to me and tell me how stupid I am.  Feel free just to trash this or 
close it out without informing me.
  
 Thanks.  -- Greg

**Comment by TomAugspurger** [comment]
That extra column is the index, which you clearly don't care about. Just use

```python
frame.to_csv('experiment.csv', index=False)
```

Indexes are often important in pandas, so that's why the default is True.
Nobody here would bash you for having a question :)

**Comment by GregStG** [comment]
Tom,

I know that.  And if save it again, you will get another index.  And that
can and does mess up lots of code.  What I want is a saving format which
saves the index and column headings separately so when you save it and and
read it back you don't essentially get two indices but the original index
that the data frame had.  It's pretty simple and obvious really, even
though nobody seems to get it.  A dataframe is essentially a matrix with a
set of names for the rows and the columns.  The names should be saved
separately.

I guess I'll have to talk to Wes about it.

Best,

Dr. Greg St. George

**Comment by TomAugspurger** [comment]
I guess maybe I didn't understand you're question then. Could you explain what you mean by saving the names separately?

Here's a successful round trip:

```
In [158]: df = pd.DataFrame({'a': [1, 2, 3], 'b': [1, 2, 3]})

In [159]: df
Out[159]: 
   a  b
0  1  1
1  2  2
2  3  3

In [160]: df.to_csv('test.csv')

In [161]: pd.read_csv('test.csv', index_col=0)
Out[161]: 
   a  b
0  1  1
1  2  2
2  3  3
```

Here's another one without the index:

```
In [162]: df.to_csv('test.csv', index=False)

In [163]: pd.read_csv('test.csv')
Out[163]: 
   a  b
0  1  1
1  2  2
2  3  3

In [164]: !cat test.csv
a,b
1,1
2,2
3,3
```

**Comment by shoyer** [comment]
CSV is a text format, so it's almost impossible to guarantee complete fidelity when saving/loading data. There's no place to store extra metadata like whether the index was included or not.

We usually recommend HDF5 when someone is looking for a higher performance data than CSV, but the pandas flavor of HDF5 also is better at doing things like preserving data types and keeping track of whether something is an index or not. I would definitely recommend giving it a try:
http://pandas.pydata.org/pandas-docs/stable/io.html#id2

**Comment by TomAugspurger** [comment]
I think I did just misread the original example. I'm pretty sure `pd.read_csv('experiment.csv', index_col=0)` is exactly what @GregStG is looking for.

**Comment by GregStG** [comment]
Stephen, Tom

Since a pandas DataFrame is an object with a index (row names) and a set of
column names, there should be a structure that saves those such that when
you save it, and then recall it, those two objects are the same.  I am just
saying that the structure you save should look like the structure you
have.  I have learned to work around this problem, but it is a problem with
pandas that this doesn't exist.  I have not investigated pandas internals
to know whether what I want is possible.  Maybe its very easy and you
essentially need a new name DataFrame_save for something that already
exists.

Anyway I am doing what I did not want to do, which is to argue about this.
I knew you would close this immediately and that is fine with me; I can
work around this problem with the stock data that I use.

Respectfully,

G.

**Comment by shoyer** [comment]
@GregStG That's exactly what `to_hdf`/`read_hdf` does... or, for that matter, `to_pickle`/`read_pickle` (though I don't particularly recommend using pickle files). As I explained, a limitation of the CSV file format is that it can't faithfully represent pandas DataFrame objects.

**Comment by GregStG** [comment]
Tom,

I haven't tried this, and I think you are right, because I don't think the
columns will ever be messed up.  Is the first column always the index? I do
the same thing by making all my data frames into time series, because I
always have a date column and I can pop that and assign it to the index.  I
haven't tried this, but if it always works, it should be flagged for the
next edition of Wes's book under 'saving dataframes'.

Greg

**Comment by TomAugspurger** [comment]
With my same `df` as before

```python
In [168]: df.index = pd.to_datetime(['2010-01-01', '2011-01-01', '2012-01-01'])
In [172]: df.to_csv('test.csv')

In [173]: pd.read_csv('test.csv', index_col=0, parse_dates=True)
Out[173]: 
            a  b
2010-01-01  1  1
2011-01-01  2  2
2012-01-01  3  3

In [174]: !cat test.csv
,a,b
2010-01-01,1,1
2011-01-01,2,2
2012-01-01,3,3
```

**Comment by GregStG** [comment]
Stephen,

Haven't tried that.  Sounds like exactly what I want.  If so, then it is,
as I suspected, just my ignorance of something that is already there.  But
since I am working from the book, which focuses on the csv format, there is
just a need for a footnote or something.  But most people don't work from
books as exclusively as I do.

Greg

**Comment by GregStG** [comment]
Tom,

Looks like that works fine, and so should be codified as the 'save_df'
function.  Thanks

Greg

**Comment by shoyer** [comment]
I have to admit, I have a copy of Wes's book on my desk at work but haven't read much of it :). This does seem like something worthy of a footnote, at least....

**Comment by TomAugspurger** [comment]
HDF5 has a section on pg. 169 (in my version).

**Comment by GregStG** [comment]
Tom, Stephen

Yes it's there, and I probably skipped over it because I didn't know what
HDF5 was.  Maybe it's just because I am a mathematician, but structure
matters, and if you create a structure (in this case the DataFrame) there
should be a prominently flagged way to save it and recall it, named
save_dataframe and read_dataframe (or whatever) which allows you to do the
two most basic operations with that thing.  It should be right there when
you first introduce the structure (in this case, the DateFrame).  I have no
problem with this now, or for the last year, but it was a lot of problem
when I first started because the location of columns changes depending on
how many times you have saved your data set, which is not a good property,
and causes you to have to right lots of extra, rather ugly, code.

Thanks all,

Greg

**Comment by GregStG** [comment]
T, S

sorry 'right' in the last line should be 'write'.

G.
