### ISSUE TITLE
to_csv keyword arguments missing?

### ISSUE THREAD

**Issue by ozak** [pydata/pandas#9718]
I just upgraded to 0.16.0 from 0.15.2 and the following command stopped working

    dflabels.to_csv('labels.do', encoding='utf-8', index=False, sep='\n', quoting=False, quotechar=' ')

I get the following error

    TypeError                                 Traceback (most recent call last)
    <ipython-input-20-332582a26117> in <module>()
    ----> 1 dflabels.to_csv('labels.do', encoding='utf-8', index=False, sep='\n', quoting=False, quotechar=' ')

    TypeError: to_csv() got an unexpected keyword argument 'quoting'

Any one else having this issue?

**Comment by ozak** [comment]
Ok...I just uninstalled and reinstalled it and now it works. Strange since even in 0.15 I had those arguments before.

**Comment by ozak** [comment]
Noticed that the issue was caused by the fact that the ``DataFrame.to_csv`` function has these additional attributes, while the ``Series.to_csv`` does not.

**Comment by DSLituiev** [comment]
I had the same problem. It is confusing that Series does not have this option, though DataFrame does.
Also trying to use `df[["myfield"]].to_csv( ... , quoting = QUOTE_NONE)` gives an error:
```
pandas/lib.pyx in pandas.lib.write_csv_rows (pandas/lib.c:17992)()

Error: single empty field record must be quoted
```
