### ISSUE TITLE
Cannot get Yahoo option data using Remote Data Access of Pandas

### ISSUE THREAD

**Issue by SelenaIsLovely** [pydata/pandas#9719]
I am trying to download Yahoo option data using the remote data access function of Pandas, I installed Anaconda on my laptop and launch ipython-qtconsole. I ran the following commands and got error "AttributeError: 'str' object has no attribute 'month', do I miss a module? If so, how can I find it?

from pandas.io.data import Options

aapl = Options('aapl', 'yahoo')
data = aapl.get_all_data()

AttributeError Traceback (most recent call last) in () ----> 1 data = aapl.get_all_data()

C:\Personal\Anaconda\lib\site-packages\pandas\io\data.pyc in get_all_data(self, call, put) 1109 1110 for month in months: -> 1111 m2 = month.month 1112 y2 = month.year 1113

AttributeError: 'str' object has no attribute 'month'

**Comment by jorisvandenbossche** [comment]
What version of pandas are you using? (show `pd.__version__`) This works for me using pandas 0.15.2

**Comment by SelenaIsLovely** [comment]
mine shows 0.14.1. I installed mine shows 0.14.1., not sure how to upgrade Pandas.

**Comment by jorisvandenbossche** [comment]
It seems you are using anaconda. Upgrading pandas is then as simple as: `conda update pandas`

**Comment by SelenaIsLovely** [comment]
Thanks a lot, that helps.
