### ISSUE TITLE
iterrows turns some columns from int64 to float64

### ISSUE THREAD

**Issue by graingert** [pydata/pandas#9728]
```python
>>> import pandas as pd
>>> pd.version.version
'0.15.2'
>>> df = pd.DataFrame({u'A': {123.0: 2.0}, u'B': {123.0: 1}})
>>> df
     A  B
123  2  1
>>> df['B'].dtype
dtype('int64')
>>> type(df.iterrows().next()[1]['B'])
<type 'numpy.float64'>
```

**Comment by jreback** [comment]
This is simply a consequence of putting together a cross-sectional that goes across dtypes and is as expected.

Anytime you slice a row from a frame and turn it into a Series this will happen. All dtypes are upcast to the common-dtype to hold them all.

```                                                                                                              
In [9]: df = pd.DataFrame({u'A': {123.0: 2.0}, u'B': {123.0: 1}, 'C' : 'foo'})                                
                                                                                                              
In [10]: list(df.iterrows().next())[1]                                                                        
Out[10]:                                                                                                      
A      2                                                                                                      
B      1                                                                                                      
C    foo                                                                                                      
Name: 123.0, dtype: object                                                                                    
                                                                                                              
```

**Comment by iosonofabio** [comment]
Sorry for reopening, is there a way of iterating over rows and keeping dtype?

**Comment by jorisvandenbossche** [comment]
@iosonofabio You can use `itertuples` for that, if you really need to iterate over rows. There is an updated section in the docs about this: http://pandas-docs.github.io/pandas-docs-travis/basics.html#iteration (not yet in stable docs)

**Comment by iosonofabio** [comment]
Thanks!

(I find it funny how much emphasis is put in pandas documentation about avoiding iterations. Of course it is slow, but people do not only use pandas for efficiency but also for simple bookkeeping :smile: )

**Comment by jorisvandenbossche** [comment]
Because people *do* complain about it being slow :-) And also quite some people use loops for things that are really not necessary, and even more complex to do with a loop (eg adding a number to all elements, I've seen this a lot when teaching pandas to beginners). 
But you're right, in certain cases, and if you know what you're doing, nothing wrong with it.
