### ISSUE TITLE
Pandas concat breaks with axis specified

### ISSUE THREAD

**Issue by Chris7** [pydata/pandas#9730]
I have an odd issue where if I specify the axis in concat it throws the following error:

InvalidIndexError: Reindexing only valid with uniquely valued Index objects

Pandas version: 0.16.0
OS: Ubuntu 14.04 LTS x64

Here's the pickle of the data structure causing this (it's rather large, ~60 megs, but it's my real use case which caused this error)

https://www.dropbox.com/s/02dn99dbi6p14um/pandas_error.pickle?dl=0

```
import pickle
import pandas as pd
l = pickle.load(open('pandas_error.pickle'))
scan_query = '(index >= 624.306193 & index <= 624.326171) | (index >= 624.807981 & index <= 624.826795) | (index >= 625.309633 & index <= 625.32635) | (index >= 628.315655 & index <= 628.331508) | (index >= 628.815043 & index <= 628.83164)'
# works
pd.concat([i.dropna().to_frame().query(scan_query) for i in l])
# breaks
#pd.concat([i.dropna().to_frame().query(scan_query) for i in l], axis=1)
```

**Comment by dsm054** [comment]
Well, you have a duplicate index.  `concat` can't figure out what number you want in the cell corresponding to (say) col=35.182033 and index=624.318843, because you have two values that want to go there.

**Comment by Chris7** [comment]
Thanks for pointing that out. Looks like I need to just use append.

Oddly, axis=0 breaks as well, which is the default, which should be equivalent to pd.concat([i.dropna().to_frame().query(scan_query) for i in l]).
