### ISSUE TITLE
HDFStore: AttributeError: __exit__ in with statement

### ISSUE THREAD

**Issue by cachitas** [pydata/pandas#9734]
I have this method in a class:

    def save(self, filename, key='/'):
        """Saves to an HDF5 store."""
        with pd.HDFStore(filename) as store:
            for g in self.GENDERS:
                df = getattr(self, g)
                store.put(key+g, df,
                          data_columns=df.columns,
                          format='table',
                          encoding='utf-8',
                          dropna=False)

and in my Unittest:

    def test_save_to_hdf(self):
        td = TrackData()
        with tempfile.NamedTemporaryFile(suffix='.h5') as temp:
            td.save(temp.name)

When I run nosetests I get this:

    ERROR: test_save_to_hdf (courtana.tracker.tests.test_trackdata.TestTrackData)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/hugo/projects/courtana/courtana/tracker/tests/test_trackdata.py", line 34, in test_save_to_hdf
        td.save(temp.name)
      File "/home/hugo/projects/courtana/courtana/tracker/trackdata.py", line 54, in save
        with pd.HDFStore(filename) as store:
    AttributeError: __exit__

Why did this suddenly stop working?

**Comment by jreback** [comment]
the ``HDFStore`` context manager was introduced in 0.15.2. are you sure you are using the same (or greater version). as you say 
>>>Why did this suddenly stop working?

stop working from what?

**Comment by cachitas** [comment]
Yeah I'm reaching that conclusion... I think I messed around with my virtualenvs and I'm doing the tests with version 0.13... Thank you for the hint!

**Comment by cachitas** [comment]
Ok turns out it is not an old version problem. I'm using 0.16.0 and still get that error.

> stop working from what?

When I use that code (`save` method) outside my Test class it works.

**Comment by TomAugspurger** [comment]
I don't think pd.HDFstore was ever a context manager. You want `pd.get_store(filename)`

**Comment by cachitas** [comment]
That is also referenced in #8791. But I find it odd that it is not mentioned in the docs. I can only find a `pd.get_storer()`. 
But note that the `pd.HDFStore` is mentioned in the docs and an example is given with a `with` statement ([IO Tools](http://pandas.pydata.org/pandas-docs/dev/io.html#hdf5-pytables))

```
# Working with, and automatically closing the store with the context
# manager
In [266]: with HDFStore('store.h5') as store:
   .....:     store.keys()
   .....: 
```

So what's the correct way of doing this?

**Comment by jreback** [comment]
@cachitas what you posted above should work just fine.

so be sure you have at least 0.15.2.

**Comment by cachitas** [comment]
I figured it out. For some reason I had version 0.16.0 in my virtualenv but when `nosetests` ran it was reporting 0.14... I reactivated it and it was solved. Looks like this was only a version issue from my side.
