### ISSUE TITLE
plotting: passing in ax is removing the wrong x labels

### ISSUE THREAD

**Issue by JanSchulz** [pydata/pandas#9737]
The following code will show the x labels on the right side, but actually it should show the labels at the bottom (or better: should show all!)

```
%matplotlib inline
import matplotlib.pyplot as plt
import matplotlib as mpl
import matplotlib.gridspec as gridspec
import pandas as pd
gs = mpl.gridspec.GridSpec(2, 2)
ax_tl = plt.subplot(gs[0,0])
ax_ll = plt.subplot(gs[1,0])
ax_tr = plt.subplot(gs[0,1])
ax_lr = plt.subplot(gs[1,1])

axes = [ax_tl, ax_ll, ax_tr, ax_lr]

df = pd.DataFrame({"a":[1,2,3,4,5,6], "b":[1,2,3,4,5,6]})

for ax in axes:
    df.plot(x="a", y="b", title="title", ax=ax)
gs.tight_layout(plt.gcf())
```

IMO: in `MPLPlot.__init__()`

```
def __init__(..., sharex=None,...):
    [...]
    if sharex is None: 
        if not ax is None:
             # if we get a ax, the users should know what he does... 
             sharex=False
        else:
             sharex = True
    [...]
```

**Comment by JanSchulz** [comment]
While I still think that the highets plotting command should refuse to handle `sharex` and `sharey` together with `not ax is None` (e.g. "if we don't build the axis, don't mess with them"), the following fix would at least do the right thing:

in `_handle_shared_axes`:

```
def _handle_shared_axes(axarr, nplots, naxes, nrows, ncols, sharex, sharey):
    if nplots > 1:

        if sharex and nrows > 1:
-            for ax in axarr[:naxes][:-ncols]:    # only bottom row
+           for ax in axarr:
+               # only the last row of subplots should get x labels -> all other off
+               if not ax.is_last_row():
+                   continue
[...]
        if sharey and ncols > 1:
            for i, ax in enumerate(axarr):
-                if (i % ncols) != 0:  # only first column
+               # only the first column should get y labels -> set all other to off
+               if not ax.is_first_col(): 
[...]
```
%matplotlib inline
import matplotlib.pyplot as plt
import matplotlib as mpl
import matplotlib.gridspec as gridspec
import pandas as pd
gs = mpl.gridspec.GridSpec(2, 2)
ax_tl = plt.subplot(gs[0,0])
ax_ll = plt.subplot(gs[1,0])
ax_tr = plt.subplot(gs[0,1])
ax_lr = plt.subplot(gs[1,1])

axes = [ax_tl, ax_ll, ax_tr, ax_lr]

df = pd.DataFrame({"a":[1,2,3,4,5,6], "b":[1,2,3,4,5,6]})

for ax in axes:
    df.plot(x="a", y="b", title="title", ax=ax, sharex=False)

for ax in plt.gcf().get_axes():
    if not ax.is_last_row():
        for label in ax.get_xticklabels():
            label.set_visible(False)
        ax.xaxis.get_label().set_visible(False)
    
gs.tight_layout(plt.gcf())
```

**Comment by JanSchulz** [comment]
I can do a PR with this two changes (adding the "sharex|y together with ax" check and using "is_last_row/first_col"), if someone says that this is the right way forward.

**Comment by JanSchulz** [comment]
Ok, just did that and uploaded in #9740

**Comment by TomAugspurger** [comment]
Thanks. I'll try to give it a look this weekend.

**Comment by TomAugspurger** [comment]
Closed by https://github.com/pydata/pandas/issues/9740

**Comment by JanSchulz** [comment]
Closing, as the PR is merged
