### ISSUE TITLE
Yahoo Datareader RemoteDataError when end date added in Python 3

### ISSUE THREAD

**Issue by ccsv** [pydata/pandas#9739]
See stackoverflow description: 

http://stackoverflow.com/questions/29296045/pandas-yahoo-datareader-remotedataerror-when-end-date-added?noredirect=1#comment46788752_29296045

**Comment by jreback** [comment]
pls post to : https://github.com/pydata/pandas-datareader

as this is where the future support will come from for the datareaders...

**Comment by ccsv** [comment]
Done
https://github.com/pydata/pandas-datareader/issues/36
