### ISSUE TITLE
BUG: utils.testing.get_locales()

### ISSUE THREAD

**Issue by dstephens99** [pydata/pandas#9744]
Line 334: raw_locales = [] deletes the data received from locale_getter, so the return from this function is always a blank list.

```python
  try:
        raw_locales = locale_getter()
    except:
        return None

    try:
        # raw_locales is "\n" seperated list of locales
        # it may contain non-decodable parts, so split
        # extract what we can and then rejoin.
        raw_locales = []
        for x in raw_locales:
            try:
                raw_locales.append(str(x, encoding=pd.options.display.encoding))
            except:
                pass
    except TypeError:
        pass

    if prefix is None:
        return _valid_locales(raw_locales, normalize)

    found = re.compile('%s.*' % prefix).findall('\n'.join(raw_locales))
    return _valid_locales(found, normalize)
```
https://github.com/pydata/pandas/blob/8d2818e32d0bbb50e183ccb5724c391e4f604670/pandas/util/testing.py#L334

**Comment by jreback** [comment]
it DOES run, but you have to override the locale; see the ``.travis.yml`` which sets the env variable which travis interprets.

**Comment by jreback** [comment]
see the install section: https://travis-ci.org/pydata/pandas/jobs/55924400

**Comment by jreback** [comment]
hmm, looking at the code it does seem that it is overriden...

**Comment by dstephens99** [comment]
I tried that in a test branch.  The problem is the code in pandas.utils.get_locales().

You get the locales:
raw_locales = locale_getter()
Next line that runs is:
raw_locales = []

So the function never returns any locales.

I made the fix in:
https://github.com/dstephens99/pandas/commit/4b1e35deb27d1795a5d269751d034f3196d6bff9

And the Travis test has a bunch of errors in TestGoogle (because it wasn't running before).
https://travis-ci.org/dstephens99/pandas/jobs/56178961

**Comment by dstephens99** [comment]
I'm fixing up the data-readers code, when I finish I'll make a pull request to update the pandas data / test_data code, then a pull request to fix this bug.

**Comment by jreback** [comment]
@dstephens99 ok, gr8!
