### ISSUE TITLE
Pandas io data.py market data feed source in question

### ISSUE THREAD

**Issue by jcrubino** [pydata/pandas#9749]
I was trying to fix a stock data feed error in data.py for python 2.7
I used line 124  to look into the problem. 

    # for codes see: http://www.gummy-stuff.org/[redacted]-data.htm

Is another reliable source available?

**Comment by jorisvandenbossche** [comment]
@jcrubino If you have further questions or issues with this, please raise a new issue at https://github.com/pydata/pandas-datareader (this functionality is split off from pandas into it's own package)
