### ISSUE TITLE
USMemorialDay defined incorrectly.

### ISSUE THREAD

**Issue by zegres** [pydata/pandas#9760]
Memorial day is incorrectly defined. 

    >>> from pandas.tseries.holiday import AbstractHolidayCalendar, USMemorialDay
    >>> class MemorialDayCalendar(AbstractHolidayCalendar): rules=[USMemorialDay]
    >>> MemorialDayCalendar().holidays('2021','2022')
    <class 'pandas.tseries.index.DatetimeIndex'>
    [2021-05-24]
    Length: 1, Freq: None, Timezone: None

The [actual date](http://www.calendar-12.com/holidays/memorial_day/2021) of Memorial day in 2021 is 5/31.

Memorial day should be defined as:
`Holiday('Memorial Day'    , month=5 , day=25, offset=DateOffset(weekday=MO(1)))`

**Comment by rockg** [comment]
One would think the test spanning 10 years was enough.  I agree that this is right...care to do a Pull Request?

**Comment by zegres** [comment]
OK, I made a pull request.

**Comment by jreback** [comment]
closed by #10282
