### ISSUE TITLE
API: DataFrame constructor for subclassing Series

### ISSUE THREAD

**Issue by sinhrks** [pydata/pandas#9762]
``Series.to_frame`` uses ``pandas.DataFrame`` statically as frame constructor. It is nice if ``Series`` has overridable property to specify frame-like constructor, like ``DataFrame`` has ``_constructor_sliced``. 

How about ``Series._constructor_frame``?

**Comment by jreback** [comment]
maybe ``_constructor_expanddim``? should add to ``generic`` as ``NotImplemented``; change ``to_panel`` (in frame) to use as well
