### ISSUE TITLE
Invalid comparison of object Series objects containing None

### ISSUE THREAD

**Issue by katastrofa999** [pydata/pandas#9768]
In pandas 0.15.2:

    from pandas import Series
    a = Series(['A', None])
    b = Series(['A', None])
    a == b

gives

    0     True
    1    False
    dtype: bool

while `a[1] == b[1]` gives `True`. This is a) inconsistent and b) the behaviour of `a == b` is wrong (None is equal to None, so `a==b` should return `[True, True]`.

**Comment by jreback** [comment]
In general ``np.nan`` is used as the sentinel for missing values. ``None`` ONLY appears on ``object`` dtypes. not that ``np.nan != np.nan``. Further see below.

```
In [34]: Series([1,np.nan]) == Series([1,np.nan])
Out[34]: 
0     True
1    False
dtype: bool

In [35]: Series(['A',np.nan]) == Series(['A',np.nan])
Out[35]: 
0     True
1    False
dtype: bool

In [36]: Series(['A',None]) == Series(['A',None])
Out[36]: 
0     True
1    False
dtype: bool
```
So this IS consistent with how the rest of pandas works. 


Further you should be using ``.isnull()/equals`` to compare things anyhow. Numpy (which implements the ``==`` operator for most cases), doesn't compare null positions correct.

```
In [23]: pd.isnull(a)
Out[23]: 
0    False
1     True
dtype: bool

In [24]: pd.isnull(b)
Out[24]: 
0    False
1     True
dtype: bool

In [25]: a.equals(b)
Out[25]: True
```

**Comment by katastrofa999** [comment]
It might be consistent, but it is in my opinion wrong when applied to non-numerical data. But if that is a policy decision in pandas then I'll just have to live with it.

How can I generate a mask with equals()?

**Comment by jreback** [comment]
use isnull see my example

**Comment by katastrofa999** [comment]
isnull() is applied to single Series, not to compare two of them.

**Comment by jreback** [comment]
the use equals that's point they are equal or they r not
you could compare the masks if u really want otherwise

**Comment by katastrofa999** [comment]
I'm afraid that doesn't really solve my problem. For two Series `a` and `b` containing objects I want to generate a third series

    e[i] := a[i] == b[i]

where `None == None` evaluates to `True`. I suppose I can do this with `(a == b) | (a.isnull() & b.isnull())` but that's quite a mouthful and traverses the Series objects more than once, which will be a performance problem for large datasets.

Any chance of modifying `equals` to optionally return a mask, then?

**Comment by jreback** [comment]
you can have a look at array_equivalent if you want

**Comment by katastrofa999** [comment]
Do you mean an existing function or that I could have a stab at it myself?

**Comment by jreback** [comment]
look in pandas.core.common

this implements equals
