### ISSUE TITLE
Website links to incorrect doc versions

### ISSUE THREAD

**Issue by gnomic** [pydata/pandas#9771]
http://pandas.pydata.org/pandas-docs/dev/index.html  PDF linnk returns a 0.14.x version of the document, other PDF links return 404. It all depends on how you get to the link. I suggest checking all the documentation links on the website to verify they are linking to the appropriate version of the documentation.

**Comment by jorisvandenbossche** [comment]
Yes, that is because I forgot to upload the pdf for the dev docs (problem is that we don't really use the dev docs anymore)

Which other links are you talking about?

**Comment by jorisvandenbossche** [comment]
Closing this, as it are only the dev docs that has this problem (but please reopen if you update with other links!)
