### ISSUE TITLE
Boolean negation gives wrong output when dtype is not boolean

### ISSUE THREAD

**Issue by hertzmann** [pydata/pandas#9782]
When a Series or DataFrame has boolean elements, but the dtype is not bool, the elementwise negation operator (~) performs bitwise complement instead of negation. I got bit by this surprising behavior and it took awhile to track down and understand:

```
In [1]: import pandas as pd

In [2]: s = pd.Series([None,True])

In [3]: s.iloc[0] = False

In [4]: s
Out[4]: 
0    False
1     True
dtype: object

In [5]: ~s
Out[5]: 
0    -1
1    -2
dtype: object
```
whereas one would normally expect this sort of behavior:
```
In [6]: t = pd.Series([False,True])

In [7]: t
Out[7]: 
0    False
1     True
dtype: bool

In [8]: ~t
Out[8]: 
0     True
1    False
dtype: bool
```
Here's my version information:
```
% ipython
Python 2.7.9 |Anaconda 2.2.0 (x86_64)| (default, Dec 15 2014, 10:37:34) 
Type "copyright", "credits" or "license" for more information.

IPython 3.0.0 -- An enhanced Interactive Python.

In [12]: pd.show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.9.final.0
python-bits: 64
OS: Darwin
OS-release: 14.1.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

pandas: 0.15.2
nose: 1.3.4
Cython: 0.22
numpy: 1.9.2
```

**Comment by shoyer** [comment]
I agree this behavior is surprising. Unfortunately, this is how Python defines `~` for booleans:
```
In [20]: ~False
Out[20]: -1

In [21]: ~True
Out[21]: -2
```

We could do more aggressive dtype inference to cast the first array to `dtype=bool`, but would likely have severe negative performance implications.

**Comment by hertzmann** [comment]
This makes sense. 

One could argue that this behavior is really a consequence of overloading `~` as logical not. In fact, if `~False=-1`, then it seems like it's more consistent to produce `-1` than `False` when applying `~` to a boolean array.

What I'd like to have is some function or operator equivalent to `s.map(lambda x: not x)`, and probably a warning to be careful when using `~` on booleans. This function/operator could check the dtype, and, if it's bool, it could run whatever efficient algorithm is currently being used. (I'm just speculating, since I don't know the actual inner workings.)

**Comment by shoyer** [comment]
Well, for this functionality we currently rely entirely on numpy -- so this is also an issue there.

In any case, the operation you're looking for is `np.logical_not`, which should work fine on pandas objects. I tend to prefer `logical_not` to `~` for exactly these sorts of reasons.

**Comment by hertzmann** [comment]
Ok, thank you!
