### ISSUE TITLE
groupby() changes values of pandas.Timestamp (pandas 0.15.2)

### ISSUE THREAD

**Issue by katastrofa999** [pydata/pandas#9788]
import datetime as dt; import pandas as pd
    d2 = dt.datetime(2015, 4, 2, 12, 23, 12, 567000)
    df = pd.DataFrame([['Bar', d2]], columns=['name', 'date'])
    df2 = df.sort('date').groupby('name').last().reset_index()

`df2` is

name	date
0	Bar	2015-04-02 12:23:12.567000064

i.e. 64 nanoseconds were added to the timestamp. The amounts added seem to be always the powers of 2, perhaps it is caused by some internal conversion to double?

**Comment by jreback** [comment]
this was fixed in 0.16.0, see #9311, #6620

```
In [1]: import datetime as dt; import pandas as pd

In [2]: d2 = dt.datetime(2015, 4, 2, 12, 23, 12, 567000)

In [3]: df = pd.DataFrame([['Bar', d2]], columns=['name', 'date'])

In [4]: df2 = df.sort('date').groupby('name').last().reset_index()

In [5]: df2
Out[5]: 
  name                       date
0  Bar 2015-04-02 12:23:12.567000

In [6]: df2.iloc[0,1]
Out[6]: Timestamp('2015-04-02 12:23:12.567000')

In [7]: df2.iloc[0,1].value
Out[7]: 1427977392567000000
```
