### ISSUE TITLE
Issue when installing Pandas 0.16 on Windows using Conda

### ISSUE THREAD

**Issue by canyon289** [pydata/pandas#9791]
Hi,
I tried installing pandas .16 using conda in windows but am getting the following issue. I tried reinstalling using an admin console but it doesn't work. I've downgraded to 0.15.2 which works again but could use help.

This is my first time posting so if this is not the appropriate channel please let me know.

Thanks in advance
        C:\Users\kumarra>ipython
	Python 3.4.1 |Continuum Analytics, Inc.| (default, Jun 11 2014, 17:27:11) [MSC v
	.1600 64 bit (AMD64)]
	Type "copyright", "credits" or "license" for more information.

	IPython 3.0.0 -- An enhanced Interactive Python.
	Anaconda is brought to you by Continuum Analytics.
	Please check out: http://continuum.io/thanks and https://binstar.org
	?         -> Introduction and overview of IPython's features.
	%quickref -> Quick reference.
	help      -> Python's own help system.
	object?   -> Details about 'object', use 'object??' for extra details.

	In [1]: import pandas
	---------------------------------------------------------------------------
	TypeError                                 Traceback (most recent call last)
	pandas\tslib.pyx in pandas.tslib.Timedelta.__new__ (pandas\tslib.c:29661)()

	TypeError: 'nanoseconds' is an invalid keyword argument for this function

	During handling of the above exception, another exception occurred:

	ValueError                                Traceback (most recent call last)
	<ipython-input-1-d6ac987968b6> in <module>()
	----> 1 import pandas

	C:\Miniconda3\lib\site-packages\pandas\__init__.py in <module>()
		 45
		 46 # let init-time option registration happen
	---> 47 import pandas.core.config_init
		 48
		 49 from pandas.core.api import *

	C:\Miniconda3\lib\site-packages\pandas\core\config_init.py in <module>()
		 15                                 is_instance_factory, is_one_of_factory,
		 16                                 get_default_val)
	---> 17 from pandas.core.format import detect_console_encoding
		 18
		 19

	C:\Miniconda3\lib\site-packages\pandas\core\format.py in <module>()
		 22 import csv
		 23
	---> 24 from pandas.tseries.period import PeriodIndex, DatetimeIndex
		 25
		 26 docstring_to_string = """

	C:\Miniconda3\lib\site-packages\pandas\tseries\period.py in <module>()
		  6 from pandas.core.base import PandasObject
		  7
	----> 8 import pandas.tseries.frequencies as frequencies
		  9 from pandas.tseries.frequencies import get_freq_code as _gfc
		 10 from pandas.tseries.index import DatetimeIndex, Int64Index, Index

	C:\Miniconda3\lib\site-packages\pandas\tseries\frequencies.py in <module>()
		  7
		  8 from pandas.core.algorithms import unique
	----> 9 from pandas.tseries.offsets import DateOffset
		 10 from pandas.util.decorators import cache_readonly
		 11 import pandas.tseries.offsets as offsets

	C:\Miniconda3\lib\site-packages\pandas\tseries\offsets.py in <module>()
	   2150
	   2151
	-> 2152 class Nano(Tick):
	   2153     _inc = Timedelta(nanoseconds=1)
	   2154     _prefix = 'N'

	C:\Miniconda3\lib\site-packages\pandas\tseries\offsets.py in Nano()
	   2151
	   2152 class Nano(Tick):
	-> 2153     _inc = Timedelta(nanoseconds=1)
	   2154     _prefix = 'N'
	   2155

	pandas\tslib.pyx in pandas.tslib.Timedelta.__new__ (pandas\tslib.c:29707)()

	ValueError: cannot construct a TimeDelta from the passed arguments, allowed keyw
	ords are [days, seconds, microseconds, milliseconds, minutes, hours, weeks]

**Comment by shoyer** [comment]
Probably a good idea to re-file this over at [anaconda-issues](https://github.com/continuumio/anaconda-issues/issues)

**Comment by TomAugspurger** [comment]
I did have a similar sounding issue updating last time where another python process was open. Fixed by closing all the processes and `conda install -f pandas`.

**Comment by jreback** [comment]
yes you need to force install
you had Python open when u installed

**Comment by canyon289** [comment]
I did a force install after ensuring that Python wasn't open but I'll try it again. I'll move this. Thank you guys
