### ISSUE TITLE
Pandas DataFrame.plot() does not default to matplotlib rcparams grid setting

### ISSUE THREAD

**Issue by jdavidheiser** [pydata/pandas#9792]
When using df.plot() to creat a simple line chart from a dataframe, the expected behavior is that, if no 'grid' keyword is passed, the plot will default to the matplotlib 'axes.grid' rcParam setting to determine whether to show a grid or not.  However (in 0.16), the grid is always being shown, regardless of the matplotlib setting, unless I explicitly pass grid=False.

In general, there are several plot types where grid=True is forced, which basically breaks the consistent styling that you get from matplotlib rcparams or another package like Seaborn.  I can understand forcing a default grid=False for the type of plots where a grid doesn't make sense, but forcing grid=True, overriding the configured defaults, for things like boxplots seems a bit counter intuitive.

**Comment by TomAugspurger** [comment]
Agreed for the most part, but where do we draw the line (sorry for the bad pun). I'm not sure which plots grids makes sense on. I guess have grids for line, scatter, density. No grid for box. On barplots I usually only have gridlines along the `y` axis, but I'm not sure that's the best default.

**Comment by jdavidheiser** [comment]
my opinion is that they should fall back on rcparams for almost everything, except those where grid lines make no sense at all.  The problem with overriding rcparams is that it 'breaks' the default matplotlib behavior for people who are used to using matplotlib.

**Comment by artemyk** [comment]
I also ran into this issue and found it very confusing and --- worst of all --- in conflict with the documentation (which says that not passing in grid will result in matplotlib default)

**Comment by TomAugspurger** [comment]
Should be a pretty simple fix if you're up to submitting a PR.

The signature should still be `df.plot(..., grid=None, ...)`.

If the user specifies `True` or `False`, we use that.

If they leave the default of `None`, we either

- overriding `plt.RcParams` for `box` and `pie` (setting `grid=False`)
- fall back to rcParams otherwise

**Comment by artemyk** [comment]
@TomAugspurger  OK, I made a PR.  `box` can go either way, I believe.
