### ISSUE TITLE
PyCon 2015 sprints

### ISSUE THREAD

**Issue by jreback** [pydata/pandas#9811]
I am going to be hosting a 2-day *pandas* sprint at ``PyCon 2015``, on April 13-14, see [here](https://us.pycon.org/2015/). Thanks for choosing to partcipate!

We are in room 513D.

This issue will be the landing page for contributors.

[pandas](http://pandas.pydata.org) is an open source, BSD-licensed library providing high-performance, easy-to-use data structures and data analysis tools for the Python programming language. 

See our shiny new [Contributing Guidelines & Instructions](http://pandas-docs.github.io/pandas-docs-travis/contributing.html)

Here are various issues that are open and would like your attention:

- [Difficulty Novice](https://github.com/pydata/pandas/issues?q=is%3Aopen+is%3Aissue+label%3A%22Difficulty+Novice%22)
- [Difficulty Intermediate](https://github.com/pydata/pandas/issues?q=is%3Aopen+is%3Aissue+label%3A%22Difficulty+Intermediate%22)
- [Difficulty Advanced](https://github.com/pydata/pandas/issues?q=is%3Aopen+is%3Aissue+label%3A%22Difficulty+Advanced%22)

List of issues that would be nice to fix:
- https://github.com/pydata/pandas/issues/5724
- https://github.com/pydata/pandas/issues/5677
- https://github.com/pydata/pandas/issues/7820
- https://github.com/pydata/pandas/pull/7872
- https://github.com/pydata/pandas/issues/9847
- https://github.com/pydata/pandas/issues/9862
- https://github.com/pydata/pandas/issues/9602

Please comment on an issue if you are working on it.

Here is a [link](https://gitter.im/pydata/pandas) to the gitter chatroom.
For people who would like to participate remotely, I will post a link to a google hangout.

**Comment by TomAugspurger** [comment]
[link](https://gitter.im/pydata/pandas) to our chat room. I'll be available there as much as possible during the sprint.

**Comment by jreback** [comment]
List of issues that would be nice to fix:
- https://github.com/pydata/pandas/issues/5724

**Comment by scari** [comment]
I don't really want to mess this issue thread with somewhat OT comment but I'm in sprints introduction at room 511 now and couldn't get you @jreback 
Would you let me know what time it would starts and where?
