### ISSUE TITLE
Holiday.dates always fails with tz-aware input

### ISSUE THREAD

**Issue by ssanderson** [pydata/pandas#9825]
The conversion from `start_date` to `base_date` on https://github.com/pydata/pandas/blob/master/pandas/tseries/holiday.py#L206 drops tz information, which causes the `DatetimeIndex` constructor to barf if end_date is tz-aware.  Fixed by https://github.com/pydata/pandas/pull/9824.

**Comment by jreback** [comment]
closed by #9824
