### ISSUE TITLE
add Cython version as a pip dependency

### ISSUE THREAD

**Issue by drevicko** [pydata/pandas#9827]
When I tried to pip install pandas on a system with cython 0.15.1, it failed (I'm guessing that's not surprising). After pip installing cython (to 0.22), pandas installs fine. The error messages talked about missing lib.pxd and tslib.pxd files - to my untrained eye, Cython wasn't an obvious culprit!

My point is that, unless there's a good reason not to, the minimum cython version for compiling pandas should be a dependency in pip.

**Comment by shoyer** [comment]
Cython actually isn't an install requirement for pandas if you are using the pypi distribution (what you get from `pip install pandas`) -- it should install just fine without it. Frankly, I would think it should work even if you only have an older version of Cython installed... how did you install pandas?

**Comment by drevicko** [comment]
`pip install pandas` from within a virtualenv with system-site-packages turned on.

**Comment by shoyer** [comment]
Hmm. Looking through our setup.py file, it appears we attempt to build with Cython if it's installed without checking any minimum versions. That is indeed problematic -- the installation page mentions that cython 0.19.1 is required to build the dev version.

**Comment by jreback** [comment]
I suppose you could add this similarly to how ``numpy/pytz/dateutil`` are there. though the min version of cython is 0.19.1 is over 2 years old (and 0.15.1 is almost 4).

building with system installed libraries is not generally recommended, see the [install instructions](http://pandas.pydata.org/pandas-docs/stable/install.html)

**Comment by drevicko** [comment]
Yeah, it's an unusual case: a university server where I've not got sudo privelidges and Ubuntu 12.04 (with about 40 updates not installed! It's behind a firewall though..). Anyway, it's an easy fix and helpful for others in a similar situaion (:

**Comment by jreback** [comment]
@drevicko gr8 thanks!

**Comment by bashtage** [comment]
@drevicko You might want to consider Anaconda (esp Miniconda as a starting point)

**Comment by ajamian** [comment]
Attempting this as part of pycon sprints.

**Comment by jreback** [comment]
closed by #9881
