### ISSUE TITLE
Ubuntu daily builds are broken due to hg-git import

### ISSUE THREAD

**Issue by timmie** [pydata/pandas#9831]
Canonical/Ubuntu's launchpad was importing this repo on daily basis and creating packages for Ubuntu based distros
https://code.launchpad.net/~pythonxy/+archive/ubuntu/pythonxy-devel/+packages?field.name_filter=pandas

This run well for many years until recently some changes in the repo broke the chain:

>> The problem is that the Git repository was imported from Mercurial, and recent versions of hg-git >>add some >non-standard commit headers that bzr-git doesn't support, and it isn't clear how they >>should be supported.

>They must have recently merged a branch that was created by a new version of hg-git.

Please have a look to a discussion with a Launchpad developer here:
https://answers.launchpad.net/launchpad/+question/264432

Is there anything the maintainers could do to fix this issue?

Else, we would have to wait until Launchpad supports git directly.

**Comment by jreback** [comment]
ok, since this is not directly a pandas issue, closing. but you can make comments if needed.

**Comment by shoyer** [comment]
Unfortunately, we don't have a good way to control how people make contributions to pandas, and at this point the problematic merge has happened -- so per the discussion on Launchpad, there's not anything we can do on our end short of rebasing master, which is not an option. I'm sure there are other work arounds but some interested outside party who cares about this (you?) will need to figure them out.

**Comment by timmie** [comment]
OK, thanks for the clear reply.

I will wait until Launchpad will have the git feature, then.

Just for your notice, the daily builds are also in the docs:
https://github.com/pydata/pandas/blob/master/doc/source/install.rst#installing-using-your-linux-distributions-package-manager

**Comment by shoyer** [comment]
Thanks for pointing that out -- it's probably worth removing that from our docs. Even if it still worked, I don't think we have any good reason for recommending daily builds to end users.

**Comment by timmie** [comment]
>I don't think we have any good reason for recommending daily builds to end users.

Reason was that offical packages were many times very outdated due to distro release cycles.

Up to your consideration.

**Comment by shoyer** [comment]
> Reason was that offical packages were many times very outdated due to distro release cycles.

Yes, this makes sense, but pandas itself makes releases every few months, so it would be a better idea to be mirroring those instead of the git-master.

**Comment by timmie** [comment]
>so it would be a better idea to be mirroring those instead of the git-master.

Sure. I think this is what Neurodebian does. But it's a manual procedure...
So those wanting official stuff could go there.

The git-master builds were initiated around 2010 when pandas was receiving essential new features (e.g. timeseries capability) with every commit. And these were not available in the distros.

And these builds are similar to a conda install, I would guess.

That's also why
https://github.com/pydata/pandas/blob/master/doc/source/install.rst#installing-using-your-linux-distributions-package-manager
says: unstable (latest packages) for Neurodebian (not: unstable from distro perspective) and unstable (daily builds) for the other packages. So the user is definitely warned.

**Comment by jorisvandenbossche** [comment]
Just a question on SO where someone followed the instructions on our website and installed pandas 0.8.0: http://stackoverflow.com/questions/29536848/pandas-to-datetime-got-an-unexpected-keyword-argument-unit

Maybe we should be more clear on the installation page that the official stable repos are not really recommended, and that eg at least use the neurodebian ones.
