### ISSUE TITLE
Dict View Issue in IO data.py

### ISSUE THREAD

**Issue by hirokib** [pydata/pandas#9833]
If using python 3.4 there will always be a TypeError thrown in the data.py 
lines 330-332

        if len(stocks) > 0 and len(failed) > 0:
            df_na = stocks.values()[0].copy()
            df_na[:] = np.nan

For python 3 users the stock.values needs to be wrapped because it's returning a view not a list

            df_na = list(stocks.values())[0].copy()

**Comment by hirokib** [comment]
Sorry, wrote the fix off the top of my head and was incorrect. In either case can't index into a dictionary view object in python 3.x +

**Comment by jreback** [comment]
you should give a specific example as well as show ``pd.show_versions()``. but need to be in https://github.com/pydata/pandas-datareader
