### ISSUE TITLE
Add key option to sort methods

### ISSUE THREAD

**Issue by SethMMorton** [pydata/pandas#9855]
One feature that I am missing from dataframes is to sort with a custom `key` function, similar to the builtin `sorted` or `list.sort`. I see there is some effort to unify sorting in issue #8239, so it might be a nice to add this powerful functionality to `pandas` while the sorting API is being overhauled.

**Comment by jreback** [comment]
pls show an example of what/how this would be used as generally you can simply pass in the column name.

**Comment by jreback** [comment]
dupe of #3942 
(you can add an example to that issue)

**Comment by SethMMorton** [comment]
I have added the specific example to the dupe.  Thanks!
