### ISSUE TITLE
Add test for sdist and pandas import

### ISSUE THREAD

**Issue by ajamian** [pydata/pandas#9878]
As a follow-on to #9827, add a test for packaging pandas and importing that package into a venv that does not contain cython via https://github.com/pydata/pandas/wiki/Release-Checklist:
* python setup.py sdist --formats=zip,gztar
* create virtualenv with pandas dependencies (requirements_dev.txt), minus cython
* pip install <path_to_dist_tar.gz>
* run some subset of nosetests once installed

**Comment by jreback** [comment]
@ajamian I think we could modify one of the current builds to actually just do this
triggered by a new env variable (this way wouldn't need another new build)

**Comment by ajamian** [comment]
@jreback sounds good; i was thinking of adding a variable to the 2.6 regression, and add some stuff to the end of script.sh to create the limited venv and then test the install.
