### ISSUE TITLE
Calling shift on a DatetimeIndex of length 0 returns an Index instead of a DatetimeIndex 

### ISSUE THREAD

**Issue by ssanderson** [pydata/pandas#9903]
Minimal repro:
```
In [5]: pandas.__version__
Out[5]: '0.16.0-151-gcef3c85'

In [7]: DatetimeIndex([]).shift(3, 'H')
Out[7]: Index([], dtype='object')
```

**Comment by ssanderson** [comment]
(This happens because DatetimeIndex delegates to Index.shift, which then calls the Index.__new__ with an empty list, and it can't infer that the output should be a DatetimeIndex.)

**Comment by ssanderson** [comment]
This is fixed by #9904.

**Comment by sinhrks** [comment]
This has been already fixed in current master (maybe by #11211?). Adding tests then close.

**Comment by jreback** [comment]
@sinhrks looks good.

```
In [1]: DatetimeIndex([]).shift(3, 'H')
Out[1]: DatetimeIndex([], dtype='datetime64[ns]', freq=None)
```

I since we have 0 len we don't infer the freq, but in this case we *know* the freq (as we are shifting by it), or is that too much carry-over?

**Comment by sinhrks** [comment]
``DatetimeIndex.freq`` is common frequencies between elem, and it can be different from shifting freq. Thus it sounds making an exception in length=0 case. Thoughts? 

```
s = pd.DatetimeIndex(['2011-01-01', '2011-01-02'], freq='D')
s.shift(1, 'H')
# DatetimeIndex(['2011-01-01 01:00:00', '2011-01-02 01:00:00'], dtype='datetime64[ns]', freq=None)
```

**Comment by jreback** [comment]
cc @ssanderson 
cc @llllllllll

**Comment by jreback** [comment]
@sinhrks no, I was more thinking that If I shift an index, then I want to have it set the freq (as opposed to infer it which won't work if its < 3 elements). not really strong here opinion here, except that this was from a user action.

**Comment by ssanderson** [comment]
@jreback I don't think that shifting an index by a specific frequency should be taken to imply that the index's data has that frequency.  If I have an hourly-frequency index, and I shift it forward by 5 minutes, it's still hourly frequency.  That doesn't change if my index is empty.

**Comment by ssanderson** [comment]
https://github.com/pydata/pandas/pull/13026 looks good to me btw.  Thanks @sinhrks.

**Comment by jreback** [comment]
@ssanderson hmm, that is right. ok then!

**Comment by jreback** [comment]
thanks @sinhrks
