### ISSUE TITLE
Series don't plot in nbagg while dataframe.plot() call works

### ISSUE THREAD

**Issue by michaelaye** [pydata/pandas#9919]
All explained here:
http://nbviewer.ipython.org/gist/michaelaye/4af80037146dfb65b105

Not sure if I should have submitted it here or with matplotlib. Just let me know, then I can open one there.

Output of pd.show_versions():

INSTALLED VERSIONS
------------------
commit: None
python: 3.4.3.final.0
python-bits: 64
OS: Linux
OS-release: 2.6.32-431.11.2.el6.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

pandas: 0.16.0-151-gcef3c85
nose: 1.3.6
Cython: 0.22
numpy: 1.9.2
scipy: 0.15.1
statsmodels: 0.6.1
IPython: 3.2.0-dev
sphinx: 1.2.3
patsy: 0.3.0
dateutil: 2.4.2
pytz: 2015.2
bottleneck: None
tables: 3.1.1
numexpr: 2.3.1
matplotlib: 1.4.3
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 0.9.9
pymysql: None
psycopg2: None

**Comment by jorisvandenbossche** [comment]
I am not fully sure (should look into more detail), but possibly related to the same issue that I reported here: https://github.com/matplotlib/matplotlib/issues/4281 
Also, know that `Series.plot()` does not create a new figure but gets added to the 'current figure', if this exists. WIth nbagg, this means the previous figure that is shown inline in the notebook that gets updated.

**Comment by michaelaye** [comment]
That's good to know, thanks, but why is that so? I would certainly like to be able to control that? (without doing cumbersome `fig, ax = plt.subplots()...` Is there a keyword to force Series.plot() to create a new plot?

**Comment by jorisvandenbossche** [comment]
See #8776 for some discussion on this.

You can also always add ``plt.figure()`` before the `Series.plot()` call, if you don't want to go the `fig, ax = plt.subplots()` route. 
Also note that this is the same behaviour as with `plt.plot()`

**Comment by michaelaye** [comment]
Oh, wow, I even did not see that plt.plot() also cannot open a new plot with `nbagg`, I am using pandas plotting so often for everything. ;) Thanks for the link.

**Comment by jorisvandenbossche** [comment]
Do you think there is still an issue, apart from the things I pointed out? Otherwise you can close the issue.
