### ISSUE TITLE
Initialising a dataframe with empty data and column names fails

### ISSUE THREAD

**Issue by filmor** [pydata/pandas#9948]
The following fails:

    pd.DataFrame([], columns="a b".split())

I'd expect this to be equivalent to

    pd.DataFrame(None, columns="a b".split())

Is there any reason not to do it like this?

**Comment by alan-wong** [comment]
Why do you expect this to work, you've passed a list with a single empty element? It is clearly not the same shape when you pass a list of columns containing 2 elements?

**Comment by filmor** [comment]
Well, the following works:

    pd.DataFrame([(1, 2), (2, 3)], columns="a b".split())

If I pass an empty `list` that is merely the empty variant of the same statement.

**Comment by alan-wong** [comment]
No, it's clearly different the DataFrame ctor is trying to deduce the final shape of the df, as you've passed an iterable object it'll assert that the shapes of the passed data and columns agree which they don't this is different to when you explicitly pass `None`

**Comment by jreback** [comment]
this is fixed by #9939. Its an edge case in the inference. You can't deduce the shape of the data, but you do have the column information so it just returns an empty frame. Either the data has to exactly match the number of columns in a list or has to be empty.
