### ISSUE TITLE
Docs: Add reference to pandaSDMX to the pandas Ecosystem page in the API section

### ISSUE THREAD

**Issue by dr-leo** [pydata/pandas#9962]
I would be pleased if pandaSDMx (http://pandasdmx.readthedocs.org) could be added to the pandas Ecosystem directory. The following text is just a proposal, feel free to change it as you see fit:

"pandaSDMX is a libraryaimed at becoming the most intuitive and versatile tool to retrieve and acquire statistical data and metadata disseminated in 
SDMX
 format. As of v0.2 it works well with the SDMX services of the European statistics office (Eurostat) and the European Central Bank (ECB) both of which provide hundreds of thousands social and economic indicators. While pandaSDMX is extensible
to cater any output format, it currently exports SDMX datasets with observations and/or attributes to multi-indexed pandas DataFrames and Series. Metadata such as datastructure definitions, dataflow definitions, and code lists are represented in terms of the SDMX-2.1 information model."

**Comment by jorisvandenbossche** [comment]
I think that could certainly be added. Can you make a PR for this?

**Comment by dr-leo** [comment]
Well, why not? Maybe because I have to learn how to rebase. I have an
older PR which should be ok but hasn't been rebased yet. And even if I
did rebase it, I could not compile on Win7 with MinGW. The compiling
instructions  works on the install page of pandas are not very helpful.
But yes, for this small PR I'll try again hoping no rebaseing will be
needed.






Am 21.04.2015 um 18:28 schrieb Joris Van den Bossche:

**Comment by jreback** [comment]
http://pandas-docs.github.io/pandas-docs-travis/contributing.html are the new contributing guidelines

**Comment by jorisvandenbossche** [comment]
For a small addition to the docs, you don't need to compile pandas (or also the docs is not required), so that shouldn't be the problem! 
And if there would be a problem with rebasing, we are here to help you

**Comment by dr-leo** [comment]
Thanks. I've compiled it for the first time. libpython was missing. - I
need compiling to test my other PR on hashable Series.name which has, I
understand, not been merged yet...

Chances are that I'll finally get there shortly.

Am 21.04.2015 um 23:45 schrieb Joris Van den Bossche:

**Comment by dr-leo** [comment]
Done.

https://github.com/pydata/pandas/pull/10007

Am 21.04.2015 um 23:45 schrieb Joris Van den Bossche:
