### ISSUE TITLE
dividing by integers wierd in 0.14.1

### ISSUE THREAD

**Issue by hhuuggoo** [pydata/pandas#9973]
In [1]: import pandas as pd; pd.Series ([-49.2, 0.0], index=[0,1]) / pd.Series([49,0], index=[0,1])                                                                                  
Out[1]: 
0   -inf
1    inf
dtype: float64

This appears to be resolved in 0.15, and 0.16 - so not sure that this is worth reporting

**Comment by jreback** [comment]
thanks for the report Hugo 
yes has been resolved to work in later versions by #7785 and a follow on fix iirc
