### ISSUE TITLE
Wrong/better error message for AttributeError with wrong attribute in attribute. 

### ISSUE THREAD

**Issue by fnielsen** [pydata/pandas#9976]
Pandas (core.generic) gives a misleading error message for AttributeError with wrong attribute in attribute in version 0.16.0. Example:

    import pandas as pd
    
    class MyDataFrame(pd.DataFrame):
        @property
        def my_attribute(self):
            self.a_wrong_attribute
            return 'Hello, World'

Applying it yields:

    >>> my_frame = MyDataFrame()
    >>> my_frame.my_attribute
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/lib/python2.7/dist-packages/pandas/core/generic.py", line 1978, in __getattr__   (type(self).__name__, name))
    AttributeError: 'MyDataFrame' object has no attribute 'my_attribute'

The 'my_attribute' is of course there. I would have expected: 

    AttributeError: 'MyDataFrame' object has no attribute 'a_wrong_attribute'

It would be nice with a better error message directly pointing to the wrong attribute. The problem also appears for, e.g., the pandas.Panel class.

**Comment by jreback** [comment]
read and understsbd fully this section
http://pandas-docs.github.io/pandas-docs-travis/internals.html#subclassing-pandas-data-structures

you are not registering the attributes properly 
sub classing though possible is not usually a good idea

**Comment by fnielsen** [comment]
Thanks! Setting `_metadata` works fine.
