### ISSUE TITLE
Plot matrix (and more specifically confusion matrix)

### ISSUE THREAD

**Issue by scls19fr** [pydata/pandas#9993]
Hello,

I don't find any method to plot a matrix (such as confusion matrix) using "pure" Pandas.

Having a more convenient approach than
http://scikit-learn.org/stable/auto_examples/model_selection/plot_confusion_matrix.html
http://matplotlib.org/examples/pylab_examples/matshow.html
will be great.

    import pandas as pd
    y_actu = pd.Series([2, 0, 2, 2, 0, 1, 1, 2, 2, 0, 1, 2])
    y_pred = pd.Series([0, 0, 2, 1, 0, 2, 1, 0, 2, 0, 2, 2])

    df_confusion = pd.crosstab(y_actu, y_pred, rownames=['Actual'], colnames=['Predicted'])

Something like

    df_confusion.plot(kind='matrix')

It should display matrix with colormap (and a legend of this colormap)

A normalized matrix plot will be great too.

    def plot_confusion_matrix(df_confusion, title='Confusion matrix', cmap=plt.cm.gray_r):
        plt.matshow(df_confusion, cmap=cmap) # imshow
        #plt.title(title)
        plt.colorbar()
        tick_marks = np.arange(len(df_confusion.columns))
        plt.xticks(tick_marks, df_confusion.columns, rotation=45)
        plt.yticks(tick_marks, df_confusion.index)
        #plt.tight_layout()
        plt.ylabel(df_confusion.index.name)
        plt.xlabel(df_confusion.columns.name)

    plot_confusion_matrix(df_confusion)

A Pandas class to manage confusion matrix (and also binary confusion matrix) will be great.

Kind regards

**Comment by TomAugspurger** [comment]
Thanks for raising the issue. We aren't really enhancing the plotting features of pandas any more beyond the basics. I'd suggest using something like seaborn's [heatmap](http://stanford.edu/~mwaskom/software/seaborn-dev/generated/seaborn.heatmap.html) method.

![gh](https://cloud.githubusercontent.com/assets/1312546/7337764/fac4a686-ebfa-11e4-8d03-7ce40a45e075.png)

**Comment by scls19fr** [comment]
And about confusion matrix:

I did this:

    #!/usr/bin/python
    # -*- coding: utf8 -*-

    """
    Binary confusion matrix
    """

    import math
    import pandas as pd

    class BinaryConfusionMatrix:
        """Binary confusion matrix"""
    
        def __init__(self, y_actu, y_pred):
        
            if isinstance(y_actu, pd.Series):
                self.y_actu = y_actu
            else:
                self.y_actu = pd.Series(y_actu)
            
            if isinstance(y_pred, pd.Series):
                self.y_pred = y_pred
            else:
                self.y_pred = pd.Series(y_pred)
        
            self.df_confusion = pd.crosstab(y_actu, y_pred, rownames=['Actual'], colnames=['Predicted'])
            #self.df_confusion.index.name = 'Actual'
            #self.df_confusion.columns.name = 'Predicted'

            self.df_conf_norm = self.df_confusion / self.df_confusion.sum(axis=1)

        @property
        def P(self):
            """Positive"""
            return(self.df_confusion.loc[True, :].sum())
    
        @property
        def N(self):
            """Negative"""
            return(self.df_confusion.loc[False, :].sum())
    
        @property
        def TP(self):
            """
            true positive (TP)
            eqv. with hit
            """
            return(self.df_confusion.loc[True, True])
    
        @property
        def TN(self):
            """
            true negative (TN)
            eqv. with correct rejection
            """
            return(self.df_confusion.loc[False, False])
    
        @property
        def FN(self):
            """
            false negative (FN)
            eqv. with miss, Type II error
            """
            return(self.df_confusion.loc[True, False])
    
        @property
        def FP(self):
            """
            false positive (FP)
            eqv. with false alarm, Type I error
            """
            return(self.df_confusion.loc[False, True])
    
        @property
        def FPR(self):
            """
            fall-out or false positive rate (FPR)
            \mathit{FPR} = \mathit{FP} / N = \mathit{FP} / (\mathit{FP} + \mathit{TN})
            """
            #return(float(self.FP)/(self.FP + self.TN))
            return(float(self.FP) / self.N)
    
        @property
        def TPR(self):
            """
            sensitivity or true positive rate (TPR)
            eqv. with hit rate, recall
            \mathit{TPR} = \mathit{TP} / P = \mathit{TP} / (\mathit{TP}+\mathit{FN})
            """
            #return(float(self.TP) / (self.TP + self.FN))
            return(float(self.TP) / self.P)

        @property
        def sensitivity(self):
            """
            same as TPR
            """
            return(self.TPR)


        @property
        def TNR(self):
            """
            specificity (SPC) or true negative rate (TNR)
            \mathit{SPC} = \mathit{TN} / N = \mathit{TN} / (\mathit{FP} + \mathit{TN}) 
            """
            return(float(self.TN) / self.N)

        @property
        def SPC(self):
            """
            same as TNR
            """
            return(self.TNR)

        @property
        def specificity(self):
            """
            same as TNR
            """
            return(self.TNR)

        @property
        def PPV(self):
            """
            precision or positive predictive value (PPV)
            \mathit{PPV} = \mathit{TP} / (\mathit{TP} + \mathit{FP})
            """
            return(float(self.TP) / (self.TP + self.FP))

        @property
        def precision(self):
            """
            same as PPV
            """
            return(self.PPV)

        @property
        def NPV(self):
            """
            negative predictive value (NPV)
            \mathit{NPV} = \mathit{TN} / (\mathit{TN} + \mathit{FN})
            """
            return(float(self.TN) / (self.TN + self.FN))
    
        @property
        def FDR(self):
            """
            false discovery rate (FDR)
            \mathit{FDR} = \mathit{FP} / (\mathit{FP} + \mathit{TP}) = 1 - \mathit{PPV} 
            """
            return(1 - self.PPV)
    
        @property
        def FNR(self):
            """
            Miss Rate or False Negative Rate (FNR)
            \mathit{FNR} = \mathit{FN} / P = \mathit{FN} / (\mathit{FN} + \mathit{TP}) 
            """
            return(float(self.FN) / self.P)
    
        @property
        def ACC(self):
            """
            accuracy (ACC)
            \mathit{ACC} = (\mathit{TP} + \mathit{TN}) / (P + N)
            """
            return(float(self.TP + self.TN) / (self.P + self.N))
    
        @property
        def F1_score(self):
            """
            F1 score is the harmonic mean of precision and sensitivity
            \mathit{F1} = 2 \mathit{TP} / (2 \mathit{TP} + \mathit{FP} + \mathit{FN})
            """
            return(2 * float(self.TP)/(2 * self.TP + self.FP + self.FN))
    
        @property
        def MCC(self):
            """
            Matthews correlation coefficient (MCC)
            \frac{ TP \times TN - FP \times FN } {\sqrt{ (TP+FP) ( TP + FN ) ( TN + FP ) ( TN + FN ) } }
            """
            return((self.TP * self.TN - self.FP * self.FN) \
                / math.sqrt((self.TP + self.FP) * ( self.TP + self.FN ) *\
                ( self.TN + self.FP ) * ( self.TN + self.FN )))
    
        @property
        def informedness(self):
            """
            Informedness = Sensitivity + Specificity - 1
            """
            return(self.sensitivity + self.specificity - 1.0)
    
        @property
        def markedness(self):
            """
            Markedness = Precision + NPV - 1
            """
            return(self.precision + self.NPV - 1.0)
    
        def __repr__(self):
            return(self.df_confusion.__repr__())

        def __str__(self):
            return(self.df_confusion.__str__())

        def plot(self):
            import seaborn as sns
            sns.heatmap(self.df_confusion)

it might be useful
